### ISSUE TITLE
Question about the move

### ISSUE THREAD

**Issue by TFTWPhoenix** [MeteorDevelopment/meteor-client#1]
Anything different in the development process? Stuff gets weird when things change. I changed a couple things in one of my own projects and gradle broke. Anything special I'd need to do?

**Comment by MineGame159** [comment]
Nothing changed in the development, you just need to delete your old fork and fork this one

**Comment by TFTWPhoenix** [comment]
Thanks

**Comment by Reycko** [comment]
so this is the first issue

**Comment by 31a05b9c** [comment]
did not anticipate github interpreting that as an issue reference
