### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by frawwd** [MeteorDevelopment/meteor-client#1000]
Color module:

instead of the rainbow option at the end of the color selector it could be replaced with a option to sync colors with all render options for each different module and would have a customizer like :
![image](https://user-images.githubusercontent.com/76732507/121367969-a17fff00-c932-11eb-913c-f3b05225007e.png)

**Comment by Wide-Cat** [comment]
issue 1000 🎉

**Comment by seasnail8169** [comment]
Shit issue for such a nice number, this is a shit setting imo since you would never want every color to be the same.

**Comment by frawwd** [comment]
what ur dumb why would u want different colors for stuff
or at least make the rainbow option customizable 
such as: hue, saturation and lightness monk

**Comment by Wide-Cat** [comment]
I thought this meant a more detailed global settings menu for rainbow colour, not an option to sync it to all the same colour

**Comment by frawwd** [comment]
Thats what I ment and for it to replace the current rainbow option

**Comment by RickyTheRacc** [comment]
This was based why was this closed

**Comment by frawwd** [comment]
Exactly
