### ISSUE TITLE
[Bug] Meteor // OptiFabric CRASH

### ISSUE THREAD

**Issue by Winkado** [MeteorDevelopment/meteor-client#1004]
**Describe the bug**
Refuses to launch with both optifabric and meteor in mods folder.

**To Reproduce**
1. Create 1.16.5 Fabric instance
2. Put meteor, optifine and optifabric in mods folder
3. Launch game

**Expected behavior**
Launching the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/47163549/121415734-1274e600-c936-11eb-8312-32265d41aa6a.png)

**Additional context**
Newest meteor version, 1.16.5 Java Edition

**Comment by Lovecrafts-Cat** [comment]
We have said this multiple times, it is even in the info section of the website and the Discord server:
Meteor will never be compatible with Optifine, as it destroys all render modules.
Also optifine itself is badly implemented (both on forge and through optifabric). 

If you need alternatives to boost your performance we suggest these mods:
- [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium)
- [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor)
- [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium)
