### ISSUE TITLE
Killaura only 5 targets :(

### ISSUE THREAD

**Issue by Kokorska-okurka** [MeteorDevelopment/meteor-client#1008]
On a new version you can select max 5 targets in killaura to hit them in one moment. Can you please add back the feature when it can hit infinite targets at ones?

Thanks

**Comment by Epik123** [comment]
How many people are u fucking fighting at once bro

**Comment by Whop42** [comment]
this is very useful with large swarms in PVE minigames

**Comment by StormyBytes** [comment]
You can input values into the text box that are higher than the slider's max. There is no "maximum" to this text box input in killaura, you can just set this to a very high value (say, 10000).

Close this issue.
