### ISSUE TITLE
Anti Magma/Fire/Pressure Plate

### ISSUE THREAD

**Issue by Kokorska-okurka** [MeteorDevelopment/meteor-client#1009]
**Describe the feature**
Hey, in Impact client i've found Anti Hazard feature. It prevents from walking into fire, taking damage from magma block, steping on pressure plate etc... Can you please add it? It would be very nice, if it was here and if i don't need to use meteor and impact together 😖.

**Screenshots**
No screens.

**Additional info**
You can look to imapact code, there you'll see how to do it 😉

**Comment by C10udburst** [comment]
> You can look to imapact code, there you'll see how to do it 😉

What? Isn't Impact closed source?

**Comment by Z3r0ut** [comment]
https://github.com/ImpactDevelopment Although i dont see the source code there.

**Comment by Z3r0ut** [comment]
Btw, if you can add that feature, please make it so we can toggle it individually, i mean so that we can activate anti fire and anti lava, but still be able to use pressure plates, or the other way around, damage from fire and lava blocks, but not able to aktivate pressure plates

**Comment by Kokorska-okurka** [comment]
you can use www.decompiler.com to Impact.jar *smart*

**Comment by Kokorska-okurka** [comment]
> https://github.com/ImpactDevelopment Although i dont see the source code there.

**Comment by seasnail8169** [comment]
Firstly, thats not how obfuscation works.
Secondly this just doesn't work in recent versions
