### ISSUE TITLE
Jesus fly bug

### ISSUE THREAD

**Issue by Kokorska-okurka** [MeteorDevelopment/meteor-client#1010]
**Describe the bug**
Jesus for lava or water not working when flying. In version lower than the previous version it worked. Can you add a option to Jesus _Work when flying_ ? Because of this, i burned many times. Thanks
**To Reproduce**
1. Turn on flight
2. Turn on Jesus
3. Fly to lava
4. See what it does

**Expected behavior**
I would like, if when i flew to lava it will stop me from falling into it. I would like to work also if i flew into diagonal lava, not only horizontal

**Screenshots**
No screens

**Additional context**
No additional context

**Comment by seasnail8169** [comment]
bruh thats just retarded, flight gives you complete control of your player, just fly over the liquid
