### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Intoprelised** [MeteorDevelopment/meteor-client#1011]
**Describe the bug**
When enabling freecam on 1.17 your game crashes.

**To Reproduce**
Click on freecam (turn it on)

**Expected behavior**
Freecam to work properly and not crash.

**Screenshots**

**Additional context**
I am using meteore test build 0.4.4 build 1018

**Comment by Wide-Cat** [comment]
I can't reproduce this. Can you send the crash report please?

**Comment by CountBleck** [comment]
First of all, 1.17 is unstable. Second of all, what other modules are you using, specifically Tracers? Tracers caused a crash when I enabled Freecam since it tried to draw a tracer to me.

**Comment by Wide-Cat** [comment]
does this still crash you on the latest build?

**Comment by seasnail8169** [comment]
@Intoprelised
