### ISSUE TITLE
Auto32k

### ISSUE THREAD

**Issue by cmk-Destro** [MeteorDevelopment/meteor-client#1020]
Auto use 32k weapons 
Bypass anti 32k plugin by placing an hopper or a dispenser

**Comment by StormyBytes** [comment]
Meteor had it, but was removed.

**Comment by cmk-Destro** [comment]
Yea they can just re-add it

**Comment by cmk-Destro** [comment]
No comment @seasnail8169 ?

**Comment by seasnail8169** [comment]
comment

**Comment by RickyTheRacc** [comment]
Cope!

**Comment by cmk-Destro** [comment]
Just re-add it

**Comment by supakeks** [comment]
No, illegalstack patched the dispenser bypass so long ago, it's not even worth making it a module.

Perhaps making it into an addon like the book dupe and auto mount bypass dupe?

**Comment by HENRYMARTIN5** [comment]
YES! Please make an addon like that @seasnail8169.

**Comment by seasnail8169** [comment]
cant be bothered

**Comment by a-couple-objects** [comment]
clothes
