### ISSUE TITLE
[Suggestion] Miscellaneous Improvements 

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1023]
**Fullbright Radius:**
A range slider for fullbright, which would only illuminate blocks within a set range of the player. Would be nice to still have it without having your eyes strain from *everything* being fullbright.

**Potion Hud Improvement:**
Add the ability to choose what effects display in the potion effects hud, would be nice to hide things like haste and such. 

**Handview:**
Add an option to lower the shield's model, and a drop-down menu for eating animations: vanilla, no eating, and snap, where the food instantly snaps up to then eating position.

**Search:**
Instead of showing blocks with updated configs at the top of the list with an asterisk, show them on a second half of the list like other modules.

**Rich Presence:**
Unsure if this is actually possible, but maybe add an option to choose the image displayed in Discord?

**XP Thrower:**
Add an option to toggle on at a certain durability and toggle off at a certain durability, would be useful for pvp in case you don't see your armor about to break. Also maybe merge this into auto mend since they sort of do the same thing?

**Comment by seasnail8169** [comment]
Please make separate issues for separate issues

**Comment by RickyTheRacc** [comment]
Soz
