### ISSUE TITLE
[Bug] nether ambiance / skybox colour in dev build 0.4.4-1023

### ISSUE THREAD

**Issue by 0sleep** [MeteorDevelopment/meteor-client#1024]
**Describe the bug**
while in the nether pressing tab shows / hides nether ambiance (red background)

**To Reproduce**
1. be in the nether
2. press [TAB]
3. observe background color change (red<->black)

**Expected behavior**
pressing tab does not change skybox colour

**Additional context**
DEV BUILD! (1023), fabric 1.17, no additional addons

**Comment by 0sleep** [comment]
I assume this is the same issue as #1026

**Comment by seasnail8169** [comment]
This was fixed
