### ISSUE TITLE
[Bug] 1.17 dev build 0.4.4-1023 crashes when attempting to join realms (w/ recording)

### ISSUE THREAD

**Issue by Aquertyon** [MeteorDevelopment/meteor-client#1025]
**Describe the bug**
When you try to join anyones realm, the game crashes

**To Reproduce**
Click on Minecraft Realms
Try to join anybody's realm
Game crashes

**Expected behavior**
I expected to be able to join my realm and play on it.

(Recording) 
https://user-images.githubusercontent.com/85746440/121757855-f9fafc00-caec-11eb-9ce8-3c26eaf32e7b.mp4

**Comment by a-couple-objects** [comment]
post log not crash

**Comment by seasnail8169** [comment]
Nothing to do with realms, just a module that hasn't been fixed yet
