### ISSUE TITLE
Loading issues with the sky (Makes half the sky black) also when using F1 or going into 3rd person the whole screen turns black. Type .panic in chat to fix.

### ISSUE THREAD

**Issue by Spicymang04** [MeteorDevelopment/meteor-client#1026]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by StormyBytes** [comment]
Titles are meant to be clear and concise.

**Comment by seasnail8169** [comment]
this was fixed
