### ISSUE TITLE
[Bug] Glow Squid & Axolotl from entity selector

### ISSUE THREAD

**Issue by C10udburst** [MeteorDevelopment/meteor-client#1027]
**Describe the bug**
Glow Squid & Axolotl missing from `EntityTypeListSetting`

**Screenshots**

![image](https://user-images.githubusercontent.com/18114966/121773932-8229e180-cb7f-11eb-85c9-fa38384deb0d.png)

**Additional context**
- meteor-client-0.0.4-1023
- meteor-rejects ![:swag:](https://cdn.discordapp.com/emojis/809807864365318225.png?v=1&size=40)

**Comment by JackRedstonia** [comment]
Don't you love it when Mojang pulls a `UNDERGROUND_WATER_CREATURE` on you
