### ISSUE TITLE
[Bug] Missing tooltips

### ISSUE THREAD

**Issue by C10udburst** [MeteorDevelopment/meteor-client#1028]
**Describe the bug**
Module tooltips display missaligned

**To Reproduce**
1. Press <kbd>right shift</kbd>
2. Hover over any module
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/18114966/121774093-c79ade80-cb80-11eb-8f25-d1c61c7f6f42.png)

**Additional context**
meteor-client-0.0.4-1023
amd gpu btw

**Comment by seasnail8169** [comment]
This was fixed
