### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Pinguks7** [MeteorDevelopment/meteor-client#1032]
Meteor Client GUI text not rendering.

1. Launch Minecraft.
2. Join a Multiplayer Server/ Single Player World
3. Press the right shift to open the meteor client GUI.
4. See error.
5. (It only happens in a server/world or after entering a server/world)

I expected to be able to read the displayed text, to toggle or configure certain utilities.

Before entering a Server/World:

![Captura de Pantalla 2021-06-12 a la(s) 16 07 41](https://user-images.githubusercontent.com/84537090/121789086-81517980-cb98-11eb-8eee-99df1fd8235f.png)

In a Server/World:

![Captura de Pantalla 2021-06-12 a la(s) 16 08 26](https://user-images.githubusercontent.com/84537090/121789096-93331c80-cb98-11eb-893f-7c700d4c9494.png)

After Entering and exiting a Server/World:

![Captura de Pantalla 2021-06-12 a la(s) 16 08 37](https://user-images.githubusercontent.com/84537090/121789101-a0e8a200-cb98-11eb-824a-8ab2c73e7094.png)

Minecraft 1.17 - Fabric Loader 0.11.3 - Meteor build # 1023 - Mods Installed: "Bedrockify" "EasierVillagerTrading" "Fabric API" "Krypton" "LambDynamicLights" "Lithium" "ModMenu" "Simple RPC" "Sodium"

**Comment by supakeks** [comment]
Does this issue happen without sodium?

**Comment by Pinguks7** [comment]
Yes

**Comment by seasnail8169** [comment]
This was fixed im pretty sure @Pinguks7 can you try latest dev build

**Comment by Pinguks7** [comment]
Ill try

**Comment by Pinguks7** [comment]
Same bug on latest build ): (Build # 1039)

![Captura de Pantalla 2021-06-14 a la(s) 09 51 04](https://user-images.githubusercontent.com/84537090/121912403-2cc41080-ccf6-11eb-8858-26c9769f75ad.png)

**Comment by seasnail8169** [comment]
can you remove all mods and try again (just meteor)

**Comment by Pinguks7** [comment]
thx, fixed (:
