### ISSUE TITLE
[Suggestion] Add a Feture To Better Chat

### ISSUE THREAD

**Issue by DrDuggi** [MeteorDevelopment/meteor-client#1039]
**Describe the feature**
The Feuture should be if you type on the and it says METEOR Or METEOR ON CRACK

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/62102560/121821798-a2e75980-cc9b-11eb-8acc-a1e930ac7d52.png)

**Additional info**
Okay, The Screenshot should help

**Comment by Laar-u** [comment]
what the fuck do you mean

**Comment by seasnail8169** [comment]
Literally just suffix, its already a feature in betterchat

**Comment by RickyTheRacc** [comment]
Inb4 this gets closed, open the client before you make suggestions retard

**Comment by Wide-Cat** [comment]
@seasnail8169  close this then lmao

**Comment by seasnail8169** [comment]
oh yeah :trollface:
