### ISSUE TITLE
Duping

### ISSUE THREAD

**Issue by VyommBansal** [MeteorDevelopment/meteor-client#1042]
Hello, I started using meteor client but I can not find the duping option I cannot find book dupe or the automount bypass dupe I am playing on the 1.16.5 version what should i do?

**Comment by StormyBytes** [comment]
Bookdupe addon: https://github.com/MeteorDevelopment/meteor-mbd-addon/releases/latest
MBD addon: https://github.com/MeteorDevelopment/meteor-mbd-addon/releases/latest
Place the addon jars in your mod folder along with meteor.

Also, those dupes are patched in 95% of servers.
