### ISSUE TITLE
Realms not working

### ISSUE THREAD

**Issue by InlandPheonix90** [MeteorDevelopment/meteor-client#1046]
when I get on mc and go to a realm with the newest dev build it never loads, I try without dev build and it works

**To Reproduce**
1. Go to minecraft
2. Click on realms
3. Scroll down to any realm and join

**Expected behavior**
i expect the realm to load

**Screenshots**
![Screenshot 2021-06-14 171826](https://user-images.githubusercontent.com/85906409/121960794-9400b580-cd34-11eb-8e71-4f50cb159f94.png)

**Additional context**
1.17 dev build 1049

**Comment by seasnail8169** [comment]
send your `latest.log` file from `.minecraft/logs` after trying to connect to a realm

**Comment by RedCarlos26** [comment]
@InlandPheonix90 is this still happening?
