### ISSUE TITLE
Crouch obsidian[Suggestion]

### ISSUE THREAD

**Issue by Epik123** [MeteorDevelopment/meteor-client#1047]
**Describe the feature**
Bassicly when u crouch it will place 4 obsidian block around u in a plus shape with u in the middle and if applicable it will also place 1 below u

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
It's in catalyst client for 1.12 and it would be dope to also be in meteor

**Comment by seasnail8169** [comment]
> surround

**Comment by RickyTheRacc** [comment]
Retard alert!

**Comment by Epik123** [comment]
> Retard alert!

Yes I have retardation
