### ISSUE TITLE
Nofall and flight are broke[Bug] 

### ISSUE THREAD

**Issue by Epik123** [MeteorDevelopment/meteor-client#1048]
**Describe the bug**

**To Reproduce**
1. No fall packet mode
2. It doesnt block the fall damage
2. Flight with antikick packet mode 
3. The flight repeat drops u as if u were on normal mode
4. 

**Expected behavior**
It to block fall damage and fly to keep u level

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc). 1.17 mc
Dev build 1052

**Comment by Epik123** [comment]
It was fixed in a newer dev build

**Comment by C10udburst** [comment]
> It was fixed in a newer dev build

:trollface:
