### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by 31173-commit** [MeteorDevelopment/meteor-client#1049]
uhh idk it crashed on launch

![image](https://user-images.githubusercontent.com/78868716/122007448-3ada6580-cdb8-11eb-8350-ebf52b9cfd48.png)

meteor version: 0.4.3-864,i don't have any other mod in mods folder

**Comment by mihirgarg01** [comment]
Yeah I am having the same issue, its a certain module doing that, I just turned off all the modules, joined the server, then turned on the things I needed. I did get ~ the same error.

**Comment by StormyBytes** [comment]
That is **not** the crash log

**Comment by MineGame159** [comment]
Very old Meteor version, update and if it still happends then make a bug report.

**Comment by 31173-commit** [comment]
> Very old Meteor version, update and if it still happends then make a bug report.

it's the newer version of 1.16.5 meteor
