### ISSUE TITLE
[Bug] Crashing Problems

### ISSUE THREAD

**Issue by JayH4x** [MeteorDevelopment/meteor-client#1050]
My client is crashing
this happens when i press f5, spawn a fake player and just randomly.
ive tested on other clients besides meteor and this bug does not happen.

the top of the crash report says:
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffca067bfa3, pid=17432, tid=5312
#
# JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [atio6axx.dll+0x8dbfa3]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by timoreo22** [comment]
Seems like the AMD graphics drivers crash, what is your meteor version ?

**Comment by JayH4x** [comment]
im using meteor-client-0.4.4

**Comment by timoreo22** [comment]
Yep it's not fixed there yet, use 4.3 or the dev version (found on the discord) or just avoid using ESPs

**Comment by JayH4x** [comment]
ok thanks

**Comment by JayH4x** [comment]
hey also i went to download the 4.3 but it says "Artifact not found" on the website

**Comment by StormyBytes** [comment]
Send the **actual** crash report in `.minecraft/crash-reports`
