### ISSUE TITLE
[Bug] Fake player crashes the game.

### ISSUE THREAD

**Issue by NIGHTMARIO** [MeteorDevelopment/meteor-client#1051]
**Describe the bug**
The fake player module crashes the game in meteor version 0.4.4 build #1052

**To Reproduce**
1. Spawn in the world.
2. Spawn a fake player with any settings. through GUI or .fakeplayer.
3. The game crashes.

**Expected behavior**
Fake Player should spawn with the specified settings.

**Screenshots**

**Additional context**
Minecraft version: 1.17
Meteor version: 0.4.4 build #1052

**Comment by seasnail8169** [comment]
Please send the log of the crash found in `.minecraft/crash-reports`

**Comment by seasnail8169** [comment]
oops

**Comment by NIGHTMARIO** [comment]
[crash-2021-06-20_08.50.01-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6681669/crash-2021-06-20_08.50.01-client.txt)
![Screen_from_not_enough_crashes_mod](https://user-images.githubusercontent.com/84377831/122660905-eadb1480-d1a4-11eb-9185-659418bf68e9.png)
1st file is the crash report and the photo is the screen displayed from the "Not Enough Crashes" mod.

**Comment by NIGHTMARIO** [comment]
This issue is now solved in the new dev-builds.
