### ISSUE TITLE
[Bug] Meteor Client Refusing To Connect To A Server

### ISSUE THREAD

**Issue by mihirgarg01** [MeteorDevelopment/meteor-client#1053]
**Describe the bug**
This bug happens with v0.4.4 build #1055. The issue is that a certain not-known module is preventing me from any single player world or server. When joining a server, the screen gets stuck on encrypting, and will not move past.

**To Reproduce**
1. Launch Minecraft (Using Stable MultiMC) with meteor client v0.4.4 build #1055
2. Click on Multiplayer
3. Join A Server Of Your Choice.
4. Notice Stuck On Encrypting.

**Expected behavior**
Should join the server without being stuck on encrypting step.

**Screenshots**
![image](https://user-images.githubusercontent.com/46659408/122111737-f14c4380-cdd4-11eb-818a-75f987190468.png)

**Additional context**
Log: [https://paste.ee/p/p3Tdc](https://paste.ee/p/p3Tdc)
Crash Log: [https://paste.ee/p/FP4pi](https://paste.ee/p/FP4pi)
OS: Arch Linux v5.12.9-arch1-1 w/ GNOME 40.2
Java: Java-16-jdk
MultiMC: MultiMC 5 - Version 0.6.12
Active Mods:
```
  [✔️] RoughlyEnoughItems-6.0.249-alpha-fabric
  [✔️] TRansliterationLib-1.1.0
  [❌] appleskin-mc1.16-fabric-1.0.11.jar (disabled)
  [✔️] architectury-2.0.8-fabric
  [❌] baritone-api-fabric-1.6.3.jar (disabled)
  [✔️] fabric-api-0.35.1+1.17
  [❌] hydrogen-fabric-mc1.16.5-0.2.jar (disabled)
  [✔️] litematica-fabric-1.17.0-0.0.0-dev.20210608.211719
  [✔️] lithium-fabric-mc1.17-0.7.0
  [✔️] lock_minecart_view-for-MC1.17-rc1-1.2.1
  [✔️] malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
  [✔️] meteor-client-0.4.4-1055
  [✔️] modmenu-2.0.2
  [✔️] notenoughanimations-1.3.0
  [❌] notenoughcrashes-3.3.0+1.17-fabric.jar (disabled)
  [❌] phosphor-fabric-mc1.16.3-0.7.2+build.12.jar (disabled)
  [❌] sodium-fabric-mc1.16.3-0.1.0.jar (disabled)
```
Active Modules (The Issue Seems To Be Originating From A Misbehaving Module)
```
-- Meteor Client --
Version: 0.4.3

[Combat]:
Arrow Dodge (arrow-dodge)

[Player]:
Anti Hunger (anti-hunger)
Auto Eat (auto-eat)
Auto Respawn (auto-respawn)
Auto Tool (auto-tool)
Death Position (death-position)
No Rotate (no-rotate)
Portals (portals)
Potion Spoof (potion-spoof)

[Movement]:
Elytra Fly (elytra-fly)
Flight (flight)
No Fall (no-fall)
No Slow (no-slow)
Step (step)

[Render]:
Better Tooltips (better-tooltips)
Fullbright (fullbright)
HUD (HUD)
Hand View (hand-view)
Hole Esp (hole-esp)
Search (search)
Wall Hack (wall-hack)

[World]:
Anti Cactus (anti-cactus)
Auto Steal (auto-steal)
Enderman Look (enderman-look)

[Misc]:
Anti Packet Kick (anti-packet-kick)
Auto Reconnect (auto-reconnect)
Better Tab (better-tab)
Discord Presence (discord-presence)
```
Thanks for any help! Meteor is an awesome client!

**Comment by seasnail8169** [comment]
Firstly, you are using really old meteor, secondly this issue has literally nothing to do with meteor anyway.

**Comment by mihirgarg01** [comment]
Alr ty anyways

**Comment by mihirgarg01** [comment]
Found the issue, auto log and auto totem were causing the crash. Also, the meteor version I was using was a dev build from the discord server....

**Comment by seasnail8169** [comment]
known issue
