### ISSUE TITLE
[Suggestion] Visual Range Buffer (prevents spam)

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1062]
**Describe the feature**
My suggestion is rather complicated. I want visual range to only work when I'm in areas with little players, eg travelling or at my base. However, when I go to /spawn my chat is flooded with dozens of visual range messages.
I suggest that instead of instantly alerting the user when it finds a player, it'll wait two seconds to see if it finds more than one player. If it finds 5+ players, it will cancel and not alert the player whatsoever.

**Additional info**
Yes, this is niche, but it's a feature that would be beneficial to me and many other players too. Obviously, all the settings would be configurable such as how many players to cancel message and how long to wait.

**Comment by seasnail8169** [comment]
Just turn it off when you go to spawn, it makes no sense to only show some of the people who enter visual range since the point is to know exactly who
