### ISSUE TITLE
[Suggestion] Better spam delay

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1063]
**Describe the feature**
Improve the delay setting of 'spam'. It doesn't allow for decimals, it only allows integers which is quite annoying when trying to configure it to match the antispam limit as closely as possible. 
Either expand it so instead of running via seconds, run via ticks. (And adjust the slider to accomodate for higher values obviously) Or allow decimals.

**Comment by seasnail8169** [comment]
7d4c11b
