### ISSUE TITLE
[Suggestion] Container viewer should display anything that can hold items.

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1064]
**Describe the bug**
Container viewer does not show all items containing {Item:} tag.

**To Reproduce**
1. Hold furnace (or dispenser, hopper, campfire, etc) with items inside.
2. Observe how it does not appear on the HUD.

**Expected behavior**
Shows up in HUD like how it does if you hover over the item with bettertooltips enabled.

**Additional context**
Dev build 1061 (most recent)

**Comment by seasnail8169** [comment]
This isn't a bug, just something that has not been implemented.

**Comment by seasnail8169** [comment]
bruh

**Comment by RedCarlos26** [comment]
Bruhhhh

**Comment by TheRedHippo** [comment]
Additionally, it would be nice if it only showed the container viewer when it detects the Item: tag. Showing an empty container when holding any container is annoying if anything. Maybe just only always show when holding a shulker box.

**Comment by seasnail8169** [comment]
thats what it does?

**Comment by TheRedHippo** [comment]
No. Currently, if you hold a completely normal chest- devoid of any NBT tags, container viewer WILL show up with an empty container.
I'm suggesting that container viewer only shows if there are items inside OR it's a shulker box.

**Comment by seasnail8169** [comment]
its a setting im pretty sure

**Comment by seasnail8169** [comment]
Its not showing an empty container, its showing your enderchest

**Comment by TheRedHippo** [comment]
I have that disabled

**Comment by seasnail8169** [comment]
it doesn't
