### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Intoprelised** [MeteorDevelopment/meteor-client#1066]
**Describe the feature**
Auto wither, when u turn it on it detects if u have soul sand and wither skulls in ur inventory then places them in the format of how to build a wither

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
This would be useful for mass griefings

**Comment by StormyBytes** [comment]
Check before you make a suggestion/bug report. Someone has already suggested this (#516)
