### ISSUE TITLE
[Bug] Trail has blank particles that crash the game.

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1073]
**Describe the bug**
Particle list in Trail and Particle blocker have blank entries. Adding one of these particles to the trail menu with it enabled will crash your game.

**To Reproduce**
1. Open trail module
2. Select a particle without a name
3. Enable trail
4. Game crashes

**Expected behavior**
The blank particles don't show up at all (or show what they're supposed to, idk what they are)

**Screenshots**
![image](https://user-images.githubusercontent.com/67818307/122540571-1efeea00-d06c-11eb-8cbc-4d72cd0227de.png)

**Additional context**
Dev build 1068

**Comment by MineGame159** [comment]
Fixed in b31ed371df4bed6a1f906d724a0121310692de9f
