### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BlockTroller** [MeteorDevelopment/meteor-client#1078]
When I use Jesus on top of lava, and start Flight, I will fall in the lava for some reason. This has caused many deaths and sad moments. I don't know if it's just me.

To Reproduce
1. Go on top of lava with Jesus on
2. Turn on Flight
3. See error and also burn to death

Expected behavior
Flying normally from lava

Screenshots
I have no screenshots

Additional context
Meteor 0.4.4, Minecraft 1.16.5 and no other mods.

**Comment by mvrozanti** [comment]
Not sure if it's related, but I noticed a similar behavior using flight only. I'm able to reproduce it by just flying and hitting the fly hotkey repeatedly; it will sometimes change direction, of flight even though I'm pressing the forward key. It does not change yaw or pitch.

**Comment by seasnail8169** [comment]
This is not a bug, you are literally just standing on lava and expecting not to burn, its just how minecraft works. If you dont want to burn, dont stand on lava *or* jump before you enable flight.
