### ISSUE TITLE
[Bug] Handview

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1080]
**Describe the bug**
Break ur arms when you eat

**To Reproduce**
Enable handview and eat anything

**Expected behavior**
Not break your arms

**Screenshots**
https://streamable.com/mudtxx

**Comment by seasnail8169** [comment]
As i said, not a bug

**Comment by seasnail8169** [comment]
🐒

**Comment by seasnail8169** [comment]
#1081
