### ISSUE TITLE
[Suggestion] Scale nametags relative to distance from the entity.

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#1082]
I think that nametags should grow bigger/smaller for how close/far away you are from an entity. Right now, the nametag size is constant, and basically the issue is that when your far away and have many players in your view, the nametags are very obtrusive, but when you close the distance, the nametags are very tiny relative to the player and I cant see them easily while the player is moving around. If not all people like this, the feature could be an toggleable option.

![Screenshot from 2021-06-18 17-03-45](https://user-images.githubusercontent.com/29315797/122619944-4eefc280-d057-11eb-9ddc-6ba46b0e05ba.png)
![Screenshot from 2021-06-18 17-04-01](https://user-images.githubusercontent.com/29315797/122619948-50b98600-d057-11eb-8a53-9aee6d9a11a5.png)

**Comment by BowenGIT** [comment]
The way this should be implemented is not exactly how I described, but basically the main issue is when you are too close to the player the nametag is tiny. Use Inertias nametags for reference.

**Comment by RedCarlos26** [comment]
I agree with you, when you are close the nametags are too small

**Comment by cxzlw** [comment]
https://github.com/MeteorDevelopment/meteor-client/issues/847
