### ISSUE TITLE
[Suggestion] Add TargetStrafe

### ISSUE THREAD

**Issue by mokeWe** [MeteorDevelopment/meteor-client#1084]
**Describe the feature **
An option within kill aura, similar to the random teleport feature, but it will strafe around the target when activated. 

**Screenshots**
As demonstrated in this video: https://youtu.be/JehRYvtrpkM

**Comment by Epik123** [comment]
Yes

**Comment by seasnail8169** [comment]
Imo this only has a use for cheating

**Comment by Epik123** [comment]
> Imo this only has a use for cheating

And for trolling 
:trollface:
