### ISSUE TITLE
[Bug] Autotool Bug

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1087]
**Describe the bug**
Enchanted items will be selected before unenchanted items, even if it's the wrong tool for the block. Ex: with an enchanted axe and a normal pick in your hotbar, trying to mine stone items will switch to the axe because it is enchanted.

**To Reproduce**
1. Enable Autotool
2. Give yourself two different tools, one with enchants
3. Try to mine a block type that matches with the unenchanted tool

**Expected behavior**
The module should select the unenchanted item which mines the block faster

**Comment by StormyBytes** [comment]
This is probably a mistake in the scoring system.
