### ISSUE TITLE
a module that shows new chunks

### ISSUE THREAD

**Issue by ollyw123** [MeteorDevelopment/meteor-client#1088]
**Describe the feature**
a module that shows new rendered chunks this will be useful for base finding

**Screenshots**
https://youtu.be/lkwm4lgC8Eg 3:31 in video

**Additional info**
I believe this would be a great feature to add to the client as it isn't on many other clients

**Comment by Wide-Cat** [comment]
They way newchunks worked on 1.12.2 servers was a bug in 1.12 spigot, that was patched immediately in the next version. It can be made ([case in point](https://github.com/C10udburst/meteor-rejects/blob/master/src/main/java/cloudburst/rejects/modules/NewChunks.java)) but theres a fair margin for error

**Comment by ollyw123** [comment]
If its possible i say it would be worth it

It would give meteor such qn advantage over other clients
