### ISSUE TITLE
[Bug] Xray doesn't work in 1.17

### ISSUE THREAD

**Issue by LeSnake04** [MeteorDevelopment/meteor-client#1089]
**Describe the bug**

**To Reproduce**
1. Enable xray

**Expected behavior**
Only show selected block

**Current behavior**
Shows all blocks

**Additional context**
Minecraft 1.17
Compiled version (06/20/21)

**Comment by seasnail8169** [comment]
are you using sodium

**Comment by LeSnake04** [comment]
@seasnail8169 yes

**Comment by seasnail8169** [comment]
Thats why, given that sodium is not stable for 1.17 we wont have any compatibility fixes until it can be safely included in meteor as it was before.

**Comment by LeSnake04** [comment]
Ok. If the issue persists when the stable release comes out, i will inform you
