### ISSUE TITLE
No fall does not work after 0.4.4 build#1090[Bug]

### ISSUE THREAD

**Issue by fatasduckling** [MeteorDevelopment/meteor-client#1095]
**Describe the bug**
i still die of fall damage even if no fall is turned on

**To Reproduce**
1. just fall and you will still take fall damage
**Expected behavior**
i expect not to take fall damage at all

**Additional context**
meteor 0.4.4 build#1090, 1.17

**Comment by RickyTheRacc** [comment]
Cope!

**Comment by seasnail8169** [comment]
Fixed in 63e5d04
