### ISSUE TITLE
Add Macro Keybinding [Suggestion]

### ISSUE THREAD

**Issue by Frosty9999** [MeteorDevelopment/meteor-client#1096]
**Describe the feature**

The title is fairly self explanatory, would be a huge feature to this client!

**Comment by seasnail8169** [comment]
what even

**Comment by MineGame159** [comment]
What?

**Comment by RickyTheRacc** [comment]
Literally macros tab at the top of the screen in clickgui, swear to god half these brainlets don't even use the client before they make suggestions
