### ISSUE TITLE
[Suggestion] Elytra packet stabilisation + Speednuker + Auto log parameter

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1100]
Hey,
Elytra packet on the latest version is not very usable, since the player vision shakes a lot. Implementing Inertia's elytra packet would be very cool (infinite durability), and adding the slow fall to not get kicked would be awesome.

Nuking on meteor is slow, and could have an option "speednuker", for mining multiple instaminable blocks at once (you can take wurst's speednuker as an example)

Autolog parameter
It would be very useful to be logged off when going over/under a certain y level:
For example travelling under the nether could be safer for servers that aren't allowing the nether roof

**Comment by RickyTheRacc** [comment]
1. No
2. No
3. Just don't go on the nether roof if you don't want to go on the nether roof

**Comment by tomtom5968** [comment]
Just don't go on the nether roof if you don't want to go on the nether roof // bruh it's just not allowed, this is why i travel under the nether and suggesting this feature

**Comment by BowenGIT** [comment]
These suggestions are all good, especially the nuker one. I dont know what yall are talking about

**Comment by tomtom5968** [comment]
> These suggestions are all good, especially the nuker one. I dont know what yall are talking about

The MaxBlockPerTick option has just been added :)

**Comment by tomtom5968** [comment]
This is so good, it was the only reason I was stuck with inertia + wurst since meteor isn't compatible with wurst. Thanks the devs
