### ISSUE TITLE
[Suggestion] Hit Reach read the descrip

### ISSUE THREAD

**Issue by Epik123** [MeteorDevelopment/meteor-client#1103]
**Describe the feature**
So it could be 2 things at once number 1 improve the reach of ka to like 12 if that's possible

2 make a hit reach module that let's u attack from further away say like 10-12 blocks max

Reason is I feel like it would help on a anarchy server I play on to have a further reach then others

**Comment by necrophili** [comment]
Monkiest comment my eyes have encountered

**Comment by Epik123** [comment]
> Monkiest comment my eyes have encountered

🙈

**Comment by RickyTheRacc** [comment]
most based comment

**Comment by a-couple-objects** [comment]
TPreach when
