### ISSUE TITLE
[Bug] Flight module bug

### ISSUE THREAD

**Issue by NIGHTMARIO** [MeteorDevelopment/meteor-client#1104]
**Describe the bug**
It's a big bug that has existed through I guess from meteor build #1082. I'm sorry that I'm very late to report this.

**To Reproduce**
1. Load the world.
2. Go in survival game mode.
3. Turn flight on.
4. Fly for some time.
5. You will notice that your character is moving in other directions than what keys you pressed.
6. Press f5 and see that you were seeing in the front while your character head is turned to the side. (it can be both right and left)
![javaw_9BPpe6GYVZ](https://user-images.githubusercontent.com/84377831/123101941-41ba4580-d454-11eb-82ff-2f40b16f9197.png)

**Expected behavior**
The character can fly properly.

**Screenshots**
The screenshot is given in the "To reproduce" part.

**Additional context**
Minecraft version: 1.17
Meteor version: Applicable through all dev-builds for 1.17 probably from #1082, I haven't tried this on older builds. It still exists in the latest builds which is meteor 1106 while I'm writing this. And this bug didn't exist in any 1.16 versions.
All the mods in use: Fabric API
                                 Architectury
                                 Cloth config
                                 Multiconnect
                                 Roughly enough items   (non of the enabled mods should affect character movement)

Meteor modules enabled: Flight
                                          Fullbright

**Comment by StormyBytes** [comment]
From my testing it only happens in velocity mode, not in abilities mode.
It also happens only after sneaking, other movements wont start the bug.

And to stop it, you have to turn off flight, land on the ground, then turn it back on again.
