### ISSUE TITLE
[Suggestion] Create a "legit" meteor (Maybe called Comet?)

### ISSUE THREAD

**Issue by Redo11** [MeteorDevelopment/meteor-client#1105]
At this point, meteor as a client combines so many quality of life features, it would make sense, to strip it out of cheats and contribute these features to the entire modding community, either by packaging them into several mods OR creating a stripped down version of Meteor.

I would gladly hear your opinion about this topic, as I see Meteor really useful in gameplay, outside of anarchy and cheating servers.

**Comment by MineGame159** [comment]
Just don't enable them

**Comment by MineGame159** [comment]
Well actually there is a very distant idea / plan that might do something similiar

**Comment by Epik123** [comment]
> At this point, meteor as a client combines so many quality of life features, it would make sense, to strip it out of cheats and contribute these features to the entire modding community, either by packaging them into several mods OR creating a stripped down version of Meteor.
> 
> I would gladly hear your opinion about this topic, as I see Meteor really useful in gameplay, outside of anarchy and cheating servers.

Idk man seems kinda sus

**Comment by RickyTheRacc** [comment]
Aka make a legit client so you can cheat in servers with anticheatd

**Comment by Redo11** [comment]
@MineGame159 Well, just disabling cheats, doesn't make a case, why I do have them installed. I want to be legit, having full on hacked client isn't.
@RickyTheRacc Kinda yes, kinda no, as it's not only for servers with anticheat, but for servers in general. I mean, I would accept an unfair advantage, if it would be in a form of quality of life improvement, not straight out killaura. 

I am thinking of something in-between anticheat client(lunar, badlion etc) and a cheat client, living on a gray edge. Of course, you can disable the features, that go too far, but try explaining that to an admin compared to killaura and esp.

This kind of mod would also be perfect for a mod pack, as the quality of life for users is improved and it is fair for everyone.

Of course it's your mod and you do what you think will be right. I am just sharing my though process.
It might just be a thing worth considering, especially when clients like badlion and lunar are on the rise.

**Comment by Starmania** [comment]
If Meteor is successfully divided in multiple part (like in branch 5c261092ee6c922d5021b0623a35480b0a06b01b), it would just be a module to remove or not

**Comment by ThebestkillerTBK** [comment]
when meteor becomes an addon

**Comment by Starmania** [comment]
Oh yea
