### ISSUE TITLE
[Suggestion] Make .locate work with a given seed 

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1107]
This would be so useful, when searching for structures/biomes (no op permissions needed)

**Comment by C10udburst** [comment]
Duplicate of #980

**Comment by tomtom5968** [comment]
bruh so i guess it will not be added... rip

**Comment by StormyBytes** [comment]
@tomtom5968 an issue being a duplicate doesn't necessarily mean it wont be added

**Comment by tomtom5968** [comment]
> @tomtom5968 an issue being a duplicate doesn't necessarily mean it wont be added

it has been multiple weeks since the first suggestion, you may be right but the longer a feature isn't added the more it will never appear

**Comment by TyraVex** [comment]
Wow thanks it's working well
