### ISSUE TITLE
I still receive fall damage when landing from fly, even with nofall on.

### ISSUE THREAD

**Issue by Spicymang04** [MeteorDevelopment/meteor-client#1110]
**Describe the bug**
When flying (even with nofall) when trying to land you take damage when not landing in water or the sort.

**To Reproduce**
1. Fly around in survival and try to land.

**Expected behavior**
You will take damage and without armor you will most likely die.

**Screenshots**

**Additional context**
Meteor 4.4 1108
Litematica

**Comment by NightMite** [comment]
This happens on a server or on singleplayer?

**Comment by D3V1LC0D3R** [comment]
seems like a duplicate of #1097
