### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Robotninja100** [MeteorDevelopment/meteor-client#1116]
**Describe the feature**
A clear and concise description of what feature/change is.
auto build like schematic

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.
![image](https://user-images.githubusercontent.com/86416762/123268694-90241e80-d4fe-11eb-8a89-76db812b7ca5.png)
 that with autobuild
**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
Other mods
