### ISSUE TITLE
[Suggestion] No Fall and Elytra Fly

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1117]
Hello,
Enabling no fall is very laggy on servers with anticheats (rollbacks etc)
But enabling it when using elytra fly works great.
An option to enable No fall when starting to elytra fly + disabling it when hitting the ground would prevent any elytra fly fall damage. The option would be called "smart elytra based toggle", in the No fall parameters

I tried to bind No fall with the same key as elytra fly but with some delay. So when flying, no fall activates, and when i stop, it disables itself 1 second after. It works great, but it isn't reliable at all, since enabling elytra fly 2 times in less than 2 seconds break the system. And adding more delay isn't convenient, since you need to wait for it to disable to be able to walk, and it breaks even faster.

**Comment by RedCarlos26** [comment]
This was fixed
