### ISSUE TITLE
Bookdupe not launching with the latest dev version of Meteor Client 1114[Bug]

### ISSUE THREAD

**Issue by artajdc** [MeteorDevelopment/meteor-client#1118]
Bug: launching Minecraft 1.17 Fabric with meteorclient and the bookdupe in the mods folder crashes on attempt to launch the game. 

1. Downloaded the latest dev meteor client version in #dev-builds
2. Downloaded the latest bookdupe addon mod .jar -dev version
3. Files in mods folder: bookdupe-0.3-dev.jar, fabric-api-0.36.0+1.17.jar, and meteor-client-0.4.4-1114.jar

![NVIDIA_Share_FCV91qSyl8](https://user-images.githubusercontent.com/69132337/123374144-87057280-d53b-11eb-972e-a0ed64f1bc03.png)
![NVIDIA_Share_BMqFFUCyRU](https://user-images.githubusercontent.com/69132337/123374145-879e0900-d53b-11eb-92c9-e83a4072d107.png)

**Comment by C10udburst** [comment]
You've download the wrong bookdupe jar. Use [bookdupe-0.3.jar](https://github.com/MeteorDevelopment/meteor-book-dupe-addon/releases/download/latest/bookdupe-0.3.jar)

**Comment by artajdc** [comment]
> 
> 
> You've download the wrong bookdupe jar. Use [bookdupe-0.3.jar](https://github.com/MeteorDevelopment/meteor-book-dupe-addon/releases/download/latest/bookdupe-0.3.jar)

![image](https://user-images.githubusercontent.com/69132337/123380629-88876880-d544-11eb-9494-0bb55e7fc143.png)

**Comment by seasnail8169** [comment]
https://github.com/MeteorDevelopment/meteor-book-dupe-addon/releases/tag/latest
