### ISSUE TITLE
[Suggestion] Alt list/Proxy List

### ISSUE THREAD

**Issue by AlexKari** [MeteorDevelopment/meteor-client#1124]
Add a feature to import proxies as a ip:port list, and alts as a username:password list.

Considering we have things like the swarm module, it's kind of absurd that we have to manually input proxies and alts.

**Comment by TyraVex** [comment]
An import option like inertia would be appreciated
+1

**Comment by AsherY8979** [comment]
Bump
+1

**Comment by arlomcwalter** [comment]
bump -7

**Comment by DesiCow** [comment]
Bump +69

**Comment by SIMULATAN** [comment]
Is the alts thing even needed anymore considering mojang accounts won't work anymore in a month

**Comment by SIMULATAN** [comment]
Also, for proxies, what format should we use? `ip:port` isn't really that universal because what about names or a protocol? I could make both optional but what protocol do you use then as the default?
