### ISSUE TITLE
[Suggestion] Moses

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1126]
**Describe the feature**
Normal movement mechanics underwater

**Comment by seasnail8169** [comment]
I would need tyrannus' permission, he created it.

**Comment by RedCarlos26** [comment]
@tyrannus00

**Comment by tyrannus00** [comment]
It's fine you can add it

**Comment by RedCarlos26** [comment]
POG

**Comment by DesiCow** [comment]
You can now use `Ignore` mode for water in Jesus module now.

**Comment by ThebestkillerTBK** [comment]
> You can use `Ignore` mode for water in Jesus module now.

no moses is no water drag
