### ISSUE TITLE
[Bug] When standing on water with Jesus, attacks don't connect.

### ISSUE THREAD

**Issue by dotqurter** [MeteorDevelopment/meteor-client#113]
If I had to guess, it's because of not passing through the other data of the packet before sending the update packet in jesus.java.

**Comment by dakone22** [comment]
Well, `Jesus` impact only on `PlayerMoveC2SPacket`:
```java
    @EventHandler
    private final Listener<PacketEvent.Send> onSendPacket = new Listener<>(event -> {
        if (!(event.packet instanceof PlayerMoveC2SPacket)) return;
```
As I see, for attack using `PlayerInteractEntityC2SPacket`. So, I don't think that issue in packet messing.

**Comment by RedCarlos26** [comment]
Is this not an anti-cheat issue? Is it possible to reproduce it in vanilla?

**Comment by dotqurter** [comment]
> Is this not an anti-cheat issue? Is it possible to reproduce it in vanilla?

It's been a while since I last used, but even in a local server I could replicate.

**Comment by RedCarlos26** [comment]
Ok

**Comment by seasnail8169** [comment]
Cant reproduce at all, ac issue.
