### ISSUE TITLE
[Bug] Liquid velocity in singleplayer

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1132]
On the lastest version of meteor liquid velocity in singleplayer is affecting items.
With this module on, water streams are broken, they doesn't push the items. The module is applied to them.
Turning it off resolved the issue.

**Comment by MineGame159** [comment]
Cannot reproduce

**Comment by TyraVex** [comment]
Ok i will make a video then, because it is breaking my testing worlds each time

**Comment by MineGame159** [comment]
Make sure you are on latest commit

**Comment by TyraVex** [comment]
But it isn't compatible with 1.16.5 nah? I need to use viaversion?

**Comment by MineGame159** [comment]
Well then of course it is broken for you when you are not using latest commit

**Comment by TyraVex** [comment]
So no way of having a fix for a 1.16.5 config?
