### ISSUE TITLE
[Suggestion]  Date and time hud.

### ISSUE THREAD

**Issue by NIGHTMARIO** [MeteorDevelopment/meteor-client#1134]
**Describe the feature**
It is a very small suggestion. I want the "HUD" module to include the hud to display Date and time IRL. I also use labymod which has date and time hud, it is really useful for me because I sometimes just forget to check my time and stay up late doing some Minecraft projects. This feature may help me and many other people who use Minecraft in full-screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/84377831/123540268-db883800-d75d-11eb-85db-20e0b735f13a.png)
Screenshot is taken from labymod.

**Additional info**
I don't think any additional info is required.

**Comment by seasnail8169** [comment]
the time hud element can already show the local time, date is unnecessary imo

**Comment by RedCarlos26** [comment]
It's useful when you want to leave signs or remember what was the date on a screenshot honestly

**Comment by seasnail8169** [comment]
no

**Comment by RedCarlos26** [comment]
Bruh

**Comment by seasnail8169** [comment]
literally just check or remember the date

**Comment by NIGHTMARIO** [comment]
Ok.

**Comment by RedCarlos26** [comment]
Sad
