### ISSUE TITLE
[Sug

### ISSUE THREAD

**Issue by LDoom** [MeteorDevelopment/meteor-client#1140]
**Describe the feature**
A major missing block is the Respawn Anchor.

**Screenshots**
![image](https://user-images.githubusercontent.com/73355762/123714539-1eb8d880-d83c-11eb-81ef-a22916338abc.png)

**Additional info**
anchor does not affect the face place in the nether.

**Comment by a-couple-objects** [comment]
sugma

**Comment by LDoom** [comment]
this was for another client 😁
