### ISSUE TITLE
[Suggestion] Blink Improvements

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1141]
**Describe the feature**
Add options to toggle off automatically once you either enter a hole or move a distance away from when you started blinking, also add compatability to surround so it stays on while blinking

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by seasnail8169** [comment]
Encouraging blinking in cpvp is cringe

**Comment by RickyTheRacc** [comment]
bruh just because you don't like it isn't a reason that it shouldn't be added

**Comment by necrophili** [comment]
Stealing banana+ features :trollface:

**Comment by seasnail8169** [comment]
> bruh just because you don't like it isn't a reason that it shouldn't be added

Why not? Who else should make the decision about what I do.

**Comment by LDoom** [comment]
I use blink with surround ._.

**Comment by seasnail8169** [comment]
then you're shit at pvp
