### ISSUE TITLE
Game Crash [Bug]

### ISSUE THREAD

**Issue by aresociety** [MeteorDevelopment/meteor-client#1143]
**Describe the bug**
When you launch fabric with the mod on the game immediately crashes everytime. 

**To Reproduce**
1. Open Minecraft Launcher and select fabric
2. Launch
3. Wait until it loads

**Expected behavior**
Successfully launches game 

**Screenshots**
Happens to fast to actually screenshot

**Additional context**
Meteor Client 0.4.4-1123
bookdupe-0.3-dev

fabric-loader-0.11.3-1.17
windows 10 20h2 build: 19042.1052

exit code: 0
also this issue isnt caused by bad computer

**Comment by StormyBytes** [comment]
dont use the dev version of bookdupe. The one with "-dev" on the back.
