### ISSUE TITLE
[Suggestion] Merge XRay and Wallhack

### ISSUE THREAD

**Issue by IIpho3nix** [MeteorDevelopment/meteor-client#1145]
**Describe the feature**
A Xray That Is Half Transparent

**Screenshots**

https://user-images.githubusercontent.com/79083095/123778561-e4057d80-d8d9-11eb-805b-7a61b5545c65.mp4

**Additional info**
This Feature Will Be Useful Since It Lets You See The Terrain While Using Xray

**Comment by JFronny** [comment]
The code needed for this could reuse the wallhack stuff like i did [here](https://github.com/JFronny/meteor-client/tree/wallhack-xray-merge)

**Comment by TyraVex** [comment]
Why not using search?

**Comment by IIpho3nix** [comment]
> Why not using search?

what do you mean by that

**Comment by TyraVex** [comment]
Try the search module you will see

**Comment by seasnail8169** [comment]
> The code needed for this could reuse the wallhack stuff like i did [here](https://github.com/JFronny/meteor-client/tree/wallhack-xray-merge)

or just merge them :trollface:

**Comment by seasnail8169** [comment]
(i am doing it)
