### ISSUE TITLE
[Suggestion] cave lighter or something

### ISSUE THREAD

**Issue by MARlUS003** [MeteorDevelopment/meteor-client#1147]
since this is a utility mod, i think  this wold be good. it show where caves that arent lit up in a customizable radius that you set on a coordinate. this would be pretty nice for making mob farms because you could know where caves are that arent lit up

no screenshots, sorry :(

maybe like a red outline on caves that dont have light, and where lightlevel is lighter than 12 there isnt the outline.

**Comment by C10udburst** [comment]
SpawnProofer module is a thing

**Comment by seasnail8169** [comment]
wait does spawn proofer place torches?

**Comment by MARlUS003** [comment]
i meant to not light up caves, but to find unlit caves and see them through walls

**Comment by StormyBytes** [comment]
The light overlay module does that.

Also, spawn proofer works for light sources and non light sources.

**Comment by MARlUS003** [comment]
so light overlay shows where to light up through walls too?

**Comment by StormyBytes** [comment]
Yes. Just turn on the render through walls setting.

**Comment by seasnail8169** [comment]
oh
