### ISSUE TITLE
[Bug] Waypoints scale make them unreadable at most distances

### ISSUE THREAD

**Issue by Sprink02** [MeteorDevelopment/meteor-client#1150]
Waypoint scaling makes them unreadable when far/close since 1.17 port

**Comment by seasnail8169** [comment]
@MineGame159 ficks pleas

**Comment by SpaceClouds42** [comment]
This is also an issue with nametags and any other in world meteor rendered text. Zooming in to try to see it just makes it become smaller so you have to freecam over to it to actually read it.

**Comment by Wide-Cat** [comment]
this has been fixed
