### ISSUE TITLE
[Suggestion] Add surround break to the CA

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1154]
**Describe the feature**
Please I am begging you

**Comment by necrophili** [comment]
Beggin youououou

**Comment by cmk-Destro** [comment]
- [ ] _upvoted_

**Comment by seasnail8169** [comment]
mfw "Describe the feature"

what does surround break do?

**Comment by RickyTheRacc** [comment]
places a crystal next to someone's surround and keeps it there so when you city them they can't replace it, there's also normally an option called surround break that accompanies it which forces the ca to keep placing next to their surround instead of where it would be so they can't resurround

**Comment by Makrennel** [comment]
> there's also normally an option called surround hold

"normally" - literally haven't seen this anywhere except in old meteor CA, and it just spam wastes crystals.

Surround break is just placing a crystal where a block was (or is) after (or before) the block is broken without calculation. It's not necessarily necessary.

Neither will stop a faster surround from replacing before the CA can place the next crystal. Hold is just a meme.

**Comment by seasnail8169** [comment]
Moment in history, Makrennel used logic for the first time
