### ISSUE TITLE
Damage Indictors [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1156]
**Describe the feature**
Customizable Damage Indicators that appear when you hit a target.
-They should be able to:
render through/ontop entities and blocks
appear ingame near the target
option to not show ignore sweeping edge damage
change size of the damage number
have a background to the damage number
Show the calculated damage with armor/toughness
render duration setting (the render of the damage number)

-additional features?
possibly appear in chat
hud option that shows your last damage delt and to what type of entity (sweeping edge disabled)

**Comment by a-couple-objects** [comment]
yes please damage indicator mods are all trash for visibility

**Comment by seasnail8169** [comment]
You can hide certain particles with No Render

**Comment by seasnail8169** [comment]
and you can just use nametags for health, damage is exessive imo

**Comment by Texbio** [comment]
It is really unfortunate that you have closed this suggestion even though it was such a needed suggestion. It is hard to see how much damage you do to a target and servers with many plugins use a bunch of weird weapons with enchants. There are a couple more examples for where this kind of information would be useful like seeing how much damage other players took from your end crystal, how much damage do your beds do to other players, and other information that would be covered with having this kind of informative module. You will never know how much damage you actually can do unless you use some sort of debug script. 

"and you can just use nametags for health, damage is excessive imo"; nametags can get in the way and you will never be heavily paying attention see your damage output in decimals, and even you did, it would feel very inconvenient to the person testing these kinds of thing. I think it would definitely be beneficial to add Damage indicators as they are definitely needed and will be used.

**Comment by Texbio** [comment]
If there is no reply I will reopen a new suggestion later

**Comment by seasnail8169** [comment]
"are definitely needed" litteraly why, the only purpose for this is like debugging combat modules which doesnt need to be in production. Maybe the idea of adding something like crystal aura has, to bed aura and anchor could be a good idea but I don't agree with your other points. Also i don't see what the benefit for you to be rude to me is, its my judgment and opening another issue isn't gonna change anything unless you make you suggestions better.

**Comment by Texbio** [comment]
I am really sorry if I came off as rude, as I would never want to do that to someone who actually knows what they are doing. I really don't understand the purpose of the last reply, as this is a great module that should be added immediately and would help players understand how they can do more damage, and even see how much damage they can do to custom mobs. I will not bring up other plugins since you seemed not to like me talking about them. 

For vanilla minecraft players do damage to everything and on crits you do more damage. What about 32ks, 32ks armor and people playing around with minecraft vanilla attributes (max armor+max toughness+health) and potion effects? It would be annoying to test these things manually so making a script is more useful in this case to get your damage outputs against entities, but with this module any sad hobo can just turn on this module and see how much damage they just did. 

This is not a hacking module but rather an extremely informative module so it should be treated differently compared to air place or killaura. 

The value of this module is really big to me since I use this module on inertia every day I am playing minecraft if I can (tweakaroo crashes inertia client so there are times I can't use inertia). It would be awesome if it could be implemented into meteor since after 1.16.5 inertia will not be compatible with meteor's modules without translating code.
