### ISSUE TITLE
An actual item saver that works [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1157]
**Describe the feature**
-Item saver that works for all of my gear. 
-Could be able to customize durability settings for certian items (elytras, flintnsteals, shears, ect)

**Comment by seasnail8169** [comment]
Inventory tweaks does this

**Comment by Texbio** [comment]
The closest thing I found to inventory tweaks was inventory profiles. Could you please confirm that is what you were talking about?

**Comment by Texbio** [comment]
> The closest thing I found to inventory tweaks was inventory profiles. Could you please confirm that is what you were talking about?

never mind, I was using an old version of meteor
