### ISSUE TITLE
Anti Ghost blocks 2 [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1158]
**Describe the feature**
#818 Talked about anti-ghost blocks, and Inertia client has it implemented this very well. The only issue is that new versions of meteor break inertia commands completely. 

I suggest that meteor makes their own version of anti-ghost blocks since the mod https://www.curseforge.com/minecraft/mc-mods/antighost sucks because you have to keep on pressing the key to load blocks in a radius and could easily be kicked for too many packets.

**Comment by seasnail8169** [comment]
commands have been fixed for the next release

**Comment by seasnail8169** [comment]
And as you said, a duplicate

**Comment by Texbio** [comment]
What does this mean? I was asking for a module that would verify if blocks were actually broken when you break them by sending packets to the server. Inertia client is known for doing a good job at this feature if you want to look at it. I still want to know what this means: "commands have been fixed for the next release"

**Comment by seasnail8169** [comment]
The bug you said with inertia commands has been fixed since the latest release, hence it will come with the next release. And as for the actual suggestion, its a duplicate suggestion as you literally said.

**Comment by Texbio** [comment]
I dont think meteor should have to rely on inertia to have convenience. "I suggest that meteor makes their own version of anti-ghost blocks because [the curseforge mod] sucks". I think if you have time later you could this feature to meteor too because meteor is the better client in-terms of overall features but lacks some basic features (auto farm, color signs use to be one, tunneler (there is a version i think on meteor rejects), stronghold finder, new chunks got added i think?). There are other clients to choose from but inertia is a good example since it was a good utility client.
