### ISSUE TITLE
Enchant Color [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1160]
**Describe the feature**
A simple module that changes item enchant color. Rainbow could be an option too.

**Comment by seasnail8169** [comment]
Just change it with a resource pack since you can do that now

**Comment by Texbio** [comment]
The difference between using a mod and a client would be more customization and less laggy mess. You could even add borders to items in the gui to represent if it is enchanted vs not enchanted.

BOTTOM TEXT

**Comment by seasnail8169** [comment]
"less laggy mess" what? Recolouring a texture would have absolutely 0 impact on performance, definitely less than using a mod to do it although still completely irrelevant and not possible to notice

**Comment by Texbio** [comment]
yea it would not be laggy, I was just thinking about making a resource pack where you add a border to all items and apply that texture for every item if it is enchanted. That scenario might cause a bit of lag. (not a laggy mess, I over exaggerated)

**Comment by seasnail8169** [comment]
it wouldn't, textures have extremely little performance impact
