### ISSUE TITLE
Anti Bot [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1161]
**Describe the feature**
Instead of removing players and custom npcs that might be useful using antibot, allow players to remove them from killaura and from nametags and any other targeting system.

**Comment by Texbio** [comment]
why was this closed? Was it because of meteor rejects addon?

**Comment by seasnail8169** [comment]
Meteor is not meant for cheating

**Comment by Texbio** [comment]
Npcs are bots too ._. you dont want to attack them for no reason. (usually players can make npcs using server plugins)

**Comment by Texbio** [comment]
Meteor rejects instead completely removes these guys instead of attacking them, which is not good. There should also be an option to see if the bot is moving or if it will take damage from the player (if it does not take damage why are u attacking it???)

**Comment by Texbio** [comment]
If you dont want to make an anti bot you can ignore this one but it might be suggested in the future
