### ISSUE TITLE
Auto Steal features [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1162]
**Describe the feature**
-Allow auto steal to be smart and have some options:
auto open chests in range
range settings
preform vanilla minecraft item on item shift-click to move more than one stack
filters for what items to take
through walls settings
replenish stacks
Instead of toggling auto dump or auto steal each time move auto dump to a new module. If you try to toggle the second one using a hotkey or manually it should turn off the one you had on before. 
Ex: Had auto dump on and turned on auto steal, so auto steal would stay on and auto dump will be toggled off.
Auto dump should also have most of the same settings as auto steal.

**Comment by Texbio** [comment]
Why was this closed @seasnail8169

**Comment by Texbio** [comment]
This has only been implimented up to auto steal and auto dump existing. I was looking for something that would automaticly open chests in range and have a filter for what to steal instead of trying to steal 20 stacks of cobblestone.

**Comment by seasnail8169** [comment]
Make your suggestions more specific, not just a bunch of ideas in one issue

**Comment by Texbio** [comment]
I will try to make it more specific, but I was sure that I listed the possible stuff I wanted to be added properly.

**Comment by seasnail8169** [comment]
Thats not the point, i don't want a list of things i want one thing per issue that is reasonable, justified and well explained.

**Comment by Texbio** [comment]
It takes a longer time to do that but if you request that, I will definitely explain things better.

**Comment by Texbio** [comment]
ported to #1189
