### ISSUE TITLE
Module to tweak splash screen and resource pack loading [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1163]
**Describe the feature**
-Add a module to tweak the splash screen and another for loading resources packs
-splash screen options
use mouse click buttons normally (I think you can already move using WASD keys)
interact anything you normally cant interact with? (if there is anything)
stop the splash screen from appearing completely!
small splash screen loading bar option?

-loading resources packs
auto accept resource packs
bypass accepting resourcepacks? Some plugins try to make you accept resource packs.

If you don't want to do the resource pack part atleast consider doing the splash screen part as it will be very useful and would get rid of a big annoyance!

**Comment by Texbio** [comment]
if you do not want to do the other parts could you do " stop the splash screen from appearing completely!" and " use mouse click buttons normally (I think you can already move using WASD keys)" I have not seen a client do this yet.

**Comment by seasnail8169** [comment]
Literally all of that is completely meaningless, you haven't explained what you mean at all.

**Comment by seasnail8169** [comment]
Like "the splash screen" ? wtf is the splash screen

**Comment by Texbio** [comment]
> Like "the splash screen" ? wtf is the splash screen

The splash screen is the screen that appears when you are loading a resource pack. I am sorry if I defined it incorrectly but I could not find out what it was called even after trying to look it up. There are tons of fabric mods that I found that called it a splash screen so I went with it. 
https://www.curseforge.com/minecraft/mc-mods/custom-splash-screen

**Comment by seasnail8169** [comment]
Alright, so you are asking to prevent the "splash screen" (i will call it the loading screen) from showing? Surely you can realise that this screen displays for a reason. You cant just hide it because minecraft needs time to reload all textures and therefore there would be nothing to show when the loading screen would be shown because there is no textures.

**Comment by Texbio** [comment]
> Alright, so you are asking to prevent the "splash screen" (i will call it the loading screen) from showing? Surely you can realise that this screen displays for a reason. You cant just hide it because minecraft needs time to reload all textures and therefore there would be nothing to show when the loading screen would be shown because there is no textures.

Durring this time if you logged out in a certian area, and the server is forcing you to load a splash screen, you are completely vullernable if you don't turn on kill aura. Also during this time usually people want to sort chests or do something else other than waiting 20 seconds for a splash screen. 
(examples: shooting rockets when u have an elytra equipped to move away from that area, break your shulkers that are placed down and you cant reach, and even save yourself from dying in the void because you could not see where you were). The game will reload textures in your world and menu once it is done loading them so I don't see how this could harm the player at all.

**Comment by seasnail8169** [comment]
I dont think you are understanding, the point is that there would be no textures to render during thats screen, you cant just show it normally because you wouldnt see anything

**Comment by Texbio** [comment]
> I dont think you are understanding, the point is that there would be no textures to render during thats screen, you cant just show it normally because you wouldnt see anything

That is incorrect, the default minecraft textures are there by default and whatever resource packs you are using. 
Also when the server is adding server resource packs, it first downloads it if it needs to, then just places that server resource pack on the top of your resource pack list, rendering with a priority above the other resource packs you are using. If you could remove the splash screen, you would just see default minecraft textures or whatever resource packs you are using until the server resource pack loads.

**Comment by seasnail8169** [comment]
If that was the case, what would be the point of the loading screen, maybe it wouldn't be completely blank but there is clearly a reason for the screen

**Comment by Texbio** [comment]
> If that was the case, what would be the point of the loading screen, maybe it wouldn't be completely blank but there is clearly a reason for the screen

There is litterly no point since the game is still rendering the chunks you are inside. I doubt it will cause any errors to hide it but idk how to make it so the player can still use their mouse.
