### ISSUE TITLE
Importing Meteor to 1.12

### ISSUE THREAD

**Issue by zeyaadoesntcodestuff** [MeteorDevelopment/meteor-client#1168]
I'd really love to make meteor available for 1.12, as it's the only decent client other than future, and i really don't know how to use other client like inertia or phobos. I personally think it'll benefit alot of us 2b2t players, as i'm not waiting forever to have a hacked client that may not even have the features i want it to have.

**contact me**
Ya_boii_ziad#0001 (im in meteor discord)
zeyaadmoutier@gmail.com

**Comment by MineGame159** [comment]
https://www.curseforge.com/minecraft/mc-mods/multiconnect
