### ISSUE TITLE
A world loading & render bug

### ISSUE THREAD

**Issue by Trakioos** [MeteorDevelopment/meteor-client#1174]
**Describe the bug**
my world loading is crashed or something?

**To Reproduce**
I just installed the client (cause i want to try it) entered a world, and this happened.

**Expected behavior**
A normal world 

**Screenshots**
![image](https://user-images.githubusercontent.com/85789483/124501571-7fab5800-ddca-11eb-969a-2840135b8419.png)

[
![2021-07-05_19 54 24](https://user-images.githubusercontent.com/85789483/124501824-ef214780-ddca-11eb-9fb2-b585793cafc6.png)
](url)

**Additional context**

**Comment by seasnail8169** [comment]
Can you try without meteor in your mods folder and see if the issue persists

**Comment by Trakioos** [comment]
> Can you try without meteor in your mods folder and see if the issue persists

good idea

**Comment by RickyTheRacc** [comment]
What mods are you using?

**Comment by seasnail8169** [comment]
ok ricky

**Comment by Trakioos** [comment]
> Can you try without meteor in your mods folder and see if the issue persists

it dont worked. i have sodium, i will try without sodium.

**Comment by Trakioos** [comment]
> What mods are you using?

Client + SeedCracker + Sodium

**Comment by Trakioos** [comment]
![2021-07-05_20 17 56](https://user-images.githubusercontent.com/85789483/124503422-2cd39f80-ddce-11eb-817d-5924062036b6.png)
Thanks for help, ı changed this setting to Oneshot (GL 3.0) and issue solved.
