### ISSUE TITLE
[Suggestion] Increased world height for 1.17

### ISSUE THREAD

**Issue by MunchyG** [MeteorDevelopment/meteor-client#1177]
The search and nuker functions (there may be more, these are just the 2 i have noticed) do not work below y0 if you use the experimental world gen to make the deeper cave.

**Comment by MunchyG** [comment]
liqiud filler also doesn't work below y 0

**Comment by MineGame159** [comment]
Fixed in 3c37ea1bf9c12a094114c237f74ac76144291c4a
