### ISSUE TITLE
[Suggestion] Random Block Placement

### ISSUE THREAD

**Issue by Cethien** [MeteorDevelopment/meteor-client#1180]
Would be cool to have a Random Block Placement feature. 
[FVT](https://modrinth.com/mod/fvt) has a good one, maybe take a look at that one?

**Comment by seasnail8169** [comment]
What do you mean?

**Comment by Cethien** [comment]
It's a feature which takes random placeable blocks from your hotbar when you try to place it and places it instead. Useful for building with different kind of blocks.

**Comment by seasnail8169** [comment]
This is literally the most useless thing i can posssibly imagine
