### ISSUE TITLE
[Bug] 1.17.1

### ISSUE THREAD

**Issue by C10udburst** [MeteorDevelopment/meteor-client#1181]
**Describe the bug**
MixinTransformerError in 1.17.1

**To Reproduce**
1. Launch minecraft

**Additional context**
[crash-2021-07-06_18.35.32-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6771448/crash-2021-07-06_18.35.32-client.txt)
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/6771450/latest.log)

**Comment by Fr-gs** [comment]
I have the same crash log

**Comment by C10udburst** [comment]
Uhh fixed in 5eb22ae8f079c29d5a246877e84ddfb5ff95131d i guess
