### ISSUE TITLE
MC Crashes when viewing brewing stand UI

### ISSUE THREAD

**Issue by ForsakenMage** [MeteorDevelopment/meteor-client#1186]
**Describe the bug**
When you right-click a brewing stand and open its UI, the game crashes after ~0.5 sec
**To Reproduce**
1. Launch MC 
2. Right-click on brewing stand
3. Move mouse around

**Expected behavior**
The game does not crash
**Additional context**
MC version: 1.17.1
Meteor version: v0.4.4 build 1136
Fabric API version: 0.36.1-1.17
Breaks even with no modules enabled
[crash-2021-07-06_14.59.32-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6773037/crash-2021-07-06_14.59.32-client.txt)

**Comment by seasnail8169** [comment]
Send the crash log

**Comment by Wide-Cat** [comment]
beat me to it

**Comment by ForsakenMage** [comment]
How?

**Comment by Wide-Cat** [comment]
send the latest file from the .minecraft/crash-reports folder

**Comment by ForsakenMage** [comment]
[crash-2021-07-06_14.59.32-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6773032/crash-2021-07-06_14.59.32-client.txt)

**Comment by pitust** [comment]
> [crash-2021-07-06_14.59.32-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6773032/crash-2021-07-06_14.59.32-client.txt)

what version are you using?
