### ISSUE TITLE
#1157 Re-write Antibreak single module [Suggestion]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1188]
Remove all of the antibreaks from all the modules and instead make a stable anti-break module. 

Antibreak: Moves the item that is about to break to a slot in your inventory if it is armor or a shield; for tools it will move your selected slot to another slot that the tool is not in, and if you try moving back to the slot with the tool, it will keep on moving thier selected slot. 
-it should check each time you try moving to a slot with the selected tools.

-add blacklist possibilities (you dont care if your wooden sword breaks or shears/flint n' steel)
-add a durability amount/percent range (you can choose if the item is down by 10% or 10 durability to remove it from that slot)

**Comment by seasnail8169** [comment]
There is absolutely no reason to do this and it's completely illogical, for example auto armor manages your armor and hence manages whether to allow it to break or not, same with all of the other modules that have any kind of anti break (pretty sure just auto tool)

**Comment by Texbio** [comment]
I don't want to use auto armor or auto tool because I don't need auto armor or auto tool, I just need something to prevent accidental overuse of items. Auto armor swaps out your armor for no reason sometimes and usually I end up needing the armor it just swapped out. Adding an antibreak is much better than adding antibreak to all modules as it actually lets you customize stuff how you want it to be instead of just adding restrictions that you will only use for crystal pvp. 

My take on it is that It is really inconvenient to have antibreak on all modules that use tools/ armor because you have to be restricted to picking a piece of armor based on its stats (can't wear gold to the nether if you have auto armor and cant quick swap to an elytra without going into the module and editing it). It is definately smarter to create one module that controls what kinds of armors can break. I hope you understand why having one module controlling armor/tools is better.
