### ISSUE TITLE
[Suggestion] Containers preview 

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1190]
Hello,

I couldn't find any mod for fabric 1.16.5+ that allows you to preview the content of containers while looking at them.
This could be so useful when searching for specific items in hundreds of containers
It would be client side only by requesting the content of containers without opening their GUIs, and then display a hologram of the items in it.
In addition, using it with a chest tracker mod would allow you to simply run in front of hundreds of chest and logging every one of them into the mod, and easily find any items you want in these containers.

I think it could be a cool addition :)

**Comment by Texbio** [comment]
There is a fabric mod called chest tracker that works pretty good, use that instead.

**Comment by TyraVex** [comment]
> There is a fabric mod called chest tracker that works pretty good, use that instead.
"In addition, using it with a **chest tracker** mod would allow you to simply run in front of hundreds of chest and logging every one of them into the mod, and easily find any items you want in these containers."

This addition could work with the mod and automatically log every chest near you without opening it, this is why i think it could be a cool feature 
But the first usage would be to preview containers, for example finding a stuck item in a super smelter

**Comment by Texbio** [comment]
> > There is a fabric mod called chest tracker that works pretty good, use that instead.
> > "In addition, using it with a **chest tracker** mod would allow you to simply run in front of hundreds of chest and logging every one of them into the mod, and easily find any items you want in these containers."
> 
> This addition could work with the mod and automatically log every chest near you without opening it, this is why i think it could be a cool feature
> But the first usage would be to preview containers, for example finding a stuck item in a super smelter

That does not work on most servers

**Comment by TyraVex** [comment]
Tbh I think it would be possible, since you don't need to aim at a container to open it (proven by opening chests with freecam), and the module would basically open the chest and close it the next tick, without opening the chest gui. Player movements would not be affected, since XCarry is a thing

I just don't find a way where this would not be possible ¯\_(ツ)_/¯
