### ISSUE TITLE
add trigger feature back (plzz)

### ISSUE THREAD

**Issue by Xrawr** [MeteorDevelopment/meteor-client#1191]
**Describe the feature**
Automatically hits entities when they pass through the crosshair

**Additional info**
This was a module used a lot by me and my friends who also use the meteor, we miss it a lot and it would be amazing if you could add it again to the 1.17 update. <3

**Comment by seasnail8169** [comment]
Kill Aura has a setting called only on look

**Comment by Texbio** [comment]
Yea killaura is better to use now
