### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Envizar** [MeteorDevelopment/meteor-client#1194]
Some textures are displayed incorrectly in the HUD.

1. Install sodium on fabric.
2. Log in to the server.
3. Enable HUD and inventory preview.
4. Enjoy the black texture instead of the beautiful texture of the inventory.

I would like to see a normal texture instead of this one.

https://cdn.discordapp.com/attachments/689197706169942135/862640770589786112/h8sr5z89.png

Minecraft version-1.17.7, fabric loader 0.11.6, meteor client dev-build https://meteorclient.com/download?devBuild=1139

**Comment by StormyBytes** [comment]
Isn't sodium still beta? We can't fix it if it's still beta.

**Comment by MineGame159** [comment]
Cannot reproduce, you are probably using old versions
