### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Seaparty** [MeteorDevelopment/meteor-client#1195]
Durability extender
Im not sure about if this is possible, but could it be affected so durability isnt changed. The reason i think this may be possible is because the unbreaking enchantment doesnt have a defined number and it may be possible to abuse that

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by GildedS** [comment]
Patched

**Comment by RickyTheRacc** [comment]
Lmfao what
