### ISSUE TITLE
[Suggestion] Opacity Option For X-Ray

### ISSUE THREAD

**Issue by cqtgirl** [MeteorDevelopment/meteor-client#1203]
**Describe the feature**
A clear and concise description of what feature/change is.
A way to make blocks some what see-through instead of straight up seeing through a block (if you don't know what I mean, look at future client's xray)
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.
https://i.imgur.com/X6hQPyC.png
**Additional info**
Add any other info.

**Comment by cybrpop** [comment]
The feature is already present in the latest dev build.

**Comment by RickyTheRacc** [comment]
Already exists brainlet

**Comment by cqtgirl** [comment]
sorry, wasn't on the latest dev build
