### ISSUE TITLE
[Bug] Hide HUD

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1210]
**Describe the bug**
Turning on "hide hud" in the gui tab and then saving your profile or closing meteor will not save that it's enabled

**Comment by C10udburst** [comment]
| | |
|:-------------------------:|:-------------------------:|
|<img src="https://user-images.githubusercontent.com/18114966/125575855-7964e45a-ce11-476a-854c-4dd4800b3931.png">|<img src="https://user-images.githubusercontent.com/18114966/125575923-7658cc95-c102-440d-a3a2-984f138cca60.png">|


you issue

**Comment by RedCarlos26** [comment]
@RickyTheRacc ^

**Comment by RedCarlos26** [comment]
@arlomcwalter close pls
