### ISSUE TITLE
Meteor will not launch with optifabric 1.17.1

### ISSUE THREAD

**Issue by Windorabug** [MeteorDevelopment/meteor-client#1212]
**Describe the bug**

Meteor will not launch with optifabric in the mod folder on 1.17.1

**To Reproduce**
1. Place optifabric, meteor client, and fabric API in mods folder.
2. Launch meteor client through the normal mc launcher
3. See error "creating empty clause?"

**Expected behavior**
The game to launch with all mods working

**Screenshots**
https://imgur.com/a/CNyLG9B

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).
Meteor version: 0.4.4
optifabric version: 1.11.17
mc version: 1.17.1
OS: Linux Mint 20.1 Cinnamon

**Comment by MineGame159** [comment]
Meteor will never be compatible with optifine / optifabric. Use https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754.
