### ISSUE TITLE
[Bug] VoidESP Crashes client in a Void/Empty world

### ISSUE THREAD

**Issue by pog5** [MeteorDevelopment/meteor-client#1213]
**Describe the bug**
When for example going into a Housing world on hypixel or a Skyblock world while having VoidESP on, your game crashes.

**To Reproduce**
1. Go on a Superflat world thats just void
2. Turn on VoidESP

**Expected behavior**
All void blocks would be highlighted

**Screenshots/Logs**
[crash-log-client-newest.txt](https://github.com/MeteorDevelopment/meteor-client/files/6806774/crash-2021-07-13_08.57.28-client.txt)

**Additional context**
Note: This only happens if you are using Lithium, removing Lithium solved the issue for me.

**Comment by tk4096** [comment]
this happens because your pc cant handle it highlighting all the blocks. get a better pc and this wont happen :trollface:

**Comment by pog5** [comment]
then why does removing lithium fix the issue?

**Comment by tk4096** [comment]
actually your right it wasnt caused due to lag, from what I understand the data structure that stores the blocks highlighted got bigger than the size limit lithium imposes and it crashed due to that, still no real way to fix it though and why are you using antivoid in minegame servers anyways?

**Comment by a-couple-objects** [comment]
meteor good performance mod

**Comment by seasnail8169** [comment]
> Who said he was?

@BobIsMyManager literally him

> hypixel or Skyblock

**Comment by BobIsMyManager** [comment]
Didn't see that lol

**Comment by MineGame159** [comment]
Fixed in 7268645853e6a184708f2a69911cdd2b53a591db

**Comment by tk4096** [comment]
epic
