### ISSUE TITLE
[Bug] Minecraft freezes after trying to add a Microsoft account

### ISSUE THREAD

**Issue by z0rug1** [MeteorDevelopment/meteor-client#1218]
**Describe the bug**

**To Reproduce**
1. Go to 'Multiplayer'
2. Click on 'Accounts'
3. Click on 'Microsoft'
4. Click "No" in the browser (Deny the permissions)
5. Go back to Minecraft
6. See error

**Expected behavior**
Minecraft not freezing

**Comment by seasnail8169** [comment]
#1865
