### ISSUE TITLE
[Suggestion] waypoints

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1220]
**Describe the feature**
Increase the maximum distance visible from 10,000 to 100,000, or just have it be a text box that the player can define themselves. As of now the range is way too small, especially on anarchy servers where bases or important places can be tens of thousands of blocks apart which basically makes setting a waypoint useless, as you can't see it.

**Comment by MineGame159** [comment]
Just type it yourself, only the slider is limited

**Comment by RickyTheRacc** [comment]
Ohhhhhh, didn't realize that lol. Thank you minegame
