### ISSUE TITLE
[Bug] Auto Replenish

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1221]
**Describe the bug**
Autoreplenish seems like it only works on items without a name, or with the same name. Could imagine this being a problem as most crystals and other items on anarchy servers have different names depending on kits, and sometimes even kits have differently named items inside them. Maybe try and find a way to simply look for the type of item it is as opposed to things named the same?

**Comment by seasnail8169** [comment]
This is how minecraft works, you cant stack items with different names

**Comment by RickyTheRacc** [comment]
I knoe you can't stack them, I mean an option to simply replace them with a new stack when the old one runs out entirely
