### ISSUE TITLE
add offhand crash, like bleachhack

### ISSUE THREAD

**Issue by Katguardain** [MeteorDevelopment/meteor-client#1224]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by Wide-Cat** [comment]
come on youve just got to be trolling at this point

**Comment by Wide-Cat** [comment]
have you even run the client? its literally already module

**Comment by RickyTheRacc** [comment]
bruh stop opening retarded issues, run the client and then suggest stuff

**Comment by Katguardain** [comment]
ok, my friend asked for this im sorry
