### ISSUE TITLE
armor above hotbar?

### ISSUE THREAD

**Issue by Katguardain** [MeteorDevelopment/meteor-client#1226]

**Comment by RedCarlos26** [comment]
You can modify it by yourself by going in the hub tab (the position of the armour hud is entirely customizable)

**Comment by Katguardain** [comment]
wair do i find armor hud?

**Comment by Katguardain** [comment]
> You can modify it by yourself by going in the hub tab (the position of the armour hud is entirely customizable)

wair is armor hud?

**Comment by ehylo** [comment]
click the hud tab at the top of the gui, if you have any more questions please just join the discord, making issues is annoying and most of what your asking can be answered in the discord
