### ISSUE TITLE
[Suggestion] jesus mode (Powder snow)

### ISSUE THREAD

**Issue by LDoom** [MeteorDevelopment/meteor-client#1229]
**Describe the feature**
A jesus mode or another module to be on top of the powder snow.

**Screenshots**
![image](https://user-images.githubusercontent.com/73355762/125650692-295f04cd-9e3e-4935-8817-6a3e3281ae9b.png)

**Additional info**
none.

**Comment by MineGame159** [comment]
Added in 724bbf499d6d782b2ec5a386138c73496df3be03
