### ISSUE TITLE
[Bug] Can't not install OptiFine

### ISSUE THREAD

**Issue by doanminhthanh** [MeteorDevelopment/meteor-client#1231]
**Describe the bug**
- Bug is Can't not install OptiFine if install then get an error

**To Reproduce**
1. install OptiFine_1.16.5_HD_U_G8 and optifabric-1.11.9 in .minecraft/mods
2. launch minecraft

**Expected behavior**
- Found conflicting mods: optifabric conflicts with {meteor-client @ [>=0.4.1]}
- Creating Empty clause ?

**Screenshots**
![image](https://user-images.githubusercontent.com/67426064/125653710-df7dc65a-e3c8-4570-b629-ad45b58b9386.png)

**Additional context**
- Meteor version : 0.4.4
- Minecraft version : 1.16.5
- Use mod : OptiFine_1.16.5_HD_U_G8 and optifabric-1.11.9

**Comment by Makrennel** [comment]
Use Sodium
