### ISSUE TITLE
Make Jesus work with anticheats

### ISSUE THREAD

**Issue by PilaCiu** [MeteorDevelopment/meteor-client#1234]
Meteor client is the only utility mod without functional Jesus on NCP/AAC, can you fix this?

**Comment by RickyTheRacc** [comment]
Also ncp scaffold 🙏

**Comment by mmvanheusden** [comment]
Yes this would be very useful

**Comment by D3V1LC0D3R** [comment]
@RickyTheRacc try using the rotate option or try walking in different angles

**Comment by D3V1LC0D3R** [comment]
an option maybe to make the water solid after 1/2 block or even 1/16 that might work. another option may be to spam the swim/space key

**Comment by D3V1LC0D3R** [comment]
duplicate of #556

**Comment by RedCarlos26** [comment]
These duplicates I swear 😅

**Comment by RedCarlos26** [comment]
@seasnail8169 this is a duplicate
