### ISSUE TITLE
[Suggestion] Tab Gui

### ISSUE THREAD

**Issue by xFadedxShadow** [MeteorDevelopment/meteor-client#1236]
**Describe the feature**
Tab Gui for players.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Something simple to add

**Comment by RickyTheRacc** [comment]
the fuck

**Comment by a-couple-objects** [comment]
wurst has a thing called tabgui which you navigate with the arrow keys+enter

**Comment by seasnail8169** [comment]
Meteor doesn't have a thing called tabgui which you navigate with the arrow keys+enter
