### ISSUE TITLE
Xray is broken in version 0.3.9

### ISSUE THREAD

**Issue by Computeiscool** [MeteorDevelopment/meteor-client#124]
when ever i turn on xray random faces of blocks show up and some targeted blocks are missing

**Comment by MineGame159** [comment]
What other mods do you have?

**Comment by Computeiscool** [comment]
Soduim and fabric api

**Comment by MineGame159** [comment]
Hm

**Comment by Computeiscool** [comment]
![2021-01-07_13 20 36](https://user-images.githubusercontent.com/74794251/103929398-429c2c80-50eb-11eb-91af-8b37b8c343eb.png)

**Comment by Computeiscool** [comment]
keep in mind that on version 0.3.8 there was no problem

**Comment by notseanyay** [comment]
Unrelated to the issue but use Baritone 😼

**Comment by robert0987654321** [comment]
I have the same problem

**Comment by ikearefrigerator** [comment]
this is happening to me too. works fine most of the time, but this happens somewhat often

**Comment by Whop42** [comment]
#204

**Comment by seasnail8169** [comment]
This should be fixed in 0.4.1? @ikearefrigerator please let me know if you are still having this issue
