### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by D1048596** [MeteorDevelopment/meteor-client#1240]
**Describe the bug**
Crash, apparently caused by indigo renderer during the rendering of a kelp block.

**To Reproduce**
All I did was log into the game next to an ocean (a shulker farm was also in the loaded chunks nearby, although this does not seem relevant from the crash report).
I have been unable to reproduce the crash in single player, but it has happened every time I logged into this server.

See attached crash report.

[crash-1 - Copy.txt](https://github.com/MeteorDevelopment/meteor-client/files/6824274/crash-1.-.Copy.txt)

**Comment by MineGame159** [comment]
Does it stop happenening when you remove Meteor?

**Comment by D1048596** [comment]
Yes.

**Comment by MineGame159** [comment]
If you can provide a way for us to reproduce this issue then write it here and reopen the issue.
