### ISSUE TITLE
[Suggestion] Improve Surround

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1241]
**Describe the feature**
- Keep it from activating or deactivating while using blink and freecam
- Add a mode to place two out in each direction to avoid city breaking
- Add options to toggle off modules like speed and step when activating
- Add an option to automatically toggle on when entering an obsidian hole
- Add an option to attack crystals that could potentially break surround
- Make only on sneaking center you every time you sneak
  (As of now it only centers you when the module is activated the first time)
- Add a keybind to place double high until the module is turned off
  (Could be useful for dealing with bed users)
- Add an "only apply if players in x range" setting, would be amazing 
  for builders who want to be able to surround when they need to without 
  being unable to crouch while building when noone is around

**Comment by RickyTheRacc** [comment]
(I understand if not _all_ of these are implemented but please at least add the first thing, it makes surround such a pain to use when you're in freecam and it disables because you're trying to move downward)

**Comment by necrophili** [comment]
Why would you wanna turn on surround in a bedrock hole tho

**Comment by RickyTheRacc** [comment]
What? Idk what you mean brain issue skill issue cope harder?
