### ISSUE TITLE
[Bug] Swarm Guide button causes freeze

### ISSUE THREAD

**Issue by SpaceClouds42** [MeteorDevelopment/meteor-client#1248]
**Describe the bug**
Clicking `guide` in the swarm module menu causes the game to freeze

**Expected behavior**
Not freezing

**Additional context**
1.17.1, build 1161

The link to the guide does successfully open, but the game then freezes completely.

**Comment by MineGame159** [comment]
We are just using the same method Minecraft itself uses for opening links.

**Comment by SpaceClouds42** [comment]
That doesn't change the fact that the game freezes _:thinking:_ This is an issue with meteor, not mc, because clicking on links in mc works fine, no freeze.
