### ISSUE TITLE
[Suggestion] Regex and words spam filters

### ISSUE THREAD

**Issue by D3V1LC0D3R** [MeteorDevelopment/meteor-client#1249]
**Describe the feature**
the antispam should be able to 1.) supress messages completely based on:
 - words or strings
 - regex
 - users

**Comment by D3V1LC0D3R** [comment]
this would block annoying players as well as advertisers that try to push their stupid discords

**Comment by MineGame159** [comment]
Better Chat can already do that (regex)

**Comment by D3V1LC0D3R** [comment]
where can you add the regex?

**Comment by D3V1LC0D3R** [comment]
so to clarify what i meant:
i want a denylist of words or regex that the user can edit and when something in the chat matches it gets blocked

**Comment by MineGame159** [comment]
Yes, exactly what filters do in Better Chat

**Comment by D3V1LC0D3R** [comment]
oops im sorry i missed that change 😞
