### ISSUE TITLE
Add potion effects to nametags

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#1250]
Meteor nametags should also display potion effects, along with the amount of time remaining.

**Comment by LDoom** [comment]
target hub add this, no nametag

**Comment by BowenGIT** [comment]
@LDoom can you please clarify?

**Comment by LDoom** [comment]
> @LDoom can you please clarify?

Add effects here 
![image](https://user-images.githubusercontent.com/73355762/126055836-88826f50-fada-486c-a5bf-57ce7f1623c9.png)

@MineGame159

**Comment by StormyBytes** [comment]
Duplicate of #797

**Comment by StormyBytes** [comment]
closed because duplicate
