### ISSUE TITLE
[fixed now] Baritone won't pause pathing when killaura attacks

### ISSUE THREAD

**Issue by Tendas240** [MeteorDevelopment/meteor-client#1252]
**Describe the bug**
Meteor should send (prefix)pause / (prefix)resume when killaura hits enemies in range like it does with autoeat but it doesn't.

**To Reproduce**
1. Have killaura activated
2. Have baritone pathing
3. be near a hostile mob
4. see how it just walks past or being stuck while trying to mine something and slay at the same time

**Expected behavior**
Meteor should send (prefix)pause / (prefix)resume when killaura hits enemies in range like it does with autoeat

**Screenshots**
A screenshot wouldn't help

**Additional context**
/

**Comment by WhoAmI2704** [comment]
dumbass go to kill aura settings and choose pause on combat

**Comment by Tendas240** [comment]
> dumbass go to kill aura settings and choose pause on combat

wow dude... that was the first thing i checked...
and thx for your kindness

**Comment by wxyzsupermod** [comment]
I am not familiar with the project but I took a look and it appears the code for this is there but commented out I uncommented it and am testing it seems to be working fine I am stress testing by having baritone mine diamond ore which it was not able to do before.

**Comment by Tendas240** [comment]
> I am not familiar with the project but I took a look and it appears the code for this is there but commented out I uncommented it and am testing it seems to be working fine I am stress testing by having baritone mine diamond ore which it was not able to do before.

okay thanks for investigating and letting me/us know. So that means it got removed accidentally? Okay so maybe the developers will find it out or find this post and fix it in future versions..

**Comment by wxyzsupermod** [comment]
> > I am not familiar with the project but I took a look and it appears the code for this is there but   ##commented out I uncommented it and am testing it seems to be working fine I am stress testing by having baritone mine diamond ore which it was not able to do before.
> 
> okay thanks for investigating and letting me/us know. So that means it got removed accidentally? Okay so maybe the developers will find it out or find this post and fix it in future versions..

I've posted the "fix" as a pull request if the main devs like it it'll get posted but until then you can easily recompile the code yourself with the change

**Comment by Tendas240** [comment]
> > > I am not familiar with the project but I took a look and it appears the code for this is there but   ##commented out I uncommented it and am testing it seems to be working fine I am stress testing by having baritone mine diamond ore which it was not able to do before.
> > 
> > 
> > okay thanks for investigating and letting me/us know. So that means it got removed accidentally? Okay so maybe the developers will find it out or find this post and fix it in future versions..
> 
> I've posted the "fix" as a pull request if the main devs like it it'll get posted but until then you can easily recompile the code yourself with the change

alright thank you! 
I don't have any experience on how to do that... I don't know how i would do that :'D

**Comment by mathmakgakpak** [comment]
should be fixed in a8192d273c2f370914b28c8617af55dfc0de1577
