### ISSUE TITLE
[Suggestion] Option to disable tracers for friends

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1255]
Would be very appreciated
Because chasing someone with friends is complicated and it could be way easier

**Comment by Lovecrafts-Cat** [comment]
This should be already an option i think, look in the configs of the Tracers module 👀

**Comment by TyraVex** [comment]
> This should be already an option i think, look in the configs of the Tracers module 👀

Gonna look closer but i don't remember finding it
I was chasing someone thogh

**Comment by TyraVex** [comment]
![IMG_20210719_222927](https://user-images.githubusercontent.com/34800546/126223065-7bc20641-d490-4911-b2c8-07e39b4f5aa8.jpg)

I am playing on 0.4.4 but i don't think it's on 0.4.5
