### ISSUE TITLE
so when ever i try to load into any kind of server whether its a world or realm it crashes and then has the exit code of 0

### ISSUE THREAD

**Issue by shvxxzn** [MeteorDevelopment/meteor-client#1256]
![Screenshot_33](https://user-images.githubusercontent.com/87668448/126207101-8dd939df-a0b6-432e-8652-4abc05fa0241.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by seasnail8169** [comment]
open a ticket in the discord
