### ISSUE TITLE
[Suggestion] Render Trajectories for Other Players

### ISSUE THREAD

**Issue by chaperiez** [MeteorDevelopment/meteor-client#1258]
**Describe the feature**
Add an option to the "Trajectories" module to render trajectory paths for other players when holding a projectile.

**Screenshots**
What it would look like:
![example1](https://user-images.githubusercontent.com/87503920/126260507-b247727b-8776-4572-b70b-36f77abf2f24.jpg)
![example2](https://user-images.githubusercontent.com/87503920/126260648-ddc158ad-d0ad-4e2b-a9df-73c73fcddc99.jpg)

**Additional info**
Being able to select different colors for friends and threats (if implemented) would be nice as well.

**Comment by MineGame159** [comment]
Added in 050d53d043f5a4cc555a9e0bc416b982bd3fb38e
