### ISSUE TITLE
[Bug] Crashes on ARM Linux.

### ISSUE THREAD

**Issue by timof121** [MeteorDevelopment/meteor-client#1260]
**Describe the bug**
Meteor client crashes on linux at the state of loading, I think its because DiscordRPC from the logs (theres no discordrpc for ARM)

**To Reproduce**
1. Run Meteor on ARM linux (or an arm vm)
2. You'll see how it crashes

**Expected behavior**
Meteor should load and work??

**Screenshots**
no
**Additional context**
Using sodium, fabric api, fabric kotlin, and meteor. heres the log 
https://hastebin.com/koqiqojigu.sql

A solution would be make so meteor can handle discordrpc being unavailable and simply starting without it.

**Comment by timof121** [comment]
no, this isnt pojavlauncher, its linux

**Comment by MineGame159** [comment]
The log you posted is invalid

**Comment by timof121** [comment]
oops 1 sec

**Comment by timof121** [comment]
done

**Comment by a-couple-objects** [comment]
for a manual fix you can just remove discordrpc

**Comment by timof121** [comment]
How i do that? I removed the discordrpc libraries, and the classes that contain"discord"

**Comment by timof121** [comment]
it crashes with saying that its missing

**Comment by JFronny** [comment]
- clone the source code
- remove the discord rpc dependency
- remove the DiscordPresence module and other references to the lib
- profit

Or just use my fork, it doesn't include that feature

**Comment by timof121** [comment]
Thanks
