### ISSUE TITLE
Squidoodly is a loser!

### ISSUE THREAD

**Issue by abt5** [MeteorDevelopment/meteor-client#1261]
NOBODY LIKES HIM HE SUCKS!!

**Comment by C10udburst** [comment]
@squidoodly

**Comment by Wide-Cat** [comment]
squidoodly is great, you are clearly just uncultured

**Comment by squidoodly** [comment]
Nooooooooooo. Please take it back. 😭😭😭
Please bro. I can’t take it. I’m coping so hard. 🥺🥺🥺🥺🥺
