### ISSUE TITLE
Radar feature

### ISSUE THREAD

**Issue by Uzername6942069** [MeteorDevelopment/meteor-client#1262]
Adding a radar that detects and displays selectable entities and/or nearby ores and chests and waypoints aswell as north south east and west

![Screenshot 2021-07-20 093436](https://user-images.githubusercontent.com/87708219/126333429-7808bb59-4812-4aca-b019-fb50327126f2.jpg)
![radarbro-1-9](https://user-images.githubusercontent.com/87708219/126333430-873fda0e-b9ad-42fa-b7d0-315b79e8660a.jpg)

**Comment by seasnail8169** [comment]
just use a minimap mod
