### ISSUE TITLE
[Suggestion] New options/modules for anchor pvp/cpvp

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1268]
Auto pillar option in anchor aura:
Automatically builds a pillar to place anchors above players
Very useful for servers disabling air placement

Auto self trap:
Replaces exploded anchors/crystals near player with obsidian (counters anchor aura/cpvp based on trapping)

Auto chorus:
When trapped, and when auto self trap fails (due to ping for example) automatically uses chorus fruit

Better autogap:
Option to make it eat the apple fully even if the health regenerates 

Better auto log:
Option to trigger it based on:
- the number of totems remaining
- if trapped in an obsidian cage
- if armor breaks/is low
- if no items of a specific type in inventory

Auto xp thrower:
Triggers when one piece of armor is below a specific percentage

**Comment by RedCarlos26** [comment]
Make separate suggestions for each request it is easier for seasnail and minegame to manage @TyraVex
