### ISSUE TITLE
[Suggestion] AutoMine and AutoPlace

### ISSUE THREAD

**Issue by snnwer** [MeteorDevelopment/meteor-client#1269]
**Describe the feature**
Auto Mine speaks for itself, it holds left click or mines the block without you holding it. Now, this might be useful since to mine blocks with baritone faster, you have to enable Auto Mine (which meteor doesn't have yet) or hold down left click, and it will be useful with Auto Place.

Auto Place will, as simple as auto mine is, place blocks that you're holding, which can be useful for bridging (lmao hell nah) and converting ores into items.

**Screenshots**
None available

**Additional info**
None

**Comment by mathmakgakpak** [comment]
1. it's called packet mine
2. why

**Comment by snnwer** [comment]
> 1. it's similar to packet mine but ok
> 2. why

1. no, packet mine sends packets to mine it and it's not automatic, automine automatically mines blocks clientside.
2. reread my suggestion lol

**Comment by StormyBytes** [comment]
This is already a feature in AutoClicker. 
Its under the `Mode` setting.
Make sure the feature you are suggesting doesnt already exist before submitting a new issue.

AutoPlace is the same. Just change the `Mode` to `Hold` and the `Button` to `Right`

**Comment by RedCarlos26** [comment]
@MineGame159

**Comment by snnwer** [comment]
> This is already a feature in AutoClicker.
> Its under the `Mode` setting, change it to `Hold`.
> Make sure the feature you are suggesting doesnt already exist before submitting a new issue.
> 
> AutoPlace is the same. Just change the `Button` to `Right`

you cant use both of them at the same time plus you have to keep chat off n bullshit like that, I want to both chat and use freecam

**Comment by RedCarlos26** [comment]
> "Bullshit"

You can code the client if I want lmfao. Like bruh, a bit of respect for the devs pls

**Comment by snnwer** [comment]
> > "Bullshit"
> 
> You can code the client if you want lmfao. Like bruh, a bit of respect for the devs pls

who said I don't respect them? plus, if I'd be able to do shit in java I'd do a lot of forks already, it's just meteor doesn't get a lot of major updates nor doesn't get a lot of modules added so I'm trying to get them to do that
