### ISSUE TITLE
[Bug] Stash finder toast notification

### ISSUE THREAD

**Issue by fuckcuff** [MeteorDevelopment/meteor-client#1271]
**Describe the bug**
Stash finder toast notification bug

**To Reproduce**
1. use 0.4.5 build
2. find a stash with toast notifications on

Screenshot:
![Screenshot_3](https://user-images.githubusercontent.com/67871539/126634134-aa18a4f5-116b-4c78-a949-b07bb457b0f8.png)

**Comment by MineGame159** [comment]
Should be fixed in 40cc074159ea37338ff25d16657e384a2eb0dd6c. I cannot test myself because it only happens in specific conditions but if it still happens type here and I will reopen it.
