### ISSUE TITLE
[Suggestion] max enchant per type

### ISSUE THREAD

**Issue by Rabkaleta** [MeteorDevelopment/meteor-client#1275]
**Describe the feature**
Add [.enchant <all,all_posible,one> max] to enchant max level of enchant type (not 32k)

**Screenshots**
![2021-07-23_00 21 38](https://user-images.githubusercontent.com/84437677/126682120-67c2ffa7-8aac-44bb-a00b-c7880a936ade.png)
![2021-07-23_00 22 24](https://user-images.githubusercontent.com/84437677/126682152-2958a9ef-dbc2-4db6-a700-825831f39a23.png)

**Additional info**
sorry my english bad :<

**Comment by MineGame159** [comment]
Added in 9b9a72c602dee1ce50882ff49c8a9ed49d7dee8f
