### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kiven7e** [MeteorDevelopment/meteor-client#1277]
**Describe the bug**
 Error 522 on meteorclient.com

**To Reproduce**
1. visit meteorclient.com

**Expected behavior**
search browser should connect to meteorclient.com

**Comment by MineGame159** [comment]
I know

**Comment by kiven7e** [comment]
can i have a link to the discord?

**Comment by mathmakgakpak** [comment]
@kiven7e https://discord.gg/ykeU6WQVfu
