### ISSUE TITLE
Add Auto Mine/Break

### ISSUE THREAD

**Issue by Exustine12** [MeteorDevelopment/meteor-client#1280]
Add auto mine as it comes in use when mining or removing a thousand layers of obsidian that would be helpfull

**Comment by StormyBytes** [comment]
Baritone

**Comment by Exustine12** [comment]
No cause i strip mine in a server which says no to baritone

**Comment by Wide-Cat** [comment]
dont use meteor on servers that arent allowed, also what would this 'auto mine' do thats in any way different to what baritone already does?

**Comment by RickyTheRacc** [comment]
Rofl
