### ISSUE TITLE
[Bug] Getting damage while using No Fall.

### ISSUE THREAD

**Issue by satelite000** [MeteorDevelopment/meteor-client#1281]
**Describe the bug**
 The local player getting damage while using No Fall & Flight together.

**To Reproduce**
Use the cheat for some time

**Expected behavior**
Does not get damage from flight usage

**Video**
https://youtu.be/rAH2g_l4zbA

**Additional context**
Meteor version 0.45, reworked No fall.

**Comment by mathmakgakpak** [comment]
duplicate of #1247
