### ISSUE TITLE
[Bug] The inventory HUD doesn't work correctly

### ISSUE THREAD

**Issue by MrEAZL** [MeteorDevelopment/meteor-client#1282]
**Describe the bug**
The texture of inventory HUD at the top of the screen is broken and it only shows black, the items still show up.

**Expected behavior**
The HUD needs to show the texture of your inventory.

**Screenshots**
https://some.questionable.link/554Ehi2Eb

**Additional context**
Meteor 0.4.5, Minecraft 1.17.1, Sodium 0.3.0+build.5 and Lithium 0.7.3

**Comment by MineGame159** [comment]
What is your OS and GPU

**Comment by MineGame159** [comment]
Fixed in 40cc074159ea37338ff25d16657e384a2eb0dd6c
