### ISSUE TITLE
Better swinging animations for swords and items[Suggestion]

### ISSUE THREAD

**Issue by iTwisten** [MeteorDevelopment/meteor-client#1283]
**Describe the feature**
cool and custom swinging animations for hitting and swinging with items.

**Screenshots**
https://media.giphy.com/media/ht6RiVfmGc6kITf6W6/giphy.gif
https://media.giphy.com/media/ht6RiVfmGc6kITf6W6/giphy.gif
https://media.giphy.com/media/ht6RiVfmGc6kITf6W6/giphy.gif

**Additional info**
Add any other info.

**Comment by mathmakgakpak** [comment]
why did you paste 3 copies

**Comment by iTwisten** [comment]
> why did you paste 3 copies

why not
