### ISSUE TITLE
[Bug]Unfocused CPU doesn't properly prevent the window from unfocusing

### ISSUE THREAD

**Issue by O3nboi** [MeteorDevelopment/meteor-client#1287]
**Describe the bug**
In the latest version of Meteor client, the module "Unfocused CPU" does not prevent the Esc menu from opening if the window is unfocused.

**To Reproduce**
1. On the latest version of meteor, join a world.
2. Activate the "Unfocused CPU" module.
3. Use Alt+TAB or Win+D to minimise the window, and open it back up
4. See error (Game is paused and all actions have ceased)

**Expected behavior**
The expected behaviour is for all actions currently taking place to continue running, and the game to not get paused

**Screenshots**

**Additional context**
This bug only happens on the latest version (0.4.5 at time of post) and happens with no additional mods.

**Comment by MineGame159** [comment]
Thats not what Unfocused CPU is supposed to do. Its supposed to not render the game while the window is not focused and thus not consume so much CPU and GPU resources. This should be put as a suggestion insteaf of a bug.

**Comment by O3nboi** [comment]
The problem i had was that this DID work in the previous version, and I had been using it, but since then it has stopped working in the same way.

**Comment by MineGame159** [comment]
Well then it wasn't intended and I didn't know about it

**Comment by O3nboi** [comment]
Attached is footage of an older version working as described:
https://user-images.githubusercontent.com/72664566/126868634-a3f74417-26fb-4293-94d4-1cd5ca35886e.mp4
