### ISSUE TITLE
[Suggestion]Unfocused CPU prevent the Esc menu from opening

### ISSUE THREAD

**Issue by O3nboi** [MeteorDevelopment/meteor-client#1288]
**Describe the feature**
In the last version (0.4.4) there was a feature that allowed you to leave something running (e.g using the F3+T bug to hold down the mouse button) and then use the "Unfocused CPU" module to leave the window running while minimized, and it would not open the pause menu. However, in the latest version, this no longer is the case and I had been using this feature for a while. I would like for this to be added back.

**Screenshots**
N/A

**Additional info**
This feature already existed in 0.4.4, but not in 0.4.5

**Comment by O3nboi** [comment]
Attached is a recording of the intended behavior (recorded on an old version)
https://user-images.githubusercontent.com/72664566/126868634-a3f74417-26fb-4293-94d4-1cd5ca35886e.mp4

**Comment by seasnail8169** [comment]
This never was a "feature" and nothing about unfocused cpu changed.

**Comment by O3nboi** [comment]
i forgot F3+P was a thing
