### ISSUE TITLE
Version check for new update notification

### ISSUE THREAD

**Issue by SArpnt** [MeteorDevelopment/meteor-client#1289]
when i start minecraft running meteor 0.4.4 on 1.16.5,  it gives a notification to update to 0.4.5, which only works on 1.17, and not the version i'm running. i can't test this on newer versions of course, but if it hasn't been changed, it would be better if there was some kind of version check so that if the new meteor version doesn't run on the same version of minecraft, that either the notification doesn't appear or it shows a disclaimer.

![image](https://user-images.githubusercontent.com/36542932/126871732-e7353bfa-667b-4889-a75b-b30669c6dad9.png)

**Comment by C10udburst** [comment]
1.16.5 is outdated. Update please

**Comment by SArpnt** [comment]
i can't just magically update every single mod i use, i shouldn't just be expected to always constantly run the version of minecraft that happens to fit meteors development speed.

**Comment by RickyTheRacc** [comment]
And we're asking you to stop being sped. It takes maybe half an hour to download 1.17 jars, use multiconnect and don't open useless issues

**Comment by SArpnt** [comment]
"download 1.17 jars"
do you think every single minecraft mod that has ever been made will always be up to date at the exact same time as meteor, for every update that will ever happen?
i'm suggesting a small bit of text for future versions, so that this doesn't happen when 1.18 comes out.
