### ISSUE TITLE
[Bug] Baritone issue

### ISSUE THREAD

**Issue by Kapyyyy** [MeteorDevelopment/meteor-client#1292]
**Describe the bug**
Baritone fails at pathing on mp server

**To Reproduce**
Tested in sp, pathing works with my current setup. Moved to a papermc server that's hosted on my machine pathing fails to go anywhere

**Screenshots**
https://gfycat.com/SlowNaturalJavalina

**Additional context**
Mc 1.17.1 running fabric, mods folder contains latest public release of meteor (0.4.5), fabric api, and voxelmap

**Comment by StormyBytes** [comment]
Report this on baritone, not on meteor.
