### ISSUE TITLE
[Suggestion] Differentiate team

### ISSUE THREAD

**Issue by Re10ad** [MeteorDevelopment/meteor-client#1293]
**Describe the feature**
Differentiate team by color of leather armor or nametags. Affects some combat modules like Aimbot and Killaura.

**Screenshots**
Maybe no need.

**Additional info**
Usually used for Server events or Team duels.

**Comment by chaperiez** [comment]
You wouldn't need this module unless you're on some sort of minigame server, which I doubt permits utility mods like meteor. Teams functionality would be hard to implement across servers as nametag styles & armor patterns vary based on what you're playing; it simply wouldn't be reliable. If you want a solution, just use MCF or manually add your teammates as friends.
