### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by tomasventura13** [MeteorDevelopment/meteor-client#1294]

**Comment by Wide-Cat** [comment]
inb4

**Comment by StormyBytes** [comment]
1. Its not as simple as you may expect. What if someone leaving the tab list actually exited the game instead of going into spectator mode? 
2. Stop using meteor in servers that dont allow it.

**Comment by RedCarlos26** [comment]
> 1. Its not as simple as you may expect. What if someone leaving the tab list actually exited the game instead of going into spectator mode? 
> 
> 2. Stop using meteor in servers that dont allow it.

The point 2 is the reason why this will probably never be added

**Comment by TheRedHippo** [comment]
Usernames turn to italics whenever a player enters spectator mode on most servers, which is what they're referring to.

**Comment by tomasventura13** [comment]
> 1. Its not as simple as you may expect. What if someone leaving the tab list actually exited the game instead of going into spectator mode?
> 2. Stop using meteor in servers that dont allow it.

The Horizon is a youtuber that uses hacked clients, especially meteor on pay2win servers that dont allow it, and hes doing something good, i think iw tould be amazingly good

and btw it would know if a player enters spectator mode because in the tab a player in spectator has his name in italics
