### ISSUE TITLE
I got logged in as seasnail and cant change it please help

### ISSUE THREAD

**Issue by Falcon23K** [MeteorDevelopment/meteor-client#1297]
I got logged in as "seasnail" and cant change it please help

**Comment by FolfyBlue** [comment]
This is your life now. No going back, seasnail.

**Comment by Falcon23K** [comment]
Deleted files, now fixed if anyone has the same issue delete the "meteor-client" folder in the miecraft folder

**Comment by seasnail8169** [comment]
Its actually caused by the Name Protect module and its a feature not an issue.

**Comment by Falcon23K** [comment]
nice feature I now will try to use it more often
