### ISSUE TITLE
[Suggestion] Xray optimisation

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1301]
**Describe the feature**
Instead of rendering every side of every xray block, only render sides that are connected to air or a transparent block.

**Screenshots**
Current xray rendering:
![xraybad](https://user-images.githubusercontent.com/67818307/127130355-23b43c55-7991-47bc-bbc2-00afac54316d.png)

New xray rendering:
![xraygood](https://user-images.githubusercontent.com/67818307/127130377-0866b63c-f74d-443a-a16a-90f93f3117cb.png)

**Additional info**
Will drastically improve FPS when there are lots of ores around (eg when you accidentally toggle xray on a server with antixray, and your game drops to 2 fps)

**Comment by MineGame159** [comment]
![2021-08-12_22 54 40](https://user-images.githubusercontent.com/25082624/129268552-6b58cdbd-d3f4-4bb6-903d-14460a24a999.png)
![2021-08-12_22 54 51](https://user-images.githubusercontent.com/25082624/129268558-4bca7a4a-0412-473c-8c79-9df23517ac67.png)
