### ISSUE TITLE
[Bug] baritone's auto tool fights with meteor's auto tool

### ISSUE THREAD

**Issue by mathmakgakpak** [MeteorDevelopment/meteor-client#1304]
**Describe the bug**
baritone 

**To Reproduce**
1. Enable auto tool
2. Open options of auto tool and set prefer to fortune
3. Get a fortune pickaxe and normal sword
4. watch the vid**oe** original: https://mirrorace.org/m/5MG9a
![GIF](https://user-images.githubusercontent.com/44949126/127216572-75090269-446d-4f50-b929-42de1ad380c9.gif)

**Expected behavior**
stop using meteor's auto tool when baritone is mining

**Additional context**
meteor client v0.4.6 build #1175

**Comment by seasnail8169** [comment]
just disable baritone auto tool

**Comment by WhoAmI2704** [comment]
fucking just turn off ur client autotool or do assumeExternalAutoToolFalse

**Comment by mathmakgakpak** [comment]
seasnail already said that i understood first time
