### ISSUE TITLE
[Bug] Jesus leading to frequent crashes.

### ISSUE THREAD

**Issue by CyfunZuZu** [MeteorDevelopment/meteor-client#1305]
**Describe the bug**
When using Jesus, ~50% of the time the game will start to lag heavily, then save the world and close the game.

**To Reproduce**
Enable Jesus, all default settings. Sprint/Jump around on water.

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).
Meteor 0.4.5, Fabric 1.17.1, no other mods.

**Comment by Wide-Cat** [comment]
if you dont send the crash report then theres nothing we can do about it

**Comment by MineGame159** [comment]
Cannot reproduce and you did not provide any crash reports
