### ISSUE TITLE
Dont working with OptiFabric.[BUG]

### ISSUE THREAD

**Issue by Ebanytiy** [MeteorDevelopment/meteor-client#1306]
![conflicting with optifabric](https://user-images.githubusercontent.com/87265332/127265328-a6fc3969-8cad-4882-939e-0c92ec5f3725.png) 
Found conflicting mods: optifabric conflicts with {meteor-client @ [>=0.4.1]}

**Comment by ehylo** [comment]
Meteor is not compatible with optifine, please read [this list](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) of better optifine alternatives

**Comment by WhoAmI2704** [comment]
fucking nerd at least read faq before making a shit issue

**Comment by Lovecrafts-Cat** [comment]
Even with #general locked we cannot evade these  requests...
