### ISSUE TITLE
[Bug] Alt Manager

### ISSUE THREAD

**Issue by satelite000** [MeteorDevelopment/meteor-client#1307]
**Describe the bug**
Alt manager stopped support the nicknames with a spacebar

**To Reproduce**
1. Go to alt manager
2. Click on cracked
3. Enter the nickname that contains a space between two parts
4. Get crashed

**Expected behavior**
An new account got added to alt manager like in 0.4.4 version

**Additional context**
Bug is created between 0.4.4 and 0.4.5 version builds

**Comment by mathmakgakpak** [comment]
minecraft doesnt support names with spacebar but this still doesn't change that it shouldn't crash the game

**Comment by NIGHTMARIO** [comment]
Minecraft names aren't supposed to have space. Check thiS article for more info: 
https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Java-Edition-Username-FAQ

**Comment by masranber** [comment]
https://help.minecraft.net/hc/en-us/articles/360034636712-Minecraft-Java-Edition-Username-FAQ
> What are the requirements for creating a username? 
> 
> Must have 3-16 characters 
> No Spaces are allowed between characters 
> Accepted characters: 
> 
> A-Z (upper and lower case) 
> 0-9 
> The only special character accepted is _ (underscore) 

The solution should be as simple as adding a filter to the username text input. Any server will refuse the connection if the username is invalid anyways, so it makes sense to block them from even being input in the first place.
