### ISSUE TITLE
killaura not working[Bug]

### ISSUE THREAD

**Issue by lamboaddict** [MeteorDevelopment/meteor-client#1311]
**Describe the bug**
the killaura isnt working
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
im on 1.17.1 and using normal settings

**Comment by StormyBytes** [comment]
Have you set the entities you want to target?
Also make sure the weapon to use is set properly.

**Comment by lamboaddict** [comment]
what settings should i put it at then

**Comment by Sam2004-2** [comment]
You have provided no actual evidence of an issue
