### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kittshy** [MeteorDevelopment/meteor-client#1314]
**Describe the bug**
When the no fall is enabled and you flight quickly down and hit a block you take damage anyway and in certain cases when you just go down when flying you take damage too, like if the no fall wasn't enabled. 
**To Reproduce**
1. Enable "no fall" (packet) and "flight" (vanilla) 
2. Fly up away 
3. Go down rapidly and at the same time go forward with W or Z and hit yourself to a block
4. With this step you will normally take damage. 

**Expected behavior**
When you have no fall you normally don't have to take the damage in anayway possible but in this case with paket no fall you them anyway 

**Screenshots**
can't 

**Additional context**
Last DEV build version of meteor on 1.17.1

**Comment by seasnail8169** [comment]
already reported
