### ISSUE TITLE
[Suggestion] Light Overlay and Spawn proofer should ignore bedrocks

### ISSUE THREAD

**Issue by system-** [MeteorDevelopment/meteor-client#1315]
**Describe the feature**
Light Overlay and Spawn proofer should ignore bedrocks, or consider it as already spawn proof, since it's not a spawnable block, and please consider adding facing option to spawn proofer.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by StormyBytes** [comment]
By facing option do you mean the option to place on walls or on ground?

**Comment by system-** [comment]
> By facing option do you mean the option to place on walls or on ground? Or something else?

I was thinking of telling the server that your character is facing the block you're placing on, but letting all the buttons facing the same direction would be a nice addition too.

**Comment by StormyBytes** [comment]
That is already a feature, it's the setting named "rotate".

**Comment by system-** [comment]
> That is already a feature, it's the setting named "rotate".

Nice, what about the bedrock part?

**Comment by StormyBytes** [comment]
PR'ed it already.
