### ISSUE TITLE
[Bug] Norender particle crashes game

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1320]
**Describe the bug**
Adding the flash particle in particle blocker, then rendering that particle will crash your game. (ticking particle)

**To Reproduce**
1. Open NoRender
2. Go to particle blocker
3. Enable particle "flash"
4. Enable NoRender module
5. Launch a firework with a firework star

**Expected behavior**
Particle is blocked, game doesn't crash

**Additional context**
No other mods
Tested on dev build 1180 (latest) and 1166 
[crash-2021-07-31_19.35.04-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6910964/crash-2021-07-31_19.35.04-client.txt)

**Comment by radiden** [comment]
Works as of dev build 1244
