### ISSUE TITLE
[Bug] HUD not showing up and can’t move modules along Y axis. 

### ISSUE THREAD

**Issue by dbuldum4** [MeteorDevelopment/meteor-client#1323]
**Describe the bug**
The hud does not show up. At all. I can’t move modules vertically. 
Additionally, I cannot break blocks in single player. 
**To Reproduce**
1. Be me
2. Edit HUD
3. Does not exist

**Expected behavior**
I expected the desired HUD changes to appear on my screen after closing the menu. 

**Screenshots**
It just looks like vanilla Minecraft. 

**Additional context**
Using Lithium, Iris, and MultiConnect on MultiMC. Latest update.

**Comment by MineGame159** [comment]
Do you have HUD module enabled
