### ISSUE TITLE
crash when mining

### ISSUE THREAD

**Issue by energy11a** [MeteorDevelopment/meteor-client#1325]
Crash when you mine a block

**To Reproduce**
1. go to survival and mine stone.
2. it will crash moment after breaking stone

Crash when you mine a block and after crash everything is tilted.

**Screenshots**
![2021-08-01_19 08 57](https://user-images.githubusercontent.com/46869399/127778538-1fe9dfe1-45d4-4c0c-ba12-36cf171299e0.png)
![2021-08-01_19 02 47](https://user-images.githubusercontent.com/46869399/127778542-1b1e06ac-5249-48bf-a14b-4e7d8eeeba2e.png)
![2021-08-01_19 06 19](https://user-images.githubusercontent.com/46869399/127778543-e8f1cb5f-9c7b-41cc-bae4-d239fabc277b.png)
![2021-08-01_19 06 28](https://user-images.githubusercontent.com/46869399/127778546-d7381d08-55e7-4404-a179-9389732d39be.png)
![2021-08-01_19 07 13](https://user-images.githubusercontent.com/46869399/127778548-76d6cbb3-8d35-4a8f-9c64-bdfdef136d05.png)
![2021-08-01_19 08 34](https://user-images.githubusercontent.com/46869399/127778550-7a22a044-7e00-496c-9c35-af14e224f1ad.png)

**Additional context**
I used meteor 0.4.5 and "not enough crashes" to see tilted after crash
I didn't crash if didn't have anything in meteor turned on
Everything included in gdrive (zip) https://drive.google.com/file/d/1YQtg7pViHrJdWJO82LH4yDj9GlE3xoNN/view?usp=sharing
(folder) https://drive.google.com/drive/folders/18hSTXBowzvUZbKTTSKe0zXpeUouEdjba?usp=sharing

**Comment by MineGame159** [comment]
Update to latest dev build
