### ISSUE TITLE
i need help downloading meteor client jar file for 1.16.5 please help[Suggestion]

### ISSUE THREAD

**Issue by Cudz** [MeteorDevelopment/meteor-client#1326]
**Describe the feature**
A clear and concise description of what feature/change is. make 1.16.5 easily accesable

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by ehylo** [comment]
Older versions are unsupported, use [multiconnect](https://github.com/Earthcomputer/multiconnect/releases)
