### ISSUE TITLE
[Suggestion] Better extra elytra

### ISSUE THREAD

**Issue by Kraken12112** [MeteorDevelopment/meteor-client#1329]
**Describe the feature**
A clear and concise description of what feature/change is.
Just change the elytrafly to the one wurst has called "extra elytra". When active, you get an elytra boosts not like a firework but a proportional boost when you hold w it's hard to explain here but if you try it out, you will understand what I mean. Also when you jump, it automatically goes into elytra mode.
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by MunchyG** [comment]
yes please, i have switched to meteor for baritone integration from wurst and meteor is better in every way except the elytra hack

**Comment by StormyBytes** [comment]
1. You can modify `horizontalSpeed` and `verticalSpeed` to more or less match vanilla's. Unless you're talking about a precise mimic of vanilla's elytra but at that point why are you even using ElytraFly lol. 
2. `autoTakeOff` is already a setting in ElytraFly.
