### ISSUE TITLE
[Bug] No interact

### ISSUE THREAD

**Issue by necrophili** [MeteorDevelopment/meteor-client#1330]
No interact does not let you place blocks on normal mode,
On packet mode it only places ghost blocks

**To Reproduce**
1. Turn on normal mode, turn on surround (no blocks will show)
2. Turn on packet mode, turn on surround (blocks will show but these are ghost blocks)

**Expected behavior**
No interact is meant to only prevent the inventory/screen gui to appear
Perhaps this should be made into another module

**Screenshots**

**Additional context**
Dev build 1186

**Comment by RedCarlos26** [comment]
I cannot reproduce
