### ISSUE TITLE
ka wont attack the same mob immeidately after the smart delay is done[Bug]

### ISSUE THREAD

**Issue by iTwisten** [MeteorDevelopment/meteor-client#1331]
**Describe the bug**
when ka attacks a mob it just pauses and doesnt attack for a long time even after the weapon cooldown thing is done

**To Reproduce**

**Expected behavior**
it to attack immediately once the smart delay is over

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by MineGame159** [comment]
Cannot reproduce
