### ISSUE TITLE
[Suggestion] Advanced scaffold blocks

### ISSUE THREAD

**Issue by DzakXtreme** [MeteorDevelopment/meteor-client#1333]
**Describe the feature**
Add slab and stair to scaffold

**Screenshots**

**Additional info**

**Comment by trimpta** [comment]
You cant select it from blocks menu?

**Comment by DzakXtreme** [comment]
Yeah i can pick and add to whitelist, but it doesn't work, i still fall while trying to scaffold with slabs and any other block

**Comment by seasnail8169** [comment]
scaffold only works with full blocks

**Comment by RedCarlos26** [comment]
> scaffold only works with full blocks

Maybe removing the non full blocks from the block scaffold list would be a good option then

**Comment by ztgasdf** [comment]
@arlomcwalter Will slab scaffolding ever be implemented?

**Comment by arlomcwalter** [comment]
> @arlomcwalter Will slab scaffolding ever be implemented?

will nuclear fusion ever be sustainable on earth?

**Comment by arlomcwalter** [comment]
> I wouldn't know. Whatever, Atomic has semi-functional slab scaffolding.

use it then

**Comment by Waveluke** [comment]
I'd also like this feature, as it would assist with rapid spawnproofing of big areas, such as preventing striders from spawning in the nether, as well as bridging with limited resources (crafting cobblestone into slabs to stretch what you can place).
