### ISSUE TITLE
[Suggestion] Light mode for the ClickGUI

### ISSUE THREAD

**Issue by DzakXtreme** [MeteorDevelopment/meteor-client#1334]
**Describe the feature**
A light mode for ppl who hate dark theme/wants light theme, and provide a neat and modern GUI
**Screenshots**
![image](https://user-images.githubusercontent.com/88361815/127957141-9a34556b-d720-4b57-be3f-ad0aa1a1b600.png)
![image](https://user-images.githubusercontent.com/88361815/127957158-18bcb1cb-72cc-4737-91f4-c3465a25cd6f.png)

**Additional info**
Add Meteor-light to the theme dropdown menu

**Comment by seasnail8169** [comment]
Themes aren't for colors, they are for widget designs. There us no reason to have a "light theme" because anyone can change the colors however they would like.

**Comment by dadudeme** [comment]
Light mode is painful
