### ISSUE TITLE
Build Output Location?

### ISSUE THREAD

**Issue by LynxPopulus** [MeteorDevelopment/meteor-client#1336]
**Describe the bug**
Pretty simple question: does anyone know where the build output is?

**To Reproduce**
1. Change meteor code by adding a comment `//test` at the start of `Main.java`
2. Open PowerShell in the location
3.  `./gradlew.bat`

**Expected behavior**
`.jar` in the root directory

**Comment by MineGame159** [comment]
/build/libs

**Comment by LynxPopulus** [comment]
The only subfolders in the `build` folder are:

classes
generated
loom-cache
tmp

(I'm on Windows btw)
