### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by DzakXtreme** [MeteorDevelopment/meteor-client#1338]
**Describe the feature**
Add search bar inside Container GUI to make finding items easier 

**Screenshots**
![image](https://user-images.githubusercontent.com/88361815/128195500-0022eef0-9d8a-4bca-8104-098cb794ea7c.png)

**Additional info**

**Comment by TheRedHippo** [comment]
yis and make the text stay after gui close, so you can open another chest and not have to retype it to find the item you want.
way better then going into the menu to configure item highlight and enabling it, then disabling once you're done

**Comment by MunchyG** [comment]
use REI it already has this feature

**Comment by DzakXtreme** [comment]
thx for the answer. finally found invsearch mod
