### ISSUE TITLE
Auto Crystal and Auto Totem Offhand Interferance

### ISSUE THREAD

**Issue by GoldenAureuz** [MeteorDevelopment/meteor-client#1340]
When using crystal aura, whenever autototem switches the offhand to a totem, it won't switch back to the crystal and they rapidly switch back and forth. It fixes itself when you open and close the inventory.

To reproduce the bug, make a fakeplayer, turn on Offhand CA (with Smart Auto Totem already enabled), and hit yourself with your own crystals until autototem switches your offhand to a totem. Eat gaps in your mainhand until you have enough health to switch back and see what happens.

Totem switches back to the Crystal after health is back to stable level.

https://user-images.githubusercontent.com/62858980/128260853-867817cf-e615-4ff7-bc34-4eeef9d13ebb.mp4

The bug was found in dev build #1184

**Comment by RedCarlos26** [comment]
@GoldenAureuz just close this bug report since you have made a new one
