### ISSUE TITLE
Support for localization (translation)?

### ISSUE THREAD

**Issue by buiawpkgew1** [MeteorDevelopment/meteor-client#1341]
### **Description**
Will meteor-client support localization?
I want to translate meteor-client through the lang file so that other users can also translate meteor-client into their language.

**Comment by seasnail8169** [comment]
tfw wurst

**Comment by mathmakgakpak** [comment]
wurst?

**Comment by mathmakgakpak** [comment]
why did you close it

**Comment by mathmakgakpak** [comment]
nice 
i didnt see this in any client. it would be hell to implement but it would be cool

**Comment by zengkuankuan** [comment]
Implementing this feature will be cool

**Comment by Wuqibor666** [comment]
Most of these clients are hard coded. Rarely use. Lang files by specification. But I agree you.
