### ISSUE TITLE
[Help] Building meteor

### ISSUE THREAD

**Issue by fuckcuff** [MeteorDevelopment/meteor-client#1342]
I know this might not be the best place to ask this but the discord link isnt working on here or the meteor website.
Why do i have +100 errors when i import the meteor project into Eclipse? I downloaded this repository and imported it into Eclipse. I am not experienced with java or eclipse so id appreciate any help
![image](https://user-images.githubusercontent.com/67871539/128287447-536c8493-ba7d-4797-89ec-54a2ce61447b.png)
![image](https://user-images.githubusercontent.com/67871539/128287453-d05cd7f7-1130-476d-bb67-f310635745d8.png)

**Comment by RitomG69** [comment]
Did you import it as a gradle project?

**Comment by MineGame159** [comment]
Discord links work for me and looks like it did not properly import gradle dependencies. You should switch to intellij idea.

**Comment by fuckcuff** [comment]
Thanks for the replies, importing it as a gradle project did fix almost all of the problems but i now have only one error, how do i fix this one?
![image](https://user-images.githubusercontent.com/67871539/128364617-7a5dd3e7-f935-491c-9f45-a2cfac8e0be8.png)

**Comment by RitomG69** [comment]
https://discord.gg/nGquuVMjVK

**Comment by MineGame159** [comment]
Oh thats weird, fixed.
