### ISSUE TITLE
dropped item esp

### ISSUE THREAD

**Issue by nappyaim** [MeteorDevelopment/meteor-client#1345]
**Describe the feature**
A clear and concise description of what feature/change is.
a box around a dropped item

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.
if this is a thing DM me nappyaim#1313

**Comment by MineGame159** [comment]
Nornal ESP

**Comment by nappyaim** [comment]
> Nornal ESP

how
