### ISSUE TITLE
fps drops with crystal arua

### ISSUE THREAD

**Issue by oturoonie** [MeteorDevelopment/meteor-client#1346]
so whenever im using crystal aura, my pc's fps just destroys itself and, i normally get very high fps, and i just cant find any crystal aura configs / settings. i just need some help, finding some settings and new some help with what crystal settings i should use so drop them down below if you can help :)

**Comment by RedCarlos26** [comment]
Turn off support (this uses a lot of resources for some reason)

**Comment by oturoonie** [comment]
> Turn off support (this uses a lot of resources for some reason)

im sorry for not responding sooner, but where is this support configuration? is it inside of the crystal aura or just one of the main configs? because ive searched the entire set. BY THE WAY this the 1.17.1 version, so if this is outdated then sorry.

**Comment by RedCarlos26** [comment]
It is inside the crystal aura settings. Updating to the last version is always a good thing by the way

**Comment by oturoonie** [comment]
![Desktop Screenshot 2021 08 06 - 14 32 52 42](https://user-images.githubusercontent.com/86896283/128518265-eba773e3-2741-494a-acf9-4e3872ac11c5.png)
![Desktop Screenshot 2021 08 06 - 14 32 45 27](https://user-images.githubusercontent.com/86896283/128518274-c9573c36-f463-4edc-b2df-ae60cecc531a.png)
these two photos show my crystal aura and i cant find it? either im blind or have no clue.

**Comment by oturoonie** [comment]
SORRY LOL i found it, sorry for wasting your time and thanks so much :)

**Comment by RedCarlos26** [comment]
No problem
