### ISSUE TITLE
[Bug] You can sort creative inventory

### ISSUE THREAD

**Issue by mathmakgakpak** [MeteorDevelopment/meteor-client#1349]
**Describe the bug**
You can sort creative inventory for example food

**To Reproduce**
1. enable inventory tweaks
2. enable sorting in inventory tweaks sorting
3. go to inventory>food and sort it using binded key

**Expected behavior**
not sort it

**Screenshots**
![image](https://user-images.githubusercontent.com/44949126/128610253-d52c03a9-694f-4b46-8399-efffceb8ef0c.png)

**Additional context**
meteor-client-0.4.6-1192 1.17.1

**Comment by MineGame159** [comment]
Fixed in 1af1f93b309729ab673d752a032432f66c384c06
