### ISSUE TITLE
[Bug] offhand and replenish in 1.17+ meteor

### ISSUE THREAD

**Issue by Kiriyaga05** [MeteorDevelopment/meteor-client#1352]
Only with 1.17+ meteor, 1.16 is ok
https://youtu.be/YyiAP8SMvs8

Also replenish buggy like offhand

**Comment by GoldenAureuz** [comment]
^^^^^^^

**Comment by RedCarlos26** [comment]
Yes pls fix

**Comment by LDoom** [comment]
This happens to me when I have Inventory tweaks activated

> Only with 1.17+ meteor, 1.16 is ok
> https://youtu.be/YyiAP8SMvs8
> 
> Also replenish buggy like offhand

It happens to me when I have the inventory tweaks activated

**Comment by GoldenAureuz** [comment]
I hate this bug so damn much

**Comment by RedCarlos26** [comment]
Duplicate of #1840

**Comment by GoldenAureuz** [comment]
> 
> 
> Duplicate of #1340

Yeah, it should also be noted that this bug persists even without autoreplenish.

**Comment by RedCarlos26** [comment]
@seasnail8169 ^^

**Comment by seasnail8169** [comment]
cry more
