### ISSUE TITLE
Shader Background

### ISSUE THREAD

**Issue by sugisaru** [MeteorDevelopment/meteor-client#1355]
**Describe the feature**
An GLSL-shader as an background in the main-menu.

**Screenshots**
I'd recommend this shader:
https://www.shadertoy.com/view/4dGyRh

**Additional info**
My friend forced me to make a suggestion. xd

**Comment by ThebestkillerTBK** [comment]
Simply use https://modrinth.com/mod/glsl-panorama/ .
