### ISSUE TITLE
[Suggestion] Highway Maker

### ISSUE THREAD

**Issue by DrDuggi** [MeteorDevelopment/meteor-client#1358]
**Describe the feature**
A feature The Should Make AUTOMATIC Highways So I can like Run it on a Server
**Screenshots**
No, Dont Have Screenshots

**Additional info**
There Should be an option when there is no Obsidian/ echests or Pickaxe's To mine Netherrack It should stop

-1b1t Highway Team

**Comment by StormyBytes** [comment]
Duplicate of #516 
Check if your suggestion/bug was already submitted prior to creating a new issue.

**Comment by toxicdefender404** [comment]
this is a feature in an addon to meteor already https://github.com/C10udburst/meteor-rejects

**Comment by MineGame159** [comment]
Added in 508b0755c2a47f4c1e1ad92fe9293109da28ab37
