### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LevVxP** [MeteorDevelopment/meteor-client#1362]
i have a new isues for meteor client 0.4.5 meteor version, sometime if i cpvp the crystal wont place, when im using fake player, the crystal magicly working 

here is the photo https://cdn.discordapp.com/attachments/842965938809864222/875251406452424774/unknown.png

i hope my bug can get read

**Comment by MineGame159** [comment]
Can you provide a video

**Comment by solar-1902** [comment]
this is a valid bug as i have had this too
