### ISSUE TITLE
Flight + No fall kills me when touching water

### ISSUE THREAD

**Issue by jerrythemouse27** [MeteorDevelopment/meteor-client#1363]
**Describe the bug**
I had this problem for a long time now,i activate flight and no fall and fly for like 1 minute straight,when landing in water WITH FLIGHT ON
i die,why does this happen?

**To Reproduce**
Active Flight
Activate Nofall
Fly for 1 or more minutes at a high altitude
Land in water while flight still active
Then you die

**Expected behavior**
I expect Nofall to work everytime,it kills me on water

**Screenshots**

**Additional context**
Meteor Client for 1.17.1

**Comment by MineGame159** [comment]
#1097

**Comment by jerrythemouse27** [comment]
how u close this but don't respond
