### ISSUE TITLE
Stash Finder notification issue

### ISSUE THREAD

**Issue by HeshamSHY** [MeteorDevelopment/meteor-client#1370]
Hi,
Stash Finder "toast" notification has a problem which that it shows some random symbols and above it is written something like "StashRecorder found stash" when it finds a stash instead of the known pop-up thing, and the image attached shows an example
Meteor Client Version: `dev build 0.4.6-1199`
![2021-08-11_17 31 12](https://user-images.githubusercontent.com/79906420/129457516-17a8b15c-a4f6-484b-b2c5-d5f9c9b13a05.png)

**Comment by maxsupermanhd** [comment]
Confirmed

**Comment by MineGame159** [comment]
Fixed in f8c91427a567b093f0052b7a8c9e2e738b0331b3
