### ISSUE TITLE
[Suggestion] Add Auto mine 

### ISSUE THREAD

**Issue by Manksui** [MeteorDevelopment/meteor-client#1377]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by StormyBytes** [comment]
duplicate of #1269 
check if your suggestion was already submitted prior to submitting a new issue.

**Comment by PiotrekUnityDeveloper** [comment]
just enable autoclicker on Hold mode lol
