### ISSUE TITLE
ITS A FUCKING BUG AND IM HELD HOSTAGE TO REPORT IT SO THERE YOU GO.

### ISSUE THREAD

**Issue by Rytham1819** [MeteorDevelopment/meteor-client#1379]
**Describe the bug**
idk men i when ever i try to connect to an unknown host my mc crashes
**To Reproduce**
1. Go to 'Multiplayer'
2. Click on Direct Connect'
3. Use an unknown IP "Joe.mama"

**Expected behavior**

**Screenshots**
[
[crash.txt](https://github.com/MeteorDevelopment/meteor-client/files/6992361/crash.txt)
](url)

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by MineGame159** [comment]
Fixed in b0f24d4a8c5c2539225d6fee6aaa684d722d380c
