### ISSUE TITLE
Safe chat

### ISSUE THREAD

**Issue by LikeableLucas** [MeteorDevelopment/meteor-client#1386]
**Describe the feature**
A module that you can toggle on or off in click gui or accessibility options in Minecraft. It basically blurs out or tags any swear word that is detected in the chat. You can add your own blocked out words or can disable some cuss words if your fine with it. 

**Screenshots**
Dont have any screenshot

**Additional info**
Add any other info.

**Comment by StormyBytes** [comment]
Why not use the regex filter?

**Comment by RedCarlos26** [comment]
Yea it is already in the client
