### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by OneEyeKing19** [MeteorDevelopment/meteor-client#1388]
**Describe the feature**
Team check allow the aim assist not target your teammate anti bot it will not aim at a bot 

**Screenshots**
-

**Additional info**
-

**Comment by RickyTheRacc** [comment]
Meteor is not for minigame servers stop using it there

**Comment by RedCarlos26** [comment]
Exactly @minegame (sorry for multiple pings) but these needs to be closed I think
