### ISSUE TITLE
Auto tool doesnt work with Auto clicker

### ISSUE THREAD

**Issue by foxxd** [MeteorDevelopment/meteor-client#139]
I am trying to use Auto Clicker and auto tool with a block that updates every time you break it
but it doesn't work most of the time

**Comment by dakone22** [comment]
> a block that updates every time you break it

Which block? For example?

**Comment by foxxd** [comment]
![Uploading ezgif-3-8c1cf0c99be3.gif…]()

**Comment by foxxd** [comment]
![ezgif-3-8c1cf0c99be3](https://user-images.githubusercontent.com/40585717/105663590-b0b26300-5ee3-11eb-878e-1d783db48553.gif)

**Comment by RedCarlos26** [comment]
I cannot reproduce this bug in the latest dev build

**Comment by RedCarlos26** [comment]
This issue can be closed

**Comment by MineGame159** [comment]
Cannot reproduce on latest commit

**Comment by brokuka** [comment]
still bug in latest dev version
