### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Miahkai** [MeteorDevelopment/meteor-client#1391]
Feature: Player Detection
This feature would detect when a player joins the server and you could set up options for it.
1. Leave the game
2. Stop all hacks
3. Tp to your home
4. Any other ideas the devs have

Additional info:
When a certain player joins the server, with the user you typed in, it would automatically do one of options above, to make it non detectable that you're hacking.

**Comment by RickyTheRacc** [comment]
This implies you're using meteor where you shouldn't be. Get a father, rethink your actions, and use it strictly in anarchy servers as intended :)

**Comment by RedCarlos26** [comment]
@MineGame159 close

**Comment by RedCarlos26** [comment]
@seasnail8169 close?
