### ISSUE TITLE
[Suggestion] Make zoom not make waypoints smaller

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1394]
**Describe the feature**
Make zoom not make waypoints smaller. When you zoom in, waypoints and nametags remain the same size despite everything else zooming in.

**Comment by tyrannus00** [comment]
This happens with any zoom mod btw, so it's not a zoom issue

**Comment by RedCarlos26** [comment]
Duplicate of #1150

**Comment by RedCarlos26** [comment]
@seasnail8169 ^
