### ISSUE TITLE
Eatting a chorus fruit with no fall, disabled no fall

### ISSUE THREAD

**Issue by lumberjackfrog** [MeteorDevelopment/meteor-client#1395]
upon eating a chorus fruit before hitting the ground i died afterwards no fall no longer worked.
idk how to reproduce this other than falling & eatting a bunch of times but im now Stuck, with fall damage, my friends works fine
too

**Comment by mathmakgakpak** [comment]
Can you follow bug template? It really helps maintaners of this repository

**Comment by Cypphi** [comment]
I doubt this can be fixed (I may be wrong on this one) but when eating chorus fruit you get tped to the ground aka the thing which makes you take fall damage

**Comment by RedCarlos26** [comment]
Linked to #1097

**Comment by seasnail8169** [comment]
> Linked to #1097

not really

**Comment by Bluscream** [comment]
> > Linked to #1097
> 
> not really

really

**Comment by Wide-Cat** [comment]
I was unable to reproduce, probably fixed
