### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by WAJLgit** [MeteorDevelopment/meteor-client#1398]
**Describe the feature**
A clear and concise description of what feature/change is.
try to add a improvement mod like optifine
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by radiden** [comment]
https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754
