### ISSUE TITLE
Area Miner/Excavator

### ISSUE THREAD

**Issue by btainge44** [MeteorDevelopment/meteor-client#1399]
**Describe the feature**
A clear and concise description of what feature/change is.
You can set parameters (3 of them) on certain blocks to create a highlight. You would set the bottom corner, then it would create a highlight that moves with your mouse making a flat platform highlight, then you set the opposite bottom corner block to fix the highlight in place. Next, you would set the height to make the box 3D and finish the highlight. You can then choose to excavate the area and which blocks you want to excavate, essentially mining out the area for you. The highlight would show the area that will be excavated.
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.
It's a bit hard to describe but it makes sense in your head once you see it.

**Comment by MineGame159** [comment]
Baritone
