### ISSUE TITLE
Using * symbol in better chat filter regex crashes game [Bug]

### ISSUE THREAD

**Issue by friendlytherapist** [MeteorDevelopment/meteor-client#1400]
**Describe the bug**
Using `*` symbol in better chat filter regex crashes game
**To Reproduce**
Enable better chat
Enable filter regex and input `*https://discord.gg/*`
crash...

**Expected behavior**
I assumed * was a wildcard but it just crashes

**Extra info**
It crashes when using it on multiconnect 1.12.1 servers but just throws massive errors on regular 1.17.1

**Comment by C10udburst** [comment]
This is not valid regex. You should type `.*https://discord.gg/.*` but then again the game shouldn't crash even if regex isn't valid
