### ISSUE TITLE
Many errors in log but still playable [Bug]

### ISSUE THREAD

**Issue by friendlytherapist** [MeteorDevelopment/meteor-client#1401]
**Describe the bug**
Many errors in log but still playable. The log even complains about sodium even though it is a fresh multimc install.

**To Reproduce**
I only use MultiMC so this may not be applicable to other MC's
Create fresh instance and install fabric.
Put meteor 0.4.5 and fabric api jar into mod folder
Open game and look at log

**Expected behavior**
No errors, especially sodium errors because its not even installed....

**Additional context**
[Pastebin of log](https://pastebin.com/sEccJ0e9)

**Comment by seasnail8169** [comment]
This is not a bug, it clearly says "warn" not error. It is simply stating that modifications made by meteor to sodium can't be made because sodium is not present.

**Comment by RickyTheRacc** [comment]
No but it's a warning, that means bad

**Comment by friendlytherapist** [comment]
Okay thanks, what about the STDERR at 18:22:40 and below?

**Comment by RickyTheRacc** [comment]
You have an std, sorry :c

**Comment by radiden** [comment]
it's a literal failed regex match
