### ISSUE TITLE
[Suggestion] Delete ALL chat commands info setting

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1402]
**Describe the feature**
When you toggle a module, it will say so in chat and delete the message for when you last toggled the module. It doesn't delete messages for when you toggle other modules. I suggest that there should be a setting to disable all of those module toggle messages each time you toggle something, and not just the one for that specific module.

**Screenshots**
![image](https://user-images.githubusercontent.com/67818307/130390527-785abc12-3775-4c19-acc1-c2cdd63bbe1e.png)
Enabling parkour should delete the flight message.
**Additional info**
my chat looks like this now :(
![image](https://user-images.githubusercontent.com/67818307/130390580-f7f80f3e-b30c-4faf-8790-43abed4f4294.png)
Also I think this used to be a thing, but was changed at some point. Correct me if I'm wrong.

**Comment by seasnail8169** [comment]
no
