### ISSUE TITLE
[Bug] Can't sort custom named containers

### ISSUE THREAD

**Issue by mathmakgakpak** [MeteorDevelopment/meteor-client#1403]
**Describe the bug**
Since [this](https://github.com/MeteorDevelopment/meteor-client/commit/1af1f93b309729ab673d752a032432f66c384c06) commit you can't sort custom named containers

**To Reproduce**
1. Enable inventory tweaks and sorting option.
2. Try to sort custom named shulker/container.
3. You can't.

**Expected behavior**
You can sort custom named shulkers

**Screenshots**
-

**Additional context**
meteor-client-0.4.6-1206

**Comment by MineGame159** [comment]
Fixed in 1d956c1019a74a36886aec617b2e8bd48f4a1874
