### ISSUE TITLE
[Bug]the anarchy server i play updated to 1.17.1 and the only hack client in 1.17.1 is meteor.

### ISSUE THREAD

**Issue by mrdd66** [MeteorDevelopment/meteor-client#1404]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by RickyTheRacc** [comment]
brainless

**Comment by mrdd66** [comment]
great suport!! thx!
