### ISSUE TITLE
[Bug] Cape revoked???

### ISSUE THREAD

**Issue by ojoeth** [MeteorDevelopment/meteor-client#1411]
I donated and i had my cape for a few months and now it's gone, and when I log in to the website it says I have no cape, and my rank on the PVP server is gone too.
Minecraft IGN: sneedfeed
I don't have discord because discord is a privacy nightmare.

**Comment by RedCarlos26** [comment]
@MineGame159 ^

**Comment by ojoeth** [comment]
@MineGame159 do you have an email address?

**Comment by seasnail8169** [comment]
this issue doesn't need to be open but it can still be resolved elsewhere

**Comment by MineGame159** [comment]
@ojoeth petulko08@gmail.com

**Comment by MineGame159** [comment]
Given you donator rank on mpvp but I need to know your meteor account name or email.

**Comment by MineGame159** [comment]
Done
