### ISSUE TITLE
Unfocused CPU doesn't work

### ISSUE THREAD

**Issue by RustyVeteran** [MeteorDevelopment/meteor-client#1419]
**Unfocused CPU Module doesn't work on the latest versions (0.4.5 - 0.4.6 dev)**

1. Open Unfocused CPU module
2. Activate Module
3. Open a second minecraft instance / run the instance in the background
4. See error: the minecraft instance isn't unfocused

**Additional context**
Minecraft Version 1.17.1 running Mac OS, numerous reports of Unfocused CPU also not working on Windows.
Meteor Client Versions tested:
- Latest Release 0.4.5
- Latest Dev Build 0.4.6 - 1208

**Comment by Wide-Cat** [comment]
Can confirm that unfocused cpu does not work for me either

**Comment by RickyTheRacc** [comment]
Nor me

**Comment by MineGame159** [comment]
Fixed in 98c58fc84ad5d57036ebc194adb6f863ca709524
