### ISSUE TITLE
randomly die from "falling" from holding left CTRL to go down while using flight 

### ISSUE THREAD

**Issue by GUCCI5908** [MeteorDevelopment/meteor-client#1424]
**Describe the bug**

I was searching for villages on a server using flight and when I were to hold left CTRL, I die while still in the air. I know when you hot the ground it counts as fall damage, but I was still in the air and its happened multiple times, even when im high up

**To Reproduce**
1. Go to pretty much anywhere flat
2. Click on Flight
3. Hold left CTRL

**Expected behavior**
Take lots of damage or (for me) die

**Additional context**
Not using any other mods except for shaders and a texture pack, and in 1.17.1

**Comment by RedCarlos26** [comment]
Linked to #1097, not sure if it's a duplicate

**Comment by Doogie13** [comment]
it probrably has onGround true at some random packet. NoFall might not work but try using that when flying

**Comment by seasnail8169** [comment]
duplicate #1097
