### ISSUE TITLE
[Suggestion] Minecraft font to the hud and hex colour input

### ISSUE THREAD

**Issue by dadudeme** [MeteorDevelopment/meteor-client#1426]
**Describe the feature**
Please add the standart minecraft font and a hex number input to the colour option for better compatibility with other hud mods such as maruohon's litematica and minihud

**Screenshots**
this looks horrible
![2021-08-30_21 12 24](https://user-images.githubusercontent.com/79927205/131399226-fc12c474-7980-48c3-9df5-815a033c99b8.png)

**Additional info**
Add any other info.

**Comment by C10udburst** [comment]
you can disable custom font in config tab

**Comment by MineGame159** [comment]
Disable custom font
