### ISSUE TITLE
[Bug] Spam doesn't save messages

### ISSUE THREAD

**Issue by opabinia3** [MeteorDevelopment/meteor-client#1429]
**Describe the bug**
When I add messages to spam, they show up and work, until I restart Minecraft, upon which the messages are cleared. The file for the messages is still in the meteor folder in .minecraft, despite the messages not showing up in-game.

**To Reproduce**
1. Go to 'Spam'
2. Right click, and add messages
3. Save and quit
4. Restart Minecraft
5. Reopen 'Spam' settings
6. Messages are gone

**Expected behavior**
Messages should stay in the 'Spam' module upon relaunching

**Additional context**
Meteor v0.4.5, Minecraft 1.17.1,  Fabric Api v0.36.1+1.17, Fabric Loader v0.11.6, Architectury v2.1.20, Cloth Basic Math v0.5.1, Cloth Config v5.0.34, EasierVillagerTrading v1.17.1-fabric0.36.1-1.5.4, Lithium v0.7.3, Mod Menu v2.0.2, MultiConnect v1.4.11, Roughly Enough Items v6.0.264-alpha, Server Pack  Unlocker v1.0, Sodium v0.3.0+build.5, wthit v3.7.0, Xaero's Mini Map v21.12.5.1, Xaero's World Map v21.12.5.1

**Comment by MineGame159** [comment]
Cannot reproduce
