### ISSUE TITLE
Final Ender Chest isn't broken in Highway Builder

### ISSUE THREAD

**Issue by ijustneedsomemilk** [MeteorDevelopment/meteor-client#1430]
When the Highway Builder is done breaking Ender Chests, it breaks the Netherrack surrounding it, but doesnt break the Ender Chest itself. This obstruction causes inconvenience while travelling the highway.

**Steps to reproduce the behavior:**
1. Turn on Highway Builder, with ender chests in your inventory (no obsidian).
2. Wait for the enderchests to be broken into obsidian.
3. Final enderchest is left there, and Highway Builder continues with the building.

**Expected behavior:**
Every enderchest that is placed should be broken.

**Video Demonstration:**
https://user-images.githubusercontent.com/71714632/131454625-ba7de122-2680-456a-b658-f1cc9854797f.mp4

**Additional context:**
Meteor version: 0.4.6 1211
Minecraft version: 1.17.1

**Mods:**
cleancut-1.17-4.0-fabric
fabric-api-0.39.2+1.17
InGameAccountSwitcher-Fabric-1.17.1-7.1.1
litematica-fabric-1.17.1-0.0.0-dev.20210713.103711
malilib-fabric-1.17.1-0.10.0-dev.24
modmenu-2.0.6
Xaeros_Minimap_21.16.0_Fabric_1.17.1

**Comment by MineGame159** [comment]
Could you post a video with your hotbar and inventory shown (inventory viewer in hud). I cannot reproduce this.

**Comment by ijustneedsomemilk** [comment]
> Could you post a video with your hotbar and inventory shown (inventory viewer in hud). I cannot reproduce this.

I'm hoping this would be sufficient.
https://user-images.githubusercontent.com/71714632/131516038-51c4ce7b-5d05-4a8f-907a-aec4708a8305.mp4

**Comment by Wide-Cat** [comment]
![image](https://user-images.githubusercontent.com/74723656/131521744-1e7e55c5-dc2d-4374-8128-f387f5aa79dd.png)

this happened to me too, although i dont think it always happens for some reason

**Comment by MineGame159** [comment]
I have not been able to reproduce it but I just made it always check the block where it placed ender chests when mining the blocks around it so it should be fine now. 6ac968386b0d9732e34a3b57be809dd03635cd15
