### ISSUE TITLE
Anchor Issue

### ISSUE THREAD

**Issue by CheFuls** [MeteorDevelopment/meteor-client#1432]
Anchor wont work with any setting i put in it.

**Comment by RickyTheRacc** [comment]
Config issue

**Comment by CheFuls** [comment]
> Config issue

I said with absolutely all settings

**Comment by RedCarlos26** [comment]
Send me your config

**Comment by RedCarlos26** [comment]
It is probably a pitch issue

**Comment by RedCarlos26** [comment]
@CheFuls
