### ISSUE TITLE
[Suggestion] Console in ClickGUI

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#1433]
**Describe the feature**
Add a console to the clickgui. This would allow you to run commands without the . prefix and would prevent you from accidentally typing commands in chat. It would also be more fancy since it could make use of fonts.

**Screenshots**
none

**Additional info**
I know we can use commands in chat already, but consoles are just so sex

**Comment by RickyTheRacc** [comment]
Based

**Comment by GoldenAureuz** [comment]
very based

**Comment by Tigerrrrrrrrrrrrrr** [comment]
very very based

**Comment by seasnail8169** [comment]
completely useless and would simply be worse than chat commands

**Comment by Cypphi** [comment]
cope!

**Comment by Affexe** [comment]
You can use 
Packet canceller -> C2S Packets -> then add ChatMessageC2SPacket to the right column" and bind it
