### ISSUE TITLE
Can I get older version??[Suggestion] 

### ISSUE THREAD

**Issue by dogevspenguin** [MeteorDevelopment/meteor-client#1436]
### Describe the feature

In the website there are no dowload for older version,Which will be a great edition

**Comment by MineGame159** [comment]
Multiconnect

**Comment by itsmorethantech** [comment]
Some people want to use multiple mods at once though

**Comment by MineGame159** [comment]
Not our problem, they should update.

**Comment by dolphin-cat** [comment]
where can we download the older versions of meteor??? dont ask why. maybe multiconnect won't do what we want, we need older versions. add a button for "download older versions" that lets u choose version, mc version should also be next to meteor version in the list of older meteor versions
