### ISSUE TITLE
[Suggestion] Auto farm module

### ISSUE THREAD

**Issue by DiscrimIsPog** [MeteorDevelopment/meteor-client#1439]
### Describe the feature

Baritone has a autofarm module but one to walk and farm in a certain area would be nice. Or farm  as you walk over the crops.

**Comment by RedCarlos26** [comment]
Isn't this already in the client? At least I'm pretty sure

**Comment by seasnail8169** [comment]
just use baritone, if you only wanna destroy the crops use nuker
