### ISSUE TITLE
[Suggestion] Add TargetStrafe

### ISSUE THREAD

**Issue by mokeWe** [MeteorDevelopment/meteor-client#1448]
### Describe the feature

Add target strafe, a module that strafes around targets when kill aura is active, you already kinda have this with the random teleport option within kill aura but I think target strafe would be a better alternative.

**Comment by Cypphi** [comment]
Yes, please, tp aura doesn't work on any anticheat server whereas targetstrafe would rotate around the target with a set distance and would just copy player speed which works on most anticheat servers
(Basically how Sigma 5 has it)

**Comment by seasnail8169** [comment]
this is literally only useful for cheating
