### ISSUE TITLE
Crystal aura moment

### ISSUE THREAD

**Issue by CheFuls** [MeteorDevelopment/meteor-client#1449]
### Describe the bug

Crystal aura wont break crystal
Remember trolls. No config ussie

### Steps to reproduce

```bash
Just turning on crystal aura lol
```

### Meteor Version

0.4.5

### Minecraft Version

1.17

### Operating System

Windows

**Comment by seasnail8169** [comment]
config issue

**Comment by RickyTheRacc** [comment]
Boggling
