### ISSUE TITLE
Seasnail issue

### ISSUE THREAD

**Issue by CheFuls** [MeteorDevelopment/meteor-client#1450]
### Describe the bug

Crystal aura wont normaly break crystals after spamming packets in unreachable range for it
No config issue bcuz range is 5

OK SEASNAILO HOW ABOUT THAT

### Steps to reproduce

```bash
Turn on crystal aura bruh with range more than 5
```

### Meteor Version

0.4.5

### Minecraft Version

1.17

### Operating System

Windows

**Comment by MineGame159** [comment]
![image](https://user-images.githubusercontent.com/25082624/132037588-fd8dcbfa-114e-4dd1-9f01-656fca76a30e.png)
Literally said whats the problem

**Comment by CheFuls** [comment]
> ![image](https://user-images.githubusercontent.com/25082624/132037588-fd8dcbfa-114e-4dd1-9f01-656fca76a30e.png)
> Literally said whats the problem
Dude... Range is 5 and crystal aura is boughta out but if u place crystal in freecam u can place further and break it succesfuly

**Comment by CheFuls** [comment]
Sooo why crystal aura has range more than 5 
answear pls

**Comment by RickyTheRacc** [comment]
Config issue
