### ISSUE TITLE
[Bug] Hand view Broken in 1.17 release

### ISSUE THREAD

**Issue by Tokara1** [MeteorDevelopment/meteor-client#1452]
### Describe the bug

Eating with Hand view is completely weird, it moves (when eating with right hand) the whole right hand past the offhand, same goes for all simmelar animations. 
It overdoes all animations.
Becides that, Handview in 16 and 17 with exact same settings look completly different. ( Hands are in altered positions)

A setting where this is visible pretty well:
Scale X Y Z all 0
Position x y both 0, z -0.100
Rotation x y z all 0
swing mode none
main progress 0
offhand progress 0

also if swing mode is set to none shouldnt it like not do the swing animation at all?
Bc it still does it

### Steps to reproduce

```bash
1. Have meteor
2. Enable hand view
3. Have described settings
4. Eat sth
...
```

### Meteor Version

Both 0.4.5 and 0.4.6 1240

### Minecraft Version

1.17.1

### Operating System

Linux

**Comment by MineGame159** [comment]
#1081
