### ISSUE TITLE
[Bug] Font picker not disappearing on custom font toggle

### ISSUE THREAD

**Issue by radiden** [MeteorDevelopment/meteor-client#1455]
### Describe the bug

The custom font option doesn't make the font picker disappear when you toggle it off.

### Steps to reproduce

```bash
1. Toggle Custom Font on or off
```

### Meteor Version

v0.4.6 build #1244

### Minecraft Version

1.17.1

### Operating System

Linux

**Comment by MineGame159** [comment]
Fixed in b9e83e5dbda24ff5fd53e8aa8db3353879a71356
