### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Dasyat1s** [MeteorDevelopment/meteor-client#1456]
### Describe the feature

- More setting to chams and esp (to make crystals and players look like that : https://imgur.com/a/ZUsJSjY)
- Customizable crosshair (just to chnage crosshair settings)
- Hit show (crosshair thing like in CoD, in this vid : https://www.youtube.com/watch?v=Kog5YVr237MS and this image : https://imgur.com/a/bQlP68t)
- Health bar option to esp (green bar on the left, in raven b3 client (1.8.9)) : https://imgur.com/a/M0ZPRsd
- Armor notifier : hud message notifying that armor is low (under a health percentage)
- Adding minecraft basic font to the font list (the ones on internet are shit and the option todisable costom font is making it look shit : https://imgur.com/a/0Hbnlws)
- Adding a pop counter in taget hud and a way to display the ennemy health points (instead/in the already existing bar) and/or a way to make it look like that : https://imgur.com/a/nzh94Tf
- Fix chams (showing crystal though walls even tho they aren't chosen as entities to render)
- Add a way to make each hand customizable differently in handview
- Add a setting to armor hud to display both number and bar

**Comment by MineGame159** [comment]
1. One suggestion per issue
2. Many of these are already suggested
