### ISSUE TITLE
[Suggestion] Fonts fix

### ISSUE THREAD

**Issue by Dasyat1s** [MeteorDevelopment/meteor-client#1461]
### Describe the feature

Adding minecraft basic font to the font list (the ones on internet are shit and the option todisable costom font is making it look shit : https://imgur.com/a/0Hbnlws)

**Comment by seasnail8169** [comment]
just disable custom font

**Comment by seasnail8169** [comment]
if it looks shit, your scale is wrong. the font is low res and therefore displays weirdly on certain scales
