### ISSUE TITLE
[Bug] Game crashes when trying to edit HUD from home screen

### ISSUE THREAD

**Issue by Genius-Format** [MeteorDevelopment/meteor-client#1466]
### Describe the bug

When I try to edit my HUD from the main menu of minecraft, it just crashes. It also happens if you are in the multiplayer menu.

### Steps to reproduce

```bash
1. Go to the main menu
2. Press right-shift
3. Press the HUD button
```

### Meteor Version

0.4.5

### Minecraft Version

fabric-loader-0.11.6-1.17.1

### Operating System

Linux

**Comment by RickyTheRacc** [comment]
Are you using addons with hud elements? Some addons (notably older versions of orion) will do this
