### ISSUE TITLE
My accounts list dissapeared and I cant readd the accounts

### ISSUE THREAD

**Issue by meteor-on-top** [MeteorDevelopment/meteor-client#1468]
### Describe the bug

my accounts list in meteor disappeared and I cannot add accounts back to the list and I also cannot add new accounts to the list

### Steps to reproduce

```bash
I don't know how to reproduce this bug
```

### Meteor Version

4.5

### Minecraft Version

Java edition

### Operating System

Windows

**Comment by seasnail8169** [comment]
fixed in latest build 4/09/21
