### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Tigerrrrrrrrrrrrrr** [MeteorDevelopment/meteor-client#1473]
### Describe the feature

Android support for apps like pojavlauncher. For example make the discord rpc a little bit more different since it causes the game to crash since the device is a phone. (Arm64/arch64 difference make game crash)

**Comment by Talhoid** [comment]
tf

**Comment by cum-account** [comment]
https://github.com/cum-account/meteor-client/actions/runs/1203768557
