### ISSUE TITLE
[Suggestion] Orientation lock (either current or set orientation)

### ISSUE THREAD

**Issue by w014prc2** [MeteorDevelopment/meteor-client#1475]
### Describe the feature

If I knew how to use java to write meteor plugins I wouldn't bother with this, as its such a simple thing to implement, but it would be nice to have an orientation lock, so that you don't have to worry about bumping the mouse and putting yourself out of alignment if you're in, say, a totem farm, or pointing towards something to afk travel to it.

You would still have full control, and be able to move normally, you just couldn't move the camera. It _could_ have two modes, although the set orientation mode doesn't seem very useful to me. Either, when you activate it locks your view, or when you press the key, it orients itself in a predetermined orientation.

It is very possible, and honestly more likely than not, that baritone has some form of this, in which case I may look stupid. But even then, it would be nice to have the ability to bind this with a key, and I don't know if you can bind stuff with baritone.

**Comment by StormyBytes** [comment]
What you are looking for is exactly the **Rotation Module**.

Locks Rotation/Orientation of the player head but still allows everything else to be controlled.

**Comment by w014prc2** [comment]
> What you are looking for is exactly the **Rotation Module**.
> 
> Locks Rotation/Orientation of the player head but still allows everything else to be controlled.

Yea I just found that now I feel REALLY stupid lmao
