### ISSUE TITLE
[Suggestion] Freecam speed control with the mouse wheel

### ISSUE THREAD

**Issue by Kissunen** [MeteorDevelopment/meteor-client#1477]
### Describe the feature

Like in vanilla, in spectator mode, you can roll the mouse wheel to set your flying speed. Freecam is almost like the spectator mode, but the speed can't be changed on the fly, only through the module settings, which is slow and cumbersome. Controlling the speed with the mouse wheel could be a checkbox option in the module's config.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
- [X] This wasn't already suggested.
- [X] This feature is a valid suggestion, according to the FAQ and Guides.

**Comment by CoolestGuy94** [comment]
Absolute Vouch.

**Comment by MineGame159** [comment]
Added in 763e8c1dab2a9f1ae86fbffed76aed7483b3a147.
