### ISSUE TITLE
[Bug] alts

### ISSUE THREAD

**Issue by galson2008** [MeteorDevelopment/meteor-client#1478]
### Describe the bug

when i try to put name for alt it doesnt work

### Steps to reproduce

```bash
1.
2.
3.
...
7
```

### Meteor Version

last

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
- [X] This is a valid bug and I have checked all settings.

**Comment by MineGame159** [comment]
Update to latest dev build
