### ISSUE TITLE
[Bug] You cannot use cracked mc accounts in Relese 0.4.5

### ISSUE THREAD

**Issue by WhoGanda** [MeteorDevelopment/meteor-client#1482]
### Describe the bug

as simple as that , i would like to use alts on your client , and i appreciate your work

### Steps to reproduce

```bash
1.
2.
3.
...
```

### Meteor Version

Relese 0.4.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
- [X] This is a valid bug and I have checked all settings.

**Comment by MineGame159** [comment]
Update to latest dev build
