### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by spartamy** [MeteorDevelopment/meteor-client#1483]
### Describe the bug

Thealtening doesn’t work on the meteor devbuild, as I’ve attempted to used it normally and the alt doesn’t appear in the account menu.

### Steps to reproduce

```bash
1. Use Thealtening in “accounts” as usual
2. After using the token, the alt doesn’t appear
3. Even if you were to try to exit the account menu and click on the account button once again, the alt still doesn’t appear but “Cracked” accounts work.
...
```

### Meteor Version

1.17.1 Devbuild

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
- [X] This is a valid bug and I have checked all settings.

**Comment by hribik100** [comment]
i have this problem too on windows and linux
