### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by VinhNguNgu** [MeteorDevelopment/meteor-client#1484]
### Describe the bug

I can't use baritone, when i use they said Invalid Agruments

### Steps to reproduce

```bash
1.
2.
3.
...
```

### Meteor Version

4.5.0

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
- [X] This is a valid bug and I have checked all settings.

**Comment by RickyTheRacc** [comment]
Hurrr
