### ISSUE TITLE
[Suggestion] Hello this will be better

### ISSUE THREAD

**Issue by AzozDevill** [MeteorDevelopment/meteor-client#1487]
### Describe the feature

hello i Suggestion to make the meteor clinet as 1.16.5 vanilla wiht optifine alot of pepole want that this will be so cool you clinet is so cool but i cant play with it cuz my pc is bad so i Suggestion for taht
By AzozDevill.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
- [X] This wasn't already suggested.
- [X] This feature is a valid suggestion, according to the FAQ and Guides.

**Comment by StormyBytes** [comment]
You clearly didn't read the faqs.
Meteor is only available for latest versions of minecraft, we suggest using multiconnect if you want to connect to servers of older versions.
also, optifine is not and never will be supported, we recommend using sodium instead.
