### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by b868b68** [MeteorDevelopment/meteor-client#1489]
### Describe the feature

Make autotool work with shears on wool/leaves/etc

Seems weird that it defaults to sword when mining wool, might be useful

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
- [X] This wasn't already suggested.
- [X] This feature is a valid suggestion, according to the FAQ and Guides.

**Comment by StormyBytes** [comment]
Already exists on the latest devbuild

**Comment by Amnessie** [comment]
@StormyBytes this still does not work in **0.5.3** 1.19.4 any suggestions?
