### ISSUE TITLE
[Suggestion] Elytra 40/40

### ISSUE THREAD

**Issue by HarryPotter42MC** [MeteorDevelopment/meteor-client#1491]
### Describe the feature

A module wich automaticly changes the serverside pitch to 40 and -40 for elytra so you can fly infinite distances without using efly and fireworks. This also wouldn't use any durability in 1.18

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [ ] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Cypphi** [comment]
Idk if it would be infinite but should work for very long distances, especially with a client which changes pitch perfectly

**Comment by seasnail8169** [comment]
you can just use the Rotation module for this, ill look into a proper module/part of efly once 1.18 is released.
