### ISSUE TITLE
[Bug] Search module marks air

### ISSUE THREAD

**Issue by mathmakgakpak** [MeteorDevelopment/meteor-client#1492]
### Describe the bug

https://youtu.be/SyanwzHPLXY

### Steps to reproduce

```bash
1. Connect to a 1.12.2 server using multiconnect
2. Enable search
3. Watch your pc fry
```

### Meteor Version

0.4.6-1249

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Click the reset button next to the blocks setting.

**Comment by mathmakgakpak** [comment]
ok thanks
