### ISSUE TITLE
Meteor doesnt save my changes, cant read and create accounts, manage profiles.

### ISSUE THREAD

**Issue by MarcelloLOLL** [MeteorDevelopment/meteor-client#1493]
### Describe the bug

![image](https://user-images.githubusercontent.com/82828579/132988740-fe59cfce-c2a6-43b6-9d8a-411c6eafe4a4.png)

### Steps to reproduce

```bash
i cant trigger this bug. its just happening :/
```

### Meteor Version

meteor-client-0.4.6-1251

### Minecraft Version

1.16.5 , 1.17.1

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by StormyBytes** [comment]
"I cant trigger this bug."
"I am able to reproduce this on the latest dev build"
what?

**Comment by MarcelloLOLL** [comment]
sorry. I dont know but i tryed with the normal and with the dev build too. No, i still dont know how to fix this. from trying to reinstall meteor, delete meteor files, and these things.  "I cant trigger the bug"  if its not understandable i will explain it:  Use Thealtening in “accounts” as usual
2. After using the token, the alt doesn’t appear
3. Even if you were to try to exit the account menu and click on the account button once again, the alt isnt there.

1. Open any module on the latest dev and normal build
2. Turn on or off any feature that uses a checkmark indicator
3. Watch as the bind, toggle on release, and active/visible indicators vanish

**Comment by LordDoom-eng** [comment]
>again create profile
>save backup profile.nbt
>wow again reset?
>copy paste backup profile.nbt 
>eezz
