### ISSUE TITLE
crystal aura settings

### ISSUE THREAD

**Issue by master7720** [MeteorDevelopment/meteor-client#1498]
### Describe the feature

make the ca have multi place

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested.
(I have checked every suggestion on github)

- [ ] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by seasnail8169** [comment]
no mulitplace is completely useless

**Comment by master7720** [comment]
Bruh no it aint

**Comment by seasnail8169** [comment]
and the sky is red
