### ISSUE TITLE
[Bug] mc-heads down

### ISSUE THREAD

**Issue by minebotter** [MeteorDevelopment/meteor-client#1500]
### Describe the bug

mc-heads.net is currently down, metor requires it to log in with the accounts tab, possible solutions are make the player head not required to log in or use another service.

Laucher Log:
Failed to read skin url. (https://www.mc-heads.net/avatar/UUID)

### Steps to reproduce

```bash
Try to login with the accounts tab in the server list
```

### Meteor Version

0.4.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
fixed in latest devbuild
