### ISSUE TITLE
[Bug] Unable to walk through 1 wide block spaces

### ISSUE THREAD

**Issue by mokeWe** [MeteorDevelopment/meteor-client#1504]
### Describe the bug

When you go prone or even try to swim through 1 wide spaces it instantly lags you back and will not let you go through 1 block wide spaces. I have tried every module and it seems like a module isn't causing it, I don't know what is, this also happens when trying to swim through 1 wide spaces.

### Steps to reproduce

```bash
Go prone and try to walk through a 1 wide hole, it lags you back and does not allow you to go through, this also applies to swimming.
```

### Meteor Version

Meteor dev build 1254

### Minecraft Version

Minecraft 1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by StormyBytes** [comment]
Most likely anti hunger

**Comment by RedCarlos26** [comment]
It is related to #

**Comment by LordDoom-eng** [comment]
ca
