### ISSUE TITLE
[Suggestion] Start over

### ISSUE THREAD

**Issue by GhostTypes** [MeteorDevelopment/meteor-client#1505]
### Describe the feature

The client is bad, please rewrite everything from scratch (without skidding wurst) 👍👍

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by IUDevman** [comment]
Chad

**Comment by RickyTheRacc** [comment]
Based ghosttypes

**Comment by RitomG69** [comment]
Best suggestion
