### ISSUE TITLE
[Suggestion] No Cooldown

### ISSUE THREAD

**Issue by CoolestGuy94** [MeteorDevelopment/meteor-client#1507]
### Describe the feature

Disables cooldown for enderpearls

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Cypphi** [comment]
Isn't the cooldown also handled server-side

**Comment by MineGame159** [comment]
Already done. Fast Use.
