### ISSUE TITLE
[Bug] Cannot walk /swim through 1 block wide spots.

### ISSUE THREAD

**Issue by mokeWe** [MeteorDevelopment/meteor-client#1510]
### Describe the bug

I made another bug report but it was instantly closed because you guys said it was related to Anti Hunger, I have tested it with and without every single module in the client and it still happens, I have tested it with and without every other mod I have in my mods folder, it still happens. I don't know if anyone else has this issue but it's kinda annoying.

### Steps to reproduce

```bash
Go prone
Try to go through a 1 block wide hole
It will lag you back
```

### Meteor Version

Meteor dev build 1254

### Minecraft Version

Minecraft 1.17.1

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by IUDevman** [comment]
I can confirm that this is a thing.

**Comment by RedCarlos26** [comment]
This is not happening in vanilla, it is a server anti cheat that is doing that. Which server did you test this on?

**Comment by WhoAmI2704** [comment]
you used prone module ? or u went prone by water or elytra ?

**Comment by GoldenAureuz** [comment]
That's almost definitely a server anticheat and not a problem with the client.

**Comment by Cypphi** [comment]
Seems to be an issue with ViaBackwards or related, had it on my own server and anyone using a specific version would get laggedback while 1.13/1.14/1.15 worked fine
