### ISSUE TITLE
[Suggestion] AutoDrop

### ISSUE THREAD

**Issue by Markskieee** [MeteorDevelopment/meteor-client#1512]
### Describe the feature

Its a feature that will drop any block/item that you selected automatically.

Also add a command:
.autodrop (add) | (remove) (block or item)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
InventoryTweaks module.
