### ISSUE TITLE
Auto Farming

### ISSUE THREAD

**Issue by jackstw** [MeteorDevelopment/meteor-client#1513]
### Describe the feature

Auto Farming, would essentially farm crops, automatically (obv). It would include smaller modules, such as being able to replant crops such as, carrots, wheat, etc. Or being bone-mealing crops until your inventory is filled. This would also work with sugarcane, and various other farmable materials in the game.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RedCarlos26** [comment]
@seasnail8169 this is an already closed bug report

**Comment by RedCarlos26** [comment]
@jackstw do not suggest already suggested features that are closed

**Comment by toxicdefender404** [comment]
This is in baritone already
