### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by trimpta** [MeteorDevelopment/meteor-client#1514]
### Describe the bug

While using Auto fish, if the crosshair is not pointing at the water(or the Trajectory of the fishing rod), The auto fishing still goes on.
If you want to open a chest nearby you cant do it properly since the cursor goes to The center each time it recasts

### Steps to reproduce

```bash
Turn on auto fish
point crosshair at a chest
```

### Meteor Version

meteor-client-0.4.6-1250

### Minecraft Version

1.17.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
I don't see what is the bug here. Thats how Auto Fish is supposed to work.

**Comment by trimpta** [comment]
Its supposed to fish, not open chests

**Comment by MineGame159** [comment]
You are supposed to look at water, not at chests
