### ISSUE TITLE
[Bug] Crystal Aura randomly stops working.

### ISSUE THREAD

**Issue by bofnb** [MeteorDevelopment/meteor-client#1515]
### Describe the bug

Me and a friend are practicing cpvp, we both use meteor. Yesterday, we had to stop because my crystal aura wouldnt attack, i friended him, and unfriended him, tried everything, and it didnt work. Today, we tried to play again only to find out that my client worked, but his didnt. He reset every setting, and turned off al other hacks. We are both on the latest dev build.

### Steps to reproduce

```bash
I have no idea
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by GoldenAureuz** [comment]
You're 100% sure you had players selected under entities right?

**Comment by bofnb** [comment]
Yes, the weird thing is that it would randomly work, and suddenly stop. Checked all the settings, and they were intact.

**Comment by CoolestGuy94** [comment]
might be because the player is in a hole.

**Comment by WhoAmI2704** [comment]
um send ur config here ?

**Comment by Cypphi** [comment]
Also happens to me, sometimes it doesn't even place support blocks while the target is not surrounded or just on normal terrain

**Comment by CheFuls** [comment]
Set minimum damage to place and break on 4.5
and self damage to 3
that fixed my not woking crystal auta

**Comment by Cranky481** [comment]
yeah sidk whats happeing i cant fix it

**Comment by RedCarlos26** [comment]
Mainly only happening on meteor pvp for me, so it seems more like an anti cheat thing
