### ISSUE TITLE
[Suggestion] want like a Inertia's Notebot

### ISSUE THREAD

**Issue by 8MiYile** [MeteorDevelopment/meteor-client#1516]
### Describe the feature

I prefer the Notebot in InertiaClient to use more timbre, add support if you can, visual tuning, more timbre support, like playing inside a ball

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [x] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by 8MiYile** [comment]
That's more in line with my habits, you can control the tone, let the client read the tone of the note box or read the box below the block

**Comment by Cypphi** [comment]
Meteor doesn't have to be the same as another client, although some improvements would be nice

**Comment by KMatias123** [comment]
why does it have autocrystal then, if a lot of other clients have it already?

**Comment by MineGame159** [comment]
Retard spotted above.
