### ISSUE TITLE
[Bug] Trying to add a Account while having service disabled fails.

### ISSUE THREAD

**Issue by pog5** [MeteorDevelopment/meteor-client#1517]
### Describe the bug

On windows, when you disable the services that are responsible for network list showing (aka the ones that show IF you are connected to internet), meteor thinks you are not connected to internet at all and dosent add any accounts.

### Steps to reproduce

```bash
Start Windows 10 and lower, open up `services.msc` find Windows Event Log, set it to disabled and restart your computer, try to add a acocunt to meteor.
```

### Meteor Version

0.4.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)
I cannot launch the latest DEV build.

**Comment by seasnail8169** [comment]
i'm no expert but how about just not doing that. isn't it kinda like saying if i turn off my internet, i cant connect to a server.

**Comment by Wide-Cat** [comment]
![image](https://user-images.githubusercontent.com/74723656/133802893-0c1e8a50-8bf0-446c-a279-5ebb9b1ee1e1.png)

**Comment by FolfyBlue** [comment]
Why do you need this service disabled?

**Comment by seasnail8169** [comment]
brue

**Comment by pog5** [comment]
> i'm no expert but how about just not doing that. isn't it kinda like saying if i turn off my internet, i cant connect to a server.

but its not, its just disabling the notification that you have internet, the internet still works fine.



> Why do you need this service disabled?

performance, it uses a lot of ram
