### ISSUE TITLE
[Suggestion] Bedrock breaker module

### ISSUE THREAD

**Issue by ImKindaSus** [MeteorDevelopment/meteor-client#1518]
### Describe the feature

So there is a good way to automate bedrock breaking on 1.16-1.17.1. and i'd like it to be added to client or plugin (vid witth it https://youtu.be/JsfvjNcK8SU)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
In the description there is literally linked the mod.
