### ISSUE TITLE
[Bug] Renaming a profile is not automatic

### ISSUE THREAD

**Issue by samcries** [MeteorDevelopment/meteor-client#1519]
### Describe the bug

Let's say I have a profile named "A" and I would like to rename it to "B". When I rename A to B, B cannot be loaded or saved. This is because the folder that profile B is stored at is non-existent. When profile A was created, a folder called ".minecraft\meteor-client\profiles\A" was created with it. When A is renamed to B, the folder name remains the same. What SHOULD be happening, is, when you rename A to B, the folder should be renamed to B as well, so the user does not manually have to do it themselves.

### Steps to reproduce

```bash
1. Create a new profile with the name "A". (This will create a folder, ".minecraft\meteor-client\profiles\A")

2. Rename the profile "A" to "B". (The folder ".minecraft\meteor-client\profiles\A", will not be renamed to B)

3. Try to load "B". (It will not work, since it is trying to access ".minecraft\meteor-client\profiles\B", which does not exist, since the folder which the profile is stored in is still at ".minecraft\meteor-client\profiles\A")
```

### Meteor Version

0.4.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
That's not a bug, it was never intended to work.

1. Load A
2. Delete A
3. Save it as B
