### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Vindicator4095** [MeteorDevelopment/meteor-client#1520]
### Describe the bug

HUD isn't showing every time I click HUD nothing shows. 

### Steps to reproduce

```bash
when I click active on HUD nothing shows
```

### Meteor Version

0.4.6 1249

### Minecraft Version

1.17.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MrPalel** [comment]
The same problem just occurred, do you have a lot of mods?
