### ISSUE TITLE
[Suggestion] Add Alternate Account Support for McLeaks 

### ISSUE THREAD

**Issue by Penaple01** [MeteorDevelopment/meteor-client#1522]
### Describe the feature

While the altening works well to generate minecraft alts, there is another service, [Mcleaks](https://mcleaks.net/) That allows you to renew and generate alts for free, allowing for people to use the same account multiple times without having to pay. I would really appreciate if this was added.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Bogieloo** [comment]
bump

**Comment by Wide-Cat** [comment]
looks like its been shut down
