### ISSUE TITLE
[Suggestion] please keep chat history log

### ISSUE THREAD

**Issue by RouZong** [MeteorDevelopment/meteor-client#1523]
### Describe the feature

please keep chat history log

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by StormyBytes** [comment]
aren't they already stored in log files?
in `minecraft/logs` ?

**Comment by RouZong** [comment]
> 它們不是已經存儲在日誌文件中了嗎？
> 在`minecraft/logs`？

No,only have debug logs

**Comment by RouZong** [comment]
okay..my worng
0.4.5 is not work
but 0.4.6 dev version is working

**Comment by StormyBytes** [comment]
then close this issue because it exists on the latest dev build
