### ISSUE TITLE
[Suggestion] change version

### ISSUE THREAD

**Issue by DolaPRO** [MeteorDevelopment/meteor-client#1526]
### Describe the feature

this feature is for change version without exit the game

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Cypphi** [comment]
Yes, Inertia like version spoofer would make me cum so hard

**Comment by seasnail8169** [comment]
you're both speds, use multiconnect

**Comment by Cypphi** [comment]
😭
