### ISSUE TITLE
[Suggestion] .b farm new addition

### ISSUE THREAD

**Issue by DaCrazyRaccoon** [MeteorDevelopment/meteor-client#1527]
### Describe the feature

It would be a cool to make baritone detect bamboo and let us farm it with .b farm . The default tool could be either an axe or a sword. I don't really know what else to say to be honest.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
We are not baritone developers.

**Comment by cum-account** [comment]
baritone should detect bamboo, sounds like a bug
