### ISSUE TITLE
If you have nofall and flight, whenever you fly downwards and hit the ground u take dmg[Bug] 

### ISSUE THREAD

**Issue by mrgamer45** [MeteorDevelopment/meteor-client#1531]
### Describe the bug

in the title

### Steps to reproduce

```bash
press shift while flying
```

### Meteor Version

0.4.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
duplicate
