### ISSUE TITLE
Game crashed when i joined server and pressed tab[Bug] 

### ISSUE THREAD

**Issue by mrgamer45** [MeteorDevelopment/meteor-client#1532]
### Describe the bug

this is the log
https://paste.ee/p/PHzJm

### Steps to reproduce

```bash
idk i had bettertabs on and i pressed tab
```

### Meteor Version

0.4.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Nothing to do with Meteor.
