### ISSUE TITLE
[Bug] Double & Int value input

### ISSUE THREAD

**Issue by necrophili** [MeteorDevelopment/meteor-client#1537]
### Describe the bug

The current box where you can type exactly the value (instead of the slider) for both Integer and Double values only accepts input from numbers which are positives. The negative sign or “-“ is unable to be inserted into the box. The only way to go around this at the moment is by moving the slider below 0 and then type in the negative value you want.

I expect the input box to be able to accept “-“ as an input when the min value can be a negative value, not using the sliderMin to get there.

### Steps to reproduce

```bash
Go into a module where negative int/double can be inputted, take burrow for example, if you try to insert a negative rubberband height you will need to slide the slider below 0 and then input the negative number instead of pressing “-“ right away.
```

### Meteor Version

Latest dev build

### Minecraft Version

1.17.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 2f3ab0bef75e4004f11ec02500371de0143cccd4.
