### ISSUE TITLE
[Suggestion] add a remove enchant to .enchant

### ISSUE THREAD

**Issue by GodsonGamerGr** [MeteorDevelopment/meteor-client#1545]
### Describe the feature

add the option to .enchant to remove certain enchants so for example be able to remove curse of binding an so on (.enchant remove (enchant and/or all)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Added in 594bc97723d97274af23b786337557fd16ff71f1.
