### ISSUE TITLE
[Bug] Highway Builder Crash

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#1547]
### Describe the bug

Highway builder has been crashing since a couple of dev builds.

### Steps to reproduce

```bash
1. Turn on auto builder (default config)
2. Make sure it has blocks to mine in his way like netherrack or obsidian
3. See it crash after a couple of seconds (sometimes minutes) when trying to mine a block
```
Original crash report: [crash-2021-09-30_19.18.18-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7263006/crash-2021-09-30_19.18.18-client.txt)

Crash report on the latest dev build (1302): [crash-2021-10-21_10.13.07-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7389728/crash-2021-10-21_10.13.07-client.txt)

### Meteor Version

0.4.6 - 1275 and above (maybe some dev builds below as well I did not check)

### Minecraft Version

1.17.1

### Operating System

Windows 10

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
Edit: Added crash report

**Comment by RedCarlos26** [comment]
Please fix 😭

**Comment by RedCarlos26** [comment]
Anyone has an idea why it crashes (by looking at the crash report)

**Comment by MesVeines** [comment]
Highway builder makes my game crash as well but only after about 30 minutes and the description in the crash report says "Container click".

Meteor :
Version: 0.4.7
Dev Build: 1323

**Comment by RedCarlos26** [comment]
Seems to not be happening anymore in 1.18 dev builds
