### ISSUE TITLE
[Bug] Meteor conflicts with optifabric

### ISSUE THREAD

**Issue by gabrielmaster123** [MeteorDevelopment/meteor-client#1548]
### Describe the bug

When I want to start meteor with optifabric it doesn't work
this pops up 
![image](https://user-images.githubusercontent.com/60442371/135636945-4b08fe34-32af-49bf-a010-f1d9bbc37b3c.png)

### Steps to reproduce

```bash
Install optifabric and meteor
```

### Meteor Version

0.4.6-1275

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by StormyBytes** [comment]
Check the [faq](https://github.com/MeteorDevelopment/meteor-client/wiki) before submitting a bug report please.

**Comment by radiden** [comment]
https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by Tokara1** [comment]
Optifine is larp af noone uses that stop using optifine. 
If you want better fps go use sodium if you want shaders use iris otherwise cope

**Comment by ShayBox** [comment]
how about I **cope** with a different client, optifine does more than performance and shaders, the game looks worse with sodium/lithium/hydrogen/iris/etc, they are not comparable.

**Comment by Tokara1** [comment]
Lmfao bro thats bs

Litterally optifine doesnt change anything abt the appearance of the game but Performance and shaders. You shall cope without any Client bc At this point optifine is basically Not supported With anything anymore.

Optifine is trash when it comes to using it With other mods and the bullshit With optifine looks better is simply you having issues With your brain or so bc it doesnt make a difference.

**Comment by tempaccounttoask** [comment]
Why are people who promote Sodium over OptiFine always so nasty? There's a reason people prefer OptIFine. Sometimes it's out of necessity. There's no reason to be hyper competitive and ignorant about what the person says.

**Comment by seasnail8169** [comment]
> Why are people who promote Sodium over OptiFine always so nasty? There's a reason people prefer OptIFine. Sometimes it's out of necessity. There's no reason to be hyper competitive and ignorant about what the person says.

because its extremely frustrating people creating issues about the legacy shitware that is optifine.
