### ISSUE TITLE
[Bug] Adding a proxy will not immediately show unless if you refresh the proxy list

### ISSUE THREAD

**Issue by wsquarepa** [MeteorDevelopment/meteor-client#1563]
### Describe the bug

Adding a proxy will not show the new proxy immediately, you must refresh the proxy list in able to see the newly added proxy. Here is a [video](https://ufile.io/jgdtht5j) to demonstrate the bug. As well, this bug is **not** on the Meteor stable build (Release 0.4.5). 

### Steps to reproduce

```bash
1. Open proxy menu
2. Add a proxy
3. Observe as it does not have it added
4. Close proxy list
5. Open proxy list (To refresh the list)
6. Observe how the proxy now appears.
```

### Meteor Version

Meteor 0.4.6-1283

### Minecraft Version

1.17.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 1d84fe228bd14402081b43e94d7d566e9f34a436.
