### ISSUE TITLE
[Suggestion] Support `minecart with chest` in Storage ESP

### ISSUE THREAD

**Issue by SukkaW** [MeteorDevelopment/meteor-client#1565]
### Describe the feature

RT.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
Minecarts are entities, they are in regular ESP
