### ISSUE TITLE
[Suggestion] Add Hacktoberfest tags and issue labels

### ISSUE THREAD

**Issue by mmvanheusden** [MeteorDevelopment/meteor-client#1571]
### Describe the feature

https://hacktoberfest.digitalocean.com/resources/maintainers

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Why?

**Comment by mmvanheusden** [comment]
Why not

**Comment by MineGame159** [comment]
Just contribute without it?
