### ISSUE TITLE
[Bug] Crash on startup with MultiMC

### ISSUE THREAD

**Issue by Tony-Goat** [MeteorDevelopment/meteor-client#1574]
### Describe the bug

Any attempt to launch a Fabric installation installed by MultiMC with Meteor in the mod folder results in a crash on launch.

0.4.5 Crash Logs: [0.4.5 Crash.txt](https://github.com/MeteorDevelopment/meteor-client/files/7316412/0.4.5.Crash.txt)
0.4.6 Crash Logs: [0.4.6 Crash.txt](https://github.com/MeteorDevelopment/meteor-client/files/7316413/0.4.6.Crash.txt)

I am unable to collect more verbose logs from the disk because it crashes before it flushes the logs.

### Steps to reproduce

1. Run MultiMC from the archive on their website
2. Create a new instance
3. Install Fabric on that instance using the MultiMC directions on Fabric's website
4. Drag and drop Meteor into the mod folder of the instance
5. Attempt to launch the profile.

### Meteor Version

0.4.5 & 0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
![image](https://user-images.githubusercontent.com/25082624/136674493-d0c5d8c5-9be8-4433-9a68-0bebe99ca5ac.png)

**Comment by Tony-Goat** [comment]
Alright, I've checked the API to make sure Fabric wasn't reporting is as stable, and I'll file a bug report with MultiMC

**Comment by Tony-Goat** [comment]
![image](https://user-images.githubusercontent.com/70238376/136675419-8386825a-c0f0-4472-acff-15c7f599e431.png)
It looks like it is putting a little star next to a version marked as unstable by the Fabric meta API.

And you can see in the lower right hand corner that this is the latest Linux build, 0.6.13.

**Comment by peterix** [comment]
hit `Refresh`

**Comment by peterix** [comment]
Things might also be cached somewhere. It could take a while to flush that out. But:
![image](https://user-images.githubusercontent.com/203326/136675980-232336a2-e403-48bc-8210-5bdd8526b233.png)

**Comment by Tony-Goat** [comment]
> Things might also be cached somewhere. It could take a while to flush that out. But:

Looks like it's working! Bravo! :-)
