### ISSUE TITLE
[Suggestion] Portal tracers for nether and end portals

### ISSUE THREAD

**Issue by Sloth8586** [MeteorDevelopment/meteor-client#1581]
### Describe the feature

The ability to have tracers for different types of portals.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
search
