### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by WorldSpinAround** [MeteorDevelopment/meteor-client#1582]
### Describe the bug

Ever since I use the Meteor client as a mod for fabric 1.17.1, whenever I switch profile and version (so no longer using Meteor), I have my gamma so high that I can see everywhere. Each time I have to lower my brightness to stop it. I tested it on DEV, and it is not fixed.

### Steps to reproduce

```bash
Install Meteor, activate either xray or full brightness, then leave and change profile (as long as you no longer use Meteor).
```

### Meteor Version

1.17.1

### Minecraft Version

1.17.1 (and any other)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
That is how Fullbright works.
