### ISSUE TITLE
[Bug] Random crashes

### ISSUE THREAD

**Issue by Dasyat1s** [MeteorDevelopment/meteor-client#1585]
### Describe the bug

Idk my game is crashing a lot for random reasons but always with the same crash lo
[crash-2021-10-16_09.22.55-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7357118/crash-2021-10-16_09.22.55-client.txt)
g 

### Steps to reproduce

```bash
It's either by toggling ca or autocity idek
```

### Meteor Version

1292

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 1d84fe228bd14402081b43e94d7d566e9f34a436.
