### ISSUE TITLE
Add ID in [Storage ESP].

### ISSUE THREAD

**Issue by c0blok** [MeteorDevelopment/meteor-client#1586]
### Describe the feature

I think they should add **ESP** for **chests** that are in a **Minecart** (chest_minecart) I am in a Mineshaft but I can't easily find the **chests**.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Use normal ESP.
