### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Dori-afk** [MeteorDevelopment/meteor-client#1588]
### Describe the feature

I want to be able to play mereor client on all versions so therefor am suggesting that you allow us to play it on all versions

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
meror
