### ISSUE TITLE
[Bug] Vein Miner not triggering if packet Mine has been enabled before

### ISSUE THREAD

**Issue by gP387** [MeteorDevelopment/meteor-client#1598]
### Describe the bug

Vein Miner is not triggering if packet Miner has been enabled before, the packet miner has to be re-enabled to get Vein-miner triggering

### Steps to reproduce

```bash
1. Enable Packet Mine
2. Enable Vein Miner
```

### Meteor Version

0.4.6 1300

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Cannot replicate.
