### ISSUE TITLE
[Suggestion] Improved Nuker range settings

### ISSUE THREAD

**Issue by Tokara1** [MeteorDevelopment/meteor-client#1614]
### Describe the feature

Nuker range should have settings like eg inertia nuker. 
That means: 

Customizable and indipendant range to Left and right from the player ( that means eg 2 blx left 3blx right )
as well as upwards range ( eg 2 blx upwards ).

This would be an improvement since you could dig clean areas way easier ( for example 3 high clearance through netherrack or simmelar )

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RedCarlos26** [comment]
That would be based

**Comment by MineGame159** [comment]
Added in ff15150a2facd1654c9dc9bb3422e8c3826c4704.
