### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AAlchemy** [MeteorDevelopment/meteor-client#1618]
### Describe the bug

Name tag position doesn't line up with intended entity when using ultra-wide display (21:9 aspect)

### Steps to reproduce

```bash
Just enable nametags on any display 21:9 or wider.
```

### Meteor Version

0.4.6-1314

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
Screenshot?

**Comment by AAlchemy** [comment]
![2021-11-29_08 01 25](https://user-images.githubusercontent.com/3503676/143873559-0555168e-171b-4d37-aeed-328a13764259.png)
![2021-11-29_08 01 43](https://user-images.githubusercontent.com/3503676/143873562-c014831d-235b-4452-b6cb-9a9cdbdbffaf.png)
![2021-11-29_08 02 12](https://user-images.githubusercontent.com/3503676/143873564-3da37e78-bdf8-4afa-8251-e2e2c2b64c3e.png)
![2021-11-29_08 02 34](https://user-images.githubusercontent.com/3503676/143873570-0ac02640-f781-4021-a618-b78b97a03dbc.png)
![2021-11-29_08 02 43](https://user-images.githubusercontent.com/3503676/143873573-98ba0a0d-bc1e-4772-ac6b-bf2a4b0252bb.png)
