### ISSUE TITLE
[BUG]swarm not working over 2 pcs in same network

### ISSUE THREAD

**Issue by gabrielmaster123** [MeteorDevelopment/meteor-client#1621]
### Describe the bug

I cannot use swarm on 2 pcs in the same network, I try to do it with localhost and it says no server found on port 7777 (Host is arch linux, worker windows 10)

### Steps to reproduce

```bash
install meteor on arch linux and try to do swarm on 2 machines one arch one windows
```

### Meteor Version

0.4.6-1314

### Minecraft Version

1.17.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnale** [comment]
im pretty sure this was a you issue, if you can still reproduce it, reopen it

**Comment by KalebSchmidlkofer** [comment]
I have the same issue Except both of mine are running windows
