### ISSUE TITLE
[Suggestion] Delay for Fast Use

### ISSUE THREAD

**Issue by SlushFiend** [MeteorDevelopment/meteor-client#1622]
### Describe the feature

Add a customizable tick delay for fast use.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RedCarlos26** [comment]
This is already in the client
