### ISSUE TITLE
[Bug] Chams breaks Norender

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1628]
### Describe the bug

Turning off rendering for players and crystals with the Norender module is broken when Chams is enabled, which forces the client to render them even if they are unselected in every possible way in the Chams module. 

### Steps to reproduce

```bash
Turn on norender and select players to not be rendered. Turn on esp in wireframe mode. Turn on chams and watch as players reappear, even if you deselect them from through walls and to be modified!
```

### Meteor Version

1314

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
this appears to be resolved
