### ISSUE TITLE
[Bug] minecraft crash when trying to customise hud

### ISSUE THREAD

**Issue by ItsIsntItsKeera** [MeteorDevelopment/meteor-client#1629]
### Describe the bug

title

### Steps to reproduce

```bash
1.press click gui bind
2. right click at hud button on top
```

### Meteor Version

0.4.5

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send the crash report.

**Comment by StormyBytes** [comment]
Also update

**Comment by MineGame159** [comment]
@ItsIsntItsKeera

**Comment by ItsIsntItsKeera** [comment]
there no crash report in my folder what

**Comment by ItsIsntItsKeera** [comment]
also i try this time it not crash anymore
