### ISSUE TITLE
[Bug] Baritone crash in modded

### ISSUE THREAD

**Issue by MunchyG** [MeteorDevelopment/meteor-client#1630]
### Describe the bug

Game crashes when standing on (or flying closely over) cables in modded, so far Applied Energistics 2 and Industrial Revolution cables have caused this crash. And I say it is baritone crash because I tried running the baritone snapshot inside the meteor.jar only and the crash still occurred. So I am unsure if this is an issue for meteor development or for Leijurv and the baritone dev team. 

[crash-2021-10-30_22.25.14-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7446775/crash-2021-10-30_22.25.14-client.txt)  (Multiplayer)

[crash-2021-10-30_22.34.38-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7446848/crash-2021-10-30_22.34.38-client.txt)  (Singleplayer)

### Steps to reproduce

```bash
Stand on an Applied Energistics 2 or Industrial Revolution cable

You don't need to be running any baritone programs.
```

### Meteor Version

0.4.6 and 0.4.7-1323

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
We have nothing to do with development of Baritone.

**Comment by MunchyG** [comment]
Is there a branch of meteor that doesn't have baritone, so I can continue to use it in the meantime?

**Comment by MineGame159** [comment]
Nope.

**Comment by MunchyG** [comment]
All good I managed to make a crude build that removed dependency, had to lose a couple modules (weirdly kill aura) but better than nothing
