### ISSUE TITLE
Crystal blocks

### ISSUE THREAD

**Issue by Scc1234567890987654321** [MeteorDevelopment/meteor-client#1631]
### Describe the feature

You can place crystals on blocks even if the block is not obsidian or bedrock (if possible can be used with air-place as well)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
And how woul that work.

**Comment by Wide-Cat** [comment]
this is impossible, so if you can show an example of this being done by another client i would love to see it

**Comment by RickyTheRacc** [comment]
No, you probably just haven't figured it out yet, nice iq 🤓🤓🤓
