### ISSUE TITLE
By version

### ISSUE THREAD

**Issue by Scc1234567890987654321** [MeteorDevelopment/meteor-client#1632]
### Describe the feature

An option to change version within the client - opens a menu with list of versions and you can choose what version you want

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
https://modrinth.com/mod/multiconnect
