### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ovseos** [MeteorDevelopment/meteor-client#1635]
### Describe the bug

Fix the Auto tool if The auto tool is on, if I start breaking dirt it start to auto Switch to different tools like sword pickaxe and like others I dont have a shovel in my inventory and hotbar!

### Steps to reproduce

```bash
Auto Tool
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
This is not a bug, it just chooses the best tool it can find. If you don't want it to do that then open a new issue for new setting.
