### ISSUE TITLE
Kill aura not working when hit chance is changed 

### ISSUE THREAD

**Issue by PeterW1302** [MeteorDevelopment/meteor-client#1636]
### Describe the bug

When I try to change the hit chance, it stays at 100 and then the kill aura can't hit anything.

### Steps to reproduce

```bash
When I try to change the hit chance, it stays at 100 and then the kill aura can't hit anything.
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
Fixed in a recent commit. Can you try on the latest dev build @PeterW1302 ?
