### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Jackesparragos** [MeteorDevelopment/meteor-client#1641]
### Describe the bug

error: package meteordevelopment.meteorclient.addons does not exist
import meteordevelopment.meteorclient.addons.MeteorAddon;
                                            ^
error: cannot find symbol
public class ExempleAddonMain extends MeteorAddon {

// it cannot find "MeteorAddons" but in the latest versions of Meteor Client it is located there...

### Steps to reproduce

```bash
X
```

### Meteor Version

meteor client v0.4.6 build #1308+

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by C10udburst** [comment]
you're using some outdated addon

**Comment by Jackesparragos** [comment]
i tried to compile the template to create the addon:  https://github.com/MeteorDevelopment/meteor-addon-template

**Comment by arlomcwalter** [comment]
the meteor version you are using is outdated, update

**Comment by arlomcwalter** [comment]
> you're using some outdated addon

nah, its an issue with the meteor version not the addon
