### ISSUE TITLE
[Suggestion] New options for no-fall

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1646]
### Describe the feature

It would be cool if there would be options that :
        - enables it only in elytra mode
	- disables it automatically and temporarily when jumping (because no fall + jump = tpback when the server have anticheats)
	- allows the player to fall (so no-fall would only be useful for cancelling any fall damage)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
literally all of this is incorrect
