### ISSUE TITLE
[Bug] Player is moving while in freecam

### ISSUE THREAD

**Issue by TyraVex** [MeteorDevelopment/meteor-client#1651]
### Describe the bug

It is possible to make the player move forward by sprinting in the freecam module.

### Steps to reproduce

```bash
Enable freecam
Go forward in freecam and play with the control key
The player moves

In video :
https://youtu.be/-KVBi1wCmhc
```

### Meteor Version

0.4.7

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by AsherY8979** [comment]
can confirm for latest dev build

**Comment by MineGame159** [comment]
Cannot reproduce.
