### ISSUE TITLE
CA improvments 

### ISSUE THREAD

**Issue by Dasyat1s** [MeteorDevelopment/meteor-client#1653]
### Describe the feature

An option to disable the automatic faceplace on people that are auto trapped (useless waste of crystals) and an option to make it so you can eat while crystalling (useful for 1.12 servers)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Turn off "pause on eat" for 1.12

**Comment by RedCarlos26** [comment]
Yes

**Comment by RedCarlos26** [comment]
Why was this closed? It's actually useful caus face place trough blocks only does 0.1 damage per crystal
