### ISSUE TITLE
[Bug] Baritone Water Crash

### ISSUE THREAD

**Issue by LethalAspect** [MeteorDevelopment/meteor-client#1656]
### Describe the bug

Just a simple crash bug that is really annoying.

### Steps to reproduce

```bash
1. Use baritone and set a path to a island where water surrounds it.
2. Use freecam when baritone is moving towards the island.
3. When crossing the water, disable freecam.
4. Get crashed by minecraft.


Note: This bug might be me, i dont know.
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
Post the crash report

**Comment by arlomcwalter** [comment]
@LethalAspect post the crash report please.

**Comment by LethalAspect** [comment]
[crash-2021-11-05_16.06.26-server.txt](https://github.com/MeteorDevelopment/meteor-client/files/7517772/crash-2021-11-05_16.06.26-server.txt)
[crash-2021-11-05_14.27.46-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7517773/crash-2021-11-05_14.27.46-client.txt)

**Comment by arlomcwalter** [comment]
> [crash-2021-11-05_14.27.46-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7517773/crash-2021-11-05_14.27.46-client.txt)
> 
> 

that crash report has absolutely nothing to do with jesus or baritone or water, it is a crash to do with the locate command

**Comment by arlomcwalter** [comment]
fixed in the latest commit

**Comment by Wide-Cat** [comment]
> that crash report has absolutely nothing to do with jesus or baritone or water

Bruh
