### ISSUE TITLE
Zoom Feature

### ISSUE THREAD

**Issue by Ovseos** [MeteorDevelopment/meteor-client#1657]
### Describe the bug

The Zoom feature is not Working for some reason if I turn on Zoom it does nothing and I think its a bug

### Steps to reproduce

```bash
Using Zoom Feature
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
I've never experienced problems with zoom

**Comment by LethalAspect** [comment]
Try to rejoin or refresh your minecraft.
