### ISSUE TITLE
[Suggestion] make the dev build available for 1,16

### ISSUE THREAD

**Issue by ppmaster69** [MeteorDevelopment/meteor-client#1659]
### Describe the feature

aint it a bit rude huh?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
https://modrinth.com/mod/multiconnect
