### ISSUE TITLE
Add setting to Trigger.java

### ISSUE THREAD

**Issue by N08I40K** [MeteorDevelopment/meteor-client#166]
`/*
 * This file is part of the Meteor Client distribution (https://github.com/MeteorDevelopment/meteor-client/).
 * Copyright (c) 2020 Meteor Development.
 */

package minegame159.meteorclient.modules.combat;

import me.zero.alpine.listener.EventHandler;
import me.zero.alpine.listener.Listener;
import minegame159.meteorclient.events.world.TickEvent;
import minegame159.meteorclient.modules.Category;
import minegame159.meteorclient.modules.Module;
import minegame159.meteorclient.settings.BoolSetting;
import minegame159.meteorclient.settings.Setting;
import minegame159.meteorclient.settings.SettingGroup;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.entity.LivingEntity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.util.Hand;
import minegame159.meteorclient.utils.player.Chat;

public class Trigger extends Module {
    private final SettingGroup sgGeneral = settings.getDefaultGroup();

    private final SettingGroup sgShield = settings.createGroup("Shield");

    private final Setting<Boolean> onlyWhenHoldingAttack = sgGeneral.add(new BoolSetting.Builder()
            .name("only-when-holding-attack")
            .description("Attacks only when you are holding left click.")
            .defaultValue(false)
            .build()
    );

    private final Setting<Boolean> NoShield = sgShield.add(new BoolSetting.Builder()
            .name("not-attack-on-shield")
            .description("Do not attack if using a shield.")
            .defaultValue(false)
            .build()
    );

    public Trigger() {
        super(Category.Combat, "trigger", "Automatically swings when you look at entities.");
    }

    @EventHandler
    private final Listener<TickEvent.Post> onTick = new Listener<>(event -> {
        if (mc.player.getHealth() <= 0 || mc.player.getAttackCooldownProgress(0.5f) < 1) return;
        if (!(mc.targetedEntity instanceof LivingEntity)) return;
        if (((LivingEntity) mc.targetedEntity).getHealth() <= 0) return;
        if (filterattack()) attack();
    });

    private boolean filterattack()
    {
        if (NoShield.get()) {
            if (mc.options.keyUse.isPressed() && mc.player.getEquippedStack(EquipmentSlot.OFFHAND).getItem() == Items.SHIELD) return false;
        }
        if (onlyWhenHoldingAttack.get())
        {
            if (!mc.options.keyAttack.isPressed()) return false;
        }
        return true;
    }

    private void attack() {
        mc.interactionManager.attackEntity(mc.player, mc.targetedEntity);
        mc.player.swingHand(Hand.MAIN_HAND);
    }
}`

**Comment by supakeks** [comment]
Why not make it a pull request instead?

**Comment by N08I40K** [comment]
It sounds stupid but I don't know how to do it

**Comment by squidoodly** [comment]
I'm assuming you have a fork if you have made this?

**Comment by N08I40K** [comment]
I downloaded the source code

**Comment by dakone22** [comment]
@N08I40K, если ты уверен, что код рабочий, то можешь добавить изменения через GitHub:
![image](https://user-images.githubusercontent.com/35692622/104934701-7f093b80-59bb-11eb-8a2b-61338a918984.png)

GitHub за тебя создаст форк, ветку, а затем и pull request.

**Comment by N08I40K** [comment]
> @N08I40K, если ты уверен, что код рабочий, то можешь просто добавить изменения через GitHub:
> ![image](https://user-images.githubusercontent.com/35692622/104934701-7f093b80-59bb-11eb-8a2b-61338a918984.png)
> 
> GitHub за тебя создаст форк, ветку, а затем и pull request.

Да спасибо за совет, я уже создал форк :)

**Comment by notseanyay** [comment]
russian moment

**Comment by N08I40K** [comment]
> russian moment

:D почему бы и нет))
