### ISSUE TITLE
better nuker like inertias(could steal code from wwe deobf leak)[Suggestion] 

### ISSUE THREAD

**Issue by ppmaster69** [MeteorDevelopment/meteor-client#1660]
### Describe the feature

inertia nuker sooo much <meteor nukereasiar to cinfigure and the creative feature is nice too that they have speeds up mining by a long shot
so is they packet elytra mode just saying
wwe deobf leak has it a little convertion could work on meteor

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
1. #744 #1614
2. If those are not what you mean then make an issue what should be improved, not just that a nuker from other client is better.
