### ISSUE TITLE
[Suggestion] Tick delays

### ISSUE THREAD

**Issue by jumst3rvr** [MeteorDevelopment/meteor-client#1662]
### Describe the feature

Add a tick delay of placing blocks for scaffold, auto trap, surrounde etc.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RedCarlos26** [comment]
Blocks per tick would be better in my opinion

**Comment by arlomcwalter** [comment]
> Blocks per tick would be better in my opinion

you can only safely place one block per tick in minecraft

**Comment by arlomcwalter** [comment]
> Add a tick delay of placing blocks for scaffold, auto trap, surrounde etc.

Delay for scaffold would just be horrible to use, thats kinda missing the point of scaffold. Surround already has a delay. Auto trap has one i'm pretty sure, let me check rq.
