### ISSUE TITLE
[Suggestion]  Anti-Lag Module

### ISSUE THREAD

**Issue by LethalAspect** [MeteorDevelopment/meteor-client#1663]
### Describe the feature

A Anti-Lag module, this module will remove armor stands and particle effects. This module would be really great if someone is trying to lag the server, it will lag the server, but you might have less lag than the others.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by StormyBytes** [comment]
already exists. it's under no render
