### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by HiongZ** [MeteorDevelopment/meteor-client#1665]
### Describe the feature

The feature is seed based xray for servers with anti xray. I have the source for it.

https://github.com/19MisterX98/DiamondSim

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
This is a duplicate of #537, with the same exact github repo linked.
As you can see by the activity in the original issue, someone is working on it probably.

**Comment by RedCarlos26** [comment]
@MineGame159 ^^
