### ISSUE TITLE
[Suggestion] Potion Hud Positioning and interaction with other HUD modules

### ISSUE THREAD

**Issue by bakjedev** [MeteorDevelopment/meteor-client#1667]
### Describe the feature

For the potion effects in the HUD to change positioning of other HUD modules when potion effects change
![bigmetoerhacksuggest](https://user-images.githubusercontent.com/59623580/141137946-1a7cf017-4046-4376-9a2a-c8c9c5a250f8.png)
So that when i get more effects my other hud modules (fps tps ping move down)

i hope this explains i find it very hard to explain especially because im not english 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
merge with #3064
