### ISSUE TITLE
[Suggestion] Motion Blur

### ISSUE THREAD

**Issue by xzkael18** [MeteorDevelopment/meteor-client#1668]
### Describe the feature

That smooth-like effect whenever we move our mouse  or when we move. Would be great for pvp/cpvp or generally have it, making it more great to play the game. (There's already a similar feature called "Blur", which blurs the UI background. If we have that kind of feature, then why not add the "motion" one too?) 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
No, get Canvas or Iris.
