### ISSUE TITLE
[Suggestion] schematic

### ISSUE THREAD

**Issue by adamkovava** [MeteorDevelopment/meteor-client#1669]
### Describe the feature

need to put schematic files somewhere? And is there a file that "litematic" where to put it?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Please translate to english.

**Comment by StormyBytes** [comment]
I think they meant baritone's schematic building

**Comment by adamkovava** [comment]
It's english. yeah baritone

**Comment by adamkovava** [comment]
i don't know how to load them

**Comment by adamkovava** [comment]
> I think they meant baritone's schematic building

can u help me mate?

**Comment by StormyBytes** [comment]
ask that to baritone developers / support,  not us.

**Comment by adamkovava** [comment]
okay
but the "real" baritone has custom controlls to save the schematic
