### ISSUE TITLE
Better Tab

### ISSUE THREAD

**Issue by Sprink02** [MeteorDevelopment/meteor-client#1670]
### Describe the feature

I am thinking a way to toggle tab

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RedCarlos26** [comment]
Just do not press tab or unbind it?

**Comment by RickyTheRacc** [comment]
Okay retard
