### ISSUE TITLE
[Suggestion] Keystrokes 

### ISSUE THREAD

**Issue by 123stein** [MeteorDevelopment/meteor-client#1671]
### Describe the feature

A Customizable Mod that displays WASD, LMB, RMB although these keys can be changed(individual Key positions and your own Keys) 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by LethalAspect** [comment]
You could just download the mod ya know :|

**Comment by RedCarlos26** [comment]
Yes just download the mod meteor is not like all the mods in one lol

**Comment by RedCarlos26** [comment]
@arlomcwalter ^^^
