### ISSUE TITLE
A problem 

### ISSUE THREAD

**Issue by Y0uBetterCat** [MeteorDevelopment/meteor-client#1673]
### Describe the bug

Hey i recently installed the mod and i have a "bug" if i can call it taht way. the problem is my pickaxe is alyways pulled in my hotbar and i dont know why, i already tried reinstalling it but that didnt fix the issue. It wasnt like this from the start but since today i have this problem or "bug" whatever you call it

https://user-images.githubusercontent.com/94190372/141507750-8019f9cf-cb9f-45b7-9ba5-e4385961bf5b.mp4
 

### Steps to reproduce

```bash
see in the video
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Do `#allowInventory false`. It is caused by Baritone.

**Comment by Y0uBetterCat** [comment]
Thank you it works now fine again
