### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by BIBiIK** [MeteorDevelopment/meteor-client#1674]
### Describe the bug

Scaffold do not place blocks when i play on servers on servers [here](https://youtu.be/-NDiU7r_GKM)
Once don`t place when i was in singleplayer

### Steps to reproduce

```bash
You must on scaffold and sprint.
```

### Meteor Version

0.4.7

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
1. Don't use Meteor on servers where it's not allowed.
2. Most probably an issue with the anti cheat.
