### ISSUE TITLE
[Suggestion] Star chams shader

### ISSUE THREAD

**Issue by Dasyat1s** [MeteorDevelopment/meteor-client#1677]
### Describe the feature

![image](https://user-images.githubusercontent.com/86971319/141653707-1198060d-5f43-43c8-bd40-e1246952793e.png)
Looks dope

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Wide-Cat** [comment]
send a link to the shader file

**Comment by Dasyat1s** [comment]
> 

i don't have it sadly looks good tho

**Comment by master7720** [comment]
bruh
