### ISSUE TITLE
[Suggestion] Stop on Health

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1679]
### Describe the feature

Allow the player to choose a health at which Crystal Aura stops placing, this is somewhat covered by offhand if you use it, but with main handing the only option is Anti Suicide which pauses at 1 health and leaves you to be easily popped.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by LethalAspect** [comment]
Auto Log?

**Comment by RickyTheRacc** [comment]
You're a retard, ignored

**Comment by LethalAspect** [comment]
dont care lol
