### ISSUE TITLE
[Suggestion] Anti-Blindness

### ISSUE THREAD

**Issue by LethalAspect** [MeteorDevelopment/meteor-client#1680]
### Describe the feature

A Anti-Blindness module! This module will remove all visual negative effects. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by TheRedHippo** [comment]
enable norender and check your settings

**Comment by LethalAspect** [comment]
World, Hud, or Overlay

**Comment by LethalAspect** [comment]
Ok, thx
