### ISSUE TITLE
[Bug]  Cobblestone, dirt and stone get stuck on last hotbar slot

### ISSUE THREAD

**Issue by Broekinator** [MeteorDevelopment/meteor-client#1683]
### Describe the bug

Every time when I have dirt, cobblestone or stone in my inverntory, and I close my inventory, the stack of block in question ALWAYS teleports into my 9th hotbar slot. Whenever I try to put it back into my inventory, it just teleports back.
I also have this issue just now with my pickaxe on a Minecraft server.

The strange part is that my friends don't have this issue at all, while also using Meteor.
Also, no errors on server and client (checked multiple times)
Link to see what I am exactly talking about: https://imgur.com/a/6yTSLAh

### Steps to reproduce

```bash
1. Install Meteor Client, no other mods needed.
2. Open Minecraft in survival
3. Get some cobblestone
4. Place it in the 9th slot or sum
```

### Meteor Version

0.4.6 AND 0.4.7 - 1334

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
It is Baritone. Do `#allowInventory false`.
