### ISSUE TITLE
aim assist smoothing 

### ISSUE THREAD

**Issue by cat11xx** [MeteorDevelopment/meteor-client#1685]
### Describe the feature

smoothing would make the aim assist look more legit by making it so the players head doesnt snap onto the target 
this can be added on a slider like aim speed

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by master7720** [comment]
yes we need this

**Comment by zeroxoneafour** [comment]
Are you sure this doesn't exist? I'm pretty sure you can toggle it

**Comment by arlomcwalter** [comment]
> Are you sure this doesn't exist? I'm pretty sure you can toggle it

yeah it does, you have to disable instant look
