### ISSUE TITLE
Farming Aura

### ISSUE THREAD

**Issue by mrGRINCH** [MeteorDevelopment/meteor-client#1689]
### Describe the feature

Farming Aura from Atomic client.

https://github.com/0x151/Atomic/blob/master/src/main/java/me/zeroX150/atomic/feature/module/impl/world/FarmingAura.java

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RedCarlos26** [comment]
@mrGRINCH tbis is already in the client

**Comment by mrGRINCH** [comment]
@RedCarlos26 @arlomcwalter would you care to show me where? meteor client v0.4.7 build #1373 btw.

https://i.imgur.com/ko5MSVY.png
