### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RobinDcGitHub** [MeteorDevelopment/meteor-client#1690]
### Describe the bug

When using spawn proofer and u run out of torches, the game crashes for some reason

### Steps to reproduce

```bash
Get a stack of torches and start using spawn proofer. Start running around and when you ran out of torches
the game crushes
```

### Meteor Version

meteor-client-0.47-1334

### Minecraft Version

1.17.1 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by LethalAspect** [comment]
Send the crash report

**Comment by Wide-Cat** [comment]
send the crash report @RobinDcGitHub or theres not too much we can do
