### ISSUE TITLE
[Bug] Time since last tick not showing

### ISSUE THREAD

**Issue by oliver408i** [MeteorDevelopment/meteor-client#1692]
### Describe the bug

![image](https://user-images.githubusercontent.com/75344601/142775000-caf1091f-7952-440b-949a-eceaf515d522.png)
editor says

But ingame is just disappears
![image](https://user-images.githubusercontent.com/75344601/142775006-388db6d8-cc62-45fc-b9b7-b0c533f5fe91.png)

### Steps to reproduce

```bash
just log into a server and turn on HUD and time since last tick
```

### Meteor Version

Lastest

### Minecraft Version

1.17.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by oliver408i** [comment]
Now noticed it flashes once in a while

**Comment by RedCarlos26** [comment]
It is normal it does not show unless the server lags
