### ISSUE TITLE
[Bug] Crash on disconnect

### ISSUE THREAD

**Issue by oliver408i** [MeteorDevelopment/meteor-client#1693]
### Describe the bug

When I disconnect from ANY server, it says saving world then quit
Crash report:

[crash-2021-11-21_11.53.33-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7576975/crash-2021-11-21_11.53.33-client.txt)
s.

### Steps to reproduce

```bash
Join a random server. Disconnect
```

### Meteor Version

Lastest

### Minecraft Version

1.17.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Dasyat1s** [comment]
heppening to everyone even on windows, happens when loggin on as well

**Comment by oliver408i** [comment]
Anyway to fix?

**Comment by AsherY8979** [comment]
lmk if you find something

**Comment by RedCarlos26** [comment]
Wait what that never happened to me :/

**Comment by MineGame159** [comment]
Should be fixed in 5633f74f5cc2e588f9fedd6753ac2be650a0e17d.
