### ISSUE TITLE
[Suggestion] Norender item names

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1694]
### Describe the feature

Add an option to norender to not render the item name when you switch items, as it clutters up your hud and would be nice to not have

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Added.
