### ISSUE TITLE
[Suggestion] Color Settings

### ISSUE THREAD

**Issue by necrophili** [MeteorDevelopment/meteor-client#1703]
### Describe the feature

Let ppl ctrl c ctrl v color settings pwease plszsssssz 🛐 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
YES

**Comment by RedCarlos26** [comment]
Yesss
