### ISSUE TITLE
Fix NoRender blindness for Sodium [Suggestion] 

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1705]
### Describe the feature

Based on #1696 I was told I have to ask for this to be added as a suggestion.
The suggestion would be to make blindness and the water overlay work on sodium.
I am using a mac with the latest 1.17.1 dev build of sodium (https://github.com/CaffeineMC/sodium-fabric/actions/runs/1495670671). I tried it on other versions of sodium and cant get rid of blindness/water overlay. 
Also when distortion effects are set to 0%, the nausea overlay still appears but can be easily removed using a texturepack. (report as a bug?)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Wide-Cat** [comment]
this should be resolved
