### ISSUE TITLE
Module: Shader Chams

### ISSUE THREAD

**Issue by Lence2b2t** [MeteorDevelopment/meteor-client#1711]
### Describe the feature

Essentially, this would function as any other chams, but instead of rendering entities as a color or their natural texture through walls, it would render a photo of a sort (it would be cool if this was customizable; i.e. you could drop a photo into the meteor folder and load it in)

note: this doesn't necessarily have to be its own module, it could just be a mode on the chams module already in meteor

> 
![Screenshot_20211125-091655_YouTube](https://user-images.githubusercontent.com/85973963/143481681-8816d04c-6cfe-456c-9749-28313d16052e.jpg)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Shaders are not just an image. Send the shader that you want and then reopen this issue.
