### ISSUE TITLE
[Suggestion] Add functionality to the infinity miner module to have multiple target blocks and/or repair blocks.

### ISSUE THREAD

**Issue by Lexlogan312** [MeteorDevelopment/meteor-client#1718]
### Describe the feature

Add functionality to the infinity miner module to have multiple target blocks and/or repair blocks.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Myithspa25** [comment]
Yes
