### ISSUE TITLE
[Suggestion] Autoblock

### ISSUE THREAD

**Issue by zeroxoneafour** [MeteorDevelopment/meteor-client#1721]
### Describe the feature

A feature where, after you hit something, you block. Would work with KillAura, or without (similar to how Criticals can be KA-only or not.) It should work with shields and possibly swords, if using MultiConnect on a 1.8.x server. Maybe could also block incoming projectiles, such as arrows, or automatically brace for things such as fireballs or ghast fireballs.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
#2012
