### ISSUE TITLE
[Suggestion] Toggling entity groups using .settings

### ISSUE THREAD

**Issue by zeroxoneafour** [MeteorDevelopment/meteor-client#1722]
### Describe the feature

When configuring entity target settings manually for hacks such as KillAura or ESP, you can toggle whole groups (ex. players, animals, monsters) at a time. However, when configuring via the `.settings` command, you can only toggle individual entity types per each value. Typing out each of these values to toggle a single category (ex. monsters) is time consuming, and even more so if you are putting them in several macros to toggle target groups. So, I am suggesting that when there is an `entities` configuration option in the `.settings` command, you can toggle whole groups at once without having to write out each individual member. So, instead of doing, say,
```
.settings kill-aura entities player, zombie, skeleton, enderman, spider, ...
```
you could do
```
.settings kill-aura entities player, monsters
```
instead. This would make writing macros for target changing or entering quick configuration changes much easier.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Wide-Cat** [comment]
8a7079652a6bd42cc6acc5cfe8eb917e5d1d0199
