### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BIBiIK** [MeteorDevelopment/meteor-client#1728]
### Describe the bug

Crystal Aura does not work.

### Steps to reproduce

```bash
on crystal aura
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
This is easy to fix, you just

**Comment by BIBiIK** [comment]
> 

so what i need to do?

**Comment by BIBiIK** [comment]
@RickyTheRacc

**Comment by BIBiIK** [comment]
what i need to do?
