### ISSUE TITLE
[Bug] Infinity Module Does Not Work

### ISSUE THREAD

**Issue by Lexlogan312** [MeteorDevelopment/meteor-client#1729]
### Describe the bug

When trying to use the new Infinity module, no matter what I do it responds with doing nothing and sending the error message, "Could not find a usable pickaxe." I have tried to turn off auto tool, tried enchanting pickaxes differently, having only a fortune pick in my inventory/hotbar, and more but have not gotten anything to get it to work.

Video of the error: https://user-images.githubusercontent.com/53305449/143773311-732843b6-835d-42db-b10a-fbf422337b69.mp4

Auto Tool Settings (Have tried with it turned off): https://user-images.githubusercontent.com/53305449/143773363-b83eec84-fa40-4006-94ae-5c9b0ea27711.png

### Steps to reproduce

```bash
1. Turn on or off auto tool
2. Get any pickaxe and put it in the hotbar
3. Turn on infinity miner
4. See error message
```

### Meteor Version

Dev Build 0.4.7 build #1340

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Seasnail issue

**Comment by arlomcwalter** [comment]
you need mending
