### ISSUE TITLE
[Suggestion] Chat For Meteor Client Users

### ISSUE THREAD

**Issue by LethalAspect** [MeteorDevelopment/meteor-client#1731]
### Describe the feature

This feature allows users that use meteor client to chat with each other. This allows users that have meteor to talk with each other privately. This can be done by using a .chat command.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by StormyBytes** [comment]
devs already said this won't be added. just use the discord
