### ISSUE TITLE
[Suggestion] Add Branch Mining/Strip Mining Module/Baritone Setting

### ISSUE THREAD

**Issue by Lexlogan312** [MeteorDevelopment/meteor-client#1733]
### Describe the feature

Add a module or custom baritone setting that basically combines baritones tunnel and legitmine where it mines tunnels and branches to create a better legitmine in a pattern like so: 
![image](https://user-images.githubusercontent.com/26852749/77428302-c50f6600-6dcf-11ea-9749-d8ace4bb3d63.png)

When ores are made visible, mine them and continue the pattern.

Possible settings:
Y-level
Ignored Ores
Tunnel Spacing
Etc.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
This is already a feature, open the baritone tab at the top of the clickgui and enable "Legit mine."

**Comment by Lexlogan312** [comment]
I know that legit mine is a thing, but I’m talking about making actual branch mining. Legit mine sometimes goes in a straight strip mine path but then also goes off and randomly mines most of the time. This would be controlled and imo better than just mining randomly and is a more “legit” way of mining

**Comment by emir4169** [comment]
Uhm, baritone isn't here temporarily are you stuck on 1.17.1 versions?

**Comment by emir4169** [comment]
> Uhm, baritone isn't here temporarily are you stuck on 1.17.1 versions?

Well, It could be added but then I would know it from the discord server

**Comment by Lexlogan312** [comment]
@emir4169 Yes, I am on the dev build for 1.17.1, not 1.18 because I don’t need it and since it doesn’t have baritone. I’m perfectly fine waiting for a while if they are currently working on the 1.18 version though and until they get baritone working
