### ISSUE TITLE
[Suggestion] Here i have some idea's to improve Meteor Client!

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#1737]
### Describe the feature

1. Add Custom Totem (i dont know if this is possible)
2. Add Chat Translator (i dont know if this is possible)
3. Add Killer bot
4. Add Bonemeal Aura
5. Add Turn Off/Turn On Meteor Client (without removing from the mods file :V)
6. Make Bow Aimbot better more better! (Always miss when the enemy is running)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Make one feature per issue but:
1. I have no idea what that is.
2. #1022
3. No, best thing you can do is follow entities with baritone and enable Kill Aura.
5. There is `.panic` command which disables all modules, completely turning it off is impossible.
6. Can't really predict where the player will go.

**Comment by SussyBob** [comment]
custom totem its like custom totem of undying picture (icon)
![Custom Totem](https://user-images.githubusercontent.com/95006470/144563756-0e35d8b4-5b61-4c19-be96-295bc81ac9e4.png)
)

if you want the resourcepack you can dm me Couriersix11#0672
ALSO 1 MORE, BETTER MOUNT HUD (show your hunger bar when riding a horse)
