### ISSUE TITLE
[Suggestion] i more idea :)

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#1738]
### Describe the feature

8. Add Better Mount HUD (show your hunger bar when riding a horse)
9. Locate where is your pet (i dont know if this is possible)
10. Add Custom Totem of Undying (i dont know if this is possible), here is the example:

![Custom Totem](https://user-images.githubusercontent.com/95006470/144564552-d4bc527a-674e-4365-ba66-bd8df59388ad.png)
Here is the Resourcepack: [Couriersix11's Custom Totem of Undying.zip](https://github.com/MeteorDevelopment/meteor-client/files/7647642/Couriersix11.s.zip)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Did you not read my comment on your previous issue????
**_One feature per issue._**

But:
9. Not possible.
10. Just use the fucking resource pack.
