### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jaysz0101** [MeteorDevelopment/meteor-client#1743]
### Describe the bug

everytime i click on an server or click on ''acounts'' or ''proxity'' my minecraft gets closed and i get an ''code 0'' wat does this mean

### Steps to reproduce

```bash
file above
```

### Meteor Version

1.17-1.18

### Minecraft Version

17.1-18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
@jaysz0101 ^
