### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sebkopter** [MeteorDevelopment/meteor-client#1745]
### Describe the bug

Minecraft Crashes when launching in 1.18

### Steps to reproduce

```bash
when i try to lauch minecraft 1.18 with fabric, fabric api and meteor it crashes before it´s even started
```

### Meteor Version

0.4.6

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Update to latest dev build.
