### ISSUE TITLE
[Bug] AbstractFurnaceScreenHandler.isSmeltable

### ISSUE THREAD

**Issue by VolcanoCookies** [MeteorDevelopment/meteor-client#1750]
### Describe the bug

Game crashes when shift-clicking smeltable items into a furnace.

[crash-2021-12-04_13.00.55-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7653868/crash-2021-12-04_13.00.55-client.txt)

### Steps to reproduce

```bash
Open a furnace, shift-click an item to put it in the furnace, game crashes.
```

### Meteor Version

meteor-client-0.4.7-1355

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by StormyBytes** [comment]
send the crash report

**Comment by VolcanoCookies** [comment]
Its attached in the initial message?

**Comment by StormyBytes** [comment]
oh sorry, somehow missed that.

**Comment by MineGame159** [comment]
Cannot reproduce.
