### ISSUE TITLE
[Suggestion] Blockselection in Spectator

### ISSUE THREAD

**Issue by ColGroLoOl** [MeteorDevelopment/meteor-client#1751]
### Describe the feature

Hide the custom block selection, when you are in spectator mode or using freecam, just like the vanilla block selection

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MoMMde** [comment]
# Created PR for this
https://github.com/MeteorDevelopment/meteor-client/pull/1789
