### ISSUE TITLE
[Bug] Cant update addons

### ISSUE THREAD

**Issue by CheFuls** [MeteorDevelopment/meteor-client#1752]
### Describe the bug

Cant update addons for meteor 1.18

### Steps to reproduce

```bash
Massive cope
```

### Meteor Version

Last devbuild

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
What?

**Comment by CheFuls** [comment]
Im trying to update my addon for latest meteor and i cant do it
It just failes build

**Comment by MineGame159** [comment]
Look at the [addon template](https://github.com/MeteorDevelopment/meteor-addon-template).
