### ISSUE TITLE
[Bug]  impossible to put waypoints under y = 0

### ISSUE THREAD

**Issue by mijax** [MeteorDevelopment/meteor-client#1753]
### Describe the bug

waypoints under y= 0 are impossible, the value changes back to 0 when you put it on a negative value.

### Steps to reproduce

```bash
waypoints under y= 0 are impossible, the value changes back to 0 when you put it on a negative value.
```

### Meteor Version

0.4.7 build 1349

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in db3b567ca17eaf647d0e5e655677d6b01e130123.
