### ISSUE TITLE
[Bug] teleport to ground and die

### ISSUE THREAD

**Issue by Chivalry0** [MeteorDevelopment/meteor-client#1754]
### Describe the bug

If I'm in survival (With no fall on) in 1.18 and fly with the flight hack, I can teleport myself to the ground and take lots of fall damage. I was doing this over and over and I didn't know why I was dyeing so I made a single player world and I was able to do it over and over again. On servers (I did it on an anarchy minehut server) it worked half the time, the other half it would teleport me back to where I started before falling. I also did this in survival.  

### Steps to reproduce

```bash
If I fly with the flight hack and disable it midair and fall then activate and deactivate flight quickly I'm teleported to the ground and take a large amount of fall damage. I use the key 'G' as my key bind for flight. This happens on my single player world that I was testing different commands on. When I do this on servers it either glitches me back to where I was before I started falling or it just kills me like it does on my single player world.
```

### Meteor Version

Dev build 0.4.7 - 1357

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ShaniZ-VK** [comment]
This is not the bug. The hack doesn't give you the ability to fly exactly like in the creative. The mechanics of falling are still working and how many blocks up you fly, how much damage you will get

**Comment by AsherY8979** [comment]
Please don't write a narrative in any issue on GitHub.

For example, in this issue, you could have said:

"When clickTPing(?) to the ground using nofall and flight, I take fall damage."

The second part of your issue is ambiguous. If I interpreted it correctly, in that you sometimes rubberband, that's not something that can be fixed.
