### ISSUE TITLE
[Bug] Configs not Saving

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1760]
### Describe the bug

Loading profiles will seemingly at random just not update some of the modules when joining a new server. 

### Steps to reproduce

```bash
I'm not sure, I guess just create two different profiles with different modules enabled and swap between servers? I can't even tell how to get this bug to happen
```

### Meteor Version

1356

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
what a helpful issue

**Comment by RickyTheRacc** [comment]
You're welcome seasnail

**Comment by RedCarlos26** [comment]
Duplicate of #
