### ISSUE TITLE
[Suggestion]  Hide tracer when pressing F1

### ISSUE THREAD

**Issue by naBBolethano** [MeteorDevelopment/meteor-client#1761]
### Describe the feature

As described in the title, nothing special, It's an inconsistency in the modules because everything gets hidden when pressing f1 except tracers.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Mans said what we're all thinking

**Comment by DesiCow** [comment]
Someone forgot to close this issue 👀
