### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Warwarwarpl** [MeteorDevelopment/meteor-client#1765]
### Describe the feature

add a module named Multihand who allows to mine blocks atack enemies when holding shield, eating food, pulling bow etc such when you holding shield you can eat golden apple 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by CheFuls** [comment]
Called MultiTask and it was in Ares and other clients like skids or idk. So it can be added into meteor.
