### ISSUE TITLE
Uhm actualy... I did something wrond :/

### ISSUE THREAD

**Issue by CheFuls** [MeteorDevelopment/meteor-client#1766]
### Describe the bug

![image](https://user-images.githubusercontent.com/82179217/144916186-e8110d36-f568-4860-a5f9-f5bcc1b15b57.png)
That bug was actualy was caused by ESP 
Config:
![image](https://user-images.githubusercontent.com/82179217/144916262-7a6c97df-f866-4d8a-8d57-65c21b4ac899.png)

P.S. This bug was caused by turning on and off iris shaders. Or idk.

### Steps to reproduce

```bash
Repeat what said in description of issue.
```

### Meteor Version

Last devbuild

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by CheFuls** [comment]
Ok thats funny but it isnt

**Comment by MineGame159** [comment]
Already reported.
