### ISSUE TITLE
[Bug] [Infinity Miner]  Could not find a usable pickaxe

### ISSUE THREAD

**Issue by andreski6y** [MeteorDevelopment/meteor-client#1771]
### Describe the bug

When i turn on Infinity Miner, then writes to me in the chat: [Meteor] [Infinity Miner] Could not find a usable pickaxe. 
![kaim kgf](https://user-images.githubusercontent.com/95772281/145261493-81452e92-adbc-4f18-b05f-334f8410e482.PNG)

### Steps to reproduce

```bash
I wanted to afk when infinity miner mining
```

### Meteor Version

0.4.7 - 1361

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
You need the mending enchantment on your pickaxe, obviously. If you just want to mine a block then use normal baritone function (`#mine block_id`).
