### ISSUE TITLE
[Suggestion] Remove playerheads

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1774]
### Describe the feature

Garbage module, there are separate mods that do the same thing and look better than this. Apart from that I've known one person ever use this since it was added

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Then provide feedback what can be improved, I think it is quite cool.

**Comment by arlomcwalter** [comment]
but it barely works? its not "provide feedback" its just bad.

**Comment by arlomcwalter** [comment]
and idk if there is a way of it being better but i would agree to remove it

**Comment by RickyTheRacc** [comment]
It can be improved by removing it

**Comment by RedCarlos26** [comment]
The module is actually cool ngl. Just disable it if you do not like it lmao

**Comment by arlomcwalter** [comment]
ita not "actually cool ngl" because it barely works

**Comment by RedCarlos26** [comment]
What? Works perfectly for me...

**Comment by seasnail8169** [comment]
> What? Works perfectly for me...

it doesnt, you are just too stupid to notice
