### ISSUE TITLE
Baritone not mining any Deepslate type blocks?[Bug] 

### ISSUE THREAD

**Issue by AryonLegacy** [MeteorDevelopment/meteor-client#1777]
### Describe the bug

Baritone doesnt work when trying to mine deepslate blocks using .b mine command.

### Steps to reproduce

```bash
1. type in chat: .b mine deepslate_diamond_ore
```

### Meteor Version

v0.4.7-1362

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by StormyBytes** [comment]
We ain't baritone devs

**Comment by AryonLegacy** [comment]
> 

baritone issue
