### ISSUE TITLE
[Bug] FPS drop

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#1782]
### Describe the bug

FPS drop while mining using baritone

### Steps to reproduce

```bash
FPS drop to 3 FPS from 53-61 FPS, No reason why...
```

### Meteor Version

0.4.7 Dev Build Version - 1362

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by cristiioan** [comment]
While I don't help at this project, I had similar issues with baritone on old harware and different clients. You should first report it on the baritone github repo.

**Comment by MineGame159** [comment]
Make a new issue with more info, just saying "I have less FPS" doesn't help us at all. Make sure it is Meteor doing it, try turning off different modules to narrow down the issue, provide a list of the mods you use, provide a Spark profiler link, etc.
