### ISSUE TITLE
[Suggestion] CHAT TRANSLATOR!

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#1783]
### Describe the feature

Add chat translator so we can understand what they say :V
Translate chat to selected language!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by StormyBytes** [comment]
already suggested

**Comment by MineGame159** [comment]
#1022
