### ISSUE TITLE
[Bug] (low priority) incompatible mod

### ISSUE THREAD

**Issue by kurshy1** [MeteorDevelopment/meteor-client#1788]
### Describe the bug

![screenshot](https://user-images.githubusercontent.com/82122071/145727918-78fa4163-c92f-49e8-91e1-ff00f8df1638.png)
[crash-2021-12-12_15.12.54-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7699617/crash-2021-12-12_15.12.54-client.txt)

The issue is meteor client is incompatible with another fabric mod called better [better mount hud](https://www.curseforge.com/minecraft/mc-mods/better-mount-hud)

crash report and screenshot are included

### Steps to reproduce

```bash
I have mod menu, fabric api, meteor client and better mount hud in the mods folder. I open minecraft up, then it doesn't open and instead crashes consistently giving me the same crash report every time.
```

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
this is because meteor already includes this feature

**Comment by RedCarlos26** [comment]
@kurshy1 close the issue
