### ISSUE TITLE
[Bug] [Crash] keybinds trolling me 

### ISSUE THREAD

**Issue by snnwer** [MeteorDevelopment/meteor-client#1791]
### Describe the bug

basically a keymanager problem i
[crash-2021-12-14_00.00.23-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7706218/crash-2021-12-14_00.00.23-client.txt)]
crash log ^

### Steps to reproduce

```bash
idk i just pressed some buttons
```

### Meteor Version

0.4.7-1365

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Cannot reproduce.
