### ISSUE TITLE
[Suggestion] AutoEXP Improvements

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1792]
### Describe the feature

- Only activate at a set health
- Only in hole
- Wait to activate if you're holding a gapple or eating
- Automatically turn on AutoMend
- Pause on eat, drink, and mine

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by seasnail8169** [comment]
no, ok, no, no, ok

**Comment by RickyTheRacc** [comment]
cool

**Comment by RickyTheRacc** [comment]
I should clarify I meant won't activate if below a set health by the way, not just at one set health amount lol
