### ISSUE TITLE
AutoClicker given a range[Suggestion] 

### ISSUE THREAD

**Issue by Spinyfish** [MeteorDevelopment/meteor-client#1793]
### Describe the feature

To prevent consistency checks giving the autoclicker a range slider to look more legit. Maybe a 2 way slider so you could have an option to run it at 7-9 cps or 11-15 cps or something.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
This could only ever be useful on legit pvp servers where rules specifically ban auto clickers so no
