### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by VoteJasper** [MeteorDevelopment/meteor-client#1794]
### Describe the bug

When i try to load up the client, it crashes.

### Steps to reproduce

```bash
Nothing. I haven't yet used the client.
```

### Meteor Version

0.46

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Update to latest dev build. 0.4.6 is for 1.17.1.
