### ISSUE TITLE
Auto Tool should have "Fortune for Ores" option[Suggestion] 

### ISSUE THREAD

**Issue by AryonLegacy** [MeteorDevelopment/meteor-client#1796]
### Describe the feature

Sometimes you want to mine some stone with Silktouch but the ores with Fortune. So it would be nice if it could auto switch for u.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Based suggestion
