### ISSUE TITLE
[Bug] Latest dev build crashes on startup

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1797]
### Describe the bug

See title

### Steps to reproduce

```bash
https://paste.ee/p/Z2cZD
```

### Meteor Version

1369

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Update.
