### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by tankyap** [MeteorDevelopment/meteor-client#1798]
### Describe the bug

It crashes when started the game with Minecraft 1.17.1 version

Heres the [crash report file](https://github.com/MeteorDevelopment/meteor-client/files/7718600/crash-2021-12-15_18.28.31-client.txt) and [latest.log](https://github.com/MeteorDevelopment/meteor-client/files/7718609/latest.log) file if you wanted.

### Steps to reproduce

```bash
1. Open Minecraft Launcher.
2. Start the game with Fabric loader.
3. Profit(Crashes).
```

### Meteor Version

0.4.6

### Minecraft Version

Minecraft 1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Looks like an incompatibility with Reach Entity Attributes, or that mod is just broken.

**Comment by tankyap** [comment]
but I didn't have that mod in my mod file.How can I find it?

**Comment by MineGame159** [comment]
Oh, then it must be a library that some other mod includes.

**Comment by MineGame159** [comment]
It may be Doom.

**Comment by tankyap** [comment]
Ok, I'll deal with it.
