### ISSUE TITLE
Everytime i open the game in dev build 1369 the game crashes.

### ISSUE THREAD

**Issue by Tupli5** [MeteorDevelopment/meteor-client#1799]
### Describe the bug

I have restarted everything and it doesnt work, here is the crash report.
https://paste.ee/p/hxK9S

btw the closest report of this bug was https://github.com/MeteorDevelopment/meteor-client/issues/1797

### Steps to reproduce

```bash
Every time i start the game with dev build 1369.
```

### Meteor Version

dev build 1369

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Download previous dev build, there is a bug in the latest one.

**Comment by Tupli5** [comment]
how?

**Comment by Tupli5** [comment]
> Download previous dev build, there is a bug in the latest one.

how?

**Comment by MineGame159** [comment]
There are links in our discord.
