### ISSUE TITLE
[Bug] ESP bug

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1802]
### Describe the bug

The fade distance setting in ESP on shader mode appears to be broken as it does not disappear as you get closer to the mobs.

### Steps to reproduce

```bash
Enable ESP and select any common mob (player, cows, sheep, etc.) and set the fade distance to 10 blocks. Approach the entity behind a wall and notice that even at only 3 or 4 blocks away there is no noticeable decrease in opacity of the ESP. 

Unsure if using the latest sodium could make a distance but that should be the only mod I'm using which affects rendering.
```

### Meteor Version

1368

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
only breaks with shader esp, not any of the other settings

**Comment by seasnail8169** [comment]
#1139
