### ISSUE TITLE
[Bug] v0.4.7 build #1371 crash report

### ISSUE THREAD

**Issue by Decme** [MeteorDevelopment/meteor-client#1806]
### Describe the bug

Game crashes with Meteor client:
https://paste.gg/p/anonymous/087d730402eb4133aae8b3fd84c8c4c6

Game does not crash without Meteor client.

### Steps to reproduce

```bash
see description
```

### Meteor Version

v0.4.7 build #1371

### Minecraft Version

1.18.1 Fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
1. Wi Zoom and Meteor are not compatible
2. Use older dev build, latest has a bug

**Comment by Decme** [comment]
I have since tested the build prior to that one without Wi Zoom, and it still crashes.

**Comment by arlomcwalter** [comment]
use the latest build now that bug was fixed
