### ISSUE TITLE
Visual Occlusion at Chunk Border [Bug] 

### ISSUE THREAD

**Issue by Pilot1782** [MeteorDevelopment/meteor-client#1815]
### Describe the bug

When panning around the camera, a visual occlusion bug occurs where vision is blocked at the chunk border:

![unknown_2021 12 18-15 37](https://user-images.githubusercontent.com/71522520/146657305-31515654-5b4b-40b0-8386-bc1a9656e764.png)

### Steps to reproduce

```bash
Open a single player and pan the camera.
```

### Meteor Version

0.4.7 1368

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Meteor does nothing that would break chunk rendering.
