### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Daeviin** [MeteorDevelopment/meteor-client#1816]
### Describe the bug

When i start minecraft with meteor client it crashes i tried with different versions too and it still crashes. Please send help

### Steps to reproduce

```bash
start minecraft
```

### Meteor Version

4.6

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Use dev build #1368 from our discord.

**Comment by Daeviin** [comment]
> Use dev build #1368 from our discord.

How?

**Comment by MineGame159** [comment]
A crash was fixed with latest dev builds so you can just use the latest one.
