### ISSUE TITLE
Meteor crash on startup

### ISSUE THREAD

**Issue by Daeviin** [MeteorDevelopment/meteor-client#1820]
### Describe the bug

When i want to start meteor on 1.18 fabric loader version 12.12 on meteor 4.6 but when i try the dev version it works well
please help me discord : Daeviin#7153

### Steps to reproduce

```bash
Just start meteor on minecraft
```

### Meteor Version

4.6

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
0.4.6 is for 1.17.1 and 0.4.7 dev build is for 1.18.x

**Comment by Daeviin** [comment]
Ohh ok tq minegame
