### ISSUE TITLE
[Bug] Baritone module cannot render azalea bushes correctly

### ISSUE THREAD

**Issue by TheRedDraqon** [MeteorDevelopment/meteor-client#1822]
### Describe the bug

Baritone module cannot render azalea bushes correctly (1.18)

![image](https://user-images.githubusercontent.com/87587178/146837284-c0e71a77-f46c-4ee3-b2ae-33dbdfe04aa6.png)

### Steps to reproduce

```bash
1. set a goal for baritone (eg. mining, goto)
2. Have baritone try to jump 1 moss block with azalea bush on top
3. baritone will attempt to jump over bush like chest hitbox (you can or could in 1.7, jump on blocks chest is sitting on and then jump on chest)
```

### Meteor Version

0.4.7 1362

### Minecraft Version

1.18

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
We are not Baritone developers.
