### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by CloudzRCool** [MeteorDevelopment/meteor-client#1823]
### Describe the feature

Update tp 1.18.1 please the java hack thing

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
when the real real funy java me when the the real java hack 1.18
