### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by F12Studios** [MeteorDevelopment/meteor-client#1824]
### Describe the bug

When i launch my minecraft it crashes 

### Steps to reproduce

```bash
When i launch my minecraft it crashes and im just tryna play on my server
```

### Meteor Version

1.18.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by StormyBytes** [comment]
1. "1.18.1" is not a meteor version. What we meant were like "0.4.6", "dev build 1372".
2. If its a crash provide the crash report/log

**Comment by Talpae** [comment]
Are you taking the piss mate

Send us your logs

**Comment by RedCarlos26** [comment]
@F12Studios send the crash report
