### ISSUE TITLE
[Question] How to stop the zoom module from announcing it's been enabled & disabled

### ISSUE THREAD

**Issue by Decme** [MeteorDevelopment/meteor-client#1825]
### Describe the feature

If this isn't possible, could this be considered a feature request? I zoom in/out a lot and it's very spammy.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
gui > config tab > chat feedback

**Comment by RedCarlos26** [comment]
@arlomcwalter I think he wanted to say an option to only disable the chat feedback for certain modules like zoom, since it becomes very spammy. The thing is having chat feedback on is useful, but the zoom module can make it spammy

**Comment by Decme** [comment]
I see this has been closed. Has this been implemented?

**Comment by RedCarlos26** [comment]
No

**Comment by bluepanee** [comment]
> I see this has been closed. Has this been implemented?

I added this feature to my pull request. It will be implemented if everything is ok.

**Comment by RedCarlos26** [comment]
Based thanks a lot
