### ISSUE TITLE
[Bug] Potion Hud

### ISSUE THREAD

**Issue by necrophili** [MeteorDevelopment/meteor-client#1826]
### Describe the bug

When giving yourself a potion effect with very high amplifier (lets j say 255 for this context) the Potion Hud will show the potion amplifier as 0.

### Steps to reproduce

```bash
Hop on single player. /effect give xxx yyy time 255
kaboom
```

### Meteor Version

1373

### Minecraft Version

1.18.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
That is because the maximum amplifier Minecraft allows is 127, this has nothing to do with Meteor.
