### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AmFloofyBoi** [MeteorDevelopment/meteor-client#1827]
### Describe the bug

when i try and use the infinity miner, it says "There is no available pickaxe in your inventory.  

### Steps to reproduce

```bash
I just turn on infinity miner and it says it.
```

### Meteor Version

meteor-client-0.4.7-1346

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
It needs mending

**Comment by AmFloofyBoi** [comment]
> 

oh
