### ISSUE TITLE
[Bug] Cope then

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1828]
### Describe the bug

https://crashy.net/tjNNgK0Y7HN3zQI2V8Aq

Crash as soon as you join a world lul

### Steps to reproduce

```bash
Use the latest meteor dev build and join a server
```

### Meteor Version

1373

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Addon
