### ISSUE TITLE
[Bug] The Announcer feature for placing blocks is doubled

### ISSUE THREAD

**Issue by Dragon77mathbye** [MeteorDevelopment/meteor-client#1829]
### Describe the bug

Whenever I place a block with announcer on, it doubles the value of how many blocks I placed.

### Steps to reproduce

```bash
1. Turn on Announcer and make sure placing is active
2. Place any block
3. Wait
4. In chat, it will announce: "I just placed 2 {block}!" if you have it default, though it should say "I just placed 1 {block}!"
```

### Meteor Version

Dev Build 0.4.7 - 1373

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 3da16fd7bcba65e202a2fb6dcdf35549fd26fd12.
