### ISSUE TITLE
[Bug] No Interact Whitelist mode not working

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#1830]
### Describe the bug

No Interact Whitelist mode not working

### Steps to reproduce

```bash
turn on 'No Interact'
select whitelist mode
pick a block in 'Block Mine'
try mining it; it can be mined
```

### Meteor Version

latest dev build

### Minecraft Version

1.18

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by N08I40K** [comment]
I don't know about you, everything works for me.

**Comment by N08I40K** [comment]
![image](https://user-images.githubusercontent.com/55545594/147521362-b4edb430-05eb-43ef-8446-ef7f9bb438ce.png)
![image](https://user-images.githubusercontent.com/55545594/147521383-bcb846af-c725-4216-857d-bdddeeb61706.png)
![image](https://user-images.githubusercontent.com/55545594/147521409-742744b0-5f9e-4c52-8a96-ed82c0e38363.png)
