### ISSUE TITLE
[Bug] Highway builder crash (again)

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#1832]
### Describe the bug

Highway builder crashes at random (it says container click)

### Steps to reproduce

```bash
Turn on highway builder and wait for it to crash (it can sometimes take 30+ minutes, its very random)
```

### Meteor Version

0.4.7-1373

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
send the log, obviously. how long do you need to nolife meteor issues to know that we cant fix 99% of crashes without a log

**Comment by RedCarlos26** [comment]
Lol I thought I sent it. Sending it asap

**Comment by MineGame159** [comment]
Still no crash report.

**Comment by RedCarlos26** [comment]
Yes I can't find the crash report I'm tying to see the crash again so I can send the report. Hopefully I have it for tomorrow

**Comment by RedCarlos26** [comment]
Wasnt able to reproduce. Will reopen if I finally get a crash report someday.
