### ISSUE TITLE
[Bug] When Criticals Module is on, Crit Jumping Normally Does Not Result in a Crit

### ISSUE THREAD

**Issue by Lexlogan312** [MeteorDevelopment/meteor-client#1833]
### Describe the bug

When I turned on the Criticals Module, the crit only occurs when standing on the ground and does not work if you were trying to jump and crit normally. I tried changing it from packet to bypass and it works about 5% of the time, but other than that, it doesn't work any better. Not sure if this is a bug or just something that just comes as a result of having a crit module, but if it is the former, I would love to see it fixed so I can always get crits even when I have a tendency to jump.

### Steps to reproduce

```bash
1. Turn on Criticals Module
2. Try criting something by jumping and hitting it
3. Try a different option (Packet and Bypass)
4. See it doesn't crit out the opponent
```

### Meteor Version

Dev Build 0.4.7 build #1373

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
no shit, the whole point of the module is so you dont have to jump yourself
