### ISSUE TITLE
[Bug] it crashes on startup both releases even after redownload

### ISSUE THREAD

**Issue by BiggestDikkus** [MeteorDevelopment/meteor-client#1834]
### Describe the bug

 it doesn't work when I load it I've been able to use it a lot of times but now it just doesn't work
exit code (for the dev build)
**The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "$$1" is null
Exit Code: -1**
exit code (release 

### Steps to reproduce

```bash
i hit the play button and mc opens and crashes when the mc tap pops up
```

### Meteor Version

newest

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send the crash report

**Comment by KuuEldin** [comment]
But that's the thing, if this is the same issue I have, with it crashing constantly using the Dev Build, there IS NO crash report in the files. I've checked.

![Screenshot (39)](https://user-images.githubusercontent.com/95960027/147464609-cbf0300d-0b71-45d5-b780-b6228bc43577.png)

And this is the latest (and only) crash report in the files I have in my files. Nothing in any of the bins, nothing deleted or removed. The only other client I have is WURST, and even then, wurst still functions perfectly, whilst even after removing WURST from the mod files, Meteor still crashes.
[crash-2021-12-10_22.52.15-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/7779916/crash-2021-12-10_22.52.15-client.txt)
![Screenshot (40)](https://user-images.githubusercontent.com/95960027/147467001-ffe1a02f-151b-41a4-980e-e8b3d70bb5ec.png)

Even using the correct build and version (both Minecraft and Meteor Client), there's still no crash report presented, nor added to the files.

Apologies if this is intruding at all, but I hope this assists in fixing the current issue.
