### ISSUE TITLE
[Suggestion] Auto-MLG

### ISSUE THREAD

**Issue by TheAlphaReturns** [MeteorDevelopment/meteor-client#1837]
### Describe the feature

Basically, if the module it's on and there is a water bucket in your hotbar, it does an MLG for you. If nether, same for vines.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Declipsonator** [comment]
Auto mlg is an option inside of nofall. Using vines however, is not

**Comment by Declipsonator** [comment]
Also I believe ladders would have the same effect

**Comment by TheAlphaReturns** [comment]
alr thanks
