### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Unbr3ackble** [MeteorDevelopment/meteor-client#1839]
### Describe the feature

please add optfine if you can to meteor client to increase the performance to many players that dont have a very good pc and dont get that much fps (like me).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Declipsonator** [comment]
Optifine originated as a forge mod and therefore is very incompatible with a large portion of fabric mods. However there are other preformance improving mods for fabric such as sodium, phosphor and lithium.

**Comment by SIMULATAN** [comment]
As Declipsonator already said, optifine isn't a good option.
If you want your potato PC to not die when playing minecraft, use sodium, phosphor and lithium (imo not a "suggestion" to do that, its more of a must have tbh)

**Comment by RickyTheRacc** [comment]
You should kill yourself... now!!

**Comment by Makayu43135** [comment]
use FabricOptifine bruh

**Comment by SIMULATAN** [comment]
> use FabricOptifine bruh

1) it's called OptiFabric
2) it's not supported by Meteor
3) optifine is trash anyway
4) sodium is the way to go

**Comment by sarnthilIsHorny** [comment]
> use FabricOptifine bruh

:brainlet:
