### ISSUE TITLE
[Suggestion] Starscript improvements 

### ISSUE THREAD

**Issue by N08I40K** [MeteorDevelopment/meteor-client#1843]
### Describe the feature

Add a variable responsible for:
- The number of all modules.
- Number of enabled modules
- Integration with baritone (enabled or not)
- [I do not know if this is possible or not] Access to variables and functions of modules ( modules.killaura.isActive() ) 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Added in 3a660033a032ee1d374e0ede79cf2b3b4409b1fe.
