### ISSUE TITLE
[Suggestion] Rename F3 info with VanillaSpoof module

### ISSUE THREAD

**Issue by erxson** [MeteorDevelopment/meteor-client#1844]
### Describe the feature

For example:
Minecraft 1.18.1 (MultiMC5/fabric/Fabric) -> Minecraft 1.18.1 (MultiMC5/vanilla)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by sarnthilIsHorny** [comment]
good one

**Comment by RedCarlos26** [comment]
Based suggestion
