### ISSUE TITLE
add range display

### ISSUE THREAD

**Issue by shittass** [MeteorDevelopment/meteor-client#1845]
### Describe the feature

a circle surrounds player,the radius of the circle is set by myself(show others' attack distance)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Suggestion by shittass
