### ISSUE TITLE
[Microbug] Dragging the Mouse out of bounds of a text field doesn't change the position

### ISSUE THREAD

**Issue by SIMULATAN** [MeteorDevelopment/meteor-client#1847]
### Describe the bug

A bit weird to describe in words so have a GIF:

![explanation gif](https://user-images.githubusercontent.com/63104422/147590076-40d6203b-a8c1-4860-ac6e-3f19b4debdfb.gif)

As you can see, even though the text continues on the left, the view stays where it is but when deleted it deletes the correct text

### Steps to reproduce

```bash
Open up a module with a text setting (for example the module `Discord Presence` like in my GIF), press the arrow keys to shift the text far enough to not see everything, drag the mouse in the direction of the hidden text.
```

### Meteor Version

0.4.7-1373

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
Can confirm
