### ISSUE TITLE
[Suggestion] Chat Reaction Bot

### ISSUE THREAD

**Issue by wrobz16** [MeteorDevelopment/meteor-client#1848]
### Describe the feature

Many servers have a chat feature that is "hover for the word to type" where you hover over the chat message with your mouse and you type the given word. First one to type it wins a prize. The bot would do this automatically within a set time. Some time variation would be nice so it doesnt look suspicious. Also, if possible, an unscrabmler. Same concept, but the word is unscrambled and the player has to unscramble it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
No, stop using meteor on servers that do not explicitly allow it
