### ISSUE TITLE
track players

### ISSUE THREAD

**Issue by PierceWoods** [MeteorDevelopment/meteor-client#1851]
### Describe the feature

A feature that tracks a player. Maybe make a waypoint of where a specific  player is. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
doable

**Comment by arlomcwalter** [comment]
> doable

make it 🙏🙏🙏
