### ISSUE TITLE
[Bug] https://crashy.net/0nD4YATMRwnwCBPgrf8K

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1855]
### Describe the bug

After crashing with Not Enough Crashes, Meteor afterwards will crash every time it has to render something until the game is relaunched

### Steps to reproduce

```bash
Crash with Meteor being the main cause, and then attempt to open the clickgui on the title screen or join a server - either will cause a crash from Meteor.

https://crashy.net/0nD4YATMRwnwCBPgrf8K
```

### Meteor Version

1373

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
It shouldn't crash in the first place, we need to fix that.

**Comment by arlomcwalter** [comment]
> It shouldn't crash in the first place, we need to fix that.

yeah but this isn't the original crash, this crash is just because notenoughcrashes being a stupid idea
