### ISSUE TITLE
[Suggestion] Just make this client give me op

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [MeteorDevelopment/meteor-client#1857]
### Describe the feature

Soo, i am requesting some modules that can be helpful while playing on hypixel
MODULES AND OTHER STUFF I WANT:
- op giver
- module that nukes whole chunk loaded by player client
- autoban mod that bans everyone that enters my render distance
- oh, maybe also mod that makes me have access to servers control panel, you know prints me login and password to login to  bithosting.
i personally think these four modules you will implement in 30 minutes so theres some more
- module that makes you change game i am playing so i can bind it to DEL and toggle gta and minecraft games while waiting for bedwars game in hypixel lobby
- Maybe add also a mod that gets players bank account name from other players and gives it to me. And since i am too lazy to actually do anything in my life, make it automatically transfer all the money to my paypal account. Thanks!

Hope, youre not overworked! Thanks and good luck man!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by BlueTree242** [comment]
Is this a joke? Wtf

**Comment by PiotrekUnityDeveloper** [comment]
yes, that would also be helpful

**Comment by HoseanRC** [comment]
sweet dreams :)
