### ISSUE TITLE
auto farm

### ISSUE THREAD

**Issue by mrturtlek** [MeteorDevelopment/meteor-client#1858]
### Describe the feature

breaks crop when it is fully grown and replants

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Baritone has farm command.
