### ISSUE TITLE
auto wither

### ISSUE THREAD

**Issue by mrturtlek** [MeteorDevelopment/meteor-client#1859]
### Describe the feature

makes withers automatically 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Duplicate of #516.

**Comment by mrturtlek** [comment]
> Duplicate of #516.

oh sorry
