### ISSUE TITLE
[Bug] Meteor on Crack

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1862]
### Describe the bug

I personally find this phrase very offensive, my mom died after I stepped on a crack and this phrase is very insensitive to victims of actual crack murder.

### Steps to reproduce

```bash
Load Meteor for the first time and notice several default configs for text-based modules have the phrase "Meteor on Crack!" in them.
```

### Meteor Version

1377

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Insensitive

**Comment by anzy2026** [comment]
Easter egg？
