### ISSUE TITLE
[Bug] unsuccessful login freezes game

### ISSUE THREAD

**Issue by Radial2250** [MeteorDevelopment/meteor-client#1865]
### Describe the bug

when trying to add an alt, and being unnsucessful (not actually adding an account) there is no way to get out of the account add screen, apart from closing and reopening mc

### Steps to reproduce

```bash
try and add an alt from the multiplayer menu, dont actually add one, then try and get back to the menu.
```

### Meteor Version

meteor client v0.4.7 build #1377

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by maxsupermanhd** [comment]
Bump
