### ISSUE TITLE
Fox ESP

### ISSUE THREAD

**Issue by GrubbyKnight698** [MeteorDevelopment/meteor-client#1866]
### Describe the feature

Option 1: Highlight foxes with an item in their mouth
Option 2: Range (Distance)
Option 3: Show item name
Option 4: Keybind

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by GrubbyKnight698** [comment]
Could be used to find emeralds?

**Comment by Makrennel** [comment]
sounds useless
