### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Eivind22** [MeteorDevelopment/meteor-client#1874]
### Describe the feature

"new chunk" mark old/New chunks. Use full for base hunting

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SIMULATAN** [comment]
It's in [meteor-rejects](https://github.com/anticope/meteor-rejects)
