### ISSUE TITLE
[Suggestion] Add Optifine Cosmetic see

### ISSUE THREAD

**Issue by AbelGamz** [MeteorDevelopment/meteor-client#1879]
### Describe the feature

Basically we can see the cosmetics/capes of people using optifine you can make a different meteor 1 with no optifine and 1 with optifine please uwu
#

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SIMULATAN** [comment]
No, just no

**Comment by link-discord** [comment]
just use the minecraft-capes mod if you want to see capes and stuff

**Comment by arlomcwalter** [comment]
or just get a meteor cape
