### ISSUE TITLE
[Suggestion] Please add Japanese font

### ISSUE THREAD

**Issue by nosashuumai** [MeteorDevelopment/meteor-client#1880]
### Describe the feature

Please add Japanese font

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
#333
