### ISSUE TITLE
[Suggestion] Auto EXP Range Option

### ISSUE THREAD

**Issue by link-discord** [MeteorDevelopment/meteor-client#1881]
### Describe the feature

A slider option that prevents auto exp from being active when players are in certain range of u (for example 3 blocks) It doesn't toggle off the module it just makes the module do nothing as long as a player is in range of you

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by sarnthilIsHorny** [comment]
auto-mend.
