### ISSUE TITLE
[Suggestion] Add support for spaces/underscores and punctuation to profiles

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1882]
### Describe the feature

The title says it all

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
why

**Comment by RickyTheRacc** [comment]
So I can write "Ricky's Server" instead of Rickyserver as a profile name

**Comment by arlomcwalter** [comment]
rickys-server

**Comment by arlomcwalter** [comment]
profiles are saved as files so they cant just have any name

**Comment by MineGame159** [comment]
Added in 279138b80d9974fefc923bf70833ca53aae113cb.
