### ISSUE TITLE
[Suggestion] Better Noslow

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1885]
### Describe the feature

Add an option to ignore vines in noslow

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
pretty sure thats not how it works. i think the slowdown comes from beginning to climb the vine which cant be avoided
