### ISSUE TITLE
[Suggestion] Saving Hotbar

### ISSUE THREAD

**Issue by BaraoVermelho** [MeteorDevelopment/meteor-client#1887]
### Describe the feature

Imagine you going to spawn of a random anarchy server, grab your kit pvp from echest and lost a lot of time organizing your hotbar and inventory.

The suggestion would be an option that would save the hotbar and when taking certain items and activating the function, it would organize the entire hotbar in the predefined sequence once and disable it automatically.

If you can extend to the entire inventory that would be great too.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
#1639
