### ISSUE TITLE
Seed Extractor [Suggestion] 

### ISSUE THREAD

**Issue by CursedHand** [MeteorDevelopment/meteor-client#1890]
### Describe the feature

Gets the seed of a server using slime chunk locations. This would be helpful for finding structures like strongholds/ocean monuments along with biomes.

Kind of like these but automated:
https://github.com/Badel2/slime_seed_finder
https://github.com/pruby/slime-seed

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by HoseanRC** [comment]
it's HARD AS HELL
you need to generate every single seed and check the exact location you are on
also you might be on a chunk that is loaded at older version of minecraft so you need to check it 7 times
billion of seeds × 7 = TOOOO MUCH TIME

**Comment by arlomcwalter** [comment]
> it's HARD AS HELL
> 
> you need to generate every single seed and check the exact location you are on
> 
> also you might be on a chunk that is loaded at older version of minecraft so you need to check it 7 times
> 
> billion of seeds × 7 = TOOOO MUCH TIME

no, it's just in lots of other mods so doesn't need to be in meteor

**Comment by CursedHand** [comment]
> > it's HARD AS HELL
> > you need to generate every single seed and check the exact location you are on
> > also you might be on a chunk that is loaded at older version of minecraft so you need to check it 7 times
> > billion of seeds × 7 = TOOOO MUCH TIME
> 
> no, it's just in lots of other mods so doesn't need to be in meteor

Can you link some of these mods because I have not been able to find any.
