### ISSUE TITLE
[Suggestion] Remove Aim Assist

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1891]
### Describe the feature

There's no reason anyone would need this in any server where Meteor is allowed, it practically just encourages people to try and use the client where it shouldn't be used

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Selbstverliebter** [comment]
dont u understand what a hack client is for?

**Comment by Vitalasy** [comment]
ratio

**Comment by qeqeqeplayer533** [comment]
aim assist is very useful on gun colony

**Comment by I-Got-You-Dead** [comment]
@qeqeqeplayer533 can u stop replying to really old issues 💀

**Comment by Soda5601** [comment]
it is removed ( ͡° ͜ʖ ͡°)

**Comment by loma-baldsson** [comment]
1 year anniversary of open issue

**Comment by Big-Iron-Cheems** [comment]
Completely forgot this legendary issue existed.
Truly the best thing to ever be done 🙏

**Comment by loma-baldsson** [comment]
rest in peace, we will miss you Richard "Lionheart" 1 of England
