### ISSUE TITLE
[Suggestion] Add "Auto GlowInkSac" option to "AutoSign" module

### ISSUE THREAD

**Issue by naBBolethano** [MeteorDevelopment/meteor-client#1893]
### Describe the feature

As described in the title, this option would automatically apply an ink sac when a sign is placed. Nothing impossible to do and kinda useful especially for people actually using meteor as an utility mod :)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
> ### Describe the feature
> 
> As described in the title, this option would automatically apply an ink sac when a sign is placed. Nothing impossible to do and kinda useful especially for people actually using meteor as an utility mod :)
> 
> ### Before submitting a suggestion
> 
> - [X] This feature doesn't already exist in the client.
> (I have checked every module and their settings on the **latest dev build**)
> 
> - [X] This wasn't already suggested.
> (I have checked every suggestion on github)
> 
> - [X] This feature is a valid suggestion.
> (I have read the FAQs and Guides)
> 

the most niche thing ever
