### ISSUE TITLE
[Suggestion] remove announcer

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1895]
### Describe the feature

Only autists use this

"Announcer -> Look, I have autism"
-minegame

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Fix my qoute monke

**Comment by arlomcwalter** [comment]
> Fix my qoute monke

qoute

**Comment by MineGame159** [comment]
Ok
