### ISSUE TITLE
[Suggestion] Playsound

### ISSUE THREAD

**Issue by AL3X45DJGamer** [MeteorDevelopment/meteor-client#1897]
### Describe the feature

The command will play a specific sound/music  when you execute it.
e.g. 
.playsound minecraft:music.menu master @s 
It will (if you can) make this work in all gamemodes.

I suggest this so it won't be too eerie in-game.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Useless
