### ISSUE TITLE
[Bug] Cannot use drums with notebot

### ISSUE THREAD

**Issue by nosashuumai** [MeteorDevelopment/meteor-client#1898]
### Describe the bug

If you use drums, they will all be harp sounds.

### Steps to reproduce

```bash
Just create an nbs file with the latest OpenNBS and play it.
```

### Meteor Version

0.4.7 1390

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Does your notebot have the block to place under the note blocks to give them a drum voice?

**Comment by nosashuumai** [comment]
yes

**Comment by nosashuumai** [comment]
My nbs
https://mega.nz/file/msM2WZbT#PKoTdXbivNLVhl7BfFQjYQ0q_Uo78RQayY8R9q0-Na0
