### ISSUE TITLE
[Bug] I don't even know

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1902]
### Describe the bug

https://crashy.net/hDt7YAPitjb00x7lGuRb

### Steps to reproduce

```bash
No idea, but I was just messin around in Mpvp and my game crashed out of nowhere. The log said something about guimove but I didn't even have it on so idk
```

### Meteor Version

1392

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Declipsonator** [comment]
This is probably an issue with meteor tweaks as it overwrites guimove

**Comment by Declipsonator** [comment]
The addon overwriting thing can have unintended effects sometimes (Like messing up references to settings or modules)

**Comment by Declipsonator** [comment]
For example if I overwrite autoreconnect in an addon, it makes this mixin crash meteor  https://github.com/MeteorDevelopment/meteor-client/tree/master/src/main/java/meteordevelopment/meteorclient/mixin/DisconnectedScreenMixin.java#L31
