### ISSUE TITLE
[Suggestion] Command Ideas

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1904]
### Describe the feature

Add the ability to modify values of module settings through the toggle command

> .toggle auto-armor ignore-elytra on

> .toggle crystal-aura break-delay 5

Add a .macro command to trigger macros instead of only having keybinds

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
It makes zero sense for a command named toggle to change settings.

**Comment by RickyTheRacc** [comment]
Then maybe a separate command, .update maybe? I'm not saying it has to be in that same setting but the ability to customize module settings should be a thing somehow

**Comment by arlomcwalter** [comment]
> Then maybe a separate command, .update maybe? I'm not saying it has to be in that same command but the ability to customize module settings should be a thing somehow

literally .settings

**Comment by RickyTheRacc** [comment]
Oh

**Comment by MineGame159** [comment]
Or .s as an alias
