### ISSUE TITLE
[Suggestion] Auto City Render

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1906]
### Describe the feature

Add rendering to Auto City so you can tell what block it's mining

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Justgamer101** [comment]
I believe this works with break indicators.
