### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Eivind22** [MeteorDevelopment/meteor-client#1909]
### Describe the feature

Module name: Auto dupe. 

Description: automaticly does the Shulker Dupe. 

What happens in the code? It brakes a shulker_box att the same time as it's takeing out the item. 

Nice if it could replace the Shulker_box agein after its picked up.

Pro tip: use with "Auto tool" to brake shulker faster. (I couldn't get it to work with "efficiency 5" only "efficiency 4" and lower on a diamond_pickaxe.)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by hellidox** [comment]
no
use the dedicated mod
