### ISSUE TITLE
[Suggestion] Dev Build Warning when game has been launched.

### ISSUE THREAD

**Issue by ItzVaio** [MeteorDevelopment/meteor-client#1911]
### Describe the feature

For the dev build, make a type of warning when launching the game and the loading screen has finished loading that it says "Warning: This is a Dev Build, (insert version) problems may occur, if occurred please report it to the github page."
There is two buttons, which is "I know what I'm doing." and the other being "Force Quit mod loader and quit vanilla."

The Button "I know what I'm doing." will clear out the screen and lets the person proceed.
"Force Quit" for short, will completely and safely quit the game without harming the game or system.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Not worth it in my opinion.
