### ISSUE TITLE
[Suggestion] Update Link to Optifine Alternatives

### ISSUE THREAD

**Issue by SIMULATAN** [MeteorDevelopment/meteor-client#1913]
### Describe the feature

In the wiki, the link to the OptiFine Alternatives info site still points to the Gist.
The site moved to [a own domain](https://lambdaurora.dev/optifine_alternatives) instead of [the old gist](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by ItzVaio** [comment]
my man optifine will never even be supported for meteor client

**Comment by arlomcwalter** [comment]
> my man optifine will never even be supported for meteor client

read what he actually wrote bruh
