### ISSUE TITLE
[Suggestion] Crystal Per Second Counter

### ISSUE THREAD

**Issue by MattyJJ** [MeteorDevelopment/meteor-client#1921]
### Describe the feature

Just A Simple Addon To The Gui Displaying The Crystals You Place And Break Per Second For Crystal pvp

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SWP360** [comment]
is it really that hard to count it manually??
