### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Sk-Reaper** [MeteorDevelopment/meteor-client#1922]
### Describe the feature

Auto mlg pls an riptide and loyalty
 trident switch

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by sarnthilIsHorny** [comment]
no fall has a water bucket mode.
