### ISSUE TITLE
Scrolling down or toggling some modules made HUD text glitched[Bug] 

### ISSUE THREAD

**Issue by AL3X45DJGamer** [MeteorDevelopment/meteor-client#1926]
### Describe the bug

Some modules at the Active modules in HUD glitched and made other HUD modules glitched too.
It also applies to scrolling in different categories.
![image](https://user-images.githubusercontent.com/97241724/149056182-dc179665-3411-43d9-8e79-8c34ad0f19d6.png)

### Steps to reproduce

```bash
When I scroll through No Render to disable death particles, the text disappear when I scroll down but when I scroll up it reappears.

This also applies to when searching in the search bar.
The modules I toggled suppose to show at Active Modules but it glitched instead and made other HUD modules text out of the box.
```

### Meteor Version

Meteor Client Dev-build 0.4.7 - 1390

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by AL3X45DJGamer** [comment]
![image](https://user-images.githubusercontent.com/97241724/149172413-cba4c3ab-0b8f-4c54-8f40-b56d2bba2446.png)
I just opened Accounts and this happened.

**Comment by AL3X45DJGamer** [comment]
![image](https://user-images.githubusercontent.com/97241724/149172617-2e60fe6f-9783-402d-9bfc-4e2230d5f058.png)
Then this too.

**Comment by AL3X45DJGamer** [comment]
![image](https://user-images.githubusercontent.com/97241724/149172779-0fb7465e-f5f9-421f-90e6-a4ec9a970abf.png)
This happens when I join.

**Comment by arlomcwalter** [comment]
lmao is that windows 7?

**Comment by sarnthilIsHorny** [comment]
> lmao is that windows 7?

probs or he may be using a windows modifcation app called "start is back".

**Comment by arlomcwalter** [comment]
@AL3X45DJGamer can you show your mods folder

**Comment by AL3X45DJGamer** [comment]
> @AL3X45DJGamer can you show your mods folder

sure
