### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Sk-Reaper** [MeteorDevelopment/meteor-client#1928]
### Describe the bug

my game crashes when i activate hud

### Steps to reproduce

```bash
turn on some hud stuff and activate the hud
```

### Meteor Version

meteor client v0.4.7 build 

### Minecraft Version

minecraft 1.18.1 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by SIMULATAN** [comment]
Please add the exact dev build number and the full crash log

**Comment by Sk-Reaper** [comment]
meteor client v0.4.7 build #1398

**Comment by Sk-Reaper** [comment]
it didn't give me a crash log sorry for not helping

**Comment by MineGame159** [comment]
Then we can't help you or do anything about it if you don't provide a crash report. If you decide to send it then reopen the issue.

**Comment by SIMULATAN** [comment]
> it didn't give me a crash log sorry for not helping

skill issue
open up .minecraft/logs and send everything from the first stack trace on

**Comment by arlomcwalter** [comment]
odds is an addon issue?

**Comment by Sk-Reaper** [comment]
[2022-01-12-5.log.gz](https://github.com/MeteorDevelopment/meteor-client/files/7859138/2022-01-12-5.log.gz)
