### ISSUE TITLE
[Bug] Baritone not working

### ISSUE THREAD

**Issue by NotMtth** [MeteorDevelopment/meteor-client#1935]
### Describe the bug

Baritone doesn't work with any command because in version 0.4.6 is in `"dev environment"`.
If you want to double check just type `#version` with the client loaded.
Hope you can find a fix!

### Meteor Version

0.4.6

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotMtth** [comment]
https://linx.do/ffsqgpp0.png | SC of the Error

**Comment by Justgamer101** [comment]
This seems to be an issue with baritone rather than meteor.
