### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Selbstverliebter** [MeteorDevelopment/meteor-client#1937]
### Describe the feature

It is simple but helpful basically a feature like jesus but for powder snow

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by ItzVaio** [comment]
it's already a thing
