### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Selbstverliebter** [MeteorDevelopment/meteor-client#1938]
### Describe the bug

Baritone messes up while walking on powderd snow. 
It starts aiming around trying to get out and u will have to .b stop and get out of the hole by urself

### Steps to reproduce

```bash
walk on powderd with baritone(.b goto ~ ~ ~)
```

### Meteor Version

meteor-client-0.4.7-1398 (dev)

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ItzVaio** [comment]
That's because you don't have leather boots.

**Comment by arlomcwalter** [comment]
its also an issue with baritone not meteor
