### ISSUE TITLE
[Bug] Not really a bug.

### ISSUE THREAD

**Issue by ItzVaio** [MeteorDevelopment/meteor-client#1939]
### Describe the bug

This isn't really a bug, but there isn't any question  thing so i have to report it as bug: Does anybody know how to fix the Announcer "i walked <blocks walked>" I put it to zero, and it keeps on spamming it any fixes? Else I have to change to Wurst Client until I get support.

### Steps to reproduce

```bash
Goto Announcer, Set whatever like speed to zero, and minecraft will flag you for spam.
```

### Meteor Version

DEV Build 1398

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
??? Of course when you set the settings for moving in Announcer to 0 it will spam. They control how often the message is sent and what is the minimum distance.

**Comment by ItzVaio** [comment]
How am i suppose to fix it?

**Comment by ItzVaio** [comment]
> ??? Of course when you set the settings for moving in Announcer to 0 it will spam. They control how often the message is sent and what is the minimum distance.

How am i suppose to fix it?

**Comment by SIMULATAN** [comment]
> > ??? Of course when you set the settings for moving in Announcer to 0 it will spam. They control how often the message is sent and what is the minimum distance.
> 
> How am i suppose to fix it?

Literally put the delay to something higher

How can you be so stupid bruh

**Comment by ItzVaio** [comment]
> > > ??? Of course when you set the settings for moving in Announcer to 0 it will spam. They control how often the message is sent and what is the minimum distance.
> > 
> > 
> > How am i suppose to fix it?
> 
> Literally put the delay to something higher
> 
> How can you be so stupid bruh

HOW? MY GAME WILL LITERARY DISCONNECT ME RIGHT BEFORE I EVEN LOAD CHUNKS

**Comment by MineGame159** [comment]
You can open the GUI in main menu the same way you would in-game.

**Comment by ItzVaio** [comment]
ok yes i am stupid back i go to upgrading my dev build
