### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by meme-boi374** [MeteorDevelopment/meteor-client#1944]
### Describe the feature

add cps counter for left and right: [<cpsleft>|<cpsright>]
custom crosshair in render that you can draw
combo counter

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by sarnthilIsHorny** [comment]
use lunar.

**Comment by meme-boi374** [comment]
> use lunar.

how do i add lunar to meteor?
