### ISSUE TITLE
[Suggestion] pls add parkour hack

### ISSUE THREAD

**Issue by Razornminty** [MeteorDevelopment/meteor-client#1945]
### Describe the feature

like a module like baritone but for parkour

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SWP360** [comment]
Already in the client

**Comment by sarnthilIsHorny** [comment]
already present.
