### ISSUE TITLE
[Bug] Baritone schematica building

### ISSUE THREAD

**Issue by HealingArcYT** [MeteorDevelopment/meteor-client#1946]
### Describe the bug

22:02:11.895
Stopping worker threads
22:02:12.237
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 14.01.22, 22:02
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "<parameter1>" is null
	at baritone.process.BuilderProcess.a(Unknown Source)
	at baritone.process.BuilderProcess.onTick(Unknown Source)
	at baritone.utils.PathingControlManager.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)
	at net.minecraft.class_310.method_1574(class_310.java:1720)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at baritone.process.BuilderProcess.a(Unknown Source)
	at baritone.process.BuilderProcess.onTick(Unknown Source)
	at baritone.utils.PathingControlManager.a(Unknown Source)
	at baritone.behavior.PathingBehavior.onTick(Unknown Source)
	at baritone.event.GameEventHandler.a(Unknown Source)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at baritone.event.GameEventHandler.onTick(Unknown Source)
	at net.minecraft.class_310.handler$zzh000$runTick(class_310.java)

-- Affected level --
Details:
	All players: 1 total; [class_746['MNKYD'/171, l='ClientLevel', x=-175.28, y=68.00, z=49.23]]
	Chunk stats: 4096, 741
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,0), Section: (at 0,8,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 54862 game time, 54862 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2156848968 bytes (2056 MiB) / 4596957184 bytes (4384 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4,64
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072,00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9729
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 3,00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27992,38
	Virtual memory used (MB): 21540,59
	Swap memory total (MB): 11684,64
	Swap memory used (MB): 1135,80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.18-SNAPSHOT
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.6
		iris: Iris 1.1.3
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.9.0
		malilib: MaLiLib 0.10.0-dev.26
		meteor-client: Meteor Client 0.4.7-1361
		minecraft: Minecraft 1.18
		multiconnect: MultiConnect 1.5.2
		multiconnect-api: MultiConnect API 1.5.2
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		sodium: Sodium 0.4.0-alpha5+build.9
		worldedit: WorldEdit 7.2.8+6008-1246d61
	Launched Version: fabric-loader-0.12.6-1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.29, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 6x AMD Ryzen 5 3500X 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['MNKYD'/171, l='ServerLevel[New World]', x=-175.28, y=68.00, z=49.23]]
	Data Packs: vanilla, Fabric Mods

-- Meteor Client --
Version: 0.4.7
Dev Build: 1361

[Combat]:
Auto Totem (auto-totem)
Criticals (criticals)

[Player]:
Auto Fish (auto-fish)
Auto Replenish (auto-replenish)
Auto Tool (auto-tool)
Ghost Hand (ghost-hand)
No Mining Trace (no-mining-trace)
Portals (portals)

[Movement]:
Elytra Boost (elytra-boost)
Entity Control (entity-control)
Gui Move (gui-move)
Jesus (jesus)
No Fall (no-fall)
No Slow (no-slow)

[Render]:
Better Tooltips (better-tooltips)
Boss Stack (boss-stack)
Break Indicators (break-indicators)
Camera Tweaks (camera-tweaks)
Fullbright (fullbright)
HUD (HUD)
Item Physics (item-physics)
Logout Spots (logout-spots)
Nametags (nametags)
No Render (no-render)
Search (search)
Storage Esp (storage-esp)
Tracers (tracers)
Void Esp (void-esp)

[World]:
Anti Cactus (anti-cactus)
Auto Sign (auto-sign)
Auto Smelter (auto-smelter)

[Misc]:
Anti Packet Kick (anti-packet-kick)
Inventory Tweaks (inventory-tweaks)
Middle Click Friend (middle-click-friend)
Vanilla Spoof (vanilla-spoof)

#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Daniel\AppData\Roaming\.minecraft\meteorinstallation\crash-reports\crash-2022-01-14_22.02.12-client.txt
  <log4j:Event logger="meteordevelopment.meteorclient.MeteorClient" timestamp="1642194132206" level="INFO" thread="Thread-5">
    <log4j:Message><![CDATA[Saving]]></log4j:Message>
  </log4j:Event>
22:02:12.242
XML_ERROR_PARSING
22:02:13.280

22:02:13.280
Process crashed with exit code -1

### Steps to reproduce

```bash
Baritone schematic building (also for the highway builder)
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
baritone issue
