### ISSUE TITLE
[Bug] Adding Cracked Accounts / Some not working

### ISSUE THREAD

**Issue by kapustaz** [MeteorDevelopment/meteor-client#1947]
### Describe the bug

So I tried adding some random gibberish letters number over 5 characters and it plays me choose, however if i want to login to a specific account, or add my own premium account, after clicking add, I see the 3 OoO and after nothing happens.  Their should be a way to login to any username, I don't what what this bug is or how to duplicate it

### Steps to reproduce

To reproduce just go to Multi player - > Accounts and just type any username for cracked and hit add, half of the time it doesn't work, only 2 names out of 100 I tried let me add the cracked accounts, and those 2 are not registered in Mojang. 

### Meteor Version

Current

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
Cant do much when you have no steps to reproduce.

**Comment by kapustaz** [comment]
Bro to reproduce just go to Multi player - > Accounts and just type any username for cracked and hit add, half of the time it doesn't work, only 2 names out of 100 I tried let me add the cracked accounts, and those 2 are not registered in Mojang,  so maybe adding real accounts like grumm don't let you?

**Comment by rusyaew** [comment]
Uncaught exception in thread "pool-5-thread-1"
java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1358)
	at meteordevelopment.meteorclient.systems.accounts.AccountCache.loadHead(AccountCache.java:45)
	at meteordevelopment.meteorclient.systems.accounts.Account.fetchHead(Account.java:36)
	at meteordevelopment.meteorclient.gui.screens.AccountsScreen.lambda$addAccount$5(AccountsScreen.java:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by rusyaew** [comment]
i tried account "goodtime"

**Comment by seasnail8169** [comment]
99% sure this doesn't happen anymore
