### ISSUE TITLE
Pickaxe won't budge out of the hotbar

### ISSUE THREAD

**Issue by dogeology** [MeteorDevelopment/meteor-client#1949]
### Describe the bug

In the 1.18 Dev Build of Meteor client on Windows 11, if you drag a pickaxe to your inventory and out of your hotbar, it goes immediately back to the 1st slot, no matter the gamemode, modules toggled, or type of pickaxe. You can drop it, but it will go to the 1st hotbar slot once you pick it up and only to that slot. If there is a item already within the 1st slot, the pickaxe will replace it and the item will go else where in my inventory

https://user-images.githubusercontent.com/97562496/149608382-f53743b6-16a9-4d43-947f-175444e49d2a.mp4

https://user-images.githubusercontent.com/97562496/149608513-70b59545-f0c5-42f1-a444-50f279db0816.mp4

### Steps to reproduce

```bash
1. Get a Pickaxe (any)

2. Move Pickaxe to Inventory

3. Pickaxe moves to 1st hotbar slot instantaneously

OR

1. Put any item in the 1st hotbar slot

2. Get a Pickaxe (any)

3. Move Pickaxe to Inventory

4. Pickaxe replaces item in 1st hotbar slot instantaneously
```

### Meteor Version

 Dev Build 0.4.7 - 1399

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by BookWyrm114** [comment]
I had that bug on a previous dev build, running windows 10 and 1.17

**Comment by dogeology** [comment]
I got in contact with support on discord, it is solvable by setting allowinventory on Baritone to false
