### ISSUE TITLE
[Suggestion] Anti-Blindness

### ISSUE THREAD

**Issue by Theboiboi8** [MeteorDevelopment/meteor-client#1950]
### Describe the feature

based utility client feature fr fr also maybe add it to No Render settings because only nausea is in there rn

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SIMULATAN** [comment]
Check the NoRender mod

**Comment by Theboiboi8** [comment]
> Check the NoRender mod

I personally cannot find any such options in the no-render options

**Comment by bluepanee** [comment]
> > Check the NoRender mod
> 
> I personally cannot find any such options in the no-render options

It's called fog.

**Comment by bluepanee** [comment]
> Fog is enabled in norender and the blindness effect still occurs

Ah, I get it. Probably sodium issue if you have it installed. #1705 #1696

**Comment by Wide-Cat** [comment]
this should be resolved
