### ISSUE TITLE
[Bug] Text will glitch out of bounds/box.

### ISSUE THREAD

**Issue by AL3X45DJGamer** [MeteorDevelopment/meteor-client#1952]
### Describe the bug

Earlier, I already wrote this but I accidentally press Closed but I rewrite it again.
So I was scrolling through the baritone configuration then this happened again.
Same goes for the HUD and other categories. I've been experiencing this since I first got meteor.

![image](https://user-images.githubusercontent.com/97241724/149666474-8395dee2-a6bd-4b03-aced-c2ea49a8330c.png)

![image](https://user-images.githubusercontent.com/97241724/149666580-da87cfa2-24ee-4aa3-84b0-3bd5b5173049.png)

### Steps to reproduce

```bash
Scroll through Baritone section, No Render and etc will make text glitch and out of bounds.
```

### Meteor Version

Meteor Client Dev-build 0.4.7 - 1401

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by AL3X45DJGamer** [comment]
And also someone asked for my mods folder and I'll show it. I just **Updated** the whole mods in the mods folder and it still occurred.
![Bug (1)](https://user-images.githubusercontent.com/97241724/149666741-387e20ca-219a-44cc-82a9-2a3988fd49ce.png)

**Comment by AL3X45DJGamer** [comment]
Someone asked me to show the mods folder. So I'll show. But I **Updated** the mods but the error still occured
![Bug (1)](https://user-images.githubusercontent.com/97241724/149667133-ad3159dd-2af5-4d41-b891-dcf5476700cd.png)
.

**Comment by RedCarlos26** [comment]
Could this be related to #

**Comment by RedCarlos26** [comment]
Also does this still happen for you

**Comment by AL3X45DJGamer** [comment]
Not anymore since I updated meteor to the latest version. Thanks.

**Comment by seasnail8169** [comment]
> Could this be related to #2476?

no

**Comment by seasnail8169** [comment]
it's an issue with some texture packs

**Comment by seasnail8169** [comment]
#1854
