### ISSUE TITLE
[Suggestion] Addon Specific Naming

### ISSUE THREAD

**Issue by scout247** [MeteorDevelopment/meteor-client#1957]
### Describe the feature

To prevent overlapping of modules from Addons, add an option in standard Meteor to add a prefix to every addon. This would allow for the following

An addon called "Nemesis" has a module called: Surround+
An addon called "Norphius" has a module called: Surround+

When enabebling the config option, this would result in te following:
Nemesis Prefix: "Ne"
Norphius Prefix: "No"

Module names:
Ne - Surround+
No - Surround+

Which means: no overlap, 2 fully functional Surround+ modules without one overwriting the other.

The prefixes should be configurable and will have to be loaded before the modules of the addons get loaded.

Greetings,
Scout

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by C10udburst** [comment]
shouldn't this be implemented on a per addon basis?

**Comment by scout247** [comment]
> 

As there is no way to make sure people keep other addons in mind when writing their own (there is a few that are smart enough to do so) then no, would be better to have a toggleable option in meteor to prevent issues with addons not taking this into account. (that is my opinion btw, doesnt mean you look at it in the same way). I think it is best for the whole addon way of thinking with meteor since it will allow players to use multiple addons without having to worry which module overwrites which module

**Comment by scout247** [comment]
And yes, im busy atm so my english looks like wordvomit

**Comment by Makrennel** [comment]
just stop using addons

**Comment by Makrennel** [comment]
all these shit addon devs making ares surround skids which are 1% better than the skid they copied and naming them the exact same thing. just use a different name you mong

**Comment by scout247** [comment]
Most modules that are double in my list are significantly different from eachother. Telling people to stop using addons isn't really an option, why would you then add the possibility to make addons

**Comment by arlomcwalter** [comment]
> Most modules that are double in my list are significantly different from eachother. Telling people to stop using addons isn't really an option, why would you then add the possibility to make addons

to limit the amount of people skidding the whole client

**Comment by scout247** [comment]
> shouldn't this be implemented on a per addon basis?

Well yes, yet some addons make modules with the same name. Take "Cev breaker" for example. there is about 3 different Cev Breakers on the market momentarily, yet the all override eachother just leaving the player with one version, which most of the time is the crappiest of the three because law of murphy and shit xD

So would generally like it to have an option to enable this in the client itself. Doesnt have to be enabled on default,  but would very much help players with a lot of addons

Sorry for opening this suggestion again, was talking about it with some friends and they also hoped this would be added. Making a new suggestion is only spam, so keeping it here.

Geetings,

**Comment by arlomcwalter** [comment]
> > shouldn't this be implemented on a per addon basis? ~C10udburst
> 
> 
> 
> Well yes, yet some addons make modules with the same name. Take "Cev breaker" for example. there is about 3 different Cev Breakers on the market momentarily, yet they all override eachother just leaving the player with one version, which most of the time is the crappiest of the three because law of murphy and shit xD
> 
> 
> 
> So would generally like it to have an option to enable this in the client itself. Doesnt have to be enabled on default,  but would very much help players with a lot of addons
> 
> 
> 
> Sorry for opening this suggestion again, was talking about it with some friends and they also hoped this would be added. Making a new suggestion is only spam, so keeping it here.
> 
> 
> 
> Geetings,

you didnt reopen the issue

**Comment by scout247** [comment]
> you didnt reopen the issue

You know what I mean, I know it's still closed on gitub. Could we please keep the comments here on-topic. The suggestion got closed based on an opinion, looking for ground to build on as I've heard many people about this being a good addition to the client.

Didn't want to open a new ticket. So thats why I said "sorry I opened it again" with which I meant "sending messages in a closed ticket".

I'll wait for an answer, curious about the opinions of some other participants

**Comment by arlomcwalter** [comment]
> > you didnt reopen the issue
> 
> 
> 
> You know what I mean, I know it's still closed on gitub. Could we please keep the comments here on-topic. The suggestion got closed based on an opinion, looking for ground to build on as I've heard many people about this being a good addition to the client.
> 
> 
> 
> Didn't want to open a new ticket. So thats why I said "sorry I opened it again" with which I meant "sending messages in a closed ticket".
> 
> 
> 
> I'll wait for an answer, curious about the opinions of some other participants
> 
> 
> 
> 

i'm 99.99% certain it will never be added
