### ISSUE TITLE
[Suggestion] Alphabetically sort module list

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#1958]
### Describe the feature

As said in the title, I think it'd be nice to have the option to sort the module list alphabetically.

It's easier to find what you need in a sorted list.
The sorting name could be `Alphabetic` or `Alphasort`.
We already have a drop down menu so it could be added to it easily.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Justgamer101** [comment]
Is it not already sorted?

**Comment by Lovecrafts-Cat** [comment]
> Is it not already sorted?

My bad for not being so specific, I meant the Active Moudle List
![2022-01-20 15_06_28 javaw ZHaqy_LI](https://user-images.githubusercontent.com/52252627/150354102-6ddbf8fe-1f41-4e34-8b6d-70f523f82bba.jpg)
