### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by BigNoOob** [MeteorDevelopment/meteor-client#1959]
### Describe the feature

Can you remove that it requires a mending pickaxe since you can really get a mending pickaxe at the start of the game and change it to like the repair blocks require a mending pickaxe.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Just use baritone normally
