### ISSUE TITLE
[Bug] Killaura always on axe delay

### ISSUE THREAD

**Issue by zaryar** [MeteorDevelopment/meteor-client#1960]
### Describe the bug

Does not matter if I use smart delay, it always has a long ass delay. Maybe I'm just retarded, but I'm pretty sure it's a bug.

### Steps to reproduce

```bash
Duh, turn on killaura XD
```

### Meteor Version

Release 0.4.6

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
Are you sure you don't have custom delay on? I do not have this issue

**Comment by zaryar** [comment]
Ye nah it was mb, there was a name tag plugin on the server. So it stopped hitting after the first strike.
