### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jorgebros08** [MeteorDevelopment/meteor-client#1965]
### Describe the bug

kill aura dont work

### Steps to reproduce

```bash
proving the kill aura
```

### Meteor Version

0.4.6 and 0.4.7 dev team update

### Minecraft Version

18+ and 1.7+

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by dylif** [comment]
Have you enabled the entities you want to target in the GUI?
