### ISSUE TITLE
[Suggestion] ClickGUI should not be bound to a keybind to prevent screensharing

### ISSUE THREAD

**Issue by Errorcrafter** [MeteorDevelopment/meteor-client#1966]
### Describe the feature

As of the current dev build the Meteor ClickGUI is bound to a keybind in the settings menu. as such, several server owners have found that they can tell a suspected Meteor user to rebind sneak/sprint/any arbitrary control to Right Shift while screensharing. As Minecraft highlights conflicting keybinds in red and the ClickGUI has its keybind set to Right Shift by default, server owners are able to easily tell if someone is using Meteor with this method.

So I suggest making the ClickGUI's keybind changeable in the clickgui itself, either as a module or inside the Config tab so this method cannot be used.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
meteor is not meant to be used to cheat on servers

**Comment by Wide-Cat** [comment]
💀
