### ISSUE TITLE
[Suggestion] Stash finder count

### ISSUE THREAD

**Issue by electronphenom** [MeteorDevelopment/meteor-client#1967]
### Describe the feature

Hi, as with a few other things, like storage esp or tracers, they have a count number next to them in the HUD.. It would be nice, if the Stash finder could also have a count, to show how many stashs its found, that are in its list it keeps within its settings.. that way i dont have to keep going into the settings to see if its found any if ive been afk while it searchs

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Selbstverliebter** [comment]
hm
