### ISSUE TITLE
[Bug] meteor dev build 1406 crashes most addons

### ISSUE THREAD

**Issue by Theboiboi8** [MeteorDevelopment/meteor-client#1968]
### Describe the bug

title

### Steps to reproduce

```bash
install meteor addon (vector; orion; etc.)
instal meteor 1406 or later
enjoy
```

### Meteor Version

=> 1406

### Minecraft Version

1.18/1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by C10udburst** [comment]
orion's updated

**Comment by C10udburst** [comment]
and this is not a meteor client issue
