### ISSUE TITLE
[Suggestion] a panic button that disables all hacks 

### ISSUE THREAD

**Issue by slowbro63s** [MeteorDevelopment/meteor-client#1969]
### Describe the feature

a feature that can be binded to any key, that when pressed/activated disabless all hacks enabled.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
.toggle all off
