### ISSUE TITLE
[Bug] HUD Keybind acting strangely

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#1971]
### Describe the bug

The HUD keybind can be activated inside of the Meteor Clickgui, unlike other binds. This also means that it toggles when setting another module to the same keybind as your HUD.
Additionally, if you have multiple modules bound to the same key as HUD, you will notice that the HUD has a delay to being enabled/disabled. (other modules will be turned off first, then the hud shortly after)

### Steps to reproduce

```bash
Activating in GUIS
1. Bind HUD to a key (eg; H)
2. Open Meteor clickgui and press your HUD keybind
HUD will be toggled.

Toggle Delay
1. Bind your HUD to "h"
2. Bind flight to "h"
3. Press h and observe flight being toggled off first, then the hud disappearing shortly after.
```

### Meteor Version

0.4.7 Release

### Minecraft Version

1.1.8.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
i dont see any issue with this.
