### ISSUE TITLE
[Bug] Crashes with Pehkui mod

### ISSUE THREAD

**Issue by Dragonlord1005** [MeteorDevelopment/meteor-client#1975]
### Describe the bug

When having the pehkui mod installed alongside meteor, the game will crash on launch, I know it is caused by meteor because when disabling meteor, the game launches normally. It seems that meteor is forcing itself to overwrite pehkui

game log: https://paste.ee/p/mpyY4
crash log: https://paste.ee/p/GE9NR

### Steps to reproduce

```bash
Install meteor client and pehkui, launch the game, crash.
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Vitalasy** [comment]
origins shit incompatible.pehkui is used to manipulate entity size right?

**Comment by Dragonlord1005** [comment]
Yes, although I am not using origins, but immersive portals

**Comment by Justgamer101** [comment]
have you tried it without using 10 thousand other mods?

**Comment by Justgamer101** [comment]
try with the vanilla launcher

**Comment by Dragonlord1005** [comment]
@Justgamer101 The issue when running the vanilla launcher still occurs, with the same set of mods installed

**Comment by Justgamer101** [comment]
then dont use whatever that mod was that causes it to crash

**Comment by Dragonlord1005** [comment]
It was pehkui that caused it to crash, but I want to use that mod, is there any way around it?
