### ISSUE TITLE
Cape hidden while using chams.

### ISSUE THREAD

**Issue by zb2t** [MeteorDevelopment/meteor-client#1977]
### Describe the bug

When using the chams module, it makes capes glitch so that it's semi-invisible within the player chams area.

### Steps to reproduce

```bash
Turning on chams, with the none shader setting, players set to on.
```

### Meteor Version

0.4.8- 1413

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
what is up with you and chams?
