### ISSUE TITLE
[Bug] Basically none of the "Death" features in "Waypoints" work on cracked servers

### ISSUE THREAD

**Issue by Theboiboi8** [MeteorDevelopment/meteor-client#1981]
### Describe the bug

Sending death location in chat – broken, doesn't work
adding a waypoint on the point of death – broken, doesn't happen

also /kill nr other similar methods of dying don't work at all.

### Steps to reproduce

```bash
install meteor devbuild 1415
enable waypoints and enable any of the features for "Death Position" and optionally disable the one with singleplayer for testing
die
experience the pain
```

### Meteor Version

dev. 1415

### Minecraft Version

1.18/1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
problem: cracked servers
solution: normal servers

I've done all of these things on oa with no issue.
so maybe a config issue? (too far to render way points, anti coord leak etc...)
a cracked server interacts with a client in the exact same way as a vanilla server.

**Comment by Theboiboi8** [comment]
> 

idk, doesn't seem to work for me on any of the cracked servers I play on and sometimes even on normal servers
