### ISSUE TITLE
[Bug] Can't take items out of containers in 1.12.2

### ISSUE THREAD

**Issue by LilyyDev** [MeteorDevelopment/meteor-client#1984]
### Describe the bug

Using the latest version of MultiConnect to join 2b2t on 1.12.2, items can't be taken out of my echest or any other containers as they just glitch back in. Works with other clients so I know it's something with meteor, other than that amazing client but yikers please fix this <3

### Steps to reproduce

```bash
Taking items out of containers while using the MultiConnect mod to join a 1.12.2 server.
```

### Meteor Version

Latest

### Minecraft Version

Fabric 1.18.1 => MultiConnect 1.12.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Declipsonator** [comment]
What other clients did you use

**Comment by LilyyDev** [comment]
> What other clients did you use

I have tried Impact, Vanilla, Optifine, even Lunar and none of them have the same issue.
I have also tried using ViaFabric as a replacement for MultiConnect and the same bug appears still so this is definitely an issue with meteor.

**Comment by missonance** [comment]
literally 1984
