### ISSUE TITLE
[Bug] Creative GUI Crash

### ISSUE THREAD

**Issue by Upsilon7** [MeteorDevelopment/meteor-client#1985]
### Describe the bug

When having GUI Move on and in Creative Mode game freezes then crashes upon opening the Creative GUI.

### Steps to reproduce

```bash
Turn GUI Move on then open the creative menu.
```

### Meteor Version

v0.4.8 build #1415 dev

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Declipsonator** [comment]
Send the crash report

**Comment by MineGame159** [comment]
@Upsilon7
