### ISSUE TITLE
[Feature Update for NoteBot] 

### ISSUE THREAD

**Issue by JustARandomName1** [MeteorDevelopment/meteor-client#1987]
### Describe the feature

The notebot on meteor client feels really simplistic and cant play on more than 5x5 platform of noteblocks, I want to suggest to make it detect the different blocks under the noteblocks ( the different instruments ) and be able to tune and configure a whole platform that could play high detail songs.

This has been seen done by other clients such as inertia and future and would be really cool to see happen in a future update for meteor!
For reference of how i would like to see this happen can be found on youtube:https://www.youtube.com/watch?v=N8fV6pUv6uE , I will also attach a screenshot of one of the noteblock layouts i wish for notebot to be compatible with.
Thanks
![Screenshot 2022-01-25 at 17 21 36](https://user-images.githubusercontent.com/87848632/151026894-92f705e3-54fb-4376-9892-d42ef2fb7493.png)
!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Justgamer101** [comment]
ok, who actually uses notebot that much?

**Comment by JustARandomName1** [comment]
i do, is that a problem?

**Comment by Vitalasy** [comment]
> i do, is that a problem?

yeah it is.

**Comment by Holatae** [comment]
> ok, who actually uses notebot that much?

Notebot is awesome and fun to use

**Comment by 8MiYile** [comment]
yes yes 
i love that

**Comment by Wide-Cat** [comment]
This is now more than possible
