### ISSUE TITLE
[Bug] Session crashes after several hours

### ISSUE THREAD

**Issue by iFeather** [MeteorDevelopment/meteor-client#1989]
### Describe the bug

(1.18.1) newest version of meteor. the client will crash after a few hours, even when afking and not doing anything.

### Steps to reproduce

```bash
run minecraft for a few hours with meteor
```

### Meteor Version

o.4.7

### Minecraft Version

1.18.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send crash report

**Comment by Vitalasy** [comment]
> iFeather

no crash log and the issue is your shit device i can tell

**Comment by TwoThreeTwo** [comment]
Stop playing for like 5 hours you sad sack of lard

**Comment by MineGame159** [comment]
@iFeather
