### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by e45g** [MeteorDevelopment/meteor-client#1990]
### Describe the bug

My minecraft is crashing after I make baritone build schematics with allowInventory on true

### Steps to reproduce

```bash
.b set allowInventory true
.b build <file>
*crash*
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by C10udburst** [comment]
maybe attach a crash report?
