### ISSUE TITLE
[Suggestion] Add a anticheat disabler?

### ISSUE THREAD

**Issue by ItzVaio** [MeteorDevelopment/meteor-client#1993]
### Describe the feature

Basically just the Sigma 5.0 anticheat disabler, but more advanced. Because most of the people use Meteor on server's that have anti-cheats and not anarchy. so which type of anticheat should it disable: AntiGamingChair, AntiCheatReloaded, Watchdog 2, Sentiel Anticheat (cubecraft anticheat), etc.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SIMULATAN** [comment]
yes please!!11 and also add bake me a cake modlule pls and maek ym homwork module!!11

**Comment by Justgamer101** [comment]
meteor is specifically made as a utility mod and not for cheating on servers which don't allow it. And who uses meteor for that.
