### ISSUE TITLE
[Bug] crash on fabric

### ISSUE THREAD

**Issue by minhlongdev** [MeteorDevelopment/meteor-client#1994]
### Describe the bug

i install and got crash

error log : RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
<html>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)<br/>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)<br/>at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:606)<br/>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
NoClassDefFoundError: org/spongepowered/asm/mixin/transformer/FabricMixinTransformerProxy
<html>at java.base/java.lang.ClassLoader.defineClass1(Native Method)<br/>at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)<br/>at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)<br/>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)<br/>at meteordevelopment.meteorclient.MixinPlugin.onLoad(MixinPlugin.java:59)<br/>at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)<br/>at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)<br/>at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)<br/>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)<br/>at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)<br/>... 6 more</html>
ClassNotFoundException: org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy
<html>at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)<br/>at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)<br/>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)<br/>at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)<br/>at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)<br/>... 23 more</html>

mods : only meteor
fabric version : 0.12.12

### Steps to reproduce

```bash
just run
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
This is unreadable, either post the crash log file, or link a formatted text from pastebin.

Also be sure to play on 1.18.1, with Java 17 and latest version of the Fabric loader.

**Comment by Justgamer101** [comment]
what lovecrafts-cat said and fabric api for the current version

**Comment by ItssParadox** [comment]
same happened to me aswell while trying to redownload the client for baritone. (i needed to redownload due to a full reset on my pc.)
