### ISSUE TITLE
[Bug] Axolotl missing from Tracers entities

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#1995]
### Describe the bug

As said in the title.
Missing toggle for Axolotls in the entities selector.
![2022-01-28 23_20_28 javaw 904sm](https://user-images.githubusercontent.com/52252627/151629670-2d3c5eb7-0a47-4916-bdba-5ba34dd906d0.png)
![2022-01-28 23_22_48 javaw orI73](https://user-images.githubusercontent.com/52252627/151629674-3d523553-922d-4ad8-873a-3ff5469f2a8a.png)

Still an issue even on latest dev build.

### Steps to reproduce

```bash
Open Tracers menu
Edit entities
No "Axolotl" option under "Water Animals"
```

### Meteor Version

0.4.7-1401

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in ca4d557a61f4956e95a724da1ca4ea94d47a4ea7.
