### ISSUE TITLE
[Suggestion] Phasing etc

### ISSUE THREAD

**Issue by dxzv666** [MeteorDevelopment/meteor-client#1997]
### Describe the feature

I would really like to see a Phase/Noclip module on Meteor to phase into players bases

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by bluepanee** [comment]
Duplicate of #1681

**Comment by Justgamer101** [comment]
vclip doesn't work on vanilla. also just break 2 blocks 😆

**Comment by bluepanee** [comment]
> vclip doesn't work on vanilla. also just break 2 blocks lmao

You mean hclip but who cares. vclip still a thing.

**Comment by master7720** [comment]
> vclip doesn't work on vanilla. also just break 2 blocks lmao

you know thats too hard for @dxzv666

**Comment by SIMULATAN** [comment]
Iirc meteor rejects has a phase
