### ISSUE TITLE
[Bug] Search module doesn't render liquids correctly.

### ISSUE THREAD

**Issue by bluepanee** [MeteorDevelopment/meteor-client#2002]
### Describe the bug

How it looks:
![2022-01-30_16 15 12](https://user-images.githubusercontent.com/53943505/151697603-632deabb-575e-4aa1-b2f5-dc17c4a13942.png)

How it should look like:
![2022-01-30_16 15 52](https://user-images.githubusercontent.com/53943505/151697605-612329fa-0611-4cc7-9e97-91c96adbf94f.png)

### Steps to reproduce

```bash
1. Select water/lava in the Search module.
2. Voila.
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
doesn't seem useful. and why would you have a liquid enabled for search anyways?

**Comment by MineGame159** [comment]
Fixed in 16b87802844cc894c3955452696e21c7e7d90e87.
