### ISSUE TITLE
[Suggestion] More PotPVP Combat Modules

### ISSUE THREAD

**Issue by 010101230** [MeteorDevelopment/meteor-client#2005]
### Describe the feature

Module #1: Hotbar Refiller - When you open your inventory the client automatically puts splash health potions into your hotbar

Module #2: Inventory Autoclicker - Self explanatory, let's you autoclick in the inventory so you can refill health pots faster

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Justgamer101** [comment]
inventorytweaks module. (close issue reason 1) also this implies you will use this to cheat on servers which dont allow it (close issue reason 2)
