### ISSUE TITLE
[Suggestion] bypass server texturepack

### ISSUE THREAD

**Issue by no0name97802** [MeteorDevelopment/meteor-client#2009]
### Describe the feature

some servers ask you to use a resourcepack, there could be a module to bypass that

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Bluscream** [comment]
https://gitlab.com/0x151/atomic/-/blob/master/src/main/java/me/zeroX150/atomic/feature/module/impl/misc/TexPackSpoof.java
