### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mateoiskool** [MeteorDevelopment/meteor-client#2013]
### Describe the bug

when i turn on autolog and put it to 20 health i cant join servers anymore, so thic client is useless untill u guys fix this. would be very cool. btw uninstalling and instaling it again also didnt work

### Steps to reproduce

```bash
by pressing auto log to trigger at 20 health
```

### Meteor Version

4.7

### Minecraft Version

1.18

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
You can open the GUI in main menu.

**Comment by dylif** [comment]
you can also delete the meteorclient folder in .minecraft if you wish to revert your configuration

**Comment by RickyTheRacc** [comment]
Rip bozo 2022 #packwatch

**Comment by Justgamer101** [comment]
why would uninstalling and reinstalling change anything? its the exact same jar. or just delete the meteor client config folder (lazy). or join a singleplayer world without meteor client give yourself an enchanted golden apple, eat it in survival then rejoin the world with meteor client (also lzay) Or decode the meteor nbt config file and edit it directly (less lazy). or realize that minegame said a simple solution and this was a waste of time.
