### ISSUE TITLE
[Suggestion] AutoFishing Anti-Break option

### ISSUE THREAD

**Issue by NakyoykaN** [MeteorDevelopment/meteor-client#2014]
### Describe the feature

I need a way to prevent my non mending fishing rods from being broken in the early game.  The default fishing rod only has 64 durability, and I usually have a bunch of these fishing rods while trying to get Mending with AFK fishing.  

Add a feature to prevent allowing a fishing rod to be broken, and maybe also auto switch fishing rods.

I tried enabling AutoFish plus the Auto Tool with the Break option on but it did not work.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Selbstverliebter** [comment]
W

**Comment by Vitalasy** [comment]
Unbased
