### ISSUE TITLE
Beeing able to write § symbol

### ISSUE THREAD

**Issue by Teero888** [MeteorDevelopment/meteor-client#2016]
### Describe the feature

A simple function which removes the restriction of not beeing able to write the § symbol.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by C10udburst** [comment]
that would just kick you from the server
