### ISSUE TITLE
[Suggestion] Series of events leading to an action (VERY IMPORTANT TO ADD)

### ISSUE THREAD

**Issue by MysteryNBS** [MeteorDevelopment/meteor-client#2017]
### Describe the feature

A module where you can type your series of events to do something.
For Example:

If [**_Rank: Owner, Mod, Mod+, Helper_** Joins Game] do [Command: "#stop", "/home"]
 
Or another example:

If [**_Rank: Owner, Mod, Mod+, Helper_** Joins Game] do [Leave Game]

Or another example:

If [Inventory Full] do [Place _**minecraft:ancient_debris**_ in shulker]

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Declipsonator** [comment]
no chance

**Comment by RickyTheRacc** [comment]
Do not use meteor on servers where it is not explicitly allowed, also cope retard

**Comment by Vitalasy** [comment]
cope harder.
