### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Flopiko** [MeteorDevelopment/meteor-client#2018]
### Describe the feature

Add realistic lines and sides if using fireworks on crossbow with trajectories

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by DesiCow** [comment]
Resolved in #2918
