### ISSUE TITLE
crystal aura doesn't auto hit the crystal after placing a crystal

### ISSUE THREAD

**Issue by 1st2Last** [MeteorDevelopment/meteor-client#202]
crystal aura places a crystal but fails to hit it even when the crystal is clearly hittable, i even meesed with the settings and it still doesnt want to hit the crystal at all so it leaves the player to hit them manually and if the crystals get placed on the other side of a block the player is screwed if they dont have a second client to crystal pvp, i have also downloaded the client about 5 times as of right now to make sure it wasnt a downloading problem

**Comment by supakeks** [comment]
What server are you on?
What's your ping?
What are your crystal aura settings?
Can you send us a screenshot of your crystal aura settings? thanks

**Comment by seasnail8169** [comment]
config issue, ask for help in the discord

**Comment by 1st2Last** [comment]
@supakeks it doesnt matter what server im on it wont work even in singleplayer, my average ping on eliteanarchy.org is 19-24 on average, these are screenshots of my settings even if i dont change  any of the settings it doesnt work, i remember it working a couple weeks ago and than i updated and it wont work, ive even gone so far as too even delete my entire.minecraft folder and use it but still no luck
![2021-01-27_16 12 16](https://user-images.githubusercontent.com/78060132/106055319-33d9e180-60bb-11eb-9d46-735858ec7320.png)
![2021-01-27_16 12 19](https://user-images.githubusercontent.com/78060132/106055321-34727800-60bb-11eb-8329-0f21dc3fd544.png)
![2021-01-27_16 12 22](https://user-images.githubusercontent.com/78060132/106055323-350b0e80-60bb-11eb-8bc8-ecf285e77721.png)
![2021-01-27_16 12 25](https://user-images.githubusercontent.com/78060132/106055325-350b0e80-60bb-11eb-9334-cca42af6d685.png)
