### ISSUE TITLE
Flight hack issue [Bug]

### ISSUE THREAD

**Issue by GlitchaXD** [MeteorDevelopment/meteor-client#2020]
### Describe the bug

For some reason when using flight the No Fall module doesn't work also sometimes i would randomly die from fall damage in mid-air

### Steps to reproduce

```bash
To make the no fall work i turn on and off the flight but sometimes when i turn it off mid air I die or take massive damage in the air
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Duplicate

**Comment by Bluscream** [comment]
That because sneak. Dont ever sneak you based coper
