### ISSUE TITLE
auto clicker need improvement

### ISSUE THREAD

**Issue by mr-moon-face** [MeteorDevelopment/meteor-client#2025]
### Describe the feature

can u add a more user friendly auto clicker module?
what is this click delay even means?
1 ms?
1 cps?
1 tps?
1 banana?
add a cps mode guys

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Have you tried reading the description?

**Comment by arlomcwalter** [comment]
the state of meteor issues

**Comment by RickyTheRacc** [comment]
The state of seasnail

**Comment by arlomcwalter** [comment]
> The state of seasnail

who's that

**Comment by Justgamer101** [comment]
mr-moon-face, the intelligence is inspiring

**Comment by Vitalasy** [comment]
unbased issue
