### ISSUE TITLE
add a survival nbt editor[Suggestion] 

### ISSUE THREAD

**Issue by tympanicblock61** [MeteorDevelopment/meteor-client#2026]
### Describe the feature

right now the .nbt only works in creative and im wonering if you can make it survival and creative

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
You can't just modify stuff however you want.

**Comment by Lovecrafts-Cat** [comment]
> You can't just modify stuff however you want.

"What do you mean I can't edit my 1337 armor to have Thorns 420?"
