### ISSUE TITLE
 Add more versions

### ISSUE THREAD

**Issue by BigNoOob** [MeteorDevelopment/meteor-client#2028]
### Describe the feature

Is it possible for you to add different version since you can only use meteor client with 1.18.1

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Multiconnect

**Comment by Justgamer101** [comment]
lol

**Comment by BigNoOob** [comment]
Wow this is the best comment in history
