### ISSUE TITLE
cbe[Suggestion] 

### ISSUE THREAD

**Issue by tympanicblock61** [MeteorDevelopment/meteor-client#2029]
### Describe the feature

command block editor. a command block editor that does not require you to be in creative or have op

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Vitalasy** [comment]
no

**Comment by Justgamer101** [comment]
lol

**Comment by tympanicblock61** [comment]
wtf
