### ISSUE TITLE
[Suggestion] Anti Console/Anti Log

### ISSUE THREAD

**Issue by SynthWareJS** [MeteorDevelopment/meteor-client#2030]
### Describe the feature

A module which deletes certain logs or warnings from the console log file. Kind of like MultiMC since it stops printing logs after reaching a maximum limit

Dont ask why I dont use MultiMC

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
> Dont ask why I dont use MultiMC

Well now I gotta know. The only reason not to is if you have a cracked account.

Also don't know if it's possible to do that. Why would you need to edit a normal log, not even a crash log?

**Comment by Vitalasy** [comment]
cracked pooron

**Comment by hellidox** [comment]
meteor spams the log with generic opengl errors for some reason
