### ISSUE TITLE
[Bug] Xray incompatibility with Sodium

### ISSUE THREAD

**Issue by issuerep** [MeteorDevelopment/meteor-client#2032]
### Describe the bug

![image](https://user-images.githubusercontent.com/99236188/152920427-3f0923c4-dafd-4caa-9e3b-ca580589d9ba.png)
![image](https://user-images.githubusercontent.com/99236188/152920460-6ba4559a-c044-4739-bbec-d32389315391.png)
![image](https://user-images.githubusercontent.com/99236188/152920525-7d8bf817-adf8-43f7-94a7-b2c775d884de.png)

doesn't happen without sodium 

### Steps to reproduce

```bash
launch meteor with sodium present, toggle xray
```

### Meteor Version

0.4.8 dev build and stable 0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by hellidox** [comment]
workaround, use search
better anyways

**Comment by NotAstralYT** [comment]
glitches for me too but i ignore it

**Comment by issuerep** [comment]
> workaround, use search better anyways

doesnt fix the issue

**Comment by MineGame159** [comment]
It can be fixed by simply updating Sodium.

**Comment by hellidox** [comment]
> > workaround, use search better anyways
> 
> doesnt fix the issue

okay

> workaround
