### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by realunrealgamer** [MeteorDevelopment/meteor-client#2033]
### Describe the feature

Only 5 words :- MAKE IT COMPATIBLE WITH 1.17.1 

plzzz

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by C10udburst** [comment]
[read this dumbass](https://github.com/MeteorDevelopment/meteor-client/wiki#how-do-i-use-meteor-on-older-minecraft-versions)

**Comment by Vitalasy** [comment]
multiconnect exists.

**Comment by Justgamer101** [comment]
checks the box that says this wasnt suggested... suggested countless times, and every single one says use multiconnect. state of meteor issues/suggestions.
