### ISSUE TITLE
[Suggestion] CS:GO Bunnyhop

### ISSUE THREAD

**Issue by linus378** [MeteorDevelopment/meteor-client#2035]
### Describe the feature

1. Bunny Hop like in CS:GO
2. Option to turn on music (Thé à la menthe - La Caution)
3. Option to disable hud and replace it with CS:GO hud (+knife animation?)
4. Option When full speed reached play MLG Overlay and music (overlays over (Thé à la menthe - La Caution))

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Sorry, you forgot to download CS:Source. 
Your texture perms have been revoked.

**Comment by Vitalasy** [comment]
bad one.

**Comment by bluepanee** [comment]
5. add e621 integration

**Comment by RickyTheRacc** [comment]
Add e621 integration.

**Comment by hellidox** [comment]
Add e621 integration.
