### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by maxszul** [MeteorDevelopment/meteor-client#2036]
### Describe the bug

game crashs for no reson

### Steps to reproduce

```bash
i dont know
```

### Meteor Version

latest

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send crash report and reopen this issue.
