### ISSUE TITLE
chat encryption

### ISSUE THREAD

**Issue by maxszul** [MeteorDevelopment/meteor-client#2037]
### Describe the feature

you should add chat encryption so only meteor users with key can view messages

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Useless.

**Comment by maxszul** [comment]
its not with commandspy admins/mods can see commands like /msg /w /r and more. chat encryption can bypass commandspy becaus you dont need to even use a command logs/console on server cant see it, it would be better to add chat encryption then to not

**Comment by maxszul** [comment]
so please add it

**Comment by MineGame159** [comment]
You would need to first give the key to the other person through some other app such as discord so why not just use discord????

**Comment by maxszul** [comment]
you would need to tab out of minecraft to use discord and what if some1 didnt have discord then what and when you tab out you cant see whats happening on minecraft

**Comment by maxszul** [comment]
you can "/msg" the person the key the admins wont know what the random string you sent your friend is, and if you dont do it then your a cunt

**Comment by MineGame159** [comment]
Oh no, a random called me a cunt, what am I gonna do now.

**Comment by maxszul** [comment]
why you using github i dmed you on discord lmao

**Comment by Justgamer101** [comment]
the geniuses that make meteor issues/suggestions rn
