### ISSUE TITLE
Bug] 

### ISSUE THREAD

**Issue by maxszul** [MeteorDevelopment/meteor-client#2038]
### Describe the bug

[crash-2022-02-08_19.10.36-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8026751/crash-2022-02-08_19.10.36-client.txt)

### Steps to reproduce

```bash
move in hub inv=crash
```

### Meteor Version

latest

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Rejects issue.
