### ISSUE TITLE
client interaction code

### ISSUE THREAD

**Issue by JanCantCode** [MeteorDevelopment/meteor-client#2039]
### Describe the feature

How about adding a feature, which would basically make you able to "code" what the client would do frame by frame. The code would be accessable in the .meteor folder in a seperate scripts folder, and you would execute code with .run <file>, where <file> can be any file within the scripts folder. the coding language wouldn't have to be complex, maybe contain simple loops or if statements, maybe even variables or something. You could "control" what the client is doing using some type of command, for examplel
turn(yaw, pitch) // would look into the given direction in yaw and pitch
baritone(baritonecommand) // would execute an given baritone command
chatmessage(text) // send a chat message, specified with text, also works with commands.
interact(type) // interacts with the block in the direction the client is facing in, type specifies if a left or right click interaction.
craft(shape) // would put items from your inventory, if in an crafting table, in an shape formatted in some way, specified with shape, as long as the items are in your inventory, and take out the item from the crafting grid output, if theres one
getInventory(item, stackCout, nbt) // returns an array of slotID's containing an item, if given, with specific parameters
switch(slotA, slotB) // switches the items in 2 inventory slots, if one of the slots is empty it puts in the item from the other slot.
selectHotbarSlot(slot) // selects an hotbar slot which is used when calling the interact() function.
toggle(module, args) // works similar to .toggle
walk([x,y], [yaw, pitch]) // depending on what argument is specified, autowalks into an direction / towars some coords
find([x,y], [yaw, pitch]) // uses baritone to try and walk to a specific place. If baritone can't find a way, returns null 
sneak() // sneaks untill the unsneak() function is called

Obviously, all of those are ideas for commands, probaply not even that good ones. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Declipsonator** [comment]
Make an addon using the built in add-on system. You can do everything here and much more.

**Comment by Justgamer101** [comment]
this is such a bad idea, just make an addon
