### ISSUE TITLE
xray will sometimes get stuck in xray mode even when module is not active

### ISSUE THREAD

**Issue by ikearefrigerator** [MeteorDevelopment/meteor-client#204]
toggling and un toggling xray will sometimes cause the client to bug out and get stuck in xray mode. it causes certain things to render normally, but others will be stuck in xray view. kind of complicated to explain but i hope i got the point through

**Comment by asdffdsdaf** [comment]
um i tried but it didnt stuck

**Comment by ikearefrigerator** [comment]
also a new thing ive encountered is xray rendering certain items that shouldnt be rendered when the module is active, like grass, torches, and fences. ive tried reinstalling meteor but to no avail.

**Comment by Whop42** [comment]
Whenever this happens, try pressing f3+A (to reload chunks)

**Comment by MineGame159** [comment]
I believe this is fixed
