### ISSUE TITLE
[Suggestion] gui

### ISSUE THREAD

**Issue by maxszul** [MeteorDevelopment/meteor-client#2040]
### Describe the feature

you should beable to do ".bind gui 'and button'" to change the key your gui opens with

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
You can change the key in minecraft's keybinds options. GUI is not treated as a module so .bind won't work with it.

**Comment by maxszul** [comment]
how tf did i never see that
