### ISSUE TITLE
[Suggestion] Favorites Menu/Category

### ISSUE THREAD

**Issue by Mukshub** [MeteorDevelopment/meteor-client#2051]
### Describe the feature

Hello I have a suggestion for this awesome client. The Suggestion is a favorites menu when you press Rshift so you can access all of your favorited modules there instead of looking in the categories or searching. Thanks for reading

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Kxifed** [comment]
I want this

**Comment by SIMULATAN** [comment]
@Mukshub @Kxifed @bluepanee Implemented in #2061, pray for mimgam to merge it

**Comment by MineGame159** [comment]
Added in 7d13e7f8fb95d6d0e404cdd2e821cfe9e848a8bb.
