### ISSUE TITLE
[Bug] instamine/civbreak not breaking the block if it's instabroken

### ISSUE THREAD

**Issue by snnwer** [MeteorDevelopment/meteor-client#2052]
### Describe the bug

If you break a grass block (which will be instant), as example, with instamine activated, instamine will not keep breaking it.

### Steps to reproduce

```bash
Put a command block that repeatedly sets a block to grass, activate instamine, left click on the grass causing it to break, notice that instamine is not breaking it

Expected behavior:
- instamine breaking the block even if you broke it
```

### Meteor Version

0.4.8 build 1417

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
lol

**Comment by snnwer** [comment]
how did you complete this by deleting instamine
