### ISSUE TITLE
[Suggestion] Add Version List 

### ISSUE THREAD

**Issue by 0Ariel0** [MeteorDevelopment/meteor-client#2054]
### Describe the feature

a suggestion for the site is: add the version list page to help players find their version to install and play the version the player wants

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by 0Ariel0** [comment]
> They already can choose between stable and dev build. There is no reason to allow the use of outdated builds, because, as the name implies, they are outdated. If you want to play on older MC servers, use the Multiconnect mod.

Believe me, I already tried. But it didn't work

**Comment by bluepanee** [comment]
> > They already can choose between stable and dev build. There is no reason to allow the use of outdated builds, because, as the name implies, they are outdated. If you want to play on older MC servers, use the Multiconnect mod.
> 
> Believe me, I already tried. But it didn't work

What about viafabric? It works fine.

**Comment by 0Ariel0** [comment]
I know it works for some people (it doesn't for me) but that's not the reason for this suggestion. The reason is to add a new version list to the builds/dev

**Comment by Lovecrafts-Cat** [comment]
> I know it works for some people (it doesn't for me) but that's not the reason for this suggestion. The reason is to add a new version list to the builds/dev

There will never be a list to download older versions of the client.
Not only would that mean that the devs should maintain those version, but also that people could report bugs from older (and thus unpatched) versions.
Also old builds can't stay up forever, as they are deleted from Circle.ci.
