### ISSUE TITLE
[Suggestion] ShaderEsp for storage

### ISSUE THREAD

**Issue by communist-cat** [MeteorDevelopment/meteor-client#2057]
### Describe the feature

Shader mode for storageEsp

https://user-images.githubusercontent.com/97807721/154092247-2a859c89-ed28-4fd0-a452-2cbe4a611c67.mp4

( this is clip from hydraclient was just the first clip i found )

Why this? Box esp looks ugly as F*** with large clusters of storageblocks

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Added in 533fdb86ed812c76851dfcb57a1a24157fa04a59.
