### ISSUE TITLE
[Suggestion] Add Regen Module

### ISSUE THREAD

**Issue by Bladesunder** [MeteorDevelopment/meteor-client#2059]
### Describe the feature

Add a combat module that enhances the rate that saturation and hunger is consumed in order to regenerate lost health more quickly.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Declipsonator** [comment]
What you are asking for, is impossible.

**Comment by bluepanee** [comment]
antihunger?
