### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LEOlaona** [MeteorDevelopment/meteor-client#2062]
### Describe the bug

![QQ图片20220216121140](https://user-images.githubusercontent.com/85039910/154253041-966b1ebe-002b-4129-ad03-a0432274167d.png)
 Could not find a usable mending pickaxe.

This prompt appears when I mine automatically, what should I do。
This is true whether I have the tools or not。

### Steps to reproduce

```bash
When I need a certain material set use(infinity miner) will be like this
```

### Meteor Version

0.4.7   0.4.8

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
You need to have a pickaxe with mending in your hotbar to use infinity miner.
That module works in the following way:

- Check if mendig pickaxe is in hotbar
- Mine selected block, until durability reaches the treshold
- Mine the block selected to gain XP
- Repeat until inventory is full or module is stopped

If what you wanted is to just mine blocks, then use the Beritone #mine BLOCK_NAME command.

**Comment by Justgamer101** [comment]
close dumb issue
