### ISSUE TITLE
[Bug] Update checker is broken

### ISSUE THREAD

**Issue by C10udburst** [MeteorDevelopment/meteor-client#2063]
### Describe the bug

1. [api endpoint](https://meteorclient.com/api/version) is missing
2. yes no prompt breaks title screen rendering [because of this](https://github.com/MeteorDevelopment/meteor-client/blob/6fe78a10de08d89ca34b162f6be9a5c2b2f7867c/src/main/java/meteordevelopment/meteorclient/utils/render/prompts/YesNoPrompt.java#L127-L131)
3. ok prompt when pressing no prevents from returning to title screen

### Meteor Version

0.4.8

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 9a375aac76395104c7d0bfaa64ae6d4f435efdad
