### ISSUE TITLE
[Suggestion] anti slow falling

### ISSUE THREAD

**Issue by snnwer** [MeteorDevelopment/meteor-client#2067]
### Describe the feature

removes slow falling just like no levitation so you cant get crystaled ez

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by DesiCow** [comment]
Added in #3276
