### ISSUE TITLE
[Bug] Game crashed without even touching anything just going into a singleplayer world.

### ISSUE THREAD

**Issue by GoodGolem** [MeteorDevelopment/meteor-client#2069]
### Describe the bug

It makes the game really laggy and it crashes when entering a singleplayer world.

### Steps to reproduce

```bash
Open minecraft go in single player create a new world(It also does it in a old world.
```

### Meteor Version

0.4.8(dev build)

### Minecraft Version

fabric 1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by GoodGolem** [comment]
my mods
![image](https://user-images.githubusercontent.com/96292812/154795245-341571fc-7fe5-4d1c-a152-f3c636fb3abf.png)

**Comment by GoodGolem** [comment]
ok fixed it myself but now singleplayer is very laggy

**Comment by Lovecrafts-Cat** [comment]
Dashloader is extremely unstable.

Also have you considered not using 10 add-ons, and maybe adding some performance boosting mods, like the ones suggested in [this list](https://lambdaurora.dev/optifine_alternatives/) ?
