### ISSUE TITLE
[Suggestion] remove option to add a cracked alt

### ISSUE THREAD

**Issue by Radial2250** [MeteorDevelopment/meteor-client#2078]
### Describe the feature

cope poorfags

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Pointless request, mald and seethe.

There are users who own a legit account that might want to use a cracked alt.

**Comment by Selbstverliebter** [comment]
> No cope

Ratio
