### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by maxszul** [MeteorDevelopment/meteor-client#2080]
### Describe the bug

when using frost walker on a server like 5b5t it wont make ice but it will make ghost blocks how can i fix this?

### Steps to reproduce

```bash
idk
```

### Meteor Version

latest

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
nothing to do with meteor client. join with 1.12.2. dont use frost walker.
