### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jackezz** [MeteorDevelopment/meteor-client#2081]
### Describe the bug

It's a bug where no servers are loaded in. im not sure if its a bug or not, but i really need help.
![image](https://user-images.githubusercontent.com/100248287/155246106-14a89b75-2325-4caa-bcaf-7ef8aa0833f8.png)

### Steps to reproduce

```bash
I just open up multiplayer, then it happens.
```

### Meteor Version

meteor-client-0.4.7 

### Minecraft Version

most recent version (1.18.)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment]
use dev build 💀

**Comment by RickyTheRacc** [comment]
thanks for all the detail

**Comment by SIMULATAN** [comment]
You have a invalid proxy selected
