### ISSUE TITLE
[Bug] Highway builder crash

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#2082]
### Describe the bug

Highway builder crashes randomly
[crash-2022-02-22_22.32.14-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8121745/crash-2022-02-22_22.32.14-client.txt)

### Steps to reproduce

```bash
Turn on highway builder and wait for the crash (can be long sometimes)
```

### Meteor Version

0.4.8 - 1423

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
reproduce with no other mods installed

**Comment by xXBaboBastiXx** [comment]
Can confirm, highway crashes your game, if you get disconnected from the server and reconnect while highway builder endabled.

The reason for this is, that highway builder calculates the distance you traveled while building highway, also the broken and placed blocks. 
If you don't disable highway builder before reconnecting, the task to calculate how many blocks you traveled/broke/placed might still be in the memory. But by disconnecting and relogging, highway builder believes sometimes that you walked from spawn to your current position (let's say 500k) and attemps to count the highways build by your highway builder + the already existing highways together, which leads to absurd high numbers in blocks traveled/broken/placed and finally crashes your game.

How to avoid this crash: disable highway builder before you rejoin the server and re-enable after server join again.

**Comment by afan-kucukovic** [comment]
how do i disable highway builder withoput joining a server when i join it craches my game so im stuck in a loop
