### ISSUE TITLE
[Suggestion] Hunt mod like impact client.

### ISSUE THREAD

**Issue by GoodGolem** [MeteorDevelopment/meteor-client#2083]
### Describe the feature

It will use AI (baritone) to hunt down targets that r set by the player and it needs to work with most of the module(obviously because I don't think any module will conflict on it except .mine or could it?)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by TheRedHippo** [comment]
iirc #hunt is a command in baritone, if not use #follow player <username> and enable killaura

**Comment by GoodGolem** [comment]
But it doesn't have a settings

**Comment by GoodGolem** [comment]
right?
