### ISSUE TITLE
[Suggestion] Make diamond blocks with infinity miner.

### ISSUE THREAD

**Issue by canonrebel04** [MeteorDevelopment/meteor-client#2085]
### Describe the feature

It would be cool if you could automatically make diamond blocks when using infinity miner to save space or put them in a chest that you set.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by bluepanee** [comment]
It would be nice if someone would make an autocraft module instead.

**Comment by SnivyLlama** [comment]
That is in meteor rejects

**Comment by SnivyLlama** [comment]
But it requires a crafting table and stuff

**Comment by canonrebel04** [comment]
> That is in meteor rejects

I didn't know i just though it was a good idea.

> It would be nice if someone would make an autocraft module instead.

yea a auto craft module would be very nice.

**Comment by walksanatora** [comment]
if you want auto craft module just get [altoclef](https://github.com/gaucho-matrero/altoclef)
it is baisically baritone but slightly smarter

**Comment by Lamorkitu93** [comment]
how do you have infinite miner
i had it before, but when i downloaded meteor for 1.20.4, the module wasnt here
