### ISSUE TITLE
[Bug] Autoeat and KillAura incompatibility

### ISSUE THREAD

**Issue by unhookedhook** [MeteorDevelopment/meteor-client#2087]
### Describe the bug

Autoeat and KillAura get stuck in a loop while hungry in combat.

Suggestion to fix
Perhaps have Killaura turn off autoeat while in combat, like how it pauses baritone

### Steps to reproduce

```bash
Turn on KillAura and Autoeat
Have Sword or Axe and Food in hotbar
Go to a hostile mob
Get hungry while fighting
Autoeat tries to eat while Killaura tries to attack
This causes a loop where autoeat can't finish eating, and killarua can't finish fighting
This usually leads to death unless autoeat or killaura can quickly be switched off in time.
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Justgamer101** [comment]
why would you ever have auto eat on? There's a setting called pause auras that pauses auras...
![image](https://user-images.githubusercontent.com/79098706/155801994-0642ec30-4501-4fb8-9f60-5ae50af2fe23.png)
