### ISSUE TITLE
[Bug] Ignore Passive option in ka means phantoms attacking you are not targeted

### ISSUE THREAD

**Issue by Radial2250** [MeteorDevelopment/meteor-client#2091]
### Describe the bug

.

### Steps to reproduce

```bash
.
```

### Meteor Version

meteor client v0.4.8 build #1435

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 9eefbdffb6293da0a4a1b36de224a0a65fd5ff57.
