### ISSUE TITLE
SAVER

### ISSUE THREAD

**Issue by Jean-Michell** [MeteorDevelopment/meteor-client#2093]
### Describe the feature

you should may add in combat a module that use a splash potion of insta healts under the user when life is low 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Justgamer101** [comment]
https://www.grammarly.com/
