### ISSUE TITLE
[Bug] Meteor have issue with sky rendering

### ISSUE THREAD

**Issue by ItsIsntItsKeera** [MeteorDevelopment/meteor-client#2095]
### Describe the bug

It happen for me every version, normally it rarely happen but it now more frequencies this time
[crash-2022-02-26_21.55.27-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8148042/crash-2022-02-26_21.55.27-client.txt)

https://user-images.githubusercontent.com/91017793/155868243-d4b7455f-2e1c-4c05-b02e-f00842d63c3f.mp4

### Steps to reproduce

```bash
It can randomly happen
```

### Meteor Version

0.4.8 1435 dev build

### Minecraft Version

1..18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ItsIsntItsKeera** [comment]
seem like when u try to disable full bright it will crash the game

**Comment by MineGame159** [comment]
That crash is caused by Sodium and for the sky issue, are you 100% sure it is caused by Meteor? We never had anyone else complain about something like this.

**Comment by ItsIsntItsKeera** [comment]
i gonna try it, thanks!
