### ISSUE TITLE
[Suggestion] where to find themes？

### ISSUE THREAD

**Issue by magicfleece** [MeteorDevelopment/meteor-client#2096]
### Describe the feature

**There is a theme folder in the meteor-client folder, and there is also a theme selection interface in the settings, but how to find the theme?**
![image](https://user-images.githubusercontent.com/99643174/155873072-6ed1c114-f9d1-4612-a6ad-e87e929d7888.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by magicfleece** [comment]
I mean are there any user made themes? or how should i make it myself

**Comment by Lovecrafts-Cat** [comment]
There is a work in progress system to make custom GUI elements and even more customization.

Once it gets released and merged into Meteor, users will be able to make custom themes and share them.

For now, you have to wait until the devs complete it.

**Comment by MineGame159** [comment]
Currently themes have to be added in code so that means through addons.

**Comment by magicfleece** [comment]
Ok, I'll close it right away, I'm so sorry













At 2022-02-27 17:10:44, "MineGame159" ***@***.***> wrote:

Closed #2096.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by magicfleece** [comment]
I haven't commented on github before, please give me some time



在 2022-02-28 14:24:48，"Richardp" ***@***.***> 写道：




Ok, I'll close it right away, I'm so sorry













At 2022-02-27 17:10:44, "MineGame159" ***@***.***> wrote:

Closed #2096.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by magicfleece** [comment]
> 目前必须在代码中添加主题，这意味着通过插件。

errr  how to close the iuuse

**Comment by Lovecrafts-Cat** [comment]
It has already been colsed a day ago, don't worry.

> > 目前必须在代码中添加主题，这意味着通过插件。
> 
> errr how to close the iuuse
