### ISSUE TITLE
[NEED FEEDBACK] settings cloud sync

### ISSUE THREAD

**Issue by SIMULATAN** [MeteorDevelopment/meteor-client#2099]
### Describe the feature

I was thinking about implementing cloud sync for the settings but I wanted to ask for opinions before doing that, I would add Google Drive and possibly other cloud storage systems. Please state your opinions below!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Can't you just save them in a profile, and if you need to transfer, just copy the folder?
This is so overcompilcated and unnecessary imo.

**Comment by SIMULATAN** [comment]
> Can't you just save them in a profile, and if you need to transfer, just copy the folder?
> This is so overcompilcated and unnecessary imo.

Good luck sending over folders every day, it quickly gets overcomplicated. You might not use different devices often but other people do switch frequently

**Comment by Lovecrafts-Cat** [comment]
Ok, I get your point, but why would you need to change your config so often?
Also, I am sure there already exist software capable of syncing a folder between devices.

**Comment by SIMULATAN** [comment]
> Ok, I get your point, but why would you need to change your config so often?
> Also, I am sure there already exist software capable of syncing a folder between devices.
> 

1) because things change, your freecam is too fast, a bypass changes (for a anarchy server of course), ...
2) yes but they often don't allow you to select an external folder to sync or they don't have proper excludes (to prevent syncing passwords)

**Comment by Lovecrafts-Cat** [comment]
Ok, and how is Meteor supposed to do this syncing for you?

Syncing means data has to be shared, but how can you share your profile data if, let's say, the receiving device is off?

**Comment by SIMULATAN** [comment]
It'll sync it over something like google drive, as stated in the post.
My plan is to utilize their API to upload and download the files, it'll sync the data on start and stop and possibly other events

**Comment by MineGame159** [comment]
In my opinion cloud storage is a feature that only a very small group of people would use and would add a lot of code to be maintained. If we ever decided to have something like this then it would be done on our server through meteor accounts and not relying on multiple different providers.
