### ISSUE TITLE
[Bug] meteor crashing on 1.18.2

### ISSUE THREAD

**Issue by Anonywix** [MeteorDevelopment/meteor-client#2100]
### Describe the bug

I don't know if meteor just needs a new version for 1.18.2 but if it doesn't then I would like to know how to fix it.
Thank you.

### Steps to reproduce

```bash
Just open Minecraft.
```

### Meteor Version

Dev build 0.4.8 1435

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Yes, Meteor needs to be updated, wait for the next dev builds.

**Comment by SIMULATAN** [comment]
Fixed in https://github.com/MeteorDevelopment/meteor-client/commit/7da6caaa59f3c42c30ee33e87ed4a280146c0583
