### ISSUE TITLE
Auto Strip Miner [Suggestion] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2102]
### Describe the feature

When mining diamonds in legit mode of baritone it takes so much time
But if there was autostripminer which automatically Strip Mined,then it would be faster!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Isn't there a Baritone commando to strip mine already?

I am sure I used it once before.

**Comment by procrafter820** [comment]
I didnt find any

**Comment by Justgamer101** [comment]
legit mine should strip mine

**Comment by procrafter820** [comment]
no it doesn't

**Comment by procrafter820** [comment]
> Isn't there a Baritone commando to strip mine already?
> 
> I am sure I used it once before.

Which command???

**Comment by Selbstverliebter** [comment]
dude u are one of the dumbest people on this github page legit ask questions after doing research .b tunnel just strip mines like a tunnel and if u have questions abt baritone than go to barione github page dumbfuck
