### ISSUE TITLE
[Bug] insane fps drops after activeting Infinity miner.

### ISSUE THREAD

**Issue by Selbstverliebter** [MeteorDevelopment/meteor-client#2103]
### Describe the bug

today i  tried infitnity miner for the first time after activating i had 0 fps but i still managed to turn it off. this happpened 3 times in a row and its 100% not my hardware. 

### Steps to reproduce

```bash
tbh idk. it happened to me 3 times and now it seems to be fixed again i dont know how i should reproduce it.
```

### Meteor Version

meteor-client-0.4.7-1398 (dev)

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Try using baritone normally for example `#mine diamond_ore` if it has the same effect.
