### ISSUE TITLE
[Suggestion] Add Blink Cancel

### ISSUE THREAD

**Issue by OctonalXX** [MeteorDevelopment/meteor-client#2104]
### Describe the feature

I saw other clients which contain blink cancel, can we add this as a command?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)
- [X] This wasn't already suggested.
(I have checked every suggestion on github)

**Comment by Justgamer101** [comment]
> What is Blink Cancel

I assume it tps you back instead of doing the blink

kind of useless tho, just walk back to the original position, or just dont screw up ur blink

**Comment by MineGame159** [comment]
@OctonalXX

I will reopen the issue if you are alive.
