### ISSUE TITLE
[Suggestion] add this for bedrock

### ISSUE THREAD

**Issue by rando489** [MeteorDevelopment/meteor-client#2107]
### Describe the feature

add this for bedrock

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by NotAstralYT** [comment]
"bedrock is shit" - mimgam

**Comment by Justgamer101** [comment]
LMAO

**Comment by BookWyrm114** [comment]
I’ve seen some dumb suggestions bc I have all notifications on for this repository but this takes the cake.

**Comment by Lovecrafts-Cat** [comment]
Amazing bro, leme just casually convert thousands of files from Java to C++. (Knowing well that most of the code would have to be completely rewritten).
