### ISSUE TITLE
No antiKB[Suggestion] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2108]
### Describe the feature

Where is anti knockback

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Velocity, next time scroll through the module list.
