### ISSUE TITLE
[Bug] Crash on game startup

### ISSUE THREAD

**Issue by Funtimes909** [MeteorDevelopment/meteor-client#2112]
### Describe the bug

I don't know if this is possible to reproduce as it may be system specific but for me the game crashes using the latest dev build
(At the time of writing this is 0.4.8 - 1441), also something to note whenever I download the latest dev build from the website it ends up downloading version "meteor-client-0.4.8-1435" instead of version 144
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8181306/latest.log)
1

Attached is the crash report, I think it might be something to do with jesus hacks

### Steps to reproduce

```bash
I am unsure if this is reproduceable
```

### Meteor Version

meteor-client-0.4.8-1435

### Minecraft Version

fabric-loader-0.13-1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
It is crashing because you are using an old dev build, and I don't know what to tell you because it downloads 1441 fine for me.
