### ISSUE TITLE
AutoEject[Suggestion] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2113]
### Describe the feature

In mining,autoejects cobblestones/deepslate cobble stone (i mean we can set the blocks to autoeject from inventory)

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by TheRedHippo** [comment]
inventorytweaks module

**Comment by I-Got-You-Dead** [comment]
> inventorytweaks module

I was gonna say that lol

**Comment by procrafter820** [comment]
ok
