### ISSUE TITLE
Xray only renders exposed ores[Suggestion] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2114]
### Describe the feature

This will bypass antixray

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by NotAstralYT** [comment]
just go to freecam and see exposed ores

**Comment by procrafter820** [comment]
> just go to freecam and see exposed ores

It is time taking and it is not possible to go 360 degrees at one time

**Comment by procrafter820** [comment]
Mathax has this feature.....but i use meteor

**Comment by NotAstralYT** [comment]
t
hen steal the code

**Comment by SIMULATAN** [comment]
> t
> hen steal the code

Uno reversing mathax (real!)

**Comment by procrafter820** [comment]
> t hen steal the code
The thing is I don't know java a lot

**Comment by procrafter820** [comment]
> > t
> > hen steal the code
> 
> Uno reversing mathax (real!)

What do you mean

**Comment by Justgamer101** [comment]
this took less than 10 seconds to find https://github.com/tokfrans03/AntiAntiXray

cheating on servers that disallow it is C R I N G E

**Comment by procrafter820** [comment]
> this took less than 10 seconds to find https://github.com/tokfrans03/AntiAntiXray
> 
> cheating on servers that disallow it is C R I N G E

It is outdated

**Comment by procrafter820** [comment]
it is there in meteor i found it now
