### ISSUE TITLE
In HUD it should also show player distance in metres[Suggestion] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2117]
### Describe the feature

In mulitplayer,it should show players distance

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by procrafter820** [comment]
It is there in mathax....port from it..lol

**Comment by MineGame159** [comment]
Player list in HUD can show distance.
