### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Sadminati** [MeteorDevelopment/meteor-client#2120]
### Describe the bug

in meteor client 0.4.4 , When I try to add a crack/premium alt account it doesn't get added. It happens most of the time.
I hope it gets fixed.

### Steps to reproduce

```bash
Whenever you click "add account" it keeps loading and doesn't add the alt.
```

### Meteor Version

0.4.4

### Minecraft Version

1.16.5

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Selbstverliebter** [comment]
they cant update an older version lol there are new versions with it being fixed
