### ISSUE TITLE
Shield/Totem Swapper Hack

### ISSUE THREAD

**Issue by Rberigah** [MeteorDevelopment/meteor-client#2121]
### Describe the feature

A hack that allows the user to use a shield until they reach a certain health, then swaps to a totem of undying.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Selbstverliebter** [comment]
Alrdy exists

**Comment by BestCheeringWinter** [comment]
> Alrdy exists

where?

**Comment by arlomcwalter** [comment]
offhand
