### ISSUE TITLE
Tunnel ESP[Suggestion] 

### ISSUE THREAD

**Issue by fishiewishie** [MeteorDevelopment/meteor-client#2122]
### Describe the feature

Highlight 2 by 1 tunnels useful for hunting bases far out in the nether. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Selbstverliebter** [comment]
Rusherhack has this. 
But still based + W suggestion

**Comment by MineGame159** [comment]
Duplicate of #679.
