### ISSUE TITLE
[Bug]Exit code 1

### ISSUE THREAD

**Issue by Mcplayer69** [MeteorDevelopment/meteor-client#2123]
### Describe the bug

When i launch an unexpected error exit code 1 happens it did not happen yesterday
![Screenshot (81)](https://user-images.githubusercontent.com/101039946/156915901-d49ed829-4f95-4362-984e-a06a24e8c282.png)
.

### Steps to reproduce

```bash
I just launch the game
```

### Meteor Version

0.4.7

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Send the crash log (latest.log file, located in .Minecraft/logs) or we can't know why it crashed.

**Comment by Mcplayer69** [comment]
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8192776/latest.log)

**Comment by Mcplayer69** [comment]
i just played with friends the log is in game
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8192783/latest.log)

**Comment by Lovecrafts-Cat** [comment]
You should send the log after you crash, or else it won't be up to date.
The one you sent is a normal one.

**Comment by Mcplayer69** [comment]
oh fixed it i just updated everything to the newest like the newest dev build api and stuff

**Comment by Lovecrafts-Cat** [comment]
@Mcplayer69 or @MineGame159 Close this issue later 👍
