### ISSUE TITLE
[Bug] Crash when re-opening menu

### ISSUE THREAD

**Issue by GavinGoGaming** [MeteorDevelopment/meteor-client#2124]
### Describe the bug

![image](https://user-images.githubusercontent.com/57292172/156933303-bbad31cb-9294-4a41-a65d-9c6aca43fab4.png)
crash video: https://streamable.com/e/t3bor6 (you cant rlly see it cuz the recording stops but at the end it does crash with the exit code above)

### Steps to reproduce

```bash
1. Join a minecraft server on same dev build
2. Log out
```

### Meteor Version

meteor-client 0.4.8 dev build 1441

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send crash report.

**Comment by GavinGoGaming** [comment]
ok 1 sec

**Comment by GavinGoGaming** [comment]
[crash-2022-03-06_08.58.10-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8193082/crash-2022-03-06_08.58.10-client.txt)

**Comment by GavinGoGaming** [comment]
something in PotionSpoof's deactivate

**Comment by MineGame159** [comment]
Make a new issue if this happens with latest dev build.
