### ISSUE TITLE
[Bug] Killaura ignores pillagers

### ISSUE THREAD

**Issue by Vitalasy** [MeteorDevelopment/meteor-client#2126]
### Describe the bug

Turned on ignore passive and now ka is not attacking the pillagers.

### Steps to reproduce

```bash
1.Set option ignore passive to true
2.Turn on KA near a pillager
3.No
```

### Meteor Version

Latest Dev

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by slam64notch** [comment]
not a bug bro, you gotta config your ka so that it attacks pillagers
pillagers are also (i think) considered somewhat passive so idk

**Comment by Vitalasy** [comment]
> not a bug bro
I am pretty sure i have it configgered correctly
> pillagers are also (i think) considered somewhat passive so idk
Not gonna say anything abt your opinion.

**Comment by slam64notch** [comment]
Just thought of this, maybe you have to anger them or smth to trigger them to attack, making them not passive..?

**Comment by Vitalasy** [comment]
> Just thought of this, maybe you have to anger them or smth to trigger them to attack, making them not passive..?
no.do you even play mc?

**Comment by NakyoykaN** [comment]
With 'Ignore passive' toggled on - no mobs were attacked with KA on.  Examples include Blazes, Wither Skeletons, Zombies, Skeletons, and a bunch of other mobs.  Turning 'Ignore Passive' off makes it so KA works again.

**Comment by BestCheeringWinter** [comment]
I think for some reason mobs that fire projectiles are considered passive.  I don't know about the latest version, but for the 1.18.1 dev-build, I remember kill-aura not working on the wither and ghast when ignore passive was on.  I think it was the same for the ender dragon.
