### ISSUE TITLE
Shows dropped items in ESP[Suggestion] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2129]
### Describe the feature

Shows dropped items in ESP
Will be helpful in finding dropped items etc....
It will not take long enough to add....

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Already possible.

**Comment by procrafter820** [comment]
@MineGame159 How?

**Comment by procrafter820** [comment]
> I understand it might be difficult to click on the esp module and add items to the list

@Mathrandom7910 True! It took me 2357.32 milliseconds to do that(indeed a large number)
