### ISSUE TITLE
[Suggestion] Auto Log Improvements

### ISSUE THREAD

**Issue by Zgoly** [MeteorDevelopment/meteor-client#2132]
### New settings that I want to see:
1. Mode: **Logout** - Leaves from the server
2. Mode: **Command** - Executes a command
_(If selected **Command**, input field appears)_
- Range - (1-100)
- Ignore friends - (On/Off)

### Preview:
![preview](https://user-images.githubusercontent.com/46041044/157306029-203b1cbc-33fe-4e07-982b-30a8708e73c2.png)

### Before submitting a suggestion

- [X] This wasn't already suggested.
(I have checked every suggestion on github)
- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)
- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Selbstverliebter** [comment]
Dude is this a joke? This exact module exists its called auto log bruh shitter.

**Comment by Mathrandom7910** [comment]
lol

**Comment by Zgoly** [comment]
@Selbstverliebter Theres no settings that I described.

**Comment by Zgoly** [comment]
I made this module for myself so yeah

**Comment by Selbstverliebter** [comment]
> I made this module for myself so yeah

ok ratio then
