### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mateoiskool** [MeteorDevelopment/meteor-client#2139]
### Describe the bug

x ray isnt doing any thing if i turn it on

### Steps to reproduce

```bash
pressing the x key on my keyboard
```

### Meteor Version

4.7

### Minecraft Version

1.18

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment]
you gotta give it a keybind
