### ISSUE TITLE
[Suggestion] you should add viaversion (backport)

### ISSUE THREAD

**Issue by HashNotAsh** [MeteorDevelopment/meteor-client#2140]
### Describe the feature

Hello, i would like viaversion, its good and usefull for when you want to backport to a lower version, could you add it into the client?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by NotAstralYT** [comment]
use multiconnect if it updates
use viafabric if multiconnect dont update
