### ISSUE TITLE
[Suggestion] forge meteor

### ISSUE THREAD

**Issue by shittass** [MeteorDevelopment/meteor-client#2142]
### Describe the feature

neednt more describe

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by shittass** [comment]
dont say what

**Comment by NotAstralYT** [comment]
ratio + L bozo + forge sucks for hack clients

**Comment by Vitalasy** [comment]
Fabric is faster for 1.14.4+ than forge so cope.

**Comment by DesiCow** [comment]
ratio + L bozo + forge sucks for hack clients

**Comment by Vitalasy** [comment]
> ratio + L bozo + forge sucks for hack clients

get original.

**Comment by Mathrandom7910** [comment]
gee, how many times has this been suggested
