### ISSUE TITLE
Open settings with hotkey

### ISSUE THREAD

**Issue by Ideenmeister** [MeteorDevelopment/meteor-client#2143]
### Describe the feature

For example you have kill aura bound to k. With this feature you press rshift + k to open your kill aura settings. This way you can configure modules much easier.

This is not my idea. I took this from Kilab Gaming. 
(https://www.youtube.com/watch?v=V6PXzEGWDHw)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Selbstverliebter** [comment]
BASED WW

@MineGame159 add this pwls uwu

nah fr nojoke now this is a rlly good idea and not hard to code prob.

**Comment by Wide-Cat** [comment]
this is now kinda possible, with the .s command now being able to open the relevant modules settings page
