### ISSUE TITLE
No Air Pocket mode for freecam[Suggestion] 

### ISSUE THREAD

**Issue by Th3L1nk** [MeteorDevelopment/meteor-client#2144]
### Describe the feature

a lot of anti xray plugins spoof air pockets and ores to throw off freecam, but the air pockets are usually no bigger than 4-6 blocks of air, so if freecam were to be able to be configured in a way in which small air pockets wouldnt be rendered it would make freecam more effective against such plugins.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Freecam? huh?
