### ISSUE TITLE
[Suggestion] add different clients to spoof in discord presents.

### ISSUE THREAD

**Issue by I-Got-You-Dead** [MeteorDevelopment/meteor-client#2146]
### Describe the feature

e.g. make it so u can choose different presets so u can make it look like you are on lunar client or other popular clients in discord.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SIMULATAN** [comment]
Just don't use the client on servers where you're not allowed to, ez fix

**Comment by I-Got-You-Dead** [comment]
Ik but like if mods can see ur on lunar client they won’t be as suspicious towards you

**Comment by SIMULATAN** [comment]
R u dumb or smth
I just said only use it where you're allowed to, there you also don't have to worry about staff
If you really fear that staff will see you're using meteor and ban you then you're 100% playing on the wrong servers

**Comment by I-Got-You-Dead** [comment]
1: yes
2: smh
