### ISSUE TITLE
[Bug] Client tries to tessellate a null block

### ISSUE THREAD

**Issue by Jonathan274** [MeteorDevelopment/meteor-client#2147]
### Describe the bug

it crashes the game randomly. And someone on discord told me its trying to tessellate a null block
[crash-2022-03-13_11.26.18-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8239276/crash-2022-03-13_11.26.18-client.txt)

### Steps to reproduce

```bash
Idk it happens randomly, but often.
```

### Meteor Version

0.4.8 - 1443

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Nothing to do with Meteor.
