### ISSUE TITLE
[Bug] conflicts with PingList

### ISSUE THREAD

**Issue by Man297** [MeteorDevelopment/meteor-client#2150]
### Describe the bug

If i using PingList, my game crashes

### Steps to reproduce

```bash
just add pinglist
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
What is PingList?

**Comment by MineGame159** [comment]
Also send the crash report.

**Comment by z0rug1** [comment]
Try using Meteor clients "Better TAB" module for ping in TAB.

**Comment by Man297** [comment]
https://modrinth.com/mod/pinglist
[crash.zip](https://github.com/MeteorDevelopment/meteor-client/files/8242215/crash.zip)
