### ISSUE TITLE
[Suggestion] Self Destuct

### ISSUE THREAD

**Issue by Bobisawesome07** [MeteorDevelopment/meteor-client#2152]
### Describe the feature

add a self destruct module to meteor client so if somebody got screen shared they can self destruct so they don't get caught

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
`.panic` command

**Comment by I-Got-You-Dead** [comment]
I think he means like u have to restart the game to reenable tho (disable everything e.g. gui, modules, hud, keybinds)

**Comment by SIMULATAN** [comment]
just don't use it on servers where you're not allowed to, ez

**Comment by I-Got-You-Dead** [comment]
:l

**Comment by I-Got-You-Dead** [comment]
I swear u just copy and pasted that

**Comment by SIMULATAN** [comment]
I didn't

**Comment by I-Got-You-Dead** [comment]
-_-

**Comment by Texbio** [comment]
I think I suggested this before and it got denied... maybe meteor rejects?

**Comment by I-Got-You-Dead** [comment]
Maybe ig
