### ISSUE TITLE
[Bug] Font rendering inconsistent 

### ISSUE THREAD

**Issue by obyyx** [MeteorDevelopment/meteor-client#2154]
### Describe the bug

When you turn off custom font in meteor client the default Minecraft font is very distorted and does not render properly. You can remedy it slightly by changing the GUI scale but it still doesn't look correct. 

### Steps to reproduce

```bash
Turn off custom font
```

### Meteor Version

Latest Dev

### Minecraft Version

1.18.2

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Funtimes909** [comment]
1. Set a keybind
2. Does the server have anti-xray

**Comment by RickyTheRacc** [comment]
bruh this is a valid issue

**Comment by arlomcwalter** [comment]
> bruh this is a valid issue

you are the only issue around here

**Comment by arlomcwalter** [comment]
> bruh this is a valid issue

you are the only issue around here

**Comment by arlomcwalter** [comment]
> bruh this is a valid issue

you are the only issue around here

**Comment by arlomcwalter** [comment]
> bruh this is a valid issue

you are the only issue around here
