### ISSUE TITLE
[Suggestion] hello i just wanted to suggest that you add the triggerbot

### ISSUE THREAD

**Issue by amvrAsd** [MeteorDevelopment/meteor-client#2155]
### Describe the feature

Triggerbot like wurst or atistois 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Kill Aura has a setting to only attack when you are looking at the entity.

**Comment by amvrAsd** [comment]
but to make it look legal it is better to triggerbot

**Comment by I-Got-You-Dead** [comment]
Yea nah

**Comment by Mathrandom7910** [comment]
> but to make it look legal it is better to triggerbot

just dont hack on servers that disallow it
