### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by iimportforfun** [MeteorDevelopment/meteor-client#2158]
### Describe the bug

For me, I am not able to use kill aura. I'm using fabric 1.18 and when I check the box to enable it, it just does not work. 

### Steps to reproduce

```bash
I just doesn't not work. Any way it could work?
```

### Meteor Version

Latest

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment]
negative iq moment

**Comment by RegalAether** [comment]
what entities did you enable kill aura for? right click it and edit settings
