### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RouZong** [MeteorDevelopment/meteor-client#2167]
### Describe the bug

If change world,Inventory Tweaks will drop error items then loading items.

### Steps to reproduce

```bash
change world or server,reload player data will trigger.
```

### Meteor Version

meteor-client-0.4.8-1435

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
That's just how X Carry works, nothing can be done about it.
