### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MrNotBanana1221** [MeteorDevelopment/meteor-client#2168]
### Describe the bug

Hi I love meteor client but recently I've been having these crashes when, I'm wondering if I can get some help ill send a screenshot in..
![Fabric Loader 0 13 3 18_03_2022 8_52_34 PM](https://user-images.githubusercontent.com/101867537/158981004-299f0d04-d1c6-4f7d-b7c1-afbdf7b06c28.png)

There you go 

### Steps to reproduce

```bash
So if I go to the minecraft launcher I press play it starts to load then It does not load and shows a error report
```

### Meteor Version

meteor-client-0.4.7

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MrNotBanana1221** [comment]
If its a version problem how do I get the 1.17.1 version of meteor I'm not that smart with this type of stuff so sorry if its a useless report

**Comment by Lovecrafts-Cat** [comment]
> If its a version problem how do I get the 1.17.1 version of meteor I'm not that smart with this type of stuff so sorry if its a useless report

As the error says, the current version of Meteor requires Minecraft 1.18.1 (1.18.2 if you use Dev-Builds).
***
If you want to use meteor on older servers, then you need to:
1. Make an instance on 1.18.1
2. Add the [Multiconnect](https://www.curseforge.com/minecraft/mc-mods/multiconnect/download/3597246/file) mod
3. Join any server

**Comment by MrNotBanana1221** [comment]
> > If its a version problem how do I get the 1.17.1 version of meteor I'm not that smart with this type of stuff so sorry if its a useless report
> 
> As the error says, the current version of Meteor requires Minecraft 1.18.1 (1.18.2 if you use Dev-Builds).
> 
> If you want to use meteor on older servers, then you need to:
> 
> 1. Make an instance on 1.18.1 (That will use Java 17)
> 2. Add the [Multiconnect](https://www.curseforge.com/minecraft/mc-mods/multiconnect/download/3597246/file) mod
> 3. Join any server

oki thanks but what do you mean by instance like fabric loader 1.18.1 or just download the 1.18.1 version on the launcher and thanks for your time.

**Comment by Lovecrafts-Cat** [comment]
> oki thanks but what do you mean by instance like fabric loader 1.18.1 or just download the 1.18.1 version on the launcher and thanks for your time.

![image](https://user-images.githubusercontent.com/52252627/158984977-8935fe0a-3974-41df-9072-bb857c5d2d14.png)
Instances are created when you click on the button with name and version written on it (to the left of the big green button)
So you can click there, and make a fabric 1.18.1 instance following [this guide](https://fabricmc.net/wiki/player:tutorials:install_mcl:windows)

**Comment by MrNotBanana1221** [comment]
> > oki thanks but what do you mean by instance like fabric loader 1.18.1 or just download the 1.18.1 version on the launcher and thanks for your time.
> 
> ![image](https://user-images.githubusercontent.com/52252627/158984977-8935fe0a-3974-41df-9072-bb857c5d2d14.png) Instances are created when you click on the button with name and version written on it (to the left of the big green button) So you can click there, and make a fabric 1.18.1 instance following [this guide](https://fabricmc.net/wiki/player:tutorials:install_mcl:windows)

Okay! Thanks for your help and time
