### ISSUE TITLE
[Bug] killaura ignores a bunch of mobs on 1.18, latest dev build

### ISSUE THREAD

**Issue by system69-e** [MeteorDevelopment/meteor-client#2169]
### Describe the bug

killaura simply ignores shulkers, zombies and spiders, ender dragon,endermen that are not agro'd (the ones I noticed)

### Steps to reproduce

```bash
try killing any of the mobs mentioned above
```

### Meteor Version

0.4.8 1449

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by SIMULATAN** [comment]
did you enable them in the entities setting

**Comment by system69-e** [comment]
> did you enable them in the entities setting

obviously
