### ISSUE TITLE
reseting everything

### ISSUE THREAD

**Issue by tympanicblock61** [MeteorDevelopment/meteor-client#2170]
### Describe the bug

keeps reseting all of the modules and profiles and it doesnt use the profile nbt in the meteor client folder 

### Steps to reproduce

```bash
idk
```

### Meteor Version

1448

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
Try deleting your meteor folder entirely and starting over
