### ISSUE TITLE
[Suggestion] Hand view swing speed

### ISSUE THREAD

**Issue by p9sq** [MeteorDevelopment/meteor-client#2171]
### Describe the feature

So for the swing speed setting in the hand view module, I've noticed that it edits the swing speed for every player and I would suggest to make it so then the swing speed only applies to your player/character only instead of applying to every player.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SIMULATAN** [comment]
💀 oops I forgor that's a thing
Only tested it in SP lol

**Comment by MineGame159** [comment]
Fixed in 5cdf9046f6b6670207f960746121ef001bcaeba1.
