### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by quinten023** [MeteorDevelopment/meteor-client#2172]
### Describe the bug

Ghost hand, opening containers through wall doesn’t work tried to open a container with only 1 block between me and the chest chest doesn’t open 

### Steps to reproduce

```bash
click on chest otherside of wall didn’t open
```

### Meteor Version

meteor 0.4.8-1449

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in aba2bdfc8cc00a1ec03f7a5f7ac5c15c039943fa.
