### ISSUE TITLE
[Suggestion]  Highway builder doesn't utilize pickaxes in invintory once the pickaxes in the hotbar are used up. 

### ISSUE THREAD

**Issue by CadaverThrasher** [MeteorDevelopment/meteor-client#2177]
### Describe the feature

Give Highway Builder the option to use all of the inventory and not just the hotbar. If it's supposed to be that way already, then I guess this is a bug report. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Wide-Cat** [comment]
Unable to reproduce
