### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Boxedbox1976** [MeteorDevelopment/meteor-client#2180]
### Describe the feature

=====================
  Add  IRC / Internet Relay Chat
=====================

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by NotAstralYT** [comment]
why

**Comment by I-Got-You-Dead** [comment]
yea... why?

**Comment by I-Got-You-Dead** [comment]
although it would be cool for like a dc bot ig

**Comment by SIMULATAN** [comment]
Who the fuck uses irc

**Comment by Boxedbox1976** [comment]
==================================================================================
     A reason I think it would be worth making a IRC. The Internet Relay Chat / IRC would make it easier to talk to other people 
                  using Meteor. You could even have your own ranking system. [note] Sorry for not replying instantly.
==================================================================================

**Comment by SIMULATAN** [comment]
6 min is still considerably fast, NW
Well personally I always felt like IRC is the useless chat nobody uses and it's always the first I turn off in a new client. I don't know the experience of other people tho. I guess we'll just wait for giamams opinion abt this

**Comment by I-Got-You-Dead** [comment]
It would be useful for private messages for friends on meteor which would be nice

**Comment by I-Got-You-Dead** [comment]
> or use this program that almost everyone uses nowadays called... discord :O

Yep

**Comment by Starmania** [comment]
Good suggestion bc I can't keep Discord open, but if someone do that, copy the implementation of an existing mod (so no one will be bad of AntiCheat detecting easily)

**Comment by Mathrandom7910** [comment]
> Good suggestion bc I can't keep Discord open
bruh its a chat app
> copy the implementation of an existing mod
so skid a public src one?
> so no one will be bad of AntiCheat detecting easily
how tf will a chat be detected by ac
