### ISSUE TITLE
[Bug] crashing on fabric 1.18.2

### ISSUE THREAD

**Issue by walksanatora** [MeteorDevelopment/meteor-client#2181]
### Describe the bug

it crashes
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8321409/latest.log)
.

### Steps to reproduce

```bash
install latest client from downloads
crash
```

### Meteor Version

I cant tell because it crashes before i can start

### Minecraft Version

1.18.2

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by M1zxn** [comment]
use latest dev build if you on 1.18.2

**Comment by walksanatora** [comment]
just built latest and diffrent errors
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8321471/latest.log)

now fabric actually starts. but it spits a ton of errors at me

**Comment by M1zxn** [comment]
can you send a picture of your mods list in mods folder?

**Comment by walksanatora** [comment]
> can you send a picture of your mods list in mods folder?

![image](https://user-images.githubusercontent.com/47339836/159416430-39658817-a976-4a39-9cbd-ca50199a353d.png)

**Comment by walksanatora** [comment]
the `meteor-client-0.4.8-all.jar` is a symbolic link to `meteor-client/build/libs/meteor-client-0.4.8-all.jar`

**Comment by M1zxn** [comment]
https://meteorclient.com/download?devBuild=latest

**Comment by walksanatora** [comment]
i have no idea why the downloaded build worked when the compiled one did not. but thanks now it works
