### ISSUE TITLE
[Suggestion] Right and left autoclicker

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#2185]
### Describe the feature

I'd like to suggest a option to the autoclicker. I found 2 options to this. The first is to make a quick button to change from left to right and same in the other way, or make 2 bindable button for left and right autoclicker.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by DesiCow** [comment]
Already implemented as of #2825
