### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LemonNotLime** [MeteorDevelopment/meteor-client#2186]
### Describe the bug

ESP renders the shader
 next to the mob
![creeper](https://user-images.githubusercontent.com/91822759/159994912-16023d49-8ebe-456f-aab0-bc7aaae68853.png)

### Steps to reproduce

```bash
just have esp on and look at a mob thru walls or from far
```

### Meteor Version

meteor dev build 1452

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
#1259
