### ISSUE TITLE
[Suggestion] Phase Hacks

### ISSUE THREAD

**Issue by fireblade2534** [MeteorDevelopment/meteor-client#2187]
### Describe the feature

I suggest that you add phase hacks. They allow you to basically turn off player collision with blocks.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
They have been patched for a long time, so it feels like a useless addition.
Also I think there may be some addons for that.

**Comment by fireblade2534** [comment]
can you give me an example of an addon?

**Comment by Lovecrafts-Cat** [comment]
Try and check https://anticope.ml/ for add-ons, maybe you'll find some there

**Comment by fireblade2534** [comment]
none that work

**Comment by fireblade2534** [comment]
(for phase)

**Comment by RickyTheRacc** [comment]
Cope!

**Comment by SIMULATAN** [comment]
> none that work

See? If they don't work anyway why should meteor add it
