### ISSUE TITLE
[Suggestion] Mojang Alts

### ISSUE THREAD

**Issue by paranormalshrimp** [MeteorDevelopment/meteor-client#2188]
### Describe the feature

I can see that in the accounts section there's no option for a Mojang alt. Mojang alts still work although not through their launcher.  Also the Microsoft thing says "You may now close this page" everytime I use it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by TyraVex** [comment]
I don't know why they got rid of it...
Most alts are Mojang related, i don't understand why this feature was removed

**Comment by MeisterX9** [comment]
the feature was removed because not all mojang accounts supposedly work and if the feature was not removed the support would be overwhelmed.

**Comment by arlomcwalter** [comment]
> I don't know why they got rid of it...
> 
> Most alts are Mojang related, i don't understand why this feature was removed

mojang accounts were supposed to have stopped working a while ago when the migration deadline happened but microsoft didn't discontinue them for some unknown reason.

**Comment by MeisterX9** [comment]
but why was the feature removed if it still works ?
meteor was a very good client but since the feature is gone it's useless for me.

**Comment by MeisterX9** [comment]
> > I don't know why they got rid of it...
> > Most alts are Mojang related, i don't understand why this feature was removed
> 
> mojang accounts were supposed to have stopped working a while ago when the migration deadline happened but microsoft didn't discontinue them for some unknown reason.

but why was the feature removed if it still works ?
meteor was a very good client but since the feature is gone it's useless for me.

**Comment by TyraVex** [comment]
> > > I don't know why they got rid of it...
> > > Most alts are Mojang related, i don't understand why this feature was removed
> > 
> > 
> > mojang accounts were supposed to have stopped working a while ago when the migration deadline happened but microsoft didn't discontinue them for some unknown reason.
> 
> but why was the feature removed if it still works ? meteor was a very good client but since the feature is gone it's useless for me.

https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher

**Comment by arlomcwalter** [comment]
> > > I don't know why they got rid of it...
> 
> > > Most alts are Mojang related, i don't understand why this feature was removed
> 
> > 
> 
> > mojang accounts were supposed to have stopped working a while ago when the migration deadline happened but microsoft didn't discontinue them for some unknown reason.
> 
> 
> 
> but why was the feature removed if it still works ?
> 
> meteor was a very good client but since the feature is gone it's useless for me.

just use authme with meteor lmao, tfw you use meteor only for the account switcher

**Comment by paranormalshrimp** [comment]
mix it with bleach bc it still has mojang alt support and it’s fairly good (sexy ass itemESP)
