### ISSUE TITLE
[Bug] crashes on load

### ISSUE THREAD

**Issue by tympanicblock61** [MeteorDevelopment/meteor-client#2190]
### Describe the bug

crashes when loading all the addons i have on 

### Steps to reproduce

```bash
use more than 8 addons and try to save and load the profile
```

### Meteor Version

1452

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by M1zxn** [comment]
log?

**Comment by NotAstralYT** [comment]
if you have more addons on a certain amount when press shift and some modules tab go over the screen it crashes the game

**Comment by MineGame159** [comment]
Send crash report
