### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JxyzStompz** [MeteorDevelopment/meteor-client#2194]
### Describe the bug

when i download meteor client and put it in mods folder i try to launch it and it crashes and fabric gives me an error and if i try to go back into minecraft launcher it doesnt open and i have to redownload it

### Steps to reproduce

```bash
Launching meteor
```

### Meteor Version

1.18.2

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
U got the fabric api?

**Comment by JxyzStompz** [comment]
i did i redownloaded it after it crashed then i couldnt open it

**Comment by I-Got-You-Dead** [comment]
Do you have the right version of fabric?

**Comment by JxyzStompz** [comment]
> Do you have the right version of fabric?

yes 1.18.2

**Comment by JxyzStompz** [comment]
> Do you have the right version of fabric?

thus one 
![image_2022-03-30_023709](https://user-images.githubusercontent.com/102656232/160788835-fbacf4dd-3680-40bb-82dc-c7318e84a2ac.png)

**Comment by JxyzStompz** [comment]
i think its the fabric api that causes it not to work bc i just tried reinstalling it and when i put fabric api in it doesnt wanna open

**Comment by JxyzStompz** [comment]
i figured out the problem it was trying tto launch another client which was 1.18.1 so it caused a crash i deleted that client from the folder and it worked sorry for the false report
