### ISSUE TITLE
[Bug] Incompatibility/crash with Durability Viewer

### ISSUE THREAD

**Issue by zogared** [MeteorDevelopment/meteor-client#2196]
### Describe the bug

Crash on startup with https://modrinth.com/mod/durabilityviewer, fabric api and meteor. Crash did not happened on 1.18.1 when using fabric 0.12.12 (still crashed with 0.13 and above). 
Logs: https://www.toptal.com/developers/hastebin/apanomaruy.properties

### Steps to reproduce

```bash
Launch Minecraft with durabilityviewer, fabric api and meteor installed.
```

### Meteor Version

Latest dev

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
doesn't happen on latest
