### ISSUE TITLE
[Bug] Error: A JNI error has occurred please check your installation and try again.

### ISSUE THREAD

**Issue by pecocksir** [MeteorDevelopment/meteor-client#2199]
### Describe the bug

 Error: A JNI error has occurred please check your installation and try again.
![image](https://user-images.githubusercontent.com/95301666/161274826-dcfa1f2e-0fd3-43d8-887e-6b46acc03998.png)

After clicking ok: A Java Exception has occurred.
![image](https://user-images.githubusercontent.com/95301666/161274889-c8cde879-4c96-41fc-9fb2-531da20788e3.png)

### Steps to reproduce

```bash
I downloaded the meteor client v0.4.7 and when I opened it it crashed
```

### Meteor Version

0.4.7

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by pecocksir** [comment]
sry im dumb i forgot u put meteor in the mods folder

**Comment by M1zxn** [comment]
https://meteorclient.com/download?devBuild=latest use this one if you on 1.18.2
