### ISSUE TITLE
[Suggestion] Add OverWorld bed aura

### ISSUE THREAD

**Issue by simulatorwinner** [MeteorDevelopment/meteor-client#220]
you guy's should add Overworld bed aura which works through blocks, so its super easy to destroy beds in bed wars

**Comment by seasnail8169** [comment]
Use nuker or freecam to destroy blocks through walls, also reminder that meteor is not intended for use on non anarchy-style servers.

**Comment by supakeks** [comment]
Maybe make a mode in nuker to only break beds? (the vanilla way, not clicking it once)

**Comment by simulatorwinner** [comment]
yea, that could too work
