### ISSUE TITLE
[Bug] Crash 

### ISSUE THREAD

**Issue by JPinNYC** [MeteorDevelopment/meteor-client#2200]
### Describe the bug

[Crash Report](https://pastebin.com/rTB0pkep)
![Mods](https://user-images.githubusercontent.com/80540615/161343366-65ce1c0d-74de-4590-b355-f7ce23530940.png)
Before this crash a few comes before it:
Exit code -1
Exit Code -1073741819

### Steps to reproduce

```bash
Launch minecraft a couple of times, a couple of crashes come before it. Described in "Describe the bug"
```

### Meteor Version

4.8 1452

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by NotAstralYT** [comment]
wtf is venom hack

**Comment by JPinNYC** [comment]
Nothing that caused the crash

**Comment by JPinNYC** [comment]
Do you have any solution to fix it?

**Comment by RickyTheRacc** [comment]
LOL YOU'RE RETARDED

**Comment by JPinNYC** [comment]
If your so smart how do I fix it?

**Comment by NotAstralYT** [comment]
update mortar client

> If your so smart how do I fix it?

**Comment by JPinNYC** [comment]
I have

**Comment by MineGame159** [comment]
Looks like your Meteor config got corrupted somehow. You will have to delete your `.minecraft/meteor-client` folder as I can't tell exactly which file it is. Or you can go one by one.

**Comment by JPinNYC** [comment]
ok ty
