### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by UnknownLemonade** [MeteorDevelopment/meteor-client#2205]
### Describe the bug

![image](https://user-images.githubusercontent.com/96620548/161385656-1ad5d5ef-a211-4ba3-b07f-8235682ace71.png)
Game crash (1.18.2, Dev Build  0.4.8 - 1459)

### Steps to reproduce

```bash
I don't quite know. I went to %appdata% with Win+R and then reset my gamma back to 1.0 in the .minecraft folder at settings.txt. After restarting the game it crashed after a few seconds.
```

### Meteor Version

Dev  Build 0.4.8 - 1459

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send the full crash report.
