### ISSUE TITLE
[Bug] The game crashes because of autoeat

### ISSUE THREAD

**Issue by Emmily006** [MeteorDevelopment/meteor-client#2208]
### Describe the bug

Game crash

[crash-2022-04-05_14.39.26-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8418178/crash-2022-04-05_14.39.26-client.txt)

### Steps to reproduce

```bash
I'm not quite sure about this, but it's something that happens when I use autoeat
```

### Meteor Version

0.4.8-1461

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Emmily006** [comment]
I can't even start Meteor now, it keeps crashing.
[crash-2022-04-05_14.46.28-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8418201/crash-2022-04-05_14.46.28-client.txt)

**Comment by Mathrandom7910** [comment]
remove all other mods, relaunch
