### ISSUE TITLE
The ability to switch back to your original account when you add a second/third account to the accounts tab [Suggestion] 

### ISSUE THREAD

**Issue by Skygamer10** [MeteorDevelopment/meteor-client#2215]
### Describe the feature

What this means is when you add/login to a second account, the first one you signed into the launcher with is in the list. 

This annoys me when I log in with a cracked account and then can't login to my original Microsoft account

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
You have to add the original account too, we can't just switch back.

**Comment by RickyTheRacc** [comment]
devastating!
