### ISSUE TITLE
[Bug] Click Tp Broken with Snow

### ISSUE THREAD

**Issue by simulatorwinner** [MeteorDevelopment/meteor-client#222]
Version:  0.4.0

Problem: If u turn on click tp and click on block it will tp to that block as long as in reach, but if the block u click is a snow lair that tiny slip of snow, if u hold click tp on that lair, it will make tp u 1 block higher, just try to hold click on snow lair if u didn't get what I said.

**Comment by RedCarlos26** [comment]
Is this somewhat fixable?

**Comment by MineGame159** [comment]
Fixed in bd0b849d005d4c765fb7f0205fe88b9b33ca15b3
