### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Abelirreften** [MeteorDevelopment/meteor-client#2221]
### Describe the bug

When I use the Slippy Module at max slippness, get inside a boat and start spinning, the moment I get out of the boat the game crashes. Im using the mods shown in the photo. I don't know if this mods cause any problems.
![image](https://user-images.githubusercontent.com/103505774/162956096-ad955170-325c-4ed2-84f0-fc968d78927d.png)
All the mods are updated to the latest version. I've tried this bug in multiplayer only. But I've been able to reproduce it several times.
The launcher gives me this error: (It's in spanish, but the error code is the same as in english)
![image](https://user-images.githubusercontent.com/103505774/162956878-f2c424b1-6174-4b72-94aa-a96482367dd8.png)

### Steps to reproduce

```bash
Activate the Slippy Module. Set the slippness at 1.100
Get in a boat and start spinning for 10 seconds. Get out of the boat and the game should crash.
You may have to do this twice to crash the game.
```

### Meteor Version

meteor-client-0.4.8

### Minecraft Version

Minecraft 1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
whats the point of having autoreconnect, elytra chestplate swapper, shulkerbox tooltip, and in game account switcher when all of those are in meteor?

**Comment by Abelirreften** [comment]
Well, I use meteor client when I play on anarchy servers. But when I play
on smps or survival without hacks I use this mods. I know it sounds
strange. Sometimes I remove meteor client of the mods folder so I use those
mods instead. This time I forgot to change those mods for meteor. So I was
using all of them 😅

**Comment by Mathrandom7910** [comment]
you should just use multimc to save urself the hassle of moving mods around

**Comment by MineGame159** [comment]
Cann't reproduce so unless you send a long there is nothing I can do.

**Comment by Abelirreften** [comment]
Hi. This is the latest log after reproducing the bug. As I said in the
first gmail, the log just stops showing messages when the game crashes. Idk
if this works like this or if it should show some other information of the
crash error. I could reproduce it again so here you have a video of me
doing the bug. So you can see that in fact it crashes.
I cropped the video so you don't have to watch until the crash error pops
up.

Thanks for the attention and the help.
 bandicam 2022-04-27 08-28-32-224.mp4
<https://drive.google.com/file/d/164zeo9D_MhGniQoDzQZTqjAA_RDTavQ4/view?usp=drive_web>
