### ISSUE TITLE
[Suggestion] Auto Eat Healing hearts

### ISSUE THREAD

**Issue by Kingster90** [MeteorDevelopment/meteor-client#2222]
### Describe the feature

Adding an feature to autoeat that when it detects that you have dropped an amount of hearts it will heal by eating

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
It does bozo, cause when you loose hearts your hunger goes down.

**Comment by Texbio** [comment]
you should be able choose both
example 1: you take 10 hearts of fall dmg and should eat asap
example 2: you have 20 hearts but you don't want to eat unless you cant sprint anymore

**Comment by I-Got-You-Dead** [comment]
That’s what auto gap is for bozo

**Comment by Mathrandom7910** [comment]
"bozo"

**Comment by I-Got-You-Dead** [comment]
Mhm
