### ISSUE TITLE
[Bug] Combat Info not showing up in HUD

### ISSUE THREAD

**Issue by DJj123dj** [MeteorDevelopment/meteor-client#2223]
### Describe the bug

When I enable "combat info" in the HUD it never shows up, even if there is a player next to me.

## extra information
**Operating system:**
macOS Monterey (12.3.1)

**mods installed**
- fabric-api
- meteorclient
- litematica
- malilib (for litematica)
- viafabric
- worldedit

## screenshots
**These are my settings**
![settings](https://user-images.githubusercontent.com/80536295/163676618-acf389c6-1507-4279-9524-823492c87baf.png)
**This is in the HUD editor**
![part 1](https://user-images.githubusercontent.com/80536295/163676621-9e0765a6-c830-4fc9-b74f-81c3a8c146a5.png)
**And this is in the game, it doesn't show up**
![part 2](https://user-images.githubusercontent.com/80536295/163676624-1759fa7d-c459-41c5-b1cf-20138dcf08c7.png)

### Steps to reproduce

```bash
1: go to HUD in the ClickGUI
2: enable "combat info" on the HUD
3: stand next to someone
4: it doesn't show up
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
can you show a screenshot where there is a player nearby on your screen
i should add that it only shows when there is a player to show

**Comment by DJj123dj** [comment]
Yes, I do not have minecraft open at the moment.  So I'll send it later.

**Comment by DJj123dj** [comment]
Here is an image from a private server with my friend, here it doesn't show up.

I have discovered that if I join a large server (like hypixel), it works just fine.
Maybe does it not work on a specific type of server.

**The image**
![image](https://user-images.githubusercontent.com/80536295/163685131-71e9315a-443e-4353-8ac6-23effa04bec3.png)

**Comment by SnivyLlama** [comment]
They are in survival mode and not friended on meteor client?

**Comment by DJj123dj** [comment]
wait thats it
they are friended with me.
Thats the problem

btw sorry for bothering with "not a bug"
