### ISSUE TITLE
Can't delete death waypoints

### ISSUE THREAD

**Issue by Spicymang04** [MeteorDevelopment/meteor-client#2228]
### Describe the bug

I can't delete death waypoints.

### Steps to reproduce

```bash
Die with "waypoints" enabled
```

### Meteor Version

v0.4.9 build #1470

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 9166c3a6b8060eda3fe1cc4e4cbdc0e123d20af9.
