### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Oskar2601** [MeteorDevelopment/meteor-client#2230]
### Describe the bug

using the latest fabric loader, 1.18.2 fabric api and meteor 4.8 (i also tried the dev version 4.9-1470) and i get frozen on the "loading terrain" screen while all modules are toggled off.

### Steps to reproduce

```bash
load into a world in 1.18.2 with meteor 4.8 or 4.9 and fabric api 1.18.2 with latest fabric loader
OS: Windows 11
```

### Meteor Version

4.8 and 4.9 - 1470

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
I dont think you need fabric api for meteor
