### ISSUE TITLE
Auto Shield

### ISSUE THREAD

**Issue by BestCheeringWinter** [MeteorDevelopment/meteor-client#2235]
### Describe the feature

Automatically tries to block projectiles but also attacks(mostly of mobs) using a shield.  Briefly moves the viewer angle to block the hit and quickly returns back to the rotation before.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by tympanicblock61** [comment]
has been suggested before and denied

**Comment by MineGame159** [comment]
Duplicate of #1808
