### ISSUE TITLE
Set baritone max fall height with no fall

### ISSUE THREAD

**Issue by DannyParker0001** [MeteorDevelopment/meteor-client#224]
Idk if this should be a toggleable option or what
When the no fall module is enabled, baritones 'MaxFallHeightNoWater' should be set to 255, it can speed up its pathing a little bit

**Comment by jiaaluo** [comment]
I guess there should be a variable in nofall if this was to be added.

**Comment by RedCarlos26** [comment]
It could just be an option to toggle in the nofall settings as you said, and it could just make baritone ignore fall height, or set it to 256.
