### ISSUE TITLE
[Suggestion] Compatibility with Feather Client

### ISSUE THREAD

**Issue by BoxDevelopment** [MeteorDevelopment/meteor-client#2241]
### Describe the feature

I've been wanting you use Meteor on Feather Client since it works on my crappy little laptop that I use and I feel like it would benefit other players aswell,
If you guys need i can give a Feather Client Invite Code so you guys can test it.

Thanks in advanced!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
> Just use the original optimization mods and not a mod that copied others.

No but feather client is just one mod if it had copy paste it would be more then one!

**Comment by MineGame159** [comment]
:cope_nn:

**Comment by Mathrandom7910** [comment]
Feather client doesn't even use fabric. This is a dumb issue.
