### ISSUE TITLE
No Blindness[Suggestion] 

### ISSUE THREAD

**Issue by fireblade2534** [MeteorDevelopment/meteor-client#2242]
### Describe the feature

It would be a module that allows you to remove the blindness effect. So when you have it, there is no overlay.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Isn't this already a feature, either in NoRender, or some other module?

**Comment by fireblade2534** [comment]
Not that i know of

**Comment by I-Got-You-Dead** [comment]
It’s in no render. I’m 99% sure it’s there cause I use it lol
