### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by erPARHPOkOzgvL3QYks** [MeteorDevelopment/meteor-client#2243]
### Describe the feature

Make meteor client compatible with optifabric and optifine
heres download links for both files:
https://www.curseforge.com/minecraft/mc-mods/optifabric
https://optifine.net/downloads

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Tutorial: how to show off the fact you didn't bother reading the [FAQ](https://github.com/MeteorDevelopment/meteor-client/wiki#how-to-use-meteor-with-optifine) or try to search for [better alternatives](https://lambdaurora.dev/optifine_alternatives/).

And people wonder why the Discord chat had to be locked behind a role...
