### ISSUE TITLE
Soul Sand Breaks in Nuker

### ISSUE THREAD

**Issue by sussyboiiii** [MeteorDevelopment/meteor-client#2244]
### Describe the bug

when using nuker in a ssv as an exemple and you walk over soul sand it breaks the soul sand below probably becasue its not a full block but its hitbox or sth

### Steps to reproduce

```bash
just walk over soul sand with nuker and a shovel
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
a related issue occurs with scaffold on soul sand.

**Comment by arlomcwalter** [comment]
its because soul sand isn't a full block

**Comment by sussyboiiii** [comment]
> 

read the fucking report

**Comment by sussyboiiii** [comment]
believe cant really be fixed easily
