### ISSUE TITLE
[Suggestion] Add carpet blocks to spawn proofer

### ISSUE THREAD

**Issue by miassassin** [MeteorDevelopment/meteor-client#2246]
### Describe the feature

Carpet blocks stop spawns.  Consider adding it to list of available blocks for spawn proofer.

private boolean isNonOpaqueBlock(Block block) {
        return block instanceof AbstractButtonBlock ||
            block instanceof SlabBlock ||
            block instanceof AbstractPressurePlateBlock ||
            block instanceof TransparentBlock ||
            block instanceof CarpetBlock ||
            block instanceof TripwireBlock;

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Added in 239a935eaf76144b78b83e237e75518cf287fad7.
