### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by undyuuang** [MeteorDevelopment/meteor-client#2247]
### Describe the feature

Add hack on and off button so you can quickly turn them on and off

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Truly exceptional and aetonishing

**Comment by I-Got-You-Dead** [comment]
> Truly exceptional and astonishing

agreed

**Comment by MineGame159** [comment]
💀
