### ISSUE TITLE
trap feature[Suggestion] 

### ISSUE THREAD

**Issue by Jhid445** [MeteorDevelopment/meteor-client#2248]
### Describe the feature

can you add a feature where you trap a player in obi or any selected blocks. :)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Mathrandom7910** [comment]
https://github.com/MeteorDevelopment/meteor-client/blob/a4bbe0bf3d0bad1ee19287f7a12f824399f53f52/src/main/java/meteordevelopment/meteorclient/systems/modules/combat/AutoTrap.java

**Comment by Jhid445** [comment]
thx
