### ISSUE TITLE
spin/ troll hacks [Suggestion] 

### ISSUE THREAD

**Issue by Jhid445** [MeteorDevelopment/meteor-client#2249]
### Describe the feature

like a spin hack like csgo and other just funny shit 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
True

**Comment by Jhid445** [comment]
What do you mean closed
