### ISSUE TITLE
Incompatible with Satin

### ISSUE THREAD

**Issue by zeroeightysix** [MeteorDevelopment/meteor-client#225]
Meteor, when loaded with [Satin](https://github.com/Ladysnake/Satin) (a fabric library to sanely manage shaders) will throw the main menu screen into an infinite loop - a loading screen will appear after the initial one finishes (and keeps doing that)

Here the [log](https://pastebin.ubuntu.com/p/Q5wpJrzCQf/).

This is most likely due to the nasty [mixin](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/minegame159/meteorclient/mixin/JsonGlProgramMixin.java#L18) you use to fix minecraft's loading locations.
Consider relying on Satin instead - it does its job quite well and ensures compatibility with other mods that are also interested in using shaders, such as KAMI.

**Comment by Walaryne** [comment]
+1 on this, there's a few mods out there other than just util clients that use Satin, like Blur.

**Comment by MineGame159** [comment]
In the log you provided it shows that we are using @Redirects which I purposely changed to @ModifyVariable so it is compatible with other mods that do this. I am pretty sure its now compatible with KAMI and others.

**Comment by zeroeightysix** [comment]
Ah - you're right. I tested using the latest release. It does work using the latest commit. Looks like you were ahead of me.
