### ISSUE TITLE
[Bug] Incompatible with MiniHUD on Quilt loader only

### ISSUE THREAD

**Issue by ProfessorSniff** [MeteorDevelopment/meteor-client#2250]
### Describe the bug

On the latest dev build of Meteor and the latest release of MiniHUD, Minecraft will crash if both are loaded. 
No mods other than Fabric API / QSL, MaLiLib, Meteor, and MiniHUD are installed. 

[crash log](https://0x0.st/oAj6.txt)

### Steps to reproduce

```bash
The game crashes when both mods are loaded, but not when Meteor is not installed or MiniHUD is not installed (but MaLiLib is still installed)
The same mods loaded via Fabric Loader work fine. 
Using QSL instead of FAPI makes no difference. 
I am using PolyMC (MultiMC) launcher, and have not tested with the Vanilla launcher.
```

### Meteor Version

latest dev (0.4.9-1474) and latest git (239a935eaf76144b78b83e237e75518cf287fad7)

### Minecraft Version

1.18.2 Quilt

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Quilt is unsupported, use fabric

**Comment by ProfessorSniff** [comment]
well it works fine when i don't use minihud, so ill live without it
