### ISSUE TITLE
[Suggestion] vulcan bypass

### ISSUE THREAD

**Issue by Jhid445** [MeteorDevelopment/meteor-client#2252]
### Describe the feature

can you guys find a way to bypass vulcan 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
Just don’t hack on servers where it’s not allowed (or just turn everything down lol)
