### ISSUE TITLE
[Suggestion] Autosteal re-work; making it useable

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#2254]
### Describe the feature

I would rather have auto steal + auto dump be in a seperate module from inventory tweaks called Auto Steal. I will be referring to auto steal as its own module.

1. Instead of the auto dump part being its own thing, add a toggle button that changes if you want to put the items in your inventory (normal auto steal) or dump them on the floor (when the button is on, it should dump items on the floor).
1.5. Add some options to configure the rotation of dumped items, like the "Rotation" module.

1. Add a whitelist blacklist filter to Auto Steal.

3. Add a initial delay slider before starting to move items.

4. FIX auto steal and auto dump because they don't work with the latest devbuild of meteor (tested on single player so that might be the issue?)

5. Add a toggle button that changes if you want to close the container when you are done.

6. Add an option that opens chests (there needs to be a way to filter which containers) in a range (adjustable slider) from the player. This feature of being able to open chests within a range needs to have its own toggle button to disable/enable this and also include a toggle button for opening chests through walls.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by ThebestkillerTBK** [comment]
#4 is already fixed rn.

**Comment by ThebestkillerTBK** [comment]
6th suggestion in rejects chest aura.
