### ISSUE TITLE
[Bug] Dev Builds download error

### ISSUE THREAD

**Issue by 0Ariel0** [MeteorDevelopment/meteor-client#2258]
### Describe the bug

I was trying to install the old dev build because my pc doesn't run 1.19 so I would install an old one but I can't always say that the site doesn't exist or it's unavailable I already tested my anti virus and it's not. Please try to put the old dev build back!

### Steps to reproduce

```bash
1- Go to the download site
2- Choose an old dev build
3- Website unavailable or disabled
4- it is not the anti virus
```

### Meteor Version

v0.4.8 #1435

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
As stated in the [wiki](https://github.com/MeteorDevelopment/meteor-client/wiki#how-do-i-use-meteor-on-older-minecraft-versions), old versions aren't available, and only the latest devbuilds are kept for testing purposes.

**Comment by 0Ariel0** [comment]
> As stated in the [wiki](https://github.com/MeteorDevelopment/meteor-client/wiki#how-do-i-use-meteor-on-older-minecraft-versions), old versions aren't available, and only the latest devbuilds are kept for testing purposes.

but how am i going to use it? (not via fabric)

**Comment by Lovecrafts-Cat** [comment]
Play Minecraft 1.18.2
Download the latest Meteor dev build,
Download Viafabric
Ta-da, you can join older servers now
