### ISSUE TITLE
[Bug] The text shadow of player names, renders in front of the text.

### ISSUE THREAD

**Issue by 0xEnjoy** [MeteorDevelopment/meteor-client#2261]
### Describe the bug

Player names, when using minecraft's default font and the Nametag module, have inverted colors.

### Screenshot of the issue:
![screenshot](https://user-images.githubusercontent.com/104784056/166508784-a9a4df37-01ae-4b4d-8272-f9619ec993e4.png)
### Example of how it should look like:
![screenshot2](https://user-images.githubusercontent.com/104784056/166512335-c07f2d48-ba1e-4cc0-8670-2922041dff09.png)

### Steps to reproduce

```bash
Enable the Nametag module.
Disable custom font, from the GUI settings.
Look at a players name.
```

### Meteor Version

0.4.9 (Build from source) 

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
its just an issue with projection, its not inverted it just sometimes renders the shadow infront of the foreground text so it appears inverted
