### ISSUE TITLE
[Bug] game crashes (exit code -1) when using jesus mode on lava

### ISSUE THREAD

**Issue by articiceberg97** [MeteorDevelopment/meteor-client#2267]
### Describe the bug

game crashes as soon as lava is touched with jesus mode enabled and world is unloadable until loaded without meteor client 

### Steps to reproduce

```bash
1. enable jesus mode
2. jump on lava
3. r.i.p game
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
Attach log.

**Comment by articiceberg97** [comment]
> Attach log.

 [here](https://pastebin.com/z8VVjHmp)

**Comment by arlomcwalter** [comment]
not a meteor issue as far as i can tell
