### ISSUE TITLE
[Suggestion] add a auto water bucket

### ISSUE THREAD

**Issue by articiceberg97** [MeteorDevelopment/meteor-client#2268]
### Describe the feature

add a auto water bucket that places water under you to stop you from taking fall damage

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by NotAstralYT** [comment]
nofall exist

**Comment by articiceberg97** [comment]
> there is a mode for it in no fall

anti cheats patch no fall but they cant easily patch a auto water bucket

**Comment by arlomcwalter** [comment]
bruh, literally there is a mode to waterbucket in no fall retard

**Comment by realremkarl** [comment]
damn, in meteor client in NoFall there is a function called bucket, but it doesn't work at all :(
