### ISSUE TITLE
[Suggestion] More Killaura and Scaffold Options

### ISSUE THREAD

**Issue by cyrilYCP** [MeteorDevelopment/meteor-client#2269]
### Describe the feature

Add legit rotations, and rotation speed to scaffold
add lookspeed to killaura.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
No, die

**Comment by NotAstralYT** [comment]
kill aura alredy have legit rotations

**Comment by NotAstralYT** [comment]
+ ratio + kys
