### ISSUE TITLE
Multiple Hack Clients

### ISSUE THREAD

**Issue by lukaz34** [MeteorDevelopment/meteor-client#2270]
### Describe the bug

I can launch meteor client without any issues, but when i put multiple hack clients in the mods folder it just crashes!
I have tried removing the meteor client jar file from the mods folder and then i could play wurst and liquidbounce client together. Could you please add support for multiple hack clients!

### Steps to reproduce

```bash
When i launch Minecraft
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Have you considerd not mixing clients?
Also, providing a crashlog would be helpful `.minecraft/logs/latest.log`.
