### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by James0293** [MeteorDevelopment/meteor-client#2271]
### Describe the bug

XRAY is not working, it will enable but just will not actually xray, however u can still disable/enable it 

### Steps to reproduce

```bash
Enable XRAY
```

### Meteor Version

Latest DEV BUILD

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
Thank you for giving lots of info such as enabled modules or other mods.

**Comment by hellidox** [comment]
send logs
