### ISSUE TITLE
[Suggestion] Make autotool not mine leaves with a tool, unless it is a hoe or shears

### ISSUE THREAD

**Issue by u12bdragon** [MeteorDevelopment/meteor-client#2273]
### Describe the feature

for some reason, autotool will mine leaves with a tool. This is not faster, to my knowledge, unless using shears or a hoe. If it is (marginally) faster, please add an option to turn it off. I don't want to destroy my stone sword's durability just to mine leaves at a fraction of the speed faster. This also falls under the wider category of autotool forcing the use of a tool for some blocks, such as mining pumpkins with a sword when the player doesn't have an axe.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Mathrandom7910** [comment]
swords are slightly faster

**Comment by RacoonDog** [comment]
autotool using a sword to mine sugar cane 😐
