### ISSUE TITLE
[Bug] Autoeat crashes your game

### ISSUE THREAD

**Issue by Kolotheegg** [MeteorDevelopment/meteor-client#2274]
### Describe the bug

so i turnt on Auto eat and my game crashed 

### Steps to reproduce

```bash
If i turn on autoeat in any mod
```

### Meteor Version

newest one

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
send logs
