### ISSUE TITLE
[Bug] Game freezes on "Loading terrain"

### ISSUE THREAD

**Issue by XS493** [MeteorDevelopment/meteor-client#2275]
### Describe the bug

Whenever I try to join a singleplayer world or a multiplayer server, the game freezes on "Loading terrain". I've checked and it doesn't happen without meteor in the mods folder. Meteor is the only mod which is being used and I've tried both the latest stable release and dev builds. The fabric loader version is 1.13.3.

### Steps to reproduce

```bash
Join any singlayer or multiplayer game
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2 Fabric Loader 1.13.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
send logs

**Comment by lostlaptop** [comment]
i've had the same thing, you are in the world. and you can die, time does pass (singleplayer)

**Comment by lostlaptop** [comment]
> send logs

[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8648705/latest.log)
here's mine, i've had the same issue, i've fixed it before, but i forgot how, i tried unintalling and reinstalling, didn't fix it

**Comment by lostlaptop** [comment]
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8648713/latest.log)

**Comment by lostlaptop** [comment]
it's fixed if you delete your meteor-client dile in .minecraft, and reinstall the jar from the website

**Comment by lostlaptop** [comment]
it's fixed if you delete your meteor-client dile in .minecraft, and reinstall the jar from the website

> ### Describe the bug
> Whenever I try to join a singleplayer world or a multiplayer server, the game freezes on "Loading terrain". I've checked and it doesn't happen without meteor in the mods folder. Meteor is the only mod which is being used and I've tried both the latest stable release and dev builds. The fabric loader version is 1.13.3.
> 
> ### Steps to reproduce
> ```shell
> Join any singlayer or multiplayer game
> ```
> 
> ### Meteor Version
> 0.4.8
> 
> ### Minecraft Version
> 1.18.2 Fabric Loader 1.13.3
> 
> ### Operating System
> Windows
> 
> ### Before submitting a bug report
> * [x]  This bug wasn't already reported.
>   (I have checked every bug report on github)
> * [x]  This is a valid bug.
>   (I am able to reproduce this on the latest dev build)

**Comment by lostlaptop** [comment]
also your discord info doesn't work

**Comment by Mathrandom7910** [comment]
edit comments instead of making 20
