### ISSUE TITLE
a few days ago i started using meteor client, then i wanted to add an alt and i couldnt

### ISSUE THREAD

**Issue by roistav** [MeteorDevelopment/meteor-client#2276]
### Describe the bug

before i was using meteor i used wurst and i couldhave added accounts that are not from microsoft (i think they are not) and it would add them. now i cant add my alt, can you add a mojang account or something else so for example you would say the email and the password and it would search for an account across all platfroms you can log into minecraft from

### Steps to reproduce

```bash
idk just adding an alt and it not working
```

### Meteor Version

latest lol

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
You cant use mojang accounts after march 10th 2022. It is may 8th 2022

**Comment by Anonymous17532** [comment]
it still works
