### ISSUE TITLE
off hand crash[Bug] 

### ISSUE THREAD

**Issue by mattias209313** [MeteorDevelopment/meteor-client#2277]
### Describe the bug

i clicked off hand crash and crashed myself, i have tried to redownload metoer, but it still crashes me non stop

### Steps to reproduce

```bash
when i clicked off hand crasher it kept on crashing me. I coundnt stop it. Now if i have meteor in my files, iwont be able to play .
Please help me
```

### Meteor Version

4.8

### Minecraft Version

1.81.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
you can open the gui in the main menu and disable it
