### ISSUE TITLE
Cyrillic characters [Bug] 

### ISSUE THREAD

**Issue by Nekiplay** [MeteorDevelopment/meteor-client#2279]
### Describe the bug

Cyrillic characters don't work in text fields

### Steps to reproduce

```bash
Meteor UI
```

### Meteor Version

0.4.9-1473

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Sersoid** [comment]
Duplicate of #333
