### ISSUE TITLE
[Suggestion] Add a player radar list that can be on the side of the screen

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#228]
![Capture d’écran 2021-02-08 150428](https://user-images.githubusercontent.com/58893097/107274893-0841ea00-6a1f-11eb-92a9-be73b2ddb3f9.jpg)

**Comment by RedCarlos26** [comment]
Added in 0.4.2 build 619.

**Comment by Declipsonator** [comment]
> 
> 
> Added in 0.4.2 build 619.

If it was added, then why is this still open?

**Comment by RedCarlos26** [comment]
I don't know my guy

**Comment by Declipsonator** [comment]
I mean, you made it. You should be able to close it
