### ISSUE TITLE
[Suggestion] Auto Dump exclude from hotbar

### ISSUE THREAD

**Issue by 5alydotnet** [MeteorDevelopment/meteor-client#2281]
### Describe the feature

Inventory tweaks -> Auto Dump, It lacks simple feature which is the possibility to exclude hotbar items from autodumping/dumping in general, quite the way you can do it for Auto Drop. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
y e s

**Comment by arlomcwalter** [comment]
literally exists 
![image](https://user-images.githubusercontent.com/17166139/173209628-b63a8792-4a80-486e-8570-f9532da6c0a0.png)
