### ISSUE TITLE
[Bug] Command bug

### ISSUE THREAD

**Issue by PokerMC** [MeteorDevelopment/meteor-client#2287]
### Describe the bug

I dont know if this is a bug but i cant for some reason do "/" commands like "/spawn". When i type "/" it becomes red and an error comes up. its really annoying when im trying to do "/home" and "/spawn". hope you can help me. :)

### Steps to reproduce

```bash
It just says "Unknown or incomplete command, see below for error at position 0: <--[HERE]"
```

### Meteor Version

0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
The server doesn't have /spawn and /home commands

**Comment by I-Got-You-Dead** [comment]
> The server doesn't have /spawn and /home commands

You beat me to it lol

**Comment by Mathrandom7910** [comment]
The issue better not be this dumb.
