### ISSUE TITLE
[Bug] Notebot not working

### ISSUE THREAD

**Issue by soshimee** [MeteorDevelopment/meteor-client#2289]
### Describe the bug

Notebot places noteblocks in a 5 block radius, but it seems to be able to only set it up in 1 block radius for some reason.

### Steps to reproduce

```bash
Enable notebot and most songs will not work.
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by D-a-r-n-o-l-d** [comment]
I have the same issue on 1.20.6 meteor 0.5.7-2090

![2024-06-16_01 06 53](https://github.com/MeteorDevelopment/meteor-client/assets/124857402/a2401779-211e-4e65-887e-5ee2f52197d6)
