### ISSUE TITLE
[Suggestion] AutoGap (or AutoEat idk) when down to a certain health

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#229]

**Comment by ikearefrigerator** [comment]
this is already a module in meteor :/

**Comment by RedCarlos26** [comment]
Yes, but you don,t have an option to eat at a certain health.

**Comment by ikearefrigerator** [comment]
> Yes, but you don't have an option to eat at a certain health.

yes you do, its all configurable under auto eat. right click the module and configure it there.
also auto gap eats a gap when the effect runs out, not when you get down to a certain health amount

**Comment by ikearefrigerator** [comment]
not sure why you would want to eat at a certain health either. eating at a certain hunger value seems better by far

**Comment by seasnail8169** [comment]
Auto Gap does this, health threshold for regular auto eat is pointless as it isn't related to health.
