### ISSUE TITLE
[Bug] Xray glitch?

### ISSUE THREAD

**Issue by Haggisisgood** [MeteorDevelopment/meteor-client#2293]
### Describe the bug

Hi, my Xray is not working. When I activate it it doesn't allow me to see through blocks and instead removes all of the darkness around my area. I don't have stone, dirt, etc in my whitelist other than the usual ores.    

### Steps to reproduce

```bash
I just simply press my bind.
```

### Meteor Version

0.4.9 dev build

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [ ] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
OMG STFU WITH THE XRAY BUG AND JUST SET UR FUCKING CONFIGS

**Comment by I-Got-You-Dead** [comment]
anyway...

just set the opacity

**Comment by Haggisisgood** [comment]
My opacity is at one. I've also tried setting it to the max and back to one. But to no avail.

**Comment by I-Got-You-Dead** [comment]
Right…

**Comment by I-Got-You-Dead** [comment]
U got sodium

**Comment by I-Got-You-Dead** [comment]
?

**Comment by Haggisisgood** [comment]
I have no clue what that is so no.

**Comment by Mathrandom7910** [comment]
> OMG STFU WITH THE XRAY BUG AND JUST SET UR FUCKING CONFIGS

This seems to be an actual bug, but people are physically incapable to do the simple task of searching for duplicates.

**Comment by I-Got-You-Dead** [comment]
> 

Right…
