### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Cedri4** [MeteorDevelopment/meteor-client#2295]
### Describe the bug

If i type .fov 160 or higher when i sprint it return the gam
Proof:
![Minecraft Screenshot 2022 05 16 - 20 04 40 22](https://user-images.githubusercontent.com/93396286/168655511-68707181-6aa8-4c60-81d8-410a81f1ea93.png)

### Steps to reproduce

```bash
With fov 160 by .fov 160
```

### Meteor Version

0.4.9-1477

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Makrennel** [comment]
"return the gam"

what?

**Comment by Lovecrafts-Cat** [comment]
You do realize that increasing the FOV past a certain value will invert the camera, right?

Why would you need to go higher than the Minecraft maximum anyways

**Comment by RickyTheRacc** [comment]
Lmaoooo

**Comment by arlomcwalter** [comment]
nothing to do with meteor, vanilla behaviour

**Comment by I-Got-You-Dead** [comment]
> You do realize that increasing the FOV past a certain value will invert the camera, right?
> 
> Why would you need to go higher than the Minecraft maximum anyways

It’s 180 because of a 180 degree angle if you get what I mean

**Comment by Cedri4** [comment]
am not good at game
