### ISSUE TITLE
[Bug] Chams high performance impact

### ISSUE THREAD

**Issue by ThebestkillerTBK** [MeteorDevelopment/meteor-client#2298]
### Describe the bug

If you use chams, fps drops from 100 to 50

### Steps to reproduce

```bash
1. enable chams
2. your game start to lag
```

### Meteor Version

0.4.9-1477

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RegalAether** [comment]
pc issue, get sodium lithium and starlight

**Comment by ThebestkillerTBK** [comment]
> pc issue, get sodium lithium and starlight

no u i got em all

**Comment by RickyTheRacc** [comment]
Shit pc issue then

**Comment by Mathrandom7910** [comment]
If you get low fps with the spectral arrow then its ur pc. Same thing used to happen with me when I had a 9 year old pc, going from 60 fps to ~20.

**Comment by ThebestkillerTBK** [comment]
yeah, i tested it and fps wont drop until you face a lot of entities

**Comment by Mathrandom7910** [comment]
just go ahead and close it, it's not a meteor client issue. Use box esp for better performance.

**Comment by ThebestkillerTBK** [comment]
ik but its still got low efficiency and need to be recoded

**Comment by I-Got-You-Dead** [comment]
> > pc issue, get sodium lithium and starlight
> 
> no u i got em all
> 
> its still lagging when i turned all chams option off, just doin nothing frame drop from 100 to bout 60

its ca not chams bozo

**Comment by Eccys** [comment]
without chams I get ~130 fps, and with chams I get ~90fps, with phosphor, sodium, and lithium i get 150+ fps and with chams i get 110 to 130 depending on how many entities there are
