### ISSUE TITLE
[Bug] Cannot get regex chat filtering to work

### ISSUE THREAD

**Issue by rjbarber** [MeteorDevelopment/meteor-client#2299]
### Describe the bug

I'm trying to filter out chat spammers. Nothing 've tried in the Regex filter has worked. Here's an example:
![image](https://user-images.githubusercontent.com/10442659/169368747-52a5bb6a-5052-4c73-a9d1-a7bed6a3cb46.png)

The regex filter I'm using is this:
/.*[jJ]oin [tT]eam [vV]uz.*/gm

![BetterChatSettings](https://user-images.githubusercontent.com/10442659/169372305-9c81a95c-4fb6-435b-930c-6342e12e92c3.jpg)

Using multiple RegEx testing apps, the following string is captured with the above filter every time:
"Any stuff <The_Blackfish> 12568 Join Team Vuz Today and any other stuff"

No matter what adjustments I make to the RegEx code, it does not filter out the annoying spam messages in chat that match.

Any ideas?

### Steps to reproduce

```bash
Turn on Regex Filter in Better Chat
Enter /.*[jJ]oin [tT]eam [vV]uz.*/gm into the filter.
Nothing happens. Messages continue to flood in as depicted in the attached image.
```

### Meteor Version

meteor-client 0.4.8

### Minecraft Version

fabric-loader-0.13.3-1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Click the plus button next to the text field to add it as a string to search for

**Comment by rjbarber** [comment]
It had to be that easy, yet so damn difficult.

**Comment by rjbarber** [comment]
Thanks RickyTheRacc!!!
