### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by AlenOrbanic** [MeteorDevelopment/meteor-client#2302]
### Describe the bug

Meteor is not compatible with another mod in mc fabric called gate of babylon ( https://www.curseforge.com/minecraft/mc-mods/gate-of-babylon ) how do i make the client work
i dont need the other mod to work i only need meteor client
but to join an mc server i want, i will need both

### Steps to reproduce

```bash
when i launch mc with both of the mods, unkown error happens.
```

### Meteor Version

newest

### Minecraft Version

also newest (1.18.2.)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Mathrandom7910** [comment]
1. no crash logs
2. ur likely cheating on a server that disallows it
