### ISSUE TITLE
[Suggestion] Faster autoclicker

### ISSUE THREAD

**Issue by soshimee** [MeteorDevelopment/meteor-client#2303]
### Describe the feature

Currently, autoclicker can only get up to around 20 CPS, but external autoclickers can get up to 500~1000 CPS. It would be nice if the autoclicker module had the option to have that high CPS option.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
Welp ur fucking dumb

**Comment by arlomcwalter** [comment]
there are 20 ticks in a second, therefore you can only do a max of 20 interactions per second

**Comment by soshimee** [comment]
In a single tick, you can do multiple interactions per second. I know, you CANNOT place more than 20 blocks per second, but you CAN activate a lever 100 times a second. Redstone can also be powered multiple times per tick.

**Comment by I-Got-You-Dead** [comment]
Not how it works bud

**Comment by soshimee** [comment]
Another example: with a redstone lag machine, you CAN lag out a server with 200+ CPS but not with a meteor autoclicker.

**Comment by I-Got-You-Dead** [comment]
Smh

**Comment by I-Got-You-Dead** [comment]
Just use timer

**Comment by soshimee** [comment]
Timer existed, never thought of it. I guess it works.

**Comment by I-Got-You-Dead** [comment]
Lmao

**Comment by I-Got-You-Dead** [comment]
> Timer existed, never thought of it. I guess it works.

The code in auto clicker can ONLY run as fast as the ticks, so by using timer you can speed up the ticks

**Comment by Mathrandom7910** [comment]
there is no limits on spamming packets, even if ur running 20 tps on client and server.

**Comment by soshimee** [comment]
I guess it just loops every tick and checks if enough time is passed, so it just can't be done with current code.

**Comment by soshimee** [comment]
Could work by using multiple loops?

**Comment by arlomcwalter** [comment]
shush
