### ISSUE TITLE
Tracers don't point to bots [Suggestion] 

### ISSUE THREAD

**Issue by fireblade2534** [MeteorDevelopment/meteor-client#2305]
### Describe the feature

Add a option in tracers so they won't point to player bots.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Define player bot please?

**Comment by fireblade2534** [comment]
like fake players

**Comment by Lovecrafts-Cat** [comment]
What's a fake player tho?
All players are real, whether they are commanded through a bot or a keyboard

**Comment by fireblade2534** [comment]
do you know the plugin citizens?
