### ISSUE TITLE
[Suggestion] NoRender nametags 

### ISSUE THREAD

**Issue by awesomeusername69420** [MeteorDevelopment/meteor-client#2306]
### Describe the feature

Add an "Entity Nametags" option in No render to disable rendering of chosen entity's nametags (Useful for those mobs with really long nametags that lag/crash your game)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
added
