### ISSUE TITLE
[Suggestion] 308 Negra Arroyo Lane, Albuquerque, New Mexico 87104

### ISSUE THREAD

**Issue by epearl-tv** [MeteorDevelopment/meteor-client#2308]
### Describe the feature

KILL YOURSELF MINEGAME!!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by unfidelity** [comment]
this is a good issue

**Comment by Lovecrafts-Cat** [comment]
Oh look, a clown 🤡

**Comment by unfidelity** [comment]
> Oh look, a clown 🤡

shut up

**Comment by AquarDev** [comment]
i love this issue

**Comment by Lovecrafts-Cat** [comment]
> > Oh look, a clown 🤡
> 
> shut up

How about you shut me up big boy? 😉

**Comment by AquarDev** [comment]
shut up

**Comment by epearl-tv** [comment]
> > > Oh look, a clown 🤡
> > 
> > 
> > shut up
> 
> How about you shut me up big boy? 😉

run the credentials noname faggot fr

**Comment by AquarDev** [comment]
> > > > Oh look, a clown 🤡
> > > 
> > > 
> > > shut up
> > 
> > 
> > How about you shut me up big boy? 😉
> 
> run the credentials noname faggot fr

@everyone

**Comment by unfidelity** [comment]
> > > Oh look, a clown 🤡
> > 
> > 
> > shut up
> 
> How about you shut me up big boy? 😉

how old are u

**Comment by arlomcwalter** [comment]
amazing

**Comment by GildedS** [comment]
coping

**Comment by RickyTheRacc** [comment]
Astounding

**Comment by I-Got-You-Dead** [comment]
💀
