### ISSUE TITLE
I suggest we add a server for meteor client users to play on without having any worries of getting banned

### ISSUE THREAD

**Issue by PurPurMan** [MeteorDevelopment/meteor-client#2309]
### Describe the feature

e

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
amazing

**Comment by Declipsonator** [comment]
meteor anarchy reboot

**Comment by Lovecrafts-Cat** [comment]
"It will be great, it will be huge, and THEY will pay for it!"

**Comment by Mathrandom7910** [comment]
pvp.meteorclient.com lol
