### ISSUE TITLE
Self destruct [Suggestion] 

### ISSUE THREAD

**Issue by ItzNaFle** [MeteorDevelopment/meteor-client#2310]
### Describe the feature

You should add a self destruct feature. When you enable it, it deletes the mod from the folder and disables the whole client so the game just goes back to normal. Though i'm not really sure if its possible to delete the mod while the game is running so you can make it just hide the client completely but the guy who is screensharing can still find it in the mods folder. And i know this feature is completely useless for 2b2t players and most of the client's users are 2b2t players but a self destruct feature would be really useful for small servers that don't know how to screenshare properly.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Bro, you can't be this dumb...
Don't you see any issue with your idea of doing this?

**Comment by ItzNaFle** [comment]
> Bro, you can't be this dumb... Don't you see any issue with your idea of doing this?

No, I don't.

**Comment by RickyTheRacc** [comment]
Maybe one of the most braindead issues ever opened

**Comment by Lovecrafts-Cat** [comment]
> No, I don't.

This is literally a non-issue.
There's no way for a mod to delete itself after the game closes or while it's running.

Also, how about you don't go and use unfair advantage mods on servers that don't allow them?
