### ISSUE TITLE
[Suggestion] Go to coordinates using vclip & hclip

### ISSUE THREAD

**Issue by soshimee** [MeteorDevelopment/meteor-client#2316]
### Describe the feature

There could be a command that uses vclip and hclip rapidly using pathfinding like baritone and gets you to certain coordinates / entity.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
This would be patched literally anywhere with an anticheat

**Comment by hellidox** [comment]
fun fact: no ac servers exist

**Comment by maxsupermanhd** [comment]
Better would be just a special command that looks up vclip positions and highlights them like `.roofclip` optionally setting baritone target, pathing, breaking blocks through bedrock to make space and performing clip.

**Comment by Mathrandom7910** [comment]
> fun fact: no ac servers exist

And those servers are not dead, and really fun to play on!!!

**Comment by soshimee** [comment]
Could add a way for baritone to use hclip and vclip to move faster, would have similar results.

**Comment by maxsupermanhd** [comment]
To be clear: clipping is not faster than just cranking speed, essentially if you use timer and fine-tune everything you will get same results. Having baritone hclip everywhere will **not** help him go faster because clip functions are designed to *clip* through the blocks and not travel around, when player sends position updates it will just trigger speed limitation because it will think that player is moving at hclip_distance per tick

**Comment by soshimee** [comment]
It's just as a way to allow baritone to pathfind through blocks (if the server allows) and move faster (speed makes baritone go in lava and glitch out and stuff). Also pathfind and vclip+hclip is easier to use because it will automatically find the closest route and never make mistakes like a real player using fly. It's also useful when moving quickly on ground since speed+step doesn't always work (like under trees for example).

**Comment by soshimee** [comment]
> Better would be just a special command that looks up vclip positions and highlights them like `.roofclip` optionally setting baritone target, pathing, breaking blocks through bedrock to make space and performing clip.

Also, this is not what I want, then I can only set Y coordinates, it should also allow X and Z coordinates.
