### ISSUE TITLE
[Suggestion] Capitalize "Minecraft"

### ISSUE THREAD

**Issue by CodeDoc537** [MeteorDevelopment/meteor-client#2323]
### Describe the feature

![Screenshot 2022-05-24 2 39 35 PM](https://user-images.githubusercontent.com/62254737/170136928-f76f1dda-f8aa-4d42-96d0-9b4e8aa181e8.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Weigurde** [comment]
the absolute most based suggestion, period

**Comment by arlomcwalter** [comment]
fulfilled
