### ISSUE TITLE
[Suggestion] Add cancel button to loading terrain

### ISSUE THREAD

**Issue by soshimee** [MeteorDevelopment/meteor-client#2324]
### Describe the feature

Some servers purposefully (or unpurposefully) trap the player in "loading terrain," and that requires a restart for the player to fix. I think meteor could fix this softlock.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by DesiCow** [comment]
https://modrinth.com/mod/forcecloseworldloadingscreen
