### ISSUE TITLE
Incrase Pickup range

### ISSUE THREAD

**Issue by IcySoCool** [MeteorDevelopment/meteor-client#2327]
### Describe the feature

This feature could be match with vein miner.
 So when mining some stuff with vein miner, the drop would be stuck in some places which is not reachable. Pickup range would increase the range we pickup anything so it would be much more effective when using vein miner to afk mine/grind. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by soshimee** [comment]
Maybe teleport to the items and return when done, but can't collect items stuck in blocks.

**Comment by IcySoCool** [comment]
Wdym?

**Comment by Lovecrafts-Cat** [comment]
There's no real way to magically increase that range 🤔 
Mods can do it, but that functionality usually relies on the server IIRC.

**Comment by CodeDoc537** [comment]
> There's no real way to magically increase that range 🤔 Mods can do it, but that functionality usually relies on the server IIRC.

This exactly, there is nothing a client can do to increase item pickup range
