### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by InvalidAccount69** [MeteorDevelopment/meteor-client#2328]
### Describe the feature

Add ClickGui In Main Menu

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
This is literally a feature just click the normal button to open it

**Comment by Lovecrafts-Cat** [comment]
Knowing this new generation of kids is going to have to deal with serious issues scares me...

**Comment by CodeDoc537** [comment]
smh

**Comment by Theboiboi8** [comment]
smh, I decide to check the issues on this client after like 2 months and this is what  I see… Truly pains me.
