### ISSUE TITLE
[Bug] no render doesnt work

### ISSUE THREAD

**Issue by TaxEvasiqn** [MeteorDevelopment/meteor-client#2330]
### Describe the bug

the entities option for no render gets rid of the entities on my screen however my fps still drops as if there still are 5322 bees on my screen

### Steps to reproduce

```bash
summon a lot of entities
turn on no render and select said entity
watch as your screen freezes
```

### Meteor Version

dev build 1480

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by z0rug1** [comment]
Is the world you're playing/testing in Singleplayer/hosted on your PC or a Multiplayer server?

**Comment by TaxEvasiqn** [comment]
server

**Comment by maxsupermanhd** [comment]
Having that many bees in entity render distance will drop your fps regardless of having norender

**Comment by TaxEvasiqn** [comment]
any reason it would?

**Comment by maxsupermanhd** [comment]
Your client does not only rendering, it also processes animation and position and reads packets from server trying to keep your local world in sync with server. Even if you are not rendering them they are still existing and processing each tick. Some modules also look for entities (if enabled I hope) and if you have a lot it spirals out of control.
