### ISSUE TITLE
[Suggestion] Auto Disconnect when low health

### ISSUE THREAD

**Issue by fireblade2534** [MeteorDevelopment/meteor-client#2331]
### Describe the feature

When your health is below a set threshold it will automatically disconnect you from a server. It will also auto disable once it has disconnected.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
This already exists retard

**Comment by fireblade2534** [comment]
what module?

**Comment by SzymekNoob** [comment]
auto log
