### ISSUE TITLE
[Bug] Game Crashed When using slippery module

### ISSUE THREAD

**Issue by ItsIsntItsKeera** [MeteorDevelopment/meteor-client#2333]
### Describe the bug

I was experiment slippery module by set value of slippery to 0, then i realize 0 slippery make me stuck and cant more, i attempt to use flight module to fly out of area, then when i land on the floor, it crashe
[crash-2565-05-30_13.46.57-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8796160/crash-2565-05-30_13.46.57-client.txt)
d

### Steps to reproduce

```bash
1. set slippery module to 0 slippery
2. fly above the block a bit
3. disable flight module to make player land on the block
4. crashed
```

### Meteor Version

0.4.9 1480

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by soshimee** [comment]
Looks like a vanilla bug...

**Comment by TheRedHippo** [comment]
It is a vanilla bug, landing while walking when your movement speed attribute is 0 will crash your game.
