### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by murzen2009** [MeteorDevelopment/meteor-client#2335]
### Describe the feature

I can't download meteor client for 1.16.5

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
How about you try and read the FAQ before opening issues?
