### ISSUE TITLE
Zip file

### ISSUE THREAD

**Issue by SuhrudJoshi** [MeteorDevelopment/meteor-client#2336]
### Describe the feature

Can you add a ZIP file for it?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by SIMULATAN** [comment]
???

**Comment by RickyTheRacc** [comment]
???
