### ISSUE TITLE
[Bug] crash with nbt copy/better chat

### ISSUE THREAD

**Issue by TaxEvasiqn** [MeteorDevelopment/meteor-client#2340]
### Describe the bug

game crashes when you use .nbt copy also i looked at the crash log it says something about the betterchat module prob anti spam

### Steps to reproduce

```bash
have better chat on maybe
hold an item
type .nbt copy
type .nbt copy again
wait for your game to crash
```

### Meteor Version

1480

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
can you please send a crash log, can't reproduce
