### ISSUE TITLE
[Suggestion] Seed Miner

### ISSUE THREAD

**Issue by SzymekNoob** [MeteorDevelopment/meteor-client#2345]
### Describe the feature

Interacting with the baritone so that it can dig at the base of the seed

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by cyrilYCP** [comment]
please, kill yourself 🙏
