### ISSUE TITLE
[Suggestion] Auto drop items with large data.

### ISSUE THREAD

**Issue by energy11a** [MeteorDevelopment/meteor-client#2347]
### Describe the feature

When Bookbans are used usually multiple shulkerboxes are used. I suggest adding a module making it so that when first large item is picked up it is immediately dropped and if you have items in your inventory those are used to fill up all available slots.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
Smort

**Comment by Eccys** [comment]
it's pretty useless, that usually happens dur to server plugins making them so heavy, not the actual items.

**Comment by I-Got-You-Dead** [comment]
> it's pretty useless, there are already a so many plugins to stop that from happening.. I tried in vanilla with a shulker and 1 was enough to ban me.. same as chunkbans

Same thing with me but still, it was a good idea
