### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by uoffle** [MeteorDevelopment/meteor-client#2348]
### Describe the bug

everytime i open the new dev build (0.4.9) it immediately crashes.

### Steps to reproduce

```bash
when i open the game
```

### Meteor Version

0.4.9

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
> ### Minecraft Version
> 
> 1.19

You stoopid...
You do realise that if Baritone is still on 1.18.2 then there's no way Meteor would run on 1.19?

**Comment by sssuccess** [comment]
lol
