### ISSUE TITLE
1.19 Please [Suggestion] 

### ISSUE THREAD

**Issue by Funtimes909** [MeteorDevelopment/meteor-client#2350]
### Describe the feature

We need 1.19 because wurst is super wack

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
So true

**Comment by I-Got-You-Dead** [comment]
Meteor can’t update until baritone updates 💀
