### ISSUE TITLE
[Suggestion] No Render improvements

### ISSUE THREAD

**Issue by Radial2250** [MeteorDevelopment/meteor-client#2352]
### Describe the feature

add an option to change the size of the totem animation, instead of just disabling it.
also add an option to not render only specific armour pieces, instead of all armour at once.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by M1zxn** [comment]
bruh
