### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by kandda31** [MeteorDevelopment/meteor-client#2353]
### Describe the feature

1. A feature for Kill Aura (or not) that allows the attacker to always be behind the victim wherever the victim looks at, it could be the more useful Kill Aura feature since you can't really either be hit or even seen.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by dudethis** [comment]
Kinda like the teleport hit (sly something) in raven b+? So every time you hit them you would be behind them?
