### ISSUE TITLE
HUD[Suggestion] 

### ISSUE THREAD

**Issue by Panses2** [MeteorDevelopment/meteor-client#2356]
### Describe the feature

Ok so i have a problem with GUI , if you will have your category like PLAYER and MISC or COMBAT to far up it will be unaccesable 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
You can reset the HUD, with the (*gasp*) Reset button, and then edit it however you want.

**Comment by RickyTheRacc** [comment]
> You can reset the HUD, with the (_gasp_) Reset button, and then edit it however you want.

That isn't what they mean, although how you managed to drag a category off the screen is beyond me. You can reset the clickgui by doing .reset gui in chat.

**Comment by Lovecrafts-Cat** [comment]
I alway confuse GUI with HUD... `#general` took its toll on my sanity

**Comment by arlomcwalter** [comment]
just do .reset gui
