### ISSUE TITLE
[Bug] modules turn off randomly

### ISSUE THREAD

**Issue by goose-TM** [MeteorDevelopment/meteor-client#2358]
### Describe the bug

modules will stop working after a bit of use

### Steps to reproduce

```bash
turn on sum shit like tracers and nametags and wait a bit
```

### Meteor Version

dev build 5.0 build 1485

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by headhuntercertified** [comment]
this is a problem every time you disconnect aswell. temporary fix is to put all modules one one or 2 keybinds

**Comment by arlomcwalter** [comment]
should be fixed in cf26da3b280b8cdc0031ca0ef569c9a0de68d683
