### ISSUE TITLE
[BUG] Incompatibility with Architechtury-fabric

### ISSUE THREAD

**Issue by seanchristians** [MeteorDevelopment/meteor-client#236]
The client is incompatible with architechtury-fabric (https://www.curseforge.com/minecraft/mc-mods/architectury-fabric).

### About Architechtury
Architechtury is a compatibility layer mod. Its purpose is to allow mod developers to easily create both a Forge- and Fabric-compatible version of their mod. It does this by abstracting calls to the Fabric API to create a standard with its Forge counterpart.

### Error
Minecraft becomes stuck in a loading screen loop on boot.

### System
Running on Windows 10, Minecraft version 1.16.5
Fabric version 0.11.1
Fabric API version 0.30.0
Architechtury version 1.5.112
Meteor Client version 0.4.0 (latest from meteorclient.com as of this report)

### Reproducing
Install the mods listed in **System** and launch Minecraft. The game boots and the loading screen appears.

**Comment by seasnail8169** [comment]
@seanchristians can you please update meteor and let me know if this is still an issue.

**Comment by seanchristians** [comment]
Fixed in latest update
