### ISSUE TITLE
[Bug] game keeps crashing

### ISSUE THREAD

**Issue by Lillyblossem21** [MeteorDevelopment/meteor-client#2363]
### Describe the bug

hen i installed it for 1.18.2 and tried to play it it kept crashing with game error 1

### Steps to reproduce

```bash
start the game up
```

### Meteor Version

0.5.0-1487

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by The-MG** [comment]
Same issue here.

**Comment by Lovecrafts-Cat** [comment]
> 0.5.0-1487

Congrats, you tried to run the 1.19 build on 1.18.2 and got a crash, as expected
