### ISSUE TITLE
[Suggestion] Add an AutoBuild Module

### ISSUE THREAD

**Issue by lexqwe** [MeteorDevelopment/meteor-client#2367]
### Describe the feature

The module would allow you to build withers, and any other schematic/build automatically with items in your hotbar.
Highly inspired by highway builder.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
duplicate
