### ISSUE TITLE
No fall - Bucket or air place

### ISSUE THREAD

**Issue by MeteorClientUser420** [MeteorDevelopment/meteor-client#2368]
### Describe the feature

so  if ur using like bucket or air place with it i think there would still be a option to take no damage so if ur using air place and u ran out of blocks the no fall damage feature with it would save it 
so yeah the sugestion is addd no  fall damage seting to bucket and air place if u like run out of blocks or bucket so u would still take 0 damage i think it should  be a no fall update with  love crafts sugestion https://github.com/MeteorDevelopment/meteor-client/issues/2307

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
both exist
