### ISSUE TITLE
[Bug] Ignore Passive in Killaura not attacking Blazes

### ISSUE THREAD

**Issue by cyrilYCP** [MeteorDevelopment/meteor-client#2369]
### Describe the bug

Killaura doesn't attack blazes unless they shoot at you(With Ignore Passive On).
Killaura also stops attacking blazes when they stop shooting at you(With Ignore Passive On).

### Steps to reproduce

```bash
Turn on Killaura > Add Blazes to Select Entities > Turn on IgnorePassive > Gamemode survival > go near blaze
```

### Meteor Version

0.5.0 1494

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
there literally isn't ignorePassive in that dev build bruh
