### ISSUE TITLE
Inv Move error

### ISSUE THREAD

**Issue by minimimike** [MeteorDevelopment/meteor-client#237]
When i open any inventory, i walk backwards without pressing anything.

**Comment by simulatorwinner** [comment]
doesn't happen to me, what client version ?

**Comment by bramceulemans** [comment]
This happened to me too, the search tab is expanded and Gui Move is enabled.

**Comment by RedCarlos26** [comment]
It happened to me before but I think it is fixed in 0.4.1

**Comment by RedCarlos26** [comment]
It was fixed in 0.4.1, but it could still happen. It does not happen anymore in 0.4.2. It seems finally fixed entirely.

**Comment by RedCarlos26** [comment]
I don't know why, but it is still happening sometimes. I don't know how to reproduce it, it is pretty random.

**Comment by RedCarlos26** [comment]
I think it got fixed again. It is no longer happening to me

**Comment by RedCarlos26** [comment]
It started to happen again (and it's way worse) since the dev build that rewrites the GUI.

**Comment by MineGame159** [comment]
Should be fixed in d70ca1172f002aaf5c2ff6753c1c6ff5e663863f
