### ISSUE TITLE
[Bug] item interactions are funky

### ISSUE THREAD

**Issue by thekingofgame122** [MeteorDevelopment/meteor-client#2370]
### Describe the bug

I am currently running dev build 0.5.0 - 1494 and I am having a reoccurring issue that whenever I interact with a block or break one either nothing happens or the game kicks me with an error. The same thing happens with a juke box and a shulker

### Steps to reproduce

```bash
I interacted with blocks such as dirt, shulker box, juke box and chests.
```

### Meteor Version

0.5.0 - 1494

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
Need more info
What mods did you have active?
What error did it give?
