### ISSUE TITLE
[Bug] Killaura

### ISSUE THREAD

**Issue by iClickSlowish** [MeteorDevelopment/meteor-client#2371]
### Describe the bug

My killaura wont work/lock onto anything no matter what the target is (and yes I have my targets set on player) I dont know what wrong but the first day I downloaded the client it worked fine but after that it completely stopped working.

### Steps to reproduce

```bash
Everytime i activate killaura (doesnt matter what target im using) it wont work. It wont lock on and it wont attack and its the main hack i use.
```

### Meteor Version

0.5.0

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
Cant reproduce, did you make sure you had the same weapon equipped that was set in the Weapon setting?

**Comment by maxjiang2021** [comment]
Make sure the settings are configured correctly? (opened with right click)
