### ISSUE TITLE
[Bug] Using TAB autocomplete on names, while trying .friends add, lags your game or when you delete the name with backspace

### ISSUE THREAD

**Issue by DarkReaper231** [MeteorDevelopment/meteor-client#2380]
### Describe the bug

Basically when you open chat and try typing in .friends add and use tab, it lags your game for a second. It also happens when you have the name typed and want to delete it with backspace. Then it lags each time a character is removed.

There are no errors following this

### Steps to reproduce

```bash
Tested on ViaVersion server running 1.18.2
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
this has been resolved
