### ISSUE TITLE
[Bug] Crash at startup

### ISSUE THREAD

**Issue by noiverre** [MeteorDevelopment/meteor-client#2383]
### Describe the bug

[crash-2022-06-14_13.28.10-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8897189/crash-2022-06-14_13.28.10-client.txt)

### Steps to reproduce

```bash
Launch the client
```

### Meteor Version

dev 1496

### Minecraft Version

19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
Only way I managed to reproduce this was to manually edit my friends.nbt file to add an invalid URL character to the name of one of them

Don't know if it's worth fixing as I couldn't reproduce using only ingame tools
