### ISSUE TITLE
[Bug] crash because unable to copy font

### ISSUE THREAD

**Issue by maxsupermanhd** [MeteorDevelopment/meteor-client#2385]
### Describe the bug

Launching latest dev build (1496) in fresh environment on Linux results in startup crash. It fails to copy a font it seems,,.

[crash-2022-06-14_14.55.34-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8899536/crash-2022-06-14_14.55.34-client.txt)

### Steps to reproduce

```bash
Launch latest dev build in clean installation.
```

### Meteor Version

dev 1496

### Minecraft Version

1.19

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Should be fixed in c0e95e5bdfafe22b009b6f9dbbf4c0183d9f1199.
