### ISSUE TITLE
[Bug] Latest font fix still hasn't fixed the crash on startup at least on Linux

### ISSUE THREAD

**Issue by DarkReaper231** [MeteorDevelopment/meteor-client#2389]
### Describe the bug

[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8901623/latest.log)

btw Jetbrains Mono font doesn't seem to be in the error this time so one font is fixed I guess
so the reason might be that it also needs more fonts than Jetbrains font like DejaVu for example
these fonts must be part of the client or get fetched from their download pages

### Steps to reproduce

```bash
Launch meteor on Linux I guess
```

### Meteor Version

dev

### Minecraft Version

1.19

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Try now.

**Comment by DarkReaper231** [comment]
Seems to be working now. Changing fonts also works and it does seem to fetch the custom fonts installed on my machine from correct folders.
