### ISSUE TITLE
[Bug]  crash on start up

### ISSUE THREAD

**Issue by eeeeeeedsddddddd** [MeteorDevelopment/meteor-client#2392]
### Describe the bug

crash on start up (fabric)

### Steps to reproduce

```bash
i start game with the dev build and minecraft starts but then crashes
```

### Meteor Version

0.5.0-1501

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Needed a crash log to know the details, so please provide one. 
Located under .Minecraft/logs/latest.log.
