### ISSUE TITLE
[Bug] Under water overlay with sodium extra

### ISSUE THREAD

**Issue by mrGRINCH** [MeteorDevelopment/meteor-client#2393]
### Describe the bug

The removal of the water overlay doesn't work with sodium extra.

### Steps to reproduce

```bash
Install sodium extra and enable no render water overlay.
```

### Meteor Version

meteor-client-0.5.0-1493

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
Cant reproduce on meteor-client-0.5.0-1506
Are you using any other mods?

**Comment by mrGRINCH** [comment]
I use a few other mods but disabling sodium extra specifically was what made the no-render underwater overlay work.

I will disable all my mods and try with just sodium and sodium extra and reply with an update here.

**Comment by mrGRINCH** [comment]
I made a new instance and tested disabling underwater fog in no render and it is working.

I'm not sure what the issue was but it's working so I'm going to close this thread.
