### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by FBSANAKONDA** [MeteorDevelopment/meteor-client#2394]
### Describe the bug

AutoTotem is a little slow. I can kill myself with crystalaura.

### Steps to reproduce

```bash
turn on autototem and use caura
```

### Meteor Version

0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
It’s ur ping/wifi/pc
