### ISSUE TITLE
Crash when using f5 or freelook[Bug] 

### ISSUE THREAD

**Issue by 0DamI0** [MeteorDevelopment/meteor-client#2397]
### Describe the bug

[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8908899/latest.log)
[crash-2022-06-15_13.34.10-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8908901/crash-2022-06-15_13.34.10-client.txt)

### Steps to reproduce

```bash
Press the key to use F5 or freelook and the game will crash.
```

### Meteor Version

v0.5.0 1501

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
Unable to reproduce with just meteor, probably a mod conflict thing

**Comment by MineGame159** [comment]
Also can't replicate, if you figure out which mod it conflicts with reopen this issue.
