### ISSUE TITLE
[Suggestion] Farm

### ISSUE THREAD

**Issue by Mankifg** [MeteorDevelopment/meteor-client#2398]
### Describe the feature

added module called Farm that farm specific crops with specific tools,
it can also be config to range, area or type of crop

### Before submitting a suggestion

- [ ] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by dariusthechad** [comment]
type #farm in chat
