### ISSUE TITLE
Xray Problem

### ISSUE THREAD

**Issue by ArticRexx** [MeteorDevelopment/meteor-client#2402]
### Describe the bug

I use xray and it breaks and I can only see through grass and seagrass

Note: I cant get my dev build to work so sorry if this is not relevant :(
![Xray fail](https://user-images.githubusercontent.com/107590342/173959043-62a27e8b-f280-4fed-8954-c2991625e4b5.png)

### Steps to reproduce

```bash
I enable xray using my hotkey x and just by turning it on and it breaks
```

### Meteor Version

0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ArticRexx** [comment]
Why was this closed what is the fix?

**Comment by arlomcwalter** [comment]
because it is a duplicate

**Comment by ArticRexx** [comment]
But what was the fix?

**Comment by arlomcwalter** [comment]
there is no fix yet
