### ISSUE TITLE
Fast Swimmer/ Don't Drown 

### ISSUE THREAD

**Issue by IcySoCool** [MeteorDevelopment/meteor-client#2403]
### Describe the feature

So like the Suggestions said, makes the player swims faster and also doesn't allow you to drown(Or slow down the drown speed) Simple but convenient for anarchy SMP 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
Are you autistic, I want you to tell me how tf you expect to tell the server to slow drowning.

**Comment by I-Got-You-Dead** [comment]
> > Are you autistic, I want you to tell me how tf you expect to tell the server to slow drowning.
> 
> 
> 
> Dam bro, then explain how hitbox works 

It works kinda like ka, just when you hit it flicks ur head and hits

**Comment by SIMULATAN** [comment]
The client sends attack packets to the server, and you can send those even when you're not fully aiming at the target. Drowning and other stuff are sent by the server to the client tho, and thus you have no control over it.

Correct me if I'm wrong

**Comment by I-Got-You-Dead** [comment]
> The client sends attack packets to the server, and you can send those even when you're not fully aiming at the target. Drowning and other stuff are sent by the server to the client tho, and thus you have no control over it.
> 
> Correct me if I'm wrong

Thx

**Comment by IcySoCool** [comment]
> 

Ah ok thanks :)

**Comment by Wide-Cat** [comment]
fast swim is theoretically possible, but preventing drowning hasnt been possible for a few years, if the method im thinking of is correct.
