### ISSUE TITLE
[Suggestion] Hide hud elements

### ISSUE THREAD

**Issue by ColGroLoOl** [MeteorDevelopment/meteor-client#2406]
### Describe the feature

Add a feature that hides selected hud elements and prevent them from rendering in the hud editor, to sort out stuff you never use and still being able to hide things you dont want right now

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by ColGroLoOl** [comment]
> I see what you mean, but: how do you know which elements exist if you can fully hide them?
> 
> A good solution would be to have a list of elements to choose from and add to the HUD.

Thats what I tought, a list similar to Rejects' "Hide Module"

**Comment by arlomcwalter** [comment]
this is a feature in the hud rewrite which should be pushed before the next release of meteor. also in terms of vanilla elements, some can be hidden using the no render module, if you'd like any to be added to that list let me know. also also, i do plan to add vanilla hud elements to the hud editor eventually so they can be moved, configured and toggled
