### ISSUE TITLE
jesus broke

### ISSUE THREAD

**Issue by BlitzFan1209** [MeteorDevelopment/meteor-client#2408]
### Describe the bug

can i have google glasses

### Steps to reproduce

```bash
turn on jesus step on lava piston urself into lava
```

### Meteor Version

69.420

### Minecraft Version

1.8

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by BlitzFan1209** [comment]
L

**Comment by BlitzFan1209** [comment]
>.<

**Comment by Wide-Cat** [comment]
unable to reproduce

**Comment by somerandomcloud** [comment]
@Wide-Cat did you take this seriously? its obviously a fucking joke :skull:

**Comment by BlitzFan1209** [comment]
:trollface:

**Comment by somerandomcloud** [comment]
nvm i missed the joke myself
