### ISSUE TITLE
[Suggestion] add skulk shriekers to search 

### ISSUE THREAD

**Issue by CodeDoc537** [MeteorDevelopment/meteor-client#2411]
### Describe the feature

title

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Wide-Cat** [comment]
its spelt 'sculk'
