### ISSUE TITLE
[Suggestion] Add Darkness to No Render options

### ISSUE THREAD

**Issue by NakyoykaN** [MeteorDevelopment/meteor-client#2412]
### Describe the feature

While Full Bright counters Darkness it would be beneficial for players who want a dark ambient to be able to just disable the darkness effect itself via No Render.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
the fog option does this
