### ISSUE TITLE
[Suggestion] Add a time of day changer

### ISSUE THREAD

**Issue by Crusader-s** [MeteorDevelopment/meteor-client#2413]
### Describe the feature

This option can change the time of day client side so you can do stuff if you don't like the dark (I know full bright is there, but I like the day sky)
Or maybe you want to take a pic of the sunset but it's the middle of the day

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
This literally exists, it is called time changer, ride a submarine with screen doors
