### ISSUE TITLE
[Suggestion] Version list

### ISSUE THREAD

**Issue by KaliCyanide** [MeteorDevelopment/meteor-client#2414]
### Describe the feature

Can you make a version list from 1.16.5 to 1.19 for someone that want to use that versions on the website, It kinda complicate when you download from other source 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
![image](https://user-images.githubusercontent.com/52252627/174321256-b5bc17d6-00fe-40e7-99d0-04795084dc1a.png)
Yeah bro, you sure did...
How about you now go and read the FAQ to know how to join older servers from the latest MC version?

**Comment by KaliCyanide** [comment]
oh I see thanks
Im not read FAQ sorry.

**Comment by RicharPao** [comment]
That is to say, MeteorClient always provides the latest version, but can't find the previous version? What if I need to use the old version?

**Comment by seasnail8169** [comment]
> That is to say, MeteorClient always provides the latest version, but can't find the previous version? What if I need to use the old version?
> 
> 

did you read the response??

**Comment by ManInMyVan** [comment]
> That is to say, MeteorClient always provides the latest version, but can't find the previous version? What if I need to use the old version?
> 

[https://maven.meteordev.org](https://maven.meteordev.org)
