### ISSUE TITLE
[Bug] Can't connect to proxy on 1.19

### ISSUE THREAD

**Issue by AlexNomadrg** [MeteorDevelopment/meteor-client#2415]
### Describe the bug

I can't connect to proxy on 1.19 meteor. It work fine on 1.18.2, but seems to be broken on 1.19.

 [The error](https://pastebin.com/tL59yP0J)
 [Full log](https://mclo.gs/7Qv7p5O)

### Steps to reproduce

```bash
1. open minecraft 1.19 with meteor client 0.5.0
2. add any proxy
3. try to connect to server / refresh server list
4. get https://pastebin.com/tL59yP0J in console
```

### Meteor Version

0.5.0-1505

### Minecraft Version

1.19

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 401f6deeb9bbdfa411d7b0533564d327d2e55417.
