### ISSUE TITLE
[Bug] cant open chests or interactables without crashing

### ISSUE THREAD

**Issue by thekingofgame122** [MeteorDevelopment/meteor-client#2416]
### Describe the bug

I am currently running the latest developer version and I have encountered the problem of having difficulties interacting with objects. Everytime I open a chest or door I get kicked.

### Steps to reproduce

```bash
interacting or opening a chest
```

### Meteor Version

5.39.44.75

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
what meteor version is this? also send a picture of your active modules

**Comment by thekingofgame122** [comment]
> what meteor version is this? also send a picture of your active modules

I am terribly sorry but this issue was just caused by paring meteor client with the first beta version of multiconnect

**Comment by Wide-Cat** [comment]
In that case, if this is a multiconnect issue you should probably use viafabric until they have fixed it.
