### ISSUE TITLE
[Bug] Launcher crashing when using meteor client

### ISSUE THREAD

**Issue by MichalK23** [MeteorDevelopment/meteor-client#2418]
### Describe the bug

In the latest dev build (1505) my launcher keeps crashing. The problem is definitely in the client because when I remove it from mods folder it works fine. The latest release (0.4.9) also works fine for its minecraft version. 

I can only launch minecraft once right after reinstalling my fabric profile for 1.19. When I try launching again it crashes. This doesnt happen for release 0.4.9 on 18.2.

Here is a part of the error message: 
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [lwjgl_stb.dll+0x27b9a]

### Steps to reproduce

```bash
I put the meteor client jar file into mods folder (nothing else is there). I then install fabric 1.19 with loader version 0.14.8 and launch minecraft fabric 1.19. It works fine. Then I close it and launch again and it crashes.
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
No shit Sherlock, try using your brain what that could mean

**Comment by MineGame159** [comment]
Or do you mean you can only launch 1505 on 1.19 once? If that is so send the the crash crash, nothing we can do without it.
