### ISSUE TITLE
MultiConnect Search

### ISSUE THREAD

**Issue by jprknight** [MeteorDevelopment/meteor-client#242]
Meteor when used with multiconnect on 1.12 (possibly more versions as well); issue with search. Numerous blocks are highlighted which are not selected.

**Comment by jprknight** [comment]
Just to clarify the issue, this is my view with no blocks selected to be highlighted. The client appears to highlight cavities in the nether and caves in the overworld as well.

![2021-02-24_11 53 55](https://user-images.githubusercontent.com/40891654/109036411-906af500-7697-11eb-9702-9a7666a90c4a.png)

**Comment by jprknight** [comment]
I have cleared out my %appdata%\.minecraft\meterclient folder, after doing this I now have search working with MultiConnect on the same 1.12 server. If there is no repro, this can be closed as a one time thing.

**Comment by jprknight** [comment]
So, I thought this was ok. I was switching profiles and it came back. :(

**Comment by RedCarlos26** [comment]
The thing is that meteor isn't meant to be a 1.12 client. This could probably be fixable, but with a lot of work. I don't know if this will someday be fixed.

**Comment by RedCarlos26** [comment]
@seasnail8169 what do you think about that?

**Comment by jprknight** [comment]
After some testing on a 1.16.5 server I see the same issue. This feels more like a general incompatibility with multiconnect.

**Comment by RedCarlos26** [comment]
This is strange, because I use multi connect and I don't have this issue

**Comment by RedCarlos26** [comment]
Do you still have the issue @jprknight?

**Comment by jprknight** [comment]
Yes, I am. I also removed 1.12 from the title of this issue since I get this on a 1.16.4 client / 1.16.5 server.
![2021-04-06_15 15 11](https://user-images.githubusercontent.com/40891654/113766178-22303e00-96eb-11eb-99db-3108b00d469e.png)

**Comment by RedCarlos26** [comment]
This is really strange. Do you have any mods installed other than meteor client?

**Comment by MineGame159** [comment]
@jprknight can you try it after d362e4070440987f96c64e15b7efc3b7306e2032
