### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by DJurdad** [MeteorDevelopment/meteor-client#2429]
### Describe the feature

Make an auto mine that can mine for you without a mending pic, or just add no mending pic required for the infinite mine.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
bruh

**Comment by I-Got-You-Dead** [comment]
welp, i have lost all hope in humanity...
