### ISSUE TITLE
[Bug] baritone does not work as intended

### ISSUE THREAD

**Issue by thekingofgame122** [MeteorDevelopment/meteor-client#2435]
### Describe the bug

I have been encountering this issue ever since 1.19 for meteor was realised. Every time I try to mine something with the following command #mine ore here it would find the most tedious path and outright ignore blocks that I actually needed. The pathing does not work since all it does is calibrate paths and find nothing. 

### Steps to reproduce

```bash
simply by using the #mine command
```

### Meteor Version

1509 dev

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
config issue 💀

**Comment by MineGame159** [comment]
We are not developers of Baritone.

**Comment by IPlayMinecraftYT** [comment]
> config issue 💀

so then how do you fix it
