### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ZacLiiscool** [MeteorDevelopment/meteor-client#2436]
### Describe the bug

X-ray does not work, but if I really wanted to use they're putting a Redstone peace down and look looking through it works but it is only for a short period of time caused by lag
<img width="770" alt="Screen Shot 2022-06-21 at 11 12 43 AM" src="https://user-images.githubusercontent.com/98473212/174708704-24c7c8e8-572e-4746-ae9d-3dafa869b5b6.png">
<img width="802" alt="Screen Shot 2022-06-21 at 11 13 58 AM" src="https://user-images.githubusercontent.com/98473212/174708739-ba607b32-c7d8-4665-97b9-200711b23f87.png">
.

### Steps to reproduce

```bash
i don't know it just stoped working..
```

### Meteor Version

0.4.9

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ZacLiiscool** [comment]
I only change things like the key binds and kill aura stuff I saw a bunch of other problems on YouTube and Google about meteor client x-ray not working but they somehow fixed it, but for me I tried a lot of ways and it all doesn't work

**Comment by ZacLiiscool** [comment]
<img width="1440" alt="Screen Shot 2022-06-21 at 11 30 24 AM 2" src="https://user-images.githubusercontent.com/98473212/174710444-14441287-cb7c-4a9a-bdf6-a828d63f5047.png">

only workes like this

**Comment by ZacLiiscool** [comment]
<img width="253" alt="Screen Shot 2022-06-21 at 11 31 49 AM" src="https://user-images.githubusercontent.com/98473212/174710538-4fd599ec-8159-4694-8c0a-ee5ca8547d19.png">

**Comment by ZacLiiscool** [comment]
Actually I figured out a way how to solve this problem we just need to use our mouse to click on the opacity bar do not drag just click it and slowly make it to one it will work

**Comment by MineGame159** [comment]
Fixed in 74104436c75057165f14e8012bab78c61062de40.
