### ISSUE TITLE
Mixin Error [Bug] 

### ISSUE THREAD

**Issue by TheGamingFireman** [MeteorDevelopment/meteor-client#2437]
### Describe the bug

I have found some mods that were previously compatible in older versions (and for no proper reason wouldn't be compatible if this were the stable release) cause a mixin error on startup. While it is caused by adding certain mods to my folder all the errors in the log say it has to do with meteor.

Log: https://pastebin.com/vE9FMpAf

### Steps to reproduce

```bash
Added Giselbaer's Durability Viewer 1.19 to mod folder.
```

### Meteor Version

5.0 #1510

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
That mod is incompatible, as there is already a module / HUD element that displays similar info.
