### ISSUE TITLE
[Suggestion] Older versions' sourcecode.

### ISSUE THREAD

**Issue by energy11a** [MeteorDevelopment/meteor-client#2440]
### Describe the feature

Sourcecode for older versions. Like latest sourcecodes for meteor client for 1.16.x 1.17.x 1.18.1 1.18.2

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
You have the entire git history available.
