### ISSUE TITLE
[Bug] Friend Related Lag

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2443]
### Describe the bug

Since the switch of the friends system to be UUID based, myself and other users have noted severe lag spikes when adding or removing friends. Adding a friend ingame will cause the screen to freeze for a second, and sometimes game crashes me when running in IntelliJ. RedCarlos also noted that the friends menu seems to perform exponentially worse as you add more friends, and had to reset his NBT file because opening his menu would crash the game.

### Steps to reproduce

```bash
Add or remove friends inside of a server, or access the Friends Menu with a substantial amount of friends added
```

### Meteor Version

1510

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
To precise I needed to delete my friends.nbt after I crashed from opening the Friends tab in Meteor.

**Comment by RacoonDog** [comment]
Just curious here, do you know approximately how many friends you had?

**Comment by RedCarlos26** [comment]
> Just curious here, do you know approximately how many friends you had?

Around 30 or so I think. I never had lag before tho it's exactly when it updated to UUID based friends that it broke.
