### ISSUE TITLE
[Suggestion] rewrite and improve highwaybuilder

### ISSUE THREAD

**Issue by Aztroh** [MeteorDevelopment/meteor-client#2444]
### Describe the feature

Current highway builder is super slow and could be optimized 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by arlomcwalter** [comment]
> Yes please adding an option to place more than one block per tick when placing would be awsome!

💀

**Comment by RedCarlos26** [comment]
> > Yes please adding an option to place more than one block per tick when placing would be awsome!
> 
> 💀

Whats the matter 🤨

**Comment by JustABiscuit** [comment]
Just use HIGTools for highway things.

**Comment by I-Got-You-Dead** [comment]
> Just use HIGTools for highway things.

Retard

**Comment by JustABiscuit** [comment]
> > Just use HIGTools for highway things.
> 
> Retard

Could you please srop harassing me?

**Comment by I-Got-You-Dead** [comment]
Maybe use ur brain and I’ll think about it
