### ISSUE TITLE
[Suggestion] .toggle (module) to send feedback

### ISSUE THREAD

**Issue by energy11a** [MeteorDevelopment/meteor-client#2446]
### Describe the feature

add option to the .toggle command to send feedback on toggle for an example: .toggle anchor_aura * +  to toggle anchor aura and send feedback. .toggle anchor_aura on to toggle anchor aura on and not send feedback.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Talhoid** [comment]
what

**Comment by energy11a** [comment]
I suggested adding a tag in command that when used sends feedback.
