### ISSUE TITLE
[Bug] chest swap chat feedback

### ISSUE THREAD

**Issue by Hilikusz** [MeteorDevelopment/meteor-client#2447]
### Describe the bug

chest swap feedback is broken, either its on or off it keeps giving notifs

### Steps to reproduce

```bash
chest swap module
```

### Meteor Version

v0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
Its kind of a bug tho
