### ISSUE TITLE
[Suggestion] An auto bridge module

### ISSUE THREAD

**Issue by Crusader-s** [MeteorDevelopment/meteor-client#2448]
### Describe the feature

The module can auto bridge for you (scaffold is too sus for public server) It can do lots of different type of bridge like ninja, or even Andromeda (there is a mod for Andromeda but it's for forge)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Crusader-s** [comment]
> use safe walk

Someone definetly gonna notice me just stop at the edge of a block perfectly everytime

**Comment by Lovecrafts-Cat** [comment]
> too sus for public server

You shouldn't use Meteor on non-Anarchy servers (or servers that allow clientside modifications).

**Comment by Crusader-s** [comment]
> > too sus for public server
> 
> You shouldn't use Meteor on non-Anarchy servers (or servers that allow clientside modifications).

Still, having auto Andromeda is still a nice touch in a private server
