### ISSUE TITLE
[Suggestion] Autoreport module for Minecraft 1.19.1

### ISSUE THREAD

**Issue by MIOGMIOG** [MeteorDevelopment/meteor-client#2449]
### Describe the feature

This module uses Minecraft´s chat reporting feature.
It reports all messages in chat, with a category that the user sets
There would also be a spam mode that will report those messages over and over again (with a set delay).
I think this will be a nightmare for Microsoft moderators :) (and for players if hack module reports swearing player)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by 19MisterX98** [comment]
Im not sure if its a good idea to throw something potentially valuable like user data directly at Microsoft. Keep in mind that moderating might not be their only intend

**Comment by MIOGMIOG** [comment]
> 

yes, thats true

**Comment by MIOGMIOG** [comment]
> Im not sure if its a good idea to throw something potentially valuable like user data directly at Microsoft. Keep in mind that moderating might not be their only intend

yes, thats true...

**Comment by RedCarlos26** [comment]
Are you dumb

**Comment by arlomcwalter** [comment]
This shit is so cringe. People pay money (quite a bit) to play the game because they want to enjoy it and they should be able to do that in any way they want. I am completely against the whole reporting system in general and nothing related will ever be added to meteor. The idea for someone's money to be wasted by some feature like that is very crude.

**Comment by rjbarber** [comment]
This feature should really be reconsidered. Not for the purpose of actually reporting players, but to overwhelm and break the MS reporting system by saturating it with bogus reports. What better way to get rid of that egregious system then to have multiple clients (including Meteor) overwhelming it daily with 10s of thousands of bogus reports???

**Comment by arlomcwalter** [comment]
> This feature should really be reconsidered. Not for the purpose of actually reporting players, but to overwhelm and break the MS reporting system by saturating it with bogus reports. What better way to get rid of that egregious system then to have multiple clients (including Meteor) overwhelming it daily with 10s of thousands of bogus reports???

You don't necessarily need meteor to do that, its a very niche feature that shouldn't be there for all users. Not sure how the system works exactly but it's not an awful idea, although I wouldn't want meteor to be responsible any repercussions that spamming reports gets you.
