### ISSUE TITLE
[Bug] Rainbow speed stuck at a high value, slider does nothing.

### ISSUE THREAD

**Issue by WifiRouterYT** [MeteorDevelopment/meteor-client#2450]
### Describe the bug

I just installed meteor client this morning (used it before on a different computer) and I noticed that the rainbow speed is extremely high. I went to the config to change it, but the slider did absolutely nothing. I deleted the meteor-client folder in .minecraft, still no luck. What gives?

(epilepsy warning)
https://user-images.githubusercontent.com/45213292/175757893-146ce8a9-d33e-42c7-aa76-19e5a8339583.mp4

### Steps to reproduce

```bash
1. Install Meteor Client 0.4.9
2. Face this issue?

I honestly don't know.
```

### Meteor Version

0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
that hud element has a separate rainbow speed, just open it's settings and change it there

**Comment by WifiRouterYT** [comment]
i did not know that you can change the settings of individual hud elements. thank you.
