### ISSUE TITLE
[Bug] Crash on startup: "Failed to load font"

### ISSUE THREAD

**Issue by M1lken01** [MeteorDevelopment/meteor-client#2451]
### Describe the bug

Game crashes on startup with exit code: 1
Tried to fix it by deleting the configs and the fonts folders with no success.
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/8985365/latest.log)

### Steps to reproduce

```bash
Launching the client.
```

### Meteor Version

0.5.0-1511

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
This should be fixed
