### ISSUE TITLE
[Bug] Infinity miner strange repair pattern

### ISSUE THREAD

**Issue by meteoruser** [MeteorDevelopment/meteor-client#2452]
### Describe the bug

Infinity Miner's repair mode (lets say it repairs when tool is at 20% durability) seems to enable when the tool passes right below (eg: 19.9%) but then immediately disable when tool repairs slightly (eg: passes back at 20%)

For example, on the following image, it would mine about three blocks towards point 2 thent turn to mine 1 nether quartz at point 1 (and then repeat the process)

![2022-06-26_01 14 19](https://user-images.githubusercontent.com/108200275/175793295-8d51437b-3983-4d66-8574-06a56795b442.png)

Chat going wild from all the enabling/disabling of repair mode:
![2022-06-26_01 21 23](https://user-images.githubusercontent.com/108200275/175793382-3973045e-a7e8-4f61-bbaf-eb461af23078.png)

### Steps to reproduce

```bash
Turn on infinity miner then wait for tool durability to drop below the configured "Durability Threshold"
Observe

(In my case I had:
    target blocks => ancient debris
    repair blocks => nether quartz ore
)
```

### Meteor Version

mod file: 0.4.9  (hud reports: 0.5.0)

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by procrafter820** [comment]
Keep a large significant gap between mining threshold and Repair Threshold ....like 70% and 20% respectively
