### ISSUE TITLE
[Bug] Macros isn't working in 1.19 servers

### ISSUE THREAD

**Issue by Noroba-pro** [MeteorDevelopment/meteor-client#2463]
### Describe the bug

This happens when I am trying to use macros in 1.19 server

![image](https://user-images.githubusercontent.com/46607843/176737775-969cd475-4c6e-42e8-8887-0d075306a20a.png)

### Steps to reproduce

```bash
Use macros on 1.19 server
```

### Meteor Version

0.5.0 1511

### Minecraft Version

1.19

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
Don’t use .say lmao

**Comment by MineGame159** [comment]
Fixed in a550d22623a3cc9baa0ff475376823ad448b6853.
