### ISSUE TITLE
[Suggestion] make a option where you don’t make noise near a shulk sensor thing

### ISSUE THREAD

**Issue by DankAssassin** [MeteorDevelopment/meteor-client#2467]
### Describe the feature

So it acts like you’re sneaking but you are standing regularly just something to not make noise near the warden things. For once you make the 1.19 version of meteor 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
> "Yes, hello mister shrieker, could you please not notice my movement, pretty please?"

The only way to do this would to automatically sneak when a shrieker is within detection radius.
This is beyond useless, as the only thing you need to not trigger a shrieker is a pair of eyes to see it inadvance.

**Comment by Wide-Cat** [comment]
Enable the sneak module and set it to 'packet' mode
