### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mrplayergod** [MeteorDevelopment/meteor-client#2471]
### Describe the bug

When I get dirt and stone it start placing randomly.

### Steps to reproduce

```bash
I just pick up dirt and stone.
```

### Meteor Version

#1516

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by mrplayergod** [comment]
Help please

**Comment by DeeKahy** [comment]
What modules do you have enabled?

**Comment by I-Got-You-Dead** [comment]
Lmao scaffold moment 💀

**Comment by mrplayergod** [comment]
@DeeKahy I have [Fake player, No rotation, Portal, Reach, Better tooltip, Boss stack, Break indicator, Camera tweaks, City esp, Entity owner, Full bright, Hand view, Hole Esp, Nametag, No render, Tracers, Trajectories, Unfocused cpu, Anti anvil, Auto totem, Critical, Anti Packet Kick, Auto reconnected, Better chat, Better tab, Inventory tweaks, Gui move, No fall, No slow, velocity.

**Comment by I-Got-You-Dead** [comment]
Check ur no fall config

**Comment by mrplayergod** [comment]
Okay

**Comment by mrplayergod** [comment]
Still doesnt fix my problem :(

**Comment by mrplayergod** [comment]
PLEASE HELP ME

**Comment by mrplayergod** [comment]
Please help with my issue

**Comment by I-Got-You-Dead** [comment]
Reset ur client
