### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by numericly** [MeteorDevelopment/meteor-client#2473]
### Describe the bug

When using the PlaySoundEvent you are not able read the pitch of the sound.
```java
@EventHandler
    private void onSound(PlaySoundEvent event) {

        SoundInstance sound = event.sound;

        if (sound.getId().getPath().equals("block.note_block.harp")) {
            System.out.println(sound.getPitch());
        }
    }
```
This throws
```java
 java.lang.NullPointerException: Cannot invoke "net.minecraft.client.sound.Sound.getPitch()" because "this.sound" is null
```

### Steps to reproduce

```bash
Create a new module create a PlaySoundEvent event and do event.sound.getPitch()
```

### Meteor Version

0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by arlomcwalter** [comment]
can you send a screenshot of the whole class?

**Comment by numericly** [comment]
![image](https://user-images.githubusercontent.com/107078148/177415496-363237b5-f4b1-482b-931e-59ec0b64422d.png)
Here you go

**Comment by numericly** [comment]
Does that look correct?

**Comment by MineGame159** [comment]
Nothing to do with Meteor, just that the underlying `Sound` object inside of the `SoundInstance` is null, you can check for it with `event.sound.getSound()`
