### ISSUE TITLE
 opening friends list crashes game

### ISSUE THREAD

**Issue by headhuntercertified** [MeteorDevelopment/meteor-client#2475]
### Describe the bug

open gui, click friends, crashes

### Steps to reproduce

```bash
launch minecraft, open meteor gui, click friends, crashes
```

### Meteor Version

dev build 0.5.0 - 1518 1.19

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
send logs and friends list

**Comment by MineGame159** [comment]
Closing this because I can't replicate it and you didn't send a crash report.
