### ISSUE TITLE
[Bug] Hud Element Weirdness

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2476]
### Describe the bug

Opening any HUD element's settings (besides the module list oddly) will open a settings box wider than your screen instead of the correct width.

![image](https://user-images.githubusercontent.com/80427814/177646773-e89133eb-142c-44ee-add3-28239440770b.png)

### Steps to reproduce

```bash
Use the latest build with HUD Rewrite, open the hud and right click on any settings besides the Module List, and observe as an abnormally wide setting box is created.
```

### Meteor Version

1519

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RedCarlos26** [comment]
It doesn't show wider for me but still very very wide. Can confirm

**Comment by ItsIsntItsKeera** [comment]
u can just move the windows, keep moving, sure it mildly but it possible

**Comment by Wide-Cat** [comment]
In theory this should be fixed on the latest dev build. If it is still happening send another screenshot and reopen

**Comment by RedCarlos26** [comment]
Alright thanks

**Comment by jsmith64pro** [comment]
Still happening for me on the latest dev build just downloaded from the site. Only seems to happen to the text element though.
<img width="1680" alt="wide" src="https://user-images.githubusercontent.com/110138329/181879088-66ca3b7b-dd32-4efc-a8eb-c27b734d1893.png">
