### ISSUE TITLE
[Suggestion] Better Kill Aura

### ISSUE THREAD

**Issue by Bozalosc** [MeteorDevelopment/meteor-client#2477]
### Describe the feature

Just an all around better kill aura with fov, raytracing, the whole 9 yards if possible.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
use the Meteor plus addon
