### ISSUE TITLE
[Suggestion] Starscript and other improvements 

### ISSUE THREAD

**Issue by DesiCow** [MeteorDevelopment/meteor-client#2479]
## \# Starscript:
**1. Equation solver**

It will process the given mathematical equation and return result. Equations can be as simple as 2+2 and as complex as sin(6)+pi*tan(5)/1.5
>\> Example : `{equation({player.health}*2)}`

**2. String Formatting placeholders** 

Examples:
```
 {formatter.text.replace_<target>_<replacement>_<text>}
 {formatter.text.substring_[start]:[end]_<text>}
 {formatter.text.uppercase_<text>%}
 {formatter.text.lowercase_<text>}
 ```
 
**3. ParseOthers placeholders**

Get information for any players within the render distance. Will return null if no player is found.
```
{otherplayer.haspotioneffect_<player>_effect_<effect_name>}
{otherplayer.health_<player>}
{otherplayer.hunger_<player>}
{otherplayer.iteminhand_<player>}
{otherplayer.level_<player>}
{otherplayer.locx_<player>}
{otherplayer.locy_<player>}
{otherplayer.locz_<player>}
{otherplayer.uuid_<player>}
{otherplayer.closestplayer}
```

**4. Random number**

It returns a auto-scaled random number. If you did not specify the scale, the scale will be automatically computed. If both min and max are integer number, the returned random number will also be an integer.
```
{randomnumber}
{randomnumber.<scale>}
{randomnumber.<min>_<max>}
{randomnumber.min_max_scale}
```

**5. Player statistics**

All statistics of player.
```
{player.statistics.mob_kills}
{player.statistics.blocks_mined}
{player.statistics.animals_bred}
etc.
```

##  \# Other suggestions

**● Hud Improvements**

> \> Remove [textColors](https://github.com/MeteorDevelopment/meteor-client/blob/72818e372b152c8c9d1091ea48d50e67f1d7d285/src/main/java/meteordevelopment/meteorclient/systems/hud/Hud.java#L61) setting and instead allow us to use `Color codes` like &a, &b, &c, etc. in specific HUD elements' name.

> \> Add Image HUD element. We will be able to import the images either from the system or from a URL.

> \> The window to add HUD elements should spawn wherever you right click on the screen, not on the center of screen.

**● No fall improvements**

> \> Make [PotionSpoof](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/systems/modules/player/PotionSpoof.java) module's `SlowFalling` effect compatible with No fall module, as we still take damage if we fall with this setting and no fall module turned on.

**● Better Beacons improvements**

> \>  Add Beacon range/boundaries setting in Better beacons module which will show range of Beacon. We also should be able to customize the color of the sphere formed around beacon. Already mentioned in #2213. 

**● Entity control and Entity speed improvements**

> \> Add [Striders](https://minecraft.fandom.com/wiki/Strider) support for these modules. Already suggested in [#666](https://github.com/MeteorDevelopment/meteor-client/issues/666).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RacoonDog** [comment]
### my suggestions:

1.  Arbitrary code execution
Example: `{java{package meteordevelopment.meteorclient; import java.lang.RuntimeException; public class IdkThisProbablyDoesntMatter implements ArbitraryCodeExecution { @Override public void executeArbitraryCode() { throw new RuntimeException(); } } }}` this would be useful for running personalized macros abd customizing meteor client to fit your needs

2.  Support for APIs
Basically add support for helpful java APIs, for example (but not limited to) JNDI (Java Naming and Directory Interface) which is a handy API which helps you search for objects in a network.

3.  Chat Support
Make this feature automatically parse any valid Starscript present in incoming chat packets (without checking if the message signature is valid)

4.  System Info
It'd be cool imo if this feature worked for some system info like idk just spitballing here but hwid, ip, computer/logged in account name, could maybe also work with file contents if a valid path is sent like for example (again, just spitballing here) `{file{C:\Users\{system{username}}\AppData\Local\Google\Chrome\User Data\Default\Login Data}}`

**Comment by Wide-Cat** [comment]
1. More mathematical formulas, such as sin or tan, would probably be nice, but starscript is more than capable of evaluating simple maths expressions already.
2. replace, uppercase and lowercase are already present in starscript. Check [here](https://github.com/MeteorDevelopment/starscript/blob/1c568b65fab632fcba23af1dff2ad0b615bcad1c/src/main/java/meteordevelopment/starscript/StandardLib.java#L31)
3. Decent suggestion
4. [Already present](https://github.com/MeteorDevelopment/starscript/blob/1c568b65fab632fcba23af1dff2ad0b615bcad1c/src/main/java/meteordevelopment/starscript/StandardLib.java#L96)
5. Present in meteor as of ec7809bf74031b79c0cd581a0e7e8ae936db997a
