### ISSUE TITLE
KillAura doesn't work on Withers?

### ISSUE THREAD

**Issue by bramceulemans** [MeteorDevelopment/meteor-client#248]

**Comment by MineGame159** [comment]
Tested it and it works

**Comment by supakeks** [comment]
You need to select the entity in the entities list @bramceulemans

**Comment by bramceulemans** [comment]
It's selected.

**Comment by bramceulemans** [comment]
Figured it out, withers at spawn were named and hence ignored.

**Comment by MineGame159** [comment]
Yes, theres a setting to ignore named mobs
