### ISSUE TITLE
[Suggestion] Mass Delete HUD Elements

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2483]
### Describe the feature

Add the ability to delete HUD elements by selecting them and then using the delete key.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
You literally can do this.

**Comment by Wide-Cat** [comment]
lmao
