### ISSUE TITLE
[Bug] Friends Don't Save

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2484]
### Describe the bug

Friends don't save in profiles and reset when you join a new server, regardless of if the profile linked to that server shows that Friends are to be saved.

### Steps to reproduce

```bash
1. Add a friend in a server
2. Create a new profile and link it to the server
3. Ensure "Save Friends" is enabled for the profile
4. Save the profile and exit the server
5. Log back in to the server and observe that the friends list resets
```

### Meteor Version

1524

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 15038d3ca063831651aeef7b6412f0c3e139f988.
