### ISSUE TITLE
[Bug] Hud Elements Not Clearing

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2485]
### Describe the bug

After saving a profile and exiting a server, the HUD doesn't seem to be cleared on loading a profile, causing new instances of the HUD elements to be created as well as the original HUD elements, thus duplicating everything in your HUD

https://user-images.githubusercontent.com/80427814/177898978-ca573a9c-3133-4c86-91b6-6ca2604fd81c.mp4

.

### Steps to reproduce

```bash
1. Add a few HUD elements to your HUD and ensure it is active
2. Create and save a profile with that HUD
3. Leave and rejoin a game
4. Observe how the items in your HUD are duplicated
```

### Meteor Version

1524

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in c789387b604c7466f51e0954a8ef0226fc0b8f14.
