### ISSUE TITLE
[Bug] Baritone Autocomplete is broken

### ISSUE THREAD

**Issue by TillDV** [MeteorDevelopment/meteor-client#2486]
### Describe the bug

If I type something for batitone, press tab, type something else, the autocomplete does not update...

### Steps to reproduce

```bash
Just enter baritone commands and use tab
```

### Meteor Version

0.4.8-0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Baritone commands are not supposed to have autocomplete.

**Comment by MineGame159** [comment]
Ignore me previous comment, just tried it and it works fine for me.

**Comment by TillDV** [comment]
ok... Thanks for this information.
