### ISSUE TITLE
[Bug] Meteor crash on Launch (Contain addon) (On Dev build)

### ISSUE THREAD

**Issue by ItsIsntItsKeera** [MeteorDevelopment/meteor-client#2487]
### Describe the bug

So eh i got 1524 (before this i use 1520 without issue) and when i launch it, it crash, i using bunch of mod (u can view it in crash log) but most noticeable is meteor reject addon (maybe it culpit there, it work fine from 1520 tho) soo ehhhhhhh
[crash-2022-07-08_19.39.40-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9072114/crash-2022-07-08_19.39.40-client.txt)

### Steps to reproduce

```bash
1. get bunch of mod (look at crash log mam)
2. launch with 1524 (maybe on 1521-1523 as wwell but whatever it bug anyway)
3. crashed nerdddd
```

### Meteor Version

0.5.0 1524 dev build

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
This is an error with rejects. Open an issue on their github page with the crash report.

**Comment by ItsIsntItsKeera** [comment]
okie
