### ISSUE TITLE
[Bug] Friend Command Crash

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2488]
### Describe the bug

While using the friend add command, misspelling a name or attempting to add a player that isn't online crashes your game.

### Steps to reproduce

```bash
Enter a server and try to .friend add a player that isn't online.
```

### Meteor Version

1525

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 1b3343218675afe42c1cdfd1dda339cb4a23b0b7.
