### ISSUE TITLE
[Bug] Small Profile Bug

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2489]
### Describe the bug

When adding an IP to a profile, after leaving and returning to edit the profile the list setting itself displayed in will appear as though the IP has not actually been added, with the add button appearing on the same line instead of creating an empty new cell

### Steps to reproduce

```bash
- Link an IP to a profile
- Exit and reenter the edit profile screen
- Observe
```

### Meteor Version

Latest

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
this was fixed somewhen
