### ISSUE TITLE
[Suggestion] Paired List Setting

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2490]
### Describe the feature

A paired list setting type, probably using a hashmap to allow you to enter pairs of text that can be fetched

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Coep

**Comment by C10udburst** [comment]
Schizophrenia
