### ISSUE TITLE
Bow aimbot not working properly on Ender dragon[Bug] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2493]
### Describe the bug

Bow aimbot not working properly on Ender dragon even if i increase range to  max

### Steps to reproduce

```bash
its easy
```

### Meteor Version

latest dev build

### Minecraft Version

1.19

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ItsIsntItsKeera** [comment]
well eh due to whacky ender dragon hitbox, combine with fast movement, aimbot already almost impossible to aim/predict arrow that can hit ender dragon hitbox, it really hard to make it possible i think
