### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Rikko21** [MeteorDevelopment/meteor-client#2494]
### Describe the bug

Auto Eat does not function if the food is in your offhand

### Steps to reproduce

```bash
Put food in offhand, turn on Auto Eat
```

### Meteor Version

Latest Dev Build

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ItsIsntItsKeera** [comment]
Confirm on every version, it not intended for offhand but it would be neat
