### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mrplayergod** [MeteorDevelopment/meteor-client#2516]
### Describe the bug

When I got dirt or cobblestone on my inventory it start placing in random direction and when I tried mining, it start placing.

### Steps to reproduce

```bash
I pickup dirt and stone then it start to place everywhere.
```

### Meteor Version

1531

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by mrplayergod** [comment]
What shall I check? or do?

**Comment by ItsIsntItsKeera** [comment]
Can you give me what module you enable?

**Comment by mrplayergod** [comment]
Wait let me look at the module

**Comment by I-Got-You-Dead** [comment]
bruh #2471 🤡

**Comment by mrplayergod** [comment]
Anti anvil, Auto totem, Critical, Fake player, Reach, No fall, No slow, Sprint, Velocity, Better tooltip, Boss stack, Camera tweak, City esp, Entity owner, Fullbright, Hole esp, Nametag, No render, Trajectories, Tunnel esp, Unfocused cpu, Anti cactus, Anti packet kick, Auto reconnect, Better beacon, Better tab, Better chat, Discord presence, inventory Tweaks.

**Comment by mrplayergod** [comment]
Please help me

**Comment by ItsIsntItsKeera** [comment]
> Anti anvil, Auto totem, Critical, Fake player, Reach, No fall, No slow, Sprint, Velocity, Better tooltip, Boss stack, Camera tweak, City esp, Entity owner, Fullbright, Hole esp, Nametag, No render, Trajectories, Tunnel esp, Unfocused cpu, Anti cactus, Anti packet kick, Auto reconnect, Better beacon, Better tab, Better chat, Discord presence, inventory Tweaks.

Ummm there no module interfering with block placement, sorry

**Comment by mrplayergod** [comment]
How do i fix this?

**Comment by I-Got-You-Dead** [comment]
> How do i fix this?

Prob not a meteor issue

**Comment by mrplayergod** [comment]
Okay

**Comment by mrplayergod** [comment]
Help

**Comment by mrplayergod** [comment]
I think i got a solution what is that baritone command that let you place block behind you while you mine and use baritone?
