### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by EVclipz** [MeteorDevelopment/meteor-client#2517]
### Describe the bug

i am trying to get meteor client on feather client and it doesn't seem to work every time i try to open it, it crashed and comes up with a really long error message. and i have tried everything and nothing works.
![metor](https://user-images.githubusercontent.com/109055992/178186952-c09998cd-22be-4610-945d-813001a7fc2b.PNG)

### Steps to reproduce

```bash
i try to open the game and it doesnt work. is their anyway u could help me or fix this?
```

### Meteor Version

1.18.2

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
https://anticope.ml/incompatibilities/

**Comment by ItsIsntItsKeera** [comment]
If you are using 1.18.2 i think you can download stable build, bc since devbuild 1503 they have incompatibles issue sooooo

**Comment by EVclipz** [comment]
> https://anticope.ml/incompatibilities/

ah thank you that makes sense now
