### ISSUE TITLE
[Suggestion] No Render Title

### ISSUE THREAD

**Issue by awesomeusername69420** [MeteorDevelopment/meteor-client#2519]
### Describe the feature

An option in No Render to remove the title text that appears in the middle of the screen from '/title'

Useful for servers that annoy users with advertisements or spamming users to install the server resourcepack, especially while Server Spoof is enabled.

![image](https://user-images.githubusercontent.com/24661212/178351441-959a7f48-c1b8-4de2-ad33-4f68a5ccf485.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
Good idea

**Comment by Wide-Cat** [comment]
I'm 99% sure theres a packet you can cancel that prevents these messages from showing. Let me investigate further

**Comment by Wide-Cat** [comment]
Try cancelling 'TitleS2CPacket' and see if this works

**Comment by awesomeusername69420** [comment]
Cancelling 'TitleS2CPacket' and 'OverlayMessageS2CPacket' (For /title actionbar) gives the desired result, but packet blocking isn't as intuitive as preventing rendering although I guess it doesn't really matter in most cases.

Also, blocking 'SubtitleS2CPacket' doesn't appear to have any affect as just blocking 'TitleS2CPacket' will block both the regular title and the subtitle and blocking ONLY 'SubtitleS2CPacket' doesn't appear to affect anything.
