### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by catandmooseYT** [MeteorDevelopment/meteor-client#2522]
### Describe the bug

im using the meteor 1.19 dev build with multiconnect and sometimes when i disconnect from a server my game crashes

### Steps to reproduce

```bash
idk just reconnect and disconnect from servers until it happens
```

### Meteor Version

Dev Build 0.5.0 - 1535 [1.19]

### Minecraft Version

1.19 but im using multiconnect for 1.12

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
1. Did you make sure it happens because of Meteor? It might be just Multiconnect.
2. If yes then send the crash report.

**Comment by MineGame159** [comment]
Remove Meteor and see.
