### ISSUE TITLE
[Bug]  Game crashes when trying to load font

### ISSUE THREAD

**Issue by pikacan360** [MeteorDevelopment/meteor-client#2523]
### Describe the bug

My game crashes when it tries to load HP Simplified Bold font
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/9094518/latest.log)
[hs_err_pid1752.log](https://github.com/MeteorDevelopment/meteor-client/files/9102068/hs_err_pid1752.log)

### Steps to reproduce

```bash
I don't know how it just happens
```

### Meteor Version

Dev Build 0.5.0 - 1536 [1.19] /  Dev Build 0.5.0 - 1535 [1.19] are the ones I've tried

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by AnhNguyenlost13** [comment]
share your crash report too

**Comment by pikacan360** [comment]
> share your crash report too

Just added it

**Comment by NUKMUK** [comment]
I have this problem too
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/9133812/latest.log)

**Comment by MineGame159** [comment]
Fixed in 9a35451c9e7ad74b813731645c603c413e795b81.
