### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by mrplayergod** [MeteorDevelopment/meteor-client#2524]
### Describe the feature

I think meteor client should add a set anti cheat for like server for ncp or like other anarchy server anti cheat.
The command should be like ''.Anticheat ncp'' or ''.Anticheat ACC''.
I think meteor client should add this command, so people can if their crystal aura that is fast enough to bypass the anti cheat.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
There are literally hundreds of servers to test you clients on, so this is beyond useless.

Also it would be impossible to do this clientside.

**Comment by RacoonDog** [comment]
We do not condone the usage of this mod on servers where it is not allowed.
