### ISSUE TITLE
[Bug] Baritone loading after normal mixins, mixin order shits the bed

### ISSUE THREAD

**Issue by 0x3C50** [MeteorDevelopment/meteor-client#2526]
### Describe the bug

Since baritone loads differently in meteor, the mixin priority order is ignored, making it hard to make clients compatible with meteor

### Steps to reproduce

```java
1. Define a mixin redirect for LivingEntity#jump() at `getYaw()F`
   
@Redirect(method = "jump", at = @At(value = "INVOKE", target = "net/minecraft/entity/LivingEntity.getYaw()F"), require = 0)
    private float coffee_overwriteJumpDirection(LivingEntity instance) {
        if (instance.equals(CoffeeMain.client.player) && ModuleRegistry.getByClass(FreeLook.class).isEnabled() && !((boolean) FreeLook.instance()
                .getEnableAA()
                .getValue())) {
            return ModuleRegistry.getByClass(FreeLook.class).newyaw;
        }
        return instance.getYaw();
    }

2. Put priority 1001 on the mixin (should be loaded after meteor since meteor has prio 1000)
3. Put require = 0 on the redirect (should ignore any errors that occur with the redirect)
4. Launch the mod with the mixin with meteor
5. Observe
```

### Meteor Version

0.5.0 dev

### Minecraft Version

1.19.0

### Operating System

Linux

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Its1mpulse** [comment]
metor pls fix

**Comment by 0x3C50** [comment]
Can i get info on why this was closed @arlomcwalter

**Comment by RandomVersion** [comment]
tell us now

**Comment by arlomcwalter** [comment]
> Can i get info on why this was closed @arlomcwalter 

meteor doesn't change anything that would relate to this issue, if it is caused by baritone being packaged in meteor then it is an issue with fabric (but I don't think it is)

**Comment by arlomcwalter** [comment]
like idk what you mean "baritone" loads differently. how does it, can you point out what meteor does that would cause this?

**Comment by 0x3C50** [comment]
> like idk what you mean "baritone" loads differently. how does it, can you point out what meteor does that would cause this?

Look at the stacktrace. Meteor's being referenced in there, which means that it somehow influences how baritone loads in this case. Also see how the modules being initialized somehow leads to baritone's mixins loading, which also means that meteor is in direct contact with mixin to load baritone after the normal mixins from fabric have been initialized. Since that's the case, priority order is completely ignored, since normal game mixins will load before the baritone mixin, in every case, even if the priority is 9999 or require is 0, which means that one cannot fix this crash without either changing meteor itself or giving up on the feature that requires the mixin.

**Comment by RandomVersion** [comment]
> plse fix

yes plz fix

**Comment by MineGame159** [comment]
Meteor is referenced in there because we use custom ASM transformations for a small selected set of classes which none are from Baritone. In this case the `meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes` method call just acts as a simple proxy and not modifying anything. So as Snail already said, this doesn't seem like anything do to with Meteor or we include Baritone wrong.

**Comment by arlomcwalter** [comment]
its a conspiracy, meteor is deliberately stripping baritone's mixins of their priority and messing with your mixins to cause you issues 😄

**Comment by arlomcwalter** [comment]
can you show the whole class in a screenshot? (with imports)

**Comment by MineGame159** [comment]
My previous comment was for the Asm stack trace element, here is an explanation for the first method call from Meteor:

its shows our Modules class because we have an injection into mc's CrashReport class to add like the active modules and shit to the report and for whatever reason minecraft creates a new fake crash report at start but never throws it, so our injection gets called which then access the Modules class, but that class is not loaded yet so the jvm loads it and all of its dependencies and it just so happens that LivingEntity is its dependecy and hasnt been loaded before 

So both times Meteor appears in the crash report is just a coincidence and doesn't mean anything here.

**Comment by MineGame159** [comment]
Try removing Meteor from your mods folder and just straight up using Baritone itself.

**Comment by 0x3C50** [comment]
specifically the last mixin is shitting the bed

**Comment by 0x3C50** [comment]
also there's no baritone release for 1.19 so i can't really try it out with baritone alone

**Comment by MineGame159** [comment]
https://maven.meteordev.org/snapshots/baritone/fabric/1.19-SNAPSHOT

**Comment by 0x3C50** [comment]
> https://maven.meteordev.org/snapshots/baritone/fabric/1.19-SNAPSHOT

based

**Comment by hades3729** [comment]
https://github.com/cabaletta/baritone/actions/runs/2456528208

**Comment by 0x3C50** [comment]
doesn't work, same crash. maybe they changed how priority works and i have just been told the wrong thing?

**Comment by 0x3C50** [comment]
alr seems to work now, the mixin now crashes on my side, which i can fix. I thought higher mixin priority = called later, seems to not be the case anymore.

**Comment by 0x3C50** [comment]
next question is why does it fail with require = 0

**Comment by MineGame159** [comment]
I should have paid more attention to what you actually said and not just the crash report but yes lol, higher priority means its sooner.

**Comment by arlomcwalter** [comment]
disturbing code
anyway yeah its not related to meteor 👍

**Comment by MineGame159** [comment]
Also try using @Pseudo annotation instead of require = 0.

**Comment by 0x3C50** [comment]
> Also try using @pseudo annotation instead of require = 0.

Wouldn't see how that'd work, since pseudo is just for classes that might not exist at runtime. The error i'm facing here is that mixin still shits the bed even if i put require = 0 on the redirect that's causing the crash
