### ISSUE TITLE
Broken Auto Smelter [Bug]

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#2529]
### Describe the bug

Cant't select fuel or items to melt.

https://user-images.githubusercontent.com/95006470/179143985-ec541746-1f35-4f87-8f5f-b2dd1e3bb0a6.mp4

### Steps to reproduce

```bash
-
```

### Meteor Version

0.5.0 Dev Build Version - 1538

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by playeur242** [comment]
Only occur when opening gui from minecraft's main menu
