### ISSUE TITLE
Can't add a new [Bug] 

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#2531]
### Describe the bug

Can't add a new friend using this meteor version.

### Steps to reproduce

```bash
Meteor GUI> Friends> Enter the Name> Click "+"> and it's not added
```

### Meteor Version

0.5.0 Dev Build Version - 1538

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by playeur242** [comment]
just use .friend add for now

**Comment by Wide-Cat** [comment]
looks like this has been fixed
