### ISSUE TITLE
Add Seed Xray [Suggestion] 

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#2534]
### Describe the feature

https://youtu.be/tZclBnTvumg
https://github.com/19MisterX98/SeedcrackerX/releases

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
Meteor rejects 💀

**Comment by playeur242** [comment]
just use meteor reject : oresim module
