### ISSUE TITLE
[Suggestion] Have 2 more versions for the latest SNAPSHOT version.

### ISSUE THREAD

**Issue by emir4169** [MeteorDevelopment/meteor-client#2536]
### Describe the feature

I want two more downloads for dev builds and normal builds of the latest snapshot version.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Maintaining releases for a MC version that is not yet stable is counterproductive and prone to creating bugs.
This is why we usually keep only a stable and dev release.
