### ISSUE TITLE
HUD Edit missing all options[Bug] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2537]
### Describe the bug

Earlier when i opened Hud and then clicked edit...it looked like
![unknown](https://user-images.githubusercontent.com/70203048/179223570-051c1de7-a2d2-4e44-b44e-f658efe07c07.jpg)

Then i reinstalled meteor completely..had to again set all keybinds...but...in HUD after clicking edit it shows just some options
![image](https://user-images.githubusercontent.com/70203048/179222625-712416a7-6fb9-4b5d-b92c-4150fbef63c4.png)

### Steps to reproduce

```bash
i uploaded screenshots
```

### Meteor Version

latest dev build

### Minecraft Version

1.19

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Have you tried right clicking to add new elements?

**Comment by procrafter820** [comment]
oh ok
