### ISSUE TITLE
please give me credit for the elytra fly and speed

### ISSUE THREAD

**Issue by linustouchtips** [MeteorDevelopment/meteor-client#254]
@seasnail8169 give me credit >:(

awa
uwu
owo

we do a little trollin - grandolive

**Comment by supakeks** [comment]
wtf seasnail being a monkey again

**Comment by seasnail8169** [comment]
neither are yours bruh???

**Comment by seasnail8169** [comment]
i didn't even write elytra and it hasn't changed in like months, speed is not your speed either

**Comment by GhostTypes** [comment]
![le_monke](https://user-images.githubusercontent.com/31757267/108004388-b6bbd100-6fc3-11eb-9dc1-8fae9d82a52f.jpg)

**Comment by olliem5** [comment]
😕 seems like momentum to me...
