### ISSUE TITLE
[Bug] hud fucked on big monitors

### ISSUE THREAD

**Issue by TaxEvasiqn** [MeteorDevelopment/meteor-client#2541]
### Describe the bug

dragging/editing hud elements is fucked on monitors that arent 1920x1080 or whatever

### Steps to reproduce

```bash
own a big monitor
mess with the hud
```

### Meteor Version

1541 (website says 1543 but i dont think you updated the gradle properties)

### Minecraft Version

1.19

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
How big is ur monitor?

**Comment by MineGame159** [comment]
Can you post a video or something because what am I supposed to do, go buy a new monitor?

**Comment by DarkReaper231** [comment]
> Can you post a video or something because what am I supposed to do, go buy a new monitor?

🤣🤣🤣🤣🤣🤣🤣

**Comment by TaxEvasiqn** [comment]
https://youtu.be/NkW-8qiUCzc

**Comment by jsmith64pro** [comment]
I've experienced this same issue, I don't think it's because the monitor is big, but because it's a Retina display (same issue may also occur on non-Apple high-DPI screens, not sure.)
One of the corners of the selection box correctly follows the mouse cursor, but the rest of the HUD editor seems to be failing to take into account the display scaling, and sees the coordinates as half of what they should be.

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/181862463-e14d0c02-220b-4793-b2f2-36e77b775104.png)

Can confirm Meteor doesn't seem to have any DPI scaling.

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/181864674-bc9e24f6-d38f-414b-84ce-b645d1b6bd75.png)

Found the scale settings! I think this issue can be closed

**Comment by jsmith64pro** [comment]
I think you've missed the point of the issue - it's not about visual scale, but about the mouse input. TaxEvasiqn posted a video showing the bug. The video also shows another bug where the properties window appears very wide, which was closed as fixed but I've still encountered (I'll reopen the issue shortly).

**Comment by LoganDark** [comment]
> I think you've missed the point of the issue - it's not about visual scale, but about the mouse input. TaxEvasiqn posted a video showing the bug. The video also shows another bug where the properties window appears very wide, which was closed as fixed but I've still encountered (I'll reopen the issue shortly).

Ah, that makes sense, nevermind then.

**Comment by seasnail8169** [comment]
#2661
