### ISSUE TITLE
[Suggestion] Skin blinker

### ISSUE THREAD

**Issue by Z3r0ut** [MeteorDevelopment/meteor-client#2543]
### Describe the feature

Like the title says, a Skin blinker module. It should have the ability to turn certain parts of the outer skin layer on and of in a given interval.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
Bro… this is in banana+ so just use it 💀

**Comment by Z3r0ut** [comment]
> Bro… this is in banana+ so just use it 💀

Totally forgott that Meteor has Addons. Thanks.

**Comment by I-Got-You-Dead** [comment]
Lmao np
