### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by StealthoWillow** [MeteorDevelopment/meteor-client#2544]
### Describe the bug

When changing the author of a book it changes back to the person who actually wrote it.

### Steps to reproduce

```bash
Just change a book author and it should just turn back to the person who wrote it.
```

### Meteor Version

0.4.9

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
It’s client side 🤡

**Comment by Wide-Cat** [comment]
You need to be in creative mode to actually change the title and author, otherwise it wont work properly
