### ISSUE TITLE
[Suggestion] Auto Recconect Addon

### ISSUE THREAD

**Issue by Spicymang04** [MeteorDevelopment/meteor-client#2547]
### Describe the feature

If you have Auto Recconect and Auto Log enabled, Auto Recconect will disable when Auto Log disconnects you.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Wide-Cat** [comment]
has been added
