### ISSUE TITLE
[Bug] Add hud element bug

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#2552]
### Describe the bug

I have a 30 inch ultrawide monitor, I'm not sure if this interferes with the text of this but when I try to add a hud element, all of the text is not aligned with the box it's supposed to be in.
![2022-07-19_14 38 18](https://user-images.githubusercontent.com/72416130/179853028-754c6c5f-0dd8-4d44-bd0d-036485e54923.png)
 

### Steps to reproduce

```bash
Go to the hud element section and it should just automatically do it.
```

### Meteor Version

meteor-client-0.5.0-1554

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
#1854
