### ISSUE TITLE
1

### ISSUE THREAD

**Issue by DestructiveTransformator** [MeteorDevelopment/meteor-client#2555]
1

**Comment by RacoonDog** [comment]
*sniff*
smells like trying to bypass an anticheat

**Comment by SplashAni** [comment]
burh

**Comment by Jonathan274** [comment]
Liquid bounce has this feature, works great on hypixel

**Comment by ItzSkyReed** [comment]
> _sniff_ smells like trying to bypass an anticheat

For me This feature will help with farms. Not for pvp

**Comment by CodeDoc537** [comment]
Not a client for bypassing servers. Made for anarchy communities.

**Comment by playeur242** [comment]
> Not a client for bypassing servers. Made for anarchy communities.

can be useful for spawners that is strict about the delay it take to spawn mobs (yes as a newbie i anarchy i do farm xp to repair my armors with spawners)
