### ISSUE TITLE
[Suggestion] An auto update for modules and buspgs

### ISSUE THREAD

**Issue by cOdEx567** [MeteorDevelopment/meteor-client#2556]
### Describe the feature

This is a good feature bc it would save a lot of time as to go to the dev builds and re-installing the whole  module and re-configurating as it’s a bit annoying installing all the dev-builds. And as well and hyper hack clients uses an auto update to implement bugs and modules to the hack client. If u could make it it would be great as u can update it whenever u want.

But a bad thing it can create a security issue but I think I’m confident that u can make it as good as possible.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
1. Your english is incomprehensible (took me 3 re-reads to understand what you wanted).
2. To update a devbuild, you just delete the current Meteor JAR and install the newer one.
3. To save all your configs, you can simply make a profile in the Profiles tab.

**Comment by I-Got-You-Dead** [comment]
All you would have to do is make it opt-in to fix the security issue

**Comment by Lovecrafts-Cat** [comment]
Of course, who wouldn't want to opt in to a potentially unsafe feature...

You do realize there are already scripts that automatically update Meteor, right?

**Comment by I-Got-You-Dead** [comment]
Yea

**Comment by I-Got-You-Dead** [comment]
> 

Having it built in will make it much easier for users who have no brain cells

**Comment by Lovecrafts-Cat** [comment]
Then there is no reason to add an automatic updater, since people can use those instead.

**Comment by I-Got-You-Dead** [comment]
> Having it built in will make it much easier for users who have no brain cells

And will stop them from crying in the dc

**Comment by Lovecrafts-Cat** [comment]
For all I care, they can keep coping about it.
The average user doesn't understand the risks of a process which can automatically download from the web.

[This](https://paste.gg/p/anonymous/876453c66ea941e094d6afc81e375c32) works perfectly.

**Comment by Wide-Cat** [comment]
See the link Lovecraft sent
