### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by UnrealDestroyerOne** [MeteorDevelopment/meteor-client#2557]
### Describe the feature

make it available on forge plz. so i can play with optifine too

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
No

**Comment by Lovecrafts-Cat** [comment]
Never will be compatible with either Forge or Optifine.
If you want to use shaders, or need FPS boosts, use [these](https://lambdaurora.dev/optifine_alternatives/) mods.

**Comment by cqb13** [comment]
you can use sodium as a replacement for optifine on fabric. if you want shaders use iris.
