### ISSUE TITLE
[Bug] Crash when use with Camera Utils mod

### ISSUE THREAD

**Issue by Crusader-s** [MeteorDevelopment/meteor-client#2561]
### Describe the bug

The game just crash
Can't provide crash report, don't know where to find it

### Steps to reproduce

```bash
1. Have both Camera Utils and Meteor active
2. Do anything that change your perspective (f5, enter free cam, etc)
```

### Meteor Version

0.5.0 build #1562

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
.minecraft/logs/latest.log
Ggogle has answers for these simple questions.

**Comment by starboyceleste** [comment]
[crash-2023-04-20_01.52.14-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/11284313/crash-2023-04-20_01.52.14-client.txt)
camera utils is still causing this crash.
