### ISSUE TITLE
[Bug] Cracked account crash

### ISSUE THREAD

**Issue by GYF0814** [MeteorDevelopment/meteor-client#2562]
### Describe the bug

Cracked account will crash when loading the game.

### Steps to reproduce

```bash
Just use a cracked account.
```

### Meteor Version

0.5.0-1562

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by mrplayergod** [comment]
My game is fine with crack account how is yours crashing?

**Comment by mrplayergod** [comment]
Maybe you have a bad pc or just over use your ram I think am not an expert

**Comment by Wide-Cat** [comment]
Can you send the crash report

**Comment by GYF0814** [comment]
This is the crash report.
[minecraft-exported-crash-info-2022-07-22T18-13-14.zip](https://github.com/MeteorDevelopment/meteor-client/files/9173012/minecraft-exported-crash-info-2022-07-22T18-13-14.zip)

**Comment by GYF0814** [comment]
There's latest.log in it

**Comment by GYF0814** [comment]
> Maybe you have a bad pc or just over use your ram I think am not an expert

i used 4gb ram and it couldn't crash because of it.

**Comment by GYF0814** [comment]
Fixed :)
