### ISSUE TITLE
[Bug]  Xray only works for a split second

### ISSUE THREAD

**Issue by emir4169** [MeteorDevelopment/meteor-client#2565]
### Describe the bug

When xray is enabled no matter the xray setting. Xray will stop working after a split second.

### Steps to reproduce

```bash
1. own meteor
2. enable xray
3. reproduced!
```

### Meteor Version

1563

### Minecraft Version

1.19 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Works on my machine.
Could you post your mod list please?
Also, are you sure the server isn't running an anti x-ray plugin?

**Comment by AdvocateWalker** [comment]
If you are on 1.18.2 remove fabric API.
