### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by LMCmadman** [MeteorDevelopment/meteor-client#2566]
### Describe the feature

Allow Pojavlauncher can use meteor client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Minecraft in the phone is Bedrock edition, while Meteor, being a Java mod, is incompatible.

**Comment by CodeDoc537** [comment]
> Minecraft in the phone is Bedrock edition, while Meteor, being a Java mod, is incompatible.

projavlauncher is a way to play Java on mobile. it’s dumb

**Comment by CodeDoc537** [comment]
But not going to happen, use a pc.

**Comment by Wide-Cat** [comment]
If I remember correctly it's because discord RPC is enabled by default, which crashes on pojav. You can work around it by getting a config that already has it disabled
