### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Wikbert20** [MeteorDevelopment/meteor-client#2568]
### Describe the feature

i dont know if my suggestion is already in work but an Auto Drop feature where u can select an item wich will be droped immediatly would be great

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Already in the modules list 😒

**Comment by RickyTheRacc** [comment]
Already exists inside the inventory tweaks module

**Comment by hellidox** [comment]
search
auto drop

**Comment by isaacc100** [comment]
its already in inventory tweaks
