### ISSUE TITLE
[Suggestion] Hud Item Counter improvement

### ISSUE THREAD

**Issue by Radial2250** [MeteorDevelopment/meteor-client#2569]
### Describe the feature

make the item counter in the hud display a number "0" when there is none of the selected item present, instead of there being no number at all

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Could just have the same functionality as before, hide the element if there's none left

**Comment by AdvocateWalker** [comment]
Why?

**Comment by Radial2250** [comment]
rickys suggestion is probably better, its just easier to check the number of totems at a glace if there is an actual number 0 (or it dissapears) than there being an empty icon

**Comment by MineGame159** [comment]
Added a setting in 158ee1b4d20c0299883d44651c4759feb2cc4c49.
