### ISSUE TITLE
[Bug] Crash on startup "Failed to load font"

### ISSUE THREAD

**Issue by Pandaver** [MeteorDevelopment/meteor-client#2570]
### Describe the bug

Game crashes on startup with exit code: 1

jdk-17.0.3.7 from https://adoptium.net/
And try jdk-18 from oracle still not work
MulitMC 0.6.16-3431
Fabric Loader 0.14.8 install from MulitMC
**Mod just enable Meteor Client**
log: [hs_err_pid10616.log](https://github.com/MeteorDevelopment/meteor-client/files/9177772/hs_err_pid10616.log)

### Steps to reproduce

```bash
Launching the client
```

### Meteor Version

0.5.0-1538   0.5.0-1554   0.5.0-1562   0.5.0-1565

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Fixed in 9a35451c9e7ad74b813731645c603c413e795b81.
