### ISSUE TITLE
How do i download meteor dev build -0.50.0-1516 [Bug] 

### ISSUE THREAD

**Issue by procrafter820** [MeteorDevelopment/meteor-client#2571]
### Describe the bug

How do i download meteor dev build -0.50.0-1516 ,as after that all the dev builds like 1556,1557,1565 etc.. are unstable

### Steps to reproduce

```bash
...
```

### Meteor Version

...

### Minecraft Version

1.19

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
ong

#dev-builds in discord 🤡

**Comment by I-Got-You-Dead** [comment]
and they are stableish, its prob ur addons causing crashes.

**Comment by procrafter820** [comment]
> ong
> 
> #dev-builds in discord 🤡

It shows error,i think the file has been removed

**Comment by procrafter820** [comment]
> and they are stableish, its prob ur addons causing crashes.

I just use Sodium addon and those like meteor rejects etc..

**Comment by MineGame159** [comment]
You can't. They aren't unstable there have just been a few changes for addons they have to update for.
