### ISSUE TITLE
[Suggestion] Language support.

### ISSUE THREAD

**Issue by spacewaretwo** [MeteorDevelopment/meteor-client#2572]
### Describe the feature

Here is such a list of ranges. If this one doesn't fit, I can make another one.
[ranges.txt](https://github.com/MeteorDevelopment/meteor-client/files/9179276/ranges.txt)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by LoganDark** [comment]
wtf is a "list of ranges"? Can you add it inside a code block directly instead of making people download a text file?

**Comment by spacewaretwo** [comment]
There was already an example of the code #1868 , but they asked not for a specific language or to throw off the documentation of ranges, so I provide this list.
