### ISSUE TITLE
[Bug] Inventory Tweaks Auto Drop Removes Armor

### ISSUE THREAD

**Issue by isaacc100** [MeteorDevelopment/meteor-client#2575]
### Describe the bug

When i turn auto drop on it drops my helmet and chestplate.

### Steps to reproduce

```bash
1 Equip armour
2 Turn Auto Drop on with the armour items selected
3 Your Hat and Chestplate get dropped
```

### Meteor Version

0.5.0 1565

### Minecraft Version

1.19

### Operating System

macOS

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
> Turn Auto Drop on with the armour items selected

Well i think it's pretty obvious it would do that.
It's for sure a side effect, wich could be possibly handled by addig a "Equipped" toggle to ignore equipped armor.
