### ISSUE TITLE
[Suggestion] Anti poopoo item pickup

### ISSUE THREAD

**Issue by RaceIsIm** [MeteorDevelopment/meteor-client#2579]
### Describe the feature

hey kid thank for fix font bug. add anti pickup for poopoo items, it lets you make a full auto sorting system for a farm using your inventory, (i know theres auto drop but pls add anti pickup)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
> add anti pickup

There is no way to tell the server "I don't want to pick this item up", so it's not possible.

**Comment by RickyTheRacc** [comment]
This community consistently reaches new lows

**Comment by RaceIsIm** [comment]
black people!
