### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by IDKIJUSTUSEIT** [MeteorDevelopment/meteor-client#2581]
### Describe the feature

A module to find different locations

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by tympanicblock61** [comment]
> ### Describe the feature
> A module to find different locations
> 
> ### Before submitting a suggestion
> * [x]  This feature doesn't already exist in the client.
>   (I have checked every module and their settings on the **latest dev build**)
> * [x]  This wasn't already suggested.
>   (I have checked every suggestion on github)
> * [x]  This feature is a valid suggestion.
>   (I have read the FAQs and Guides)

what you want is a seedcracker which you can already download

**Comment by AdvocateWalker** [comment]
Its called locate. either Baritone or meteor has this, and it can only search loaded chunks. pretty good for strongholds, fortresses etc. But using the Search module while configing the blocks that make up the structure is far better
