### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SSoggyBreadd** [MeteorDevelopment/meteor-client#2582]
### Describe the bug

![image](https://user-images.githubusercontent.com/110183209/181563234-3dbd9d1a-96f9-403f-a3fb-f956ea333b7b.png)

### Steps to reproduce

```bash
I receive this error every time I open Meteor Client on fabric. This problem doesn't occur when I don't have meteor client.
```

### Meteor Version

0.5.0

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
What made you think Meteor is for 1.19.1 you dingus?

**Comment by Lovecrafts-Cat** [comment]
Also, for further reference, sending that screenshot is useless, what you should send instead is the `.minecraft/logs/latest.log` file.
