### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Gitsume** [MeteorDevelopment/meteor-client#2584]
### Describe the bug

If you have items put in your crafting slots with xcarry and go thru nether portal the items disappear.

### Steps to reproduce

```bash
Put items in crafting slots and go thru a nether portal
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
Cope

**Comment by seasnail8169** [comment]
thats just the way it has to work, cant do anything about it
