### ISSUE TITLE
[Suggestion] autovillager

### ISSUE THREAD

**Issue by phvkuhkk** [MeteorDevelopment/meteor-client#2587]
### Describe the feature

Make a module that will reset a villagers trades untill the selectet enchant is a trade

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Meteor villager roller is already an existing addon, so use that.

**Comment by DesiCow** [comment]
Would be nice having this addon merged into Meteor client itself.

**Comment by Lovecrafts-Cat** [comment]
No need to merge something that works perfectly by itself honestly. 
Ask the addon dev if he wants to do so, but he'll most likely refuse as it's his project to maintain.

**Comment by Maxo6453** [comment]
https://anticope.ml/addons/?addon=maxsupermanhd%2Fmeteor-villager-roller
