### ISSUE TITLE
[Suggestion] for better beacon

### ISSUE THREAD

**Issue by alptuna1** [MeteorDevelopment/meteor-client#2588]
### Describe the feature

I like the new better beacon but can you guys add better beacon some modules like extra range?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Not possible.
