### ISSUE TITLE
[Bug] NullPointerException on launch

### ISSUE THREAD

**Issue by EthanZeigler** [MeteorDevelopment/meteor-client#2592]
### Describe the bug

When launching the client this morning, I got a nullptr exception from the hud code. Client wouldn't boot until I deleted the `hud.nbt` file from the meteor folder which i've attached below.

[hud.nbt.zip](https://github.com/MeteorDevelopment/meteor-client/files/9229131/hud.nbt.zip)

### Steps to reproduce

```bash
Played around with the HUD yesterday, but i can't give any more than that because I don't know what I did to cause it.
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
send the crash report

**Comment by EthanZeigler** [comment]
Whoops. Thought I had. Will give in the afternoon (8 hours)
