### ISSUE TITLE
2D Hitboxes

### ISSUE THREAD

**Issue by Sprink02** [MeteorDevelopment/meteor-client#2593]
### Describe the feature

Instead of having the hitbox extend in all 3 dimensions only extend it in 2d so it does not add "reach". 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Or just don't use hitboxes

**Comment by Wide-Cat** [comment]
theres no point in that
