### ISSUE TITLE
[Bug] game crashes when i press a macro

### ISSUE THREAD

**Issue by harrykotten** [MeteorDevelopment/meteor-client#2595]
### Describe the bug

so i have a macro fro /home on mousebutton 5 and when i press it the whole game crashes

### Steps to reproduce

```bash
you press your macro button and it crashes the game
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by thetrooper2281337** [comment]
yes bug still valid

**Comment by seasnail8169** [comment]
upload crash report

**Comment by maplepy** [comment]
Does the update meteor received fixes this annoying bug?

**Comment by seasnail8169** [comment]
cant fix it without some sort of crash report, the bug doesn't happen for me

**Comment by harrykotten** [comment]
hmm weird, i have one thought, @seasnail8169  do you use the old mc lancher or the new one?
i have the old one

**Comment by harrykotten** [comment]
1.

**Comment by Wide-Cat** [comment]
I noticed this as well, but this should be resolved as of e5d978e0ddba0bec977015355fc2a6245d272ba6. If it isn't, reopen this issue with a crash report attached.

**Comment by thetrooper2281337** [comment]
@seasnail8169 with the lastest meteor dev build crash fixed

**Comment by seasnail8169** [comment]
yeah

**Comment by maplepy** [comment]
> @seasnail8169 with the lastest meteor dev build crash fixed

Game crashes instantly with the latest dev build

**Comment by maplepy** [comment]
#2642
