### ISSUE TITLE
[Suggestion] Make macros not send an empty chat message to the server.

### ISSUE THREAD

**Issue by I-Got-You-Dead** [MeteorDevelopment/meteor-client#2596]
### Describe the feature

^^^

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Fr lol

**Comment by I-Got-You-Dead** [comment]
Pain in the ass on ecme

**Comment by I-Got-You-Dead** [comment]
welp has been forgotten about :l

**Comment by seasnail8169** [comment]
literally just dont send an empty message

**Comment by I-Got-You-Dead** [comment]
Do something like .server or any other meteor command

**Comment by I-Got-You-Dead** [comment]
It still sends a chat message to the server

**Comment by seasnail8169** [comment]
no, you are adding an empty item to the list by mistake, you don't need to do that

**Comment by I-Got-You-Dead** [comment]
I’ll play around with it but Would being on 1.18.2 have something to do with it

**Comment by I-Got-You-Dead** [comment]
Ok so I see what you mean but like, it’s a bit confusing ngl

**Comment by seasnail8169** [comment]
it would be confusing either way, the ui just needs to be improved
