### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by electronphenom** [MeteorDevelopment/meteor-client#2597]
### Describe the feature

Was pretty disappointed to see the FAQ doesn't include an instruction for the need for Fabric and its API, i thought it used to, not very helpful for new players :/ now i am going to have to tell everyone i recommend it to :/

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
![image](https://user-images.githubusercontent.com/52252627/182162143-065c06ef-4640-41ce-91fe-c13b96ce51b2.png)

Meteor doesn't require the FabricAPI, oly the Fabric Loader to create Fabric instances.

**Comment by electronphenom** [comment]
oh sorry i see now, how confusing, having 2 install guides, maybe the one on the FAQ page should say, click on the Installation link on the right, the above info should be where the obscure info is on the main FAQ page for simplicity sake!
I will make sure in future, that i take the extra steps to also inform people of the installation link they need to click.
