### ISSUE TITLE
[Bug] Switching To Microsoft Account Causes Error Joining Servers

### ISSUE THREAD

**Issue by Frontesque** [MeteorDevelopment/meteor-client#2598]
### Describe the bug

Joining any multiplayer server on Meteor 0.5.1 after changing microsoft accounts via the account switcher causes the error shown below
![IXZUUwGG](https://api.celeste.photos/uploads/ee556ec1-7ac3-44ea-a1f0-541667d58879/IXZUUwGG.png)

Account switcher that I'm referencing for anyone unfamiliar
![xeYg3iPq](https://api.celeste.photos/uploads/ee556ec1-7ac3-44ea-a1f0-541667d58879/xeYg3iPq.png)

### Steps to reproduce

```bash
1. Open Minecraft w/ Meteor
2. Click "Multiplayer"
3. Click "Accounts" in top right
4. (if a second account isn't already linked) Link account by clicking "Microsoft"
5. Click "Login" next to another account
6. Press "esc/escape" on your keyboard
7. Select any multiplayer server
8. Error: "Invalid signature for profile public key. Try restarting your game."
```

### Meteor Version

0.5.1 (0.5.0 works)

### Minecraft Version

1.19.1 (1.19 works, this is likely due to microsoft's chat changes in 1.19.1)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by AchievedZeus574** [comment]
I was able to reproduce without using the account switcher at all. Can also join servers that allow cracked accounts.

**Comment by Frontesque** [comment]
> I was able to reproduce without using the account switcher at all

how did you reproduce without using the switer? When I switch back to my main, the issue goes away without restarting the client. Not exactly sure how that'd work

**Comment by AchievedZeus574** [comment]
I guess the issue is of a different cause. I found that I wasn't able to join a game when the chat reporting was disabled client side. Using another client I could reenable chat reporting and join without issue.

**Comment by Frontesque** [comment]
ok this may actually be a spigot/bukkit/paper issue as per [PaperMC/Paper#105](https://github.com/PaperMC/Paper/commit/4a00cee9ccc1e7e14b3d58781d4f85a58fa96f9c)

**Comment by wmantly** [comment]
I can also confirm this issue. Works fine with the account used from the official lunch. Switching cusses the error. Switching back works fine.

**Comment by seasnail8169** [comment]
does this happen on the latest dev build?

**Comment by wmantly** [comment]
I built meteor client from clone of master 924b333361a4e6e83dd17459a430e7f2cd0fa3b3 and this bug is still present.

**Comment by seasnail8169** [comment]
i can't reproduce it

**Comment by seasnail8169** [comment]
> I built meteor client from clone of master 924b333361a4e6e83dd17459a430e7f2cd0fa3b3 and this bug is still present.

is this not the same as #2704? have you tried doing what they did

**Comment by Frontesque** [comment]
> > I built meteor client from clone of master 924b333361a4e6e83dd17459a430e7f2cd0fa3b3 and this bug is still present.
> 
> is this not the same as #2704? have you tried doing what they did

I believe this is a different issue. I could be wrong.

**Comment by wmantly** [comment]
It is a different issue. I get the same error message as the first comment. I have tried removing the accounts and re-adding them. I have tried on a few servers with no luck. What server are you using? I mainly play on core journey.org where the error happens

**Comment by wmantly** [comment]
Any update?

**Comment by I-Got-You-Dead** [comment]
No, cope
