### ISSUE TITLE
[Bug] Click Tp doesn't work with a shield

### ISSUE THREAD

**Issue by LoganDark** [MeteorDevelopment/meteor-client#2599]
(I would have written this differently if I had waited a while before filing the issue, but in the interest of transparency I'm preserving the original writing below including any swearing. Please let me know if I should rewrite it to be less angry.)

### Describe the bug

So I was on a server and had this idiot on my ass hunting me down because I got to a crate before they did. I have Click Tp permanently on, but couldn't use it to escape because I had a shield equipped so it completely refused to work.

This jerk literally waited at my logout spot for like 10 minutes for me to log back in so they could kill me. The 0.5 seconds I had to take to try to move the shield got me killed.

Considering a shield is so common to have equipped on PVP servers I really really think there should be a setting to make it not care about the shield.

### Steps to reproduce

```bash
1. Equip shield
2. Try to save your own life
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
Lol get fucked idiot stop using meteor to cheat on smps

**Comment by LoganDark** [comment]
> Lol get fucked idiot stop using meteor to cheat on smps

This response was completely unwarranted and is unrelated to the issue. The tone may be a little off since I was frustrated while writing it, but there are legitimate reasons to improve Meteor modules other than "cheating on smps".

**Comment by LoganDark** [comment]
> refer to rule 3 in meteor's discord. Stop cheating in servers which don't allow it.

I'm not in the Discord, but PVP doesn't only happen in servers that ban hacking.

Muting the thread since "stop hacking" is not constructive criticism.

**Comment by ManInMyVan** [comment]
> refer to rule 3 in meteor's discord. Stop cheating in servers which don't allow it.

The rule is _discussion_ of cheating not cheating in general.
