### ISSUE TITLE
[Bug] items get stuck in inventory slots.

### ISSUE THREAD

**Issue by starchyunderscore** [MeteorDevelopment/meteor-client#2600]
### Describe the bug

seemingly randomly, items will get stuck in inventory slots. they cannot be moved or dropped. this affects the inventory, storage containers, and villagers, though with villagers it is odd, trades look like they works but if you leave the villager you can see that they didn't actually.

you can still pickup and place items, as well as use pickblock to swap blocks in your hotbar (both shown in video)

I have tried this with all kinds of modules enabled and disabled, other mods loaded and just meteor, etc.

the ways to gain control of your inventory back, ranked from most reliable to least reliable

100% reliable: leave the game and rejoin

90% reliable: swim in water (shown in attached video)

50% reliable: sleep in a bed

20% reliable: disable and reenable all modules

https://www.youtube.com/watch?v=lxd80nBtWdE

### Steps to reproduce

```bash
i have no idea. literally just playing the game normally, sometimes it doesnt happen for hours, sometimes it happens every few minutes. i have repeated it many times, though never with any distinct defining event that causes it.
```

### Meteor Version

0.5.1, 0.5, 0.4.9

### Minecraft Version

1.19, 1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
is this on a server?

**Comment by starchyunderscore** [comment]
> is this on a server?

yes

**Comment by RacoonDog** [comment]
isnt this a baritone setting

**Comment by starchyunderscore** [comment]
> isnt this a baritone setting

**Comment by RacoonDog** [comment]
you can stop clicking random buttons now

**Comment by starchyunderscore** [comment]
> you can stop clicking random buttons now

im sorry the "close with comment" button is super annoying i dont usually use github on this platform

**Comment by I-Got-You-Dead** [comment]
> > is this on a server?
> 
> yes
> 
> edit: though i must mention that this does not happen on that server without meteor

Prob an anticheat

**Comment by I-Got-You-Dead** [comment]
Try .toggle all off

**Comment by starchyunderscore** [comment]
> Try .toggle all off

will do tmmr

**Comment by starchyunderscore** [comment]
> Try .toggle all off

so it does seem to stop when i do .toggle all off, and it only happens on the one server, so one of the render mods (since i only had render ones toggled on) was getting me anticheated. no clue why byt i think thats solved, ill close thw issue as the problem was not necisarilly the client.
