### ISSUE TITLE
[Bug] Unable to build

### ISSUE THREAD

**Issue by NGT233** [MeteorDevelopment/meteor-client#2603]
### Describe the bug

PS F:\meteor-client> ./gradlew build
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :
Fabric Loom: 0.12.55
Loom is applying dependency data manually to publications instead of using a software component (from(components["java"])). This is deprecated and will be removed in Loom 0.13.
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
Deprecated Loom APIs were used in this build, making it incompatible with future versions of Loom. Use Gradle warning modes to control the verbosity of the warnings.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'meteor-client'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not resolve baritone:fabric:1.19-SNAPSHOT.
     Required by:
         project :
      > Could not resolve baritone:fabric:1.19-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.meteordev.org/baritone/fabric/1.19-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://maven.meteordev.org/baritone/fabric/1.19-SNAPSHOT/maven-metadata.xml'. Received status code 523 from server:

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
PS F:\meteor-client> ./gradlew.bat

> Configure project :
Fabric Loom: 0.12.55
Loom is applying dependency data manually to publications instead of using a software component (from(components["java"])). This is deprecated and will be removed in Loom 0.13.
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
Deprecated Loom APIs were used in this build, making it incompatible with future versions of Loom. Use Gradle warning modes to control the verbosity of the warnings.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'meteor-client'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not resolve baritone:fabric:1.19-SNAPSHOT.
     Required by:
         project :
      > Could not resolve baritone:fabric:1.19-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.meteordev.org/baritone/fabric/1.19-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://maven.meteordev.org/baritone/fabric/1.19-SNAPSHOT/maven-metadata.xml'. Received status code 523 from server:

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
![image](https://user-images.githubusercontent.com/96066999/182563616-bc88263e-70fb-4db5-b5ba-f55cd888fb8f.png)

### Steps to reproduce

```bash
run ./gradlew build
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
stoobid

**Comment by NGT233** [comment]
？？

**Comment by RegalAether** [comment]
the maven is down

**Comment by MineGame159** [comment]
Fixed.
