### ISSUE TITLE
[Suggestion] Spoof resource pack without brand

### ISSUE THREAD

**Issue by LoganDark** [MeteorDevelopment/meteor-client#2604]
### Describe the feature

I already have a mod that changes my client's brand to "Kitchen-Aid KMT-223 2-Slice Toaster With One Touch Lift", so I don't need Meteor's. But being able to reject these annoying custom resource packs would be great.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RegalAether** [comment]
just use meteor's server spoof and delete the mod

**Comment by LoganDark** [comment]
@RegalAether Please don't spam the issue tracker.
