### ISSUE TITLE
[Suggestion] BetterChat - Secure Message Toggle

### ISSUE THREAD

**Issue by NakyoykaN** [MeteorDevelopment/meteor-client#2606]
### Describe the feature

Add an option to enable/disable secure message (encrypted/not encrypted) for 1.19.1+

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by AchievedZeus574** [comment]
This should in theory fix the issue with not being able to join vanilla servers that require official accounts.

**Comment by RegalAether** [comment]
already exists, no signatures in server spoof

**Comment by RegalAether** [comment]
> This should in theory fix the issue with not being able to join vanilla servers that require official accounts.

no + buy the game

**Comment by AchievedZeus574** [comment]
No I do own the game. Using a client that allows for me to reenable chat reporting, I join just fine. If I turn it off mid game and try to chat I get kicked for not having a signed chat message
