### ISSUE TITLE
[Suggestion] Add to Forge

### ISSUE THREAD

**Issue by 0Ariel0** [MeteorDevelopment/meteor-client#2607]
### Describe the feature

yes I know, it's stupid, but I wanted to forge so I could play with mods with it and there are several mods for fabric but much more for forge and there are modpacks with several mods and it's just for forge, please add to forge you don't even need changing nothing or adding anything is just putting it to forge.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Shut up retard

**Comment by Vitalasy** [comment]
![image](https://user-images.githubusercontent.com/94053086/182746365-64416fc2-f88d-4e29-a790-c09856b92e05.png)


> ### Describe the feature
> yes I know, it's stupid, but I wanted to forge so I could play with mods with it and there are several mods for fabric but much more for forge and there are modpacks with several mods and it's just for forge, please add to forge you don't even need changing nothing or adding anything is just putting it to forge.
> 
> ### Before submitting a suggestion
> * [x]  This feature doesn't already exist in the client.
>   (I have checked every module and their settings on the **latest dev build**)
> * [x]  This wasn't already suggested.
>   (I have checked every suggestion on github)
> * [x]  This feature is a valid suggestion.
>   (I have read the FAQs and Guides)

**Comment by RegalAether** [comment]
how are people this dumb bro
