### ISSUE TITLE
[Bug] Infinity Miner and Auto-Eat fails

### ISSUE THREAD

**Issue by 24098762409875odfhasodf** [MeteorDevelopment/meteor-client#2609]
### Describe the bug

Infinity Miner (already bugged #2608) when it worked, had a bug where auto-eat would break it.
When it starts eating, infinity miner keeps switching back to the pickaxe, making it impossible to finish eating. Auto-eat would continue trying, causing the following issues:

1. You stay hungry, but stay slow as if you're eating (you technically are but you never finish eating)
2.  Infinity miner stops working as auto-eat constantly switches to food, resetting block break progress (making it impossible to mine any block that takes more than 1 second with auto-eat on)

### Steps to reproduce

```bash
Enable Infinity Miner (with any mending pick)
Turn on auto-eat
Wait until auto-eat starts (make sure to have food in hotbar)
```

### Meteor Version

0.5.1-1571 (Dev Build)

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
#2229

**Comment by OgmurHere** [comment]
still an issue in [meteor client v0.5.5 build #1978](https://meteorclient.com/) 1.20.2
