### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by w13523fsa** [MeteorDevelopment/meteor-client#2610]
### Describe the bug

i am trying to download 1.19 metoer but its saying error please fix this

### Steps to reproduce

```bash
i did nothing i went to download it and it came up with a error
```

### Meteor Version

1.19

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by w13523fsa** [comment]
please fix it

**Comment by TheChamply** [comment]
I have the same issue

**Comment by RegalAether** [comment]
wait for mimgam to wake up

**Comment by MineGame159** [comment]
Fixed.
