### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 1738myass** [MeteorDevelopment/meteor-client#2611]
### Describe the bug

minecraft crashes when trying to open with meteor client

### Steps to reproduce

```bash
while renaming the window title i added an emoji and my shit instantly crashed and tried opening it again and it didnt work so I tried changing the nbt data the my files and then shit starting saying failed to get nbt data or something
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send the crash report.
