### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TheChamply** [MeteorDevelopment/meteor-client#2612]
### Describe the bug

When i click on the download for meteor 1.19, the site wont load and says that there is something wrong with the host.

### Steps to reproduce

```bash
The bug happens when i click the link to download it.
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by xiaopangju** [comment]
I have the same problem. By the way, I think you should edit the tittle to help other people who has the same question read this issue.

**Comment by MineGame159** [comment]
Fixed.
