### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ah4524gdf4g5sgd5rius** [MeteorDevelopment/meteor-client#2613]
### Describe the bug

![down](https://user-images.githubusercontent.com/93934016/182814870-15c8c82a-043c-442b-bd70-16513739b853.PNG)

![image](https://user-images.githubusercontent.com/93934016/182815360-eb12ed1e-268c-4545-8dfb-69a87784d5fd.png)
i can't verify on dicord

### Steps to reproduce

```bash
somehow
```

### Meteor Version

none

### Minecraft Version

none

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RegalAether** [comment]
wait for mimgam to wake up

**Comment by MineGame159** [comment]
1. The Bot status monitor is broken, the bot works.
2. Literally fucking read the message, that is caused by you having private messages disabled for the meteor server.
