### ISSUE TITLE
Showing error when Launched :(

### ISSUE THREAD

**Issue by Nikhilcoolz** [MeteorDevelopment/meteor-client#2617]
### Describe the bug

I was using 1.18.2 and after that 1.19 came , So I was playin 1.19 , after that I wanted to go back to 1.18.2 when I put the 1.18.2 .jar file in and launch in its showing some sort of error , Here's the screenshot:
<img width="655" alt="Screenshot 2022-08-04 at 7 55 50 PM" src="https://user-images.githubusercontent.com/88964902/182871974-550f3d95-4d14-4f95-90d0-6416435dadc4.png">

### Steps to reproduce

```bash
idk wht is this ?!?!?!
```

### Meteor Version

1.18.2

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
That has nothing to do with Meteor.
