### ISSUE TITLE
[Suggestion] for kill aura

### ISSUE THREAD

**Issue by Depedria** [MeteorDevelopment/meteor-client#2619]
### Describe the feature

changeable fov for kill aura

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
what

**Comment by RickyTheRacc** [comment]
> what

It's for trying to use it on legit servers lmfao, it only attacks if the target is in a certain radius around the crosshair

**Comment by Depedria** [comment]
> > what
> 
> It's for trying to use it on legit servers lmfao, it only attacks if the target is in a certain radius around the crosshair

yes will only attack if there is any player in the selected fov
