### ISSUE TITLE
[Suggestion] Add a error message when you try to load the client with optifine or add optifine support

### ISSUE THREAD

**Issue by liad-inon** [MeteorDevelopment/meteor-client#262]
First of all i love to see a support to optifine in the client, shaders are really improving the feel of the game and almost every client support's them. Second of all when you try to load the client and optifine together the game just crush and you need to figure out yourself why. So pls at least add an error message when you try to load the client with optifine or preferably add optifine support.

**Comment by seasnail8169** [comment]
Why would we do that? We clearly state that optifine is not supported and to use alternatives, its not something we are ever gonna fix nor care about at all.

**Comment by liad-inon** [comment]
@seasnail8169 You have a really good client but as you say the client does not support optifine, and currently optifine is the only way to use shaders. So if i want to use shaders i can't use your client. So it would be great if optifine would be supported in this client in the same way he almost every other client.

**Comment by seasnail8169** [comment]
@liad-inon optifine is not the only way to use shaders, i recommend checking this gist for help with using fabric mods to replicate some features of optifine: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754
