### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yomommabois** [MeteorDevelopment/meteor-client#2620]
### Describe the bug

Crashed when I spawned a clone on a server.

### Steps to reproduce

```bash
Step one: join a server, it happened for me on play.crankhouse.net:25652
Step two: summon a clone
```

### Meteor Version

Dev Build 0.5.1

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by yomommabois** [comment]
[crash-2022-08-04_21.26.45-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9265005/crash-2022-08-04_21.26.45-client.txt)

**Comment by ThebestkillerTBK** [comment]
#2636, the same thing happens
