### ISSUE TITLE
[Bug] Download button on Website for Version 0.5.0 doesn't work.

### ISSUE THREAD

**Issue by ItsdMeSoFYou** [MeteorDevelopment/meteor-client#2621]
### Describe the bug

When on the website https://meteorclient.com you click on the download button for meteor 0.5.0 the download link doesn't work.

### Steps to reproduce

```bash
Klick on "Release 0.5.0 [1.19]" on the website
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
I'd say that we already knew about this thanks to the 2526284 reports we got in the Discord...

**Comment by ItsdMeSoFYou** [comment]
> I'd say that we already knew about this thanks to the 2526284 reports we got in the Discord...

my bad. I'm not on the discord, so I wasn't aware.
