### ISSUE TITLE
[Bug] Macro

### ISSUE THREAD

**Issue by thetrooper2281337** [MeteorDevelopment/meteor-client#2622]
### Describe the bug

Easy to explain. when u trying to activate macro of meteorclient ur game s crashing.

### Steps to reproduce

```bash
i just wanted to make /home bind and my game crashed.
```

### Meteor Version

meteor client v0.5.1 build #1571

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
#2595
