### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by XDukeCze** [MeteorDevelopment/meteor-client#2623]
### Describe the bug

When trying to download release 0.5.0
website says Error 523 origin is unreachable

### Steps to reproduce

```bash
Go to https://meteorclient.com
then click on Release 0.5.0 (1.19)
Thats it
```

### Meteor Version

Idk its website 

### Minecraft Version

1.69 idk

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
I think the other 30000 reports in the Discord were enough to let us know about this...

**Comment by tympanicblock61** [comment]
literally it has been reported already, now close this bug report
