### ISSUE TITLE
[Suggestion] Create batirone goal in freecam.

### ISSUE THREAD

**Issue by Affexe** [MeteorDevelopment/meteor-client#2624]
### Describe the feature

Create baritone goal on bind in freecam without ".b click".

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by seasnail8169** [comment]
#come
