### ISSUE TITLE
Crash on macro keybind

### ISSUE THREAD

**Issue by Affexe** [MeteorDevelopment/meteor-client#2628]
### Describe the bug

Minecraft crashes when I press keybind for the macro. 

### Steps to reproduce

```bash
I've tried to use macro
```

### Meteor Version

meteor-client-0.5.1-1571

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Funtimes909** [comment]
can confirm I also have this issue

**Comment by seasnail8169** [comment]
send the crash report
@Funtimes909
@Affexe

**Comment by Affexe** [comment]
Fixed in meteor-client-0.5.1-1580.

[crash-2022-08-09_23.07.06-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9294225/crash-2022-08-09_23.07.06-client.txt)
