### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Gamerboi276** [MeteorDevelopment/meteor-client#2629]
### Describe the feature

I would like all of the dev + official release builds to be archived all the way from the start! :)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by I-Got-You-Dead** [comment]
no

**Comment by I-Got-You-Dead** [comment]
cope

**Comment by RickyTheRacc** [comment]
kill yourself

**Comment by StonedGiraffe** [comment]
Better get started 😂
