### ISSUE TITLE
[Bug] ESP displays wrong

### ISSUE THREAD

**Issue by ngudulalose** [MeteorDevelopment/meteor-client#263]
**Describe the bug**
Player ESP, item ESP, Nametags display wrong.

**To Reproduce**
1. Just turn on player ESP, item ESP, nametags

**Screenshots**
https://i.imgur.com/ckPI8QD.png
https://i.imgur.com/Dbfghy8.png

**Additional context**
Meteor version: 0.4.1
Minecraft version: 0.16.4

**Comment by seasnail8169** [comment]
Can you try to reproduce this on the latest dev build please.

**Comment by ngudulalose** [comment]
> Can you try to reproduce this on the latest dev build please.
Meteor: v0.4.1 build #606
Minecraft: 1.16.5
Still happen.
https://i.imgur.com/jQxv9Ue.png

**Comment by seasnail8169** [comment]
What other mods are you using?

**Comment by ngudulalose** [comment]
> What other mods are you using?

Here: https://i.imgur.com/q4sXN8D.png

**Comment by RedCarlos26** [comment]
I cannot reproduce this issue.

**Comment by seasnail8169** [comment]
Neither

**Comment by RedCarlos26** [comment]
Could be an issue with hydrogen? But this is clearly not a meteor bug.

**Comment by RedCarlos26** [comment]
> > What other mods are you using?
> 
> 
> 
> Here: https://i.imgur.com/q4sXN8D.png

Try removing the mods one by one @ngudulalose, and see if the issue is still happening

**Comment by Declipsonator** [comment]
Well its clearly not a compatibility problem

**Comment by ngudulalose** [comment]
It still happens in the latest version 😥

**Minecraft version:** 0.16.5

**Meteor:** 0.4.2
Meteor setting: [url](https://i.imgur.com/cgrBT5R.png)

**Fabric:** 11.3 [url](https://i.imgur.com/9VlDHSN.png)
No change in installation: [url](https://i.imgur.com/lPgbOie.png)

**Mod folder:** Only Meteor and fabric [url](https://i.imgur.com/6JDrcQn.png)

![Inked2021-04-21_10 31 35_LI](https://user-images.githubusercontent.com/27182104/115492980-12892b80-a28d-11eb-8c3a-a87636b494c0.jpg)

**Comment by ForBai** [comment]
same problem

**Comment by ngudulalose** [comment]
fixed by use **Reset Video Settings** of Optifine.
Install an Minecraft Optifine version -> Options -> Video Settings -> Other -> Press **Reset Video Settings**. Done
Now u can exit Optifine and use Meteor normaly.

**Comment by cynxbabiee** [comment]
Nah, just follow step by step :  Language setting > Force Unicode Font : OFF.... Now enjoy it <3

**Comment by arlomcwalter** [comment]
not the same issue

**Comment by Xplar** [comment]
I was using Immediatelyfast and thats what broke it for me
