### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Iamconfused2008** [MeteorDevelopment/meteor-client#2632]
### Describe the feature

Add Auto Farm to Meteor?  Automatically farms crops

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by AnhNguyenlost13** [comment]
It's a feature in Baritone, you can do it with `.b farm` or `#farm`.
