### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by SkubiDupapa** [MeteorDevelopment/meteor-client#2634]
### Describe the bug

When I enable server spoof, it says this:
![Screenshot 2022-08-09 002741](https://user-images.githubusercontent.com/86016269/183531482-b49e3a09-f320-4c6b-b7f2-579025e2a365.jpg)

### Steps to reproduce

```bash
When I join the server
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.1-1572

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by AnhNguyenlost13** [comment]
The server you're trying to join has `enforce-secure-profile` enabled.

**Comment by SkubiDupapa** [comment]
how do i get pass it

**Comment by seasnail8169** [comment]
you disable the setting in server spoof
