### ISSUE TITLE
[Bug] Crash while using Minihud Quilt

### ISSUE THREAD

**Issue by ThebestkillerTBK** [MeteorDevelopment/meteor-client#2637]
### Describe the bug

The game crashes only you use quilt with minihud installed and fabric works fine
https://hastebin.com/qaginalali.properties

### Steps to reproduce

```bash
1. Install minihud, malilib and meteor
2. run minecraft, crash
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Well, why would you use quilt of Meteor is a Fabric mod?

**Comment by ThebestkillerTBK** [comment]
some of my mods became quilt only, and everything works fine while you remove meteor

**Comment by Lovecrafts-Cat** [comment]
Well that's obviously because Meteor is made for Fabric and not Quilt, as specified in the install guide and the FAQ.
