### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by fatalt12** [MeteorDevelopment/meteor-client#2638]
### Describe the bug

here's the crash report, i have no fucking idea what's going on https://mclo.gs/G8zayqu

### Steps to reproduce

```bash
right click crafting table, chest
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ThebestkillerTBK** [comment]
I got the same issue here

**Comment by seasnail8169** [comment]
fixed by [4a5224f](https://github.com/MeteorDevelopment/meteor-client/commit/4a5224ff53f7054864ad3b1274638ac00efb1379)

**Comment by seasnail8169** [comment]
im a retard
