### ISSUE TITLE
[Bug] Large Chat history makes the whole chat message invisible

### ISSUE THREAD

**Issue by ThebestkillerTBK** [MeteorDevelopment/meteor-client#2639]
### Describe the bug

If your chat message is more than one line, the message will become invisible

### Steps to reproduce

```bash
/
```

### Meteor Version

meteor-client-0.5.1-1578

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
![image](https://user-images.githubusercontent.com/17166139/183707506-e6a1a923-16ae-46bf-b372-6d97be0080e1.png)
works for me

**Comment by ThebestkillerTBK** [comment]
this bug only happens when you turned better chat and large chat history on

**Comment by RacoonDog** [comment]
i can confirm this does actually happen on the latest devbuild
