### ISSUE TITLE
Dev Version Crashing Code 1

### ISSUE THREAD

**Issue by Minecrafter412** [MeteorDevelopment/meteor-client#2642]
### Describe the bug

So i dont have any other mod in the mods folder and i even reinstalled everything and i still have the crashing  bug

i did not get any logs for some reason.

### Steps to reproduce

```bash
Step 1. Open Minecraft Launcher
Step 2. Start minecraft after start it crashes crash code 1
```

### Meteor Version

0.5.1 1580

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by maplepy** [comment]
https://mclo.gs/igeHjdd

**Comment by thetrooper2281337** [comment]
idk my game too was crashing insantly but i reinstalled everything and im not crashing now

**Comment by maplepy** [comment]
Weird, I just did that, a fresh install with only meteor and it still crashes

**Comment by Wide-Cat** [comment]
is this still happnening on the latest build?

**Comment by maplepy** [comment]
> is this still happnening on the latest build?

Yep, the latest 1.19.1 build that is, if I'm up to date (my mods aren't on 1.19.2 yet)

**Comment by seasnail8169** [comment]
*the* latest dev build, not 1.19.1

**Comment by maplepy** [comment]
No idea, didn't test

**Comment by MineGame159** [comment]
I will reopen the issue if you can send a crash report using latest de build (1.19.2).
