### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by popipac** [MeteorDevelopment/meteor-client#2643]
### Describe the feature

Make auto eat work with infinite miner.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Sidescript** [comment]
Please do, this is such a good suggestion.

**Comment by seasnail8169** [comment]
#2229
