### ISSUE TITLE
[Bug] Crash on adding new account.

### ISSUE THREAD

**Issue by devendrapoonia** [MeteorDevelopment/meteor-client#2646]
### Describe the bug

Today I was adding my Microsoft account in Meteor client. I logged in to Microsoft, everything was successful, but after closing the tab after success. Meteor crashed but it added the account.

Here is crash report - https://bytebin.lucko.me/qk8o9Fa57x

### Steps to reproduce

```bash
1. Install Meteor Client's 0.5.1 dev build.
2. Install Minecraft 1.19.2
3. Try adding an account.
4. Minecraft will crash.
```

### Meteor Version

Dev Build 0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Can you reupload the crash report, thanks. Preferably just move the file onto GitHub.

**Comment by devendrapoonia** [comment]
[crash-2022-08-10_11.38.04-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9484266/crash-2022-08-10_11.38.04-client.txt)

**Comment by seasnail8169** [comment]
please try without the not enough crashes mod
also im fairly sure this is fixed in the latest dev build anyway, please update before providing any more information
