### ISSUE TITLE
[Bug] Game keeps crashing when staying on servers

### ISSUE THREAD

**Issue by BlackHamster1** [MeteorDevelopment/meteor-client#2647]
### Describe the bug

When i was playing on Minehut servers (and the lobby) the game crashed. every time i tried to join after a few seconds it would inevitably crash.
![image](https://user-images.githubusercontent.com/108276578/183891637-ed2d642e-db1a-4791-9180-0e6a93f52097.png)

### Steps to reproduce

```bash
1. load up Minecraft
2. join a Minehut server (or lobby) (could be for other servers, i play on Minehut all the time)
3. the game crashes without any crash logs
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by BlackHamster1** [comment]
here a video

https://user-images.githubusercontent.com/108276578/183892820-301d2bde-4179-434a-bd64-bf30f72ff2b9.mp4

d

**Comment by Wide-Cat** [comment]
if this is still happening, can you please send a log file
