### ISSUE TITLE
Compatability with Optifabric

### ISSUE THREAD

**Issue by IncompetentMoron** [MeteorDevelopment/meteor-client#2651]
### Describe the feature

i want to use shaders while im using meteor client but i cant because its not compatible for some odd reason

### Before submitting a suggestion

- [ ] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested.
(I have checked every suggestion on github)

- [ ] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by GreemDev** [comment]
dont use optifabric, https://irisshaders.net/

**Comment by explasion** [comment]
It breaks xray and can completely crash other mods. It'll never be supported.
