### ISSUE TITLE
Better highway builder

### ISSUE THREAD

**Issue by Yura3313** [MeteorDevelopment/meteor-client#2656]
### Describe the feature

Your highway builder isn't the best, but you can use lambda's highway tools which is superior.
sure, you will need to implement it from kotlin, but the result will be great!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
We won't just copy paste code from other clients.

**Comment by Yura3313** [comment]
> We won't just copy paste code from other clients.

whats the problem, their license allows commercial use of their code

**Comment by Mathrandom7910** [comment]
> whats the problem, their license allows commercial use of their code and you wont compete anyway, since they're a 1.12.2 client

ethics
