### ISSUE TITLE
feather client compatibility?

### ISSUE THREAD

**Issue by Sudo-Muffin** [MeteorDevelopment/meteor-client#2657]
### Describe the feature

meteor doesn't work with feather client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
> meteor doesn't work with feather client

And it never will, since we don't want to support it.
If they made it open source, maybe the devs would spend time trying to make it compatible.

**Comment by MineGame159** [comment]
As was already said we don't want to support a mod that steals other mods for their own good.
