### ISSUE TITLE
[Bug] Sky 

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#2658]
### Describe the bug

When using meteor, the bottom of the sky in a world isn't rendered correctly and is instead just replaced with a black box.

<img width="1280" alt="Screenshot 2022-08-13 231728" src="https://user-images.githubusercontent.com/80427814/184522277-cc4438be-ad60-4af5-a7e8-c56a488bdb5e.png">
 

### Steps to reproduce

```bash
Use the latest dev build
Join a server
```

### Meteor Version

1583 Dev

### Minecraft Version

1.19,2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
show active modules + try with only meteor
