### ISSUE TITLE
Module upgrade

### ISSUE THREAD

**Issue by ItzSkyReed** [MeteorDevelopment/meteor-client#2659]
### Describe the feature

1. Add the ability to use food in the left hand with auto eat
2. Add Black list to nuker 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by ChillerDragon** [comment]
Imo those are two different issues. Also a more descriptive title could help. But big +1 from me for this

> Add the ability to use food in the left hand with auto eat

**Comment by seasnail8169** [comment]
#2229
separate your issues

**Comment by seasnail8169** [comment]
#429 rather
