### ISSUE TITLE
[Suggestion] No render for campfire smoke

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#266]

**Comment by Declipsonator** [comment]
Already possible through Particle Blocker. Plus this isn't a bug.

**Comment by RedCarlos26** [comment]
I know, but in the no render tab, it isn't there. I don't want to block all particles just campfire for example. And I wrote suggestion, not bug.

**Comment by Declipsonator** [comment]
You can choose exactly what particles to block in the particle blocker. You also put the label bug on this.
