### ISSUE TITLE
[Bug] HUD Does Not Edit Properly on macOS

### ISSUE THREAD

**Issue by LTBlueLatios** [MeteorDevelopment/meteor-client#2661]
### Describe the bug

Apparently the functions of the "HUD Edit Functions" consist of highlighting with a white box. This use of a "highlighting box", however, triggers a lot of issues. For one, it starts as small, easy-to-select items at the top left of your screen, to a ginormous box that is impossible to highlight anything at the bottom right. This makes the HUD retarded and ass to edit.

### Steps to reproduce

```bash
Try to move a HUD Item on the bottom right, the item is unmovable.
```

### Meteor Version

1.19.1 Dev Version -1571

### Minecraft Version

1.19.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

https://user-images.githubusercontent.com/65719723/184548949-03764019-df39-403c-b63f-8222a3dbc996.mp4

For those who can't comprehend what I'm trying to explain, I have provided you a short video of me trying to move some gui items with this "highlighting and move" feature

ld)

**Comment by seasnail8169** [comment]
this seems like it would be an issue with macOS

**Comment by LoganDark** [comment]
> this seems like it would be an issue with macOS

It's not, it's an issue with DPI scaling. You typically only run into that on macOS, but it is an issue on all platforms.

**Comment by LoganDark** [comment]
Actually, on second thought and a bit of investigation, no. On Windows, Java just uses physical pixels. It takes input in physical pixels, outputs in physical pixels. It does look like macOS is the outlier here because on macOS you typically render in logical pixels instead of physical pixels. With that said I don't see how it should be breaking Meteor unless it's using some weird API.

(I would do more testing, but my macOS machine is broken, so I can only use it over remote desktop)

**Comment by seasnail8169** [comment]
#393

**Comment by EthanZeigler** [comment]
@LoganDark I can test anything you'd like, just ping me.

**Comment by seasnail8169** [comment]
@EthanZeigler @LoganDark 
can you move to the issue i linked (https://github.com/MeteorDevelopment/meteor-client/issues/393)
trying to keep related issue discussion in a single thread

**Comment by LoganDark** [comment]
> @EthanZeigler @LoganDark can you move to the issue i linked (#393) trying to keep related issue discussion in a single thread

I didn't have any further comments to make so there is nothing to move.
