### ISSUE TITLE
[Suggestion] Remove slider limit

### ISSUE THREAD

**Issue by soshimee** [MeteorDevelopment/meteor-client#2665]
### Describe the feature

I know why it's there, but it doesn't work that well when I'm trying to use a module in edge cases or for other purposes than it was intended. There should  be a config option to remove the slider limit.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RacoonDog** [comment]
limits are there for a reason
and generally the slider limit is different from the actual value's limit anyways

**Comment by AnhNguyenlost13** [comment]
you can manually type in your values in boxes next to them

**Comment by MineGame159** [comment]
As others said 99% of the time the text box next to the slider doesn't have any maximum limits. It is impossible for a slider to not have a limit because that's just how sliders work. We could it a "limit" of the maximum number possible but then moving your mouse even a single pixel would change the number by like a million.

**Comment by soshimee** [comment]
I don't get it, what do you mean? And the text box DOES have limits

**Comment by seasnail8169** [comment]
they aren't the same, the slider has limits for visual reasons, the box has limits for functional reasons. they are defined separately.

**Comment by Mathrandom7910** [comment]
> I don't get it, what do you mean? And the text box DOES have limits, actually the same as the slider.

50% of infinity is infinity

**Comment by soshimee** [comment]
Then remove the "functional" limits. I don't bother if it crashes or not, I just want it to use it my way (such as elytra fly below bedrock)

**Comment by Mathrandom7910** [comment]
I dont think you understand how sliders work.

**Comment by soshimee** [comment]
The "numbers" still  have limits, that's what I'm talking about now.

**Comment by Mathrandom7910** [comment]
It's really not complicated to implement. But it's not in meteor since people will just crash their games with insane values. https://github.com/Mathrandom7910/meteor-client
