### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 4L3X4NDD3R** [MeteorDevelopment/meteor-client#2667]
### Describe the bug

Meteor account on the web page doesn't link propertly with discord account

### Steps to reproduce

```bash
trying to link my meteor account on the web page to discord account
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
not an issue for this repo
