### ISSUE TITLE
[Bug] Crash when loading a profile

### ISSUE THREAD

**Issue by I-Got-You-Dead** [MeteorDevelopment/meteor-client#2670]
### Describe the bug

Game crashes when ever you press the "load" button on the profile screen.

[crash-2022-08-18_15.32.42-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9367911/crash-2022-08-18_15.32.42-client.txt)

### Steps to reproduce

```bash
1: Reload a saved profile.
2: Profit
```

### Meteor Version

Dev-build 0.5.1 1588

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
This is caused by some addon you have.

**Comment by I-Got-You-Dead** [comment]
Any idea what addon?
