### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by dominikfk** [MeteorDevelopment/meteor-client#2671]
### Describe the feature

I have a suggestion.  If possible, do it so that you can set the permissions level on the servers

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested.
(I have checked every suggestion on github)

- [x] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
> do it so that you can set the permissions level on the server

What does that mean?
If you meant to get admin/op that's impossible.

**Comment by dominikfk** [comment]
Oh, ok.
