### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by fcflorentino1234** [MeteorDevelopment/meteor-client#2672]
### Describe the feature

Can summon lighting with Channeling Triden when world doesn't raining

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Since the weather sytem is server sided, you can't really tell him to spawn a lightning with no rain.
So, I don't think you really can do that.
