### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Minecrafter412** [MeteorDevelopment/meteor-client#2673]
### Describe the bug

Game crashes after joining server/singleplayer

### Steps to reproduce

```bash
1. start minecraft launcher
2. start minecraft 1.19.1
3. join a server/singleplayer game
```

### Meteor Version

0.5.1 1572

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by letaliter** [comment]
This is an unuseful report, no crash log given, and you're using an old meteor version

**Comment by Wide-Cat** [comment]
this is an older build. If you can reproduce this on the latest dev build, open this issue again with a crash report attached
