### ISSUE TITLE
[Bug] The new Chams shader dont work in front of some blocks in combination with sodium

### ISSUE THREAD

**Issue by qdwdl** [MeteorDevelopment/meteor-client#2676]
### Describe the bug

A few blocks aren't affected by the new cham image shader. (Chests, heads and signs).
![grafik](https://user-images.githubusercontent.com/111536789/185488651-863e4228-3685-4227-9bfa-a404dd0f3933.png)

### Steps to reproduce

```bash
Set the chams module to apply the shader to an entity.
Look at it with chests, heads or signs behind the entity.
```

### Meteor Version

0.5.1-1591

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RickyTheRacc** [comment]
I think this might be a sodium issue or similar, I'm on intelliJ testing and it works fine w/ no rendering mods

<img width="1280" alt="Screenshot 2022-08-18 155802" src="https://user-images.githubusercontent.com/80427814/185493498-e4c8c240-a43f-40e8-bd80-6cbfa85de91e.png">

**Comment by qdwdl** [comment]
the player with the shader has to stand in front of the block not behind it

**Comment by RickyTheRacc** [comment]
false
<img width="1280" alt="Screenshot 2022-08-18 180128" src="https://user-images.githubusercontent.com/80427814/185509702-f425a952-c9b3-405f-92aa-ed9de7fb0202.png">
