### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by dominikfk** [MeteorDevelopment/meteor-client#2678]
### Describe the feature

Item duping

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Ight, please tell us how to magically get items from thin air, we'll wait...

**Comment by dominikfk** [comment]
Dupe items its possible. Oh for 1.8 Lol

**Comment by Mathrandom7910** [comment]
🥇
