### ISSUE TITLE
[Suggestion] InventoryTweaks Addition, ArmorSwitch.

### ISSUE THREAD

**Issue by aaashleyyyy** [MeteorDevelopment/meteor-client#2679]
### Describe the feature

In vanilla Minecraft you can only equip armor from your hotbar if you do not already have a piece of armor in that armor slot, with this setting, it will disable that limitation and let you swap between the two armor pieces straight from your hotbar. Useful for switching between Elytras and chestplates quickly.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by CodeDoc537** [comment]
Good idea, however for this point > Useful for switching between Elytras and chestplates quickly.
There is a module called ChestSwap that does that with a key bind.

**Comment by aaashleyyyy** [comment]
> Good idea, however for this point > Useful for switching between Elytras and chestplates quickly. There is a module called ChestSwap that does that with a key bind.

would also be useful for switching armor sets too

**Comment by StormyBytes** [comment]
Implemented in #2791
