### ISSUE TITLE
[Bug] Macro Crash

### ISSUE THREAD

**Issue by 0Ariel0** [MeteorDevelopment/meteor-client#2680]
### Describe the bug

Whenever I press the macro (the macro is: key: [ Commando: .b stop) I pressed and it crashed in the frame then "saving world" appeared and crashed
Crash Log: [https://pastebin.pl/view/raw/5e7bfcf7](url)

### Steps to reproduce

```bash
1- Create a macro
2- Put some baritone command. Ex: .b stop
3- put any key
4- save and run
5- crash your minecraft
```

### Meteor Version

0.5.1 #1571

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by ThebestkillerTBK** [comment]
update to latest meteor
