### ISSUE TITLE
[Bug] Can't compile meteor addons

### ISSUE THREAD

**Issue by kokqi** [MeteorDevelopment/meteor-client#2682]
### Describe the bug

![image](https://user-images.githubusercontent.com/78592988/185746582-f175d715-df0b-480f-97e9-2e6960ac47b9.png)

my addons code
https://pastebin.com/SMkKiHHx
https://pastebin.com/csskYEF0

### Steps to reproduce

```bash
..idk
```

### Meteor Version

1.19.2

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
use 0.5.1-SNAPSHOT instead of 0.5.0-SNAPSHOT
