### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by zombsplayz** [MeteorDevelopment/meteor-client#2683]
### Describe the bug

When i join minehut, sometimes meteor client crashes my computer with error code -1. It happens like half of the time.

### Steps to reproduce

```bash
it just happens.
```

### Meteor Version

0.5

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
attach crash report
