### ISSUE TITLE
[Bug] with the ALT manager

### ISSUE THREAD

**Issue by Appolon24800** [MeteorDevelopment/meteor-client#2684]
### Describe the bug

The ALT manager works I manage to connect with my account but if I try to connect to a server I get an error like "Profile key i not valid" or other thank you if I have to do something with my rate or if you need to fix a bug thank you in advance

![image](https://user-images.githubusercontent.com/93398824/185790200-4e30af6d-1974-49a5-ae7f-169d6d6752e7.png)

![image](https://user-images.githubusercontent.com/93398824/185790213-1a85d807-fad8-4307-91b3-cb43dd62cd22.png)

### Steps to reproduce

```bash
connect with an account on the ALT manager and try to connect to a server
```

### Meteor Version

1.19.2

### Minecraft Version

Meteor client 0.5.11591

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by I-Got-You-Dead** [comment]
Ong

**Comment by I-Got-You-Dead** [comment]
It’s a server issue

**Comment by RacoonDog** [comment]
the alt manager was discontinued at around dev build 8600 due to the migration from microsoft to weibo accounts

**Comment by MineGame159** [comment]
You have No Signatures in Server Spoof on.
