### ISSUE TITLE
[Bug] Import profiles and macros back

### ISSUE THREAD

**Issue by Tendas240** [MeteorDevelopment/meteor-client#2685]
### Describe the bug

Since the profiles and macros were removed by the following update:

![image](https://user-images.githubusercontent.com/71498430/185957671-3f6f1f95-cb5c-43a5-a372-92e82b73e8ac.png)

i wonder how can i import them again in the new version?
I searched the FAQ but i could not find anything helpful.

### Steps to reproduce

```bash
Play on a version newer version than the one shown in the picture
```

### Meteor Version

meteor client v0.5.1 build #1592

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
The way they are stored was changed, there is no way to import the old format.

**Comment by Tendas240** [comment]
> The way they are stored was changed, there is no way to import the old format.

My macros and profiles were very complex. Do i have to readd all macros and set up all configs from scratch again? Is there anything i can use the old files for?

**Comment by RickyTheRacc** [comment]
You have to redo them manually, yes
