### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by VoidCine** [MeteorDevelopment/meteor-client#2687]
### Describe the bug

So this is basically the bug 
When i launch tlauncher with meteor client
It works
But when i go to multiplayer to click account to log onto another acc it quickly crashes my game idk why.

Btw am on tlauncher
 could u pls fix that or is it just me?

### Steps to reproduce

```bash
when i launch and i go to multiplayer and press account it crashes my game
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
try buying the game idk
