### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Kicristal31028** [MeteorDevelopment/meteor-client#2688]
### Describe the bug

baritone of this client was very stupic as #goto. When I used that command suddenly I got drop damage alot and die.
Pls help me fix that problem

### Steps to reproduce

```bash
using #goto X Y Z on command --> sucide.
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Baritone follows your commands based on your baritone config.
If you set it up to be stupid, it will be stupid.
Check your configs to make it behave how you want.

**Comment by Wide-Cat** [comment]
theres a baritone setting related to fall distance, you probably need to edit that and set it a lot smaller

**Comment by Mathrandom7910** [comment]
> where? can you show me? I didn't see

Ok, this may be difficult and require you to be able to read (you have been warned), there is a tab labeled "baritone".
