### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by iTzWillo** [MeteorDevelopment/meteor-client#2689]
### Describe the bug

if you get the seed from seed cracker it will automaticly put it in 1.18.2 , if you try to delete it from the list and putting it again you can't put it in 1.19, I fixed this issue by removing seecracker from the mod folder and putting the seed manualy

### Steps to reproduce

```bash
get the seed with seedcracker, automaticly set to 1.18.2 , remove it , no way to add a 1.19 seed
remove seed cracker from mod folder, then it works
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
I have no idea what you are talking about. Meteor does not have built in seed cracker or a way to manage seeds.

**Comment by Kicristal31028** [comment]
it isn't related to client lol
