### ISSUE TITLE
Movement recorder

### ISSUE THREAD

**Issue by Affexe** [MeteorDevelopment/meteor-client#2690]
### Describe the feature

Movement recorder like in "Midnight" hack for csgo.

https://youtu.be/kL0DbFkqC1c?t=119  (Watch ~25 seconds after timecode)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
Seems a bit out of scope to me, and also not really necessary, nor easy to implement.
Can't you use Baritone for most automated tasks anyways?

**Comment by Affexe** [comment]
For example, if I build a trap, I have to get to it faster than I die, but could I repeat all the jumps correctly?

**Comment by Tendas240** [comment]
> Why would you want to record movements? Is it because you would like to save where your baritone or main character moves on a map or something? That would be useless as we would have waypoints to set locations, and you can also use replaymod to rewatch what you have done

you could use it to create kind of a macro to do recurring tasks baritone can't do. something you would have to do manually everytime. for example when youre building a tunnel with certain features. details baritone cant comprehend. or for example defining a route baritone wouldnt take cause in its mind its not efficient. though for you it might make more sense as its a secret route or something maybe. You dont always want to take the routes baritone decides to take.
also baritone can only jump 3 blocks and has limited options to navigate. I mean there is already much to customize there but there is still something left that could be done by this recording feature.
Im just brainstorming to give you reasons why this might be helpful. There are so many features in meteor that arent as useful as this would be.
