### ISSUE TITLE
[Bug] Baritone Integration chat menu navigation not working

### ISSUE THREAD

**Issue by Tendas240** [MeteorDevelopment/meteor-client#2691]
### Describe the bug

(prefix)wp l

it will show the waypoints but not the menu when you click on a waypoint to select and show options (remove, select, goal...)

### Steps to reproduce

```bash
type (prefix)wp l and it will show the waypoints
try to click on a waypoint and nothing happens
```

### Meteor Version

meteor client v0.5.1 build #1592

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

EDIT:
I texted to a baritone developer and got this info:

![image](https://user-images.githubusercontent.com/71498430/186468025-8c08fda6-1659-4bab-9578-0e947cee7d8c.png)

**Comment by seasnail8169** [comment]
same thing as #2707
