### ISSUE TITLE
[Bug] Waypoints get deleted if you restart your game 

### ISSUE THREAD

**Issue by Kolotheegg** [MeteorDevelopment/meteor-client#2696]
### Describe the bug

So create a waypoint and press save, then restart your game. Your waypoint will be deleted.

### Steps to reproduce

```bash
Create a waypoint. Restart your game and then look at your waypoints.
```

### Meteor Version

newest dev build

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
Unable to reproduce. You might have a profile overwriting your waypoints
