### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by elpitolocoxd** [MeteorDevelopment/meteor-client#2697]
### Describe the bug

the version dev build 0.5.1 for 1.19.2 the launcher closes when I try to change accounts, I literally touch the accounts button and it closes.

### Steps to reproduce

```bash
touch the button accounts
```

### Meteor Version

dev build 0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Wide-Cat** [comment]
unable to reproduce. If this still happens on the latest build, attach a crash report.
