### ISSUE TITLE
Infinity miner crashes game [Bug] 

### ISSUE THREAD

**Issue by Celse2021** [MeteorDevelopment/meteor-client#2698]
### Describe the bug

When you select all of the blocks in the select blocks gui in the infinity miner and turn the module on, it crashes the game.

### Steps to reproduce

```bash
1) Open meteor gui

2) Locate Infinity miner module

3) Open the infinity miner configuration

4) Go to the block selection and click (select)

5) Click the + for all the blocks on the list

6) Turn on the module

7) Game freezes and then crashes (No error message just a crash)
```

### Meteor Version

0.51 (1592)

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Lovecrafts-Cat** [comment]
Can you provide a crashlog if you get any? This is truly an edge case.
On a side note: why would you add ALL the blocks to that?

**Comment by Celse2021** [comment]
Forgot to upload crash log, here it is, https://pastebin.com/LWtSAKaE

**Comment by Celse2021** [comment]
On a side note: why would you add ALL the blocks to that?

Side note response: I was trying to mine entire chunks, wanted to "grief" infinetly or until something happened.

My side note: i was using multiconnect, and in the list some blocks appeared like: multiconnect.frame.texture.block or something like that (j added that to the list), MAYBE, that crashed the game because baritone didnt understand what was that.

**Comment by Celse2021** [comment]
I was trying it on singleplayer to see if it could work on a server.

**Comment by Celse2021** [comment]
> Can you provide a crashlog if you get any? This is truly an edge case. On a side note: why would you add ALL the blocks to that?

i have responded to everything.

**Comment by Mathrandom7910** [comment]
You never gave a crash log.
