### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Dqlphix** [MeteorDevelopment/meteor-client#2699]
### Describe the feature

Clean Recording.
So what Im thinking is that when u start this you can record your game with Obs medal or anything and it would not show any hacks 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
This client is not meant to be used on servers that don't allow it. So this feature is not needed.
Also there's no reason to hide Meteor from recording.

**Comment by Mathrandom7910** [comment]
Dont cheat on servers that dont allow it :rofl:
