### ISSUE TITLE
[Bug] FontRenderer renders username input twice in AltManager

### ISSUE THREAD

**Issue by TransRights** [MeteorDevelopment/meteor-client#270]
**Describe the bug**
Hovering over the curser in the AltManager add account username field will render the username a second time somewhere on the screen.

**To Reproduce**
1. Go to the alt manager
2. Add an account and type in your username
3. Hover over your cursor

**Screenshots**
<img width="357" alt="Screenshot 2021-02-25 at 11 40 26" src="https://user-images.githubusercontent.com/47159134/109141658-4436b800-775e-11eb-8705-6b54d74f8240.png">

**Additional context**
This happened on mac; therefore, this issue might not occur on windows.

**Comment by seasnail8169** [comment]
this is a bug with hover tooltips, not alt manager btw.

**Comment by RedCarlos26** [comment]
You're right
