### ISSUE TITLE
Can't connect to Servers

### ISSUE THREAD

**Issue by TomCena** [MeteorDevelopment/meteor-client#2703]
### Describe the bug

when joining one of these error messages pop up
![image](https://user-images.githubusercontent.com/112490557/187447730-66d2b816-60a0-4b5d-9419-6ef1a0a5c3da.png)
![image](https://user-images.githubusercontent.com/112490557/187448167-9061bf27-dba2-4f96-a331-ae4e1e84e8de.png)
![image](https://user-images.githubusercontent.com/112490557/187448770-b6b0942f-a506-4027-8b5c-4c7a1a304a3c.png)
![image](https://user-images.githubusercontent.com/112490557/187448899-f4d6f9aa-20fd-44c5-9f6e-1414b1be59bf.png)
and then just says disconnected or failed to login: null

### Steps to reproduce

```bash
by joining any server
```

### Meteor Version

5.1-1592

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Do you have no signutes in Server Spoof on?

**Comment by TomCena** [comment]
@MineGame159 that fixed it tysm
