### ISSUE TITLE
[Bug] invalid  public key

### ISSUE THREAD

**Issue by rafalohaki** [MeteorDevelopment/meteor-client#2704]
### Describe the bug

 multiplayer.disconnect.invalid_public_key
thats what i get
![image](https://user-images.githubusercontent.com/20607107/187591526-f73ef8f5-2b3a-4594-97c5-0ff935d1b369.png)

### Steps to reproduce

```bash
use meteor client, change account to cracked and join server 1.19.2 velocity
```

### Meteor Version

meteor-client-0.5.1-1592

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by CodeDoc537** [comment]
Turn off no signature in server spoof

**Comment by CodeDoc537** [comment]
Also just don’t use cracked

**Comment by Mathrandom7910** [comment]
^

**Comment by rafalohaki** [comment]
lmao

**Comment by rafalohaki** [comment]
> Turn off no signature in server spoof

i see no option server spoof

**Comment by CodeDoc537** [comment]
> > Turn off no signature in server spoof
> 
> i see no option server spoof

The module “server spoof”
Turn off the no signature setting

**Comment by rafalohaki** [comment]
> > > Turn off no signature in server spoof
> > 
> > 
> > i see no option server spoof
> 
> The module “server spoof” Turn off the no signature setting

i enabled server spoof and uncheched no signature. now its working

**Comment by wmantly** [comment]
@rafalohaki I built meteor client from clone of master 924b333361a4e6e83dd17459a430e7f2cd0fa3b3 and this bug is present.
