### ISSUE TITLE
killaura can not attack Zombified Piglin 

### ISSUE THREAD

**Issue by fortune428** [MeteorDevelopment/meteor-client#2706]
### Describe the bug

As the title said.killaura can not attack
Zombified Piglin Automatically

### Steps to reproduce

```bash
target selects Zombified Piglin
Toggle killaura module
```

### Meteor Version

v0.5.1 dev 1592

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by CodeDoc537** [comment]
You probably have ignore passive setting turned on
