### ISSUE TITLE
[Bug] Bugged Baritone Integration with interaction in chat

### ISSUE THREAD

**Issue by Tendas240** [MeteorDevelopment/meteor-client#2707]
### Describe the bug

(prefix)wp l

it will show the waypoints but not the menu when you click on a waypoint to select and show options (remove, select, goal...)

EDIT:
I texted to a baritone developer and got this info - so it seems like you have to merge the fix / correct baritone version:

![image](https://user-images.githubusercontent.com/71498430/186468025-8c08fda6-1659-4bab-9578-0e947cee7d8c.png)

### Steps to reproduce

```bash
type (prefix)wp l and it will show the waypoints
try to click on a waypoint and nothing happens
```

### Meteor Version

meteor client v0.5.1 build #1592

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
I don't know where the PR is but the wagyourtail/baritone 1.19.2 branch had latest commit 25 days ago and the official repo is still stuck on 1.19.1 with even worse delay.

**Comment by ehylo** [comment]
> I don't know where the PR is

https://github.com/cabaletta/baritone/pull/3592
 it is for 1.19.1 though so I'm not sure if it would be directly compatible with 1.19.2

**Comment by StormyBytes** [comment]
PR merged
