### ISSUE TITLE
[Suggestion] Anti-Cheat Detector

### ISSUE THREAD

**Issue by moonman0800** [MeteorDevelopment/meteor-client#2708]
### Describe the feature

Add an Anti-Cheat Detector to prevent getting banned on servers.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Wide-Cat** [comment]
you shouldnt use the client on servers that dont allow it
