### ISSUE TITLE
[Bug] XRay only shows exposed ores even if the option is off.

### ISSUE THREAD

**Issue by fdsfd305** [MeteorDevelopment/meteor-client#2709]
### Describe the bug

When XRay is on, even if the option to only show exposed ores is off, only exposed ores will be shown.

### Steps to reproduce

```bash
1. Turn on XRay
2. If on, turn off the option to only show exposed ores
3. Check that only exposed ores are being shown.
```

### Meteor Version

v0.5.1 build #1593

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
can't reproduce, almost certainly a server issue
