### ISSUE TITLE
[Suggestion] Search by shulkers

### ISSUE THREAD

**Issue by Affexe** [MeteorDevelopment/meteor-client#2712]
### Describe the feature

Let's say you have many shulkers in your ender chest (and inventory) and you need to find something, but with a better tooltip it takes time to find smth, especially with custom resource packs. It would be great if you add to the item highlight an ability to search for items using the search bar.

Like this
![i1](https://user-images.githubusercontent.com/82148024/188230421-b7186623-c77c-4bb9-8b3d-1c6f3e5e976c.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Affexe** [comment]
Do this for the inventory as well

**Comment by seasnail8169** [comment]
This isn't in the scope of meteor, use REI or something.
