### ISSUE TITLE
Cant write signs on meteor client

### ISSUE THREAD

**Issue by kerem3048** [MeteorDevelopment/meteor-client#2721]
### Describe the bug

I cant write signs on meteor client

### Steps to reproduce

```bash
place sign
```

### Meteor Version

0.4.9

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
0.4.9 is not supported anymore
