### ISSUE TITLE
[Bug] Game Crashes When Sand Falls

### ISSUE THREAD

**Issue by Endlord15** [MeteorDevelopment/meteor-client#2723]
### Describe the bug

When breaking the block under a gravity block the game crashes I'm not sure what modules I have on that would cause this.

### Steps to reproduce

```bash
Have a gravity block fall.
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
@Endlord15 please attach a crash report, closing until it's there.
