### ISSUE TITLE
Low value on slippy crash [Bug] 

### ISSUE THREAD

**Issue by majorsopa** [MeteorDevelopment/meteor-client#2726]
### Describe the bug

When the slippy module is set to a low slipperiness (0.001, for example), the game stops responding. I haven't been able to get an error code or message because I've needed to kill the Minecraft process.

### Steps to reproduce

- set the slipperiness setting in the slippy module to 0.001
- enable slippy module

### Meteor Version

meteor-client-0.5.1-1592

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by CodeDoc537** [comment]
Ok, but like why would you do that

**Comment by majorsopa** [comment]
> Ok, but like why would you do that

I was messing around and my game crashed, if you'd rather I close the issue and leave the crash unfixed I can do that too 🤷

**Comment by CodeDoc537** [comment]
No that’s good you opened it I was just confused on how you figured that out lol
