### ISSUE TITLE
[Bug] Crashing on latest Dev Build

### ISSUE THREAD

**Issue by TheFantasticLoki** [MeteorDevelopment/meteor-client#2728]
### Describe the bug

During investigation into another crash issue on build 1580 I updated to latest build (1607 at time of post) and now I can't launch my game due to a method not found error. Here is the crash log: https://mclo.gs/5DJMZq0

### Steps to reproduce

```bash
Start Minecraft 1.19.2 with meteor build 1607.
```

### Meteor Version

0.5.1 Build 1607

### Minecraft Version

1.19.2 Fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by GreemDev** [comment]
Update your addons. This crash is because you're using a version of Meteor-Rejects which uses something not present in the latest version. Nothing to do with Meteor itself.

**Comment by TheFantasticLoki** [comment]
Thank you I updated and it fixed it. Now I just need my baritone crash fixed.
