### ISSUE TITLE
[Bug] Crash on asking baritone to mine

### ISSUE THREAD

**Issue by TheFantasticLoki** [MeteorDevelopment/meteor-client#2729]
### Describe the bug

My game has been crashing every now and then inconsistently when using baritone. Game freezes then crashes after issuing mine command. Happens everytime now. Issue found on 1580 persists on version 1607 Here is the crash log : https://mclo.gs/GSet7ZE
On a side note baritone seemed to be navigating in very odd ways like when mining for diamonds it will run around searching for surface ores instead of just mining straight to them when legit mine is turned off and the break penalty is super low. Couldn't get consistent data on what the cause was so couldn't make a bug report and now the game crashes when trying to mine.

### Steps to reproduce

```bash
Mine using baritone. Game can crash randomly when issuing this command but isn't super consistent.
```

### Meteor Version

0.5.1 Build 1607

### Minecraft Version

1.19.2 Fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by TheFantasticLoki** [comment]
and out of knowhere build 1607 randomly decides to start working. crash does still occur. Here is log from latest build 1607: https://mclo.gs/By4MZvm

**Comment by Mathrandom7910** [comment]
Are you able to reproduce with only meteor installed?

**Comment by TheFantasticLoki** [comment]
the answer is likely no but I am in the process of testing that and will let you know. But in the case that it does not crash I would like some idea of what other mod is causing the crash as it was not crashing a few days ago it just wasn't pathing "well".

**Comment by TheFantasticLoki** [comment]
Doesn't outright crash like on my pack BUT it straight up cannot path. I asked it to mine to iron_ore WITH a pickaxe in my characters hand and this is the output: 
![image](https://user-images.githubusercontent.com/26889568/188968956-270fb7aa-af0a-4c3a-8161-4b63f57cb52c.png)

**Comment by seasnail8169** [comment]
this is not meteor related

**Comment by TheFantasticLoki** [comment]
It is meteor related as crash still occurs with NOTHING ELSE but meteor: https://mclo.gs/pmElJiF @seasnail8169

**Comment by TheFantasticLoki** [comment]
it was this setting in the baritone settings.xml. this somehow got set incorrectly even tho it was never touched in game so could have happened due to meteor client: [pathingMapLoadFactor](https://baritone.leijurv.com/baritone/api/Settings.html#pathingMapLoadFactor) | Float | Default: 0.75f

**Comment by seasnail8169** [comment]
> It is meteor related as crash still occurs with NOTHING ELSE but meteor: [mclo.gs/pmElJiF](https://mclo.gs/pmElJiF) @seasnail8169

it's still a baritone crash, not a meteor crash
