### ISSUE TITLE
[Suggestion] rewrite peek module to change its aspect (to make it more useful and beautiful)

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#273]
With more investigation into the source code with IntelliJ idea, it could be pretty easy to modify by adding a visual option into the design of peek, which the container texture would be the tooltip background. The only thing to code would be the positioning of the tooltip box.
Other suggestions (#331).

![2021-02-25_21 19 06](https://user-images.githubusercontent.com/58893097/109245866-3cebca80-77af-11eb-8188-3ab1ae81f83c.png)

**Comment by RedCarlos26** [comment]
#410

**Comment by RedCarlos26** [comment]
O tough this was added in the latest dev build. I see now it's not added yet. Am I right @seasnail8169?

**Comment by seasnail8169** [comment]
I haven't finished writing better tooltips, thats why i said "part 1"

**Comment by RedCarlos26** [comment]
I see. Perfect. Personally, I would not group everything into the same module. I think it makes it too complicated for nothing, especially for people that are not really used to utility mods.
