### ISSUE TITLE
[Suggestion] AutoJumpbug

### ISSUE THREAD

**Issue by erxson** [MeteorDevelopment/meteor-client#2730]
### Describe the feature

Just automatize [this](https://youtu.be/hJuqwe23w_g) bug

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by seasnail8169** [comment]
patched on basically all server software
