### ISSUE TITLE
[Bug] Cant rejoin any servers after using spam on 1

### ISSUE THREAD

**Issue by logslmao** [MeteorDevelopment/meteor-client#2733]
### Describe the bug

after i used spam on a random server i cant join them anymore

### Steps to reproduce

```bash
Step 1: spam on a server
There
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by seasnail8169** [comment]
you can open the gui in the main menu.
