### ISSUE TITLE
[Suggestion] Auto-Remove Elytra

### ISSUE THREAD

**Issue by 0Ariel0** [MeteorDevelopment/meteor-client#2734]
### Describe the feature

Creating or not a module, it makes that when the elytra is close to breaking, it removes it automatically.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Mathrandom7910** [comment]
"This feature doesn't already exist in the client." 
Its literally in the elytrafly module

**Comment by Wide-Cat** [comment]
lol
