### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hacker-okan** [MeteorDevelopment/meteor-client#2736]
### Describe the bug

Profiles not showing and I cannot type in you guys discord 
![image](https://user-images.githubusercontent.com/110970707/189060797-926a9352-3a8e-42d1-88dc-d4296790a18e.png)
![image](https://user-images.githubusercontent.com/110970707/189060896-7efd36ca-c307-4f57-a5a5-4883b3c2474b.png)

### Steps to reproduce

```bash
I downloaded and played . Than I closed and re-opened it and everything has gone
```

### Meteor Version

5.0.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
You are not on the latest version of Meteor.
Update to latest and reproduce the issue or this will get ignored entirely.

**Comment by hacker-okan** [comment]
like u guys cant say If its not working go try the latest
What If I play on a 1.19 server

**Comment by GreemDev** [comment]
Use multiconnect or ViaFabric to connect to older servers. You're not going to get help with an old version, period, let alone an update to fix it.

**Comment by Mathrandom7910** [comment]
cracked player :rofl:

**Comment by AnhNguyenlost13** [comment]
btw you likely used a build newer than \#1586
