### ISSUE TITLE
Cant join from an illegalargexception

### ISSUE THREAD

**Issue by logslmao** [MeteorDevelopment/meteor-client#2738]
### Describe the bug

If i try to join a server it gives this error: IllegalArgumentException : Chat message is empty @com.google.common.base.Preconditions:145

### Steps to reproduce

```bash
i dunno sorry.
```

### Meteor Version

0.5.0

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
1.19 and 0.5.0 is not the latest development build, and yet you checked the box that says you did it on the latest version. Read.

Reproduce this on the latest version or cope

**Comment by logslmao** [comment]
lol i actually fixed it
