### ISSUE TITLE
Chunks dont render

### ISSUE THREAD

**Issue by ItzSkyReed** [MeteorDevelopment/meteor-client#2740]
### Describe the bug

Sometimes some chunks dont render and if you reproduce this bug twice the same chunks will not render. I dont saw this bug when I use build 1590

F3+A doesnt fix this; Disconnect and connect also dont help

![image](https://user-images.githubusercontent.com/93844414/189182115-b55e6a85-2e94-4d60-bdd7-4f5d4e236285.png)

### Steps to reproduce

```bash
Download 
meteor-client-0.5.1-1613
sodium-fabric-mc1.19.2-0.4.4+build.18
and it will randomly appear (about every third minecraft launch)
I tried older sodium version and this bug also appear
```

### Meteor Version

0.5.1-1613

### Minecraft Version

1 19 2 

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DesiCow** [comment]
Turn off "Defer-chunk-updates" video setting in Sodium.
