### ISSUE TITLE
FAQ error

### ISSUE THREAD

**Issue by PandaUprising** [MeteorDevelopment/meteor-client#2741]
### Describe the bug

It still says 1.18.2 not 1.19/1.19.2

<img width="296" alt="image" src="https://user-images.githubusercontent.com/110600797/189257741-0f0e33ee-fe11-4f45-b132-ed10a9149964.png">

### Steps to reproduce

```bash
Visit the FAQ page
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ehylo** [comment]
probably best to report this in the [meteor-website repo](https://github.com/MeteorDevelopment/meteor-website)

**Comment by PandaUprising** [comment]
Yeah, sorry didn't think of that
