### ISSUE TITLE
[Accounts] button crashes[Bug] 

### ISSUE THREAD

**Issue by Eliaskandil** [MeteorDevelopment/meteor-client#2744]
### Describe the bug

there is an problem where whenever i click the [accounts] button (located on the top right of the server's list) the game crashes, anyone help?

### Steps to reproduce

```bash
click the account button (the 0.5.1 dev version)
```

### Meteor Version

0.5.1 dev

### Minecraft Version

1.19.2

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by seasnail8169** [comment]
you didn't provide a crash report even though the form asks for one, how do you expect us to help

**Comment by Wide-Cat** [comment]
Reopen this if you attach a crash report.
