### ISSUE TITLE
Crash on Modpack "Better MC" because ArrayIndexOutOfBoundsException in NotebotUtils

### ISSUE THREAD

**Issue by CookieXD** [MeteorDevelopment/meteor-client#2745]
### Describe the bug

Crashing at the last stage of startup.
The error is:
[java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 17
	at meteordevelopment.meteorclient.utils.notebot.NotebotUtils](https://paste.ee/p/toeBp#:~:text=java.lang.ArrayIndexOutOfBoundsException%3A%20Index%2017%20out%20of%20bounds%20for%20length%2017)

**Java install**
[crash-2022-09-11_12.35.39-client.txt]
Eclipse Temurin JRE with Hotspot 18.0.2+9 (x64)

### Steps to reproduce

```bash
launching the game. 
(MultiMC with Modpack Better MC)
```

### Link to crash report/log if applicable
[crash-2022-09-11_12.48.22-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9542308/crash-2022-09-11_12.48.22-client.txt)

### Meteor Version

meteor client v0.5.1 build #1622

### Minecraft Version

1.19.2

### Operating System

Windows 11 22H2 Build 22000.918

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
the report you linked says that this is a notebot issue, not a wallhack one

**Comment by CookieXD** [comment]
> 

That's my mistake. I think I misunderstood the report...

**Comment by seasnail8169** [comment]
does this happen in latest dev? i believe notebot was changed quite a lot in a pr

**Comment by CookieXD** [comment]
with 1622 it still crashes.

**Comment by Wide-Cat** [comment]
Can you check to see if this happens with meteor on its own, and if it doesnt crash, then find which mod is causing the incompatibility. Might be a daunting task because you have a lot of mods, but if you disable half at a time and repeat as such you can find it out a lot quicker.
