### ISSUE TITLE
[Suggestion] add the ability to view the list of server plugins

### ISSUE THREAD

**Issue by LafayetteGPool** [MeteorDevelopment/meteor-client#2749]
### Describe the feature

Allows you to see a server's plugins
This feature is implemented in Impact client and LiquidBounce but there are older versions
Please add the ability to view the list of server plugins 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
`.server plugins` command
