### ISSUE TITLE
[Suggestion] Make trajectories predict multishot crossbows

### ISSUE THREAD

**Issue by GoodClover** [MeteorDevelopment/meteor-client#275]
At current trajectories will only predict the position of the main arrow, and not the others when you have multishot.

I think multishow is slightly random, but this is only a prediction.

![foo](https://user-images.githubusercontent.com/27222523/109520749-7882df00-7aa4-11eb-897a-3e3b65bf16ae.gif)

**Comment by ikearefrigerator** [comment]
that gui tho 😳

**Comment by RedCarlos26** [comment]
Is this really worth the effort? There is randomness in the trajectories of the arrows so it would not even be accurate

**Comment by MineGame159** [comment]
Added in 5fe1d3e4276e63df195d2d2fd6ecb97dfb76e6ec
