### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Michael2210** [MeteorDevelopment/meteor-client#2751]
### Describe the feature

More options to no fall like boat, snow, cobweb and ladder or separate module like auto mlg

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Mathrandom7910** [comment]
duplicate of #2307
