### ISSUE TITLE
All hostile entities[Suggestion] 

### ISSUE THREAD

**Issue by bobbehme** [MeteorDevelopment/meteor-client#2755]
### Describe the feature

Hi Guys, 

Is there a way to have something like kill aura attack all hostiles? I play with custom entities and obviously they don't show in the selection so are ignored

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Not how it works bud
