### ISSUE TITLE
[Bug] movebug with freecam

### ISSUE THREAD

**Issue by miam371** [MeteorDevelopment/meteor-client#2758]
### Describe the bug

It goes by itself in inventory ... and after it is like if you press your move key but you aren't
(sorry if the explanation was not good i am french)

### Steps to reproduce

```bash
active freecam
press a move key down
open the inventory
press the move key up
```

### Meteor Version

lastest

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
I think this has been fixed.
