### ISSUE TITLE
[Suggestion] normal autoMine

### ISSUE THREAD

**Issue by miam371** [MeteorDevelopment/meteor-client#2759]
### Describe the feature

something that causes the player to mine what they're looking at as if holding left click but not moving

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by seasnail8169** [comment]
auto click
