### ISSUE TITLE
Interupt: Network Error

### ISSUE THREAD

**Issue by An-m1654** [MeteorDevelopment/meteor-client#2762]
### Describe the bug

It Interupted in the middle of downloading the client

### Steps to reproduce

```bash
go to Meteor website and press dev or normal version, when downloading, BUG IS UP.
```

### Meteor Version

5.0.0/5.0.1

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Lovecrafts-Cat** [comment]
Have you tried using other browsers?
