### ISSUE TITLE
Starscript text conditional display literally checks for the text 'true'

### ISSUE THREAD

**Issue by EthanZeigler** [MeteorDevelopment/meteor-client#2763]
### Describe the bug

When using custom text hud elements, the 'shown' condition is checking for a `string` type "true" and will not use bools.

### Steps to reproduce

```bash
Text never displays:

1. Create a new arbitrary text hud element
2. Set `shown` to `when true`
3. Set condition to a truthy value such as `{2 > 1}`

Text displays when condition is true:

1. Create a new arbitrary text hud element
2. Set `shown` to `when true`
3. Set condition to a truthy value such as `{2 > 1}`, but stringify the result `{2 > 1 ? 'true' : 'false'}`
```

### Link to crash report/log if applicable (https://mclo.gs)

N/A

### Meteor Version

0.5.1-1592

### Minecraft Version

1.19.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
That is intended behavior but it should automatically stringify the boolean, will look at it later.

**Comment by Wide-Cat** [comment]
![image](https://user-images.githubusercontent.com/74723656/190729684-c2ed0293-3863-4181-86d6-e58984f52834.png)
It works completely fine for me. Send a picture of what your element looks like.

**Comment by seasnail8169** [comment]
wide cat brain

**Comment by Wide-Cat** [comment]
what?

**Comment by EthanZeigler** [comment]
What the heck... It works now. I promise y'all it didn't last week for me...

Whatever. I'll reopen the issue if it comes back.
