### ISSUE TITLE
Smart inventory

### ISSUE THREAD

**Issue by Vairoon** [MeteorDevelopment/meteor-client#2765]
### Describe the feature

Meteor dhould do a check for all players and their held item, if it is new it adds that item to a save of the players inventory. Thus .invsee is a bit better. It also should do a check if the player drops an item it remove as much as is dropped. Also dhould be .invsee reload (player), player is optional. Without it it just reset all memory for all inventory otherwise just the mentioned player.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Reading this gave me stage 5 cancer
