### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Mrfishy007** [MeteorDevelopment/meteor-client#2768]
### Describe the bug

when ever i join a sever the game almost immediately crashes and Minecraft tells me there was an unexpected issue and my game crashed and the exit code is '-1'. Pls help meteor is my favorite client for Minecraft

### Steps to reproduce

```bash
idk i just join any server
```

### Meteor Version

0.5.0 and 0.5.1

### Minecraft Version

1.19 and 1.19.2

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
where logs/crash report

**Comment by Mrfishy007** [comment]
i didnt have any

**Comment by GreemDev** [comment]
cope then

**Comment by Mrfishy007** [comment]
?

**Comment by GreemDev** [comment]
how do you expect anything to get fixed if you can't elaborate on what the issue is
it could be meteor, it could be any mod
