### ISSUE TITLE
"java.lang.ArrayIndexOutOfBoundsException" Error upon Initialization

### ISSUE THREAD

**Issue by daedx** [MeteorDevelopment/meteor-client#2769]
### Describe the bug

Upon initializing Minecraft, I receive a crash report. 
I'm using other mods as well. 

### Steps to reproduce

```bash
1. Initialize minecraft.
2. Profit.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/mGBRQV6

### Meteor Version

Dev Build 0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Can you check to see if this happens with meteor on its own, and if it does, then find which mod is causing the incompatibility. Might be a daunting task because you have a lot of mods, but if you disable half at a time and repeat as such you can find it out a lot quicker.

**Comment by Wide-Cat** [comment]
Shoukd be fixed on the latest dev build
