### ISSUE TITLE
Meteor Client crashes on Quilt Loader after dev-build 1588

### ISSUE THREAD

**Issue by JoopiterGD** [MeteorDevelopment/meteor-client#2770]
### Describe the bug

Meteor Client crashes before launch on Quilt Loader after dev-build 1588.

### Steps to reproduce

```bash
For me, using PolyMC, on the latest Quilt version, any Meteor version higher than 1588 dev-build will crash the game before it fully launches. Just put it in the mods folder, and no matter what mods are or are not in there, it will crash.
```

### Meteor Version

1589+

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ehylo** [comment]
Meteor is made for fabric, not quilt
