### ISSUE TITLE
command not working on feather client

### ISSUE THREAD

**Issue by utilityuser2048** [MeteorDevelopment/meteor-client#2772]
### Describe the bug

Hello, i am using meteor on feather client, but the commands does not work on feather client. i bounded command to . and every time i type command like .toggle kill-aura, it will just send straight in chat instead of toggling it. I don’t know why but it bothers me. I would really appreciate if you could solve the issue. Thank you.

### Steps to reproduce

```bash
i tried to use . command in client. but it does not work, it send the command i typed into the chat and everyone could see it
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
feather is not supported

**Comment by utilityuser2048** [comment]
but i mean, you can download meteor on feather and it works. so the commands are supposed to work too in my opinion.

**Comment by GreemDev** [comment]
your opinion is irrelevant here.
feather is literally listed in meteor's [`breaks`](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/resources/fabric.mod.json#L51).
you are also on an outdated version.

**Comment by I-Got-You-Dead** [comment]
Meteor doesn’t support skidded clients and is officially stated on anticope.ml

**Comment by seasnail8169** [comment]
> Meteor doesn’t support skidded clients and is officially stated on anticope.ml

anticope is not official. it's not affiliated with meteor in any way

**Comment by I-Got-You-Dead** [comment]
> > Meteor doesn’t support skidded clients and is officially stated on anticope.ml
> 
> anticope is not official. it's not affiliated with meteor in any way

Didn’t minegame say it was partnering?

**Comment by I-Got-You-Dead** [comment]
I could have sworn he said it was
