### ISSUE TITLE
error related to indium or memoryleakfix? 

### ISSUE THREAD

**Issue by zerisius** [MeteorDevelopment/meteor-client#2778]
### Describe the bug

crash related to indium or memoryleakfix? i dont know

### Steps to reproduce

```bash
start the game
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/JQ6cDGV

### Meteor Version

meteor-client-0.5.1-1624.jar

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ehylo** [comment]
There is no crash in that log

**Comment by zerisius** [comment]
> There is no crash in that log

the problem is on line 709

**Comment by ehylo** [comment]
What exactly is the problem? I see no crash on that line...

**Comment by zerisius** [comment]
there is no crash just this error. not sure what causes it
