### ISSUE TITLE
EPS Perspective has no effect[Bug]

### ISSUE THREAD

**Issue by zengkuankuan** [MeteorDevelopment/meteor-client#278]
![QQ图片20210303231751](https://user-images.githubusercontent.com/53440794/109827566-cfd8a900-7c76-11eb-90e8-0b0acc69ef08.png)

**Comment by seasnail8169** [comment]
Can you explain what you mean a little more clearly?

**Comment by zengkuankuan** [comment]
> 您能更清楚地解释一下您的意思吗？

![QQ图片20210306233537](https://user-images.githubusercontent.com/53440794/110212097-ba60ba80-7ed4-11eb-97aa-d10e63acebe5.png)
Monster animal display

**Comment by seasnail8169** [comment]
I dont understand what you mean.

**Comment by zengkuankuan** [comment]
> 我不明白你的意思。

I use meteor client can't use monster animal display, don't you have this function

**Comment by seasnail8169** [comment]
I'm going to close this because i dont really understand what you mean and i dont think its a bug anyway.
