### ISSUE TITLE
[Suggestion] .swarm cleararea 

### ISSUE THREAD

**Issue by Razzy52** [MeteorDevelopment/meteor-client#2781]
### Describe the feature

Similar to baritone's sel command, this could be used to control multiple accounts to clear an area with minimal control, giving small chunks for one account to clear, but overall a much larger area could be cleared with minimal effort, ideally this feature would also have a chest they can dump items into and a chest they can pick up needed resources from. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
fr

**Comment by seasnale** [comment]
im pretty certain nobody will ever go through the pain of making this work, but nice idea
