### ISSUE TITLE
X-ray with exposed only setting does not render some faces of ores

### ISSUE THREAD

**Issue by PLCebulak** [MeteorDevelopment/meteor-client#2786]
### Describe the bug

when using x-ray with exposed only setting, some faces of ores dont render

### Steps to reproduce

```bash
- enable x-ray with Exposed only setting
- look at any ore
```

### Meteor Version

v0.5.1-1624

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by nyncral** [comment]
it also does that without "exposed only" enabled for me

**Comment by I-Got-You-Dead** [comment]
> it also does that without "exposed only" enabled for me

same but there aint much you can do about it

**Comment by nyncral** [comment]
> > it also does that without "exposed only" enabled for me
> 
> same but there aint much you can do about it

I think for me it's because of a sodium setting I have enabled, sorry

**Comment by I-Got-You-Dead** [comment]
Sodium definitely has something to do with it, but I don’t use X-ray enough to care

**Comment by Wide-Cat** [comment]
Most likely a mod compatibility issue. If you have the more culling mod installed, go into its settings and disable block state culling. As of writing thats the only way I know that this issue can occur.
