### ISSUE TITLE
Sprint Stuttering

### ISSUE THREAD

**Issue by TechDude100** [MeteorDevelopment/meteor-client#2787]
### Describe the bug

The sprint module breaks when you hit a block jump. You then stutter sprint. 

### Steps to reproduce

```bash
When the sprint module is turned on, and you run straight into a block, then you jump, your player will stutter sprint in the air and on the ground. The only way to fix this is to reset your movement and start moving again.
```

### Meteor Version

meteor-client-0.5.1-1584

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
Probably fixed in the SimpleOptionMixin commit.

**Comment by Wide-Cat** [comment]
I think this has been fixed as of the sprint changes in recent months.
