### ISSUE TITLE
[Bug] inventory tweaks auto steal doesnt work

### ISSUE THREAD

**Issue by easyloo** [MeteorDevelopment/meteor-client#2788]
### Describe the bug

when opening containers it doesnt automatically steal items. however clicking the steal button it steals items. Also auto dump **does** work

### Steps to reproduce

```bash
turning on auto steal
```

### Meteor Version

meteor-client-0.5.1-1626

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DivisonOfLife** [comment]
https://github.com/MeteorDevelopment/meteor-client/issues/2401

**Comment by ThebestkillerTBK** [comment]
its trying to steal when the container packet wasnt received
