### ISSUE TITLE
[Bug] Problem with NameProtect

### ISSUE THREAD

**Issue by miam371** [MeteorDevelopment/meteor-client#2790]
### Describe the bug

https://user-images.githubusercontent.com/112278239/192137924-82922c16-eb29-4572-a4f0-08104788c9f0.png

### Steps to reproduce

```bash
Have "<Pseudo> IS YOU" in the home menu
```

### Meteor Version

lastest

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Just make a texture pack

**Comment by seasnail8169** [comment]
its displayed in the top left of the multiplayer menu
