### ISSUE TITLE
My minecraft doesnt start with Meteor for some reason

### ISSUE THREAD

**Issue by arul-PVP** [MeteorDevelopment/meteor-client#2792]
### Describe the bug

Hello!My issue is that I am unable to launch my game with Meteor Client.... (0.5.0 and the newer one). When I launch the game without it, just just runs perfectly fine.
I am unable to find any clue to get rid of this "error" or "bug" but yeah.. that's it..

these r the mods im using:

![image](https://user-images.githubusercontent.com/86644276/192157480-1cfe0e29-4a25-45ee-99d4-7f8f589f1bd6.png)

### Steps to reproduce

```bash
Using the game with Meteor with the above mentioned mods... If I don't use meteor, everything works fine.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/X44BjDW

### Meteor Version

meteor-client-0.5.1-1626

### Minecraft Version

Release fabric-loader-0.14.9-1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by arul-PVP** [comment]
Oh, and I can perfectly launch Meteor WITHOUT any mods... for that, I lose all my mods... that's why

**Comment by Wide-Cat** [comment]
It looks like a mod incompatibility, so you want to find which mod is causing it. My first guess would be WI-Zoom, but I could be wrong

**Comment by I-Got-You-Dead** [comment]
Wurst zoom 💀
