### ISSUE TITLE
invisible

### ISSUE THREAD

**Issue by loekd31231231** [MeteorDevelopment/meteor-client#2796]
### Describe the bug

when i use meteor client all the chest and signs are invisible 

### Steps to reproduce

```bash
the chests and signs are always invisible
```

### Link to crash report/log if applicable (https://mclo.gs)

?

### Meteor Version

v0.4.9:

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Lemme guess you use enhanced block entities?
