### ISSUE TITLE
Built in MultiConnect

### ISSUE THREAD

**Issue by Depedria** [MeteorDevelopment/meteor-client#2797]
### Describe the feature

Built in MultiConnect

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
No.

**Comment by StormyBytes** [comment]
Quite sure this is a duplicate suggestion as well.
