### ISSUE TITLE
[Suggestion] Manually add a seed to oresim

### ISSUE THREAD

**Issue by Razzy52** [MeteorDevelopment/meteor-client#2798]
### Describe the feature

Currently Oresim only allows you to use it if it has done lifting already, i think you should be able to manually put in the seed, by doing .oresim seed (seed) this'll allow you to use xray more easily on servers that have anti xray. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
You already can dumbass

**Comment by I-Got-You-Dead** [comment]
Also this ain’t meteor rejects
