### ISSUE TITLE
[Bug] riptide tridents dont work with velocity enabled

### ISSUE THREAD

**Issue by ikearefrigerator** [MeteorDevelopment/meteor-client#280]
when trying to use riptide tridents, after releasing right click button the player wont move. the player will move after disabling velocity, as expected.

**Comment by ikearefrigerator** [comment]
0.4.1 btw

**Comment by seasnail8169** [comment]
This was fixed in [this](https://github.com/MeteorDevelopment/meteor-client/commit/eb2077c50de700791e9c7c2cbb8f52f5e8b97b2c) commit as far as i know.
