### ISSUE TITLE
Game crashes when i write .settings

### ISSUE THREAD

**Issue by seujorgenochurras** [MeteorDevelopment/meteor-client#2800]
### Describe the bug

When u write _.settings search add_ it crashes the game

### Steps to reproduce

```bash
Enter a multiplayer server
type .settings search add
crashed .-.
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by StormyBytes** [comment]
Crash report

**Comment by seujorgenochurras** [comment]
[crash-2022-09-30_00.21.08-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9685169/crash-2022-09-30_00.21.08-client.txt)


> Crash report

**Comment by seujorgenochurras** [comment]
> Crash report

https://mclo.gs/OmLJmOq

**Comment by ThebestkillerTBK** [comment]
works fine for me

**Comment by StormyBytes** [comment]
@seujorgenochurras try see if the issue persists on the latest dev build

**Comment by Big-Iron-Cheems** [comment]
Closed because of inactivity from the author.
Reopen if this is still an issue on the latest dev build.
