### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by craac** [MeteorDevelopment/meteor-client#2801]
### Describe the feature

Add an option to Aim Assist so that you can stop it from targeting spectators

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
You can’t see spectators anyway
