### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by craac** [MeteorDevelopment/meteor-client#2803]
### Describe the feature

Add the option to download previous versions of meteor, you can currently download the most recent official version and the dev build, but to connect to a server on any previous version you need viaversion or multiconnect, and therefore can’t play a 1.18 server with any 1.18 mods. There are versions of the client for 1.18, they just aren’t available. Maybe lock it behind a paywall or something but at least make it an option. (This is kind of in the FAQ, but that just says to use viaversion or multiconnect, which don’t solve the issue)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
“This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)”
