### ISSUE TITLE
HUD editor is completely unusable.

### ISSUE THREAD

**Issue by 123stein** [MeteorDevelopment/meteor-client#2806]
### Describe the bug

I was trying to play meteor client on my Mac, (m1 pro) and the hud editor is completely broken. Every time I try to click an element it starts a drag box from a seemingly random position on the screen to the point where I clicked. I can not properly drag items not right click to edit them.

### Steps to reproduce

```bash
(I do not know if it is a problem related to my hardware specifications, I have a m1pro processor and run macOS on the latest update, if that helps)
1) Press R-Shift
2) Go to the HUD sector
3) Press on Edit
4) Try to adjust your hud
```

### Meteor Version

0.5.0+

### Minecraft Version

1.19+

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by seasnail8169** [comment]
dont install windows on your mac just so you can use meteor lmao

**Comment by seasnale** [comment]
this is fixed apparently
