### ISSUE TITLE
Could I please join the meteor dev team?

### ISSUE THREAD

**Issue by Cohejh** [MeteorDevelopment/meteor-client#2808]
### Describe the feature

I have advanced knowledge and experience in Java and modding, and would like to join your team, I really love Meteor, and want to help with its development. (I have dabbled in Client making myself) My discord is COHEJH#1413.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Mathrandom7910** [comment]
lol
