### ISSUE TITLE
config addition

### ISSUE THREAD

**Issue by bigdog4127** [MeteorDevelopment/meteor-client#2809]
### Describe the feature

ability to hide "logged in as <name>" and "not using a proxy" in the multiplayer menu

also the ability to hide the buttons in the multiplayer menu, but this is less of a concern because you can hide the buttons with fancymenu

you can hide the splashes and credits in the title screen so it only makes sense to be able to hide those as well

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by seasnail8169** [comment]
the options to disable main menu stuff exist because people might find it intrusive. the multiplayer stuff, however, has an important function.
