### ISSUE TITLE
Automatic frostwalker disable enhancment?

### ISSUE THREAD

**Issue by Peng1029** [MeteorDevelopment/meteor-client#2810]
### Describe the feature

Today I noticed myself using frostwalker, I also realized that while using anti-hunger frostwalker basically doesn't work
So here is the idea for the enhancement: 
A new option for this under anti-hunger or a new option for this where it temporary does whatever anti-hunger does to basically disable frostwalker if it detects you holding a water bucket or specific item.  

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ThebestkillerTBK** [comment]
Just disable Anti Hunger no need to add this

**Comment by Peng1029** [comment]
@ThebestkillerTBK Nah like the opposite, 
an option to turn it on while holding a bucket so you don’t die from using frostwalkers while falling

idk

**Comment by I-Got-You-Dead** [comment]
frfr
