### ISSUE TITLE
[Suggestion] Movement adds/changes

### ISSUE THREAD

**Issue by Oliver941** [MeteorDevelopment/meteor-client#2813]
### Describe the feature

First of all, I want to thank you for your amazing work!
This is by far the best client I have ever seen/used! Please keep up the great work!
I'm soo happy about this meteor client!

I have a few questions and suggestions for auto walk/movement in general.
I don't quite understand the auto walk smart mode, it seems to be kinda "smart" but where does it want to go?

• Locations •
I suggest adding a location option to the smart function, this way the user will be able to choose where to walk, this would make a HUGE difference!

• Auto Pickup •
would be some kind of auto walk, just where it walks and "auto pickup" certain dropped items in an x radius, and if you made an option "only stacks" as well, that would be perfect! This would work very nicely with nuker and ofc in many other ways as well!

• Follow •
This would ofc follow and/or go to a specific entity, either a specific player or/and follow go to a specific entity type, this would work so well with kill aura and a lot of other features!

• Route •
With this the user should be able to make a route, containing multiple locations, then the auto walk would go from location to location in the order the player made it, maybe even add the option to take breaks in between locations?

This would make it much easier and/or possible to do a lot of automating, lets for example say that the user makes a route between all the user's auto-farms, in this way, all of them would stay active, and the user would even be able to kill the mobs in the mob farms on the route as well!

This would also be extremely good to make an auto digging/mining system, especially if you add the option to disable the y-axis, so the user would just move to the desired x and z. With nuker and such, this could clear out a whole desired area!
VERY COOL!

Once again, thank you so much for making this whole client with all of its features available and possible for us!
It means so much to me! <3

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
1: 3 of these things are already in the client
2: The remaining 2 things have already been suggested and denied 
3: Look at addons or make ur own
4: Actually complete ‘before submitting a suggestion’ and don’t just tick the boxes

**Comment by I-Got-You-Dead** [comment]
Also, something I forgot to say is ‘smart’ auto walk uses baritone to avoid obstacles, get over mountain and parkour.

**Comment by Oliver941** [comment]
whats the names? I have been looking for all of them and can't find it

**Comment by I-Got-You-Dead** [comment]
Do #help for baritone

**Comment by ThebestkillerTBK** [comment]
* Location: Baritone goto
* Follow: Baritone follow
* Auto pickup: Meteorist addon
* Route: You can write a mod to make baritone take breaks and go between different locations

**Comment by I-Got-You-Dead** [comment]
ye

**Comment by StormyBytes** [comment]
As said above, baritone is already integrated into the client. Run `#help` or if you need more help on baritone, check out the baritone discord they have a support channel there.
