### ISSUE TITLE
fastbow

### ISSUE THREAD

**Issue by Calamaldo** [MeteorDevelopment/meteor-client#2815]
### Describe the feature

spam arrows like a minigun

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
“Bow spam” 🤡
