### ISSUE TITLE
Copy paste color settings [Suggestion] 

### ISSUE THREAD

**Issue by duckyz1** [MeteorDevelopment/meteor-client#2816]
### Describe the feature

Copy paste hex or rgb settings easier. 
Or add hex so we can ctrl + c   ctrl + v  color settings from one to another. 
Or add a palette that we can choose the past colors used so we don't have to copy paste it manually. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
already a thing
































































































cope

**Comment by ThebestkillerTBK** [comment]
> cope

nah you can only copypaste rgb not hex

**Comment by I-Got-You-Dead** [comment]
¯\_(ツ)_/¯
