### ISSUE TITLE
[Suggestion] Custom Launcher

### ISSUE THREAD

**Issue by saltinn** [MeteorDevelopment/meteor-client#2817]
### Describe the feature

Make your own launcher just like Liquidbounce. This would make the client more modern

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
no
