### ISSUE TITLE
Make the alt system like wust

### ISSUE THREAD

**Issue by Joebidenfortnite** [MeteorDevelopment/meteor-client#2821]
### Describe the feature

I find it hard to make an alt

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Lovecrafts-Cat** [comment]
Nothing is hard about making an alt.
It just requires the credentials to a valid Microsoft account, or a username for cracked ones.
