### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by haipabli** [MeteorDevelopment/meteor-client#2822]
### Describe the bug

HUD editor does not click, select or highlight the modules correctly. Whenever you click regardless if it's a drag, it goes into click and drag mode. HUD modules can't be deleted and are highlighted in red if wanted to be disabled. 

### Steps to reproduce

```bash
In the Hud editor, try to drag/click and select HUD modules.
```

### Meteor Version

meteor-client-0.5.1-1630

### Minecraft Version

1.19.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by seasnail8169** [comment]
duplicate
