### ISSUE TITLE
Minecraft Crash 

### ISSUE THREAD

**Issue by xqwiz** [MeteorDevelopment/meteor-client#2823]
### Describe the bug

I put the mod in the mods folder with no other mods on it and i launch the game on the latest fabric version and it crashes

### Steps to reproduce

```bash
I dont know it just crashes
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/TEnRJbJ

### Meteor Version

0.5.0

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Lovecrafts-Cat** [comment]
You are using TLauncehr, that's the issue.
We do not support craced users/launchers.

**Comment by xqwiz** [comment]
nah its fixed now with dev build and i own minecraft i tried on both

**Comment by Lovecrafts-Cat** [comment]
> nah its fixed now with dev build and i own minecraft i tried on both

May I ask then, why are you using an unsafe launcher instead of something good, like PolyMC for example?

**Comment by I-Got-You-Dead** [comment]
> > nah its fixed now with dev build and i own minecraft i tried on both
> 
> May I ask then, why are you using an unsafe launcher instead of something good, like PolyMC for example?

Cuz their mom won’t buy em minecraft 💀

**Comment by xqwiz** [comment]
nah i own minecraft i use tlauncher cus somehow i like it better 
![image](https://user-images.githubusercontent.com/98247108/194829016-c4d0918b-e1a9-46c7-be5e-bef562af4dd7.png)
there monkey ass nigga i own it

**Comment by I-Got-You-Dead** [comment]
> nah i own minecraft i use tlauncher cus somehow i like it better
> ![image](https://user-images.githubusercontent.com/98247108/194829016-c4d0918b-e1a9-46c7-be5e-bef562af4dd7.png)
> there monkey ass nigga i own it

Bros fr using borderline malware to play mc 💀

**Comment by Mathrandom7910** [comment]
> nah i own minecraft i use tlauncher cus somehow i like it better

Spanish player using a cracked launcher (shocking)
And tlauncher is literally the worst launcher, not to mention the spyware 💀

**Comment by I-Got-You-Dead** [comment]
> > nah i own minecraft i use tlauncher cus somehow i like it better
> 
> Spanish player using a cracked launcher (shocking) And tlauncher is literally the worst launcher, not to mention the spyware 💀

frfr
