### ISSUE TITLE
make 0.5.0 suitable with 1.18

### ISSUE THREAD

**Issue by SoulCatcher12** [MeteorDevelopment/meteor-client#2824]
### Describe the feature

make the 0.5.0 version of meteor for the fabric 1.18.2

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by StormyBytes** [comment]
"on GitHub and read the **FAQ**"
Well you didn't read the faq if you're asking for this.
