### ISSUE TITLE
unable to downlad meteor latest version.....[Bug] 

### ISSUE THREAD

**Issue by sarveshprince** [MeteorDevelopment/meteor-client#2826]
### Describe the bug

IF I DOWNLOAD THE LATEST VERSION OF METEOR MOD .. IT ISNT DOWNLOADING.. AND TELL COULDNT DOWNLOAD NETWORK ISSUE.. BUT MY NET IS FINE WITH OTHER THINGS.. AND IT IS ALSO SPEED UP TO 400KBS ...

### Steps to reproduce

```bash
CAN REPLY FOR IT AND HELP US TO DOWNLOAD IT..
```

### Meteor Version

1.19.2

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Lovecrafts-Cat** [comment]
Have you tried downloading with another device or browser?
Also, you not being able to download from the website is not our issue, unless if it was a widespread problem.

**Comment by Mathrandom7910** [comment]
I not inglish
