### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Vrext** [MeteorDevelopment/meteor-client#2829]
### Describe the feature

An addition to auto log feature where you would automatically disconnect if you get moved or teleported. Many people use clients to AFK farm, which isn't allowed on a lot of servers. The way staff members usually check if you are AFK farming is TP you away to check if you are still hitting/interacting with anything. As soon as they would do that, you would log off preventing them from confirming if you are AFK farming or not. 

This would allow to avoid a lot of bans :D 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
And then they would ban u for leaving in exactly 0.361 seconds after they tp u + don’t use meteor where it’s not allowed

**Comment by Wide-Cat** [comment]
This isn't something that's going to be added, because you shouldn't use meteor on servers that don't allow it
