### ISSUE TITLE
Changing Keybind n shi

### ISSUE THREAD

**Issue by NoLifeNoWife** [MeteorDevelopment/meteor-client#2830]
### Describe the feature

uhhh so like how do i remove the keybind button as a whole or change the name of the keybind to something else besides "open gui"
?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
what

**Comment by NoLifeNoWife** [comment]
> what

ughhh uhhh!!!! im trying to find out how to change to prefix for the keybind in controls or removing it as a whole

**Comment by RacoonDog** [comment]
:skull:
no one tell him

**Comment by NoLifeNoWife** [comment]
> 💀 no one tell him

already figured out how to remove the keybinds from controls
