### ISSUE TITLE
Meteor Client Crashing

### ISSUE THREAD

**Issue by theprisoner55** [MeteorDevelopment/meteor-client#2831]
### Describe the bug

On 1.19.2, (possibly other versions) when I log on and join a server, it just crashes. I found out that it had to do with already turned on hacks (From previous sessions) being turned on. So, to fix this, I have to turn the hacks off and on, and it's just really frustrating.

### Steps to reproduce

```bash
1. Log onto meteor client with hacks that were already enabled before you logged on
2. join a server
3. be crashed
```

### Meteor Version

0.5.1-1629

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ehylo** [comment]
need the log
