### ISSUE TITLE
[Suggestion] Combat And Movement

### ISSUE THREAD

**Issue by NecroxEye** [MeteorDevelopment/meteor-client#2870]
### Describe the feature

Mby add a Trigger Bot And Legit Scaffold  for servers with better anti cheat like Mineland . 
The Legit Scaffold to Auto Shift At The Edge Of The Block And Manualy Or Auto Place A Block In The Direction Client Its Looking At So it bypasses better anti cheat and can get better for those who want to cheat not that much . 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Don’t use motor cliwnt on servers where it’s not allowed
