### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Rberigah** [MeteorDevelopment/meteor-client#2871]
### Describe the feature

You could add a feature that auto swaps a totem when you're close to death/ low hp (you can change when it swaps depending on how many hearts you have) and maybe it could swap other items back after like perhaps a shield. also maybe a cool feature would be to see how many totems a enemy player has left though i wouldnt know how you would add this. thanks

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
retard
