### ISSUE TITLE
smarter crystal aura with more settings.[Suggestion] 

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#2872]
### Describe the feature

currently the crystal aura of meteor client is not very powerful and not a lot of settings, there is only 4 pages of settings(general, place, break, render.) I like to see more setting in crystal aura. and also maybe add a setting in crystal aura called "ai", it is basically an 
self improving ai that choose where to place and break crystal based on the settings instead of just always the same "crystal aura". the ai will probably be less powerful then a vanilla player at the start but when you use the ai more and more, the ai's crystal placement become smater and smarter. it would be nice to have a crystal aura ai be like a chess ai.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
what the fuck are you on about

**Comment by Mathrandom7910** [comment]
LOL

**Comment by Maxo6453** [comment]
Your request to improve crystal aura is incredibly general and unhelpful, and a self-improving crystal aura ai would most likely take hundreds of hours to code and debug. Please make more specific and reasonable requests in the future.

**Comment by Wide-Cat** [comment]
This is beyond the current scope of the project
