### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by 97maxim97** [MeteorDevelopment/meteor-client#2873]
### Describe the feature

No render module is just hiding entities but i still feel the lag in farms, it would be cool if it completely turns of the selected entity so there wont be lags if there is too much entities

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by StormyBytes** [comment]
Can you screenshot the debug menu (Alt + F3, the pie chart is needed) while you have no render on and is within render range of the farm entities? 
The pie chart should show where most of the lag is coming from.

**Comment by 97maxim97** [comment]
this?
![image](https://user-images.githubusercontent.com/113803604/197188829-49a198d8-12bc-4c7d-b412-24b0993bf5ef.png)

**Comment by StormyBytes** [comment]
ah. most of its coming from `tick`. go figure. I don't think cancelling the entity tick processing would be a good idea since it would also cancel the physics calculations and other updates. Perhaps you should try using [lithium](https://modrinth.com/mod/lithium/version/mc1.19.2-0.10.0) or decreasing your entity range in video settings.

**Comment by I-Got-You-Dead** [comment]
Just remove the entities from the world, isn’t hard

**Comment by Wide-Cat** [comment]
Yeah it's easy to just remove the entities, but how easy is it to add them back?

**Comment by I-Got-You-Dead** [comment]
Relog :p

**Comment by I-Got-You-Dead** [comment]
Or just have an option for both methods

**Comment by Wide-Cat** [comment]
has been added with the drop spawn packets setting
