### ISSUE TITLE
[Bug] Shulker peek since build 605 (version 0.4.2)

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#288]
Peek and default tooltip override each other. Happens when on always mode.

![2021-03-07_17 02 51](https://user-images.githubusercontent.com/58893097/110256452-fd6b6e00-7f66-11eb-9024-94ef37749533.png)

**Comment by RedCarlos26** [comment]
Still happens in build 606.

**Comment by ikearefrigerator** [comment]
whats that resource pack? also a probable fix for this is to set the shulker peek settings to press a button to view the contents, instead of having them displayed all the time.

**Comment by RedCarlos26** [comment]
> whats that resource pack? also a probable fix for this is to set the shulker peek settings to press a button to view the contents, instead of having them displayed all the time. 

This resource pack is an edit of DynamicDuo, that I custom made.

**Comment by CraftingDNA** [comment]
This is something that happens when you have advanced tooltips enabled and is caused because the developers set the peek inventory to a position where it overlaps with the tooltips. You can either turn off advanced tooltips or set shulker peek to appear only on button press in order to temporarily fix this until the developers come up with a solution

**Comment by RedCarlos26** [comment]
> This is something that happens when you have advanced tooltips enabled and is caused because the developers set the peek inventory to a position where it overlaps with the tooltips. You can either turn off advanced tooltips or set shulker peek to appear only on button press in order to temporarily fix this until the developers come up with a solution

I know that. Thanks anyway!

**Comment by RedCarlos26** [comment]
Fixed in 0.04.2 build 648.
