### ISSUE TITLE
[Suggestion] Re-add the HUD toggle keybind

### ISSUE THREAD

**Issue by sumone-lol** [MeteorDevelopment/meteor-client#2882]
### Describe the feature

The HUD toggle keybind was removed when the HUD was rewritten some time ago so add it back i guess.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
just make a macro with .t hud
