### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by okcolton** [MeteorDevelopment/meteor-client#2884]
### Describe the feature

I really thing you guys should add teleport hit and fast place. Teleport hit is where you can hit someone from far away. Fast place is where you can place blocks really fast please and thank you have a good day. btw i said this cuz it was in liquid bounce client and i used to use it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
For the first one, I don't believe teleport hit is possible on versions greater than about 1.12, although I might be wrong. As for the second one, that's already a module - 'fast use'

**Comment by StormyBytes** [comment]
Also teleport hit was already suggested on github before so you weren't looking enough
