### ISSUE TITLE
[Bug] Illegal enchantment causes the game to crash

### ISSUE THREAD

**Issue by DesiCow** [MeteorDevelopment/meteor-client#2886]
### Describe the bug

InventoryTweaks' `swap armor` setting crashes the game when player interacts with a armor item having illegal enchantments.

### Steps to reproduce

```bash
Turn on InventoryTweaks
Turn on armorSwap setting
Interact with an armor item having illegal enchantment(s)
Game crashes
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/xHJjpsz

### Meteor Version

0.5.1-1651

### Minecraft Version

1.19.2(760)

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
What enchantments did you put on the armour that caused it to crash?

**Comment by I-Got-You-Dead** [comment]
Works with anything non obtainable in gms

**Comment by DesiCow** [comment]
> What enchantments did you put on the armour that caused it to crash?

All the enchantments of level 255 possible on that specific item, works with anything non obtainable in gms.
