### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by renrweeeeeeen** [MeteorDevelopment/meteor-client#2889]
### Describe the feature

Hello, I recently discovered this problem when mining a certain block/ore. When mining, it will instantly stop because it cannot jump. I'm not sure if I'm the only one who has this problem, but I find this bug really unpleasant because you have to halt the mine orders to correct the bug in the hacks.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by StormyBytes** [comment]
https://discord.com/channels/689197705683140636/799337249526644767/1032951205565042718
moment
