### ISSUE TITLE
[Suggestion] Starscript CPS

### ISSUE THREAD

**Issue by Ompyl** [MeteorDevelopment/meteor-client#2896]
### Describe the feature

A cps variable for clicks per second in Starscript

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by airplane** [comment]
What would this even be used for, aren't they basically useless on 1.9+

**Comment by Ompyl** [comment]
> 

and if you play on 1.8 or lower?

**Comment by airplane** [comment]
I mean I guess so but that still seems kinda odd to add considering meteor wasn't made for 1.8

**Comment by qeqeqeplayer533** [comment]
or cps = crystal per second?

**Comment by Ompyl** [comment]
> or cps = crystal per second?

clicks per second

**Comment by MineGame159** [comment]
Done now.
