### ISSUE TITLE
Is metor a rat/harmful to my pc?

### ISSUE THREAD

**Issue by BobyRoss1** [MeteorDevelopment/meteor-client#2897]
### Describe the feature

.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
yes

**Comment by Lovecrafts-Cat** [comment]
It's literally open source, with millions of downloads/users.
I think someone would have pointed that out if it was dangerous in any way.

**Comment by Astral4610** [comment]
It steals your passwords yes

**Comment by Mathrandom7910** [comment]
BRO ITS A VIRUS RAT THAT WILL HACK INTO YOUR PC AND START DOWNLOADING EVERY MINECRAFT HACK UNTIL YOUR PC EXPLODES
