### ISSUE TITLE
Crash with mod KronHUD

### ISSUE THREAD

**Issue by dlfnn** [MeteorDevelopment/meteor-client#2899]
### Describe the bug

Game crash with Meteor and KronHUD together

### Steps to reproduce

```bash
Instal both Meteor and KronHUD, launch the game
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/KpCCTvl

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
I use this and it’s fine, skill issue

**Comment by dlfnn** [comment]
> I use this and it’s fine, skill issue

Same version? Do I need to manually fix by changing the mixin of one of the mods?

**Comment by I-Got-You-Dead** [comment]
Yes same version

**Comment by I-Got-You-Dead** [comment]
I would assume it’s a problem with kronhud, not meteor by looking at the log

**Comment by dlfnn** [comment]
> I would assume it’s a problem with kronhud, not meteor by looking at the log

Fine I'll remove kron's config file and isolate the two and try again

**Comment by I-Got-You-Dead** [comment]
I’ll have a better look when I get home and see if I can replicate the crash

**Comment by Mathrandom7910** [comment]
Seems to be with meteor's baritone fork

**Comment by dlfnn** [comment]
I updated Kron to the newest version, reinstalled Meteor from meteorclient.com, desabled all unnessecary mods, and now it still crash.
log: https://mclo.gs/CwmoCAM

**Comment by ThebestkillerTBK** [comment]
I created an PR in Kron's repo and it fixed that https://github.com/DarkKronicle/KronHUD/pull/99
