### ISSUE TITLE
[WEBSITE | CLOUDFLARE] Meteorclient.com connection timed out. [CODE 522]

### ISSUE THREAD

**Issue by Dnotcashier** [MeteorDevelopment/meteor-client#2900]
### Describe the bug

![image](https://user-images.githubusercontent.com/90368579/197382422-31940670-0d59-48d7-91b3-b1d42b962cdf.png)
Basically servers at meteorclient.com said "fuck you, no website 4 you". Error code 522.

Uhh yeah here's some info google shared.
![image](https://user-images.githubusercontent.com/90368579/197382557-ac0dcce7-8817-412c-aa0a-017790602aa6.png)

It's been happening since like 7 pm for me CST gmt-5, might've been going on for a day or more but it seems like a day, If anyone could share the discord server invite link or report it to higher ups it'll be nice. This is a SEVERE issue. like all of the meteor client websites are down, like https://meteorclient.com/discord and so on.

### Steps to reproduce

```bash
1. open any browser, im using firefox for this example.
2. go to https://meteorclient.com/ you can try out other stuff like meteorclient.com/discord and so on.
3. haha issue go brrr.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://meteorclient.com/

### Meteor Version

NAN

### Minecraft Version

NAN

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Dnotcashier** [comment]
Realll bad issue.

**Comment by I-Got-You-Dead** [comment]
🌰

**Comment by Dnotcashier** [comment]
totally useful.

**Comment by I-Got-You-Dead** [comment]
nut

**Comment by InstallHappiness** [comment]
Maven repos are down as well.

**Comment by Dnotcashier** [comment]
damm, did you alert staff in the discord server?

**Comment by Lovecrafts-Cat** [comment]
We know, this has been already reported multiple times. The issue is on the VPS host side, so we can't do anything about it and must wait.

In the meantime, if you really need Meteor, you can build it from source like [this](https://gist.github.com/GhostTypes/93eb5f62366cfd381df6d9496655fb0f).

**Comment by seasnail8169** [comment]
> In the meantime, if you really need Meteor, you can build it from source like [this](https://gist.github.com/GhostTypes/93eb5f62366cfd381df6d9496655fb0f).

no you cant

**Comment by seasnail8169** [comment]
this is a SEVERE issue 💀

**Comment by I-Got-You-Dead** [comment]
> this is a SEVERE issue 💀

BRO WDYMMMMMM IT ISSSS HE NEEDS HIS MOTOR CLINET

**Comment by Dnotcashier** [comment]
yeah i need my meteor client.
