### ISSUE TITLE
Crashing upon Launch of Minecraft 

### ISSUE THREAD

**Issue by daedx** [MeteorDevelopment/meteor-client#2901]
### Describe the bug

Upon launching Minecraft, my Minecraft freezes and then closes.
I'm using a modpack called BetterMC v9.

I was able to pinpoint that it was probably the meteor client considering that it only crashes whenever it's in the mods folder.

Keep in mind, it just closes. Took me a minute to figure out it was a crash in the first place via latest.log

### Steps to reproduce

```bash
1. Have the BetterMC Modpack on V9.
2. Drag and drop Meteorclient 1.19.2 into the mods folder.
3. Launch.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/awfveh2

### Meteor Version

Dev Build 0.5.1 - 1661

### Minecraft Version

1.19.2 

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by StormyBytes** [comment]
can you pin point what mod from the mod pack is conflicting with meteor

**Comment by daedx** [comment]
> can you pin point what mod from the mod pack is conflicting with meteor

**Comment by I-Got-You-Dead** [comment]
I would assume it’s conflicting with another mod that is conflicting with meteor
