### ISSUE TITLE
Make speed work while sneaking 

### ISSUE THREAD

**Issue by phvkuhkk** [MeteorDevelopment/meteor-client#2902]
### Describe the feature

It would be cool to have Speed working while sneaking maybe using No Slow

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
🤡

**Comment by StormyBytes** [comment]
It already does though?
