### ISSUE TITLE
Quilt Compat Shenanigans????

### ISSUE THREAD

**Issue by jLn0n** [MeteorDevelopment/meteor-client#2905]
### Describe the bug

i game failed to start when i launch mincefract when meteor client is installed

### Steps to reproduce

```bash
1. use quilt loader
2. put meteor-client(the latest dev build) & qsl(loads fabric-api for quilt)
3. kaboom!!!!! NOW IT DOESN'T LAUNCH
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/zqnTrFp

### Meteor Version

0.5.1-1667

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Are u retarded?

**Comment by I-Got-You-Dead** [comment]
Meteor isn’t made for quilt, it’s made for fabric

**Comment by jLn0n** [comment]
> Meteor isn’t made for quilt, it’s made for fabric

yeah i understand but i would really like to have compat on quilt loader

**Comment by I-Got-You-Dead** [comment]
Cope harder or port it yourself

**Comment by jLn0n** [comment]
> Cope harder or port it yourself

why dont u shut the fuck up and get some bitches

**Comment by I-Got-You-Dead** [comment]
No need

**Comment by StormyBytes** [comment]
When you don't know how to properly search github issues for duplicates
#2770

**Comment by I-Got-You-Dead** [comment]
🥱

**Comment by Wide-Cat** [comment]
meteor relies on some features of the fabric launcher, so its not compatible with quilt
