### ISSUE TITLE
fake player missing  "spawn" and "clear"

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#2909]
### Describe the bug

when I right click fakeplayer it does not shows the "spawn" and "clear" button, I have all of the pages open.

### Steps to reproduce

```bash
when opening fakeplayer settings
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by qeqeqeplayer533** [comment]
edit: there is no crashes

**Comment by Wide-Cat** [comment]
you need to have the module enabled for the buttons to show up
