### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Chessz0** [MeteorDevelopment/meteor-client#2911]
### Describe the feature

Pls add a command that will teleport you to a place, with a limit of 10 blocks
so if i do .tp ~ ~2 ~ in the mc chat i will be telported 2 blocks up

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
🤡

**Comment by Lovecrafts-Cat** [comment]
Meteor is not magic, you can't just do whatever you want.
For small range tp, there is already .hclip and .vclip.
