### ISSUE TITLE
[Suggestion] Chunk Trails

### ISSUE THREAD

**Issue by FoxStamp** [MeteorDevelopment/meteor-client#2914]
### Describe the feature

Some form of rendering chunk trails!

A feature added to the "render" module that will outline (or some other visual indication) of which chunks have already been loaded by another player or not.

Could be helpful for following where previous players have gone.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RickyTheRacc** [comment]
Tell me you haven't looked at closed issues without telling me you haven't looked at closed issues

**Comment by StormyBytes** [comment]
new chunks patched on 1.13 and above. not gonna be added to meteor. there were also tons of previous github issues asking for the same thing, how did you miss them bruh.
