### ISSUE TITLE
Nuker enhancements.

### ISSUE THREAD

**Issue by aRandomMenno** [MeteorDevelopment/meteor-client#2921]
### Describe the feature

Module; Nuker
Feature; Make it so you look at the block your breaking both client and server side.
Feature 2; make it so when it begins to break a block it does not stop when it found a closer block (this is an example for when sorting is on closest first.)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Retard

**Comment by JustABiscuit** [comment]
> Retard

No you.

**Comment by I-Got-You-Dead** [comment]
Retard

**Comment by JustABiscuit** [comment]
Please do not repeat or harass people here.

**Comment by I-Got-You-Dead** [comment]
Retard

**Comment by JustABiscuit** [comment]
Stop harassing meplease.

**Comment by I-Got-You-Dead** [comment]
🥱
