### ISSUE TITLE
Ingoing and outgoing packet logger. 

### ISSUE THREAD

**Issue by aRandomMenno** [MeteorDevelopment/meteor-client#2922]
### Describe the feature

Module; packet logger
Feature; Add a module that logs incoming/outgoing packets. You also add an element in the HUD maybe. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
> add to Starscript compatibility for ingoing and outgoing packets or add a module for that.
how would that even work?

**Comment by JustABiscuit** [comment]
Then make a module for it?

**Comment by I-Got-You-Dead** [comment]
Retard

**Comment by RacoonDog** [comment]
??? HOW DO YOU STARSCRIPT A PACKET

**Comment by JustABiscuit** [comment]
THEN MAKE A FUCKING MODULE BASTARD.

**Comment by JustABiscuit** [comment]
> > THEN MAKE A FUCKING MODULE BASTARD.
> 
> already exists
> 
> TELL ME HOW YOU THINK STARSCRIPT WOULD FUNCTION WITH PACKETS THOUGH

Which module in meteorclient then? to see how many packtes are incoming and outgoing?

**Comment by JustABiscuit** [comment]
> > THEN MAKE A FUCKING MODULE BASTARD.
> 
> already exists
> 
> TELL ME HOW YOU THINK STARSCRIPT WOULD FUNCTION WITH PACKETS THOUGH

Bro, you stupid.
Then make a module with java or js smth.

**Comment by RacoonDog** [comment]
- starscript is a text formatting language
- packets are complex structures containing a ton of info and there are hundreds incoming and outgoing per second

how the FUCK would you fuse the two

**Comment by JustABiscuit** [comment]
> * starscript is a text formatting language
> 
>     * packets are complex structures containing a ton of info and there are hundreds incoming and outgoing per second
> 
> 
> how the FUCK would you fuse the two

Idk you are the programmer here, and otherwise you could also make it so the ingoing and outgoing packets have their own .txt file.

**Comment by JustABiscuit** [comment]
> * starscript is a text formatting language
> 
>     * packets are complex structures containing a ton of info and there are hundreds incoming and outgoing per second
> 
> 
> how the FUCK woul

> * starscript is a text formatting language
> 
>     * packets are complex structures containing a ton of info and there are hundreds incoming and outgoing per second
> 
> 
> how the FUCK would you fuse the two

are you still talking about starscript? if so. YOU ARE A FKING RETARD. I already said to not use it 14 minutes ago. you stoopid.

then make a hud element which you can toggle that show how many packets are incoming and outgoing.

**Comment by RacoonDog** [comment]
:trollswagcat:

**Comment by TaxEvasiqn** [comment]
> > > THEN MAKE A FUCKING MODULE BASTARD.
> > 
> > 
> > already exists
> > TELL ME HOW YOU THINK STARSCRIPT WOULD FUNCTION WITH PACKETS THOUGH
> 
> Bro, you stupid. Then make a module with java or js smth.

this is a cool idea i might make a javascript module for this!

**Comment by I-Got-You-Dead** [comment]
Js 💀

**Comment by RacoonDog** [comment]
update: i have starscripted the packet
