### ISSUE TITLE
Meteorclient crash. (meteorplus and meteorclient.)

### ISSUE THREAD

**Issue by JustABiscuit** [MeteorDevelopment/meteor-client#2924]
### Describe the bug

When I start the client it crashes.
It also mentions Meteor plus addon.
Idk which one of them causes it.

[crash-2022-11-02_16.03.52-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/9921668/crash-2022-11-02_16.03.52-client.txt)

### Steps to reproduce

```bash
1. Put the mods listed in the crash report in the mods folder.
2. start the client.
3. CRASH.
```

### Meteor Version

0.5.1-1674

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
open an issue in the meteor plus repo

**Comment by JustABiscuit** [comment]
already did but no response yet.
