### ISSUE TITLE
[Bug] Fishing rod entity and items affected by jesus in singleplayer

### ISSUE THREAD

**Issue by JerimiahOfficial** [MeteorDevelopment/meteor-client#2926]
### Describe the bug

When you enable Jesus to be able to walk on water and then go fishing, the bobber never touches the water. Even if you're on land with Jesus enabled, it stops the bobber from interacting with the water. This also affects items, making them float on top of the water never actually touching or being submerged in the water, I'm not sure if this is intended.

Items floating:
![image](https://user-images.githubusercontent.com/38990407/199813137-388af5d2-82c4-43b1-a58b-c1cab8a72f2a.png)

Bobber floating:
![image](https://user-images.githubusercontent.com/38990407/199813271-35e9bdb7-2f95-42ef-b434-d59eb813e08f.png)

### Steps to reproduce

```bash
Enable Jesus
Stand on land or water
Cast the fishing rod into the water
or
Drop items onto the water
```

### Meteor Version

0.5.1 - 1674

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
That’s a you problem

**Comment by JerimiahOfficial** [comment]
> That’s a you problem

🤡🤡🤡

**Comment by I-Got-You-Dead** [comment]
the only clown here is you since you are complaining about a module that changes how the CLIENT interacts with water, which was designed for multiplayer yet you are using it in single player 😃

**Comment by JerimiahOfficial** [comment]
> the only clown here is you since you are complaining about a module that changes how the CLIENT interacts with water, which was designed for multiplayer yet you are using it in single player 😃

🤡🤡🤡

**Comment by I-Got-You-Dead** [comment]
🥱

**Comment by JerimiahOfficial** [comment]
> 🥱

🤡🤡🤡

**Comment by I-Got-You-Dead** [comment]
Keep crying kid
