### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jawor1337** [MeteorDevelopment/meteor-client#2927]
### Describe the bug

speedmine is bugged

### Steps to reproduce

```bash
i played in no anti cheat and blocks mine is bugged and not working on 
multiplayer 1600+
```

### Meteor Version

latest

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
💀
