### ISSUE TITLE
GUI scale 900 instead of 0.900

### ISSUE THREAD

**Issue by noireeth** [MeteorDevelopment/meteor-client#2928]
### Describe the bug

Is there a way of changing the GUI scale without doing 'right-shift then clicking GUI' like a command in chat. This is because I can't reach this button. Could there be a maximum GUI scale so this could be prevented for next time

### Steps to reproduce

```bash
I was playing around with the aesthetics of the GUI when I wanted to put the GUI scale to 0.900 but I accidentally put set it to 0900, which made it to 900!! I can't scroll or move things around now.
```

### Meteor Version

1.19.2

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
.reset gui

**Comment by noireeth** [comment]
Using NBT editor I managed to fix it

**Comment by beabail** [comment]
someone literally posted the answer lol
