### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Scr1pts6** [MeteorDevelopment/meteor-client#2929]
### Describe the feature

you should add a .dupe command for meteor client it will be very useful

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
do you have a duping method or do you expect someone to just pull a gamebreaking bug out of their ass

**Comment by RacoonDog** [comment]
help i have a gamebreaking bug stuck in my ass

**Comment by I-Got-You-Dead** [comment]
Man just watched a horizon vid 💀
