### ISSUE TITLE
new command

### ISSUE THREAD

**Issue by Bardelby1** [MeteorDevelopment/meteor-client#2933]
### Describe the feature

the command is called troll, it allows you to say a message, and it will show as another player, like the name history command player part, and then the message, i got it from a friend on discord, it was a command from a favorite server of mine.
and i have been trolled before with it in use, it was confusing, and the troll was trolling another player, an admin was the one using it on me, and trolling a toxic person, very confusing but funny.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
You mean like, sending a message, but it shows that its from another player? As far as im aware, thats not possible to do. Can you send an example of another mod with this feature?

**Comment by Wide-Cat** [comment]
open this again once youve completed my request

**Comment by MineGame159** [comment]
They said it was an admin who did it so that explains it.

**Comment by Bardelby1** [comment]
its possible

**Comment by Bardelby1** [comment]
ill show the code used in it, its simple

**Comment by Bardelby1** [comment]
command /troll [<player>] [<text>]:
	permission: op
	permission message: &cYou cannot execute this command!
	trigger:
		make arg-1 say arg-2

**Comment by I-Got-You-Dead** [comment]
Use /execute
