### ISSUE TITLE
[Feature Request] Future Quilt Support

### ISSUE THREAD

**Issue by OCsonic** [MeteorDevelopment/meteor-client#2936]
### Describe the feature

I know Quilt-toolchain compatibility has been asked for before, but this suggestion is more about future compatibility with other mods than it is with a specific mod loader.

With a lot of mods already slowly migrating from Fabric to the Quilt Toolchain it seems like it would be beneficial for Meteor to maintain Quilt support (or at-least avoid changes that make it too difficult to support Quilt in the future) so that if the trend of Quilt migration continues then Meteor won't be left incompatible with a lot of utility mods. (Not to mention that Quilt could be beneficial for compatibility between Meteor addons if everything works out with Chasm)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Damn I closed it before I could bully them 😠
