### ISSUE TITLE
[Suggestion] Add downloads page with previous versions

### ISSUE THREAD

**Issue by Davsennn** [MeteorDevelopment/meteor-client#2937]
### Describe the feature

I would love it if I could download versions of meteor for previous minecraft versions. I often had the issue that I wanted to join a 1.18.2 server and for that I would need meteor for 1.18.2. It would also be cool if there was meteor for 1.8.9 and 1.12.2. You could add this onto the website and/or the discord server.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
I would love it if you could actually read the fucking faq. I often had the issue of people not readying the fucking faq and for that i would need to tell retards to read the fucking faq. It would also be cool if you could maybe read the fucking faq and not suggest the same fucking issue as everyone else. You can read the fucking faq on the website and the discord server. 

Kind Regaurds, 
-I_Got_You_Dead

**Comment by Lovecrafts-Cat** [comment]
As the person above said, read the FAQ to know how to join servers on older versions.

Also, you obviously didn't check for duplicate issues before opening this one.

**Comment by ManInMyVan** [comment]
[https://maven.meteordev.org](https://maven.meteordev.org)
