### ISSUE TITLE
Distance colors ESP 

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#2938]
### Describe the feature

Meteor client developers, I have a suggestion that could add an overall a better user experience with the client and its customizability. I thought it would be great to add Distance colors to ESP because this can add a more appealing look to the tracer + ESP combination due to only being able to enable Distance colors for tracers which would result in an inconsistent color scheme, which some users might find unappealing, including me. I have been using meteor client for almost a year and a half now and donated, and after using it, this is the only thing I've wanted added to the client. Thank you for taking to the time to read this and have a good day.  (I've seen other utility clients with distance colors for esp as well.)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
I might look into it later

**Comment by I-Got-You-Dead** [comment]
Also might make a way to change the distance colors

**Comment by SnakyExotic** [comment]
> Also might make a way to change the distance colors

u think u can make this into an addon?

**Comment by I-Got-You-Dead** [comment]
Bruh

**Comment by I-Got-You-Dead** [comment]
Paste it

**Comment by I-Got-You-Dead** [comment]
I gotta fix some stuff tho

**Comment by SnakyExotic** [comment]
> I gotta fix some stuff tho

Do u have a discord because talking on github is getting repetitive

**Comment by I-Got-You-Dead** [comment]
Mhm

**Comment by SnakyExotic** [comment]
> Mhm

What's your discord?
