### ISSUE TITLE
Heart Limiter in norender

### ISSUE THREAD

**Issue by TaxEvasiqn** [MeteorDevelopment/meteor-client#2947]
### Describe the feature

Make it so there's a limit to the amount of hearts shown if you have attributes

<img width="170" alt="Screenshot 2022-11-12 at 11 29 06" src="https://user-images.githubusercontent.com/97795311/201471893-9d3ff369-6bce-4a41-9a05-4c221e39176a.png">
(i am getting 20fps in the image above)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Omfg fr

**Comment by I-Got-You-Dead** [comment]
Based

**Comment by C10udburst** [comment]
just use https://modrinth.com/mod/armorpoints
