### ISSUE TITLE
[Suggestion] Make a ticks per block section in Highwaybuilder

### ISSUE THREAD

**Issue by Kolotheegg** [MeteorDevelopment/meteor-client#2948]
### Describe the feature

I play on a strict Anarchy server and I would love to use Highway builder but the blocks always disappear if I use it. so if you add a ticks per block it wouldn't flag anymore. Thanks for the amazing client your providing.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
don't use meteor on servers you shouldn't

**Comment by TaxEvasiqn** [comment]
i mean just because it has a strict anticheat doesnt mean it's not anarchy

**Comment by GreemDev** [comment]
implementing bypasses around said anticheat would in turn also allow people to use meteor on servers they shouldn't. 
Not to mention, other issues have been closed for the exact same reason, such as #2870.

**Comment by Kolotheegg** [comment]
I play on an Anarchy server that uses Grim and you still would get flaged if you implementet a Ticks per Block section, but it wouldnt skip a block! which lets you fall down.

**Comment by I-Got-You-Dead** [comment]
> I play on an Anarchy server that uses Grim and you still would get flaged if you implemented a Ticks per Block section, but it wouldn't skip a block! which lets you fall down.

Who tf cares

**Comment by I-Got-You-Dead** [comment]
Multiplace > one block per tick
