### ISSUE TITLE
[Suggestion] Swarm teleportation requests

### ISSUE THREAD

**Issue by ultrablazed** [MeteorDevelopment/meteor-client#2951]
### Describe the feature

A command that lets you teleport/recall swarm workers using /tpa or /tpr. Example: .swarm recall (worker name) sends a /tpr request from the worker to the host and is automatically accepted. Vice versa for .swarm tp (worker name).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
This ^

**Comment by seasnale** [comment]
tpa isn't vanilla functionality so nah
