### ISSUE TITLE
[Suggestion] Additions to Starscript

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#2952]
### Describe the feature

Add starscript to not just hud elements but to modules so you can change the format for things like Nametags. Also whenever you add a color for text colors in starscript you should be able to enable an option called "Distance Colors" for things like player radar in hud, or distance in nametags. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
You have aids

**Comment by I-Got-You-Dead** [comment]
Do you even know what starscript is?

**Comment by RacoonDog** [comment]
i dont see how starscript would be useful on nametags tbh

and starscript is mutually exclusive with distance colors due to both of them having their own way to handle colors

**Comment by SnakyExotic** [comment]
> Do you even know what starscript is?

Idk I just knew that starscript could be used to change formats for things in hud

**Comment by I-Got-You-Dead** [comment]
That’s not starscript, that’s just simple text formatting

**Comment by SnakyExotic** [comment]
> That’s not starscript, that’s just simple text formatting

Should I rename the title to formatting?

**Comment by I-Got-You-Dead** [comment]
But why would you even need distance colors in the hud tho

**Comment by SnakyExotic** [comment]
> But why would you even need distance colors in the hud tho

for player radars colors since you can make the colors change based on the distance of the player

**Comment by I-Got-You-Dead** [comment]
no

**Comment by I-Got-You-Dead** [comment]
I bet snail will say the same

**Comment by SnakyExotic** [comment]
> I bet snail will say the same

wouldn't be surprised
