### ISSUE TITLE
Add distance colors to nametags 

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#2953]
### Describe the feature

- Add a color option to nametags to change the text for distance based on distance colors 
![image](https://user-images.githubusercontent.com/72416130/201501252-16b3f478-32b8-4bfc-beb8-624d5d2e4fc8.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Bro

**Comment by I-Got-You-Dead** [comment]
Close this

**Comment by SnakyExotic** [comment]
> Close this

why?

**Comment by I-Got-You-Dead** [comment]
Because you already suggested it

**Comment by I-Got-You-Dead** [comment]
And u closed it, if u didn’t mean to just reopen the old one

**Comment by SnakyExotic** [comment]
> And u closed it, if u didn’t mean to just reopen the old one

I closed the old one on purpose because I wanted this one up instead.

**Comment by I-Got-You-Dead** [comment]
“edit”

**Comment by SnakyExotic** [comment]
> 

Too late now
