### ISSUE TITLE
Add "Obfuscation" as an option to No Render

### ISSUE THREAD

**Issue by CoolestGuy94** [MeteorDevelopment/meteor-client#2956]
### Describe the feature

Obfuscation (especially with chinese characters) can cause lag or crash Minecraft clients. This suggestion will disable obfuscation when specific option is selected in No Render.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
You mean the text decoration option?

**Comment by CoolestGuy94** [comment]
Yes.
