### ISSUE TITLE
[Suggestion] Auto Eat at certain health

### ISSUE THREAD

**Issue by Stuntlover-TM** [MeteorDevelopment/meteor-client#2958]
### Describe the feature

For Auto Eat, add an option to eat whenever you're at X health (or less)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Stuntlover-TM** [comment]
also yes, I know that Auto Gap already exists but you don't always want to use (or have) gapples

**Comment by beabail** [comment]
but normal food doesn't heal you

**Comment by Stuntlover-TM** [comment]
> but normal food doesn't heal you
if you have full food points it does..?

**Comment by I-Got-You-Dead** [comment]
Yea?

**Comment by Stuntlover-TM** [comment]
thanks :3
