### ISSUE TITLE
[Suggestion] elytra speed toggle hotkey

### ISSUE THREAD

**Issue by BoomerNation99** [MeteorDevelopment/meteor-client#2959]
### Describe the feature

Traveling and building in minecraft requires two different speeds.  I love your client. Makes the game much more enjoyable. 
A toggle switch to change between elytra flying speeds would be great. 
I build at .5 speed. But travel at 2.5 (our server at IGN has speed limit)
It would be awesome to use a hotkey to switch between those speeds. 
I searched for this suggestion and haven’t seen it. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
You can change the speed through chat with `.s elytra-fly horizontal-speed 2.5` which means you can make a macro for it.
