### ISSUE TITLE
AutoTool avoid sword option

### ISSUE THREAD

**Issue by moritz-t-w** [MeteorDevelopment/meteor-client#2963]
### Describe the feature

I don't use AutoTool because it uses up my sword, would be nice if there was an option to exclude any given tool(s).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
“Am I a joke to you?” - Mending

**Comment by moritz-t-w** [comment]
🤯

**Comment by MineGame159** [comment]
Added in cd739b56188b61f08cf2e3398b2457e4664b7b52.
