### ISSUE TITLE
[Suggestion] Easyer Baritone module

### ISSUE THREAD

**Issue by lc4ro** [MeteorDevelopment/meteor-client#2966]
### Describe the feature

add a baritone in the module tab, like a auto mine, auto walk, instead of chat commands.
something like impact   

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Skill issue, learn how to use baritone the real way
