### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by easyloo** [MeteorDevelopment/meteor-client#2968]
### Describe the bug

meteor crashes when starting the game

### Steps to reproduce

```bash
start minecraft
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/eOQSkys

### Meteor Version

Dev Build: 1682

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by easyloo** [comment]
i'll just use meteor version 1680 then

**Comment by ehylo** [comment]
@RacoonDog  before he edited it, there was no log sorry
![image](https://user-images.githubusercontent.com/48396713/202014194-131b5534-9be1-4c6b-ae6a-e05fe2f8d385.png)

**Comment by ehylo** [comment]
I hate github I did not click reopen ffs

**Comment by RacoonDog** [comment]
> @RacoonDog before he edited it, there was no log sorry
> ![image](https://user-images.githubusercontent.com/48396713/202014194-131b5534-9be1-4c6b-ae6a-e05fe2f8d385.png)

Ah I didn’t know that
