### ISSUE TITLE
AntiBookBan

### ISSUE THREAD

**Issue by ultrablazed** [MeteorDevelopment/meteor-client#2970]
### Describe the feature

I know about antipacketkick BUT on some servers it doesn't work for bookbans. Even with antipacketkick I get a kick for the PacketPlayOutSetSlot packet being too large. It would be nice if there was antibookban or an updated antipacketkit to prevent this. Here's a screenshot of the kick for more info [https://prnt.sc/jN-nTG57yIZX](url)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
🤡

**Comment by I-Got-You-Dead** [comment]
Learn how packets work

**Comment by MrBreakNFix** [comment]
man does not understand that would need to be a plugin

**Comment by TaxEvasiqn** [comment]
just include books in auto drop and then turn auto reconnect on while you wait for the book to despawn 🙄

**Comment by TaxEvasiqn** [comment]
among us ඞඞඞ

**Comment by I-Got-You-Dead** [comment]
> > just include books in auto drop and then turn auto reconnect on while you wait for the book to despawn 🙄
> 
> Are you retarded. By the time your client has the chance to throw the books you'll already have been BBanned.

It’s called a joke

**Comment by Wide-Cat** [comment]
I'm pretty sure this is a server issue, and is not something that can be prevented on the client. If I am wrong about this, please feel free to correct me
