### ISSUE TITLE
crashing while trying to use xray or freecam with sodium

### ISSUE THREAD

**Issue by GZMOSV** [MeteorDevelopment/meteor-client#2972]
### Describe the bug

I am constantly crashing while trying to use xray or freecam with sodium

fabric-loader-0.14.10-1.19.2
Mods:
sodium-fabric-mc1.19.2-0.4.4+build.18
meteor-client-0.5.1-1682
fabric-api-0.66.0+1.19.2

### Steps to reproduce

```bash
Use meteor, fabric API and sodium
go into a server
toggle x-ray or freecam a couple times and then you crash
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/LijAXTm

### Meteor Version

meteor client v0.5.1 build # 1682

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by PanmanS** [comment]
same issue

**Comment by GZMOSV** [comment]
I Fixed it. Currently sodium has a problem with the latest Nvidia drivers. I was using the latest, but if you downgrade to like 517 it works perfectly
