### ISSUE TITLE
Friends color 

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#2974]
### Describe the bug

If you enable distance colors for esp and tracers and add someone as a friend their tracer/esp color won't change to the friend's color. 

### Steps to reproduce

```bash
Enable Distance colors
```

### Meteor Version

meteor-client-0.5.1-1682

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
That’s the point of distance so cope

**Comment by SnakyExotic** [comment]
> That’s the point of distance so cope

no its not lol

**Comment by I-Got-You-Dead** [comment]
Wanna bet?

**Comment by I-Got-You-Dead** [comment]
Your talking to the person who added distance colors to esp

**Comment by SnakyExotic** [comment]
> Wanna bet?

literally every other client does not do that

**Comment by I-Got-You-Dead** [comment]
I don’t give a shit about every other client

**Comment by SnakyExotic** [comment]
> Your talking to the person who added distance colors to esp

The point of friends color is so you can DIFFERENTIATE between your friends and enemies dumbass

**Comment by I-Got-You-Dead** [comment]
Don’t use distance colors then

**Comment by SnakyExotic** [comment]
> Don’t use distance colors then

Just cuz u coded it doesn't mean u did it right

**Comment by I-Got-You-Dead** [comment]
I don’t really care about your opinion

**Comment by I-Got-You-Dead** [comment]
Cry

**Comment by SnakyExotic** [comment]
> Cry

and learn how clients work

**Comment by RedCarlos26** [comment]
This got added in dev builds @MineGame159

**Comment by I-Got-You-Dead** [comment]
Annoyingly
