### ISSUE TITLE
Really interesting bug that might be able to be abused

### ISSUE THREAD

**Issue by dlfnn** [MeteorDevelopment/meteor-client#2977]
### Describe the feature

https://bugs.mojang.com/browse/MC-74984

makes players able to teleport anywhere, and give themselves any items

not exactly sure how was it done. here is a video that i saw explaning how to abuse this bug
https://youtu.be/EEG_c3ycDg4 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
Is there an actual guide instead of a video filled with stuff i dont care about until it was long enough to be profitable via ads

**Comment by dlfnn** [comment]
> Is there an actual guide instead of a video filled with stuff i dont care about until it was long enough to be profitable via ads

At least I don't know. There are some info in the bugs.mojang page though

**Comment by Wide-Cat** [comment]
I think I saw this implemented in another client, if I remember correctly it was almost a one-line module, like mc.disconnect(new MultiplayerScreen())

**Comment by MrBreakNFix** [comment]
this bug is stupid all it does is connect your client to 2 servers

**Comment by MrBreakNFix** [comment]
all you need to do is set the screen to a title screen or something and you are still connected to the server, but you can still join another

**Comment by GoldenStack** [comment]
As MrBreak said, this is a stupid bug.
You can't spawn items - it only works like it does in the video when in creative mode, because the client just creates ghost items, but the creative player has the ability to actually add them.
Also, you can't just teleport anywhere.

From the server's perspective, you're just sending it random junk in the form of packets. You can't just spawn in items and stuff like that.

Yes, you can use it to xray, but you can also just turn on xray.

A comment on the video sums it up nicely:
> This video absolutely blows the glitch out of proportion. It simply is just your client being confused and connected to two servers. Yes- you can use it as a cave finder I guess but there are easier ways to do that by glitching into blocks. You cannot transfer items over at all unless you already had creative on a server.

**Comment by seasnale** [comment]
@[seasnale](https://github.com/seasnale) seasnale closed this as [not planned](https://github.com/MeteorDevelopment/meteor-client/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) Won't fix, can't repro, duplicate, stale[now](https://github.com/MeteorDevelopment/meteor-client/issues/2977#event-7848397482)
