### ISSUE TITLE
antichunckban (new module)

### ISSUE THREAD

**Issue by JustABiscuit** [MeteorDevelopment/meteor-client#2978]
### Describe the feature

add antichunckban from bleachhack to meteorclient.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by lapoliciarobomiquesofrances** [comment]
chunck

**Comment by lapoliciarobomiquesofrances** [comment]
bleach hack and meteor work together anyway so just use both

**Comment by Wide-Cat** [comment]
Anti packet kick

**Comment by JustABiscuit** [comment]
No,
Anti Packet kick does not prevent me from being kicked in a way which antichunk ban does.

**Comment by I-Got-You-Dead** [comment]
There is no such (known)  thing as a fully working client side antichunkban
