### ISSUE TITLE
Zombified Piglins/Pigmen are not getting attacked by killaura

### ISSUE THREAD

**Issue by raffel080108** [MeteorDevelopment/meteor-client#2980]
### Describe the bug

I enabled killaura and included zombified piglins in the selected entities, but killaura does not target them at all

### Steps to reproduce

```bash
1. Enable Killaura
2. Select Zombified Piglin in Entities
```

### Meteor Version

meteor-client-0.5.1-1661

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by I-Got-You-Dead** [comment]
Give this man a round of applause

**Comment by raffel080108** [comment]
What?

**Comment by I-Got-You-Dead** [comment]
“Attack passive”

**Comment by raffel080108** [comment]
Nice, thanks
