### ISSUE TITLE
[Enhancement] Add a NoBorder module

### ISSUE THREAD

**Issue by LmaxplayG** [MeteorDevelopment/meteor-client#2983]
### Describe the feature

NoBorder would be a feature that simply makes the border not appear and have no collision client-side (it not appearing would be an option)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Addons

**Comment by 0xPlatinum** [comment]
imagine trying to skid for the LiveOverflow server lol

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by LmaxplayG** [comment]
._.

**Comment by GreemDev** [comment]
Not hateful if it's factual and accurate

**Comment by Wide-Cat** [comment]
💀💀💀

**Comment by LmaxplayG** [comment]
First on, this hasn't been suggested

Secondly, you are harassing someone for suggestions a feature.

Kinda defeats the point of having a premade template to suggest things

**Comment by LmaxplayG** [comment]
💀

**Comment by LmaxplayG** [comment]
I won't comment further, seeing as you are clearly not mentally developed enough to have a discussion with.

**Comment by GreemDev** [comment]
They are pointing out why your suggestion won't be added, and where you can even find the very same feature you're requesting.
This is not harassment. I find irony in saying *they* are the ones who aren't mentally developed enough.

**Comment by LmaxplayG** [comment]
> They are pointing out why your suggestion won't be added, and where you can even find the very same feature you're requesting. This is not harassment. I find irony in saying _they_ are the ones who aren't mentally developed enough.

Thing is: you don't have to follow up with emojis and harassment when an issue is dumb, just tell them "hey, this is in X addon, you could use that".
Instead of going the childish way and harassing the person who made the issue.

**Comment by Wide-Cat** [comment]
What exactly did they say that counts as harassment?

**Comment by LmaxplayG** [comment]
> What exactly did they say that counts as harassment?

Well this:

> imagine trying to skid for the LiveOverflow server lol

> 💀

**Comment by GreemDev** [comment]
You really seem to like the word harassment despite not really knowing what it entails.

**Comment by CopeTypes** [comment]
Cope and seethe

**Comment by I-Got-You-Dead** [comment]
> First on, this hasn't been suggested
> 
> Secondly, you are harassing someone for suggesting a feature.
> 
> Kinda defeats the point of having a premade template to suggest things

Wanna see harassment? I’ll show u harassment bud

**Comment by Mathrandom7910** [comment]
funniest issue ever
