### ISSUE TITLE
Game crashes upon joining server from other server

### ISSUE THREAD

**Issue by AfkUserMC** [MeteorDevelopment/meteor-client#2987]
### Describe the bug

Sometimes when I join a server (e.g. I used minehut) and join a server from that main server, a crash occurs.

(NEC Installed)

### Steps to reproduce

```bash
Join server
Join server from that server (e.g. A different lobby on hypixel, A server on Minehut)
Crash.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://bytebin.lucko.me/YuyQY0JBvc / https://mclo.gs/UQZ1NBj

### Meteor Version

0.5.1 DEV-1686

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
What other mods are you using?

**Comment by AfkUserMC** [comment]
> What other mods are you using?

Meteor Client, NotEnoughCrashes
Fixed when i turned off and on my modules again.

**Comment by seasnale** [comment]
a crash log with not enough crashes is literally worthless, if you don't have a log without it then we can't do anything
