### ISSUE TITLE
[Suggestion] Switch out baritone for altoclef.

### ISSUE THREAD

**Issue by dolphin-cat** [MeteorDevelopment/meteor-client#2990]
### Describe the feature

https://discord.com/invite/fUUEHeNmXb

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)
- [x] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
Lmfao

**Comment by RacoonDog** [comment]
Altoclef uses baritone

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by TaxEvasiqn** [comment]
bruh

**Comment by dolphin-cat** [comment]
i have tested them and they work fine together

**Comment by dolphin-cat** [comment]
automation is very important and altoclef or it's under-development fork known as anarchyclef would be a very good feature to add to the client! and yes alto(yea we call it alto) does use baritone so baritone won't need to be removed and you'd get both manual(ofc duh), baritone and altoclef.

**Comment by I-Got-You-Dead** [comment]
Just download it separately
