### ISSUE TITLE
Allow KeyBinds to be saved in profiles [Resolved]

### ISSUE THREAD

**Issue by LTBlueLatios** [MeteorDevelopment/meteor-client#2994]
### Describe the feature

Different profiles may have different keybinds attached to modules, and it would be frustrating to reset the keybinds every time you switched profiles.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
It already does 🤡

**Comment by I-Got-You-Dead** [comment]
close it if its fixed?
