### ISSUE TITLE
gradle wont work it gives me a error 56s

### ISSUE THREAD

**Issue by frayray909090** [MeteorDevelopment/meteor-client#2997]
### Describe the bug

please help me it will not work

### Steps to reproduce

```bash
i just run gradle.bat and the same in vs code it gives and error
```

### Link to crash report/log if applicable (https://mclo.gs)

yes

### Meteor Version

newest

### Minecraft Version

19.0

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by lapoliciarobomiquesofrances** [comment]
give error

also make sure you have java and gradle in vs code, if you dont know how to do this just use intellej like a normal person bruh

**Comment by RacoonDog** [comment]
bro you need to run gradle.bat *with arguments*

**Comment by I-Got-You-Dead** [comment]
./gradlew build gang

**Comment by TaxEvasiqn** [comment]
bruh

**Comment by frayray909090** [comment]
> give error
> 
> also make sure you have java and gradle in vs code, if you dont know how to do this just use intellej like a normal person bruh

i did
and when i run the gradle it gives me a error

**Comment by frayray909090** [comment]
> give error
> 
> also make sure you have java and gradle in vs code, if you dont know how to do this just use intellej like a normal person bruh

bruh intellej is so much better then eclipse and vs code
