### ISSUE TITLE
Can't use # (discord tags) in .say

### ISSUE THREAD

**Issue by FurnyGo** [MeteorDevelopment/meteor-client#3002]
### Describe the bug

![image](https://user-images.githubusercontent.com/68079109/204371984-21a9e6d9-d53e-4ccc-abe7-f6ae1443e8ce.png)

### Steps to reproduce

```bash
just type in chat .say discord#0001
```

### Meteor Version

Latest from github actions

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
try wrapping it with curly brackets, like so - .say {discord#0001}

**Comment by FurnyGo** [comment]
> try wrapping it with curly brackets, like so - .say {discord#0001}

![image](https://user-images.githubusercontent.com/68079109/204375235-90592164-fe32-4bf5-9102-909d1d1c7687.png)

**Comment by RacoonDog** [comment]
maybe `.say {"discord#0001"}`

**Comment by FurnyGo** [comment]
> .say {"discord#0001"}

yes it works, thanks
