### ISSUE TITLE
flying is slow

### ISSUE THREAD

**Issue by MaxizCool0713** [MeteorDevelopment/meteor-client#3010]
### Describe the bug

if i try to fly with meteor client WITHOUT the "flight" active aka "flying in creative" is painfully slow even with "flight" on and set to max its still very slow 

### Steps to reproduce

```bash
e
```

### Meteor Version

1.18.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Lovecrafts-Cat** [comment]
1.18.1 is unsupported.
Update to the newest Meteor version (1.19/1.19.2)

**Comment by Yeah-Jack** [comment]
When you have Speed active it's slow so please look when you fly that Speed is deactivated.

**Comment by I-Got-You-Dead** [comment]
> When you have Speed active it's slow so please look when you fly that Speed is deactivated.

Use banana+ strafe+
