### ISSUE TITLE
dupe

### ISSUE THREAD

**Issue by crille223** [MeteorDevelopment/meteor-client#3014]
### Describe the feature

a duping hack that can dupe things such as chests and/or shulkers

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ehylo** [comment]
github amazing user experience

**Comment by Mathrandom7910** [comment]
pov: you join github to tell meteor devs to make a dupe module
