### ISSUE TITLE
[Suggestion] Toggle Auto-Jump in Speed

### ISSUE THREAD

**Issue by PrimeTDMomega** [MeteorDevelopment/meteor-client#3017]
### Describe the feature

Can you add a togglable Auto-Jump in the Strafe mode of the Speed module. Right now it always jumps when you have speed module on strafe mode.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Defeats the purpose

**Comment by I-Got-You-Dead** [comment]
It needs the auto jump to work

**Comment by qeqeqeplayer533** [comment]
banana+ strafe+ smart mode
