### ISSUE TITLE
[Bug] .server command not working

### ISSUE THREAD

**Issue by dchinguun** [MeteorDevelopment/meteor-client#3021]
### Describe the bug

I think the .server plugin isnt working
like i get some errors

### Steps to reproduce

```bash
on chat do .server plugins
then it get some errors
like its gonna show plugins
```

### Meteor Version

0.5.1-1698

### Minecraft Version

1.19.2

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by BlueTree242** [comment]
hint: `.server plugins` has another argument

**Comment by IntNinja** [comment]
still doesn't work
