### ISSUE TITLE
[Bug] mouse starts mooving scenematicly smooth 

### ISSUE THREAD

**Issue by JanCantCode** [MeteorDevelopment/meteor-client#3025]
### Describe the bug

i used to often have the issue, that after toggling zoom, with the setting release on key release set to true, zoom would stay activated, and only turn off upon opening any GUI. that alone wasnt a big issue, but now, even when i turn zoom off using the previously described method, my mouse stays in the "scenematic" mode, meaning it starts moving smoothly around the screen. this is really annoying, as from my experience, the only way of stopping this is restarting your game. i am unsure what is actually causing this, but i would guess the zoom (fov) is reset to the standard value while scenematic mouse movement 

### Steps to reproduce

```bash
i havent been able to reproduce it on purpose, but it happens fairly often. usually, when i activate zoom, and in the exact moment that i release the zoom key, open the module menu. 

again, i am not constantly able to reproduce the bug but it happens fairly frequently.
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
if you can still reproduce this open the issue again
