### ISSUE TITLE
Baritone Doesn't Work

### ISSUE THREAD

**Issue by IPlayMinecraftYT** [MeteorDevelopment/meteor-client#3028]
### Describe the bug

When asking baritone to mine for ores (or anything) it will begin pathing to the edge of the world (presumably)

### Steps to reproduce

```bash
Download the latest dev build and try to do .mine diamond_ore or anything and it will go to the edge of nowhere
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
cant reproduce

**Comment by Lovecrafts-Cat** [comment]
> do .mine diamond_ore

Well yeah, because that's not the way you use Baritone.
The Baritone prefix is `#` not `.`

**Comment by Wide-Cat** [comment]
see lovecrafts-cat's comment

**Comment by IPlayMinecraftYT** [comment]
> > do .mine diamond_ore
> 
> Well yeah, because that's not the way you use Baritone. The Baritone prefix is `#` not `.`

misspell, meant .b mine diamond_ore (but #mine also doesn't work)

**Comment by I-Got-You-Dead** [comment]
Do #reset all then try again
