### ISSUE TITLE
[Suggestion] remove OPEN_commands and GUI

### ISSUE THREAD

**Issue by PepegaRuina** [MeteorDevelopment/meteor-client#3030]
### Describe the feature

Please add the ability to remove the OPEN_gui and OPEN_commands keys from the assignment. Or add the ability to turn off the cheat. That is, as if to completely delete the cheat for a while, and when everything was re-entered, something like panic returned

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
No.
