### ISSUE TITLE
you guys should make an anti cheat that blocks meteorr thats paid

### ISSUE THREAD

**Issue by cjmonty152** [MeteorDevelopment/meteor-client#3031]
### Describe the feature

you guys should make an anti cheat that blocks meteorr thats paid

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
No.

**Comment by Mathrandom7910** [comment]
this is a good idea wdym
