### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by NegroFighter69420** [MeteorDevelopment/meteor-client#3033]
### Describe the bug

latest build is incompatible with boosted brightness [crash-2022-12-08_16.44.49-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/10189693/crash-2022-12-08_16.44.49-client.txt) https://github.com/adamviola/BoostedBrightness

### Steps to reproduce

```bash
add the latest build of meteor and boosted brightness into mods
try to change the brightness
crash
```

### Meteor Version

latest build

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by NegroFighter69420** [comment]
i have tried launching the minecraft without meteor and it works just fine

**Comment by I-Got-You-Dead** [comment]
Just don’t use it then

**Comment by NegroFighter69420** [comment]
> Just don’t use boosted brightness then

yea but its a issue so im gonna report it

**Comment by Lovecrafts-Cat** [comment]
Why would you need that mod when Meteor already has Fullbright to see in the dark?

**Comment by ehylo** [comment]
Please provide a crash report with just meteor and this mod, and also, please use a paste service like https://mclo.gs/ or https://paste.ee/

**Comment by NegroFighter69420** [comment]
> Please provide a crash report with just meteor and this mod, and also, please use a paste service like https://mclo.gs/ or https://paste.ee/

https://mclo.gs/iQm1XZM

**Comment by seasnale** [comment]
yeah i mean it's a mod that duplicates functionality of meteor you might as well just not use it

it's the sort of conflict that is probably difficult to deal with because there aren't that many ways of doing fullbright
