### ISSUE TITLE
add ping bypass

### ISSUE THREAD

**Issue by mrbuilder08** [MeteorDevelopment/meteor-client#3034]
### Describe the feature

hosts client on a server, sending inputs to the client being run on the server. this will be very useful for Australians on 2b2t, I am in SCA and will personally promote this client once this feature is added.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by EurekaEffect** [comment]
> Ever heard of a vpn?

do you know how VPN works? 🤓

**Comment by I-Got-You-Dead** [comment]
Why yes, yes I do

**Comment by Mathrandom7910** [comment]
issues keep getting better bruh
