### ISSUE TITLE
[Suggestion] particle esp

### ISSUE THREAD

**Issue by OhSynco** [MeteorDevelopment/meteor-client#3037]
### Describe the feature

an ESP for particles using tracers (would be good for economy servers which use particles to surround a claim)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Bro

**Comment by I-Got-You-Dead** [comment]
1: Don’t use meteor where it’s not allowed
2: No offence but this is just dumb
