### ISSUE TITLE
[Suggestion]  Add no hurt cam

### ISSUE THREAD

**Issue by Shyammc18** [MeteorDevelopment/meteor-client#3039]
### Describe the feature

No hurt cam will help players from the screen shaking thingy when someone uses a fire aspect sword or something like that

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
“ This feature doesn't already exist in the client. (I have checked every module and their settings on the latest dev build)”
