### ISSUE TITLE
Tracers bobbing

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#3040]
### Describe the bug

View bobbing affects the tracers. https://imgur.com/O658O6C

### Steps to reproduce

```bash
turn on tracers
```

### Meteor Version

meteor-client-0.5.2-1715

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
o h g o d

**Comment by I-Got-You-Dead** [comment]
Prob something to do with the 1.19.3 update

**Comment by MineGame159** [comment]
Fixed in 59e92ad4961c5336f944dccc57607ef973b3c432.
