### ISSUE TITLE
[Bug] minecraft crashes upon opening the hud tab

### ISSUE THREAD

**Issue by UnsportedVortex22565** [MeteorDevelopment/meteor-client#3044]
### Describe the bug

minecraft shows this arror code whenever opening the hud tab even on servers or main menu screen

### Steps to reproduce

```bash
open the hud tab
```

### Meteor Version

0.5.2 latest dev 

### Minecraft Version

1.19.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
send logs/crash report

**Comment by rospino74** [comment]
## Stacktrace
Here's mine. I don't know if this is similar to the author's
```
[16:23:28] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_27983()" because "meteordevelopment.meteorclient.utils.misc.FakeClientPlayer.world" is null
	at meteordevelopment.meteorclient.utils.misc.FakeClientPlayer.getPlayer(FakeClientPlayer.java:45) ~[meteor-client-0.5.2-1720.jar:?]
	at meteordevelopment.meteorclient.systems.hud.elements.PlayerModelHud.lambda$render$2(PlayerModelHud.java:99) ~[meteor-client-0.5.2-1720.jar:?]
	at meteordevelopment.meteorclient.systems.hud.HudRenderer.end(HudRenderer.java:92) ~[meteor-client-0.5.2-1720.jar:?]
	at meteordevelopment.meteorclient.systems.hud.Hud.onRender(Hud.java:227) ~[meteor-client-0.5.2-1720.jar:?]
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.5.2-1720.jar:?]
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47) ~[meteor-client-0.5.2-1720.jar:?]
	...
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.11.jar:?]
```

## Cause
https://github.com/MeteorDevelopment/meteor-client/blob/daf6d3f957de77144f115c7f531987ca5e13a7ba/src/main/java/meteordevelopment/meteorclient/utils/misc/FakeClientPlayer.java#L44-L46

So basically the code checks if the world is null but then proceeds to call two of its methods anyway, resulting in an NPE
Bug was added in daf6d3f957de77144f115c7f531987ca5e13a7ba

**Comment by UnsportedVortex22565** [comment]
Here's my logs if you want to read em

https://mclo.gs/YZBlKN9

**Comment by UnsportedVortex22565** [comment]
> ## Stacktrace
> Here's mine. I don't know if this is similar to the author's
> ```
> [16:23:28] [Render thread/ERROR]: Unreported exception thrown!
> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_27983()" because "meteordevelopment.meteorclient.utils.misc.FakeClientPlayer.world" is null
> 	at meteordevelopment.meteorclient.utils.misc.FakeClientPlayer.getPlayer(FakeClientPlayer.java:45) ~[meteor-client-0.5.2-1720.jar:?]
> 	at meteordevelopment.meteorclient.systems.hud.elements.PlayerModelHud.lambda$render$2(PlayerModelHud.java:99) ~[meteor-client-0.5.2-1720.jar:?]
> 	at meteordevelopment.meteorclient.systems.hud.HudRenderer.end(HudRenderer.java:92) ~[meteor-client-0.5.2-1720.jar:?]
> 	at meteordevelopment.meteorclient.systems.hud.Hud.onRender(Hud.java:227) ~[meteor-client-0.5.2-1720.jar:?]
> 	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) ~[meteor-client-0.5.2-1720.jar:?]
> 	at meteordevelopment.orbit.EventBus.post(EventBus.java:47) ~[meteor-client-0.5.2-1720.jar:?]
> 	...
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.11.jar:?]
> ```
> 
> ## Cause
> https://github.com/MeteorDevelopment/meteor-client/blob/daf6d3f957de77144f115c7f531987ca5e13a7ba/src/main/java/meteordevelopment/meteorclient/utils/misc/FakeClientPlayer.java#L44-L46
> 
> So basically the code checks if the world is null but then proceeds to call two of its methods anyway, resulting in an NPE
> Bug was added in daf6d3f957de77144f115c7f531987ca5e13a7ba

Here's the logs if want to read em also toward the end there's a error

https://mclo.gs/YZBlKN9

**Comment by rospino74** [comment]
Yeah, it's the same exception

**Comment by UnsportedVortex22565** [comment]
> Yeah, it's the same exception 
I did some research and i discovered that everything that has a player model in the hud editor innit crashes with a code error 255

**Comment by seasnale** [comment]
#3069
