### ISSUE TITLE
Auto-eject like Impact

### ISSUE THREAD

**Issue by brickyosu** [MeteorDevelopment/meteor-client#3049]
### Describe the feature

I want an auto-eject feature like Impact. You turn it on, go to settings, and choose the block(s) that you want to auto-drop. It's very useful when mining in Baritone, getting useless blocks and you want to drop it, but you need to stop baritone and then drop it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Already a thing in Inventory Tweaks.
