### ISSUE TITLE
[Bug] Nofall prevents projectiles from being altered by jumping

### ISSUE THREAD

**Issue by SylveonBottle** [MeteorDevelopment/meteor-client#305]
**Describe the bug**

**To Reproduce**
1. Go into creative, grab a bow and/or enderpearl
2. Jump, then immediently shoot/throw the bow/enderpearl
3. Notice how the object flies at an upwards angle, going a much further distance
4. Enable No Fall
5. Repeat 2-3, notice how the projectile does not go upwards

**Expected behavior**
Nofall should not alter the behavior of shooting/throwing

**Screenshots**
Video hosted on github:
https://user-images.githubusercontent.com/17802843/111087829-b576b900-851b-11eb-9f3e-67ea6f4d8ee6.mp4

**Additional context**
Possible solution to fix the issue:
-When NoFall is enabled, do not use Nofall while on the ground. Only enable the nofall code while falling in the air.

I have came across a similar problem with another client's nofall, where Nofall would prevent blocks from breaking at a proper speed. I believe I may have experienced this issue with Meteor, although I can not test this thoroughly. If I come across this issue with steps to reproduce however, I will create a new ticket. However, my potential solution for this issue would also resolve that issue, if it exists.

**Comment by SylveonBottle** [comment]
In case the video does not load, I have uploaded a copy to Gfycat:
https://gfycat.com/simpleadmirediberiannase

**Comment by RedCarlos26** [comment]
Since no fall cancels packets, this is probably the reason why projectiles aren't affected by falling. This is probably not fixable without breaking no fall.

**Comment by SylveonBottle** [comment]
> Since no fall cancels packets, this is probably the reason why projectiles aren't affected by falling. This is probably not fixable without breaking no fall.

A very specific fix, but how about "don't cancel packets when shooting a bow or right-clicking on an enderpearl"?

**Comment by RedCarlos26** [comment]
It could be done, but no fall will not work in this case, so you could take fall damage.

**Comment by SylveonBottle** [comment]
If such a fix was necessary to introduce, would it not be simple to have a
switch to toggle this functionality?

"Disable when using projectiles"

**Comment by RedCarlos26** [comment]
Yes this could be done.

**Comment by RedCarlos26** [comment]
In my opinion, the fact of having the full trajectory of the projectile is great, because you can throw further and more precisely. What would be the benefit of adding that?
