### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by ZG468** [MeteorDevelopment/meteor-client#3053]
### Describe the feature

Auto-Clutch

It's in the name, it puts your water bucket in your hand and then places it and puts it back in the bucket.

There could be an option to change how high your fall would be to detect if your falling. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Lovecrafts-Cat** [comment]
This is already a feature, it's in the `No Fall` module.

**Comment by I-Got-You-Dead** [comment]
“ This feature doesn't already exist in the client. (I have checked every module and their settings on the latest dev build)” 🥱
