### ISSUE TITLE
[Bug] Fake player doesnt work anymore (since 1.19.3)

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#3059]
### Describe the bug

Pretty self explanatory

### Steps to reproduce

```bash
1. Try to spawn a fakeplayer (with module on or off)
2. See that it doesnt work
```

### Meteor Version

0.5.2-1719

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RickyTheRacc** [comment]
Fakeplayer does technically work, but not fully:
- The first time you spawn a fakeplayer in, it won't have a skin and will be invisible
- If you clear fakeplayers after the first time and spawn one again with a command, it will have a skin
- All fakeplayers spawned after that will be invisible

**Comment by RedCarlos26** [comment]
I see alright
