### ISSUE TITLE
[Bug] Auto Eat doesn't pause baritone if baritone is digging

### ISSUE THREAD

**Issue by SylveonBottle** [MeteorDevelopment/meteor-client#306]
**Describe the bug**
Auto Eat doesn't pause baritone if baritone is digging

**To Reproduce**
1. `#sel pos1` and `#sel pos2` a test area
2. `#sel ca` to clear the area
3. Enable Auto-Eat
4. Notice that baritone attempts to dig while autoeat attempts to eat, causing to switch back and forth between pickaxe and food

**Expected behavior**
Baritone should stop digging (paused) and eat

**Additional context**
Baritone will pause and Auto Eat will activate if baritone is currently pathing towards a goal.
However, is baritone is **actively digging** (such as using `#sel cleararea`), this glitch will occur.

**Comment by SylveonBottle** [comment]
I have uploaded footage of this behavior on Catbox.moe:
https://files.catbox.moe/byn0in.mp4

Ignoring the zombies, you can clearly see autoeat attempting to eat food despite baritone mining.

And although I did not show it, this was my autoeat config:

![javaw_AXmCDx6wP1](https://user-images.githubusercontent.com/17802843/111178330-eea63c00-85a2-11eb-8f96-49ec23dab79c.png)

I am using my own installation of Fabritone. If Meteor Client has it's own copy of baritone/fabritone and this problem does not exist, I will remove Fabritone and see if the problem is removed.

**Comment by StormyBytes** [comment]
Meteor does have its own baritone. And I can confirm this problem happened. Even with `Pause Baritone` setting set to true, auto eat still doesn't pause baritone. It only eats when I manually pause baritone using `@pause`

**Comment by RedCarlos26** [comment]
I can confirm

**Comment by MineGame159** [comment]
Cannot reproduce. Im pretty sure its caused by you having 2 baritones at the same time (one from Meteor and one in your mods folder).

**Comment by mvrozanti** [comment]
@MineGame159 I don't have two baritone mods, only meteor's built-in one, and I still get this bug. I am running two instances of the game at the same time though. Is this expected or is it a bug?

**Comment by I-Got-You-Dead2** [comment]
I managed to reproduce this

**Comment by mvrozanti** [comment]
@I-Got-You-Dead2 this commit seems offly suspicious 16f87bf9ce3ba6a8839a67ed08099d7d2d39b665
