### ISSUE TITLE
[Bug] Auto Respawn doesn't work

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#3061]
### Describe the bug

Auto Respawn fails to actually respawn you and instead just leaves you on the respawn screen like vanilla.

https://user-images.githubusercontent.com/80427814/207761470-c01a96d4-8790-4f53-bfb4-799932688d06.mp4

### Steps to reproduce

```bash
Enable auto respawn and kill yourself, observe the module failing to automatically respawn you
```

### Meteor Version

Latest

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RickyTheRacc** [comment]
I only now realized I uploaded the wrong video

**Comment by OLEPOSSU** [comment]
it works for me perfectly
also why is your ca multiplacing like that

**Comment by RedCarlos26** [comment]
I've never had an issue what
