### ISSUE TITLE
[Suggestion] Add feature to highlight chest in which there's a specific item

### ISSUE THREAD

**Issue by Astrosmos** [MeteorDevelopment/meteor-client#3063]
### Describe the feature

Like that :
https://www.curseforge.com/minecraft/mc-mods/chest-tracker

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
I would assume tie it into a chest aura

**Comment by I-Got-You-Dead** [comment]
That’s prob the best option

**Comment by seasnale** [comment]
> That's not possible. How's the client supposed to know what items are in a chest without opening it first?

it just remembers the content after you open it

**Comment by seasnale** [comment]
however its completely out of the scope of meteor

**Comment by I-Got-You-Dead** [comment]
> however its completely out of the scope of meteor

I don’t see why people don’t just use the mod that they want the feature from

**Comment by I-Got-You-Dead** [comment]
It works fine

**Comment by seasnale** [comment]
yeah
