### ISSUE TITLE
[Suggestion] SHIFT tool

### ISSUE THREAD

**Issue by Chocolate57x** [MeteorDevelopment/meteor-client#3068]
### Describe the feature

A tool to automatically shift for you. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
?
