### ISSUE TITLE
[Bug] Game crashes with CombatHud enabled

### ISSUE THREAD

**Issue by EvanHeavenn** [MeteorDevelopment/meteor-client#3069]
### Describe the bug

Game crashes whenever I try and turn on CombatHud. Crashes even with zero modules enabled and no mods except for Meteor installed.

### Steps to reproduce

```bash
Go into the Hud menu and enable Combat, game crashes.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/WKNC0xJ 

### Meteor Version

0.5.2-1729

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Looks like a fakeplayer bug, I’ll look into fixing it but someone will prob beat me to it.

**Comment by Cr7mbl3** [comment]
Calling  getRegistryKey() and getDimensionEntry() on world object that's null causes this crash. See FakeClientPlayer.getPlayer()

https://github.com/MeteorDevelopment/meteor-client/blob/daf6d3f957de77144f115c7f531987ca5e13a7ba/src/main/java/meteordevelopment/meteorclient/utils/misc/FakeClientPlayer.java#L44-L45
