### ISSUE TITLE
[Suggestion] Add anti pigmen hit module (like anti friend hit but for zombified piglins)

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#307]

**Comment by supakeks** [comment]
There should be a module called "AntiHit" which replaces AntiFriendHit imo, there could be a setting inside it called "friends" which does what antifriendhit does rn, and another setting to select any entity

**Comment by RedCarlos26** [comment]
Yes, but it would be gratifying you could choose which entity u want

**Comment by StormyBytes** [comment]
Pull request was merged already. Perhaps close this issue?

**Comment by RedCarlos26** [comment]
Yes close it

**Comment by StormyBytes** [comment]
> Yes close it

shouldnt you be able to close it since youre the author?

**Comment by RedCarlos26** [comment]
No I can't. I don,t know why.
