### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by idksalem** [MeteorDevelopment/meteor-client#3071]
### Describe the bug

im on 1.19.3 build 1730 i get the error.  An unhandled exception occurred. The error is in your game's log, please report this at github.com/cabaletta/baritone/issues 

### Steps to reproduce

```bash
#mine
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/nzdK28l

### Meteor Version

1730

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by UnsportedVortex22565** [comment]
same happened to me with the command #explore 

here's the logs: https://mclo.gs/L0NTKRX

**Comment by seasnale** [comment]
evidently a baritone issue 
you literally pasted the text that says "please report this at github.com/cabaletta/baritone/issues"
bruh
