### ISSUE TITLE
FOV Option button crash

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#3074]
### Describe the bug

Whenever I change an option, specifically FOV, then go back to the game, and press esc and options again it crashes my game.

Operating system:
Windows 11

Active mods: 
Starlight
Sodium
Meteor
Lithium
Lazydfu
Krypton
Ferritecore
Fabric API
Entity Culling
Dynamic FPS

### Steps to reproduce

```bash
> Press ESC 
> Change FOV
> Go back to main game
> Press ESC
> Press the options button
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/8ub6gyb

### Meteor Version

meteor-client-0.5.2-1730

### Minecraft Version

Fabric 1.19.3 

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
You don’t need dynamic fps installed btw

**Comment by Wide-Cat** [comment]
are you sure that this is a meteor issue? It's not present in the stack trace

**Comment by Wide-Cat** [comment]
test it to see if it still happens without meteor, and if it does then we know its a meteor issue

**Comment by I-Got-You-Dead** [comment]
Play without meteor for 2 days and if it doesn’t happen then I think it’s safe to say it’s a meteor issue

**Comment by RedCarlos26** [comment]
Can confirm
