### ISSUE TITLE
[Bug] Trajectories with Elytra+ are wrong and predict the wrong path. 

### ISSUE THREAD

**Issue by ikeafridge4** [MeteorDevelopment/meteor-client#308]
while using trajectories when flying, trajectories will display a path that is completely wrong.

**Comment by RedCarlos26** [comment]
Can confirm the bug

**Comment by SirDoz** [comment]
Can confirm

**Comment by MineGame159** [comment]
Fixed in 5fe1d3e4276e63df195d2d2fd6ecb97dfb76e6ec
