### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by adrianfuchs** [MeteorDevelopment/meteor-client#3081]
### Describe the bug

macros dont work properly

![image](https://user-images.githubusercontent.com/34813889/208467659-34c0dd18-2cea-43ae-9897-d1944b265079.png)

![image](https://user-images.githubusercontent.com/34813889/208467493-022a0b7b-cba1-4ff0-af6e-a69318551b2b.png)
![image](https://user-images.githubusercontent.com/34813889/208467517-07b1bf5d-1a24-4e93-bb4a-3f9f8b7ef6b3.png)

### Steps to reproduce

```bash
just write your baritone command in a macro and try to use it, it will appear on chat instead of work
```

### Meteor Version

meteor-client-0.5.2-1730

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by marcschwaiger** [comment]
This was patched in https://github.com/MeteorDevelopment/meteor-client/pull/3070
