### ISSUE TITLE
[Suggestion] add integrated seedmap

### ISSUE THREAD

**Issue by FrostX-Official** [MeteorDevelopment/meteor-client#3087]
### Describe the feature

So in meteor client we have command .seed but there's no use of it, i suggest adding SeedMap module and it will make a map gui at the corner of screen and show map of the seed, you can use [Amidst API](https://github.com/toolbox4minecraft/amidst) (which [chunkbase](https://www.chunkbase.com/apps/seed-map) uses) and get map data and then make it appear on map gui.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Meteor rejects

**Comment by I-Got-You-Dead** [comment]
And .locate

**Comment by FrostX-Official** [comment]
💀 im talking about map/radar gui not chat command

**Comment by I-Got-You-Dead** [comment]
Cope
