### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vikoware** [MeteorDevelopment/meteor-client#3088]
### Describe the bug

Whenever I open the HUD my game crashes but the thing is it didnt do that before i just started randomly crashing when i opened.

### Steps to reproduce

```bash
I dont know what i did but i feel like it just started crashing out of nowhere.
```

### Meteor Version

Dev Build

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by KillaQuack98** [comment]
Open appdata through windows key + r, go to roaming open the .minecraft folder, after that scroll and look for the meteor-client folder, and delete modules + config, it will undo your config but should undo your crashing.

**Comment by Cr7mbl3** [comment]
Do you have Combat HUD enabled?

**Comment by Wide-Cat** [comment]
this should be resolved
