### ISSUE TITLE
BetterChat: misplaced player heads

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#3099]
### Describe the bug

![image](https://user-images.githubusercontent.com/52252627/209246149-7a0a69e0-da12-41db-88c1-ed6f56a109f0.png)

This bug occurs whenever the `Player Heads` option is turned on in the `Better Chat` module.
While the heads should appear next to the sent messages in chat, they instead are found in the top left corner of the screen.
This has been happening in version `0.5.2 - 1730` too, as there are previous occurences of this in the discord chat.

### Steps to reproduce

```bash
1. Turn on Better Chat
2. Turn on Player Heads
3. Write any message in chat
```

### Meteor Version

0.5.2 - 1730

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Lovecrafts-Cat** [comment]
Last edit of this module happened in [this](https://github.com/MeteorDevelopment/meteor-client/commit/d8f48db1698a72ddcdd73ca75628635dad1b10ce#diff-ffa5ed6c58a863e9756981d194a7e1bf43efb5905958a5b5f83dcf8794be9cbb) commit, just in case it can help.

**Comment by RacoonDog** [comment]
> Last edit of this module happened in [this](https://github.com/MeteorDevelopment/meteor-client/commit/d8f48db1698a72ddcdd73ca75628635dad1b10ce#diff-ffa5ed6c58a863e9756981d194a7e1bf43efb5905958a5b5f83dcf8794be9cbb) commit, just in case it can help.

that commit doesn't touch any part of the head rendering code sadly
