### ISSUE TITLE
ESP Parallaxing graphical glitch when using Iris with Shader setting

### ISSUE THREAD

**Issue by Pdam67** [MeteorDevelopment/meteor-client#3111]
### Describe the bug

Parallaxing on items, armour pieces, skin and capes on a player when looking around. 

![2022-12-24_11 26 59](https://user-images.githubusercontent.com/121340850/209434129-8d62babf-55b0-44ba-b758-6f8587fbff6e.png)
![2022-12-24_11 11 04](https://user-images.githubusercontent.com/121340850/209434131-4c79465f-f9a7-45de-aaa1-781d57ef3d02.png)
![2022-12-24_11 24 55](https://user-images.githubusercontent.com/121340850/209434133-d21ba663-578e-4173-8b23-51c2ea0d8746.png)
![2022-12-24_11 25 31](https://user-images.githubusercontent.com/121340850/209434134-ba44f30f-1e19-4798-b867-f1fe9d73966e.png)

### Steps to reproduce

```bash
Use Meteor client (1741) along side Sodium WITH Iris and have the ESP module on with the Shader option enabled.
```

### Meteor Version

1741

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
Same as #1259

**Comment by I-Got-You-Dead** [comment]
Bruh @seasnale can y’all actually fix this 💀
