### ISSUE TITLE
[Bug] cant use auto eat with offhand item

### ISSUE THREAD

**Issue by hanakoyuna** [MeteorDevelopment/meteor-client#3115]
### Describe the bug

well basicly the bot just confused or smth idk it just keep spam eat but not gona eat it

### Steps to reproduce

```bash
turn on auto eat
get smth offhand
and wait til hungry
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Pain
