### ISSUE TITLE
scaffold issiues

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#3119]
### Describe the bug

when set rotate in scaffold on, scaffold place blocks slower(10 blocks per second) then rotate off(20 block per second).

### Steps to reproduce

```bash
go into scaffold settings
turn on rotate
scaffold now place locks slower and some times fail to catch me when going downwards.
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by qeqeqeplayer533** [comment]
I like hamburgers

**Comment by OLEPOSSU** [comment]
its slower because it has to rotate

**Comment by qeqeqeplayer533** [comment]
I know that is what I said

**Comment by qeqeqeplayer533** [comment]
make it not slowed down by rotate

**Comment by I-Got-You-Dead** [comment]
Cope harder

**Comment by OLEPOSSU** [comment]
its possible but fast rotations wont work on every server

**Comment by qeqeqeplayer533** [comment]
wait, first to comment is not I_Got_You_Dead?

**Comment by I-Got-You-Dead** [comment]
Cope

**Comment by qeqeqeplayer533** [comment]
maybe add an option to turn on fast rotation?

**Comment by I-Got-You-Dead** [comment]
Bro

**Comment by I-Got-You-Dead** [comment]
Do you realise that there are 20 ticks in a second

**Comment by I-Got-You-Dead** [comment]
And that rotations take 1 tick

**Comment by qeqeqeplayer533** [comment]
why not multi task

**Comment by I-Got-You-Dead** [comment]
1: packet limits
2: tick rates

**Comment by I-Got-You-Dead** [comment]
Use timer if you must

**Comment by qeqeqeplayer533** [comment]
how did u replie so fast
