### ISSUE TITLE
[Bug] Game framerate dramatically decreases when the mouse is moved

### ISSUE THREAD

**Issue by tinbolw** [MeteorDevelopment/meteor-client#312]
**Describe the bug**
Whenever the mouse is moved in game, the framerate drops dramatically.

**To Reproduce**
1. Enter a world
2. Move the mouse around
3. Watch framerate drop

**Expected behavior**
The game runs like it usually would

**Screenshots**
https://user-images.githubusercontent.com/36116384/111557074-349d0480-8749-11eb-8d39-1056c59e0b3c.mp4

**Additional context**
OS: masOS Big Sur 11.2.3
Minecraft Version: 1.16.5
Meteor Version: 0.4.2
Other Mods: MiniHUD to show the framerate, and MaLiLib, dependency of MiniHUD.
This is a bug with meteor client itself as I tested it without any other mods and the issue still happened, I just used minihud to show the framerate.

**Comment by ekcire06** [comment]
-profile pic linux logo
-plays on mac
-bruh

**Comment by ikeafridge4** [comment]
ez fix: dont play on mac :)

**Comment by seasnail8169** [comment]
I cannot reproduce this. 
Also, you do not need MiniHUD to show the FPS, Meteors HUD can do that.

**Comment by RedCarlos26** [comment]
I cannot reproduce this too. I think this is a system issue, not a bug.

**Comment by asdffdsdaf** [comment]
lol wtf get ez'd man
its a you issue ezezezezez
