### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BlazeWarfaree** [MeteorDevelopment/meteor-client#3121]
### Describe the bug

Auto reconnect does not work on constantiam
![QwlNYUs](https://user-images.githubusercontent.com/69606665/209738195-180d7498-7170-4b9f-b2e0-1c2621dc0275.png)

### Steps to reproduce

```bash
Latest meteor build, enable auto reconnect and wait for the restart done automatically every 6 hours
```

### Meteor Version

Latest

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
resolved as of #3605
