### ISSUE TITLE
Can't use Meteor on Minecraft Old Version.

### ISSUE THREAD

**Issue by LegendHuy** [MeteorDevelopment/meteor-client#3122]
### Describe the feature

Hello Developer,

I want to play Meteor Client on Minecraft 1.19 so I used ViaFabric and Multiconnect but I got this error
Replace mod 'Meteor Client' (meteor-client) 0.5.1 with any version that is compatible with: minecraft 1.19

Please help me with this error both ViaFabric and Multiconnect aren't help me this. I don't know this already suggested so thanks.

Meteor Client: Release 0.5.1 (Lastest Version)
Minecraft Version: Fabric 1.19
Minecraft Launcher: TLauncher
Submitted: 12/28/2022
Time: 6:55 GMT+7

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Lovecrafts-Cat** [comment]
Did you read our [FAQ](https://meteorclient.com/faq#how-do-i-use-meteor-on-older-minecraft-versions?) to know how to use Multiconnect or ViaFabric?
It clearly says that you must be on one of the two supported versions of Meteor (currently 1.19.2/1.19.3),
and download Multiconnect or ViaFabric for that same version (1.19.2/1.19.3 once again).
