### ISSUE TITLE
Meteor crashes when trying to edit the HUD

### ISSUE THREAD

**Issue by Maks7594** [MeteorDevelopment/meteor-client#3123]
### Describe the bug

When i click HUD in the clickgui, meteor crashes.

### Steps to reproduce

```bash
1. open clickgui
2. click hud
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/3TkGBeW

### Meteor Version

some dev build

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Maks7594** [comment]
i am also very sure that this isnt a duplicate, i searched the last 3 pages

**Comment by DemuraAIdev** [comment]
I have same issue

**Comment by ThebestkillerTBK** [comment]
#3069 same

**Comment by Maks7594** [comment]
BRUH

**Comment by Maks7594** [comment]
that talks about the combathud and not the hud itself

**Comment by RacoonDog** [comment]
> that talks about the combathud and not the hud itself

crash is caused by combathud

**Comment by unseeyou** [comment]
this also happens to me

**Comment by rospino74** [comment]
> I am also very sure that this isnt a duplicate, i searched the last 3 pages

Yes, it is. Similar issues are #3069 and #3044
