### ISSUE TITLE
[Suggestion] Critical mode: sprint

### ISSUE THREAD

**Issue by utilityuser2048** [MeteorDevelopment/meteor-client#3124]
### Describe the feature

As you may know, you can not crit people when you are sprinting, so add a new critical mode that allows you to crit people when sprinting. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by qeqeqeplayer533** [comment]
use anti hunger

**Comment by I-Got-You-Dead** [comment]
That works?

**Comment by I-Got-You-Dead** [comment]
Interesting

**Comment by Mathrandom7910** [comment]
It's because it doesnt send sprint packets.

**Comment by utilityuser2048** [comment]
is it anti cheat dectable

**Comment by utilityuser2048** [comment]
i don’t want to get kicked by anticheat and lose all my stuff bruh

**Comment by I-Got-You-Dead** [comment]
> i don’t want to get kicked by anticheat and lose all my stuff bruh
> […](#)

Average box server player

**Comment by utilityuser2048** [comment]
no it’s survival

**Comment by I-Got-You-Dead** [comment]
Doesn’t matter, you shouldn’t be using meteor where it’s not allowed

**Comment by utilityuser2048** [comment]
server rules says hacks are not allowed, but meteor is utility mod

**Comment by Mathrandom7910** [comment]
> server rules says hacks are not allowed, but meteor is utility mod
ok dude 👍
