### ISSUE TITLE
crystal aura inprovment

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#3128]
### Describe the feature

If you do not place crystal using offhand, you cant crystal aura and eat at the same time, add an checkbox at pause page called "pause on necessary" it check if you are main hand place crystal or offhand place crystal, if you are main hand it will auto pause on eat or drink even if the pause on eat or drink check box is off. Add a option at place page where you can choose what hand to use when placing crystal(main hand, offhand). main hand will prefer place crystal with main hand when both hand are not holding crystal, off hand will prefer place crystal with off hand when both hand are not holding crystal. The "pause on necessary" will not activate if preferred place hand is off hand where you can gap and place crystal at the same time.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Well that’s dumb

**Comment by qeqeqeplayer533** [comment]
?
