### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#3148]
### Describe the bug

Crash

### Steps to reproduce

```bash
enable jesus with lithium mod installed, walk on liquid in single player. then crash.
```

### Link to crash report/log if applicable (https://mclo.gs)

---- Minecraft Crash Report ---- // This doesn't make any sense!  Time: 2023-01-02 19:43:58 Description: Ticking entity  java.lang.NullPointerException: Cannot invoke "net.minecraft.class_265.method_1096(double, double, double)" because "shape" is null 	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) 	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getCollidedShape(ChunkAwareBlockCollisionSweeper.java:245) 	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:206) 	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:28) 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) 	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.getBlockCollisions(LithiumEntityCollisions.java:34) 	at net.minecraft.entity.Entity.lithiumCollideMultiAxisMovement(Entity:10608) 	at net.minecraft.entity.Entity.adjustMovementForCollisions(Entity:10588) 	at net.minecraft.entity.Entity.adjustMovementForCollisions(Entity:940) 	at net.minecraft.entity.Entity.move(Entity:650) 	at net.minecraft.entity.ItemEntity.tick(ItemEntity:132) 	at net.minecraft.client.world.ClientWorld.tickEntity(ClientWorld:267) 	at net.minecraft.world.World.tickEntity(World:466) 	at net.minecraft.client.world.ClientWorld.method_32124(ClientWorld:250) 	at net.minecraft.world.EntityList.forEach(EntityList:54) 	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld:246) 	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1851) 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135) 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768) 	at net.minecraft.client.main.Main.main(Main:244) 	at net.minecraft.client.main.Main.main(Main:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.getCollidedShape(ChunkAwareBlockCollisionSweeper.java:245) 	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:206) 	at me.jellysquid.mods.lithium.common.entity.movement.ChunkAwareBlockCollisionSweeper.computeNext(ChunkAwareBlockCollisionSweeper.java:28) 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) 	at me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions.getBlockCollisions(LithiumEntityCollisions.java:34) 	at net.minecraft.class_1297.lithiumCollideMultiAxisMovement(class_1297.java:10608) 	at net.minecraft.class_1297.method_20736(class_1297.java:10588) 	at net.minecraft.class_1297.method_17835(class_1297.java:940) 	at net.minecraft.class_1297.method_5784(class_1297.java:650) 	at net.minecraft.class_1542.method_5773(class_1542.java:132) 	at net.minecraft.class_638.method_18646(class_638.java:267) 	at net.minecraft.class_1937.method_18472(class_1937.java:466) 	at net.minecraft.class_638.method_32124(class_638.java:250) 	at net.minecraft.class_5574.method_31791(class_5574.java:54) 	at net.minecraft.class_638.method_18116(class_638.java:246)  -- Entity being ticked -- Details: 	Entity Type: minecraft:item (net.minecraft.class_1542) 	Entity ID: 15555 	Entity Name: Smoker 	Entity's Exact location: 135.80, -54.32, -40.37 	Entity's Block location: World: (135,-55,-41), Section: (at 7,9,7 in 8,-4,-3; chunk contains blocks 128,-64,-48 to 143,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1) 	Entity's Momentum: 0.02, 0.07, 0.06 	Entity's Passengers: [] 	Entity's Vehicle: null 	Entity NBT: {Age:2s,Air:300s,FallDistance:0.0f,Fire:0s,Health:5s,Invulnerable:0b,Item:{Count:1b,id:"minecraft:smoker"},Motion:[0.02461025095796586d,0.07446399999999997d,0.05534305215425494d],OnGround:0b,PickupDelay:0s,PortalCooldown:0,Pos:[135.7974675930996d,-54.3233847983139d,-40.37479391663481d],Rotation:[178.59375f,0.0f],UUID:[I;16926727,-258653819,-1336523140,-1349775711]} Stacktrace: 	at net.minecraft.class_1937.method_18472(class_1937.java:466) 	at net.minecraft.class_638.method_32124(class_638.java:250) 	at net.minecraft.class_5574.method_31791(class_5574.java:54) 	at net.minecraft.class_638.method_18116(class_638.java:246) 	at net.minecraft.class_310.method_1574(class_310.java:1851) 	at net.minecraft.class_310.method_1523(class_310.java:1135) 	at net.minecraft.class_310.method_1514(class_310.java:768) 	at net.minecraft.client.main.Main.method_44604(Main.java:244) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- Affected level -- Details: 	All players: 1 total; [class_746['qeqeqeplayer533'/9, l='ClientLevel', x=134.85, y=-55.00, z=-40.72]] 	Chunk stats: 256, 121 	Level dimension: minecraft:overworld 	Level spawn location: World: (0,65,0), Section: (at 0,1,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 57980 game time, 57980 day time 	Server brand: fabric 	Server type: Integrated singleplayer server Stacktrace: 	at net.minecraft.class_638.method_8538(class_638.java:453) 	at net.minecraft.class_310.method_1587(class_310.java:2341) 	at net.minecraft.class_310.method_1514(class_310.java:787) 	at net.minecraft.client.main.Main.method_44604(Main.java:244) 	at net.minecraft.client.main.Main.main(Main.java:51) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: Default, Fabric Mods  -- System Details -- Details: 	Minecraft Version: 1.19.2 	Minecraft Version ID: 1.19.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.3, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 1342269176 bytes (1280 MiB) / 2650800128 bytes (2528 MiB) up to 6912212992 bytes (6592 MiB) 	CPUs: 4 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz 	Identifier: Intel64 Family 6 Model 69 Stepping 1 	Microarchitecture: unknown 	Frequency (GHz): 2.49 	Number of physical packages: 1 	Number of physical CPUs: 2 	Number of logical CPUs: 4 	Graphics card #0 name: Intel(R) HD Graphics Family 	Graphics card #0 vendor: Intel Corporation (0x8086) 	Graphics card #0 VRAM (MB): 1024.00 	Graphics card #0 deviceId: 0x0a16 	Graphics card #0 versionInfo: DriverVersion=20.19.15.4835 	Memory slot #0 capacity (MB): 4096.00 	Memory slot #0 clockSpeed (GHz): 1.60 	Memory slot #0 type: DDR3 	Memory slot #1 capacity (MB): 4096.00 	Memory slot #1 clockSpeed (GHz): 1.60 	Memory slot #1 type: DDR3 	Virtual memory max (MB): 14698.30 	Virtual memory used (MB): 9019.98 	Swap memory total (MB): 6600.94 	Swap memory used (MB): 2346.14 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6580M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Fabric Mods:  		appleskin: AppleSkin 2.4.0+mc1.19 		architectury: Architectury 6.3.49 		bananaplus: Banana+ 69 		bbc: BBC 0.1.0 		betterbeds: Better Beds 1.2.0 		betterfpsdist: Better FPS distance Mod 1.19.1-2.0 		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.9.0 			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.9.0 			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.9.0 			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.9.0 			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.9.0 			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.9.0 			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.9.0 			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.9.0 			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.9.0 			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.9.0 			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.9.0 			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.9.0 			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.9.0 			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.9.0 			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.9.0 			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.9.0 			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.9.0 			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.0 			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.9.0 			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.9.0 			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.9.0 			com_ibm_async_asyncutil: asyncutil 0.1.0 			net_objecthunter_exp4j: exp4j 0.4.8 			org_threadly_threadly: threadly 7.0 		carpet: Carpet Mod 1.4.84 		chunkpregen: Fabric Chunk Pregenerator 0.3.3 		clientcommands: Client Commands 2.7.3 			clientarguments: clientarguments 1.4.1 			multiconnect-api: MultiConnect API 1.5.10 		cloth-config: Cloth Config v8 8.2.88 			cloth-basic-math: cloth-basic-math 0.6.1 		clumps: Clumps 9.0.0+11 		cullleaves: Cull Leaves 2.3.4 			midnightlib: MidnightLib 0.5.2 		dashloader: DashLoader 4.1.1+1.19 			com_github_luben_zstd-jni: zstd-jni 1.5.2-2 			dev_quantumfusion_hyphen: Hyphen 0.2.2 			dev_quantumfusion_taski: Taski 1.1.0 		dimthread: DimensionalThreading 1.2.7 			com_github_wearblackallday_javautils: JavaUtils bd58640372 		dynamicfps: Dynamic FPS 2.2.0 			com_moandjiezana_toml_toml4j: toml4j 0.7.2 		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19 			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2 			spruceui: SpruceUI 4.0.0+1.19 		entityculling: EntityCulling-Fabric 1.5.2-mc1.19 			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT 		fabric-api: Fabric API 0.66.0+1.19.2 			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290 			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90 			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+12bfe4ea90 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90 			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390 			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90 			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290 			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390 			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390 			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.1+6064db2a90 			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.3+b598f4ac90 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.0+a1d87cb890 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90 			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290 			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.33+70efcffe90 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.7+83a8659290 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.10+9e7660c690 			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.18+33fbc73890 			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90 			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90 			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.0+06e0e25190 			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90 			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.13+12bfe4ea90 			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.15+aeb40ebe90 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.16+12bfe4ea90 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390 			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.3+3e1ba48e90 			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590 			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90 			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290 		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20 			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20 			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20 			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20 			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4 			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4 			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4 			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0 			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1 			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1 			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1 		fabricloader: Fabric Loader 0.14.10 		fastfurnace: FastFurnace 1.19.2-5 		ferritecore: FerriteCore 4.2.1 		forcecloseloadingscreen: kennytv's epic force close loading screen mod for Fabric 1.1.1 		forgeconfigapiport: Forge Config API Port 4.2.6 		indium: Indium 1.0.9+mc1.19.2 		java: OpenJDK 64-Bit Server VM 17 		krypton: Krypton 0.2.1 			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT 		ksyxis: Ksyxis 1.1 		lazydfu: LazyDFU 0.1.3 		lithium: Lithium 0.10.0 		meteor-client: Meteor Client 0.5.1-1671 			baritone-meteor: Baritone 1.19.2-SNAPSHOT 		meteor-rejects: Meteor Rejects 0.2 			seedcrackerx-api: SeedCrackerX API 2.10.1 		meteor-utils: meteor-utils 1.0 		meteorist: Meteorist 1.4 		minecraft: Minecraft 1.19.2 		modmenu: Mod Menu 4.0.6 		musicplayer: Music Player 2.4.1.11 		nochatreports: No Chat Reports 1.19.2-v1.13.9 		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2 		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59 		roughlyenoughitems: Roughly Enough Items 9.1.555 			error_notifier: Error Notifier 1.0.9 		servercore: ServerCore 1.3.3-1.19.2 			com_electronwill_night-config_core: core 3.6.6 			com_electronwill_night-config_toml: toml 3.6.6 			com_github_llamalad7_mixinextras: MixinExtras 0.1.0 			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT 			me_lucko_spark-api: spark-api 0.1-SNAPSHOT 			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2 		smoke_suppression: Smoke Suppression 1.0.13 			crowdin-translate: CrowdinTranslate 1.4+1.19 		smoothboot: Smooth Boot 1.19-1.7.1 		sodium: Sodium 0.4.4+build.18 			org_joml_joml: joml 1.10.4 		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68 			caffeineconfig: CaffeineConfig 1.0.0+1.17 		starlight: Starlight 1.1.1+fabric.ae22326 		uiutils: UI Utils 1.0.0 		uteamcore: U Team Core 4.1.0.8 		vector-addon: Vector Addon 0.3.6 	Launched Version: fabric-loader-0.14.10-1.19.2 	Backend library: LWJGL version 3.3.1 SNAPSHOT 	Backend API: Intel(R) HD Graphics 4400 GL version 3.2.0 - Build 20.19.15.4835, Intel 	Window size: 1366x768 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric' 	Type: Integrated Server (map_client.txt) 	Graphics mode: fast 	Resource Packs: vanilla, Fabric Mods 	Current Language: English (US) 	CPU: 4x Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz 	Server Running: true 	Player Count: 1 / 8; [class_3222['qeqeqeplayer533'/9, l='ServerLevel[Vanilla World]', x=134.85, y=-55.00, z=-40.72]] 	Data Packs: vanilla, Fabric Mods 	World Generation: Experimental 	Client Crashes Since Restart: 1 	Integrated Server Crashes Since Restart: 0 	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Lithium (lithium)  -- Meteor Client --  Version: 0.5.1 Dev Build: 1671  [[ Active Modules ]]  [Combat]: auto-armor auto-weapon criticals kill-aura  [Player]: anti-hunger auto-tool ghost-hand no-rotate reach speed-mine  [Movement]: boat-fly fast-climb gui-move jesus no-fall no-slow reverse-step sprint step velocity  [Render]: camera-tweaks fullbright hand-view nametags no-render search storage-esp  [World]: anti-cactus  [Misc]: inventory-tweaks  [Banana Misc.]: tps-sync  [Rejects]: auto-extinguish insta-mine  [[ Active Hud Elements ]] Text {Meteor Client #1{version}} Text {FPS: #1{fps}} Text {TPS: #1{round(server.tps, 1)}} Text {Ping: #1{ping}} Text {Speed: #1{round(player.speed, 1)}} active-modules Text {Pos: #1{floor(camera.pos.x)}, {floor(camera.pos.y)}, {floor(camera.pos.z)}} Text {{player.opposite_dimension != "End" ? player.opposite_dimension + ":" : ""} #1{player.opposite_dimension != "End" ? "" + floor(camera.opposite_dim_pos.x) + ", " + floor(camera.opposite_dim_pos.y) + ", " + floor(camera.opposite_dim_pos.z) : ""}} Text {{camera.direction} #1({round(camera.yaw, 1)}, {round(camera.pitch, 1)})} potion-timers inventory armor item

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
see #3090  

add
mixin.entity.collisions=false
to lithium.properties
