### ISSUE TITLE
[Suggestion] TpAura/MultiAura

### ISSUE THREAD

**Issue by Dari-OS** [MeteorDevelopment/meteor-client#3149]
### Describe the feature

Add TpAura and MultiAura like wurst and Aristois has.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
“This feature doesn’t already exist in the client. (I have checked every module and their settings on the latest dev build)” - Average wurst user

**Comment by EnvisagedMyron** [comment]
bro check the killaura settings

**Comment by Dari-OS** [comment]
> “This feature doesn’t already exist in the client. (I have checked every module and their settings on the latest dev build)” - Average wurst user

there is no tpaura?

**Comment by I-Got-You-Dead** [comment]
Dumbass look at the killaura settings
