### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by BramClappedYou** [MeteorDevelopment/meteor-client#3150]
### Describe the feature

Make a special hack so that you auto d-tap for crystal pvp

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by kisrr** [comment]
hvh client not vpvp
