### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by odvigajlo** [MeteorDevelopment/meteor-client#3151]
### Describe the feature

Add feature where if there's any player in some range, and if yes: meteor client will automatically disconnect player.

Example Usage:
you can use baritone with this feature, you can start mining ores with baritone and this feature will disconnect you if there's
any players nearby, so admins can't spot your nickname and ban you

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
“This feature doesn’t already exist in the client. (I have checked every module and their settings on the latest dev build)”

**Comment by Wide-Cat** [comment]
Auto log
