### ISSUE TITLE
Spectator Notifier

### ISSUE THREAD

**Issue by EnvisagedMyron** [MeteorDevelopment/meteor-client#3152]
### Describe the feature

When a person goes into spectator mode you get a message in chat saying "Warning![player] is in spectator mode!" and if they go
out of spectator mode you get a message saying "The coast is clear![player] is not longer in spectator mode!". This message can be
modified in settings and you can make it say what ever you want and also change the colours of it. Also add a "panic" option in the 
settings which will turn off all hacks once a person goes into spectator.

This would help a lot for avoiding getting caught cheating in certain servers.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
I suggest u make a suggestion on meteor rejects to add this to the anti vanish module
