### ISSUE TITLE
[Bug] Module compatibility issues and no way to get started

### ISSUE THREAD

**Issue by 8MiYile** [MeteorDevelopment/meteor-client#3155]
### Describe the bug

I don't know which modules are wrong
But I have submitted the crash report with the execution log
If you can help me figure out which module is the problem, or confirm that said MeteorClient is the problem. I'd appreciate any help you can give.

### Steps to reproduce

```bash
It crashes after the process of loading the game, so.....
```

### Link to crash report/log if applicable (https://mclo.gs)

[Crash-Report](https://mclo.gs/hifPFrr)
[Latest.log](https://mclo.gs/m1EioXH)
[Quilt Loader Crash Report](https://mclo.gs/7kRR2IX)

### Meteor Version

0.5.2-1748

### Minecraft Version

1.19.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Don’t use quilt

**Comment by 8MiYile** [comment]
> Don’t use quilt

why？

**Comment by I-Got-You-Dead** [comment]
Maybe because meteor isn’t written with the quilt api?

**Comment by 8MiYile** [comment]
> Maybe because meteor isn’t written with the quilt api?

The Quilt API can all take over the work of the Fabric API

**Comment by I-Got-You-Dead** [comment]
Mald

**Comment by 8MiYile** [comment]
> Mald

what? maid? are you kidding me?

**Comment by I-Got-You-Dead** [comment]
Ratio

**Comment by I-Got-You-Dead** [comment]
Also last time I checked the install guide for meteor says to use fabric so cope harder

**Comment by 8MiYile** [comment]
> Also last time I checked the install guide for meteor says to use fabric so cope harder

It is recommended to debug why the MeteorClient mod based on Fabric does not work on Quilt
While others written based on Fabric / FabricAPI can run on top of Quilt / QuiltAPI

**Comment by I-Got-You-Dead** [comment]
Cry

**Comment by 8MiYile** [comment]
> Cry

?????????

**Comment by I-Got-You-Dead** [comment]
Cry

**Comment by 8MiYile** [comment]
> Cry

do not ying ying ying (no

**Comment by ThebestkillerTBK** [comment]
Related to [quilt-loader #179](https://github.com/QuiltMC/quilt-loader/issues/179)

**Comment by ThebestkillerTBK** [comment]
> Related to [quilt-loader #179](https://github.com/QuiltMC/quilt-loader/issues/179)

Workaround inside

**Comment by 8MiYile** [comment]
it's work
but...

**Comment by cqb13** [comment]
if you want meteor to support quilt then make a pr and fix the issue. no1 wants to do it, meteor works great on fabric as is.
