### ISSUE TITLE
Crash (v1.19.3) (Meteor Developer Build)

### ISSUE THREAD

**Issue by Kaleb1583** [MeteorDevelopment/meteor-client#3157]
### Describe the bug

it might be because its a dev build but here:

so I was changing some settings in the config and I found if you go into Config > Font Select  then type in a few random characters  then click enter it crashes. 

I hope this helps and improves the Meteor client!

### Steps to reproduce

```bash
Right Shift > Config Tab > Font > Select Font > Search some random characters like "dsaffdsffs" for example and click enter then it will crash the whole game.

short video showing it: https://clipchamp.com/watch/Hse3HddajU0
```

### Crash Report / Log

https://mclo.gs/PCuk7Id

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Launcher

TLauncher

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by StormyBytes** [comment]
we don't provide support for any cracked launchers.

**Comment by Kaleb1583** [comment]
> Bro is using Russian spyware :kekw:. It's not that hard to buy the actual game, and until you do that, no support will be given to you.

i knew someone would say something like this

**Comment by Kaleb1583** [comment]
> we don't provide support for any cracked launchers.

even if its a cracked launcher its still a problem that most likely the same on the normal launcher

**Comment by Kaleb1583** [comment]
> how do you know its only a problem in cracked versions mr i know it all



> > > we don't provide support for any cracked launchers.
> > 
> > 
> > even if its a cracked launcher its still a problem that most likely the same on the normal launcher
> 
> It isn't? It's a cracked launcher issue I know for a fact, based on how you explain it. Also who in the right mind would give support for cracked launchers, especially one that's Russian spyware?

how do you know its only a problem in cracked versions mr i know it all

**Comment by GreemDev** [comment]
because you can very easily check it? lmfao

**Comment by Kaleb1583** [comment]
I cant because i'm not spending money on it. if you have the real launcher and meteor can u check? you don't have to obviously your choice

**Comment by Wide-Cat** [comment]
Already fixed

**Comment by I-Got-You-Dead** [comment]
Y’all should just make meteor crash if ran on a cracked launcher

**Comment by cqb13** [comment]
> Y’all should just make meteor crash if ran on a cracked launcher

then there would be hundreds of people flooding support channel, bc game is crashing for no reason.

**Comment by I-Got-You-Dead** [comment]
Just make the error message say something like “cracked launchers are unsupported, please use a premium launcher” then just ban people who cry about it

**Comment by I-Got-You-Dead** [comment]
:trollface:

**Comment by Mathrandom7910** [comment]
you joke about this, but that would actually be a good idea.

**Comment by I-Got-You-Dead** [comment]
Fr

**Comment by I-Got-You-Dead** [comment]
Or instead of crashing just make random shit happen in game. E.g. random damage, triggering anticheats, walking towards creepers, a small chance of closing their game and so on
