### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ceminto** [MeteorDevelopment/meteor-client#3160]
### Describe the bug

every time i use the command ".enchant remove" for any enchantment my game crashes.

### Steps to reproduce

```bash
enter the command ".enchant remove (enchantment)"
```

### Meteor Version

Dev Build 0.5.2 [1.19.3]

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
if the issue is a crash you should post the damn crash report
