### ISSUE TITLE
Minecraft launching normaly without any meteor client modifications.

### ISSUE THREAD

**Issue by Mattem300** [MeteorDevelopment/meteor-client#3164]
### Describe the bug

After launching the game it will not run with the meteor client modifications. This happens to me on Minecraft 1.19.2.
When you try doing it again it will not load any of the modifications even when retrying the install process. When you look into the log there is some messages about the error

### Steps to reproduce

```bash
By launching the game.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/qkaB0H8

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
meteor isnt present in your log file. Can you double check to make sure you actually have it in the correct folder

**Comment by DesiCow** [comment]
T-Launcher ☠️

**Comment by Wide-Cat** [comment]
try reading https://meteorclient.com/faq/installation next time
