### ISSUE TITLE
Conflict with Wurst Client 7.30 or later

### ISSUE THREAD

**Issue by IF-desu** [MeteorDevelopment/meteor-client#3165]
### Describe the bug

MC version 1.19.2
Meteor version 0.5.1
Fabric version 0.14.11
Log:
[Uploading Crash report.zip…]()

### Steps to reproduce

```bash
1.install both Meteor client 0.5.1 for 1.19.2 and Wurst client 7.30 or later(If installed 7.29 or before game will not crash)
2.Launch game
3.Game Crashed
```

### Link to crash report/log if applicable (https://mclo.gs)

I uploaded the log in this page

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
[meteor is incompatible with wurst](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/resources/fabric.mod.json#L49-L54)
