### ISSUE TITLE
NCP bypass

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#3166]
### Describe the feature

make bypass for ncp for elytra fly, entity speed, and crystal aura thru wall.
I understand meteor is not for "hacking", but it would be nice that meteor can bypass anticheat of anarchy servers, I was getting my ass kicked by 1.12.2 client users in crystal pvp because meteor crystal aura can't bypass anticheat and place crystal thru wall.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by OLEPOSSU** [comment]
ncp is basically impossible to bypass

**Comment by qeqeqeplayer533** [comment]
future client has bypass for it

**Comment by RacoonDog** [comment]
Meteor does not bypass

**Comment by I-Got-You-Dead** [comment]
> future client has bypass for it

Then use future

**Comment by Mathrandom7910** [comment]
> ncp is basically impossible to bypass

real
