### ISSUE TITLE
[Suggestion] Add premium meteor

### ISSUE THREAD

**Issue by hackeduser2403** [MeteorDevelopment/meteor-client#3169]
### Describe the feature

make a premium version of meteor which allows user to inject into meteor, and cosmetics and discord tag. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
> discord tag
already exists for donators

> cosmetics
no

> inject into meteor
like... modify meteor? like addons already do for free?

**Comment by hackeduser2403** [comment]
> > discord tag
> 
> already exists for donators
> 
> > cosmetics
> 
> no
> 
> > inject into meteor
> 
> like... modify meteor? like addons already do for free?

no like make it injectable so people can inject it into lunar, and make the feature only available to donators

**Comment by I-Got-You-Dead** [comment]
Best issue of 2023 right here

**Comment by GreemDev** [comment]
yeah this is pretty funny

**Comment by hackeduser2403** [comment]
i know right, but i’m serious tho. i own vape client but they are never gonna make it 1.19

**Comment by hackeduser2403** [comment]
so i really want a injectable client for 1.19

**Comment by I-Got-You-Dead** [comment]
Meteor is an anarchy client

**Comment by I-Got-You-Dead** [comment]
Developed in fabric

**Comment by hackeduser2403** [comment]
yea but do u feel like meteor donator perk is way too common, make it lunar injectable

**Comment by I-Got-You-Dead** [comment]
I can tell you right now that the devs aren’t gonna rewrite their entire client just for some 14 year old wannabe hacker

**Comment by hackeduser2403** [comment]
tf it is developed in fabric??

**Comment by hackeduser2403** [comment]
nvm then

**Comment by I-Got-You-Dead** [comment]
If you want an injectable client use cape if you have it smh

**Comment by GreemDev** [comment]
bro didn't even look at the project for a damn second, jesus

**Comment by I-Got-You-Dead** [comment]
> bro didn't even look at the project for a damn second, jesus

FR

**Comment by hackeduser2403** [comment]
yes but vape only support 1.12 1.8 and 1.7

**Comment by I-Got-You-Dead** [comment]
Skill issue

**Comment by hackeduser2403** [comment]
> bro didn't even look at the project for a damn second, jesus

who even look at that shet

**Comment by GreemDev** [comment]
You are on github.

**Comment by I-Got-You-Dead** [comment]
Anyone with common sense

**Comment by I-Got-You-Dead** [comment]
Also another dumb thing is that you want to pay for an open source project 💀
