### ISSUE TITLE
need baritone's issues url

### ISSUE THREAD

**Issue by 8MiYile** [MeteorDevelopment/meteor-client#3172]
### Describe the feature

I would like to ask you where to submit an issue regarding Baritone's bugs or suggestions.
or
We suggest you edit [this file](https://github.com/MeteorDevelopment/meteor-client/blob/master/.github/ISSUE_TEMPLATE/config.yml) to add url 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Lovecrafts-Cat** [comment]
I don't see how putting the Baritone discord in there would be of any help.

Can't people just find it by themselves, the same way they found Meteor? 
(That being, browsing the internet)

**Comment by 8MiYile** [comment]
@Lovecrafts-Cat The main thing is that we do not know which side of the baritone module you are using is built

**Comment by Wide-Cat** [comment]
If it's an issue with normal baritone then you're looking for https://github.com/cabaletta/baritone
