### ISSUE TITLE
It says crashed when i load into the game

### ISSUE THREAD

**Issue by pp6942** [MeteorDevelopment/meteor-client#3173]
### Describe the bug

When I press play it just pops up with a crash of the fabric loader

### Steps to reproduce

```bash
By pressing PLay and loading into the game
```

### Link to crash report/log if applicable (https://mclo.gs)

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Meteor Client' (meteor-client) 0.5.2-1751 with mod 'Meteor Client' (meteor-client), any version.
                                                                                                                                                    
       matching version is present: v7.31-MC1.19.3!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Meteor Version

0.5.2 and 0.5.1

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Lovecrafts-Cat** [comment]
Posting a crash log as specified in the FAQ would really help.
Also, did you follow our install guide?

**Comment by pp6942** [comment]
Yes, I did And it still didn't work

**Comment by pp6942** [comment]
I was trying to put it in but it didn't work I will try again

**Comment by I-Got-You-Dead** [comment]
That what she said

**Comment by pp6942** [comment]
lol

**Comment by pp6942** [comment]
i fixed it

**Comment by pp6942** [comment]
not the crash

**Comment by I-Got-You-Dead** [comment]
Well then u didn’t “fix” it

**Comment by pp6942** [comment]
i said not the crash

**Comment by I-Got-You-Dead** [comment]
How about you reread it

**Comment by pp6942** [comment]
ok

**Comment by pp6942** [comment]
so is there a way to fix it

**Comment by ehylo** [comment]
Looks like you have wurst in your mods folder, remove it

**Comment by pp6942** [comment]
oh i did

**Comment by I-Got-You-Dead** [comment]
Average wurst user

**Comment by pp6942** [comment]
I didnt realize

**Comment by pp6942** [comment]
it didn't work

**Comment by pp6942** [comment]
now what

**Comment by X-Y0u** [comment]
i have that same problem
