### ISSUE TITLE
Add new chunk hack

### ISSUE THREAD

**Issue by IF-desu** [MeteorDevelopment/meteor-client#3174]
### Describe the feature

Add new chunk hack to meteor client,that can detecte which chunk is ewly generated

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
1: learn to spell
2: already suggested
3: it’s in meteor rejects
4: it doesn’t even work past 1.12
5: stay in school
