### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by mmmm6666b** [MeteorDevelopment/meteor-client#3175]
### Describe the feature

you should add bedrock miner to the client and enchant cracker

https://www.curseforge.com/minecraft/mc-mods/fabric-bedrock-miner
https://github.com/Earthcomputer/EnchantmentCracker/releases

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ehylo** [comment]
Just use the mods you linked

**Comment by RacoonDog** [comment]
In any case the clientcommands ench cracker is better than the one you linked
