### ISSUE TITLE
Pressing Combat On HUD crashes your game

### ISSUE THREAD

**Issue by xrt1** [MeteorDevelopment/meteor-client#3176]
### Describe the bug

same as above

//critical

this crashes your game after you do this bug 
and it also does it everytime you open the HUD menu

### Steps to reproduce

```bash
open mc and meteor
join server
open menu and open hud
right click and add COMBAT module
uh,, profit?
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/IFditjo

### Meteor Version

0.5.2 DEV BUILD 1730

### Minecraft Version

1.17.30

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Lovecrafts-Cat** [comment]
You are about 20 dev builds behind. Update and see if it crashes again.

**Comment by Wide-Cat** [comment]
this should be resolved as of the latest dev build

**Comment by xrt1** [comment]
okay ill try

**Comment by xrt1** [comment]
> this should be resolved as of the latest dev build

has this been reported in the past?

**Comment by RacoonDog** [comment]
> > this should be resolved as of the latest dev build
> 
> has this been reported in the past?

yes, that's how it was fixed in the latest release
