### ISSUE TITLE
[Suggestion]  Adding an option to log the blocks you find while using Block ESP

### ISSUE THREAD

**Issue by DaivyTheHecker** [MeteorDevelopment/meteor-client#3181]
### Describe the feature

There would be an option in Block ESP to log the block if it's in your Blocks list, it would be like a stash finder but for every block.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Lovecrafts-Cat** [comment]
Could you provide a valid use case?
I can't really see who would use this and why.

**Comment by cqb13** [comment]
i think this would be better in stash finder.
although i dont really see the point for it.

**Comment by DaivyTheHecker** [comment]
> 

Well, for example base hunting.

**Comment by I-Got-You-Dead** [comment]
Use tracers

**Comment by Lovecrafts-Cat** [comment]
> Well, for example base hunting.

I believe stash finder does this job way better than any other possibe module.
It logs storage blocks like chests/furnaces etc. and notifiess you.
![image](https://user-images.githubusercontent.com/52252627/212672095-daa683e1-0cb2-423b-98a7-b33c3c1aaae4.png)

And you can also use traccers to locate common base blocks, like beds or anything else that is not generated naturally.
