### ISSUE TITLE
baritone save throwaway blocks

### ISSUE THREAD

**Issue by friend77657** [MeteorDevelopment/meteor-client#3182]
### Describe the bug

when u rejoin a server all the throwaway blocks in baritone are reset.

### Steps to reproduce

```bash
leave and rejoin a server
```

### Meteor Version

0.52-1751

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Config issue

**Comment by ehylo** [comment]
this isn't the baritone issue tracker
