### ISSUE TITLE
[Suggestion] compatbiltiy with clients 

### ISSUE THREAD

**Issue by Yayyetsysh** [MeteorDevelopment/meteor-client#3183]
### Describe the feature

Make it compatible with clients such as feather or lunar for lower end pc or laptops who struggle to get such fps on normal launcher but still would like to enjoy the meteor experience 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
You are funi

**Comment by GreemDev** [comment]
no

**Comment by RickyTheRacc** [comment]
Bruh

**Comment by tympanicblock61** [comment]
hell nah

**Comment by Wide-Cat** [comment]
💀

**Comment by RacoonDog** [comment]
use https://github.com/Fabulously-Optimized/fabulously-optimized
