### ISSUE TITLE
[Bug] Website bug

### ISSUE THREAD

**Issue by pierrelasse** [MeteorDevelopment/meteor-client#3184]
### Describe the bug

![image](https://user-images.githubusercontent.com/76223390/212681454-29d74dc3-57ed-4011-b24b-691c99838628.png)
![image](https://user-images.githubusercontent.com/76223390/212681488-8e0906ff-5ded-4368-bfdb-d15ab9f35152.png)
That should explain all

"This is a valid bug (I am able to reproduce this on the latest dev build). *" i cant really check that but ye

### Steps to reproduce

```bash
Visit https://meteorclient.com/
```

### Meteor Version

no

### Minecraft Version

no

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by pierrelasse** [comment]
This here was

**Comment by ehylo** [comment]
report this to the [meteor-website](https://github.com/MeteorDevelopment/meteor-website/issues) issues page
