### ISSUE TITLE
auto gap

### ISSUE THREAD

**Issue by friend77657** [MeteorDevelopment/meteor-client#3188]
### Describe the bug

when auto gap is enabled and health slider was put to 6, when my hp dipped below 6 it did not gap (normal gaps not enchanted)

### Steps to reproduce

```bash
turn on auto gap set health slider to any value and it will not gap
```

### Meteor Version

0.52-1753

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by qeqeqeplayer533** [comment]
first
