### ISSUE TITLE
[Swarm] Couldn't start a server on port 420

### ISSUE THREAD

**Issue by maplepy** [MeteorDevelopment/meteor-client#3200]
### Describe the bug

Server won't create on any port

### Steps to reproduce

```bash
Launch the game
Enable swarm
Click start
```

### Meteor Version

0.5.2 1753

### Minecraft Version

https://mclo.gs/X5pe4sn

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
you do not have permission

**Comment by maplepy** [comment]
Yep, just realised we need to use ports above 1024 on Linux or need a special command to run it, or sudo but I wouldnt use sudo on minecraft
