### ISSUE TITLE
Anticheat Bypass

### ISSUE THREAD

**Issue by petruliviuadetu** [MeteorDevelopment/meteor-client#3203]
### Describe the feature

Please add an anticheat bypass. Everytime i try to bypass an anticheat , i can't. Please add it.

#replying 

- I need to bypass jartex , chickencraft , much more server that i need to bypass 💀

**Comment by petruliviuadetu** [comment]
If it already exits , please tell me how.

**Comment by GreemDev** [comment]
don't use meteor on servers where it's not allowed

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by StaidChannel708** [comment]
whats the problem it already bypasses hypixel watchdog

**Comment by OLEPOSSU** [comment]
ye the antihunger is perfect on hypixel

**Comment by petruliviuadetu** [comment]
I need to bypass on 6b6t.org and jartex and more.

**Comment by petruliviuadetu** [comment]
What server can it bypass? ( i know hypixel)

**Comment by I-Got-You-Dead** [comment]
It bypasses Vulcan anticheat

**Comment by I-Got-You-Dead** [comment]
If you use .gamemode you can change your gamemode to creative without op

**Comment by I-Got-You-Dead** [comment]
So you can grief hypixel

**Comment by DesiCow** [comment]
^
You can also use allah-hack addon for the `.force-op` command, currently works on most of the 1.8.9 servers.

**Comment by qeqeqeplayer533** [comment]
at least tell what anticheat to bypass

**Comment by qeqeqeplayer533** [comment]
funny thing is I have config for chickencraft

**Comment by petruliviuadetu** [comment]
How do i bypass anticheats with meteor, what hack from it can disable anticheats

**Comment by I-Got-You-Dead** [comment]
> How do i bypass anticheats with meteor, what hack from it can disable anticheats

Flight and speed
