### ISSUE TITLE
[Bug] Problem about "Auto Tool"

### ISSUE THREAD

**Issue by Ozaxx** [MeteorDevelopment/meteor-client#321]
It changes my tool even when I don't need it. I.e, I have to dig sand, but I don't have a shovel in my inventory. Instead of letting me dig with my hand, it chooses a pickaxe from my inventory and breaks it with it. It wastes its durability unnecessarily.

Or grass, tall grass, flowers, etc. I don't need to use any tools to break this things. Again, auto tool doesn't lets me to do it with my hand.

**Comment by RedCarlos26** [comment]
I can confirm.

**Comment by StormyBytes** [comment]
Just turn off the module?

**Comment by Ozaxx** [comment]
What are you trying to say? Should I assign the module to a key and keep pressing it? 

This is a bug and needs to be fixed.

**Comment by RedCarlos26** [comment]
Yes, but auto tool is meant for using the right item quickly when mining, farming and all that stuff, so this is kind of a fix, but this is still a bug.

**Comment by StormyBytes** [comment]
Does your pickaxe have any enchantments? Because it may affect auto tool.

**Comment by Ozaxx** [comment]
No, my pickaxe, axe or any tool doesn't have any enchs on it.

**Comment by AstroOrbis** [comment]
I think it has a list from fastest to slowest. Pickaxes are normally 2nd on the list when not 1st, so it automatically goes to that. I'll check the code.

**Comment by MineGame159** [comment]
Cannot reproduce on latest commit

**Comment by LEOlaona** [comment]
could not find a usable mending pickaxe？

**Comment by LEOlaona** [comment]
How to close must have precise repair
