### ISSUE TITLE
[Bug] Problem about "Flame Thrower"

### ISSUE THREAD

**Issue by Ozaxx** [MeteorDevelopment/meteor-client#322]
When a entitiy's life is 1, it tries to extinguish in order not to kill entitiy, and at the same time it tries to light a fire because the entitiy has not died yet. This prevents the entitiy's from dying.

**Comment by RedCarlos26** [comment]
Do you have a screen recording so we can see what is the bug in action?

**Comment by Ozaxx** [comment]
https://user-images.githubusercontent.com/69100788/113681285-75de5f80-96ca-11eb-8fe2-dc285498fde1.mp4

**Comment by Ozaxx** [comment]
You can go to 1:05 for the action, sorry for the quality and the length.

**Comment by Ozaxx** [comment]
So, I was trying to recrod the video on Singleplayer, it worked somehow. I guess when I write this issue the server that i'm playing is lagging or something like that.

Closing the issue.
