### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by SOOKSMOOTH** [MeteorDevelopment/meteor-client#3221]
### Describe the feature

Maybe a meteorclient shop that has accesories just like lunar or badlion, i don't know why but its just fancy with like a crown so if its into plans into the future im pleased to buy.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Lovecrafts-Cat** [comment]
That is not only useless, but it would bloat the codebase for no gain.
The goal of meteor is to provide utilities for (mostly) anarchy players, not to be some NFT shop with cosmetics.

**Comment by StaidChannel708** [comment]
this better be a joke
