### ISSUE TITLE
[Suggestion] for Auto Reconnect module

### ISSUE THREAD

**Issue by AAlchemy** [MeteorDevelopment/meteor-client#3222]
### Describe the feature

Auto Reconnect module:
configurable number of times the module will reconnect.
e.g. only reconnect X number of times then self-disable.
(nice for afk'ing servers that reboot once a day, but you really don't want to keep reconnecting if your disconnect reason was autolog trying to save you).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Finally a useful suggestion

**Comment by AAlchemy** [comment]
or just link autolog and auto reconnect. 
if disconnect reason was autolog, dont auto reconnect.

**Comment by Wide-Cat** [comment]
autolog now disables auto reconnect
