### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GoofyBoi420** [MeteorDevelopment/meteor-client#3226]
### Describe the bug

the pickaxe come in first hotbar slot by itself. i try and use .panic but still same thing hapen so it bug i tink

### Steps to reproduce

```bash
get netherite picaxe
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported (I have searched bug reports on GitHub).

- [ ] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
#allowinventory false

**Comment by GoofyBoi420** [comment]
do i type that?

**Comment by GreemDev** [comment]
no you say it out loud

**Comment by GoofyBoi420** [comment]
> no you say it out loud

k thx
