### ISSUE TITLE
Better xray

### ISSUE THREAD

**Issue by JanCantCode** [MeteorDevelopment/meteor-client#3228]
### Describe the feature

Add a setting to xray that only highlights the xray blocks if they are next to fire, lava air or water. most anti xrays dont obfuscate blocks that are "exposed", even when they are underground (i dont have a smarter alternative to this) which would make xray at least a little bit useable on servers that have an anti xray

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Lovecrafts-Cat** [comment]
If the server you're on has an anti-xray what makes you think Meteor as a whole is allowed on it?

**Comment by DesiCow** [comment]
Out of scope for Meteor client however you can use Oresim module from Meteor Rejects addon

**Comment by qeqeqeplayer533** [comment]
turn on check box "exposed only"
