### ISSUE TITLE
1.19.2 Start problem

### ISSUE THREAD

**Issue by Energobro** [MeteorDevelopment/meteor-client#3231]
### Describe the bug

I downloaded the client, put it in the mods folder and writes that the Main class is not loaded
![image](https://user-images.githubusercontent.com/61550676/215255867-0d32c352-22c7-4b64-af25-927d64fe4d47.png)

### Steps to reproduce

```bash
I put it in the mods folder and run my quilt assembly
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Read the faq

**Comment by I-Got-You-Dead** [comment]
Meteor isn’t made for quilt

**Comment by Energobro** [comment]
But the majority are switching to it, why is that?

**Comment by I-Got-You-Dead** [comment]
Tbh I haven’t seen one person who genuinely uses quilt

**Comment by I-Got-You-Dead** [comment]
So cope harder

**Comment by Energobro** [comment]
Well, you need to add support for quilt, why not?

**Comment by I-Got-You-Dead** [comment]
> Well, you need to add support for quilt, why not?

Not how it works

**Comment by I-Got-You-Dead** [comment]
Just use fabric like the faq says bruh

**Comment by I-Got-You-Dead** [comment]
If u use common sense u would know that fabric and quilt are not the same, it’s as simple as that

**Comment by Big-Iron-Cheems** [comment]
As said before in precedently closed issues and in our install guide, Meteor is designed to work on Fabric, not Quilt.
Supporting one of the many forks of Fabric is not in our plans.
You're free to open a PR and implement what's needed to make it compatible if you want.
