### ISSUE TITLE
Distance colors stays on red (Nametags)

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#3235]
### Describe the bug

When you enable the distance color mode for nametags, it stays on red no matter where you move. 

### Steps to reproduce

```bash
Turn on nametags and next to Distance Color Mode choose "gradient"
```

### Meteor Version

meteor-client-0.5.2-1760

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DesiCow** [comment]
:skull:
