### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Diamondhero777** [MeteorDevelopment/meteor-client#3238]
### Describe the bug

I cant use litematic printer, sodium, or open up the creative inventory with this enabled.

### Steps to reproduce

```bash
Whenever litematica printer is supposed to be printing it just crashes me.

run mc 1.19.3 with litematica printer and meteor
then try printing a schematic and it will crash you. It wont even give me a crash report.
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
Bruh

**Comment by ThebestkillerTBK** [comment]
hmm... likely https://github.com/CaffeineMC/sodium-fabric/issues/1486

**Comment by Wide-Cat** [comment]
Open an issue on their repository

**Comment by Diamondhero777** [comment]
I didnt have sodium installed because if I did I couldnt load into a world in the first place
