### ISSUE TITLE
[Suggestion] Add "Show Effects" settings in Name Tags

### ISSUE THREAD

**Issue by StormyBytes** [MeteorDevelopment/meteor-client#324]
Add a setting in NameTags Module to view other player's effects.
Here is a picture from kami blue client to prove that it can be done.
![image](https://user-images.githubusercontent.com/72693226/112074185-4f87d280-8ba8-11eb-9bc4-b2739f55a415.png)

**Comment by ikeafridge4** [comment]
that would take up way too much space. cool idea ig

**Comment by asdffdsdaf** [comment]
would look better on right side from the player model

**Comment by seasnail8169** [comment]
Similar to #797 but 797 is more detailed and should be kept
