### ISSUE TITLE
Crash during game initialization

### ISSUE THREAD

**Issue by Sepruko** [MeteorDevelopment/meteor-client#3240]
### Describe the bug

The game window does show (despite the log saying the window was never opened), however the game crashes shortly afterwards. No mods other than Meteor Client were loaded.

### Steps to reproduce

```bash
Launch the game with Meteor Client loaded.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/efWYiZq

### Meteor Version

0.5.2-1761

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
I'm able to load meteor on quilt completely fine using the release 0.17.10 loader. Try switching from the 0.18 beta to the release.

**Comment by I-Got-You-Dead** [comment]
💀
