### ISSUE TITLE
Antiban

### ISSUE THREAD

**Issue by Octohacker1** [MeteorDevelopment/meteor-client#3242]
### Describe the feature

Anti ban would allow you to not get bookbanned or chunkbanned by either canceling large amounts of packets (like packet canceler) Or you do what you want to do but this would would also allow you to make an chunk ban and turn it on while your still in the chunk. Or simply as an protection from bookbans. Also antipacketkick does not cancel bookbans, At least for me.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
you cant cancel a bookban clientside

**Comment by Octohacker1** [comment]
What about this? https://www.youtube.com/watch?v=ioG7V5Ao1Bo

**Comment by Octohacker1** [comment]
and I mean chunkban

**Comment by Wide-Cat** [comment]
Will investigate later

**Comment by Octohacker1** [comment]
alright thank you.
