### ISSUE TITLE
Add "team" moudle

### ISSUE THREAD

**Issue by IF-desu** [MeteorDevelopment/meteor-client#3246]
### Describe the feature

Add team moudle,that if someone uses the hack"aim assist","kIll aura" and so on,the moudle will ignore players of the same team instead of looking at or beating your teammates

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This is already a thing.
If a player is in your friedns list, modules such as Kill Aura, Crystal Aura etc will ignore them.

To add a player as a friend, you can use the `.friend` command or use the `MiddleClickFriend` module.

**Comment by RacoonDog** [comment]
moudle

**Comment by IF-desu** [comment]
Thanks :)
