### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by TONYMEZ** [MeteorDevelopment/meteor-client#3252]
### Describe the feature

Please for the love of god add piston arua and the crystal aura that places a block above you breaks it then explodes like a anchor idk how these things are not already a thing but please make them happen I ensure you will get positive feedback 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead** [comment]
Laughter at this user

**Comment by TONYMEZ** [comment]
> Laugh at this user
What piston arua is a fundamental hack

**Comment by serainox420** [comment]
Piston aura? Bruh, change your dealer.

Bucket aura from other hand should be a thing.
lava bucket aura against most entities, water bucket aura for endermen on on burning player / or self extinguish.
