### ISSUE TITLE
[BUG] Game crashes when inventory is opened in a creative singleplayer world.

### ISSUE THREAD

**Issue by Hamude995** [MeteorDevelopment/meteor-client#3262]
### Describe the bug

When I open a singleplayer creative world and I open my inventory.

### Steps to reproduce

```bash
You open your inventory on a singleplayer creative world.
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
attach a crash report

**Comment by Hamude995** [comment]
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/10560002/latest.log)

**Comment by Big-Iron-Cheems** [comment]
> [latest.log](https://github.com/MeteorDevelopment/meteor-client/files/10560002/latest.log)

This file is clearly incomplete, we need the full log, as explained in our FAQ.

**Comment by Hamude995** [comment]
That's all I have

**Comment by Big-Iron-Cheems** [comment]
Then restart the game, trigger the crash, and send the new log (being sure it's complete from start to crash).

**Comment by Hamude995** [comment]
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/10560155/latest.log)

**Comment by Big-Iron-Cheems** [comment]
Crash caused by Multiconnect, try swapping it with [ViaFabric](https://modrinth.com/mod/viafabric/version/0.4.9%2B24-main).

**Comment by Big-Iron-Cheems** [comment]
No updates after a week, closed for inactivity.
