### ISSUE TITLE
Items taken from creative menu dissapear in survival

### ISSUE THREAD

**Issue by Supercolon1** [MeteorDevelopment/meteor-client#3263]
### Describe the bug

Whenever i enter creative using .gamemode after i go back into survival mode all the loot ive just gotten dissapears from my inventory, am i doing something wrong or does it only work in singleplayer?

### Steps to reproduce

```bash
.
```

### Meteor Version

Latest

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
I thought it would be obvious that if you don't have OP on the server the effect would only be visual.

**Comment by I-Got-You-Dead** [comment]
💀
