### ISSUE TITLE
Hot bar Glitch

### ISSUE THREAD

**Issue by jharrison123** [MeteorDevelopment/meteor-client#327]
When ever I have a pickaxe in my inventory but not in my hot bar the pickaxe immedatly goes into my hotbar wich can get annoying. it is also the same with building blocks as it trys to keep thoes in my hotbar here. this may be a conflict with my other mods wich are baritone, lightmatica, and the litum,sodium, and phospher mods.

**Comment by RedCarlos26** [comment]
Anything else in your mods folder? And also, you probably have a module turned on (like hotbar replenish)

**Comment by Wide-Cat** [comment]
Turn off AllowInventory for Baritone, it automatically moves that stuff to your hotbar

**Comment by MineGame159** [comment]
@jharrison123 Closing this issue because as Wide-Cat said this is Baritone's issue. Aka disable AllowInventory in Baritone and it will stop.
