### ISSUE TITLE
[Bug] minecraft crashes if the esp option on distance is on 

### ISSUE THREAD

**Issue by UnsportedVortex22565** [MeteorDevelopment/meteor-client#3272]
### Describe the bug

minecraft crashed withe potion on distance turned on 

### Steps to reproduce

```bash
go to esp --> press the option distance
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/L0nxk2Z

### Meteor Version

0.5.2 1765 latest dev

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
ah shit defaults aren’t set that’s my bad
