### ISSUE TITLE
Ultimate FreeCam.

### ISSUE THREAD

**Issue by Ebanytiy** [MeteorDevelopment/meteor-client#3277]
### Describe the feature

1. Add horizontal and vertical speed.
2. Freeze player function, when freecam is on(This helps when the player is on the move.)
3. Show freecam coordinates.(today freecam show only player coordinates)
4. Function to disable interaction with the world. (interaction with entity, blocks and other)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by DesiCow** [comment]
3. Wdym? You can use Position text hud preset

**Comment by GoodGolem** [comment]
And y would u not want to interact with blocks and entity? It is the whole purpose of using it in meteor.

**Comment by GoodGolem** [comment]
No offences
