### ISSUE TITLE
Command color won't display when using Caxton

### ISSUE THREAD

**Issue by hexadecimal233** [MeteorDevelopment/meteor-client#3283]
### Describe the bug

The number would be red but it is white.
Expected: 
![image](https://user-images.githubusercontent.com/62250232/216599557-3382f815-38b3-47b6-8191-cc321ab6abbc.png)
Actual:
![image](https://user-images.githubusercontent.com/62250232/216599581-c88200fd-eded-46ca-a065-e06de2b878ac.png)

Already repoted in [Caxton's issue](https://gitlab.com/Kyarei/caxton/-/issues/28)

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
No one expects it to be red, maybe wurst users but that’s it??

**Comment by I-Got-You-Dead** [comment]
Much cleaner if it’s just left white

**Comment by ThebestkillerTBK** [comment]
> Much cleaner if it’s just left white

then use wurst

**Comment by bluebear94** [comment]
I think what @ThebestkillerTBK means is that the text is highlighted when Caxton is not installed, and the lack of highlighting when Caxton is installed is a bug.

**Comment by hexadecimal233** [comment]
Closing this because it's caxton side issue
