### ISSUE TITLE
[SUGGESTION] Block Selection; One side setting

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#330]
**Describe the feature**
Only render the block highlight lines on the side the player is looking at.

**Screenshots**
Instead of rendering all the grey lines, only render the ones highlighted in red.
![28png24-03-2021](https://user-images.githubusercontent.com/67818307/112292974-b8c13000-8ce5-11eb-986a-7c2d2a6bbbc3.png)

**Additional info**
This would also work with Fill setting, and only fill the side that the cursor is hovering over.

**Comment by RedCarlos26** [comment]
Personally I don't see the interest. What do you think @seasnail8169 ?

**Comment by seasnail8169** [comment]
I dont completely hate it.

**Comment by MineGame159** [comment]
Added
