### ISSUE TITLE
Killaura random teleport (TP aura)

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#3300]
### Describe the feature

I think this setting was previously in the client but was removed in the latest build?
Is it possible to re-add it?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ThebestkillerTBK** [comment]
removed in "improvements" 8722ef5
ironic

**Comment by Wide-Cat** [comment]
this is unlikely to be added back

**Comment by Wide-Cat** [comment]
its because meteor is primarily designed to be used on anarchy servers, and in those environments the random tp setting will more often than not just not work whatsoever

**Comment by ThebestkillerTBK** [comment]
If you want to use TPaura, use rejects instead

**Comment by ThebestkillerTBK** [comment]
> > If you want to use TPaura, use rejects instead
> 
> I use it and It doesn't include TPaura.

This will be added soon
