### ISSUE TITLE
AutoLeave when below specific hearts

### ISSUE THREAD

**Issue by Squidom** [MeteorDevelopment/meteor-client#3303]
### Describe the feature

Disconnects when the player is below an amount "X" of health.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This is already a module within Meteor.
Look for Auto Log.
