### ISSUE TITLE
Insta Mine is gone in 0.5.2

### ISSUE THREAD

**Issue by sphings79** [MeteorDevelopment/meteor-client#3308]
### Describe the bug

Insta Mine is missing in 0.5.2

### Steps to reproduce

```bash
just use 0.5.2-1780
```

### Meteor Version

0.5.2-1780

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead** [comment]
How tf is this a bug?
