### ISSUE TITLE
Smooth rotate for specific modules

### ISSUE THREAD

**Issue by cakarlen** [MeteorDevelopment/meteor-client#3310]
### Describe the feature

When using something like KillAura or InstaMine, there are options to rotate the player server-side. In some cases, a player may want to smooth out their rotations to make it seem more legit to other players. This option would help smooth server/client-side rotations.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ThebestkillerTBK** [comment]
use aim assist ig

**Comment by arlomcwalter** [comment]
or just don't cheat
