### ISSUE TITLE
player.pos.y and player.pos.z in starscript is switched

### ISSUE THREAD

**Issue by sumone-lol** [MeteorDevelopment/meteor-client#3314]
### Describe the bug

The `player.pos.y` and `player.pos.z` in starscript are switched around. y gives the value of z and vice versa. Thats just it... somehow found it.

### Steps to reproduce

```bash
1. Edit the hud
2. Add empty text
3. Input {player.pos.y} into text
4. It shows the z position instead of y
```

### Meteor Version

1781

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
cant reproduce

**Comment by sumone-lol** [comment]
https://www.youtube.com/watch?v=WELhBpvyQIk

**Comment by ThebestkillerTBK** [comment]
Do you have any other mods installed

**Comment by sumone-lol** [comment]
Yes, not sure that it would interact with it though. I just have some fps mods like sodium, lithium, or starlight and a few mods that don't mess with coordinates or anything. I do have the Meteor rejects and Villager roller addons though. If you need a full list, then here I guess:

- Alternate Current
- Carpet Mod
- Cloth Config v9
- Concurrent Chunk Management Engine
- Dynamic FPS
- Fabric API
- Fabrishot
- Ferritecore
- Indium
- Iris
- Krypton
- LazyDFU
- Litematica
- Lithium
- MaLiLib
- Memory Leak Fix
- Meteor Client
- Meteor Rejects
- Meteor Villager Roller
- Mod Menu
- Mouse Wheelie
- Reese's Sodium Options
- Replay Mod
- Sodium
- Sodium Extra
- Starlight
- YetAnotherConfigLib

**Comment by ThebestkillerTBK** [comment]
can reproduce, strange issue

**Comment by RacoonDog** [comment]
> https://www.youtube.com/watch?v=WELhBpvyQIk

It’s working perfectly, `y` is vertical, `x` & `z` are horizontal

**Comment by ThebestkillerTBK** [comment]
> > https://www.youtube.com/watch?v=WELhBpvyQIk
> 
> It’s working perfectly, `y` is vertical, `x` & `z` are horizontal

But I can reproduc this issue on the latest build

**Comment by sumone-lol** [comment]
......
Forgot about the changed coordinate system in minecraft. I use 3d modelling applications like blender and in those, `x` and `y` are  horizontal and `z` is vertical. That confusion was all on me lmao I need more sleep
