### ISSUE TITLE
[Suggestion] change inf miner OR add a new module

### ISSUE THREAD

**Issue by PixelThiefy** [MeteorDevelopment/meteor-client#3317]
### Describe the feature

okay so, as the title says, change inf miner OR add a new module to have a option to target wood/trees as well as add a target tool type (the tool the module looks for and uses once toggled) i think theres a lot of players that just want some wood but don't want to have to be there to chop it, perhaps not the best or most useful idea anybody has suggested but it may be for the people who want it.
![9ea002d64d723ad7a437e145a479c8e2](https://user-images.githubusercontent.com/124656809/217162402-810b2dbc-4e84-4d4f-a781-e7acde443ac0.png)
^^^ obviously under this category so it's the same that inf miner is

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ThebestkillerTBK** [comment]
#mine oak_log

**Comment by Big-Iron-Cheems** [comment]
As suggested, use Baritone's mine command instead.
