### ISSUE TITLE
Crash on use storage esp

### ISSUE THREAD

**Issue by NegroFighter69420** [MeteorDevelopment/meteor-client#3319]
### Describe the bug

playing on a mc server, flying around, found a village, turned on storage esp, crash

### Steps to reproduce

```bash
1. fly around
2. find village
3. turn on storage esp
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/rjHYXQi https://mclo.gs/fpDMdyi

### Meteor Version

0.5.2-1780

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
update to the latest dev build and try again

**Comment by ThebestkillerTBK** [comment]
Yes it still crash

**Comment by ThebestkillerTBK** [comment]
mimgam: Mostly fixed sodium 0.4.9 compatibility
