### ISSUE TITLE
Crash on update to latest version

### ISSUE THREAD

**Issue by NegroFighter69420** [MeteorDevelopment/meteor-client#3320]
### Describe the bug

just updated to latest version and still crash

### Steps to reproduce

```bash
update to latest version
crash
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/dv0VnIb

### Meteor Version

latest build

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Try with Sodium 0.4.8 and see if it crashes.

**Comment by rekayno** [comment]
storage-esp causes a crash, I have same problem, just disable it

**Comment by rekayno** [comment]
[https://images2.imgbox.com/62/f7/pmuzkpE5_o.png](url)

**Comment by NegroFighter69420** [comment]
i will continue to use sodium 0.4.9 is there any way of disabling it?

**Comment by Big-Iron-Cheems** [comment]
> i will continue to use sodium 0.4.9 is there any way of disabling storage esp?

Disable Storage ESP? Open the module list in the main menu and turn it off.

**Comment by NegroFighter69420** [comment]
> > i will continue to use sodium 0.4.9 is there any way of disabling storage esp?
> 
> Disable Storage ESP? Open the module list in the main menu and turn it off.

i cant since it crashes when i start mc
https://mclo.gs/jI5Oz9E

**Comment by Big-Iron-Cheems** [comment]
Disable Sodium, enter the game, disable the module, re-enable sodium.

**Comment by NegroFighter69420** [comment]
ok ok ty

> Disable Sodium, enter the game, disable the module, re-enable Sodium.
