### ISSUE TITLE
The weird sneaking bug appears again

### ISSUE THREAD

**Issue by Fiz-Vector** [MeteorDevelopment/meteor-client#3324]
### Describe the bug

This bug was reported about a month ago, and it appears again when I am playing Minecraft these days

### Steps to reproduce

```bash
Wait and watch it sneak randomly
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
It is not caused by keyboard stuff, because it sneaked when in flight and `inSneakingPose` will set to `false` during flight.

**Comment by NegroFighter69420** [comment]
can confirm, this happened to me

**Comment by staridia** [comment]
It also does that, including when I am in my gui, where it shows my character sneaking

**Comment by MineGame159** [comment]
Fixed in e2854ceb11c621c45d481680af8559c14b992baa.
