### ISSUE TITLE
Xray bug

### ISSUE THREAD

**Issue by IDEMANYA** [MeteorDevelopment/meteor-client#3327]
### Describe the bug

Whenever i try to use xray, it reloads my chunks and nothing else, the xray desnt work, does anyone have a solution?

### Steps to reproduce

```bash
i press my xray key (x)
```

### Meteor Version

1.19.3

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
use 1780 for sodium 0.4.8 and 1781 for 0.4.9

**Comment by IDEMANYA** [comment]
i did it only works when i put my opacity to 0

**Comment by ThebestkillerTBK** [comment]
What is your meteor and sodium version?

**Comment by SolacianAllie** [comment]
i have the same issue, discovered it when updating stuff to 1.19.3, i originally thaught it was ViveCraft that caused my issues but its not
