### ISSUE TITLE
Bug/Issue with zoom and chat.

### ISSUE THREAD

**Issue by Neuxs0** [MeteorDevelopment/meteor-client#3328]
### Describe the bug

When pressing the keybind for zoom ( Which I have as c ) with the chat open then immediately closing chat fast it'll toggle zoom as being on and pressing the keybind for zoom reverts it back to normal. You can only get out of it when opening chat or pressing esc.

### Steps to reproduce

```bash
Open chat, press the zoom keybind then immediately exit chat.
```

### Meteor Version

v0.5.2-1781

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Unable to replicate. Probably fixed in c51867e02768d60f172893d49272687e43e6b35b
