### ISSUE TITLE
[Suggestion] Make profiles and macros stay through updates

### ISSUE THREAD

**Issue by Neuxs0** [MeteorDevelopment/meteor-client#3330]
### Describe the feature

It is awfully annoying every time to get a new dev build update just too see that every last bit of my macros AND profiles completely removed from existence. Please add something that'll keep the macros and profiles between updates, it is very annoying to us people who actually use them.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by arlomcwalter** [comment]
dev builds very rarely contain breaking changes to config formats

if your configs are breaking every time you change dev build, you are doing something seriously wrong
