### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by tw1stt** [MeteorDevelopment/meteor-client#3333]
### Describe the feature

adding connectivity with optifine

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We will not support OptiFine, or OptiFabric.
They are only a surce of painful compatibility.
Look [here](https://lambdaurora.dev/optifine_alternatives/) for alternatives that you should actuallybe using on Fabric.
