### ISSUE TITLE
[Bug] BetterChat's "Infinite Chat Box" option does not work.

### ISSUE THREAD

**Issue by KadTheHunter** [MeteorDevelopment/meteor-client#3335]
### Describe the bug

The "Infinite Chat Box" option does nothing when enabled in the BetterChat module. 

Some additional notes:
On my main 1.19.3 instance (with other mods), I can't type or paste long messages without them getting stopped/cut off.
In a new 1.19.3 instance with only Meteor Client 0.5.2 1781, I can type or paste long messages, but when I hit enter they get cut off.

### Steps to reproduce

```bash
- Enable BetterChat
- Check "Infinite Chat Box" within BetterChat
- Try sending a really long message, or pasting sizable NBT with `.nbt set`
- Fail, because the chat box isn't infinite or even extended at all
```

### Meteor Version

0.5.2 1781

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
working as intended, the chat box was successfully extended, but we cannot extend how many characters the server is willing to accept

**Comment by KadTheHunter** [comment]
> but we cannot extend how many characters the server is willing to accept

So did something change in newer versions of meteor? In 0.5.0 I could (and still can) use Infinite Chat Box with no issues, pasting equally long and even longer messages, and having them sent.

Also, why even have Infinite Chat Box, if it doesn't send past the char limit?

**Comment by KadTheHunter** [comment]
Ok, to eat my own words, I just tried on my old 1.19 instance, and I couldn't send messages _**BUT**_ I could paste large amounts of nbt with `.nbt set`.

Can no longer do that in 0.5.2.... is there some setting I'm missing?

**Comment by KadTheHunter** [comment]
Closing this, will re-open a new issue specifically for the `.nbt set` bug.
