### ISSUE TITLE
[Suggestion] Multitask

### ISSUE THREAD

**Issue by ManInMyVan** [MeteorDevelopment/meteor-client#3336]
### Describe the feature

Add a module that allows you to attack & break blocks while blocking with a shield, eating/drinking, charging a bow/crossbow/trident, etc

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
Who said I'm using it on an anarchy server?

**Comment by GoofyBoi420** [comment]
i have it

**Comment by GoofyBoi420** [comment]
its called multitask, idk if its a meteor thing or an addon

**Comment by GoofyBoi420** [comment]
no anarchy??????????? meteor isnt supposed to be used in servers where they dont allow hacking

**Comment by ManInMyVan** [comment]
> no anarchy??????????? meteor isnt supposed to be used in servers where they dont allow hacking

"anarchy servers with an anticheat"

**Comment by ManInMyVan** [comment]
> its called multitask, idk if its a meteor thing or an addon

It's an addon

**Comment by GoofyBoi420** [comment]
> > no anarchy??????????? meteor isnt supposed to be used in servers where they dont allow hacking
> 
> > Who said I'm using it on an anarchy server with an anticheat?
> 
> Where does it say I'm using it on non anarchy servers?

your mom

**Comment by ManInMyVan** [comment]
> > > no anarchy??????????? meteor isnt supposed to be used in servers where they dont allow hacking
> > 
> > > Who said I'm using it on an anarchy server with an anticheat?
> > 
> > Where does it say I'm using it on non anarchy servers?
> 
> your mom
> 

...
