### ISSUE TITLE
[Suggestion] Add a multiplace option for crystal aura

### ISSUE THREAD

**Issue by GoodGolem** [MeteorDevelopment/meteor-client#3338]
### Describe the feature

The multiplace feature or option enables the user/client to place multiple crystals around a player making crystal aura more lethal and increases crystal aura's configurablelity.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RickyTheRacc** [comment]
Maybe the dumbest suggestion I've seen related to crystal aura, if one entity explodes multiple other entities only the one will do damage. This would just waste crystals and make you do less dps

**Comment by Big-Iron-Cheems** [comment]
Couldn't have said it better.
