### ISSUE TITLE
[Suggestion] Strafe

### ISSUE THREAD

**Issue by 1MinRamen** [MeteorDevelopment/meteor-client#334]
**Describe the feature**
The strafe feature would allow you to move side to side without the effect of momentum. This would make it easier to run and travel through the bedrock floor at anarchy server spawns. There is usually no delay and it works in a way to make the player move farther than usual.

**Screenshots**
I don't have screenshots since it is a movement-type hack.

**Additional info**
Some settings that are in it are the type of strafe. EX: Target strafe, speed strafe, vanilla, stuff like that ig.

**Comment by seasnail8169** [comment]
Strafe == NCP speed
