### ISSUE TITLE
Inventory steal and dump buttons are in the wrong location 

### ISSUE THREAD

**Issue by moofter** [MeteorDevelopment/meteor-client#3340]
### Describe the bug

This happened somewhere after version 1750. I assume an hope this is a bug and not a design change.

The old:
![old](https://user-images.githubusercontent.com/49481771/218325823-bd9ed469-9806-4e0c-a35b-f8211c938e83.png)

The new:
![new](https://user-images.githubusercontent.com/49481771/218325839-31641165-7848-40ba-8b30-edf583d21488.png)

Please fix, thank you!

### Steps to reproduce

```bash
- Cleanly install the latest build in the stock launcher or a launcher of your choice
- Enable inventory tweaks
- Open a chest
```

### Meteor Version

1781

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DesiCow** [comment]
Feature

**Comment by moofter** [comment]
Seriously this is how it's going to be? This is a big step back in ux design and usability. I always complimented Meteor on the ux design but if this is the way the client is going forward, oh well.

**Comment by Wide-Cat** [comment]
I don't remember if this was an intentional change or not but I agree that it looks worse now

**Comment by GoofyBoi420** [comment]
use minimized screen :(

**Comment by moofter** [comment]
Over 6 months and still this issue is not closed. Amazing. Guess whomever still codes for this client doesn't care the steal/dump buttons are floating somewhere halfway the screen whilst they were always tucked away nicely into the gui. 

6 fucking months for a small graphical fix. Smh.

**Comment by Fiz-Victor** [comment]
There is an pr for this and existed for 6 months. still open.

**Comment by Big-Iron-Cheems** [comment]
Are you referencing #3949 by any chance?
If so, I'll try andd press someone to take a look at it, and if all's ok hopefully it'll be merged.

**Comment by Fiz-Victor** [comment]
> Are you referencing #3949 by any chance? If so, I'll try and press someone to take a look at it, and if all's ok hopefully it'll be merged.
> 
> Update: @Fiz-Victor why are there so many seemingly unrelated changes in a PR that would need about 2 classes edited at most? ![image](https://user-images.githubusercontent.com/52252627/263710905-4e4650a1-b779-422a-8a7b-2be87d4c82ff.png)

It was what @DesiCow did, they did a lot of enhancements.

**Comment by Big-Iron-Cheems** [comment]
Ok, I can see that, but the issue is, if the PR's name is about `InvenoryTweaks`, it should not touch unrelated classes.
If he wanted to make more changes, they should have been in another dedicated branch.
