### ISSUE TITLE
Can move while in freecam [SHOULD NOT HAPPEN]

### ISSUE THREAD

**Issue by AdolfRoxler** [MeteorDevelopment/meteor-client#3343]
### Describe the bug

If you sprint while on freecam your character will move.

### Steps to reproduce

```bash
If you press the sprint button your character will move forwards. If you're like me on a one block on freecam and try to sprint to move the freecam faster, you'll fall to your doom because your character will move forward.

PS: I rebound the sprint key if that helps narrow down the issue. I don't recall this happening on previous versions.
```

### Meteor Version

0.5.2 Build 1781

### Minecraft Version

1.19.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead2** [comment]
I call bullshit

**Comment by qeqeqeplayer533** [comment]
why its 2, r u a fake I-GOT-U-DEAD?

**Comment by I-Got-You-Dead2** [comment]
Main got flagged

**Comment by AdolfRoxler** [comment]
https://anonfiles.com/A3ibacaez7/bug_report_zip

**Comment by AdolfRoxler** [comment]
> https://anonfiles.com/A3ibacaez7/bug_report_zip

This is a demonstration

**Comment by thebest9178** [comment]
Couldn't reproduce this even with rebinding sprint

**Comment by AdolfRoxler** [comment]
Fixed in the latest stable version

**Comment by Talhoid** [comment]
why did this take you two months to close
