### ISSUE TITLE
Make infinite chat from Better Chat Infinite again for meteor commands.

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#3346]
### Describe the bug

You can not:

.nbt set [255 characters of nbt]

it cuts off characters when entering this meteor command. This worked in meteor-client-0.5.1-1592 on 1.19.2 and I wish it would still work the latest version, 1.19.3

### Steps to reproduce

```bash
.nbt set [255 characters of nbt]

[Render thread/INFO]: [CHAT] [Meteor] Expected '}' at position 255: ...g1YjMyYjBk<--[HERE]
```

### Meteor Version

meteor-client-0.5.2-1781

### Minecraft Version

1.19.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Texbio** [comment]
the [255 characters of nbt] is 255 characters of nbt; it removes characters after 255 characters which does not allow you to put in 256 characters of nbt (did not count them so its around 255 characters)

**Comment by I-Got-You-Dead2** [comment]
Do you genuinely not know how to look for duplicate issues kid

**Comment by KadTheHunter** [comment]
Same as my issue #3339, but glad others are noticing this :)

**Comment by AXDWT** [comment]
im having this problem too
