### ISSUE TITLE
[SUGGESTION] Add option to change the position and the font of the chat

### ISSUE THREAD

**Issue by liadinon** [MeteorDevelopment/meteor-client#335]
Add option to change the position and the font of the chat through the better chat module. I want to be able to move and change the HUD of the chat.

**Comment by RedCarlos26** [comment]
Changing the font of the chat could be done, but I'm not sure changing its position could be done, because the MC chat has it's own settings.

**Comment by seasnail8169** [comment]
> Changing the font of the chat could be done, but I'm not sure changing its position could be done, because the MC chat has it's own settings.

I think it can, i have a plan for this in the future.

**Comment by RedCarlos26** [comment]
Good

**Comment by RedCarlos26** [comment]
This issue can be merged with #340.

**Comment by seasnail8169** [comment]
Agreed
