### ISSUE TITLE
"Ghost Hand" RClick Lag

### ISSUE THREAD

**Issue by Pulameso** [MeteorDevelopment/meteor-client#3353]
### Describe the bug

When the "Ghost Hand" module is active, pressing or holding right click causes the fps to drop to zero.

https://user-images.githubusercontent.com/50774671/219844269-534f7ec2-2050-4ee0-bf5c-f2d2ca1b07d1.mp4
I don't think you really need a video, but here you go.

### Steps to reproduce

```bash
Step 1. Toggle "Ghost Hand" module on
Step 2. Right Click
Step 3. Massive lag :(
```

### Meteor Version

v0.5.2 build #1781

### Minecraft Version

fabric-loader-0.14.12-1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
horrible code ngl
