### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TheCrazyLion** [MeteorDevelopment/meteor-client#3356]
### Describe the bug

i enabled storage esp and crashed game. will keep crashing when trying to reopen the game

### Steps to reproduce

```bash
when i enabled storage ESP it instantly crashed the game
```

### Link to crash report/log if applicable (https://mclo.gs)

https://justpaste.it/cx4sp

### Meteor Version

1.19.3

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DesiCow** [comment]
Delete `modules.nbt` in `.minecraft/meteor-client` folder to launch your game again

**Comment by I-Got-You-Dead2** [comment]
> Delete `modules.nbt` in `.minecraft/meteor-client` folder to launch your game again

U don’t even need to do that, just open the gui in the main menu and disable it
