### ISSUE TITLE
[Suggestion] Swarm antilag/boostfps

### ISSUE THREAD

**Issue by Lipuidator** [MeteorDevelopment/meteor-client#3366]
### Describe the feature

Usage: ".swarm antilag [on/off]"

Reduces all visual effects not necessary for bot function, such as texture rendering, entity rendering, etc

This can boost performance when running multiple workers locally

*Or there can just be an antilag module that does this

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
just enable UnfocusedCPU
