### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by PotatoMan4642** [MeteorDevelopment/meteor-client#3368]
### Describe the bug

I was fixing my gui size and made it to big how can i make it smaller 

### Steps to reproduce

```bash
Editing gui to big
```

### Meteor Version

1.19.3

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Use the `.reset gui` command.
