### ISSUE TITLE
[Suggestion] Mod versions

### ISSUE THREAD

**Issue by Francikiller** [MeteorDevelopment/meteor-client#3373]
### Describe the feature

It would be great to have the ability to download older versions of the mod even if outdated and with no updates, it does not seem like a very hard thing to do to just have a "Outdated" sections with older versions of the mod

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
You're free to compile and build the version you want from the Git history.
But, by our chocie, we will never openly distribute pre-built outdated versions of Meteor on our website's download page.

As stated in the [FAQ](https://meteorclient.com/faq), you can also download ViaFabric or Multiconnect to be able to join older servers while using the latest versions of Meteor on the latest version of Minecarft.

**Comment by ManInMyVan** [comment]
[https://maven.meteordev.org](https://maven.meteordev.org)
