### ISSUE TITLE
storage  Esp

### ISSUE THREAD

**Issue by easyloo** [MeteorDevelopment/meteor-client#3374]
### Describe the bug

toggling storage Esp couses minecraft to crash on any server

### Steps to reproduce

```bash
toggle storage Esp
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/SMIXzAU

### Meteor Version

Dev Build: 1784

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
already reported in earlier ones
