### ISSUE TITLE
I can see invisible players.

### ISSUE THREAD

**Issue by Ebanytiy** [MeteorDevelopment/meteor-client#3375]
### Describe the bug

I can see invisible players.
![2023-02-25_17 52 54](https://user-images.githubusercontent.com/87265332/221363940-d9dcbd25-b02e-41f3-a39f-5093d08aca02.png)

### Steps to reproduce

```bash
Go to the server where there is a player under the invisibility potion.
```

### Meteor Version

meteor-client-0.5.2-1784

### Minecraft Version

fabric-loader-0.14.16-1.19.3 fabric-api-0.75.1+1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ThebestkillerTBK** [comment]
no render configuration

**Comment by Ebanytiy** [comment]
no
