### ISSUE TITLE
[Suggestion] scaffold telly bridge mode

### ISSUE THREAD

**Issue by Tui-Vao** [MeteorDevelopment/meteor-client#3378]
### Describe the feature

![6546467435646556567765](https://user-images.githubusercontent.com/75277342/221397732-a654c9a4-2bc8-4c02-9640-eca7ff4bfa45.gif)
like this gif
sprint forward jump look back place blocks while moving backwards while spamming blocks.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead2** [comment]
Don’t use meteor where it’s not allowed

**Comment by ItzSkyReed** [comment]
Skywarsers..

**Comment by hackeduser2403** [comment]
use vape v4. scaffold module, telly bridge mode.

**Comment by qeqeqeplayer533** [comment]
it is just a sprint jump scaffold, but if rotation is turned on, scaffold can only place 10 blocks per second and will fail when using it diagonoly

**Comment by qeqeqeplayer533** [comment]
use speed + timer + scaffold to move faster.

**Comment by ToxicGamingGithub** [comment]
> use vape v4. scaffold module, telly bridge mode.

Who has money im broke 😐

**Comment by GoofyBoi420** [comment]
just use air place and do the movements 😐
