### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by cosniecosumiem** [MeteorDevelopment/meteor-client#3380]
### Describe the feature

adding it to work on feather client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by StaidChannel708** [comment]
jump off a cliff

**Comment by Big-Iron-Cheems** [comment]
Feather is closed source, this means we cannot extrapolate what are its incompatibilities with Meteor.
In addition, we do not wish to support a launcher that is known to have stolen code form open source mods without mentioning them anywhere.

TL;DR: we'll never work towards compatibility with Feather.
