### ISSUE TITLE
[Suggestion]  better ghost hand

### ISSUE THREAD

**Issue by Woutt** [MeteorDevelopment/meteor-client#3382]
### Describe the feature

Ghost hand only works works for chests, so can you make it that it can click traders too. thanks

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GoofyBoi420** [comment]
just use freecam
