### ISSUE TITLE
[Bug] x-ray doesnt work properly

### ISSUE THREAD

**Issue by MorutosBox** [MeteorDevelopment/meteor-client#3386]
### Describe the bug

basically x-ray on 1.19.3 aint working like 1.19.2 cause it shows only ores when u look through a torch or smth like this, pls look it up

### Steps to reproduce

```bash
just open xray and see urself
```

### Meteor Version

1.19.3

### Minecraft Version

1.19.3

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Works for me. It's probably some other mod causing it.

**Provide your mod list for further analysis.**

**Comment by Moruto1381** [comment]
hi, i only use sodium and sodium extra.

**Comment by Big-Iron-Cheems** [comment]
It could be sodium indeed.
I know for sure version 0.4.8 of sodium has no issues with Meteor, so try that one.

**Comment by stefexec** [comment]
Having similar issues, I suspect the connected textures mod, do you have that installed as well?

**Comment by gauravandkarthikdevelopers** [comment]
is it happening only on specific server's cause few server's have an anti x-ray plugin and some server's have this sort of obfuscate plugin
