### ISSUE TITLE
Can you guys make the handview module into a standalone mod for fabric ?

### ISSUE THREAD

**Issue by bossa98765** [MeteorDevelopment/meteor-client#3388]
### Describe the feature

Just the handview module into a standalone mod. The reason I want this is I love the feature and after using it so much in 6b6t but now when I play other servers that don’t allow clients I can’t use the feature anymore. So if you guys could make it happen or is there a mod like this already can you tell me the name or give me the link to the mod that will be very appreciated. Thanks for your time.

### Before submitting a suggestion

- [ ] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead2** [comment]
Lmfao
