### ISSUE TITLE
[Bug] 1.19.2 Meteor Client Shows Invisible Players

### ISSUE THREAD

**Issue by QuaXXz** [MeteorDevelopment/meteor-client#3389]
### Describe the bug

Even when No Render invisiblity is on invisible players still show as a translucent player, and their nametag shows up. This should not be in the client because there are many other ways to see invisible players, and we don't need to see them all the time. 

### Steps to reproduce

```bash
Load up 1.19.2 and meteor client, go to a server where someone is invisible and you will see their nametag and themselves as a translucent player.
```

### Meteor Version

1.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Starmania** [comment]
Could you help me understanding this please ?
![Screenshot_2023-03-02-21-41-57-117-edit_com android chrome](https://user-images.githubusercontent.com/52313983/222547183-adafee59-e5d9-402d-9c7c-9caa05956a87.jpg)

**Comment by Starmania** [comment]
Just to be sure

**Comment by Ebanytiy** [comment]
this bug works even on the latest version

**Comment by Ebanytiy** [comment]
can confirm
