### ISSUE TITLE
[SUGGESTION] Baritone Disable/Silent Mode

### ISSUE THREAD

**Issue by TrueSlayr** [MeteorDevelopment/meteor-client#339]
**Describe the feature**
A module or option that auto-disables Baritone's prefix/replies in chat or disables it entirely when toggling VanillaSpoof and/or hiding the HUD. Needed to record videos/take screenshots without any issues of accidentally activating Baritone or having it reply in chat.

**Screenshots**
Simple and straightforward idea.

**Additional info**
None.

**Comment by seasnail8169** [comment]
Meteor is an anarchy client, it should not be used on servers which do not allow it.

**Comment by TrueSlayr** [comment]
Understood. Please delete this issue.
