### ISSUE TITLE
Add an updated GUI. Something similar to Vape Client GUI probably!

### ISSUE THREAD

**Issue by Worgle123** [MeteorDevelopment/meteor-client#3390]
### Describe the feature

I currently use Meteor Client, but I am really annoyed with it's visual similarity to soooo many other clients. The Drag and Drop menus could remain in the code, but you would need to turn them back on to get them to appear. 

Vape client has really nailed it's current GUI, (for those of you who don't know GUI stands for graphical user interface) and I think that Meteor could really adopt a lot from it. 

Love to see this, as it would really make this client feel a whole lot more premium!

Thanks!
Worgle123

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ConwellMaraya** [comment]
"for those of you who don't know GUI stands for graphical user interface"  🤓

**Comment by I-Got-You-Dead2** [comment]
You do realise it looks so similar since everyone skids it

**Comment by I-Got-You-Dead2** [comment]
So no, cope

**Comment by Worgle123** [comment]
> You do realise it looks so similar since everyone skids it

What do you mean?
