### ISSUE TITLE
Add variables to meteor

### ISSUE THREAD

**Issue by RORAKUS** [MeteorDevelopment/meteor-client#3392]
### Describe the feature

I suggest adding a variable system to meteor client.
You could use it
a. in starscript with methods `var.get(name)` and `var.set(value)`
b. in commands -- `.var create name type value`; `.var get name`; `.var set name value`; `.var remove name`
c. or (more complicated to implement in code) to bind a variable to a specific module/hud element setting. It would have to have the same type, and there could be two options - when the variable changes, it changes the setting to its value, OR when the setting changes, it changes to variable to its state.

How would this be useful?
For example, I want to create a macro for enabling and disabling peaceful mobs in kill aura. I can use the `.setting` command, but I cannot check in which state it is currently in order to toggle it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Soda5601** [comment]
maybe use jsmacros (but not updated to 1.19.3)

**Comment by RacoonDog** [comment]
`.var create name type` should be replaced with `.var create name value` imo, since type can be inferred from either the default value or the value being set

**Comment by RORAKUS** [comment]
> `.var create name type` should be replaced with `.var create name value` imo, since type can be inferred from either the default value or the value being set

oh right, I completely forgot! I did have `.var create name type value` in my mind, I'm sorry. I'd like to have the type there, because than you can make a string "1" and also you can have suggestions true/false for type boolean.
