### ISSUE TITLE
Add an event system to meteor

### ISSUE THREAD

**Issue by RORAKUS** [MeteorDevelopment/meteor-client#3393]
### Describe the feature

It would be very nice to have an option to execute a command whenever something happens. For example: When a player sends a message "Hello" send a message "Hello" too. Or when a player enters your range, automatically turn on killaura etc...

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Soda5601** [comment]
jsmacros

**Comment by RORAKUS** [comment]
i mean also to register meteor events and execute meteor commands (not sure if jsmacro can do that)

**Comment by I-Got-You-Dead2** [comment]
https://github.com/MeteorDevelopment/orbit

**Comment by I-Got-You-Dead2** [comment]
Now shut up

**Comment by RORAKUS** [comment]
that's is a java library... I know meteor has internal event system, but how do you use that inside jsmacros?

**Comment by I-Got-You-Dead2** [comment]
Learn Java, simple

**Comment by RORAKUS** [comment]
i know java, is jsmacros just java? I thought it has it's own language

**Comment by I-Got-You-Dead2** [comment]
If you know Java then make these suggestions yourself
