### ISSUE TITLE
add auto dtap[Suggestion] 

### ISSUE THREAD

**Issue by Nova3992** [MeteorDevelopment/meteor-client#3394]
### Describe the feature

I think you should add auto dtap, where the client places down obsidion then hits the enemies and auto crystals

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead2** [comment]
Crystal aura dumbass

**Comment by I-Got-You-Dead2** [comment]
Also don’t use meteor where it’s not allowed

**Comment by Nova3992** [comment]
> Also don’t use meteor where it’s not allowed

I mean why not

**Comment by Nova3992** [comment]
> Crystal aura dumbass

also theres no placing obsidion automatically in crystal aura

**Comment by I-Got-You-Dead2** [comment]
Yes there is kid

**Comment by Wide-Cat** [comment]
this is a vanilla cpvp thing isnt it

**Comment by Nova3992** [comment]
> Yes there is kid

there isnt, i checked, theres no option in crystal aura to auto place obsidion or to auto dtap

**Comment by I-Got-You-Dead2** [comment]
“Support”

**Comment by Nova3992** [comment]
> “Support”

support places obsidion??

**Comment by I-Got-You-Dead2** [comment]
nawwwwwwwww bro it places grass blocks
