### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by cheetes** [MeteorDevelopment/meteor-client#3395]
### Describe the feature

Make soo you canmodify and disable modules on multiplayer screen

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead2** [comment]
Do t use meteor where it’s not allowed

**Comment by I-Got-You-Dead2** [comment]
> Dont use meteor where it’s not allowed

**Comment by Wide-Cat** [comment]
you can already open the gui in the main menu 🤦
