### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by IamBlacklisted** [MeteorDevelopment/meteor-client#3397]
### Describe the bug

I can't download meteor for 1.18 on the website, it says page 404 not found.

### Steps to reproduce

```bash
Go to the meteor website then go to FAQ and for release click on the "official website"
```

### Link to crash report/log if applicable (https://mclo.gs)

https://meteorclient.com/download

### Meteor Version

1.18

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Soda5601** [comment]
old version isnt supported

**Comment by IamBlacklisted** [comment]
is there a download though?

**Comment by DesiCow** [comment]
We do not support old versions of Meteor or Minecraft no matter what!
If you want to play on older servers, use ViaFabric or MultiConnect with the latest version of Meteor.
https://modrinth.com/mod/viafabric
https://modrinth.com/mod/multiconnect

**Comment by Big-Iron-Cheems** [comment]
> is there a download though?

It's literally on the [main page](https://meteorclient.com/), scroll down.
![image](https://user-images.githubusercontent.com/52252627/222898342-e3593a18-1919-4f68-a8d9-5273c8d68600.png)
