### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by dejsipiko** [MeteorDevelopment/meteor-client#3401]
### Describe the feature

give back insta break 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Soda5601** [comment]
Insta break is in rejects :trollface:

**Comment by Big-Iron-Cheems** [comment]
Already explained in the [BreakDelay commit](https://github.com/MeteorDevelopment/meteor-client/commit/774ddbe82f234ac112c0747b5fe802c1d96aa435).
