### ISSUE TITLE
[Bug] Freecam and xray don't work at end world on the server.

### ISSUE THREAD

**Issue by LackyHaus** [MeteorDevelopment/meteor-client#3402]
### Describe the bug

Today I noticed this problem, xray or freecam crashed minecraft if I'm **in the end world on the server**. I don't know what other features don't work. Demo video:
https://drive.google.com/file/d/1zmRTjEBl-bIoMlVA-7BqMJVuGmvFSIe1/view?usp=sharing

### Steps to reproduce

```bash
activate freecam/xray in end world on the server.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/VlFLZ1N

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Soda5601** [comment]
Install sodium, they have a workaround for this
