### ISSUE TITLE
Not comabitble with Origins

### ISSUE THREAD

**Issue by HammadAkhtar2** [MeteorDevelopment/meteor-client#3405]
### Describe the bug

The version of metor client 0.5.1 of 1.19.2 is incombatible with mod called Origins fabric.

### Steps to reproduce

```bash
Download the fabric origins mod 1.7.1/1.7.0 for 1.19.2 and download metor client 0.5.1
```

### Link to crash report/log if applicable (https://mclo.gs)

https://user-images.githubusercontent.com/113843421/222956907-b7d7e12e-75af-4b58-ae5f-d883b8f1e096.jpg

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DAMcraft** [comment]
not a bug, meteor is not compatible with origins

**Comment by DAMcraft** [comment]
https://anticope.ml/incompatibilities/

**Comment by headzz06** [comment]
![Screenshot_20230305_113451.jpg](https://user-images.githubusercontent.com/103905611/222958069-7e3cd6d3-09ed-4eca-9bfb-151e84bb5be5.jpg)

**Comment by HammadAkhtar2** [comment]
Any idea how to delete that piece of code to prevent it from interferring with meteor client ?

**Comment by DesiCow** [comment]
> Any idea how to delete that piece of code to prevent it from interferring with meteor client ?

Origins tends to break Meteor mixins, so you won't be able to launch your game either way.
