### ISSUE TITLE
[Suggestion] adding {baritone.eta} to starscript

### ISSUE THREAD

**Issue by UnsportedVortex22565** [MeteorDevelopment/meteor-client#3406]
### Describe the feature

This starscript {baritone.eta} will have two options:
  - {baritone.eta.NextSegment} it tells you when the next segment is in sec and in ticks
  - {baritone.eta.Goal} it tells you how much second are gonna take to reach the goal and in ticks
Here's a image:
![2023-03-05_14 01 42](https://user-images.githubusercontent.com/92231049/222962228-571cb0b7-f3a0-425a-82b3-69780d7ee16d.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by DAMcraft** [comment]
Created PR #3408
