### ISSUE TITLE
TNT Minecart Aura

### ISSUE THREAD

**Issue by Worgle123** [MeteorDevelopment/meteor-client#3409]
### Describe the feature

Just the same as the title. It would simply place a rail, as well as a chosen number of minecarts on it, before shooting it with a flame bow. Maybe it could wait for the player to move X distance away, otherwise, it could only place them.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Mathrandom7910** [comment]
You could only realistically hold 3-4 tnt minecarts. And this would be extremely slow to do, just placing a tnt minecart on an activator rail would be faster. You may as well just use auto crystal or respawn anchor aura.

**Comment by Worgle123** [comment]
> You could only realistically hold 3-4 tnt minecarts. And this would be extremely slow to do, just placing a tnt minecart on an activator rail would be faster. You may as well just use auto crystal or respawn anchor aura.

It would be another request, but would it be possible to also use Minecarts which were within shulkers, or is this not possible?

**Comment by Mathrandom7910** [comment]
you would have to place the shulker then take out the items, so no.

**Comment by Worgle123** [comment]
> you would have to place the shulker box then take out the items, so no.

Would it be difficult to manufacture a system that would quickly place a storage block and restock? If it could be done at about the same speed as chest aura, it could be effective. Especially as with speed-mine, you could almost instant break a shulker box.

My idea was really just that it could detonate a specified amount of minecarts when a key bind was pressed. Not necessarily an automatic system.

**Comment by Mathrandom7910** [comment]
if that were done, then all it would take is one crystal explosion to break the shulker and stop the restock process, and a second to destroy an entire shulker of tnt minecarts.

**Comment by Worgle123** [comment]
> if that were done, then all it would take is one crystal explosion to break the shulker and stop the restock process, and a second to destroy an entire shulker of tnt minecarts.

Sure, but as I said 2 hours ago, the original idea was that it would only place a specified amount, and 1 rail, and it would not be automatic. Only via keybind.

**Comment by Diamondhero777** [comment]
You could just use an autocraft to make more tnt minecarts, make a keybind that makes you restock if you are out or low.  You would need good ping though and anticheats might get upset.

**Comment by Dream23322** [comment]
NoxILon go brrrrrrrrrrrrrrrrrr
