### ISSUE TITLE
[Suggestion]  NUKER needs this

### ISSUE THREAD

**Issue by justin661** [MeteorDevelopment/meteor-client#3411]
### Describe the feature

hello the server im playing has line of sight checks and antinuker. is it possible to add look at block that nuker is mining to bypass the antichair? also veinmine works pretty good for some reason.
if dev can fix it and make it so i can fast mine with nuker like that  im willing to donate, for version 1.19.3
video preview: https://youtu.be/sKP08DNeskk

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead2** [comment]
Don’t use meteor where it’s not allowed

**Comment by Big-Iron-Cheems** [comment]
Meteor is not meant to bypass any sort of anti-cheat software.
We do not endorse its use outside of anarchy servers, and will not implement bypasses of that kind.
