### ISSUE TITLE
[Suggestion] send any packet

### ISSUE THREAD

**Issue by GoofyBoi420** [MeteorDevelopment/meteor-client#3412]
### Describe the feature

to send any packet in any amount

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GoofyBoi420** [comment]
?

**Comment by DAMcraft** [comment]
What do you mean any packet in any amount bruh, packets need to be constructed, you know that?

**Comment by GoofyBoi420** [comment]
i meant only 1️⃣  packet 💯 i forgot you can send only one

**Comment by GoofyBoi420** [comment]
like opposite of packet cancer i mean canceller

**Comment by MineGame159** [comment]
That makes no sense

**Comment by Mathrandom7910** [comment]
i think he wanted to be able to send specific packets by inputting a command.
