### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TehJun0614** [MeteorDevelopment/meteor-client#3417]
### Describe the bug

Some features such as "Nuker", in the "Blacklist" and "Whitelist" selection, I can't search for the block I want to blacklist or whitelist because the block names are all missing, they are all blank, I tried to search blocks name but it didn't show anything. I think all features with "Blacklist" and "Whitelist" also have this kind of bug. I hope to fix it, thanks.

### Steps to reproduce

```bash
I opened "Blacklist" and "Whitelist" and it shown up no names besides the blocks, the blocks icon were shown but the names are all missing.
```

### Link to crash report/log if applicable (https://mclo.gs)

None

### Meteor Version

Dev 1.19.3

### Minecraft Version

Fabric 1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
try disabling the custom font setting in the config menu
