### ISSUE TITLE
Meteor client automatically equips a pickaxe even with auto tool disabled

### ISSUE THREAD

**Issue by johnman69420** [MeteorDevelopment/meteor-client#3419]
### Describe the bug

Whenever I try and put my pickaxe in my inventory, meteor keeps on putting it back in my hotbar

### Steps to reproduce

```bash
No clue
```

### Meteor Version

Dev Build 0.5.2

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
thats a baritone setting, do #allowInventory false

**Comment by johnman69420** [comment]
Thank you
