### ISSUE TITLE
Add .server datapack MassScan

### ISSUE THREAD

**Issue by MSchablinger** [MeteorDevelopment/meteor-client#3422]
### Describe the feature

If this is possible add a command/module to see what datapacks the server uses similar to the .server plugins MassScan

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
is it even possible to see what datapacks the servers using without op or whatever

**Comment by Shrecknt** [comment]
> is it even possible to see what datapacks the servers using without op or whatever

no its not possible without op
the closest you can get is checking the autocomplete results of /trigger
