### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by spazmilk** [MeteorDevelopment/meteor-client#3424]
### Describe the feature

work on compatibility between other clients mainly boze. not sure why newer versions of the game have so much beef between devs but get over it and help your users 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Boze is a closed source paid client.
We have no intention of supporting software which we can't see the source code of.

It's like asking a plumber to fix your pipes without having access to them.
