### ISSUE TITLE
general ping predict

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#3425]
### Describe the feature

a module read ur ping, if ur ping is 200ms, it will predict where all ur targets are 200ms into the future, useful for crystal pvp on high ping.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Shrecknt** [comment]
Unless other players are moving in a completely straight line, I doubt it would be a good idea to try and predict their movement. And if you wanted to do physics checks, it would probably kill performance. Its possible to add, but It wouldn't really help anything, and will be very inaccurate.

**Comment by I-Got-You-Dead2** [comment]
> Unless other players are moving in a completely straight line, I doubt it would be a good idea to try and predict their movement. And if you wanted to do physics checks, it would probably kill performance. Its possible to add, but It wouldn't really help anything, and will be very inaccurate.

Simply get a better cpu
