### ISSUE TITLE
[Bug] Black screen GUI

### ISSUE THREAD

**Issue by AsHFearless** [MeteorDevelopment/meteor-client#343]
When opening the GUI to access the options, I receive a black and blue screen. I have tried uninstalling and reinstalling all of fabric and meteor 3-4 times. The longest I had the GUI open for was 5 seconds 1 time. I’m not sure what else to do.
I am using the most recent version of Minecraft (1.16.5) Newest versions of fabric, and also the 1.16.4-1.16.5 version of meteor.
I do not have any other mods installed. I have removed my other clients and optifine from my mods folder. 

![28249899-EEF3-4251-8C2D-E0D1E4FDB234](https://user-images.githubusercontent.com/81336650/112400534-2c574300-8cce-11eb-899c-8d7c32b77d93.png)

**Comment by RedCarlos26** [comment]
What are your computers specs?

**Comment by AsHFearless** [comment]
4x intel cpu max 2.58 GHZ
Intel HD graphics
8gb ram 
64Bit Operation

would that be why?

**Comment by seasnail8169** [comment]
Please try with the latest dev build. Also what other mods are you running?

**Comment by asdffdsdaf** [comment]
what if intel graphics issue :trollface: could be funny ngl

**Comment by RedCarlos26** [comment]
Idk I do not think this is the issue

**Comment by AsHFearless** [comment]
Nothing, didn’t work

**Comment by AsHFearless** [comment]
Also don’t have anything else installed

**Comment by RedCarlos26** [comment]
Do you still have the same issue with the last est dev build (being 672 as of right now)

**Comment by seasnail8169** [comment]
Just gonna assume this has been fixed given basically everything here has been rewritten since and we are like double that dev builds.
