### ISSUE TITLE
I can neither see the command suggestions nor press tab to autocomplete commands

### ISSUE THREAD

**Issue by Yoshispielt** [MeteorDevelopment/meteor-client#3433]
### Describe the bug

tested it in 1.19.2 release and 1.19.3 latest dev build

### Steps to reproduce

```bash
Idk i just used meteor and couldnt see it
```

### Meteor Version

0.5.1+0.5.2

### Minecraft Version

1.19.2+1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DesiCow** [comment]
Please send the latest.log file. You may refer to following tutorial on obtaining the logs: 
https://meteorclient.com/faq/getting-log
