### ISSUE TITLE
[Bug] AntiAFK strafe not disabling

### ISSUE THREAD

**Issue by Aurorazx** [MeteorDevelopment/meteor-client#344]
**Describe the bug**
when i turn on antiafk with strafe and turn it off it keeps strafing for a minute or two, small bug ik

**To Reproduce**
1. Go to 'meteor gui'
2. Click on 'antiafk with strafe'
3. Scroll down to 'turn on and off'

**Expected behavior**
normal anti afk, and doesnt keep strafing for a minute or two

**Screenshots**
no thx

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by RedCarlos26** [comment]
I cannot reproduce.

**Comment by MineGame159** [comment]
Fixed
