### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Vinylic5042** [MeteorDevelopment/meteor-client#3441]
### Describe the feature

My suggestion is a .dupe command. It will only work in creative and it will dupe the item you are holding.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Soda5601** [comment]
ctrl + middle
