### ISSUE TITLE
auto kit maker

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#3443]
### Describe the feature

a module auto buy stuff needed for a god kit and make the god kit, can buy exp to splash it self.(require economy shop gui plugin)

If fit in not the main client but in a addon, tell me witch addon to suggest it at.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by I-Got-You-Dead2** [comment]
Don’t use meteor where it’s not allowed
