### ISSUE TITLE
[Bug] Meteor client development build keeps crashing

### ISSUE THREAD

**Issue by p9sq** [MeteorDevelopment/meteor-client#3444]
### Describe the bug

Whenever I'm trying to use certain features on meteor client on Linux, the whole game just crashes

### Steps to reproduce

```bash
Idk if this works on any Linux distro, but I'm currently on POP_OS!.
1. Launch meteor
2. Mess around with enabling and disabling settings
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ehylo** [comment]
Please attach meaningful information like logs
