### ISSUE TITLE
[Bug] Incompatible with texture pack "Icons"

### ISSUE THREAD

**Issue by LackyHaus** [MeteorDevelopment/meteor-client#3447]
### Describe the bug

Enchantments are not displayed if the [texture pack](https://www.curseforge.com/minecraft/texture-packs/icons) is active.
Demo before and after:
![Incompatible](https://user-images.githubusercontent.com/75692490/225455632-3e20fa4a-2cd1-43c8-b6e9-7b5ae9066d8b.png)

### Steps to reproduce

```bash
Apply Texture Pack "Icons"
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by LackyHaus** [comment]
Sorry, this is not a bug. I figured it out myself, in the file: assets\minecraft\lang\en_ca.json we remove the icons in front of the names of the enchants, and everything starts working correctly.

**Comment by Wide-Cat** [comment]
if its resolved then thats all good ig
