### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by Ebanytiy** [MeteorDevelopment/meteor-client#3448]
### Describe the feature

Update to 1.19.4

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
So true @MineGame159 I think you should do this

**Comment by coletonodonnell** [comment]
incredibly important issue

**Comment by ItzSkyReed** [comment]
Why not update to 1 19 4 pre 3

**Comment by Wide-Cat** [comment]
resolved as of b0d1686255fe8957e1e4361fd4eedf60cd1f5c04
