### ISSUE TITLE
[Bug] i cant rollback items

### ISSUE THREAD

**Issue by p2wdestroyer** [MeteorDevelopment/meteor-client#345]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by Wide-Cat** [comment]
Lol

**Comment by asdffdsdaf** [comment]
cool bug report wont fix

**Comment by tyrannus00** [comment]
Lmao

**Comment by GildedS** [comment]
Mfw horizon fanboy username
