### ISSUE TITLE
Swarm improvement

### ISSUE THREAD

**Issue by Ompyl** [MeteorDevelopment/meteor-client#3450]
### Describe the feature

It would be nice if I would not only be able to use baritone with .swarm but also to be able to execute commands and chat messages as the clients.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by DAMcraft** [comment]
I already added a PR for a .run command. This would fix this issue

**Comment by Wide-Cat** [comment]
Pretty sure you already can

**Comment by DAMcraft** [comment]
Oh yeah, but before #3428 it didn‘t work with signed messages
