### ISSUE TITLE
[Suggestion] Automatic disconnect

### ISSUE THREAD

**Issue by LackyHaus** [MeteorDevelopment/meteor-client#3453]
### Describe the feature

Automatically leaves the server if there is a player in the radius. Useful if you're an afk with a good sword that you don't want to give away to another player.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
> This feature doesn't already exist in the client. (I have checked every module and their settings on the latest dev build)
yeah, you didn't. it's called autolog

**Comment by LackyHaus** [comment]
> > This feature doesn't already exist in the client. (I have checked every module and their settings on the latest dev build)
> 
> yeah, you didn't. it's called autolog

Unfortunately, it does not allow you to leave the server if the player comes close.

**Comment by Wide-Cat** [comment]
try the 'only trusted' setting
