### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by itsclex** [MeteorDevelopment/meteor-client#3455]
### Describe the bug

So every time I attempt to download the file it shows up as blank, how can I fix this? 

### Steps to reproduce

```bash
I go to https://meteorclient.com/ and then click " download Dev Build 0.5.3 [1.19.3]" and then once I have downloaded the file it shows a blank file image.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://meteorclient.com/

### Meteor Version

Dev Build 0.5.3 [1.19.3]

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
The file image doesn't matter, it just means you don't have a system wide install of Java.
Following the [install instructions](https://meteorclient.com/faq/installation) will still work as epected.
