### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by quinten023** [MeteorDevelopment/meteor-client#3458]
### Describe the feature

Hi love meteorclient first of all! but in the latest update you got rid of .b for commands and made it # , me myself i play on a macbook pro and so now i have to press T to open chat shift click on number 3 and then type command and while i use baritone a lot it makes it so much easier to just press the dot and already open chat window with a dot so you only press b afterwards and your command. no hate or anything sorry for the long message haha ! just wanted to give my opinion about it 

have a good one 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We removed the alias since it did more harm than good, especially with users being confused about what was the original Baritone prefix, both with us and the Baritone support team.
As for the small inconvenience of having to type `#` yourself, that's kind of a (you) problem. It's not like it's all that more complicated.

**Comment by quinten023** [comment]
i don’t think it’s a ‘you problem’ like you said i think a lot more people use .b instead of # i myself didn’t even know about # after i used baritone for a while, why not keep both ?
and i think it’s more a ‘you problem’ if you can’t tell your people # is the original and they keep confusing

**Comment by Big-Iron-Cheems** [comment]
If the people that come in our Discord refuse to read the FAQ present on our website, it's their problem.
Baritone's official prefix has always been `#`, our users simply refused to inform themselves.
Thye kept using `.b` just because the Meteor prefix is `.`.

**Comment by quinten023** [comment]
and your meteor right ? so why not keep both

**Comment by Big-Iron-Cheems** [comment]
Because it's useless to kepp an alias which provides zero benefits, apart from the "convenience" of having to type `.b` instead of `#`.
And the already mentioned confusion caused in Meteor and Baritone support channels.
