### ISSUE TITLE
My minecraft keeps crashing while using the infinity miner

### ISSUE THREAD

**Issue by Skjalg543** [MeteorDevelopment/meteor-client#346]
**Describe the bug**
I start the infinity miner with diamond ore as target and air as repair block, it works fine for half a minute then it crashes

**To Reproduce**
1. Go to infinty miner
2. Click on diamond ore, air
3. See error

**Expected behavior**
Not crashing

**Screenshots**

**Additional context**
im using latest version of everything as of 25,03,21

**Comment by seasnail8169** [comment]
If you dont want to have a repair block just use #mine diamond_ore, infinity miner is meant to repair your pick whilst mining the other material, setting it to air defeats the point.

**Comment by RedCarlos26** [comment]
This issue can be closed then

**Comment by seasnail8169** [comment]
> This issue can be closed then

No, i am leaving it open because the client should not crash even if air is selected. Either air should not be selectable *or* it should just catch the crash and warn the user.

**Comment by RedCarlos26** [comment]
Oh yea true

**Comment by Skjalg543** [comment]
okay so i typed #mine diamond_ore but i still crashed

**Comment by seasnail8169** [comment]
Send the crash log.

**Comment by Skjalg543** [comment]
https://pastebin.com/Kp6GFx8y

**Comment by seasnail8169** [comment]
Would you mind sending a screenshot of your mods folder.

**Comment by Skjalg543** [comment]
![image](https://user-images.githubusercontent.com/81382291/113068066-d39c1480-91bd-11eb-854e-32dae6405a85.png)

**Comment by RedCarlos26** [comment]
Meteor is not compatible with optifine

**Comment by RedCarlos26** [comment]
Yes

**Comment by MineGame159** [comment]
Fixed in dc8ebb84b29aa3a2470b235330efcdec4f9f2707
