### ISSUE TITLE
Remove HurtCam from NoRender as it's now a Vanilla feature named Damage Tilt

### ISSUE THREAD

**Issue by Ebanytiy** [MeteorDevelopment/meteor-client#3460]
### Describe the feature

Remove HurtCam from NoRender as it's now a Vanilla feature named Damage Tilt

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
theres literally an open pr for this 💀

**Comment by MineGame159** [comment]
35456ff97dfa8859cf4893b7e7cdd683efb86b2a
