### ISSUE TITLE
F3 Crash bug

### ISSUE THREAD

**Issue by Geming400** [MeteorDevelopment/meteor-client#3462]
### Describe the bug

Imagine that you want your coordinate, without using the HUD module.
Well you can't and you will crash.

### Steps to reproduce

```bash
Pressing `F3`
```

### Meteor Version

v0.5.3-1803

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
reopen this when you attach a crash report

**Comment by Geming400** [comment]
> reopen this when you attach a crash report

I should make another Issue or edit it? #

**Comment by BDARmech** [comment]
alt of
Eternaliaa
