### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Wowowowoowowowowowow** [MeteorDevelopment/meteor-client#3463]
### Describe the bug

I set my autolog to 20 to test something but the server heart cap is 10, and I don't know what to do because I can't join back on that server as it keeps kicking me and saying (player health is lower than 20)

### Steps to reproduce

```bash
Have a server with heart cap 10 and set your autolog on 20 hearts, then your going to not be able to play on that server again
```

### Meteor Version

1.19.2

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
you can open the gui in the main menu to disable it
