### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by David2871** [MeteorDevelopment/meteor-client#3465]
### Describe the feature

Two Words:
Shulker Dupe
Especially for Realms.

(THIS REQUEST IS FOR THE LATEST VERSION OF MINECRAFT)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
One line: we have nothing to do with dupes, nor will we ever implement any, since they'll eventually be patched (as 99% of the current dupes already have been)
