### ISSUE TITLE
Ability To Hide Meteor Client

### ISSUE THREAD

**Issue by FDkehh** [MeteorDevelopment/meteor-client#3467]
### Describe the feature

How do i remove the "meteor client* by minegame etc."

Also how do i remove "Proxies" and "Accounts" to make it look im legit

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Soda5601** [comment]
1. turn off "title screen credits"
2. dont use meteor where its not allowed

**Comment by FDkehh** [comment]
where is the "tittle screen credits"

**Comment by Soda5601** [comment]
skill issue
why its so hard to find config tab and click into it

**Comment by FDkehh** [comment]
??

**Comment by FDkehh** [comment]
![image](https://user-images.githubusercontent.com/128280039/226164070-c97e4f73-88a1-4db1-bb59-8bd2b3c4c1a0.png)

**Comment by FDkehh** [comment]
I have to remove that

**Comment by FDkehh** [comment]
![image](https://user-images.githubusercontent.com/128280039/226164096-86f97591-08b2-49df-a4ec-caaba4c5b5da.png)
![image](https://user-images.githubusercontent.com/128280039/226164100-0920bc67-07f2-4d29-a1dd-6a2d5dfea559.png)
Also these

**Comment by I-Got-You-Dead2** [comment]
@FDkehh you my friend, are autistic

**Comment by FDkehh** [comment]
please help

**Comment by FDkehh** [comment]
help please

**Comment by Soda5601** [comment]
rshift
config tab
title screen credits

**Comment by FDkehh** [comment]
ohh thanks

**Comment by Soda5601** [comment]
bruh

**Comment by FDkehh** [comment]
![image](https://user-images.githubusercontent.com/128280039/226164372-e929f35e-105e-4692-8b34-09beaaa35d7d.png)
now how do i remove these

**Comment by Soda5601** [comment]
no way
also join discord server and you can get full support of meteor

**Comment by FDkehh** [comment]
ok, thanks!
