### ISSUE TITLE
When i die it baritone says "Death Position Saved"

### ISSUE THREAD

**Issue by FDkehh** [MeteorDevelopment/meteor-client#3468]
### Describe the feature

When i die it baritone says "Death Position Saved" how do i remove that

Screenshot:
![image](https://user-images.githubusercontent.com/128280039/226164624-0f4c03a8-802f-4dbd-ba08-d99d405b97fc.png)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by FDkehh** [comment]
Nevermind, I found the solution Just go to "Baritone" and search "DoDeathWaypoints" and disable it

**Comment by I-Got-You-Dead2** [comment]
Omfg shut the fuck up and don’t use meteor where it’s not allowed. PERIOD.

**Comment by GodsonGamerGr** [comment]
this is not a support page you fucking idiot
