### ISSUE TITLE
The whole game crashed every time, when I was trying to join a server [Bug] 

### ISSUE THREAD

**Issue by SaintNoodles** [MeteorDevelopment/meteor-client#3471]
### Describe the bug

My game crashed every time I tried to join any server,  I already link the logs of the crashed.

### Steps to reproduce

```bash
By joining any server!
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/OahBanR

### Meteor Version

0.5.2 [1.19.3]

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Disable server-spoof-plus and see if happens again.
Ifthat doesn't fix it, remove addons one by one until you find the cause.

**Comment by ItzSkyReed** [comment]
It is because of vector addon.

**Comment by SaintNoodles** [comment]
okay gotcha!

**Comment by SaintNoodles** [comment]
Sorry for the late reply (timezone) but yeah the problem  was the vector addon! thanks for the help.
