### ISSUE TITLE
Tps sync gets me stuck when joining servers

### ISSUE THREAD

**Issue by normaluser12354** [MeteorDevelopment/meteor-client#3480]
### Describe the bug

tps sync has black screen on singleplayer and get stuck on the loading terrain when joining multiplayer

### Steps to reproduce

```bash
use default settings for tps sync on a singleplayer world first 
get black screen
try to join server
freezes on joining terrain
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
meteor doesnt have a tps sync module, this is probably an addon issue
