### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by awesomeboyex11** [MeteorDevelopment/meteor-client#3482]
### Describe the bug

Dirt cobblestone and nether rack keep teleporting into my hotbar when there isn't one of those item in it already.

### Steps to reproduce

```bash
I was playing with the air place feature and placed those blocks and they disappeared from by inventory but then reappeared. It started doing this after that. I've tried to make it stop even by closing and reopening the game but it hasn't. It only does it in survival and removing meteor stops it until you put it back in.
```

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Sounds like a baritone setting, do #allowInventory false

**Comment by awesomeboyex11** [comment]
Oh my gosh thank you so so so so so so so much!!!! You are incredible!
