### ISSUE TITLE
[Bug] Xray Not Working Properly with Sodium on Fabric

### ISSUE THREAD

**Issue by akat0zi** [MeteorDevelopment/meteor-client#3486]
### Describe the bug

Minecraft Version : 1.19.4
Meteor Version : 0.5.3-1806
Sodium Version : 0.4.10+build24

When I turn on the Xray :
- The border around the block you are watching disapear
- You don't see the block breaking animation ( the breaking progress )
- You don't see through full blocks
- You can see only through glass pane / grass ( not the block but the decorative thing )

I tried different things, but the only one that allows me to make it work again, is to remove Sodium.

Hope there is an easy fix. ( I checked my graphics drivers and they are all up to date )

### Steps to reproduce

```bash
Turn on Xray with Sodium Fabric enable
```

### Meteor Version

0.5.3-1806

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Dared0001** [comment]
i have the same problem , u not alone
