### ISSUE TITLE
1.19.4 can't clear chat history

### ISSUE THREAD

**Issue by Bobisawesome07** [MeteorDevelopment/meteor-client#3487]
### Describe the bug

when using on 1.19.4 pressing f3+d doesn't clear the chat history and even when I switch servers I can still see the messages from the other server.

### Steps to reproduce

```bash
log onto any server/singleplayer world type test,test,test in the chat. Then leave and go to to any other server/singleplayer world and when you open chat your test message will still be there. Also pressing f3+d has no effect.
```

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
which dev build are you using?

**Comment by Bobisawesome07** [comment]
1806

**Comment by Wide-Cat** [comment]
update to the latest one, there should be a fix

**Comment by DAMcraft** [comment]
me when I create yet another bug in meteor (I am very good at this)
