### ISSUE TITLE
Crashed when use Meteor with Sodium

### ISSUE THREAD

**Issue by qzhhhi** [MeteorDevelopment/meteor-client#3488]
### Describe the bug

My game crashes when I try to upgrade my meteor client dev build 0.5.2-1751 to release. After many attempts, I found that when the latest meteor and sodium coexist, the game crashes.

Trying to rule out whether my config files were set up wrong, I used a fresh copy of Minecraft 1.19.3, installed Fabric, and added the following mods:
- meteor-client-0.5.2.jar
- sodium-fabric-mc1.19.3-0.4.8+build.22.jar

The crash still occurs, and I get the same error log.

The Fabric version I'm using is 0.14.17, which is the latest I can find. Fabric API is not added (the error remains after adding).

### Steps to reproduce

```bash
The method of reproduction has been mentioned above.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/Y8IlSXB

### Meteor Version

0.5.2 release

### Minecraft Version

1.19.3 release

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Update sodium to at least 0.4.9

**Comment by qzhhhi** [comment]
Sodium 0.4.9 works, thanks.
