### ISSUE TITLE
Game just randomly crashes and gives error code: 255

### ISSUE THREAD

**Issue by MrLucaIsCool** [MeteorDevelopment/meteor-client#3490]
### Describe the bug

Whenever i launch the 1.19.3 version of meteor client and play on this mc server (6b6t) my game just sometimes randomly crashes, this also happens when i use this addon for meteor (blackout) and its auto crystal rewrite feature, however when i use the auto crystal rewrite i just get disconnected from the server (there is a error code for it but i cant copy and paste it), ive tried turning down the crystal placement and everything but it all seems to still crash. Hopefully this can be resolved, kind regards Luca (Btw im on Mac if you have any solutions)

### Steps to reproduce

```bash
1. download and install an addon for meteor (name: blackout) from - https://anticope.ml/addons/?
2. launch mc meteor in 1.19.3 and turn on crystal aura 
3. game can sometimes then proceed to get yoy disconnected.
```

### Meteor Version

Release 0.5.2

### Minecraft Version

1.19.3

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Attach a crash log as requested or we cannot do anything about it.

**Comment by MrLucaIsCool** [comment]
Hi, im back again
i still haven't gotten a response i think the coders may be inactive however whenever i use this addons auto crystal rewrite i get this error (i found it this time) "internal Exception: JavalanaglllegalArgumentException: bound must be
greater than origin". is there a common solution to this problem if so please do let me know.
![Uploading Screen Shot 2023-03-25 at 1.11.19 pm.png…]()
