### ISSUE TITLE
Better tooltips does not show container items

### ISSUE THREAD

**Issue by maxsupermanhd** [MeteorDevelopment/meteor-client#3495]
### Describe the bug

Container preview (tooltip) inside echest does not render items, only their damage bars.
![image](https://user-images.githubusercontent.com/20772987/227728777-ef08d9f7-170b-423e-9934-53154f6da09b.png)

### Steps to reproduce

```bash
Open echest and try to preview a container (shulker box).
```

### Meteor Version

0.5.3-1817

### Minecraft Version

1.19.4

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by UnderQuestion** [comment]
agreed fix it pls

**Comment by thebest9178** [comment]
Works fine for me on 0.5.3-1820 on linux

**Comment by maxsupermanhd** [comment]
Looks like it was fixed
