### ISSUE TITLE
Incorrect coloring of colored containers in peek

### ISSUE THREAD

**Issue by maxsupermanhd** [MeteorDevelopment/meteor-client#3496]
### Describe the bug

![image](https://user-images.githubusercontent.com/20772987/227728955-5a5451e7-dc26-4618-91ad-8b004794c89d.png)
![image](https://user-images.githubusercontent.com/20772987/227728987-abe94e7e-0730-4597-b4c0-f021669bd5f6.png)
Normal containers that don't have color are not affected.

### Steps to reproduce

```bash
Preview a container (middle mouse button or .peek)
```

### Meteor Version

0.5.3-1817

### Minecraft Version

1.19.4

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Soda5601** [comment]
a mod that changes the vanilla gameplay prob won't work with meteor

**Comment by maxsupermanhd** [comment]
@Soda5601 
> a mod that changes the vanilla gameplay prob won't work with meteor

I do not run any vanilla-changing mods, coloring of shulker boxes is a vanilla feature. Such bug is not present on meteor for 1.19.3.
Please elaborate

**Comment by maxsupermanhd** [comment]
Actually, speaking of mods, I had sodium and other optimization-related mods enabled, I will see if I will be able to reproduce the issue without them first. It very well may be a compatibility issue

**Comment by Soda5601** [comment]
colored shulkers arent vanilla, so you prob have optigui installed, and it creates an extra property for shulker box screen that doesnt exist in vanilla, so we have nothing to do with it

**Comment by MrBreakNFix** [comment]
> colored shulkers arent vanilla, so you prob have optigui installed, and it creates an extra property for shulker box screen that doesnt exist in vanilla, so we have nothing to do with it

Try taking a shulker box, and dye, and put them in a crafting table, be amazed

**Comment by maxsupermanhd** [comment]
@Soda5601

> colored shulkers arent vanilla

Please take a read: https://minecraft.fandom.com/wiki/Shulker_Box
Shulker boxes had colored variants since they were introduced into the game in 1.11 if I understood history section of the wiki correctly

**Comment by maxsupermanhd** [comment]
Looks like it was fixed
