### ISSUE TITLE
[SUGGESTION] no elytra damage

### ISSUE THREAD

**Issue by NotSequoia** [MeteorDevelopment/meteor-client#350]
**Describe the feature**
Please add a feature that makes it so you can’t take damage from running into things with elytra.

**Comment by RedCarlos26** [comment]
@seasnail8169 Could this be possible to implement?

**Comment by seasnail8169** [comment]
The only realistic way i can think of is just something that prevents you from going into walls in the first place. Like it will detect when near blocks and rubberband you

**Comment by RedCarlos26** [comment]
Yes, but I think this is just annoying and that it is too much work for nothing. Like, just turn when there are blocks.

**Comment by AstroOrbis** [comment]
Elytra Damage is based on speed last I checked. Maybe something that slows you down last second?

**Comment by MATIXON2115** [comment]
blink on every second tick.
and client side stop/lower speed package.
in theory it's can work. but elytra only slower breaking.
(sorry for my english)

**Comment by RedCarlos26** [comment]
This was added in dev build 670. This can be closed @
