### ISSUE TITLE
[Suggestion] Auto Lavacast

### ISSUE THREAD

**Issue by Arbisy** [MeteorDevelopment/meteor-client#351]
**Describe the feature**
Auto Lava cast, makes lava casts for you like the pyramid one, the staircase one, etc.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by RedCarlos26** [comment]
I would not implement that, because the waiting times for the lava/water to flow are always changing. On the other hand, I would implement a feature that makes the base structure to start the lava cast (with the styles you said like the pyramid, the staircase, etc.).

**Comment by RedCarlos26** [comment]
What do you think @seasnail8169?

**Comment by seasnail8169** [comment]
Ill leave it here for now. I wont work on this myself though.

**Comment by RedCarlos26** [comment]
@MineGame159 do you think this is worth taking time to make (read what I wrote just before)

**Comment by AstroOrbis** [comment]
As you said, there are too many variables, this would be impossible. Running into a block could force you to fall off. It’s easy to do things like this with Scaffold. I say we close this.

**Comment by AstroOrbis** [comment]
?

**Comment by MineGame159** [comment]
Because some suggestion is more complex doesnt mean we need to close it, also I already planned to do it at some point even before the suggestion was made.

**Comment by Arbisy** [comment]
> Because some suggestion is more complex doesnt mean we need to close it, also I already planned to do it at some point even before the suggestion was made.

Oh cool

**Comment by AstroOrbis** [comment]
Wait, maybe we could make a preloaded schematic using Baritone? wouldn't that work?

**Comment by MineGame159** [comment]
No.

**Comment by AstroOrbis** [comment]
why? Baritone would take all placed blocks into account.
