### ISSUE TITLE
mutli clei

### ISSUE THREAD

**Issue by DoctorCheese1** [MeteorDevelopment/meteor-client#3522]
### Describe the bug

minecraft will not launch just crashes everytime.

### Steps to reproduce

```bash
using wurst client and meteor client
```

### Meteor Version

latest version of 1.19.3 

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
We don't support Wurst as its modules clash with Meteors'.

Closes #3521
