### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by poldedis** [MeteorDevelopment/meteor-client#3527]
### Describe the bug

help me wen i try to use on (tllauncher) worked before 1 time now it just wont ping any servers it just says pinging... and wont do anything cant join multiplayer please help ;)

thank you! :)
![sssss](https://user-images.githubusercontent.com/129142030/228128841-b3ddcca5-e9df-4c33-90e3-8e6d4d7cbddf.png)

### Steps to reproduce

```bash
joining the game and going to multiplayer.
```

### Link to crash report/log if applicable (https://mclo.gs)

idk

### Meteor Version

1.19.3

### Minecraft Version

1.19.3 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by poldedis** [comment]
if there is a proxy to use please link it :)

**Comment by I-Got-You-Dead2** [comment]
Delete minecraft

**Comment by I-Got-You-Dead2** [comment]
Choose a different game

**Comment by Big-Iron-Cheems** [comment]
We do not support cracked launchers.
Use one of our supported ones with a paid Minecraft account.
