### ISSUE TITLE
[Suggestion] Crystal chams like the picture attached to this suggestion

### ISSUE THREAD

**Issue by supakeks** [MeteorDevelopment/meteor-client#353]
**Describe the feature**
Crystal chams like the picture attached to this suggestion
Outline width would be customizable, would have an alpha setting slider to change the alpha, default at 255
**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/70498670/112661830-55421a00-8e2d-11eb-81d1-887b6eceaef8.png)

**Additional info**
Add any other info.

**Comment by RedCarlos26** [comment]
This would be really nice to see added.

**Comment by AstroOrbis** [comment]
I believe there is one in ModelTweaks, but that isn't as sophisticated as the one in this screenshot. What client is that by the way?

**Comment by RedCarlos26** [comment]
Probably Konas client

**Comment by Wide-Cat** [comment]
Should this be closed now that chams were rewritten in 9f1cf933d1e3813d15c3b267f00db597f150a7f7

**Comment by AstroOrbis** [comment]
Agreed.
