### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by poldedis** [MeteorDevelopment/meteor-client#3534]
### Describe the bug

wont let me join multiplayer such as this are my setting but it wont let me join anything just pinging... 
![comet](https://user-images.githubusercontent.com/129142030/228707392-031de37d-c29b-4aca-872b-523a3fe84845.png)
![sssss](https://user-images.githubusercontent.com/129142030/228707438-6b3e7905-ffd7-47cf-8735-2e1b5af3ddc9.png)
(help)

### Steps to reproduce

```bash
joining minecraft on tllaucnher worked before now not anymore :/ then go to multioplayer and this is what i see...
go up to first thing
```

### Link to crash report/log if applicable (https://mclo.gs)

no

### Meteor Version

1.19.3 (not dev)

### Minecraft Version

1.19.3 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead2** [comment]
1: don’t use meteor where it’s not allowed
2: don’t use cracked minecraft

**Comment by Pxddyk45** [comment]
3: tlauncher is malware
