### ISSUE TITLE
[Suggestion] Bypassing for Anti-Cheats

### ISSUE THREAD

**Issue by Neuxs0** [MeteorDevelopment/meteor-client#3537]
### Describe the feature

Currently there is pretty much nothing to bypass any Anti-Cheat so like 90% of server you can't cheat on with this client. So please add bypassing/disabler to the client, especially for Vulcan.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ItzSkyReed** [comment]
![Screenshot_2023-03-31-07-58-53-14_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/93844414/229011769-7654574a-dee6-42ba-8908-7db03eca2f67.jpg)
Maybe it is because meteor dont want to bypass anticheats..

**Comment by Talhoid** [comment]
fun fact!!: as @ItzSkyReed said, meteor is a utility mod for **anarchy** servers only.
please stop asking for bypasses
