### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by babytaco826** [MeteorDevelopment/meteor-client#354]
all of the .commands do not work in the latest minecraft version (1.16.5

**Comment by RedCarlos26** [comment]
I cannot reproduce the bug. Do you have the lastest dev build?

**Comment by StormyBytes** [comment]
I also cannot reproduce the bug. I have been using fabric version 1.16.5. And I often update to the latest dev build. Yet the commands all work properly for me.

**Comment by babytaco826** [comment]
so basicly my mod folder looks like this https://discord.com/channels/@me/824268181618688000/825353739044651049 I AM playing 1.16.4 so that may be it but does .gamemode work

**Comment by babytaco826** [comment]
i have just got the latest everything but it STILL dosnt work

**Comment by StormyBytes** [comment]
> so basicly my mod folder looks like this https://discord.com/channels/@me/824268181618688000/825353739044651049 I AM playing 1.16.4 so that may be it but does .gamemode work

I cannot open the discord link.

**Comment by babytaco826** [comment]
k stormy heres the file then
![unknown](https://user-images.githubusercontent.com/81445278/112723123-6d747080-8ee3-11eb-89e4-09e4e9aebf32.png)

**Comment by babytaco826** [comment]
and im playing on 1.16.5

**Comment by StormyBytes** [comment]
It seems that your fabric api is not on the latest version, try using the latest one

**Comment by babytaco826** [comment]
ok

**Comment by babytaco826** [comment]
Ok probably final time. I got the new fabric api, ran meteor. and went into singleplayer. it didnt work. i went into multiplayer. didnt work. .clear-chat works but .gamemode doesnt work so .give .enchant and others are broken

**Comment by babytaco826** [comment]
i did

**Comment by MineGame159** [comment]
So what is the problem now? You are saying that .give, .enchant and .gamemode does not work in multiplayer?

**Comment by babytaco826** [comment]
so for .gamemode the visuals happen, and in adventure u cant break but u
can place and interact and in creative u can fly BUT in creative the blocks
u get are ghost blocks and will disappear if you drop them or open a gui

**Comment by MineGame159** [comment]
Thats what should happen. There is nothing wrong with it. It only changes your gamemode client-side. The server still thinks you are in your normal gamemode, there is no way around that.

**Comment by babytaco826** [comment]
ohh ok well can u chain .gamemode to .enchant orrrr

**Comment by MineGame159** [comment]
What do you mean chain

**Comment by babytaco826** [comment]
can you do .gamemode then .enchant because u need to be in creative to do
.enchant

**Comment by MineGame159** [comment]
You should be able to, why not try it. But it wont actually enchant the item. It will appear enchanted but as soon as you move it then it will revert.

**Comment by babytaco826** [comment]
ok well that's a cool feature thanks for letting me know otherwise i would
have wasted my life away trying to figure it out
