### ISSUE TITLE
[Bug] Scaffold does not work

### ISSUE THREAD

**Issue by Afanasy3000** [MeteorDevelopment/meteor-client#3543]
### Describe the bug

scaffold stops working if x or z is negative
this problem is similar to incorrect placement of blocks on negative coordinates in spawn proofer. As I understand, the distance to the block is incorrectly calculated if any of the coordinates is negative.

### Steps to reproduce

```bash
to repeat this bug, you need to stand on any negative coordinates and turn on the scaffold
```

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
should be resolved by 20d44c17daf2614bbf9c3b5ff3b9be294ec6b378
