### ISSUE TITLE
Hitbox module feature.

### ISSUE THREAD

**Issue by a7md8762** [MeteorDevelopment/meteor-client#3544]
### Describe the feature

A setting in hitbox module that makes a 2D box instead of making the entity's hitboxes bigger, as it flags some anti-cheats by hitting an entity/player while the module is enabled by sending a decreased reach (while the distance from the attacked entity/player is 3 blocks) to the anti-cheat and flagging you.

An example:
without the module enabled: the reach displayed is 3 blocks
with the module enabled: the reach displayed is 2.8 blocks (despite the fact you are exactly 3 blocks away from the entity)

more description for my suggestion: the new setting just makes a 2D hitbox visible to the user (this can be disabled in the module settings) and when hitting an entity, the reach returned to the anti-cheat is 3 blocks, and not less than that, which will make the anti-cheat doesn't flag you.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Shrecknt** [comment]
This doesn't really make any sense
You can pretend all you want that you are closer to the target client side, but the server doesn't care what the client thinks
If you are 3 blocks away you are 3 blocks away, and changing hitboxes client side cant change that

**Comment by a7md8762** [comment]
no, the anti-cheat actually cares about the reach returned to the anti-cheat by the client and the real distance from the 
hitten entity.
this is how you get flagged for using hitboxes.

**Comment by Wide-Cat** [comment]
How does the client send reach to an anticheat? All you do is send an attack packet to the server, which doesnt include a value that the client calculates your reach to be. As far as I'm aware, reach checks don't work by looking at server-client desyncs regarding what you tell the server your reach distance is. Also, what do you mean by 'makes a 2D box instead of making the entity's hitboxes bigger'?

**Comment by a7md8762** [comment]
What do I mean by 'makes a 2D box instead of making the entity's hitboxes bigger' it renders a 2D box like the Esp module in 2D mode, but a hittable hitbox.
"All you do is send an attack packet to the server, which doesnt include a value that the client calculates your reach to be" well, if so why do I get flagged by the anti-cheat when I have hitbox module on, while I'm perfectly 3 blocks from the entity and still get flagged? and I tested it without the module on, and no flags.

**Comment by Shrecknt** [comment]
> What do I mean by 'makes a 2D box instead of making the entity's hitboxes bigger' it renders a 2D box like the Esp module in 2D mode, but a hittable hitbox. "All you do is send an attack packet to the server, which doesnt include a value that the client calculates your reach to be" well, if so why do I get flagged by the anti-cheat when I have hitbox module on, while I'm perfectly 3 blocks from the entity and still get flagged? and I tested it without the module on, and no flags.

I don't know exactly what's happening in your case, I would need your configs and a bunch of other information that I don't care enough to collect or look through, but [this](https://wiki.vg/Protocol#Interact) is the current protocol specification for attack packets, which the client sends to the server the target entity id, and if the client is sneaking. It does not send anything like the location of the target, or anything else that you seem to think it contains.
