### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by singleSACRAP** [MeteorDevelopment/meteor-client#3555]
### Describe the bug

After join a map or server, I got game crashed

Exit Code: -1

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot read field "field_3911" because "this.field_4015.field_1724" is null

### Steps to reproduce

```bash
Using mods sodium-fabric-mc1.19.4-0.4.10+build.24, fabric-api-0.76.0+1.19.4, iris-mc1.19.4-1.5.2 and
meteor-client-0.5.3-1820 with fabric-loader-0.14.18-1.19.4
```

### Meteor Version

meteor-client-0.5.3-1820

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Retry without Iris and see if it works.
Also, provide the full crashlog as explained in our [FAQ](https://meteorclient.com/faq/getting-log).

**Comment by IlIlIlIIlIlIlIl** [comment]
Not crashing when i remove iris
