### ISSUE TITLE
[Suggestion] AntiKnockBack

### ISSUE THREAD

**Issue by Filipek23** [MeteorDevelopment/meteor-client#3557]
### Describe the feature

Will you add AntiKnockBack?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
the velocity module

**Comment by Filipek23** [comment]
Ok

**Comment by I-Got-You-Dead2** [comment]
Velocity dumbass
