### ISSUE TITLE
change accounts tab

### ISSUE THREAD

**Issue by CesarLeCoderMan** [MeteorDevelopment/meteor-client#3559]
### Describe the feature

change altinator in accounts to easymc because altinator doesnt work

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GoofyBoi420** [comment]
did you download the authenticator?
