### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gmeinerPudim** [MeteorDevelopment/meteor-client#356]
![Screenshot_471](https://user-images.githubusercontent.com/73142635/112729643-fe5f4200-8f0b-11eb-9e40-7c3a4a09808e.png)
When I try to enter in anarchy server it crashes, and before the crashe it shows that the world is saving.(Im playing in 1.16.5)
But in other servers works well.

**Comment by MineGame159** [comment]
Send the crash report

**Comment by MineGame159** [comment]
Can you send a screenshot of your mods folder

**Comment by RedCarlos26** [comment]
Is the crash still happening?

**Comment by MineGame159** [comment]
@gmeinerPudim

**Comment by seasnail8169** [comment]
Please ask for help on the [discord server](https://meteorclient.com/discord) since this is, to my understanding, not a bug with our mod.
