### ISSUE TITLE
X ray hack doesn't work in the 1.19.3 version

### ISSUE THREAD

**Issue by Akul2010** [MeteorDevelopment/meteor-client#3561]
### Describe the bug

X ray hack doesn't work in the 1.19.3 version. It only works when looking at water.

### Steps to reproduce

```bash
Just enable Xray.
```

### Meteor Version

Release 0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by unseeyou** [comment]
same here, but when looking at the water its not really x-ray its just not rendering the blocks like when you are inside a block in spectator mode

**Comment by GoofyBoi420** [comment]
change the opacity to 0

**Comment by Akul2010** [comment]
thanks, it works now!
