### ISSUE TITLE
maven not working

### ISSUE THREAD

**Issue by Ranele** [MeteorDevelopment/meteor-client#3570]
### Describe the bug

maven not working

### Steps to reproduce

```bash
maven not working
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
should be fixed now
