### ISSUE TITLE
better tooltips not working with shulker boxes

### ISSUE THREAD

**Issue by genshinwhale** [MeteorDevelopment/meteor-client#3571]
### Describe the bug

Im playing on DonutSMP and whenever I alt a shulker box with the "Better Tooltips" hack the item doesn't seem to render and only the durability. Sometimes, and ONLY SOMETIMES IDK WHY, if the shulker is colored, instead of the tint appearing on the little inventory thing that appears, it covers the whole screen and can only be disabled when pressing esc.
![2023-04-13_09 53 58](https://user-images.githubusercontent.com/111215305/231636266-d505aba7-885f-4224-a2c6-4786ee1f97dc.png)

### Steps to reproduce

```bash
1. Turn on better tooltips
2. get a shulker and fill it with whatever items
3. press your keybind
4. it should show nothing
5. if an item with a durability bar is in there then it should only show the bar
6. i think the bug only affects me
```

### Meteor Version

1.19.4

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Shrecknt** [comment]
Have you tried playing on an anarchy server instead?

**Comment by genshinwhale** [comment]
> Have you tried playing on an anarchy server instead?

yes. every singleplayer world, realms, servers, they all dont work

**Comment by genshinwhale** [comment]
> Have you tried playing on an anarchy server instead?

so how do i fix it?

**Comment by Wide-Cat** [comment]
This should have been resolved as of the latest dev build, also don't use meteor on servers that dont allow it.
