### ISSUE TITLE
Anchor Aura working on Meteor client even though its disabled

### ISSUE THREAD

**Issue by King4Konge** [MeteorDevelopment/meteor-client#3575]
### Describe the bug

i disabled anchor aura on meteor client but it still places anchors and i cant get it to stop

### Steps to reproduce

```bash
idk how to do it i just want it fixed
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
unable to reproduce
