### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Lakkyyyy** [MeteorDevelopment/meteor-client#3576]
### Describe the feature

Replace TheAltening Support with EasyMC support as it is more reliable and has a way bigger number of alts

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by HombrePollo** [comment]
Don't remove the altening, just add EasyMC. I still use TheAltening as it gives me the same alt everytimme which I need

**Comment by Lakkyyyy** [comment]
> Don't remove the altening, just add EasyMC. I still use TheAltening as it gives me the same alt everytimme which I need

thing is there is oly one alt so anyone can login into it which is painsaga

**Comment by HombrePollo** [comment]
Yeah idc tbh

**Comment by notsusman** [comment]
Would love to see this feature

**Comment by I-Got-You-Dead2** [comment]
> > Don't remove the altening, just add EasyMC. I still use TheAltening as it gives me the same alt everytimme which I need
> 
> thing is there is oly one alt so anyone can login into it which is painsaga

Try paying for altening
