### ISSUE TITLE
AutoReconnect doesnt show up once kicked

### ISSUE THREAD

**Issue by Lawerencium** [MeteorDevelopment/meteor-client#3579]
### Describe the bug

The AutoReconnect module doesn't behave as it should. Once turned on, it doesnt try to reconnect the moment you get kicked. It doesnt show the auto-reconnect toggle button in the kick-screen either.

### Steps to reproduce

```bash
- Turn on AutoReconnect
- get kicked
```

### Meteor Version

meteor-client-0.5.3-1820

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Soda5601** [comment]
Fixed in my open pr

**Comment by Wide-Cat** [comment]
resolved as of #3605
