### ISSUE TITLE
[Suggestion] Infinite chat length

### ISSUE THREAD

**Issue by Cazcez** [MeteorDevelopment/meteor-client#358]
**Describe the feature**
A feature implement can be cool for Better Chat which add infinite chat length. Because sometimes we need use long commands and its impossible without a command block.

**Comment by AstroOrbis** [comment]
I'll get to work!

**Comment by RedCarlos26** [comment]
Chat is almost infinite with better chat option. It can go to 1000 lines, and going up more than that could cause major lag. What do you think @seasnail8169?

**Comment by Cazcez** [comment]
> Chat is almost infinite with better chat option. It can go to 1000 lines, and going up more than that could cause major lag. What do you think @seasnail8169?

I don't mean chat history. I mean message length of us. You know some commands are longer than 256 character and you can not use messages for this. You need to use a command block.

**Comment by RedCarlos26** [comment]
Ok I see, this is a great idea

**Comment by MineGame159** [comment]
Added
