### ISSUE TITLE
Dearest Bebail

### ISSUE THREAD

**Issue by Eliaspopa** [MeteorDevelopment/meteor-client#3581]
### Describe the feature

@sneasnail please bring back .b thanks, I (and all my homies) hate # for baritone fuck the haters, fuck you.
Give me back .b!!!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
I agree
