### ISSUE TITLE
Meteor  client is crashing my louncher(T louncherr) [Bug] 

### ISSUE THREAD

**Issue by Dantes124252** [MeteorDevelopment/meteor-client#3584]
### Describe the bug

my game just does not start it just crashes 

### Steps to reproduce

```bash
when i press enter the  game on t louncher it crashes
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/uX0jsPq

### Meteor Version

Dev Build 0.5.3 [1.19.4]

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Soda5601** [comment]
🤡

**Comment by I-Got-You-Dead2** [comment]
Launcher*

**Comment by I-Got-You-Dead2** [comment]
Also buying the game might help

**Comment by Big-Iron-Cheems** [comment]
We do not support cracked launchers as stated in our FAQ. So use one of the [suggested ones](https://meteorclient.com/faq/installation) instead.
