### ISSUE TITLE
does anyone have phase mod in meteor client?

### ISSUE THREAD

**Issue by kojocisko** [MeteorDevelopment/meteor-client#3586]
### Describe the bug

if you know how to get phase im meteor client please dm me Kojot#2137

### Steps to reproduce

```bash
3213
```

### Link to crash report/log if applicable (https://mclo.gs)

321

### Meteor Version

231

### Minecraft Version

1.16.5

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Shrecknt** [comment]
I have phase, but I don't like you so you can't have it. >:)

**Comment by Big-Iron-Cheems** [comment]
Meteor doesn't have phase, since it's patched on latest versions.

Also, the GitHub issues are not a way to ask for random users to send you stuff.
