### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Suname1425** [MeteorDevelopment/meteor-client#3587]
### Describe the feature

Make an aura that has a customizable range that tills soil while holding a hoe.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MrBreakNFix** [comment]
meteor rejects has something like this in the AutoFarm module
