### ISSUE TITLE
Crashes on perspective change with Camera Utils mod.

### ISSUE THREAD

**Issue by starboyceleste** [MeteorDevelopment/meteor-client#3589]
### Describe the bug

The game crashes immediately on any player perspective change with Camera Utils installed.
Issue in Meteor Client 0.5.0 as well: #2561 

### Steps to reproduce

```bash
1. Install Camera Utils 1.0.3.
2. Change your player perspective. (F5, free cam, etc)
3. Crash.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/qAPNRV5

### Meteor Version

Meteor Client 0.5.2

### Minecraft Version

Minecraft 1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by LuukPlay** [comment]
UP 1.19.4 same bug
