### ISSUE TITLE
Can't move items in inventory and chest

### ISSUE THREAD

**Issue by BigJuicyBanana** [MeteorDevelopment/meteor-client#3594]
### Describe the bug

When i try to move any items around in my inventory it looks like they move but when i open my echest they just get teleported back to their original positions. 

### Steps to reproduce

```bash
When I was trying to open a chest and put down an item and it doesn't let put in the items and when I try to drop an item in my inventory it doesn't work as well but I works with hotbar. In some sever sometimes the bug happens and sometimes it doesn't
```

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Shrecknt** [comment]
Probably an AC issue
