### ISSUE TITLE
[Suggestion] iris shaders 

### ISSUE THREAD

**Issue by m-m574** [MeteorDevelopment/meteor-client#3595]
### Describe the feature

make iris shaders work

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Duplicate of #3596
