### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by m-m574** [MeteorDevelopment/meteor-client#3596]
### Describe the bug

iris shaders crash when i load a world

### Steps to reproduce

```bash
install iris shaders, load a world, crash
```

### Meteor Version

1.19.4

### Minecraft Version

1.19.4?

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by JustPixeled** [comment]
Will this be fixed? I love having shaders
