### ISSUE TITLE
Game crashes when using Latest version of Meteor with latest Version of Sodium

### ISSUE THREAD

**Issue by Raistart** [MeteorDevelopment/meteor-client#3598]
### Describe the bug

I tried to use meteor client with my modpack and then it started to crash during loading of the game. After checking each mod individually, I found out that it was Sodium which conflicted with meteor. Now I have to choose between performance and utility. 

Here are some details that might help:

Sodium Version: sodium-fabric-mc1.19.4-0.4.10+build.24
Meteor Version: meteor-client-0.5.3-1822
Fabric Loader version: 0.14.19
Minecraft Version: 1.19.4

### Steps to reproduce

```bash
Steps to reproduce this bug:
1. Remove all mods except meteor client and Sodium
2. Try to load up the game in the latest fabric version
 The game should fail to load and crash.
```

### Meteor Version

meteor-client-0.5.3-1822

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
post a crash report; we are fairly confident that meteor is perfectly compatible with sodium

**Comment by Pdam67** [comment]
It's not sodium that's causing the crash, it's iris i think.

**Comment by Raistart** [comment]
I'll check, thanks

**Comment by Raistart** [comment]
> It's not sodium that's causing the crash, it's iris i think.

Ok, i can confirm, it's iris that's causing issue, now what should I do? i tried the latest version of iris, and the latest dev build of meteor...

**Comment by Pdam67** [comment]
> 

Just notify the team with a crash report that it's iris and let them do their thing.

Just don't use iris at the moment.

**Comment by Pdam67** [comment]
Meteor client doesn't have the best compatibility with iris recently

**Comment by LuukPlay** [comment]
Iris...
