### ISSUE TITLE
Please upload to Curseforge and other mod sites

### ISSUE THREAD

**Issue by Akul2010** [MeteorDevelopment/meteor-client#3600]
### Describe the feature

It's just uploading the mod to websites like Curseforge, Modrinth, etc.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Talhoid** [comment]
:sotrue:

**Comment by ssaagamemer** [comment]
its Will removed in github

Microsoft own github now

**Comment by arlomcwalter** [comment]
> now

mfw reaction time of five years
