### ISSUE TITLE
[Bug] NoFall

### ISSUE THREAD

**Issue by dumbminecrafter** [MeteorDevelopment/meteor-client#3601]
### Describe the bug

NoFall deals damage when falling 

### Steps to reproduce

```bash
turn on NoFall, Fall, Deals Damage
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Shrecknt** [comment]
Fake news

**Comment by Jayesk** [comment]
Works fine on newest version of the client, 1.19.4 Dev Build 0.5.3

**Comment by GoofyBoi420** [comment]
sikll issue

**Comment by Akul2010** [comment]
lol

**Comment by Wide-Cat** [comment]
This is probably an issue with the servers anticheat, because otherwise nofall should be working fine
