### ISSUE TITLE
EasyMC Support

### ISSUE THREAD

**Issue by TheKidThatCodes** [MeteorDevelopment/meteor-client#3606]
### Describe the feature

its been mentioned before
it would probbably be easy since they have api docs

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Shrecknt** [comment]
skull emoji
