### ISSUE TITLE
add breaking block 2x2x2 or 4x2x4 and so on

### ISSUE THREAD

**Issue by NetherKK** [MeteorDevelopment/meteor-client#3607]
### Describe the feature

look when you break 1 block on 2x2x2 you break 4 blocks on 1 click can you guys add this pls but i really need this

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Pxddyk45** [comment]
Minecraft allows only for 1 block to be broken at the same time as far as i know so this wouldn't be possible

**Comment by Wide-Cat** [comment]
try checking out vein miner, or fiddling with the nuker settings
