### ISSUE TITLE
Optifabic Complat problem

### ISSUE THREAD

**Issue by ssaagamemer** [MeteorDevelopment/meteor-client#3608]
### Describe the bug

i has problem with metorclient and optifabic mod its has complat problem it doesn't boot game and game stuck on black screen

(P.S im running on pojavlauncher)
and it work normaly

### Steps to reproduce

```bash
First download optifabic optfine metorclient
Paste into mod folder
Then boot game
And Complat happen
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/vUqZpeb

### Meteor Version

0.5.4-1842

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
The [FAQ](https://meteorclient.com/faq#how-to-use-meteor-with-optifine?) is pretty clear about not using OptiFabric/OptiFine, and the alternatives you should be using on Fabric.

**Comment by Big-Iron-Cheems** [comment]
Also, we do not support Pojav launcher directly, since it's for android.
Any uissues related to that are not in our interest to fix.

**Comment by ssaagamemer** [comment]
okayyy thanks for giving info

**Comment by ssaagamemer** [comment]
but i cant use any alternative ? (sodium make my game has 1-10 fps)

**Comment by GreemDev** [comment]
then cope, meteor doesn't work with optifabric, you either use optifabric without meteor or meteor without optifabric
also, you're playing Java edition on an Android and you're SURPRISED that you're getting terrible performance..?

**Comment by I-Got-You-Dead2** [comment]
Literally buy a pc

**Comment by ssaagamemer** [comment]
Why You think Money Grown On Tree? huh

**Comment by I-Got-You-Dead2** [comment]
Yes

**Comment by I-Got-You-Dead2** [comment]
Buy a pc

**Comment by ssaagamemer** [comment]
bruh fine i gonna getting money in broke now

**Comment by ssaagamemer** [comment]
0.02$ left on my bal

**Comment by I-Got-You-Dead2** [comment]
Skill issue

**Comment by ssaagamemer** [comment]
why then go to discord not there

**Comment by I-Got-You-Dead2** [comment]
Huh

**Comment by ssaagamemer** [comment]
it is a issue discussion not chat wars
