### ISSUE TITLE
Sugest

### ISSUE THREAD

**Issue by ae23rn7diu2** [MeteorDevelopment/meteor-client#3609]
### Describe the feature

Can you make a tutorial of what you can do with meteor client?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Not to sound rude, but why would we wase time making a tutorial, when anyone can download Meteor and try it themselves?
There's even an FAQ for the most common questions etc.

**Comment by ae23rn7diu2** [comment]
Some people don't know how to use for example baritone.

**Comment by I-Got-You-Dead2** [comment]
Then get smart

**Comment by I-Got-You-Dead2** [comment]
Literally use #help

**Comment by I-Got-You-Dead2** [comment]
It’s really not that hard

**Comment by ae23rn7diu2** [comment]
ok
