### ISSUE TITLE
Crash with sodium 0.4.11

### ISSUE THREAD

**Issue by KidOfCubes** [MeteorDevelopment/meteor-client#3612]
### Describe the bug

Mixin application crash during startup

### Steps to reproduce

```bash
Start mc with latest dev build of meteor and sodium 0.4.11+build.26 from modrinth.
Game crashes
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/98lVrvr

### Meteor Version

meteor-client-0.5.3-1829

### Minecraft Version

1.19.4

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RedCarlos26** [comment]
Can confirm

**Comment by RedCarlos26** [comment]
This is my crash log if this can help : https://mclo.gs/O22PFXX

**Comment by Funtimes909** [comment]
happening as well

**Comment by Sophed** [comment]
Can confirm happening to me too

**Comment by TheNicestDev** [comment]
I can confirm this
