### ISSUE TITLE
[Suggestion] Kill Aura dont target baby animals

### ISSUE THREAD

**Issue by Andboniels** [MeteorDevelopment/meteor-client#3616]
### Describe the feature

I searched here for baby animals, but nothing showed up, sorry if it is a dupe suggestion.

Kill Aura dont seem to have an option to not target baby animals, atm it kills anything in range.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Meesterbouwer123** [comment]
there should be an option called "Ignore babies", which does exactly what you want

**Comment by Andboniels** [comment]
> there should be an option called "Ignore babies", which does exactly what you want

Oh yea, i thought it was under Entities, sorry about that.
