### ISSUE TITLE
meteordevelopment.meteorclient.systems add-on incompatibilites

### ISSUE THREAD

**Issue by pawa2401** [MeteorDevelopment/meteor-client#3625]
### Describe the bug

When you launch meteor with add-ons it crashes. From my tests to find out which add-on causes the issue, I found out that there were multiple add-ons that have this incompatibility. This error doesn't show up on the 1815 dev build (the newest sodium compatible version before the fix was implemented). Please make it so that these add-ons can work again, since some add-ons that were not updated in a while, still worked.

Two types of errors I encountered:
First:
`java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command`
and second 
`java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.isActive(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null`

Also, I've seen this in an old closed bug report, but it was marked as complete without any solutions, and since this affects most of the add-ons, It's worth looking into

Here is a table listing almost all add-ons with the errors and what versions the addons were ment for (they work on newer versions)
```

add-on		Pass?		Add-on for?
---------------------------------------------
bidoof		ERROR 1		1.19.2
tanuki		ERROR 1		1.19.3
crash		ERROR 1		1.19.3
meteorist		ERROR 1		latest
blackout		ERROR 1		latest
rejects		ERROR 1		latest
plus			ERROR 1		latest
trouser		ERROR 1		latest
numby		ERROR 1		latest
vector		ERROR 1 	        latest
utils			ERROR 2	        latest
higtools		clear		        latest
printer		clear		        latest
orion		clear		        latest
roller		clear		        latest
reaper		clear		        latest

```
If it's something on my part, please inform me of the potential cause.

### Steps to reproduce

```bash
1. Run minecraft with: (meteor-client, fabric-api, sodium, and one or more of the addons that are incompatible)
2. Crash
```

### Link to crash report/log if applicable (https://mclo.gs)

1st: https://mclo.gs/l7wYcdY /// 2nd: https://mclo.gs/40H071A

### Meteor Version

meteor-client-0.5.3-1834

### Minecraft Version

1.19.4, fabric 0.14.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
The addon developers are responsible for update to latest Meteor versions. We can't just keep backwards compatibility forever, software needs to move on.
