### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by ImInTheICU** [MeteorDevelopment/meteor-client#3627]
### Describe the bug

```
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command
Exit -1
```
Happens when trying to load Meteor using Forge (confirmed this worked 2 days ago and now started having the problem)

### Steps to reproduce

Using Forge to load Meteor.
Worked for 2-3 days then recently started getting the error.

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/brDmawH

### Meteor Version

Dev Build 0.5.3 [1.19.4]

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ImInTheICU** [comment]
Thought I fixed it, but re-appeared.

Stopped using CurseForge and used Fabric but it still happening.

**Comment by Wide-Cat** [comment]
There was a recent change which caused some addons to break. Either update your addon so it's compatible with the latest build, or remove it
