### ISSUE TITLE
Optifine also is not compatible

### ISSUE THREAD

**Issue by Smartiboi** [MeteorDevelopment/meteor-client#3628]
### Describe the bug

optifine is not working and tellling that optifabric won't work with meteor plz fix this either do sodium or optifine some players also have low end pc's for them plz look out

### Steps to reproduce

```bash
-_-
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead2** [comment]
Buy a better pc and use sodium

**Comment by Smartiboi** [comment]
sodium is not working tooo

**Comment by I-Got-You-Dead2** [comment]
So fix it

**Comment by Wide-Cat** [comment]
It should work with sodium; make sure you're using the correct version. For 1.19.3 I think you need to use 0.4.9
