### ISSUE TITLE
[Suggestion] Fish movement module

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#363]
**Describe the feature**
Addition of the fish module.
It basically disables underwater gravity, preventing the player from sinking (like in creative for example).
The player is able to go down by pressing the crouch button and go up by pressing the spacebar.

**Screenshots**
![2021-03-28 19_39_02-Minecraft_ 1 16 5 - Singleplayer](https://user-images.githubusercontent.com/52252627/112761827-54f87900-8ffd-11eb-98e0-93f11233d97f.png)

**Additional info**
Source code from Wurst's version of the module:
https://github.com/Wurst-Imperium/Wurst7/blob/a1adc128622fe6f8162e1fd922db6706b9b44c99/src/main/java/net/wurstclient/hacks/FishHack.java

**Comment by AstroOrbis** [comment]
I'll implement it!

**Comment by AstroOrbis** [comment]
Harder than I thought, but still tryna get it done... it won't build on my system but Gradle works fine on github actions, so thats poggers, you can follow along with all my trash code [here](https://github.com/AstroOrbis/meteor-clien).

**Comment by AstroOrbis** [comment]
#381 fixes this :)

**Comment by RedCarlos26** [comment]
This can be closed @Lovecrafts-Cat
