### ISSUE TITLE
[Suggestion] Meteor Client for Forge

### ISSUE THREAD

**Issue by LapizPlayz** [MeteorDevelopment/meteor-client#3635]
### Describe the feature

There's Fabric Meteor Client, now where's the Forge one?
Okay, I mostly use forge for modding but there's no Meteor Client for Forge, so just add one.
This is mostly under development for a long time, like it takes a few weeks (I think) to make it. But to access it, it may be _**paid**_ or just **"free"**?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by LapizPlayz** [comment]
pls delete if this is already made

**Comment by I-Got-You-Dead2** [comment]
Literally go die a long, painful death

**Comment by GreemDev** [comment]
Yes, let's port something that works perfectly fine on a superior modding platform to a worse modding platform just for you

shut up

**Comment by Big-Iron-Cheems** [comment]
> Just make it for forge too!

You have no idea of how much dev time would be wasted to do that. The way Meteor uses the Fabric API makes it impossible to port it to another totally different API.

> It takes a few weeks.
You clearly don't know what you're talking about.
I won't bore you with the details of how wrong that statement is.

We have no interest in supporting an old, slow to update and overall inferior mod loader. The project is open source and free to use/modify, so feel free to make a fork, learn Java and develop it yourself if you feel inclined to do so.

**Comment by ssaagamemer** [comment]
i think he hate fabic why fabic is good for mods and has op performance mod like sodium
