### ISSUE TITLE
Incompatibility with Sodium/Sodium mods

### ISSUE THREAD

**Issue by vanillyn** [MeteorDevelopment/meteor-client#3636]
### Describe the bug

On the latest release version (1.19.4), the latest version of meteor (0.5.3), and the latest version of sodium (0.4.11+build.26) there is a certain crash where it seems sodium can not load class: 
`me/jellysquid/mods/sodium/client/render/vertex/VertexFormatDescription/BufferWriter` 
which causes the fatal error: 
`java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.utils.render.MeshVertexConsumerProvider$MeshVertexConsumer failed`
which does mention:
`at meteordevelopment.meteorclient.systems.modules.render.StorageESP.<init>(StorageESP.java:156)`
It does not seem to be a sodium issue, as disabling meteor causes it to work

### Steps to reproduce

```bash
Using latest build of Meteor and Sodium with latest release version of Minecraft.
Modlist: https://paste.rs/JXr
```

### Link to crash report/log if applicable (https://mclo.gs)

https://paste.rs/OJK

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### System info

Linux
Using launcher `prismlauncher` version 6.3 from [AUR](https://aur.archlinux.org/packages/prismlauncher) on Arch Linux rolling (linux-6.2.13.arch1-1) using OpenJDK 17

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
this crash should be fixed as of the latest dev build, make sure you're updated

**Comment by vanillyn** [comment]
using the latest dev build, it does not work 
i've tried loading the latest dev build with the same modlist, and it crashes with said error

**Comment by darius172** [comment]
@vanillyn Is there a solution found ? I have the same issue .

**Comment by NeLagina** [comment]
the sodium [Sodium 0.5.0](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.0) crashes 
but [Sodium 0.4.10](https://modrinth.com/mod/sodium/version/mc1.20-0.4.10) works
