### ISSUE TITLE
Can't use x-ray with opacity more that 1!

### ISSUE THREAD

**Issue by Quocnam201010** [MeteorDevelopment/meteor-client#3638]
### Describe the bug

When I use X-ray with opacity value 1, everything look like I haven't turned on X-ray. When I set the opacity to 0. I can x-ray like normal. I use Sodium, Starlight, Sodium Extra.

### Steps to reproduce

```bash
Maybe one of these mod, Sodium, Starlight and Sodium Extra causes it.
```

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by I-Got-You-Dead2** [comment]
Update

**Comment by ManticoreV101** [comment]
**_No shit._**
Opacity controls the transparency of the blocks. So if you set it to 1, that disables transparency completely.
