### ISSUE TITLE
Cant open minecraft whit meteor client

### ISSUE THREAD

**Issue by SusgUY446** [MeteorDevelopment/meteor-client#3641]
### Describe the bug

Cant start minecraft fabric whit meteor client in the mods folder

### Steps to reproduce

```bash
Put the meteor client.jar in the mods folder
Then start minecraft whit fabric
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/wxUMfkm

### Meteor Version

1.19.3

### Minecraft Version

1.19.4 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Attach a full crash report

**Comment by SusgUY446** [comment]
I fixed it
The problem was hat i had the wrong version of the fabric api
