### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shadowplayZz00** [MeteorDevelopment/meteor-client#3645]
### Describe the bug

While playing if I have a diamond pickaxe in my hot bar and i try to move it into my inventory swapping it with something else it teleports back to my hot bar and i cant do anything about it 

### Steps to reproduce

```bash
Moving items like tools or blocks from my hot bar to my inventory it swaps back to how it was
```

### Meteor Version

 version 1.19.4

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Pxddyk45** [comment]
type `#allowInventory` in chat

**Comment by shadowplayZz00** [comment]
Thank you for the help 😁
