### ISSUE TITLE
Baritone won't work if Immersive Portals is installed

### ISSUE THREAD

**Issue by AdolfRoxler** [MeteorDevelopment/meteor-client#3649]
### Describe the bug

Let's say you want to mine stone, well shit, you're in bad luck, your character won't move and thinks everything's unaccessible

### Steps to reproduce

```bash
Install Meteor and install Immersive Portals.

Good job, you rendered Baritone useless.
```

### Meteor Version

0.5.3-1838

### Minecraft Version

1.19.4

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Report this issue on the baritone GitHub page

**Comment by BDARmech** [comment]
That the gentleman that is causing havoc?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
