### ISSUE TITLE
[SUGGESTION] Auto-Unscramble Bot

### ISSUE THREAD

**Issue by skunkiesonpatrol** [MeteorDevelopment/meteor-client#365]
**Describe the feature**
A toggleable feature which will auto unscramble messages from plugins such as "[ChatReaction](https://www.spigotmc.org/resources/chatreaction.3748/)" or "[Unscramble](https://dev.bukkit.org/projects/unscramble)". Feature should come with a customizable unscramble interval so you are not exposed in chat for solving it within 0.05 seconds or something crazy, also a setting that adds percentage to attempt unscrambling would be nice so you don't likely do 100% of every received unscramble event in chat leaving chance for others.

**Screenshots**
![87b2b1cd1e1d3347f55d30eaf7244e28443a462c](https://user-images.githubusercontent.com/81548070/112788529-93eb0500-90b7-11eb-83a9-8a317347fc99.gif)
GIF taken from the ChatReaction plugin website, though I do hope my description is self-explanatory.

**Comment by RedCarlos26** [comment]
@seasnail8169 this will not be added am I right?

**Comment by seasnail8169** [comment]
Yeah most likely not

**Comment by RedCarlos26** [comment]
This is probably a wont fix

**Comment by RedCarlos26** [comment]
This can probably be closed @skunkiesonpatrol
