### ISSUE TITLE
Request: Lock Open key mode

### ISSUE THREAD

**Issue by TheGreenBandit** [MeteorDevelopment/meteor-client#3651]
### Describe the feature

A feature in settings where you can lock the menu key to be pressed for a certain amount of time before opening, making it harder for people to trace you.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Pxddyk45** [comment]
Why should it be hard for people to trace you?

**Comment by TheGreenBandit** [comment]
> Why should it be hard for people to trace you?

Just incase your on a friend's server and they don't want you utilizing software.

**Comment by Pxddyk45** [comment]
> > Why should it be hard for people to trace you?
> 
> Just incase your on a friend's server and they don't want you utilizing software, and they implement checks such as sharing screen etc.

meteor is made for anarchy servers and servers that allow it

**Comment by BDARmech** [comment]
Is a vacuum a thing? If it is can it be everywhere, and nowhere at once?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
