### ISSUE TITLE
Baritone compatibility fix with Immersive Portals

### ISSUE THREAD

**Issue by AdolfRoxler** [MeteorDevelopment/meteor-client#3653]
### Describe the feature

So, Baritone doesn't work if Immersive Portals is installed.

Not to worry though, there's a solution: https://github.com/cabaletta/baritone/pull/2430

Thing is, I don't know where the stupid baritone api is located in meteor. Nothing shows up. If I did, I would've already conmited a fix for meteor.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Talhoid** [comment]
baritone is a dependency of meteor
but uhhh
why are you using meteor with immersive portals

**Comment by AdolfRoxler** [comment]
Playing on a modded minecraft server

**Comment by BDARmech** [comment]
> Playing on a modded minecraft server

So.. have anything like a log so that can get worked on?

**Comment by AdolfRoxler** [comment]
> > Playing on a modded minecraft server
> 
> So.. have anything like a log so that can get worked on?

You gotta understand that Baritone won't work, it won't be able to walk and will blacklist everything.

There's already a patch that works but it will never be upstreamed: https://github.com/cabaletta/baritone/pull/2430

I am too noob to figure out why gradlew doesn't work properly

**Comment by AdolfRoxler** [comment]
stupid github with close with comment

**Comment by SpomJ** [comment]
Well you probably should go to baritone, not meteor then?

**Comment by Wide-Cat** [comment]
If baritone merges the pr then reopen this issue and we can update it

**Comment by AdolfRoxler** [comment]
> Well you probably should go to baritone, not meteor then?

I specifically suggested here because of a reason my guy
