### ISSUE TITLE
Meteorist doesn't work.

### ISSUE THREAD

**Issue by drakfreddy** [MeteorDevelopment/meteor-client#3655]
### Describe the bug

It doesn't work on the latest dev builds ".38 .39"

### Steps to reproduce

```bash
Open minecraft with meteorist and the latest dev builds, doesn't work.
```

### Meteor Version

meteor client v0.5.3 build #1839

### Minecraft Version

1.19.4 FABRIC

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Contact the addon developers about this, not us
