### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ItzJapp** [MeteorDevelopment/meteor-client#3660]
### Describe the bug

When I try to use X-ray in 1.19.4 The X-ray doesn't work. All the blocks are visible and non full blocks like grass are glitched and you can see though them like you do in spectator mode.

### Steps to reproduce

```bash
Download the meteor 1.19.4 and start it.
```

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Send a list of your mods

**Comment by ItzJapp** [comment]
![Capture](https://github.com/MeteorDevelopment/meteor-client/assets/133631918/56f44431-0649-43dc-8d05-1a3cdbe69596)

**Comment by ItzJapp** [comment]
It works for me in 1.19.2 but not 1.19.4. I dont know about 1.19.3

**Comment by ItzJapp** [comment]
> Send a list of your mods

Do you know how can I fix this

**Comment by Wide-Cat** [comment]
Try setting the opacity setting to 0

**Comment by ItzJapp** [comment]
> Try setting the opacity setting to 0

![Capture](https://github.com/MeteorDevelopment/meteor-client/assets/133631918/b1036593-6494-4fce-b540-8cf3675a55c8)
Still dont work

**Comment by I-Got-You-Dead2** [comment]
Fucking idiot

**Comment by I-Got-You-Dead2** [comment]
You selected every block retard

**Comment by ItzJapp** [comment]
> You selected every block retard

Thats not every block you dumb

**Comment by ItzJapp** [comment]
> You are autism

Stop being toxic

**Comment by ItzJapp** [comment]
> Try setting the opacity setting to 0

can u tell how can i fix  i tried opacity it dont work

**Comment by I-Got-You-Dead2** [comment]
Deselect every block then opacity to 0

**Comment by I-Got-You-Dead2** [comment]
Dense mf

**Comment by ItzJapp** [comment]
> Collaborator

Can you tell me how to fix

**Comment by Mrtach** [comment]
Continuity mod it's what causing xray don't work, try disabling it( disable the whole mod, not the settings of it)

**Comment by minhperry** [comment]
> It works for me in 1.19.2 but not 1.19.4. I dont know about 1.19.3

Can confirm on 1.19.3, I also only have Lithim, Sodium and Starlight

**Comment by ManInMyVan** [comment]
> You are autism

Nice grammar
