### ISSUE TITLE
[Suggestion] Make meteor injectable or work with solar tweaks

### ISSUE THREAD

**Issue by HarshNoobXD** [MeteorDevelopment/meteor-client#3667]
### Describe the feature

Like you can make it for some money but give me for free cuz I suggested 

Thanks

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
?

**Comment by Shrecknt** [comment]
Solar tweaks point and laugh

**Comment by Pxddyk45** [comment]
> Like you can make it for some money but give me for free cuz I suggested

LMAO

**Comment by I-Got-You-Dead2** [comment]
Wow
