### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NotPlatzer** [MeteorDevelopment/meteor-client#367]
**Describe the bug**
the module search shows up twice when searching! (Meteor 0.4.2)

**To Reproduce**
1. Go to click gui
2. Click on 'search modules'
3. Type: block
4. See search twice

**Expected behavior**
the module search shows up twice when searching
**Screenshots**
![Bild_2021-03-29_120012](https://user-images.githubusercontent.com/61647453/112820832-50c46e00-9086-11eb-9501-5259470ffb70.png)

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by MineGame159** [comment]
Its working as it should. If you actually read the text on your screen you will notice that the first module is under Modules section, the second is under Settings section. So that means there is a setting that has the word `block` inside its name and the setting is inside StorageESP module.
