### ISSUE TITLE
[Suggestion] nohurtcam

### ISSUE THREAD

**Issue by gliex123** [MeteorDevelopment/meteor-client#3672]
### Describe the feature

pls add back the nohurtcam that when u take damage ur screen won't shake. make many button for like crystal damage fire damage fall damage 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
its a vanilla feature now, check the accessibility settings
