### ISSUE TITLE
[Bug / Error] Error when starting minecraft with meteor client

### ISSUE THREAD

**Issue by TBAProgramming** [MeteorDevelopment/meteor-client#3673]
### Describe the bug

![image](https://github.com/MeteorDevelopment/meteor-client/assets/121028379/7496e48b-7230-49ff-bdb1-f95bce05615d)

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.utils.render.MeshVertexConsumerProvider$MeshVertexConsumer failed

when i opening server

### Steps to reproduce

```bash
download latest version of fabric and meteor client
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/ejvfrac

### Meteor Version

Dev Build 0.5.3 [1.19.4]

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by TBAProgramming** [comment]
can someone help me?

**Comment by Wide-Cat** [comment]
Use sodium 0.4.10

**Comment by TBAProgramming** [comment]
oh

**Comment by TBAProgramming** [comment]
i  gonna try again
