### ISSUE TITLE
[Bug] video card driver crash

### ISSUE THREAD

**Issue by amogusussybaka** [MeteorDevelopment/meteor-client#3681]
### Describe the bug

(sorry if my english is suck)
i dunno if this is a bug or i should need a new video card driver
Everytime i launch minecraft with meteor, it crash.
but when i replace meteor with wurst (the hack client) and launched minecraft, it work perfectly, no crash,

the crash shoud look like this
![Opera Instantâneo_2023-05-26_184606_www youtube com](https://github.com/MeteorDevelopment/meteor-client/assets/111032942/da45b402-6321-40bd-9ffa-ef2870bb3e94)

### Steps to reproduce

```bash
When u have meteor in ur mods paste
and u launched minecraft
it crash
(ned a potato pc)
```

### Link to crash report/log if applicable (https://mclo.gs)

wat

### Meteor Version

1.19.3 and 1.19.4 both no work

### Minecraft Version

1.19.3 and 1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
We do not support TLauncher, or any cracked launcher for that matter.
The issue is also not related to Meteor.
