### ISSUE TITLE
Meteor Crashing

### ISSUE THREAD

**Issue by raffy309** [MeteorDevelopment/meteor-client#3684]
### Describe the bug

meteor crashes when i try to run the modpack, i have tried remove a lot of mods but nothing works

### Steps to reproduce

```bash
i have no idea how
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/Z5V5pJq

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by raffy309** [comment]
i didn't find anyone who was talking about the same version of sodium so i considered that it is was something complete different

**Comment by Wide-Cat** [comment]
Meteor doesn't work on quilt right now, you gotta use fabric instead

**Comment by raffy309** [comment]
oh, i wish it did

**Comment by raffy309** [comment]
> Meteor doesn't work on quilt right now, you gotta use fabric instead

does that mean that it may be supported in the future

**Comment by Wide-Cat** [comment]
It's not impossible that it could be fixed, but in all honesty don't hold your breath

**Comment by raffy309** [comment]
okay thanks for the information
