### ISSUE TITLE
killaura works extremely bad on test.2b2t.org

### ISSUE THREAD

**Issue by UnknownAstronaut** [MeteorDevelopment/meteor-client#369]
**Describe the bug**
Hill aura hits air and can't damage the player

**Expected behavior**
Make it hit players,

**Comment by RedCarlos26** [comment]
It is a config or anti-cheat issue. Meteor kill aura works fine.

**Comment by AstroOrbis** [comment]
Can confirm, it works perfectly on all the servers I've tested it on. Please close if you have no further comment.

**Comment by seasnail8169** [comment]
Mr Issue Manager above

**Comment by RedCarlos26** [comment]
> Mr Issue Manager above

Huh?

**Comment by AstroOrbis** [comment]
> Mr Issue Manager above

Tryna get everything sorted lmao... the KA on the client is actually probably one of the best I've seen so...

**Comment by RedCarlos26** [comment]
Yes meteor la is really good

**Comment by RedCarlos26** [comment]
This is not a bug, it is a anti-cheat related issue (or config issue). @seasnail8169

**Comment by RedCarlos26** [comment]
I would say this is a wont fix. We can close it @UnknownAstronaut

**Comment by supakeks** [comment]
> **Describe the bug**
> Hill aura hits air and can't damage the player
> 
> **Expected behavior**
> Make it hit players,

? It hits players, it's just that 2b has an anticheat.

If you have criticals on, turn it off, current Meteor crits don't work on 2b/updated ncp
Also, get the latest dev build in the discord server's dev-builds channel and in kill aura make the rotation mode "Always"

**Comment by RedCarlos26** [comment]
2b test server is not even online anymore.

**Comment by RedCarlos26** [comment]
I guess this can probably be closed
