### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Shibaso** [MeteorDevelopment/meteor-client#3692]
### Describe the feature

How to play this client with optifine i use optifabric and it crash

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by FlightXamb** [comment]
Bruh optifine is really bad use sodium 0.4.10

**Comment by Big-Iron-Cheems** [comment]
Optifine (and by consequence, Optifabric) are not supported as they mess with rendering in an invasive manner.

If you need performance, you can download mods like [Sodium](https://modrinth.com/mod/sodium/versions?g=1.19.4&g=1.19.3).
If you need shaders, you can download [Iris](https://modrinth.com/mod/iris/versions?g=1.19.4&g=1.19.3).
