### ISSUE TITLE
Add a secret message that gets sent to logs

### ISSUE THREAD

**Issue by EnvisagedMyron** [MeteorDevelopment/meteor-client#3695]
### Describe the feature

Basically whenever a person starts minecraft with meteor client on , meteor will generate a normal message like "I love minecraft" or something. This would be helpful for catching people using meteor client when they submit unban appeals. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
I think someone is missing eyes

**Comment by Wide-Cat** [comment]
Meteor already leaves a bunch of messages in your log file when loading
