### ISSUE TITLE
Minecraft crashing with sodium and iris

### ISSUE THREAD

**Issue by brickyosu** [MeteorDevelopment/meteor-client#3698]
### Describe the bug

i put sodium and iris into minecraft, i tried to open it but it crashed. i tried sodium 0.4.10 and it crashes, sodium 0.4.11 also crashes!

sodium 0.4.10:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/85379324/695f4128-b2d9-48ce-bc18-ec8e70b4a1b9)

sodium 0.4.11:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/85379324/5ed3b0e8-fad1-41bf-9bc2-855beeb314f9)

### Steps to reproduce

```bash
download sodium and meteor client, and run the game (also go to a world)
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/u2kNBXq

### Meteor Version

0.5.3 for 1.19.4

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Update to the latest dev build, and use sodium 0.4.10. If it then crashes with something about not finding commands, you'll need to update your addons as well.

**Comment by brickyosu** [comment]
im SO sorry for the very late response, but the latest dev build is meteor 0.5.3?

**Comment by brickyosu** [comment]
NVM, i had to go to the discord server for dev builds, ty!

**Comment by brickyosu** [comment]
I updated to build 1846 with sodium 0.4.10 and iris 1.6.4, now it says this:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/85379324/b88bdbfe-fedf-4f63-abf4-9f7b981f7cdb)

**Comment by brickyosu** [comment]
(still 1.19.4)

**Comment by brickyosu** [comment]
now when i try joining my friend's server, it crashes. i have meteor rejects addon on latest dev build and my meteor client on the latest dev build on their discord. it just says the exit code -1 thing
