### ISSUE TITLE
.enchant command bug

### ISSUE THREAD

**Issue by Little-Night-Wolf** [MeteorDevelopment/meteor-client#3702]
### Describe the bug

When you use the command ".enchant all/all_possible" it doesen't work

### Steps to reproduce

```bash
I was using the command to max a sword in my server for kill in 1 click and it doesen't work
```

### Link to crash report/log if applicable (https://mclo.gs)

no crash

### Meteor Version

0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Meesterbouwer123** [comment]
please give some more information:
- what exactly did you do
- were you in creative mode or not

without this information we can't help

**Comment by Wide-Cat** [comment]
What does it say in the chat when you try to use the command? Also if you want a sword powerfull enough to instakill someone, you need to specificy it with a high level - like `.enchant one minecraft:sharpness level 255`

**Comment by Little-Night-Wolf** [comment]
I was in a server and i test it in survival when i try to use the enchant all or the enchant all_possible it says that is a problem

**Comment by Wide-Cat** [comment]
It requires creative mode

**Comment by Little-Night-Wolf** [comment]
I have creative
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52613531/fd0a43cb-720b-4c60-bb96-c6363d46788e)

**Comment by Little-Night-Wolf** [comment]
sorry it was a mistake i am so sorry thanks
