### ISSUE TITLE
[Bug] Game crashes during initialisation

### ISSUE THREAD

**Issue by Susmaster64** [MeteorDevelopment/meteor-client#3703]
### Describe the bug

On version dev 0.5.3-1846, the game fails to start.
A crash occurs when initialising currently active modules, due to `java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "$$1" is null` error, whilst running on prismlauncher (Multimc fork). I have already checked, this is not a problem with fabric as fabric runs fine and vanilla 1.19.4 runs fine. Game loads fine when no modules are active.
Active modules for crash to occur: https://drive.google.com/file/d/11nhpUxy5Mqz_dlMeTEzOWIOheCa_eA-P/view?usp=sharing (modules nbt)

(my guess is that its the highway builder)

### Steps to reproduce

```bash
Try launch the game on dev 0.5.3-1846 with modules nbt.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://pastebin.com/9RJd99bT

### Meteor Version

0.5.3 Dev build 1846

### Minecraft Version

1.19.4

### Operating System

Linux

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Delete your modules.nbt to resolve this issue. I might take a look at resolving the underlying problem later.

**Comment by Susmaster64** [comment]
> Delete your modules.nbt to resolve this issue. I might take a look at resolving the underlying problem later.

I have already done this and I am reporting the issue to help others who may have the same problem

**Comment by GoofyBoi420** [comment]
delete system 32, i also had this issue

**Comment by Wide-Cat** [comment]
should be fixed 30437a09b9a0f89f6fc5421d4faa3b6db778dc02
