### ISSUE TITLE
Gradle being gay

### ISSUE THREAD

**Issue by cu-m** [MeteorDevelopment/meteor-client#3705]
### Describe the bug

Gradle wont build it. info: https://scans.gradle.com/s/t6iqxjjocijym

### Steps to reproduce

```bash
just build it.
```

### Meteor Version

dev

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/1a7e8987-1e53-4b3c-a716-d991349c9727)
Works on my machine, JAR correctly built in the `build\libs` folder.
Be sure that you have a system install of Java 17 to build Meteor from source.

**Comment by Ompyl** [comment]
If it still doesn't work, you can try to use wsl to build it, that has always worked for me

**Comment by GoofyBoi420** [comment]
delete system 32, i also had this issue

**Comment by Big-Iron-Cheems** [comment]
Closed for inactivity.
