### ISSUE TITLE
1.20 Update

### ISSUE THREAD

**Issue by Ebanytiy** [MeteorDevelopment/meteor-client#3707]
### Describe the feature

1.20 Update

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Pxddyk45** [comment]
It literally released like 2 hours ago

**Comment by TutorFx** [comment]
Auto Archeology :)

**Comment by Susmaster64** [comment]
Auto and anti-crystal shield?
