### ISSUE TITLE
Auto totem

### ISSUE THREAD

**Issue by Mipeonneekeri** [MeteorDevelopment/meteor-client#3711]
### Describe the feature

I would like the auto totem so that it has such a setting that it opens the inventory when it puts the totem in the hand, so the anti cheat will not notice it when, for example, the doutsmp has such an anticheat.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
In case you didn't read our FAQ, we're not interested in developing bypasses, especially for non-anarchy servers.
