### ISSUE TITLE
[Suggestion] Add villager Enchantment trading to baritone

### ISSUE THREAD

**Issue by Dupernite** [MeteorDevelopment/meteor-client#3712]
### Describe the feature

Add a command to baritone to automatically check if the villager has X enchantment to trade and if not break and replace the lectern to reset trade and loop until the villager has the trade 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by JACKKY04** [comment]
There is an add on: https://github.com/maxsupermanhd/meteor-villager-roller
Website of several other add ons: https://anticope.ml/addons/

**Comment by Shrecknt** [comment]
If you want a feature added to baritone, this is the wrong place to ask for it.
Baritone is an entirely separate project maintained by a separate group of people, and just happens to be bundled with meteor.

**Comment by Big-Iron-Cheems** [comment]
I won't repeat what the others said, they're completely right.
