### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by kplopbob** [MeteorDevelopment/meteor-client#3713]
### Describe the feature

i think you should add search back to meteor client because you could search for any block instead of just ores

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
It's still there, it was renamed to Block ESP...
