### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by SnakyExotic** [MeteorDevelopment/meteor-client#3718]
### Describe the bug

Games crashes when I try to load into a 1.20 creative world. I am not sure if this applies to survival too, so someone would have to test it out. Could be one of my modules causing this, link to my crash log is below.

### Steps to reproduce

```bash
> Open minecraft
> Create a Creative world 
> Join 
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/DFPFi6J

### Meteor Version

meteor-client-0.5.4-1849

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GoofyBoi420** [comment]
delete system 32, i also had this issue

**Comment by GoofyBoi420** [comment]
closed for inactivity/ retard

**Comment by GoofyBoi420** [comment]
?close

**Comment by BDARmech** [comment]
>
\/ retard
this thread is retarded . \

**Comment by Big-Iron-Cheems** [comment]
Cannot reproduce on my end. The stacktrace doesn't even really mention Meteor, so the cause could be something else.

Also, I noticed that in your launch options you limited Minecraft to use at most 2Gb of RAM.
You could increase that by replacing the number in `-Xmx2G`, maybe with 4, and see if this solves it for you.
