### ISSUE TITLE
Minor Typo In Stash Finder

### ISSUE THREAD

**Issue by RewardedIvan** [MeteorDevelopment/meteor-client#3719]
### Describe the bug

In stash finder, there is a setting called `Minimum Storage Cont`

### Steps to reproduce

```bash
open the settings of stash finder
```

### Meteor Version

commit 531155c (and possibly later)

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GoofyBoi420** [comment]
closed for inactvity

**Comment by ManInMyVan** [comment]
Too lazy to make a pull request, but it's in `\src\main\java\meteordevelopment\meteorclient\systems\modules\world\StashFinder.java` on line 51
