### ISSUE TITLE
[BUG] Modules unload on rejoin or death

### ISSUE THREAD

**Issue by Dragonlord1005** [MeteorDevelopment/meteor-client#3720]
### Describe the bug

Seemingly randomly, whenever I die or join a server, modules will be unloaded, but will still show as enabled, disablig and renabling the module restores its functionality.

### Steps to reproduce

```bash
- Have modules enabled
- Die or leave and rejoin server
- See effect
```

### Meteor Version

0.5,3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ItzSkyReed** [comment]
Outdated meteor client

**Comment by GoofyBoi420** [comment]
delete system 32, i also had this issue
