### ISSUE TITLE
Pathfinding of Baritone doesn't jump

### ISSUE THREAD

**Issue by FabiFNA** [MeteorDevelopment/meteor-client#3726]
### Describe the bug

When Baritone is trying to figure out a path to take it will calculate a path where jumps have to be made but it won't jump. I deleted the settings file aswell just in case this is a me problem as in I messed in the settings but it doesn't seem to be.

### Steps to reproduce

```bash
Using a command like #mine calculates a path that Baritone tries to follow, but once it needs to go up a block it won't jump.
```

### Meteor Version

0.5.4

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
I don't see how this is a meteor bug. Probably you have the baritone setting 'assumeStep' set to true while not having the module enabled
