### ISSUE TITLE
[Bug] Highway Builder has issues with echest farming and autotool

### ISSUE THREAD

**Issue by ABRAoriginal** [MeteorDevelopment/meteor-client#3729]
### Describe the bug

While using Highway Builder in Dev 1852 I noticed that Highway Builder is broken in two ways and going through some older versions indicate its been broken for a while. 

First, the logic for echest farming seems to have been broken since 1.19.3. When the module runs out of obsidian it will try to mine echests in the hotbar. It will place 1 echest, mine it, and then will be unable to place more causing the player to just stand there.

The issue is that when Highway Builder encounters certain blocks where there isn't a preferred tool the module will turn itself off saying theres no suitable tool. This is an issue that pops up namely with glowstone when its encountered while building nether highways. The HIGTools addon already has a fix for this particular issue so I imagine it wouldn't be too hard to fix in base meteor.

### Steps to reproduce

```bash
Use Highway Builder and run out of obsidian to trigger the echest farming system and try to build a highway in which it would have to remove glowstone or other blocks that don't have an optimal tool for them.
```

### Meteor Version

Dev 1852

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
30437a09b9a0f89f6fc5421d4faa3b6db778dc02
