### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by toeman4033** [MeteorDevelopment/meteor-client#3733]
### Describe the feature

something cool would be able to use metor with feather. i have no clue how to do that but it would be cool

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Shrecknt** [comment]
Feather bundles optifine which is incompatible
Use a good launcher/client instead

**Comment by MineGame159** [comment]
No

**Comment by Paddyk45** [comment]
metor

**Comment by aRandomMenno** [comment]
@toeman4033 Cope.
