### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by xAffan** [MeteorDevelopment/meteor-client#3734]
### Describe the feature

just allow 1.20.1 its almost the same

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
not how it works

**Comment by MineGame159** [comment]
Done in 1417031c9cc7bee10a5db32eb0bde94627ba7fff.
