### ISSUE TITLE
[Suggestion / Enhancement] meteor / addon prefix enhancement.

### ISSUE THREAD

**Issue by aRandomMenno** [MeteorDevelopment/meteor-client#3736]
### Describe the feature

You know how Meteor Client says something in chat when you toggle a module or execute a Meteor Cmd?
They should make a module that controls that with a prefix (some Addons already have this) and make it so Addons can easily hook into this so you can have "cool" meteor prefix instead of just "meteor" for every Addon.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
Already exists, that's how other addons already do this
