### ISSUE TITLE
[Bug] keeps crashing before it opens

### ISSUE THREAD

**Issue by HarryCooper005** [MeteorDevelopment/meteor-client#374]
**Describe the bug**
when I click play in the minecraft launcher, the green bar completes there then the launcher closes like normal then after a few seconds it crashes.

**To Reproduce**
1. click play on the minecraft launcher

**Expected behavior**
for meteor to open normally

1.16.5, latest meteor version as well as latest fabric and fabric api version

[crash-2021-03-30_12.52.24-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6228904/crash-2021-03-30_12.52.24-client.txt)

**Comment by MineGame159** [comment]
For the book dupe addon to work you need a dev build of Meteor. To get it either build it yourself or go to Meteor discord.

**Comment by HarryCooper005** [comment]
> For the book dupe addon to work you need a dev build of Meteor. To get it either build it yourself or go to Meteor discord.

ah sorry for the inconvenience. thanks
