### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Sturdy122** [MeteorDevelopment/meteor-client#3742]
### Describe the feature

Add schematica/litematica to meteor 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Just use the mod seperately
