### ISSUE TITLE
Improvement for ghosting.

### ISSUE THREAD

**Issue by aRandomMenno** [MeteorDevelopment/meteor-client#3744]
### Describe the feature

Remove the keybinds from meteor client from the keybinds menu.
![Remove-this](https://github.com/MeteorDevelopment/meteor-client/assets/109163471/9b5d81f0-c810-4e9b-8582-62e7282d5326)
This will make it a little easier to not get caught hacking in screenshare.
Maybe put the keybinds in a .txt file in the meteorclient folder.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Don't use meteor on servers that don't allow it
