### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by WitherRoom** [MeteorDevelopment/meteor-client#3746]
### Describe the feature

I need some old version of Meteor client, but i can not find it anymor (if can it so hard to find)

It great if more feature, but some old version it some better and lighter

so if u guys can, pls add a list of old version

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
[https://maven.meteordev.org](https://maven.meteordev.org)
