### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by WestinGames123** [MeteorDevelopment/meteor-client#3747]
### Describe the bug

When using surround, and activate it it can't place blocks on echests. Could you fix that?

### Steps to reproduce

```bash
standing within 1 block of an echest (above) with surround enabled
```

### Meteor Version

v0.5.2

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
unable to reproduce
