### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by hlixasd** [MeteorDevelopment/meteor-client#3749]
### Describe the feature

Auto Wool Sheerer

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by TheKidThatCodes** [comment]
Maybe just an auto right click mobs feature, could be used for other things too

**Comment by BDARmech** [comment]
you're finger not workin? Why can't you right click for 💩

**Comment by hlixasd** [comment]
> you're finger not workin? Why can't you right click for 💩

you can breed with ur fingers too

**Comment by TheKidThatCodes** [comment]
this would be usefull tho

**Comment by ManInMyVan** [comment]
> you're finger not workin? Why can't you right click for 💩 

*Your

**Comment by Wide-Cat** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/74723656/3a70e86f-5213-4789-a4d2-e51641990d32)
