### ISSUE TITLE
[Suggestion] Orebfuscator

### ISSUE THREAD

**Issue by Theyes69** [MeteorDevelopment/meteor-client#375]
If the spigot plugin is enabkes for anti xray then when you mine a "fake ore" it turns real into your inventory 

This might work or not i highly doubt it because of future having it and it being based in 1.12

**Comment by RedCarlos26** [comment]
I am not sure this is possible. @seasnail8169?

**Comment by jackiboi307** [comment]
can't you at least try? it exists in future https://www.futureclient.net/features.php and it works.
someone on reddit said it does it by holding packets.
