### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command

### ISSUE THREAD

**Issue by RAGEJames** [MeteorDevelopment/meteor-client#3750]
### Describe the bug

Help, i have meteor client 0.5.3 and i have some addons but it will crash when i load the launcher. it prompts me with a message saying The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command error code -1

### Steps to reproduce

```bash
go to https://mclo.gs/IHft4aI and read steps.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/jKcGcBw

### Meteor Version

0.5.3

### Minecraft Version

1.19.4 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RAGEJames** [comment]
my mods, ![Screenshot 2023-06-18 210427](https://github.com/MeteorDevelopment/meteor-client/assets/137014538/9aca355d-441b-4fa0-8811-6ab1c340cc84)

**Comment by GreemDev** [comment]
> my mods, ![Screenshot 2023-06-18 210427](https://github.com/MeteorDevelopment/meteor-client/assets/137014538/9aca355d-441b-4fa0-8811-6ab1c340cc84)
> 
> 

tell the author(s) of these to update (or download the newest version if they've already done so) or remove the addons. meteor changed something and addons haven't changed to accommodate.

**Comment by Npro154** [comment]
Vector and meteor-utils are not compatible with the last version.Remove them from the folder and wait for an update
