### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Yagyiko7** [MeteorDevelopment/meteor-client#3752]
### Describe the bug

the baritone in the meteor is not able to mine deepslate ores pls fix it

### Steps to reproduce

```bash
when i used #mine deepslate_diamond_ore
```

### Meteor Version

1.19.4

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Works for me, I've been using it for months with no issues.
