### ISSUE TITLE
aim assist

### ISSUE THREAD

**Issue by ae23rn7diu2** [MeteorDevelopment/meteor-client#3754]
### Describe the bug

When I search up aim assist it is not there 1.20

### Steps to reproduce

```bash
I need help
```

### Meteor Version

0.5.4

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
It was removed, just use killaura
