### ISSUE TITLE
[Bug] trajectories does not account for power enchantment

### ISSUE THREAD

**Issue by randomstuff69** [MeteorDevelopment/meteor-client#3756]
### Describe the bug

the bow overshoots where the trajectories hack says it will go when power enchantment, if possible make it calculate where it will go with power enchantment

### Steps to reproduce

```bash
when i shoot a bow with power (255) and the trajectory hack is on it goes overshoot where it says it will end up it probably is the same with any power enchantment
```

### Meteor Version

idk

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
the power enchantment doesnt change the trajectory of an arrow?
