### ISSUE TITLE
remove the thing on the thread on the disord its kinda annoying

### ISSUE THREAD

**Issue by randomstuff69** [MeteorDevelopment/meteor-client#3757]
### Describe the feature

https://discordapp.com/channels/689197705683140636/1120891839491342426

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
?
