### ISSUE TITLE
[Suggestion] Forge

### ISSUE THREAD

**Issue by ae23rn7diu2** [MeteorDevelopment/meteor-client#3763]
### Describe the feature

Can meteor client be on forge can't install it on meteor client website.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Not gonna happen
