### ISSUE TITLE
[Suggestion] Staff Ignore

### ISSUE THREAD

**Issue by Stayrsxv** [MeteorDevelopment/meteor-client#3765]
### Describe the feature

Add a feature that immediately disconnects you every time an operator or user in creative joins, unless you have the player friended via meteor you dont leave.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Maxo6453** [comment]
Ah yes, I will just nonchalantly disconnect the millisecond an admin tps to me. Totally not suspicious.
