### ISSUE TITLE
[Suggestion] Auto Clutch

### ISSUE THREAD

**Issue by Stayrsxv** [MeteorDevelopment/meteor-client#3766]
### Describe the feature

It makes you automatically clutch such as falling and placing water automatically or boat clutching, also a blacklist where you can choose what you dont want to mlg with.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by toxicdefender404** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/87145585/e2f0e6e5-56f3-4159-bee1-2f61ef1f722b)
![image](https://github.com/MeteorDevelopment/meteor-client/assets/87145585/23412e80-914c-46bf-a5e2-e9cafe5292f1)
