### ISSUE TITLE
Jesus doesn't work on flowing water

### ISSUE THREAD

**Issue by ManInMyVan** [MeteorDevelopment/meteor-client#3771]
### Describe the bug

you bob up and down in flowing water, instead of stand on top of it (I have it set to solid mode)

### Steps to reproduce

```bash
1. turn on jesus
2. walk into flowing water
```

### Meteor Version

0.5.4 #1857

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
unable to reproduce

**Comment by etianl** [comment]
I have reproduced this and fixed it in my pull request
