### ISSUE TITLE
Basefinder Crashes after time

### ISSUE THREAD

**Issue by Jumima68** [MeteorDevelopment/meteor-client#3773]
### Describe the bug

I just fly around with Basefinder and then it MC crashes.

### Steps to reproduce

```bash
Turn on Basefinder
Fly around
```

### Link to crash report/log if applicable (https://mclo.gs)

https://paste.ee/p/wFvhh

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
Basefinder is not a meteor module. Take this problem to the GitHub for the addon it's from.
