### ISSUE TITLE
[Bug] Mobs that aren't selected in chams will show up in third person mode.

### ISSUE THREAD

**Issue by ikeafridge4** [MeteorDevelopment/meteor-client#378]
**Describe the bug**
Mobs, such as cod like shown in the screenshot, will show up in chams even though they are not selected when in 3rd person mode. 

**To Reproduce**
1. Create world
2. Enable chams and dont select any entities except player
3. Press F5 and go to 3rd person mode

**Expected behavior**
You shouldn't be able to see mobs that aren't selected in chams. 

**Screenshots**
![2021-03-30_19 39 36](https://user-images.githubusercontent.com/78064813/113082957-35458a00-9190-11eb-8989-b5da14119fdc.png)
![2021-03-30_19 39 46](https://user-images.githubusercontent.com/78064813/113082980-3f678880-9190-11eb-9730-e8f7f5a90876.png)

**Additional context**
Meteor version: 0.4.2 dev build 654. Game version 1.16.5, singleplayer

**Comment by ikeafridge4** [comment]
forgot to add mods list: 
![Screenshot 2021-03-30 194443](https://user-images.githubusercontent.com/78064813/113083087-6faf2700-9190-11eb-9244-e349d3c95308.png)

**Comment by RedCarlos26** [comment]
I cannot reproduce this bug, but what i can say is that my game experience a lot of lag when using chams,even with only players enabled.

**Comment by seasnail8169** [comment]
Its not really a bug, its just the weird nature of how chams works.
