### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Houzvicka7** [MeteorDevelopment/meteor-client#3781]
### Describe the feature

create a button that shows all download links for the older and older versions im sick and tired of trying to find meteor client 0.5.0 
on the site

### Before submitting a suggestion

- [ ] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
[https://maven.meteordev.org](https://maven.meteordev.org)
