### ISSUE TITLE
Add oresim and seedcracker

### ISSUE THREAD

**Issue by MichiEspacial** [MeteorDevelopment/meteor-client#3783]
### Describe the feature

Oresim is a solution to servers with anti-xray, using the world seed its able to simulate the ore location. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by NetheriteBlockXI** [comment]
yes add this, very useful.

**Comment by ae23rn7diu2** [comment]
Please add this

**Comment by verzout** [comment]
https://gitlab.com/69420hahafuni/LeftyDupes/uploads/468954b47b910248bc301a5d55618342/anticope-fat-pack-0.4__4_.jar

**Comment by tympanicblock61** [comment]
> https://gitlab.com/69420hahafuni/LeftyDupes/uploads/468954b47b910248bc301a5d55618342/anticope-fat-pack-0.4__4_.jar hope this help

You honestly do not want to use this, it violates copyright laws and is in no way affiliated with anticopes that's why the GitHub was dmca

**Comment by verzout** [comment]
> > https://gitlab.com/69420hahafuni/LeftyDupes/uploads/468954b47b910248bc301a5d55618342/anticope-fat-pack-0.4__4_.jar hope this help
> 
> You honestly do not want to use this, it violates copyright laws and is in no way affiliated with anticope that's why the GitHub was dmca

Thanks, but is it safe to use?

**Comment by tympanicblock61** [comment]
> > > https://gitlab.com/69420hahafuni/LeftyDupes/uploads/468954b47b910248bc301a5d55618342/anticope-fat-pack-0.4__4_.jar hope this help
> > 
> > 
> > You honestly do not want to use this, it violates copyright laws and is in no way affiliated with anticope that's why the GitHub was dmca
> 
> Thanks, but is it safe to use?

I wouldn't put it past lefty to add a rat so prob not

**Comment by bruh1273** [comment]
> > > > https://gitlab.com/69420hahafuni/LeftyDupes/uploads/468954b47b910248bc301a5d55618342/anticope-fat-pack-0.4__4_.jar hope this help
> > > 
> > > 
> > > You honestly do not want to use this, it violates copyright laws and is in no way affiliated with anticope that's why the GitHub was dmca
> > 
> > 
> > Thanks, but is it safe to use?
> 
> I wouldn't put it past lefty to add a rat so prob not

It's not a rat. That is beyond disgusting to do, and to accuse someone of that is gut wrenching.
I do not put any malware in ANY of my code, I do not even have the SKILLS to do that.
I just want to help people out.

**Comment by FlightXamb** [comment]
Hi, just use ore sim from meteor rejects addon and seedcrackerX mod.

**Comment by MentalStill** [comment]
> Hi, just use ore sim from meteor rejects addon and seedcrackerX mod.
What?

**Comment by MentalStill** [comment]
> Hi, just use ore sim from meteor rejects addon and seedcrackerX mod.


Wdym?

**Comment by FlightXamb** [comment]
> > Hi, just use ore sim from meteor rejects addon and seedcrackerX mod.
> 
> Wdym?

Use SeedCrackerX mod and meteor rejects oresim module
