### ISSUE TITLE
[Suggestion] add a baritone keybind

### ISSUE THREAD

**Issue by TunaBeef** [MeteorDevelopment/meteor-client#3785]
### Describe the feature

it could just be as simple as being able to press one key and have a stop command be sent for it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Shrecknt** [comment]
Already exists as macros

**Comment by Wide-Cat** [comment]
Remember to wrap baritone commands appropriately in macros to make sure startscript doesn't interfere with them, for example `{"stop"}`
