### ISSUE TITLE
THE ABILTY TO RESET THE GUI

### ISSUE THREAD

**Issue by cooolg** [MeteorDevelopment/meteor-client#3787]
### Describe the feature

Incase you mess up the GUI accidentally

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
There's already a chat command for that, `.reset gui`.
