### ISSUE TITLE
Hotbar items wont go to inventory (mostly pickaxes and common blocks as dirt and cobblestone)

### ISSUE THREAD

**Issue by Tikrasis** [MeteorDevelopment/meteor-client#3789]
### Describe the bug

So I don't know how this happens but, when I have installed meteor client in my mods folder this happens. I tried to delete the files of meteor profile. Even the whole folder. AND still can't fix it myself.

https://github.com/MeteorDevelopment/meteor-client/assets/137997436/fd58c360-81d8-43a6-9d48-3b4536e12450

### Steps to reproduce

```bash
I have no idea. triggers on its own.
```

### Meteor Version

1.20 and 1.19

### Minecraft Version

1.20 and 1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
`#allowInventory false`

**Comment by Tikrasis** [comment]
Where do I set it to to true though?
