### ISSUE TITLE
[Bug] Keybind Shulker Peek for tooltip mod is not saved

### ISSUE THREAD

**Issue by bartaback** [MeteorDevelopment/meteor-client#379]
When i changed the keybind for the Shulker Peek tooltip mod, it's saved, but when i restart the client, the keybind for the tooltip mod is reset (to default left alt)

**Comment by RedCarlos26** [comment]
I can confirm

**Comment by RedCarlos26** [comment]
This got fixed in build #687. This issue can be closed @bartaback.

**Comment by seasnail8169** [comment]
I dont think it did tbf, i was gonna talk to minegame about it

**Comment by RedCarlos26** [comment]
It s'emmêla to be fixed, but it's still happening with j dev build #715

**Comment by RedCarlos26** [comment]
Relates to #421

**Comment by MineGame159** [comment]
Fixed in 76e9249bf2784269b61c00676684a629046aafbf

**Comment by seasnail8169** [comment]
> Fixed in 76e9249bf2784269b61c00676684a629046aafbf

![image](https://user-images.githubusercontent.com/17166139/115513410-efee1700-a27a-11eb-80d8-c74607aa1dc7.jpeg)
