### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Maks7594** [MeteorDevelopment/meteor-client#3798]
### Describe the bug

X-Ray just doesn't work. No blocks disappear.

### Steps to reproduce

```bash
1. Enable X-Ray
2. Profit
```

### Link to crash report/log if applicable (https://mclo.gs)

It's not a crash.

### Meteor Version

0.5.4 (Latest dev build)

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Maks7594** [comment]
yeah so is anyone really gonna patch this bug?

**Comment by Wide-Cat** [comment]
Not if you continue to provide literally zero information. Send an image of your mods folder at least

**Comment by DrewskyBrewsky** [comment]
I'm having the same issue; only thing that happens when toggling x-ray is all shadows disappearing, not actually able to see whitelisted blocks through the ground

**Comment by nelex1337** [comment]
So I had the same issue and I just found a solution - just download the newest version of Fabric API. I did that and everything is now normal for me.

**Comment by BDARmech** [comment]
And none of yall 1337 script kiddies can post your mod folder, or log?

**Comment by Maks7594** [comment]
> Not if you continue to provide literally zero information. Send an image of your mods folder at least

![image](https://github.com/MeteorDevelopment/meteor-client/assets/72873506/e2a6c042-1063-4c7a-a397-e559d5ee3b5c)

**Comment by Maks7594** [comment]
> And none of yall 1337 script kiddies can post your mod folder, or log?

Yeah dude. I'm so stupid.
