### ISSUE TITLE
Add Baritone+ to meteor

### ISSUE THREAD

**Issue by BallisticJandle** [MeteorDevelopment/meteor-client#3801]
### Describe the feature

Baritone+ is a fork of baritone that can do a lot more than normal baritone! Unlike the actually Baritone, it uses **real** AI instead of just pathfind, which allows it to make its OWN decisions!

I think it would be a great addition to Meteor client and it would support the growth of the Baritone+ project! 👍
[baritone plus.zip](https://github.com/MeteorDevelopment/meteor-client/files/11933150/baritone.plus.zip)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
sus

**Comment by Big-Iron-Cheems** [comment]
1. That's literally what Altoclef does
2. There's no such thing as "real pathfinding AI", it's just like traditional Baritone, using a weight system to determine the best path
3. Sharing a random zip file is definitely not the way to suggest a project, a link to the official git repo would have been better.

Also, we rely heavily on our custom Baritone version, and don't see us switching to some random one for no reason.

**Comment by GreemDev** [comment]
https://github.com/RemainingToast/BaritonePlus/blob/master/src/main/java/baritone/plus/brain/BaritoneBrain.java#L118-L120
this is not "real AI", it doesn't even have one of the most significant parts about AI, _**LEARNING**_
