### ISSUE TITLE
Need help with activating Modules by default

### ISSUE THREAD

**Issue by ItsAMeboringguy** [MeteorDevelopment/meteor-client#3803]
### Describe the feature

How do I activate a Module by default? Like basically with DiscordRPC?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Use the profiles tab to save all your active modules, keybinds and configs.
There's a setting to automatically load said profile when joining specific servers etc.

If this was a code related question instead, look at the [preoload section](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/MeteorClient.java#L92).
