### ISSUE TITLE
[Suggestion] Add anti-sculk module

### ISSUE THREAD

**Issue by One916** [MeteorDevelopment/meteor-client#3804]
### Describe the feature

A anti sculk module prevents players from being discovered by warden, and more unlikely to get killed in the ancient city

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Maxo6453** [comment]
What would the module do, exactly? Your request is quite vague.

**Comment by Wide-Cat** [comment]
Use the sneak module, probably want to use the packet setting, also iirc the warden can still follow and detect the player when they're sneaking though smelling them or something
