### ISSUE TITLE
Anti-Levitation is missing

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [MeteorDevelopment/meteor-client#3809]
### Describe the bug

I recently downloaded meteor client for 1.20 and I couldn't find the anti-levitation module. Has it been embedded into a different module or a bug is preventing me from seeing anti-levitation or has it been removed altogether?

### Steps to reproduce

```bash
...
```

### Meteor Version

0.5.4-1853

### Minecraft Version

1.20 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Look at the potion spoof module
