### ISSUE TITLE
[Suggestion] .Enchant Command Suggestion

### ISSUE THREAD

**Issue by Ch4inP4in** [MeteorDevelopment/meteor-client#3810]
### Describe the feature

Please Remove These Enchants From the **.enchant all max**

**Because These are the Worst Possible Enchants in MC**

1. Channeling
2. Knockback
3. Thorns
4. Punch
5. Smite
6. Impaling
7. Frost Walker
8. Curse of Binding
9. Curse of Vanishing

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
if you don't want everything, you shouldn't use `all`

**Comment by FlightXamb** [comment]
> Because These are the Worst Possible Enchants in MC

Well, not for everyone, some people may need them, and as greemdev said, you shouldn't use ` all ` 
all means every enchants, not the best ones

**Comment by KlyntarXgaming** [comment]
yep and I dont think this would work anyways cause it'll just be *client-side*.

**Comment by theotherhades** [comment]
Knockback, CoV, and Thorns aren't necessarily bad idk why you've included them here
