### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by 1110noahkulit** [MeteorDevelopment/meteor-client#3811]
### Describe the feature

Similar to the hack called "Blink", this hack allows you to perform specific actions in a 1 second to 5-minute timer, once the timer runs out or you stop the timer yourself, the hack repeatedly performs that action you did over and over again until you stop it from doing it, 

(ex.) You start mining logs until your inventory is full, then you walk to a fletcher, create sticks and trade with him, you stop the timer, and the cycle repeats your actions in the timeframe and it continues until you stop it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
So... macros?

**Comment by FlightXamb** [comment]
> So... macros? Something that already exists?
Well kinda, i think he want more developed macros with like conditions, delays, if, and everything.

**Comment by ManInMyVan** [comment]
> Well kinda, i think he want more developed macros with like conditions, delays, if, and everything.

So he wants one of those Hypixel Skyblock macro clients but customizable and for 1.20 and in Meteor?

**Comment by BDARmech** [comment]
[(Application.OnTime Now + TimeValue("00:05:00"), "BestMacroEver")] it exists in some platforms. But that would play hell with trying to head off malicious things. It could cause chaos like other platforms that enable functions of that sort.
