### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by BreedeMC** [MeteorDevelopment/meteor-client#3812]
### Describe the feature

Triggerbot and more pvp/pve hacks.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by FlightXamb** [comment]
Triggerbot can be found in [Blackout addon](https://github.com/KassuK1/BlackOut) and also, explain better, which pvp modules do you need.

**Comment by ManInMyVan** [comment]
>Triggerbot

Killaura\only on look
