### ISSUE TITLE
Can you add .baritone command back?

### ISSUE THREAD

**Issue by XiaoGanCN** [MeteorDevelopment/meteor-client#3815]
### Describe the feature

If I want to mine something I just need to type .baritone mine ... 
It's easy and fast,  right?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
You can just as easily do #mine BLOCK_NAME using Baritone's official commands.

**Comment by XiaoGanCN** [comment]
Oh I forgot, my bad

**Comment by Maks7594** [comment]
sometimes if you configure baritone to use something else like & or ^ you can forget and expose yourself
