### ISSUE TITLE
Server Spoof not spoofing texture pack

### ISSUE THREAD

**Issue by unseeyou** [MeteorDevelopment/meteor-client#3817]
### Describe the bug

when I join a server with server spoof enabled, the expected output is a meteor message in chat notifying me that the server has a texture pack, however I get the normal pop up telling me to download the pack.

### Steps to reproduce

```bash
enable server spoof and join a server with a custom pack (e.g. minehut)
```

### Meteor Version

0.5.4-1862 (latest dev build)

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by unseeyou** [comment]
Other mods:
ViaVersionPlus, Sodium, Starlight, Replay Mod, Ui Utils, worldedit, WTHIT, No Chat Reports, mod menu, meteor rejects, lithium, gurkens gadetry (meteor addon), badpackets, fabric API

**Comment by unseeyou** [comment]
## Popup
![image](https://github.com/MeteorDevelopment/meteor-client/assets/84846449/4a57b0b8-dce3-4025-8d68-1d55199822e1)
## Settings
![image](https://github.com/MeteorDevelopment/meteor-client/assets/84846449/5f9648cd-ba5a-4e3b-ab2d-b4010666831a)

**Comment by unseeyou** [comment]
Still happens when gurkens gadgetry is removed so it's not that one

**Comment by Cabbasca** [comment]
disable block channels

**Comment by Fiz-Victor** [comment]
This will be fixed when the pr is merged
