### ISSUE TITLE
Baritone block clutch fail

### ISSUE THREAD

**Issue by KlyntarXgaming** [MeteorDevelopment/meteor-client#3819]
### Describe the bug

when baritone path finds it chooses to place a block on the side of an existing block and fails sometimes the pathfinding gets broken and doesn't work and I have to re-type the command

### Steps to reproduce

```bash
* find a 5 blocks wide hole and set the baritone goal to the otherside
* give the bot someblocks to place 
* do #path
* it fails and falls
```

### Meteor Version

1.20

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Fiz-Victor** [comment]
This is not baritone's repo, open this issue in their repo: https://github.com/cabaletta/baritone

**Comment by Wide-Cat** [comment]
^

**Comment by KlyntarX69** [comment]
no # it works fine on impact
