### ISSUE TITLE
[Suggestion] Bedrock Breaker Module

### ISSUE THREAD

**Issue by C0D6WasTaken** [MeteorDevelopment/meteor-client#3820]
### Describe the feature

# Feature summarized: A module that automates bedrock breaking with redstone when toggled.

I am aware that **this has been mentioned in suggestions #1518 and #3175**, but **it wasn't implemented** as there already is a [fabric mod](https://github.com/LXYan2333/Fabric-Bedrock-Miner) that does the same thing more or less.

## Why should it be implemented, then?
- The mod linked above can be considered bare bones in terms of customization, thus limiting functionality.
- It would provide additional features and functionality without much of a downside (unless you count restricted use with anti-cheats).
- Integrating such a module would increase efficiency by automating specific tasks.

### Why do I keep insisting on such a feature?
I recently found another [open-source utility client](https://github.com/DustinRepo/JexClient) with this same exact feature. Unfortunately, the mod is outdated (stuck on version 1.19.2), and I know little to nothing when it comes to coding in Java, so I cannot say much about how well everything is written.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Fiz-Victor** [comment]
This probably won't be added into meteor, but I will port that mod into rejects when I got time

**Comment by thebest9178** [comment]
I already made a meteor addon port of that fabric mod with more features [here.](https://github.com/thebest9178/Unminable-Meteor)
It's on 1.19.4 rn and I'm having trouble updating the addon to 1.20 because of gradle.

Also @Fiz-Victor if you want this in rejects I could do that or re-port it since I'm familiar with the code already. Unless you want to do it yourself.

**Comment by Fiz-Victor** [comment]
Ive actually ported about one week ago but i forgor to push it
