### ISSUE TITLE
xray now work

### ISSUE THREAD

**Issue by vladisaev12** [MeteorDevelopment/meteor-client#3822]
### Describe the bug

dev build xray not work right its make block wireframe show ores through now the whole block(sorry for my bad english)

### Steps to reproduce

```bash
just turn on xray on minecraft 1.20 dev build
```

### Meteor Version

0.5.4

### Minecraft Version

1.20

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Paddyk45** [comment]
do you have sodium or any other mods?

**Comment by ManInMyVan** [comment]
> 0.5.4

Specify dev build

**Comment by vladisaev12** [comment]
> do you have sodium or any other mods?

no i don't have any mods/shaders turned on

**Comment by vladisaev12** [comment]
> > 0.5.4
> 
> Specify dev build
dev build 0.5.4 for minecraft 1.20-1.20.1

**Comment by Wide-Cat** [comment]
Send an image of your mods folder, and send a picture of your x-ray settings

**Comment by ManInMyVan** [comment]
> dev build 0.5.4 for minecraft 1.20-1.20.1

No, what number is it?

**Comment by vladisaev12** [comment]
> Send an image of your mods folder, and send a picture of your x-ray settings

only fabric-api.jar and meteor-client.jar, default x-ray seytings

**Comment by Wide-Cat** [comment]
Remove the fabric api
