### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Alilqq** [MeteorDevelopment/meteor-client#3823]
### Describe the bug

Parkour mod not working well with vanilla jumping, this can be easily detected by anticheats, since it is not vanilla behaviour, and can get players banned/punished 

### Steps to reproduce

```bash
When I jump around the same time as the parkour mod jumps for me, the game thinks I jumped twice and for some reason I get boosted forwards.
```

### Meteor Version

0.5.3 and 0.5.4

### Minecraft Version

1.19.4/1.20

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
baritone issue, should be reported to them, not us

**Comment by Big-Iron-Cheems** [comment]
Also, anticheat detectability is not something we intend to address, as Meteor is meant for anarchy servers.
