### ISSUE TITLE
[Suggestion] KillAura rotation range

### ISSUE THREAD

**Issue by chris1384** [MeteorDevelopment/meteor-client#383]
When attacking with KillAura on, the rotations are applied after the first swing, causing a miss hit. By making the player start rotating before hitting (slider setting), this would fix the issue. This is useful for in-air pvp.

**Comment by RedCarlos26** [comment]
This is already in the client. Just set the rotation mode to always and not on hit. You will be able to hit every time.

**Comment by chris1384** [comment]
That's the issue, rotation mode is set to always but the first hit misses everytime. It would be nice if there's a slider to set the 'rotation search' to look at the target before it starts hitting.

**Comment by RedCarlos26** [comment]
Ok I see

**Comment by Declipsonator** [comment]
> 
> 
> That's the issue, rotation mode is set to always but the first hit misses everytime. It would be nice if there's a slider to set the 'rotation search' to look at the target before it starts hitting.

What dev build are you on

**Comment by Declipsonator** [comment]
Because always was fixed not too long ago
