### ISSUE TITLE
Trajectories  multipleshots Enchantment Bug

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [MeteorDevelopment/meteor-client#3834]
### Describe the bug

The perspective line for multiple shots Enchantment should be in front, not behind
As shown in the picture ->   [link](https://img1.imgtp.com/2023/07/15/hjP1WGnI.png)

Workaround:
Increase the value provided to the simulated parameter at lines 149 and 152 of the code by π
The following is a modified code snippet:

`if (itemStack.getItem() instanceof CrossbowItem && EnchantmentHelper.getLevel(Enchantments.MULTISHOT, itemStack) > 0) {
            if (!simulator.set(player, itemStack, -13.1415926535, accurate.get(), tickDelta)) return;
            getEmptyPath().calculate();
            if (!simulator.set(player, itemStack, 13.1415926535, accurate.get(), tickDelta)) return;
            getEmptyPath().calculate();
        }`

### Steps to reproduce

```bash
1.Turn on the Trajectories feature
2.Holding a crossbow enchanted with multiple shots
3.Turn on the Freecam feature to observe the parabola(The parabola of multiple shots are normally invisible)
```

### Meteor Version

0.5.4

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by K1jinSeija** [comment]
I found a bit of a problem when I tested it later
It's a matter of arc,Just convert the original 10 angles to radians
`
if (itemStack.getItem() instanceof CrossbowItem && EnchantmentHelper.getLevel(Enchantments.MULTISHOT, itemStack) > 0) {
            if (!simulator.set(player, itemStack, -Math.toRadians(10), accurate.get(), tickDelta)) return;
            getEmptyPath().calculate();
            if (!simulator.set(player, itemStack, Math.toRadians(10), accurate.get(), tickDelta)) return;
            getEmptyPath().calculate();
        }
`
