### ISSUE TITLE
X-Ray doesn't make BLOCKS* disappear

### ISSUE THREAD

**Issue by Maks7594** [MeteorDevelopment/meteor-client#3836]
### Describe the bug

It just doesn't work. If i enable Freecam and fly through the wall, I can see the ores. (BEFORE YOU SAY THIS IS WAS ALREADY REPORTED, THIS IS A NEW ISSUE SO I CAN UPLOAD A SCREENSHOT OF MY MODS FOLDER.)

### Steps to reproduce

```bash
Just enable X-Ray.
```

### Link to crash report/log if applicable (https://mclo.gs)

Nope.

### Meteor Version

Latest dev

### Minecraft Version

1.20.x

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Maks7594** [comment]
Here's my mods folder.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/72873506/7392c4d8-6e29-4bcf-9c70-aa9f690ade81)

**Comment by Wide-Cat** [comment]
update your fabric api to the latest version

**Comment by Maks7594** [comment]
> update your fabric api to the latest version

it is already on the latest version

**Comment by Maks7594** [comment]
> update your fabric api to the latest version

doesnt work

**Comment by Maks7594** [comment]
doesnt work

> update your fabric api to the latest version
