### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by xX0Bryan0Xx** [MeteorDevelopment/meteor-client#3837]
### Describe the feature

do a .seed command
my idea is: an AI detects the closest 9 chunks and can see the seeds (idk if this work)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
use seedcrackerx

**Comment by Paddyk45** [comment]
You can't use AI to crack minecraft seeds
