### ISSUE TITLE
[Bug] Search doesn't detect blocks when appearing for the second time.

### ISSUE THREAD

**Issue by chris1384** [MeteorDevelopment/meteor-client#384]
It says in the title, this is common with blocks like Nether Portals or End Portals (Frames).

How to reproduce it:
1. Apply Search on desired blocks.
2. Load the chunks where the blocks are.
3. Unload the chunks then load them again.

**Comment by MineGame159** [comment]
Should be fixed in d362e4070440987f96c64e15b7efc3b7306e2032
