### ISSUE TITLE
X-Ray doesn't work. [THIS ISN'T A REPOST]

### ISSUE THREAD

**Issue by Maks7594** [MeteorDevelopment/meteor-client#3841]
### Describe the bug

It just doesn't work. It enables the Fullbright part but it doesn't alter the transparency of blocks. [YES, I HAVE TRIED TO UPDATE MY FABRIC API AND IT STILL DOESN'T WORK.] Also here's my mods folder.

![image](https://github.com/MeteorDevelopment/meteor-client/assets/72873506/acaa0919-968e-4581-9f4b-b415baf15ba2)

### Steps to reproduce

```bash
Just enable X-Ray.
```

### Link to crash report/log if applicable (https://mclo.gs)

Nope

### Meteor Version

0.5.4 1865

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Maks7594** [comment]
I swear this isn't a clone. People had just told me to update Fabric API and that didn't work. Removing Sodium also didn't work.

**Comment by Wide-Cat** [comment]
what modules do you have enabled

**Comment by theotherhades** [comment]
Send your xray config

**Comment by Wide-Cat** [comment]
I was unable to reproduce copying your mods folder near exactly. Its probably a module conflict issue. My guess would be you have wallhack enabled but it might be something else

**Comment by Maks7594** [comment]
> what modules do you have enabled

middle click friend
inventory tweaks
break indicators
unfocused cpu
camera tweals
block selection
storage esp
**no jump delay**
server spoof
auto totem
trajectories
item physics
boss stack
no render
fullbright
esp
**chat bot**
**anti bot**
portals

modules in bold are from addons

**Comment by Maks7594** [comment]
> Send your xray config

![image](https://github.com/MeteorDevelopment/meteor-client/assets/72873506/4242734d-8e8b-400d-a408-e69b08b4d056)
![image](https://github.com/MeteorDevelopment/meteor-client/assets/72873506/76fedbfc-0c64-472b-bb24-0cf4c10650c4)

**Comment by Wide-Cat** [comment]
mfw

**Comment by Wide-Cat** [comment]
you have opacity set to 255

**Comment by Maks7594** [comment]
> you have opacity set to 255

oh wait yeah that might be the issue

**Comment by Maks7594** [comment]
i think it was set like that when i installed meteor

**Comment by Maks7594** [comment]
yeah thats good, sometimes xray also didnt work when i had opacity set to 0 but thx

**Comment by theotherhades** [comment]
Knew it

**Comment by Wide-Cat** [comment]
@theotherhades good call

**Comment by GreemDev** [comment]
> i think it was set like that when i installed meteor

No, it wasn't: https://github.com/MeteorDevelopment/meteor-client/blob/5e294295834722834d126c323c095decad5c612b/src/main/java/meteordevelopment/meteorclient/systems/modules/render/Xray.java#L67
