### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by maxszul** [MeteorDevelopment/meteor-client#3844]
### Describe the bug

start up meteor

### Steps to reproduce

```bash
start meteor
```

### Link to crash report/log if applicable (https://mclo.gs)

---- Minecraft Crash Report ---- // You're mean.  Time: 2023-07-17 18:22:40 Description: Initializing game  java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:467) 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) 	at meteordevelopment.meteorclient.addons.AddonManager.init(AddonManager.java:68) 	at meteordevelopment.meteorclient.MeteorClient.onInitializeClient(MeteorClient.java:93) 	at net.minecraft.class_310.handler$bhk005$meteor-client$onInit(class_310.java:9549) 	at net.minecraft.class_310.<init>(class_310.java:683) 	at net.minecraft.client.main.Main.main(Main.java:198) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.ClassNotFoundException: meteordevelopment.meteorclient.systems.commands.Command 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	... 13 more

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
outdated addon issue
