### ISSUE TITLE
[Suggestion] Crossbow Addon

### ISSUE THREAD

**Issue by Crifall** [MeteorDevelopment/meteor-client#3845]
### Describe the feature

You can choose an arrow or fireworks and the crossbow will always take the one you chose, you wont have to hold the fireworks in your hand for it to be used on the crossbow.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
that sounds very niche, it would probably be better to include it in an addon or something
