### ISSUE TITLE
Notebot Not Autobuilding [Solved-ish]

### ISSUE THREAD

**Issue by Dojo-Ninja** [MeteorDevelopment/meteor-client#3846]
### Describe the bug

It says on one of the pages that notebot will automatically work if you have note blocks (and Im assuming their respective blocks) in your hotbar, it will automatically build to create the blocks to play the song. This is not working. Is it an NBT note block thing, or is this an actual issue?

### Steps to reproduce

```bash
Use notebot with items in hotbar
```

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

macOS

### Before submitting a bug report

- [ ] This bug wasn't already reported (I have searched bug reports on GitHub).

- [ ] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
this was removed when notebot was rewritten and the faq hasnt been updated to reflect it yet

**Comment by Dojo-Ninja** [comment]
darn
