### ISSUE TITLE
Meteor Client crashing on startup

### ISSUE THREAD

**Issue by Snaxolotl71** [MeteorDevelopment/meteor-client#3848]
### Describe the bug

Game crashes on startup with the following error: "java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.isActive(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null"

### Steps to reproduce

```bash
Open Minecraft Fabric version 1.20.1 with Meteor Client dev build version 0.5.4 in the "mods" folder.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://pastebin.com/C6E3QNv3

### Meteor Version

Dev Build 0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
shoulder surfing compat issue most likely

**Comment by Snaxolotl71** [comment]
> shoulder surfing compat issue most likely

Removing shoulder surfing fixed the issue, thx amigo
