### ISSUE TITLE
[Suggestion] kill aura with mode client/sever

### ISSUE THREAD

**Issue by Laplatffffff** [MeteorDevelopment/meteor-client#3849]
### Describe the feature

in some sever you'll get banned for tapping on players with the current kill aura, when using Bleachhack kill aura on client mode FOR ROTATIONS the camera turns in the direction of the player, another example of not getting banned kill aura is zergatul cheatutils, though the most I have experience with is bleach hack, which also will get you banned for using kill aura in sever mode ROTATIONS, this feature is essensial to the client since bleach hack and meteor and other clients cannot be used toguether, this is in the 1.19.4 version which works better with non updated mods before the 1.20 update.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by theotherhades** [comment]
Unless you're talking about anarchy servers with particularly strict anticheats, you shouldn't be using Meteor on servers where it's not allowed. This seems to me like something that would assist cheaters on servers where they shouldn't be cheating rather than assisting legit Meteor users.

**Comment by Laplatffffff** [comment]
> Unless you're talking about anarchy servers with particularly strict anticheats, you shouldn't be using Meteor on servers where it's not allowed. This seems to me like something that would assist cheaters on servers where they shouldn't be cheating rather than benefiting legit Meteor users.

I'm sorry but isn't kill aura supposed  you know, kill aura, I'm just suggesting a client method of where the camera moves when hitting a player like bleach hack does, to prevent banning, using meteor already in any sever is already cheating so I cant make sence of this, in all basics I'm just suggesting a client based kill aura.

**Comment by theotherhades** [comment]
You're not supposed to be using Meteor on servers where it's not allowed. If the purpose of this is to bypass anticheat on servers where you shouldn't be using it then I don't think it should be implemented.

**Comment by Laplatffffff** [comment]
> You're not supposed to be using Meteor on servers where it's not allowed. If the purpose of this is to bypass anticheat on servers where you shouldn't be using it then I don't think it should be implemented.

I believe the reason they are not allowed is because there is a code implemented into the sever to prevent users to keep using the hack right? there for some sever that dont have the code you are "allowed" to use meteor just like you say, lifestealsmp has a code for meteor kill aura to prevent players from using it, but bleach hack has a kill aura that is "allowed" based on your logic. that lets you keep using it there for this sever allowes the kill aura im suggesting to be implemented. and again im basing this all in your logic

**Comment by theotherhades** [comment]
No, what I mean is the Meteor devs specifically disallow usage of the client where it's not permitted. You shouldn't propose a change if it is intended to help cheaters.

**Comment by Laplatffffff** [comment]
> 

can you please send a link where they say that, because I believe all clients that alter vanilla even to a thing as simple as fullbright is cheating.

**Comment by theotherhades** [comment]
It's in the Discord server or something iirc

**Comment by Laplatffffff** [comment]
I saw it, thought the specific words is hack and cheat, I never make such a claim about hacking or cheating on my main unedited suggestion, bleachhack, that is the name of the client, either if is a hack or not, it is the name of the client only with similar features to those of meteor, plus what im suggesting is a feature that is already been crated, when the devs get frustrated is where they get people to ask for stuff that hasnt been created and they have to figure out how to not get banned, even though my suggestion does imply that, this feature has already been created, im just suggesting the implementation of this feature which im willing to pay for

**Comment by theotherhades** [comment]
Bro all I'm saying is your original post seemed like you wanted a way to use KillAura on servers where you're not supposed to.

**Comment by Laplatffffff** [comment]
> Bro all I'm saying is your original post seemed like you wanted a way to use KillAura on servers where you're not supposed to.

the thing is that it doesnt make a difference since im already using other features of meteor on this sever, again by them not having the code to prevent this kind of features they are allowing me to stay on the sever, one that they do have and this is new, is banning kill aura but is a different kind of code you can still use killaoura without being banned in bleach hack, is just frustrating switching between things when you want to pvp and use the meteor features, cuz then you have to quit and put meteor out of the folder and then put bleach hack, is the same thing this suggestion would only facilitate a feature that is already avalible

**Comment by theotherhades** [comment]
Sounds to me like you're using Meteor where you shouldn't be

**Comment by Laplatffffff** [comment]
> Sounds to me like you're using Meteor where you shouldn't be

I AM, like duh dude this thing is a hack and even tho they dont want to call it that like cults hate being called cults this is a hack wether or not im using it where I shouldn't be is not revelant, whats revelant is that this would be very useful

**Comment by theotherhades** [comment]
Learn to play the game normally without Meteor to baby you through everything. It's pretty clear it is intended for anarchy servers not whatever you're cheating on.

**Comment by Laplatffffff** [comment]
> Learn to play the game normally without Meteor to baby you through everything. It's pretty clear it is intended for anarchy servers not whatever you're cheating on.

lol if it was for that they would just put a scrip on it to only link it to anarchy severs dont u think?, they only say that for legal purposes, plus playing while cheating is better since you feel like a king having power over all.

**Comment by FlightXamb** [comment]
Omg, meteor client is an anarchy client not a legit client, meteor is made for servers like 2b2t, not hypixel. Yes, the anarchy community exist.

**Comment by Laplatffffff** [comment]
> Omg, meteor client is an anarchy client not a legit client, meteor is made for servers like 2b2t, not hypixel. Yes, the anarchy community exist. Also, no, we are not gonna block every servers that doesnt allow cheating, honestly, nobody cares if you cheat on a server that dont allows it, imagine being so bad at minecraft that you need to cheat, what a L, you can connect to servers with anticheats but we are not going to add anticheats bypasses.

BRUH IM JUST GONNA SUGGEST THE SAME THING IN A MONTH WHERE ALL YOUR STAFF WILL FORGET about this suggestion and im just gonna suggest it like: hey client kill aura should be an option because it moves the camera where a player is which makes it better in pvp. or something like that and you'll guys add it without even knowing it's me lol just telling you this to see your face when is added 1-2 months from now. and like I said you guys are a cult like those not being called a cult you guys dont want to call it a hack client even tho it is.

**Comment by Laplatffffff** [comment]
> Omg, meteor client is an anarchy client not a legit client, meteor is made for servers like 2b2t, not hypixel. Yes, the anarchy community exist. Also, no, we are not gonna block every servers that doesnt allow cheating, honestly, nobody cares if you cheat on a server that dont allows it, imagine being so bad at minecraft that you need to cheat, what a L, you can connect to servers with anticheats but we are not going to add anticheats bypasses.

and like I said is not about being bad, some people like playing alone without teams, and when people team agains one it's pretty unfair, thats when hacks come, it is fair with kill aura bc then you can deal with 2 people at the same time

**Comment by OLEPOSSU** [comment]
> > Omg, meteor client is an anarchy client not a legit client, meteor is made for servers like 2b2t, not hypixel. Yes, the anarchy community exist. Also, no, we are not gonna block every servers that doesnt allow cheating, honestly, nobody cares if you cheat on a server that dont allows it, imagine being so bad at minecraft that you need to cheat, what a L, you can connect to servers with anticheats but we are not going to add anticheats bypasses.
> 
> BRUH IM JUST GONNA SUGGEST THE SAME THING IN A MONTH WHERE ALL YOUR STAFF WILL FORGET about this suggestion and im just gonna suggest it like: hey client kill aura should be an option because it moves the camera where a player is which makes it better in pvp. or something like that and you'll guys add it without even knowing it's me lol just telling you this to see your face when is added 1-2 months from now. and like I said you guys are a cult like those not being called a cult you guys dont want to call it a hack client even tho it is.

nobody will ever add your dogshit stuff

**Comment by Laplatffffff** [comment]
> > BRUH IM JUST GONNA SUGGEST THE SAME THING IN A MONTH WHERE ALL YOUR STAFF WILL FORGET about this suggestion and im just gonna suggest it like: hey client kill aura should be an option because it moves the camera where a player is which makes it better in pvp. or something like that and you'll guys add it without even knowing it's me lol just telling you this to see your face when is added 1-2 months from now. and like I said you guys are a cult like those not being called a cult you guys dont want to call it a hack client even tho it is.
> 
> nobody will ever add your dogshit stuff

and from what asshole did you come from?

**Comment by TemptingApple42** [comment]
I thought it did have rotations

**Comment by Laplatffffff** [comment]
> I thought it did have rotations

it does, but the rotation im tlking about makes it so you dont get banned

**Comment by TemptingApple42** [comment]
I dont think the metior devs are going to invest time in bypasses.

**Comment by wfogame** [comment]
Interesting philosphy here, now thats way all the modules are so trash on servers... but so good not ons ervers. Understood
