### ISSUE TITLE
[Suggestion] No Cave Culling (Spectator View)

### ISSUE THREAD

**Issue by chris1384** [MeteorDevelopment/meteor-client#385]
This is self-explainatory, I know that Freecam has this feature, but it would be nice if there's a separate module for it (like Inertia).

**Comment by RedCarlos26** [comment]
I would say especially for the camera clip module that allow you to see trough block when in 3rd person.

**Comment by RedCarlos26** [comment]
This got added, so could be closed @chris1384.

**Comment by RedCarlos26** [comment]
@seasnail8169
