### ISSUE TITLE
[Bug] The website is down

### ISSUE THREAD

**Issue by downloadyetter** [MeteorDevelopment/meteor-client#3851]
### Describe the bug

Hello when i go to https://meteorclient.com it shows me this--->Congratulations!
You've successfully started the Nginx Proxy Manager.

If you're seeing this site then you're trying to access a host that isn't set up yet.

Log in to the Admin panel to get started.

Powered by [Nginx Proxy Manager](https://github.com/jc21/nginx-proxy-manager)

### Steps to reproduce

```bash
I logged in the website and it showed me this blank text
```

### Meteor Version

???

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
we know

**Comment by exalented** [comment]
I would suggest pinning this issue
