### ISSUE TITLE
meteorclient.com no longer works

### ISSUE THREAD

**Issue by Dojo-Ninja** [MeteorDevelopment/meteor-client#3852]
### Describe the bug

look at the title

### Steps to reproduce

```bash
open the site
```

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
we know

**Comment by Paddyk45** [comment]
Looks like you didn't search issues
