### ISSUE TITLE
Add Auto Potion

### ISSUE THREAD

**Issue by Krayiken** [MeteorDevelopment/meteor-client#3853]
### Describe the feature

I know It's more of a PVP Client than a General Modification Mod but it would really be useful for it to drink/splash potions when that effect runs out OR to put potion-drinking/splashing on a timer. There should be two separate "sections" that can be toggled on or off: Time or when run out OR just a dropdown menu to select which OR just a timer and the player has to select the specific potion time But, the easiest and most effective is When it runs out.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Krayiken** [comment]
Nvm #274

**Comment by Fiz-Victor** [comment]
xD
