### ISSUE TITLE
[Bug] Entities went invisible when using Freecam when in any block.

### ISSUE THREAD

**Issue by LegendHuy** [MeteorDevelopment/meteor-client#3854]
THIS IS NOT A BUG. I have Entity Culling mod my bad sorry.

### Describe the bug

All entities will be invisible when using Freecam when go through any block and back visible when not in any block.

### Steps to reproduce

```bash
1. Turn on Freecam.
2. Go through any block.
```

### Meteor Version

Dev 0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Fiz-Victor** [comment]
Disable entity culling mod?

**Comment by LegendHuy** [comment]
> Disable entity culling mod?

Ah entity culling ok that's why.
