### ISSUE TITLE
where can we download the build version

### ISSUE THREAD

**Issue by SugarRainbow** [MeteorDevelopment/meteor-client#3857]
### Describe the feature

So, where can we download the build version (.jar)?
discord？

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by AstraxCZ** [comment]
![download zip](https://github.com/MeteorDevelopment/meteor-client/assets/88210947/b2b8fc09-c897-4171-a692-9262bbb02ec4)

**Comment by Fiz-Victor** [comment]
actions

**Comment by RjManhas** [comment]
@Fiz-Victor how

**Comment by theotherhades** [comment]
The website is back up, you can download it there.
