### ISSUE TITLE
Error while building with gradle

### ISSUE THREAD

**Issue by JustGuardian** [MeteorDevelopment/meteor-client#3858]
### Describe the bug

A problem occurred configuring root project 'meteor-client'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not find baritone:fabric:1.20.1-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/user/Downloads/meteor-client/.gradle/loom-cache/remapped_mods/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/user/Downloads/meteor-client/.gradle/loom-cache/remapped_mods/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - file:/C:/Users/user/.gradle/caches/fabric-loom/minecraftMaven/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/user/.gradle/caches/fabric-loom/minecraftMaven/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - file:/C:/Users/user/Downloads/meteor-client/.gradle/loom-cache/minecraftMaven/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/user/Downloads/meteor-client/.gradle/loom-cache/minecraftMaven/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - https://maven.fabricmc.net/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - https://maven.fabricmc.net/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - https://libraries.minecraft.net/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - https://libraries.minecraft.net/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - https://libraries.minecraft.net/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.jar
       - https://repo.maven.apache.org/maven2/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - https://maven.meteordev.org/releases/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - https://maven.meteordev.org/releases/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - https://maven.meteordev.org/snapshots/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - https://maven.meteordev.org/snapshots/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
       - https://maven.vram.io/baritone/fabric/1.20.1-SNAPSHOT/maven-metadata.xml
       - https://maven.vram.io/baritone/fabric/1.20.1-SNAPSHOT/fabric-1.20.1-SNAPSHOT.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

### Steps to reproduce

```bash
I cloned the repository, opened with intellij and built with gradle
```

### Meteor Version

Latest dev(?)

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by JustGuardian** [comment]
> Meteors maven is currently down, thats why

ok so I just need to wait right?

**Comment by Paddyk45** [comment]
> > Meteors maven is currently down, thats why
> 
> ok so I just need to wait right?
> 

yes

**Comment by JustGuardian** [comment]
> > > Meteors maven is currently down, thats why
> > 
> > 
> > ok so I just need to wait right?
> 
> yes

meanwhile, where can I download meteorclient?

**Comment by Paddyk45** [comment]
> meanwhile, where can I download meteorclient?

nowhere, meteor is completely down

**Comment by JustGuardian** [comment]
> > meanwhile, where can I download meteorclient?
> 
> nowhere, meteor is completely down

yay

**Comment by Paddyk45** [comment]
> > > meanwhile, where can I download meteorclient?
> > 
> > nowhere, meteor is completely down
> 
> yay

Nevermind, you can use this build: https://github.com/MeteorDevelopment/meteor-client/suites/14369173626/artifacts/809475905
