### ISSUE TITLE
[Suggestion] not visible in shearscreen 

### ISSUE THREAD

**Issue by johnkouk007** [MeteorDevelopment/meteor-client#3859]
### Describe the feature

Make it so Noone can see the cheats from discord please

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
No, never. Meteor is blatant by design.
If you are a closet cheater and use it outside of anarchy, you deserve to get banned.

**Comment by Paddyk45** [comment]
Meteor isn'ta Hacked Client so no

**Comment by johnkouk007** [comment]
Then why everyone using it for hacking and cheating?

**Comment by enderschesi** [comment]
Meteor is a Utility Mod, which gives you additional tools on servers that allow those tools, like anarchy servers.

**Comment by Big-Iron-Cheems** [comment]
We brand ourselves as "A Minecraft Fabric Utility Mod for anarchy servers".

The fact people use Meteor outside of the places we made it to be used doesn't change our definition.
Just because a random kid on youtube says it's a "cheat menu" or a "hack client" it doesn't change our ideal.
