### ISSUE TITLE
[Bug] Using Search resets the GUI positions

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#386]
**Describe the bug**
As title says, on latest dev-build the GUI is misbehaving when searching for modules.

**To Reproduce**
1. Open the GUI
2. Start typing to search a module
3. The whole GUI moves to the default position

**Expected behavior**
The GUI should not move by itself

**Screenshots**
Before searching
![2021-03-31 22_45_10-Minecraft_ 1 16 5 - Singleplayer](https://user-images.githubusercontent.com/52252627/113208994-c4c36980-9272-11eb-8f03-f112f92bab5a.png)

After searching (ignore the module list on the right side, i turned it off)
![2021-03-31 22_46_07-Minecraft_ 1 16 5 - Singleplayer](https://user-images.githubusercontent.com/52252627/113209088-e58bbf00-9272-11eb-834e-8a637cb9cc42.png)

**Additional context**
Meteor version: 0.4.2-658

**Comment by StormyBytes** [comment]
can confirm

**Comment by RedCarlos26** [comment]
Can confirm

**Comment by StormyBytes** [comment]
Some more info from testing, after searching (typing any thing into the searh bar in gui) the gui does reset positions, but if you close the gui and re open it, the gui will be back to your preferred positions

**Comment by RedCarlos26** [comment]
Yes, this is a visual bug, that is somewhat annoying when searching a module.

**Comment by MineGame159** [comment]
Fixed
