### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Valkuris** [MeteorDevelopment/meteor-client#3860]
### Describe the bug

alright so basically when you reload chunks F3+A it crashes ur game if you hold it down 

### Steps to reproduce

```bash
alright so basically when you reload chunks F3+A it crashes ur game if you hold it down
```

### Meteor Version

latest

### Minecraft Version

latest

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
attach a crash report

**Comment by Wide-Cat** [comment]
if its a `hs_err_pid` one then dm it to me on discord, @wide_cat

**Comment by Paddyk45** [comment]
Thats not a meteor issue

**Comment by SpecKeef** [comment]
Thats a minecraft issue all day. Its because it is spam reloading chunks.
