### ISSUE TITLE
Meteor Website and Maven Down?

### ISSUE THREAD

**Issue by Volcan4436** [MeteorDevelopment/meteor-client#3862]
### Describe the bug

What is the ETA for the Website and Maven going to be back up?

### Steps to reproduce

```bash
Go to the website
```

### Meteor Version

???

### Minecraft Version

???

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
> This bug wasn't already reported (I have searched bug reports on GitHub).
You sure did bud...
Surely there aren't at least 3 other related issues, and surely we haven't been notified on our discord about 40 times.

**Comment by Volcan4436** [comment]
:)

**Comment by MassivebutterpapperCodes** [comment]
Try https://nightly.link/MeteorDevelopment/meteor-client/suites/14369173626/artifacts/809475905 Because someone helped me with that link

**Comment by MassivebutterpapperCodes** [comment]
but it should look like this: 
![proof](https://github.com/MeteorDevelopment/meteor-client/assets/134733276/e3f0eeef-1971-4ab9-99b2-52bbc29f16da)

**Comment by MassivebutterpapperCodes** [comment]
if its a dif problem idk

**Comment by BDARmech** [comment]
Why the caps? You mad?

**Comment by MassivebutterpapperCodes** [comment]
wha? no???
