### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Myuui** [MeteorDevelopment/meteor-client#3864]
### Describe the bug

Congratulations!
You've successfully started the Nginx Proxy Manager.

If you're seeing this site then you're trying to access a host that isn't set up yet.

Log in to the Admin panel to get started.

![bug](https://i.ibb.co/j6PsBxK/image.png)

### Steps to reproduce

```bash
https://meteorclient.com/
```

### Meteor Version

X

### Minecraft Version

X

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
we know, we're waiting for the host to reactivate it
