### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by sursikus** [MeteorDevelopment/meteor-client#3865]
### Describe the feature

hello, why did you remove the meteor build on 1.19.2?
i mean gradlew build

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
Did you want the jar? I have it on [my GitHub repository](https://github.com/ManInMyVan/meteor-archive)
