### ISSUE TITLE
meteor client site bug?

### ISSUE THREAD

**Issue by smdsolo** [MeteorDevelopment/meteor-client#3867]
### Describe the bug

so when i go to the client website, this pops up

Congratulations!
You've successfully started the Nginx Proxy Manager.

If you're seeing this site then you're trying to access a host that isn't set up yet.

Log in to the Admin panel to get started.

### Steps to reproduce

```bash
just go the website and click on the site and that will pop up
```

### Link to crash report/log if applicable (https://mclo.gs)

https://meteorclient.com/

### Meteor Version

1.19.2/1.19.3

### Minecraft Version

1.19.2/1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
> This bug wasn't already reported (I have searched bug reports on GitHub).
[Yeah, you clearly didn't.](https://i.greemdev.net/8CPjepWUT_iNe-IuZNJPIg.png)
