### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 2MinuteNoodled** [MeteorDevelopment/meteor-client#387]
Crystal aura on multi targeting mak ed you spam click an invisible entity you can see if particles are turned on and your in a pvp zone

**Comment by RedCarlos26** [comment]
I cannot reproduce

**Comment by RedCarlos26** [comment]
This is probably a config issue. This can be closed in my opinion because it is not relevant.

**Comment by Declipsonator** [comment]
> This is probably a config issue. This can be closed in my opinion because it is not relevant.

Just because it doesn't happen to you doesn't mean it won't happen to someone else

**Comment by Declipsonator** [comment]
multi targeting has been bugged before

**Comment by RedCarlos26** [comment]
Hmm
