### ISSUE TITLE
Disabler

### ISSUE THREAD

**Issue by PeakHacks** [MeteorDevelopment/meteor-client#3871]
### Describe the feature

Bypasses Server Anticheat

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
someone used a Disabler on you....

**Comment by BDARmech** [comment]
¯\_(ツ)_/¯
