### ISSUE TITLE
New Nuker Feature

### ISSUE THREAD

**Issue by SpinachIsDelicious** [MeteorDevelopment/meteor-client#3872]
### Describe the feature

In nuker, it only breaks blocks but in some servers you have to right click certain blocks to get money
Can you make it so that there is a setting for whether you want meteor client to right click certain blocks or not
So that nuker right clicks things like carpets

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
You shouldnt use meteor on servers that don't allow it
