### ISSUE TITLE
[Suggestion] add Scripts / upgrade Macros

### ISSUE THREAD

**Issue by Rommmmaha** [MeteorDevelopment/meteor-client#3876]
### Describe the feature

Scripts manager (primitive design as I imagine it):
![image](https://github.com/MeteorDevelopment/meteor-client/assets/53641123/a15175ba-7887-4b3e-b332-01284a6ad6b2)

Always active script (turns on at intervals of several ticks)
![image](https://github.com/MeteorDevelopment/meteor-client/assets/53641123/d26d77f9-c492-48bf-b932-dcd31f3bd6c4)

When i press 'Y' script automatically writes text until y>-10
![image](https://github.com/MeteorDevelopment/meteor-client/assets/53641123/71132ac5-c036-41bf-91d8-89a3d147b211)

mb add Starscript support to get variable values more easily

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Fiz-Victor** [comment]
You can use JSMacros or write a module by yourself, we are not considering adding this for now
