### ISSUE TITLE
Website Down 

### ISSUE THREAD

**Issue by nxexdev** [MeteorDevelopment/meteor-client#3877]
### Describe the bug

This is quite embarrassing for such a large project.
Get it together.

### Steps to reproduce

```bash
go to https://meteorclient.com
```

### Meteor Version

Latest

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
![Screenshot_20230724_045003_Firefox](https://github.com/MeteorDevelopment/meteor-client/assets/74723656/cab21c38-dd3c-4bd8-8df9-6aec39e5fce7)
Don't act so entitled when you clearly have no idea what you're talking about.

**Comment by arlomcwalter** [comment]
Also since when is it ok for you to tell us to get it together??
What obligation do we have to you to maintain any of our services?
Meteor is free and open source, if we decided to shut everything down tomorrow, we are well within our rights lmao

**Comment by FlightXamb** [comment]
The only thing that is embarrassing here is you that can't figure out how to press refresh

**Comment by Duck6887** [comment]
if you click one of the download options it has taken me to an 'add focus' page please help

**Comment by Duck6887** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/133347153/dacc3ba4-746a-4cf5-8b85-e8816b3dfb70)

**Comment by FlightXamb** [comment]
I wonder...
![image](https://github.com/MeteorDevelopment/meteor-client/assets/97624502/f2f7a539-286d-4671-a8ce-7b09f17744dc)
