### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by taiday** [MeteorDevelopment/meteor-client#3882]
### Describe the feature

i want add REGEN Look like 1.8.9 in 1.20 and 1.19.4 thank you

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
As far as I'm aware, not possible
