### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Duck6887** [MeteorDevelopment/meteor-client#3883]
### Describe the bug

when i click 'RELEASE' or 'DEV BUILD' it just takes me to an 'add focus' page therefore I can not download your client

### Steps to reproduce

```bash
open meteor website
click release or dev build
it will take you to this page https://adfoc.us/8192681
```

### Meteor Version

0.5.3-0.5.4

### Minecraft Version

1.19.4-1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Not a bug, look at the skip button in the top right corner.
