### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by SomeDuckOnEarth** [MeteorDevelopment/meteor-client#3884]
### Describe the bug

When i click download it brings me to ad focus and when i press skip nothing happens

### Steps to reproduce

```bash
Go to https://meteorclient.com/
Press Dev build 0.5.4
Wait 5 seconds
Press skip
```

### Meteor Version

0.5.4

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Not a bug, click skip in the top right corner.

**Comment by Big-Iron-Cheems** [comment]
If you have some adblocker it could be messing with it, try turning it off and see if that changes.
