### ISSUE TITLE
Health Indicator

### ISSUE THREAD

**Issue by insanowasaa** [MeteorDevelopment/meteor-client#3887]
### Describe the feature

Put a mod where you can see the lives of other users / mobs

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Nametags
