### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Angelenx** [MeteorDevelopment/meteor-client#3888]
### Describe the feature

When the game language is Japanese, the entitys and the blocks name will not be shown properly. So I want a switch to keep using English in those lists.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Known issue with the custom font renderer when rendering Unicode characters. Either set your in-game language to English, or go to the config tab and disable the custom font setting

**Comment by Angelenx** [comment]
> Known issue with the custom font renderer when rendering Unicode characters. Either set your in-game language to English, or go to the config tab and disable the custom font setting
Well, that work. But the inputer would not work. That mean I can't search anything in the lists.
