### ISSUE TITLE
[Suggestion] Ignore friends in hitbox

### ISSUE THREAD

**Issue by GhostMikz** [MeteorDevelopment/meteor-client#3889]
### Describe the feature

"Ignore friends" feature in hitbox

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by KlyntarX69** [comment]
you're that dude who put this in the support channel right ???

**Comment by KlyntarX69** [comment]
anyways this whould be cool
