### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by supersloth365** [MeteorDevelopment/meteor-client#3891]
### Describe the feature

Could you add the ability to create multiple configurations of modules so that if you want to use say killaura and critical but on a different server kilaura and criticals can be detected you can switch to a configuration without those modules 

Thanks for reading this  :)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
1. You can already do this.
2. Don't use meteor where not allowed and this wouldn't be an issue.
