### ISSUE TITLE
Spoof Mob we kill

### ISSUE THREAD

**Issue by fcflorentino1234** [MeteorDevelopment/meteor-client#3892]
### Describe the feature

Can I Spoof mob i've killed?
like i killed a chicken but server think i killed a cow.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
If only

**Comment by Paddyk45** [comment]
This isn't bedrock where you can change anything you want

**Comment by ManInMyVan** [comment]
> This isn't bedrock where you can change anything you want

Unfortunately they patched .give
