### ISSUE TITLE
Make Infinite Miner.. Infinite <3

### ISSUE THREAD

**Issue by OfflinePing** [MeteorDevelopment/meteor-client#3893]
### Describe the feature

Hello,

Is it possible to make the infinite Miner actually infinite?

Features that I am missing:
- Make an option to deposit certain items into containers (for example put mined Ancient Debris after Inventory full)
- Make an option to not pickup items (e.g Quartz so if your inventory is full and its trying to repair it freezes because it tries to pickup the Quartz)
- Make an option to enable Auto Eat so you dont die of Hunger <3

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Use Baritone's #mine command for that.
It should pause on eat, and you can also setup inventory filters via other modules.

As for storing to an inventory, that is not possible.

**Comment by OfflinePing** [comment]
but what about the repairing feature? it doesnt auto-repair my Pickaxe does it?

**Comment by OfflinePing** [comment]
Wich other modules?
And why should I then even use the Infinity Miner if it doesnt mine Inifnite you know? Seems like an uneccecary feature then

**Comment by Big-Iron-Cheems** [comment]
Infinite miner is infinite, as long as you have a pickaxe with mending. 
You should read the module settings to understand better how it works.

**Comment by GameBounty** [comment]
> Infinite miner is infinite, as long as you have a pickaxe with mending. You should read the module settings to understand better how it works.

autoeat doesnt work with infinity miner (there is a fix in pull request)
"Make an option to not pickup items (e.g Quartz so if your inventory is full and its trying to repair it freezes because it tries to pickup the Quartz)" was one of the things listed and i believe turning off mineScanDroppedItems helps with this but should be turned on only during the repair process (idk how hard that is to automate)
