### ISSUE TITLE
Game crashing right after launch

### ISSUE THREAD

**Issue by devendrapoonia** [MeteorDevelopment/meteor-client#3895]
### Describe the bug

I have latest Meteor version installed and whenever I try to launched the game, everything works, the game windows shows, it loads and right after it loads. It will crash and show me a crash report. There is nothing much about it, if I disable Meteor client and then launch, it will work fine.

### Steps to reproduce

```bash
1. Install latest Meteor Dev Version
2. Launch the Game
3. The game should automatically crash after launch
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/0xcT1sH

### Meteor Version

0.5.4 - 1871

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Go to .minecraft/meteor-client and delete modules.nbt
