### ISSUE TITLE
Add a new pvp feature

### ISSUE THREAD

**Issue by TechnicTree** [MeteorDevelopment/meteor-client#3896]
### Describe the feature

Ok so basically when meteor detects a end crystal it could swap your offhand to a shovel and dig down as if you simply dig down one block crystals do less than 2 hearts then it would switch back to whatever was in your offhand before like a totem

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
You cant dig down and fall nearly fast enough before the other person explodes the crystal.

**Comment by Wide-Cat** [comment]
💀
