### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MifikTTV** [MeteorDevelopment/meteor-client#3897]
### Describe the bug

the waypoints dosent show

### Steps to reproduce

```bash
just create a waypoint
```

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by BDARmech** [comment]
Opening and closing your own? Thats wheird.
