### ISSUE TITLE
Cannot load addons with commands

### ISSUE THREAD

**Issue by MrNooberDude** [MeteorDevelopment/meteor-client#3899]
### Describe the bug

Game crashes when trying to load an addon with a command in it. That simple.

### Steps to reproduce

```bash
1. Download any addon with a command in it
2. Put it in the mods folder with Meteor enabled
3. Run the game
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/Wuy7Pw6

### Meteor Version

0.5.4 build 1871

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Caused by: java.lang.ClassNotFoundException: meteordevelopment.meteorclient.systems.commands.Command
