### ISSUE TITLE
[Suggestion] Corner place

### ISSUE THREAD

**Issue by Arbisy** [MeteorDevelopment/meteor-client#391]
**Describe the feature**
Corner place, lets you place on the corner of blocks.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
I don't understand what you mean

**Comment by RedCarlos26** [comment]
Me as well

**Comment by Arbisy** [comment]
> I don't understand what you mean

Like you know how your building and you want to place the block in the corner of it so you have to put another block on the side of the block in order to do that, now with the feature I suggested you don't have to do that and instead you look somewhere around the corner of a block and place the block and it places it there

**Comment by MineGame159** [comment]
Ohhhh ok

**Comment by Declipsonator** [comment]
hmmm, this sounds a lot like smth tweakaroo does

**Comment by DesiCow** [comment]
Just use air place module

**Comment by I-Got-You-Dead** [comment]
💀

**Comment by Wide-Cat** [comment]
air place
