### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Dolfe-1** [MeteorDevelopment/meteor-client#392]
When I launch the client I crash immediately and comes up with a crash message that says is:
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: minegame159.meteorclient.commands.Command.<init>(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
Exit Code: -1
^^^^^^^^
So I cannot use the bookdupe addon to the client and it has happened every time I have tried and I tried updating everything as well so please fix.

**Comment by Dolfe-1** [comment]
Thank you for helping even if you reject it.

**Comment by MineGame159** [comment]
The bookdupe addon needs a dev build to work
