### ISSUE TITLE
the text assests are missing(prob my device problem)

### ISSUE THREAD

**Issue by NetherDragonTw** [MeteorDevelopment/meteor-client#3922]
### Describe the bug

like title, this bug is the list didnt displays the name of items, and it cant be searched.
(updated: this bug also appeared on other select list)
![圖片](https://github.com/MeteorDevelopment/meteor-client/assets/99878040/2ae0e2ce-d647-437d-8eec-b1283659bca6)
![圖片](https://github.com/MeteorDevelopment/meteor-client/assets/99878040/191d1a7a-e516-4e06-ae01-17ca0d27446a)

(btw this bug is not appeared on the 1~3 days since i install meteor.)

### Steps to reproduce

```bash
open minecraft, open gui, go inv tweaks and click "Auto drop items" select button.
```

### Meteor Version

Dev Build 0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
probably caused by known issues to do with the font renderer
