### ISSUE TITLE
Fix Jesus, all other updates are meaningless until Jesus is with us again

### ISSUE THREAD

**Issue by etianl** [MeteorDevelopment/meteor-client#3923]
### Describe the bug

Jesus is broken, change two lines and it can be fixed. I have a PR for this. The tag originally used to determine if a liquid "ShouldBeSolid()" does not recognize those "flowing" liquid blocks and thus does not define it as a solid block. (in practice this causes you to be dipped over and over again into the flowing liquid, which is deadly in the case of lava)

See this PR for more details
https://github.com/MeteorDevelopment/meteor-client/pull/3799

### Steps to reproduce

```bash
Stand on water or lava that is flowing, with the Jesus module enabled. (not the source block)
```

### Meteor Version

Every one that has been updated to 1.20 and later

### Minecraft Version

1.20+

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ManInMyVan** [comment]
![Screenshot_20230811_234942_com.discord.png](https://github.com/MeteorDevelopment/meteor-client/assets/113963219/499a1a27-344c-4ca8-8ede-e0867a8666ec)

**Comment by etianl** [comment]
kthx :D
