### ISSUE TITLE
[Suggestion] Map Inject

### ISSUE THREAD

**Issue by TurtlemanLiam** [MeteorDevelopment/meteor-client#3924]
### Describe the feature

I'm not sure if this is possible, but could there be a new feature where it could inject pixel art onto a map, instead of having to build the entire thing. I think this would be a cool idea, sparing lots of time instead of gathering resources and making it block perfect.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
unfortunately not possible without direct access to the server files

**Comment by TurtlemanLiam** [comment]
Didn't there use to be a insert command in beta minecraft?
