### ISSUE TITLE
Continuity (Indium) breaks XRay and WallHack

### ISSUE THREAD

**Issue by Fiz-Victor** [MeteorDevelopment/meteor-client#3925]
### Describe the bug

Reproduced
https://discord.com/channels/689197705683140636/1138165064344555611/1138165064344555611

### Steps to reproduce

```bash
Turn on XRay/Wallhack
Watch the opacity not being changed
```

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by AlphaCraft9658** [comment]
I have the same issue. While I didn't know the cause, now I know it.
