### ISSUE TITLE
[Bug] Mouse position on macOS is sometimes incorrect

### ISSUE THREAD

**Issue by YEETboi-debug** [MeteorDevelopment/meteor-client#393]
**Describe the bug**
Color picker screen not working with larger gui scale than 1 on some systems
Generally the mouse position on macOS breaks sometimes incl in the hud editor.

**To Reproduce**
1. go to gui tab. 
2. click on accent collor
3. try to use the slider it just doesnt move or change the color

the issue is macOS

**Comment by YEETboi-debug** [comment]
1. go to gui tab. 
2. click on accent collor
3. try to use the slider it just doesnt move or change the color

i expect it to just be able to move the slider and change the color

i use meteor client 662, minecraft version 1.16.5, i use dupe mod, multiconnect, fabric api and of course meteor dev build 662

**Comment by MineGame159** [comment]
@YEETboi-debug what OS are you using?

**Comment by RedCarlos26** [comment]
I cannot reproduce

**Comment by YEETboi-debug** [comment]
I'm using Mac

**Comment by seasnail8169** [comment]
@MineGame159 FIX

**Comment by YEETboi-debug** [comment]
Thx

**Comment by RedCarlos26** [comment]
Is this still happening @YEETboi-debug

**Comment by YEETboi-debug** [comment]
I don't know didn't test yet

**Comment by arlomcwalter** [comment]
it is

**Comment by RedCarlos26** [comment]
Sad moment
