### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Intoprelised** [MeteorDevelopment/meteor-client#394]
When you disconect from a world or a server it crashes thats pretty much it.

**Comment by MineGame159** [comment]
Can you send the crash report

**Comment by Intoprelised** [comment]
kk one sec i disabled all the modules and it didint crash so there is on that makes it crash then

**Comment by Intoprelised** [comment]
btw this is the message 
![image](https://user-images.githubusercontent.com/78622918/113454350-07518700-93d6-11eb-83f4-1c8b891a380a.png)

**Comment by Intoprelised** [comment]
this is the crash report https://gofile.io/d/zcXpCI

**Comment by MineGame159** [comment]
Did you turn on every module or what 💀

**Comment by RedCarlos26** [comment]
This is just a config issue. I cannot reproduce.
