### ISSUE TITLE
[Suggestion] spinbot/derp

### ISSUE THREAD

**Issue by datcathuh** [MeteorDevelopment/meteor-client#3943]
### Describe the feature

spinning like crazy in circles or how u call it just spin like crazy

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
anti afk

**Comment by datcathuh** [comment]
> anti afk

nonono ik its there but make a feture so its random not a specifk yaw like random spinning in all directions

**Comment by datcathuh** [comment]
yk?
