### ISSUE TITLE
[SUGGESTION] No Render for minecarts 

### ISSUE THREAD

**Issue by killerbigpoop** [MeteorDevelopment/meteor-client#395]
**Describe the feature**
Just a simple no render for minecarts/water particles so it wont lag my client to 1 frame per 10 seconds

**Comment by MineGame159** [comment]
There already is Particle Blocker

**Comment by RedCarlos26** [comment]
For water particles, you can disable it when using the particle blocker module. For minecarts, that could be a great integration to the no render module.
