### ISSUE TITLE
controller support

### ISSUE THREAD

**Issue by Moosbee** [MeteorDevelopment/meteor-client#3950]
### Describe the feature

Controller Support with either [Controlify](https://modrinth.com/mod/controlify) or [MidnightControls](https://modrinth.com/mod/midnightcontrols).

Basically the 1.19.4 Arrow Navigation for ClickUI and Settingsscreen

https://github.com/MeteorDevelopment/meteor-client/issues/1236

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Fiz-Victor** [comment]
why you would use meteor on  a controller

**Comment by Moosbee** [comment]
on the steam deck, because my laptop is a potato

**Comment by Fiz-Victor** [comment]
there's a virtual mouse in the options, and guess that will work
