### ISSUE TITLE
[Suggestion] Auto switch baritone

### ISSUE THREAD

**Issue by 86PP** [MeteorDevelopment/meteor-client#3953]
### Describe the feature

auto switch to for not break tools and stop baritone and replay

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
[AutoTool and AntiBreak](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/systems/modules/player/AutoTool.java#L51) are aready a thing, and Baritone should by default use the best tool it has in the hotbar to mine something. I'm not sure whether baritone will still attempt to use the almost broken tool though, or switch to another one.

As for "stop and replay", that would be more appropriate as a suggestion to Beritone's repo, but I'm not sure it's a feature they're considering to develop at the moment.
