### ISSUE TITLE
[Suggestion] Store EasyMC token for further renewing

### ISSUE THREAD

**Issue by oie1** [MeteorDevelopment/meteor-client#3954]
### Describe the feature

Add a way to get the token. or store it in the accounts.nbt file...

Maybe a Renew button on the account on the accounts list?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by CoolestGuy94** [comment]
I support this idea

**Comment by TheKidThatCodes** [comment]
oops i reposted it lol

**Comment by CuteistCat** [comment]
yes!

**Comment by pixo2000** [comment]
Just a idea for the renew button: it creates a browser in minecraft(just Background) where it also uses a hCaptcha solver to solve the captcha and then just enters the token

**Comment by TheKidThatCodes** [comment]
> Just a idea for the renew button: it creates a browser in minecraft(just Background) where it also uses a hCaptcha solver to solve the captcha and then just enters the token

hcaptcha solvers cost money

**Comment by pixo2000** [comment]
ah sad then i need to find a free one if one exists

**Comment by denisapain** [comment]
Thanks misten :D
