### ISSUE TITLE
Meteor 1.12.2?

### ISSUE THREAD

**Issue by LowKeyy07** [MeteorDevelopment/meteor-client#396]
**Describe the feature**
Meteor for 1.12.2. All the same modules, hacks, and GUI (Not counting BedAura, AnchorAura, etc.)

**Screenshots**
![image](https://user-images.githubusercontent.com/78048791/113463586-a08f9600-93f4-11eb-8369-27072b4fd788.png)

**Additional info**
Asking for this because i'm bad at java so I can't code it.

Best Regards,
LowKeyy_07

**Comment by MineGame159** [comment]
Are you using 0.3.3????? 💀

**Comment by LowKeyy07** [comment]
The download link won’t work for 0.3.3idk if its something to do with my adblockers/browser. Sent from Mail for Windows 10 From: MineGame159Sent: Saturday, April 3, 2021 5:43 AMTo: MeteorDevelopment/meteor-clientCc: LowKeyy07; AuthorSubject: Re: [MeteorDevelopment/meteor-client] Meteor 1.12.2? (#396) Are you using 0.3.3????? 💀—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by seasnail8169** [comment]
what the

**Comment by MineGame159** [comment]
???????????

**Comment by Lovecrafts-Cat** [comment]
I think his email service fucked up the mail format, but he wanted to say this:

> The download link won’t work for 0.3.3idk if its something to do with my adblockers/browser.

**Comment by seasnail8169** [comment]
You know we are currently on 0.4.2 right? Probably 0.4.3 soon…

**Comment by LowKeyy07** [comment]
I do know, but I'm trying to get Meteor for 1.12.2 bc the crystal aura is fucking insane and 0.4.2 is 1.16 and I can't find a single download where it's 1.12.2

**Comment by MineGame159** [comment]
`and I can't find a single download where it's 1.12.2`
Because there never was

**Comment by LowKeyy07** [comment]
oh
now i feel like a dipshit
i mean i probably am
