### ISSUE TITLE
[Bug] Baritone dosnt pause when killaura is trying to kill

### ISSUE THREAD

**Issue by Fishy38** [MeteorDevelopment/meteor-client#3960]
### Describe the bug

When kill aura is enabled and the option to pause baritone is enabled when a mob comes into distance to kill it does not pause baritone which just makes you mine while getting murdered :)

### Steps to reproduce

```bash
enable killaura with the option pause bairtone on then have bairtone doing something and a selected mob walk into killing distance.
```

### Meteor Version

v0.5.4 build #1907

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Fishy38** [comment]
The reason it did not work was because i did not have auto switch enabled on KA. Maybe make baritone pause only an option when auto switch is enabled so people will know?

**Comment by zydiaa** [comment]
> The reason it did not work was because i did not have auto switch enabled on KA. Maybe make baritone pause only an option when auto switch is enabled so people will know?

Thank you! This solved my problem. This should really be auto activated!
