### ISSUE TITLE
[Suggestion] Better freecam

### ISSUE THREAD

**Issue by Fishy38** [MeteorDevelopment/meteor-client#3961]
### Describe the feature

If you press f+3g (windows) you can see chunk borders and with most other clients while in freecam you can see the chunk borders for where your freecam character is. This client only shows you the chunk border your actual player is standing in while in Freecam. It would be awsome if you could see the chunk borders while in freecam.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
> If you press f+3g

I can't find "3g" on my keyboard, am I doing something wrong?

**Comment by Fishy38** [comment]
f3+g
-_-

**Comment by Starmania** [comment]
+ Tab in chat on looked block shoud be the one looked by freecam

**Comment by MineGame159** [comment]
Added in 3e1df8383ae3f7d963aeadc7b95c190685692a3e.
