### ISSUE TITLE
bug while using block esp

### ISSUE THREAD

**Issue by Nasligamer2** [MeteorDevelopment/meteor-client#3966]
### Describe the bug

im using block esp on 2b2t and im triyint to esp portals to escape spawn, but portals do not appear but these glitched blocks yes, look

![Captura de pantalla (49)](https://github.com/MeteorDevelopment/meteor-client/assets/142456433/2c6d3455-6343-4eb5-b9bd-0c663f1a746e)

### Steps to reproduce

```bash
try to esp portals on 2b2t
```

### Meteor Version

dev build 1.20.1

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Nasligamer2** [comment]
look this one
![Captura de pantalla (50)](https://github.com/MeteorDevelopment/meteor-client/assets/142456433/13e67054-9a9c-4d8f-b372-153e6ea8bb07)

**Comment by Fiz-Victor** [comment]
You can try to use this build: https://github.com/MeteorDevelopment/meteor-client/suites/15186682427/artifacts/867805880

**Comment by supakeks** [comment]
Know bug, devs are aware of it. Use dev build 0.5.4 1898 for now.
