### ISSUE TITLE
[Suggestion] Nuker breaking seeds and fully grown wheat crops.

### ISSUE THREAD

**Issue by Shoesniffer** [MeteorDevelopment/meteor-client#3970]
### Describe the feature

For nuker, whenever I select wheat crops it breaks wheat and seeds. It would be nice to have those as two different blocks to whitelist as I dont want to break the seeds. I only want to break fully grown wheat. This also goes for the other types of crops.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
Meteor Rejects has an Auto Farm Module, try that

**Comment by MineGame159** [comment]
That is because both of those are the same block, so Nuker cannot distinguish between them. Something like this would be more suited for a more general solution to select individual block states.
