### ISSUE TITLE
Autoreconnect Constantly sends you to the wrong server.

### ISSUE THREAD

**Issue by Razzy52** [MeteorDevelopment/meteor-client#3971]
### Describe the bug

When using autoreconnect it'll often send you to a completely different server? 

### Steps to reproduce

```bash
Use autoreconnect
```

### Meteor Version

Latest

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Update to the latest dev build
