### ISSUE TITLE
Add the Nasalization font

### ISSUE THREAD

**Issue by Cyrogigabyte** [MeteorDevelopment/meteor-client#3977]
### Describe the feature

https://www.dafont.com/nasalization.font
would love to see this font in meteor client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
meteor lets you use system installed fonts

**Comment by Cyrogigabyte** [comment]
> meteor lets you use system installed fonts

how
