### ISSUE TITLE
Pause on mine option in crystal aura doesn't work when auto city is used.

### ISSUE THREAD

**Issue by sleepingnep** [MeteorDevelopment/meteor-client#398]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by seasnail8169** [comment]
This isn't a bug, auto city mines blocks using packets which are only sent once therefore crystal aura would never pause. You may want to make a suggestion for a feature that pauses CA in order to auto city specifically.
