### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by kubaaa203** [MeteorDevelopment/meteor-client#3988]
### Describe the feature

Make it possible to bind one module on **multiple** buttons!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
Use macros

**Comment by ManInMyVan** [comment]
In macro:

*Replace <MODULE> with the module you want to have a second bind for.*

Set the name to anything you want.

Message number 1:
`.t <MODULE>`

Next set the bind.

Now you're done!
