### ISSUE TITLE
Strange multiplication of macro menu

### ISSUE THREAD

**Issue by mokeWe** [MeteorDevelopment/meteor-client#399]
**Describe the bug**
The macro menu doubles horizontally when you attempt to edit a macro
**To Reproduce**
1. Go to the Macros tab at the top of the screen,
2. Click on the edit button next to any macro,
3. Exit the macros menu by pressing escape or by hitting apply
4. See how the menu multiplies vertically.

**Expected behavior**
I expected to be able to edit a macro without a massive hitch such as this one.

**Screenshots**
![3zNyQw7lmd](https://user-images.githubusercontent.com/81923935/113516725-b2765380-9530-11eb-903a-0ab5a6f8939b.gif)

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).
I am using the meteor dev build 667, as well as sodium and the fabric API, both of which are updated.

**Comment by StormyBytes** [comment]
Isn't this fixed already?

**Comment by RedCarlos26** [comment]
Yes

**Comment by RedCarlos26** [comment]
Issue can be closed @mokeWe

**Comment by seasnail8169** [comment]
To my knowledge this hasn't been fixed.

**Comment by MineGame159** [comment]
Fixed
