### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by FarizFakhrudin** [MeteorDevelopment/meteor-client#3995]
### Describe the bug

Why is it that when I use the command "#mine diamond_ore" or something like that it always crashes? Is there something wrong or some kind of bug?

### Steps to reproduce

```bash
I don't know, when I die a few times maybe?
```

### Link to crash report/log if applicable (https://mclo.gs)

dont have

### Meteor Version

Dev Build 0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
You cannot seriously open an issue related to a crash and not post the crash log...
Go and fetch it as stated in our [FAQ](https://meteorclient.com/faq/getting-log), or else this is useles.

**Comment by FarizFakhrudin** [comment]
https://mclo.gs/DD3HKBy

**Comment by Starmania** [comment]
Remove in the folder `%appdata%\.minecraft\baritone\` the file `options.txt` (will reset baritone settings) or use this command in chat `#settings reset pathingMapLoadFactor`
