### ISSUE TITLE
Compatible with other client

### ISSUE THREAD

**Issue by bingchilliner** [MeteorDevelopment/meteor-client#3996]
### Describe the feature

if we make the client compatible with other than many newbie client  user wont worry of what to chose

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
thats retarded reasoning
just choose a client
there's absolutely no reason to have multiple clients at the same time, apart from "newbie client users," that are just too lazy to choose a client to get used to, who you shouldn't cater to

**Comment by bingchilliner** [comment]
ok thannks

________________________________
