### ISSUE TITLE
Can u make it work with Optifine? 

### ISSUE THREAD

**Issue by ItsLLolly** [MeteorDevelopment/meteor-client#3998]
### Describe the feature

So i bought myself an optifine cape a while ago and when i found meteor (love the client) i tried adding optifabric to the mods sadly it didnt work and know i cant use my cape i dont know if this can be made possible but please respond if it is possible or not

Thank you

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Unfortunately not really possible, optifine changes the game in an array of invasive ways and are closed source so it would be an unmanageable chore

**Comment by toxicdefender404** [comment]
if u want a client side cape u can just use a mod like this https://www.curseforge.com/minecraft/mc-mods/minecraftcapes-mod

**Comment by ManInMyVan** [comment]
If you want to use your optifine cape, you can use [openmcskins]() or [capes](https://modrinth.com/mod/capes)
