### ISSUE TITLE
Crystal Aura pause on Auto City

### ISSUE THREAD

**Issue by sleepingnep** [MeteorDevelopment/meteor-client#400]
**Describe the feature**
A setting in crystal aura where it pauses on auto city

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
would be nice if the ca pre targeted the auto city block

**Comment by RedCarlos26** [comment]
Is it not already automatic @seasnail8169?

**Comment by RedCarlos26** [comment]
Added in dev build #695.

**Comment by seasnail8169** [comment]
Similar to #605
