### ISSUE TITLE
[Suggestion] Pingbypass

### ISSUE THREAD

**Issue by HAV0X1014** [MeteorDevelopment/meteor-client#4001]
### Describe the feature

"Pingbypass" refers to running a remote - usually headless - instance of the Minecraft client as a 'server' and using a local Minecraft client to control the remote instance. The remote client would run its own instance of Meteor, and the local client would instruct the remote client on what to do (i.e., enable modules, move, look, connect to a game server, etc).

Pingbypass differs from a VPN or Proxy as the Pingbypass server would be the 'source' of the packets, not requiring a full round-trip back to the local client. This would essentially 'bypass' the slowdown caused by high latency for some modules.

Pingbypass would likely need to affect all modules in the client. An example of a client with Pingbypass is 3arthqu4ke's 3arthh4ck, where the 'server' instance runs a full instance of the game, and other clients can connect to the 'server' instance.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by tympanicblock61** [comment]
Might be hard for meteor because I doubt they will spend money on servers

**Comment by HAV0X1014** [comment]
Servers (ideally) would be self hosted by whoever wants to use Pingbypass.

**Comment by ridglef** [comment]
wouldnt sending your packets to a closer server to the minecraft server have the same latency or more

**Comment by Wide-Cat** [comment]
@ridglef the idea is to have a version of the client hosted on the closer server, so packets from something like crystal aura would come from that one, not your local client, reducing latency

**Comment by ridglef** [comment]
@Wide-Cat but wouldnt it be the same delay because your sending it to a server which sends it to a server
![pingbypass](https://github.com/MeteorDevelopment/meteor-client/assets/126202739/36057654-0851-4067-a54d-f671e38b5ff7)

**Comment by Fiz-Victor** [comment]
> @Wide-Cat but wouldnt it be the same delay because your sending it to a server which sends it to a server ![pingbypass](https://user-images.githubusercontent.com/126202739/264543488-36057654-0851-4067-a54d-f671e38b5ff7.png)

bruh could you use a flowchart software 10/10 drawing

**Comment by ridglef** [comment]
too laze

**Comment by Wide-Cat** [comment]
Using your example, there would only be a 20ms delay for the actions coming from the ping bypass server because it's closer than your client. Therefore, you do the processing and packet sending for stuff that desires a low latency, such as crystal aura or surround, from the ping bypass server.

**Comment by ridglef** [comment]
yeah but wouldnt it also take 20 ms to get to the ping bypass server

**Comment by Aspect-404** [comment]
Upvoting this, would love to see it added. My 3arthh4ck PingBypass is 1-2ms and makes a massive difference especially for poor ping players like me. I use USB tethering due to unstable wi-fi so my ping is roughly 350ms, making it difficult in CPvP.
