### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by biglines** [MeteorDevelopment/meteor-client#4004]
### Describe the bug

i used a addon and know i cant use another addon it says java.lang.RuntimeException

https://mclo.gs/qPsAGZw

### Steps to reproduce

```bash
add a addon
```

### Meteor Version

meteor-client-0.5.4-1920

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by supakeks** [comment]
That looks like it's an issue with whatever add-on you want to add, and not Meteor itself

**Comment by biglines** [comment]
> That looks like it's an issue with whatever add-on you want to add, and not Meteor itself

i deleted the addon and now it wont work
