### ISSUE TITLE
[SUGGESTION] Keybinds for profiles

### ISSUE THREAD

**Issue by tyrannus00** [MeteorDevelopment/meteor-client#401]
**Describe the feature**
Add the option to bind profiles to keybinds, so that when you press that key it automatically selects the profile.

**Additional info**
This would be useful, because you could switch profiles seemlessly while playing.
A toggle message that shows which profile got selected would also be useful.

**Comment by seasnail8169** [comment]
You can just make a macro for `.profile <name> load/save/delete`. It sends feedback in chat.
Make sure not to name your profiles with any spaces or they wont work in commands.
