### ISSUE TITLE
[Suggestion] Storing keybinds optional in profiles

### ISSUE THREAD

**Issue by tyrannus00** [MeteorDevelopment/meteor-client#402]
**Describe the feature**
An option for profiles that lets you choose whether you want to save keybinds or not.

**Comment by RedCarlos26** [comment]
I like this idea

**Comment by seasnail8169** [comment]
I dont, its gonna be complex to implement kekw.

**Comment by RedCarlos26** [comment]
I agree with you @seasnail8169. The thing is that each time a module is added, a hang Seoul's need to be made, and just removing key binds by hand is not really hard.

**Comment by seasnail8169** [comment]
a what

**Comment by RedCarlos26** [comment]
Lol I was monke I edited the comment

**Comment by RedCarlos26** [comment]
Maybe close the suggestion?

**Comment by seasnail8169** [comment]
This seems a bit niche, I dont want to add this.
