### ISSUE TITLE
Meteor crashes when using FreeCam

### ISSUE THREAD

**Issue by HIlight3R** [MeteorDevelopment/meteor-client#4020]
### Describe the bug

Minecraft crashes when trying to use FreeCam in the 2b2t queue.

I have tried the following possible solutions to the problem:
- Disabled all other mods except Meteor and Fabric API (I used ViaFabricPlus and Meteor Plus before)
- Used a different version of Java (Adoptium 17 LTS instead of the standard one in my launcher)
- Reset Minecraft and Meteor settings
- Reinstalled the drivers on my video card using DDU

All this did not bring any results.

Here are my PC specs if it's helpful:

- MB: Gigabyte B365M DS3H
- CPU: Intel Core i9-9900
- GPU: EVGA RTX 3060 Ti FTW3 Ultra
- RAM: 4x8GB DDR4-2666
- SSD: Samsung M.2 PM9A1 1TB

Here are all the log files I found:
- [tl-logger15362173464371614804.txt](https://github.com/MeteorDevelopment/meteor-client/files/12465004/tl-logger15362173464371614804.txt)
- [hs_err_pid7236.log]

###  Steps to reproduce

```bash
- Use Meteor 0.5.4-1917
- Connect to the 2b2t.org queue
- Enable FreeCam
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/Vg1IWFY

### Meteor Version

0.5.4-1917

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Fiz-Victor** [comment]
Install sodium they have a workaround
