### ISSUE TITLE
Support for Better than Adventure?

### ISSUE THREAD

**Issue by shawnjb** [MeteorDevelopment/meteor-client#4023]
### Describe the feature

With the recent release of Better than Adventure, which has gained incomprehensible popularity, with it came some anarchy servers.

There is a client out there called ASMLoader which is practically Better than Adventure & Babric combined. With this in mind, I would assume that the implementation would not be too difficult, other than dealing with a different block ID system (if any). From what I can tell, the only difference I've seen is that loading a texture pack from native Beta 1.7.3 will be mixed up with new blocks added into the mod, so I can take a good educated guess that the game is using a **numerical block ID system** like the original game.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Fiz-Victor** [comment]
wrong repo?

**Comment by shawnjb** [comment]
> wrong repo? dont understand what you want

Not the wrong repository. Babric is a fork of Fabric, made for Beta versions of Minecraft.
