### ISSUE TITLE
Config loading leads to crash

### ISSUE THREAD

**Issue by SeedCrackerXEnjoyer** [MeteorDevelopment/meteor-client#4024]
### Describe the bug

loading any config that would have previously worked just fine all of a sudden crashes my game now.

### Steps to reproduce

```bash
I don't know how to reproduce it because it happened randomly.
```

### Meteor Version

0.5.4 1853 

### Minecraft Version

1.20 fabric

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
You can't seriously post a crash issue and not provide the related [crash log](https://meteorclient.com/faq/getting-log).

**Comment by SeedCrackerXEnjoyer** [comment]
> You can't seriously post a crash issue and not provide the related [crash log](https://meteorclient.com/faq/getting-log).

I don't think it produces a crash report because, for a split second before crashing, it says "saving world" as if Minecraft expects to be closed.

**Comment by SeedCrackerXEnjoyer** [comment]
I found out the issue, my laptop was just bad. I have to let Minecraft run for 5 minutes to stabilize my laptop and then use configs
