### ISSUE TITLE
".wp add" specify coordinates

### ISSUE THREAD

**Issue by Rommmmaha** [MeteorDevelopment/meteor-client#4031]
### Describe the feature

add the ability to specify coordinates when creating waypoints:
.wp add Name
.wp add Name x y z
.wp add Name ~-5 ~ ~53

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
You can specify the coordinates when you create it in the waypoints settings

**Comment by Rommmmaha** [comment]
i know, but its faster and easier (for me) to use chat command

**Comment by Starmania** [comment]
Commit 77aa25e107db479c65feea6c71143c5cbd070b7e could close this issue if relative coordinates where accepted

**Comment by Starmania** [comment]
@Big-Iron-Cheems

**Comment by Big-Iron-Cheems** [comment]
For technical reasons, we currently can't provide support for relative coords, as they require `ServerCommandSource`, while all our commands use `CommandSource`.
I hope that in the future we may be able to extend our commands system to allow more command types.

**Comment by RacoonDog** [comment]
> If anyone is interested in working on this, feel free to give it a try and open a PR once ready.
:3
