### ISSUE TITLE
Compatibility with wurst client?

### ISSUE THREAD

**Issue by BOT53423** [MeteorDevelopment/meteor-client#4038]
### Describe the feature

Just compatibility with wurst client like it was working some years before.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
no

**Comment by ManInMyVan** [comment]
Wurst is bad

**Comment by BaconDave312** [comment]
N O
