### ISSUE TITLE
I would really like to have the aim assist module backe in the 1.20.1 build

### ISSUE THREAD

**Issue by neelanshj** [MeteorDevelopment/meteor-client#4039]
### Describe the feature

Helps aim on nearby players and other entities.
For PVP

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by neelanshj** [comment]
'Closed #4039
<https://github.com/MeteorDevelopment/meteor-client/issues/4039> as
completed.' means the feature is added??

**Comment by Fiz-Victor** [comment]
its in rejects

**Comment by neelanshj** [comment]
why?????
