### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#404]
**Describe the bug**
Using the new profile system and adding or removing an automatic configuration IP will duplicate the UI somehow? 

**To Reproduce**
1. Go to the settings tab and create a new profile
2. Add an IP address to the field for "Load when joining:" (optional), and then click the plus button.
3. Watch the UI perform mitosis!

**Expected behavior**
The IP addresss should be added to a list, like other modules.

**Screenshots**
https://streamable.com/kfhvho

**Comment by seasnail8169** [comment]
Fixed in 6b05095.
