### ISSUE TITLE
Crash on 1.20.1 with mod

### ISSUE THREAD

**Issue by Fleepe** [MeteorDevelopment/meteor-client#4040]
### Describe the bug

After adding PacketFixer mod to my modpack the game crashes.
Everything is updated: Windows 10 (22H2), Adoptium Java 17 (17.0.8.7) for 1.20.1, Meteor and mod too.
The creator of the mod told me that the game is crashing due to a meteor client.
[crash-2023-09-03_22.15.54-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/12507198/crash-2023-09-03_22.15.54-client.txt)
[latest.log](https://github.com/MeteorDevelopment/meteor-client/files/12507199/latest.log)

### Steps to reproduce

```bash
1. Download Meteor and PacketFixer.
2. Start the game and try to create / load any world.
3. Game crashes.
```

### Meteor Version

meteor-client-0.5.4-1925

### Minecraft Version

Minecraft 1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by xiaofengv233** [comment]
me too

**Comment by Fiz-Victor** [comment]
you can turn on `AntiPacketKick` and this module contains all features from `PacketFixer`

**Comment by Fleepe** [comment]
@Fiz-Victor Didn't know that, thanks. But it's always better to make sure that the meteor does not crash the game with any mods.

**Comment by JuviGamez** [comment]
This Happend to me but in 1.20.2, try any other mod and see if it crashes if i add a meteor client addon it dosent even start and dosent even say it crashed but if add some other mod unrelated to metero client it starts but if i load a world it crashes with a error message i am using the modrinth app btw
