### ISSUE TITLE
NOT LOGGING IN 

### ISSUE THREAD

**Issue by bumperYEYE** [MeteorDevelopment/meteor-client#4042]
### Describe the bug

SO I HAVE BEEN USING METEOR FOR A WHILE NOW BUT FOR THE PAST MOUNTH I HAVE HAD THIS PROBLEM WERE NO MATTER WHAT I DO TO TRY TO LOG IN IT ALWAYS LOGS ME IN AS SEASNAIL WHEN I LOOK AT MY SKIN IM A STEVE CAN ANYONE HELP ME WITH THIS IF YOU KNOW HAW TO FIX IT 

### Steps to reproduce

```bash
LOGGING IN
```

### Meteor Version

ALL

### Minecraft Version

ALL

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
disable name protect
