### ISSUE TITLE
Elytra recast autowalk suggestion

### ISSUE THREAD

**Issue by someone39212321** [MeteorDevelopment/meteor-client#4044]
### Describe the feature

elytra recast mode makes it so you automatically walk. a toggle for this would be nice!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by arlomcwalter** [comment]
just bind auto walk (in simple mode) to the same key as ely fly

**Comment by someone39212321** [comment]
i meant to turn it off not turn it on. it does that anyway without autowalk
