### ISSUE TITLE
elytra recast feature

### ISSUE THREAD

**Issue by someone39212321** [MeteorDevelopment/meteor-client#4045]
### Describe the feature

would be nice to have  acceleration feature

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
What does that even mean

**Comment by someone39212321** [comment]
actually just add a yaw lock feature so we can toggle it

**Comment by master7720** [comment]
> What does that even mean

Boze has it or smt

**Comment by GreemDev** [comment]
3 suggestions and all 3 of them are brainrot
