### ISSUE TITLE
Question regarding upstreaming network-specific features

### ISSUE THREAD

**Issue by amxda** [MeteorDevelopment/meteor-client#4052]
### Describe the feature

Hello!

Assuming compliance with all functionality and style guidelines, does the Meteor client accept contributions of modules developed for a particular Minecraft network?

I have searched through the documentation and wiki, and haven't found anything to answer this.

Thank you :)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
Only if the server allows cheating, so for example (most) anarchy servers

**Comment by amxda** [comment]
Thank you for the answer, marking as closed.
