### ISSUE TITLE
[Suggestion] Allow the account manager to support more than 3 accounts

### ISSUE THREAD

**Issue by terrysgg** [MeteorDevelopment/meteor-client#4054]
### Describe the feature

When you load a 4th, 5th, 6th alt account into the account manager - it deletes every account after the 3rd one when Minecraft is restarted

IDK if this one is a "Feature" or a bug with the account manager

But I saw lots of posts on the discord about this issue

Would love to see this fixed / improved - as account manager is also something Rusherhack currently does not have in their 1.20 version

3 accounts is currently kinda a weird limitation

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by terrysgg** [comment]
Anyone know if this one has been looked into?

Would love to add more than 3 accounts to the account manager

**Comment by spazmilk** [comment]
Bump? how has this not been fixed yet.

**Comment by terrysgg** [comment]
I've tested this change in the latest version of Meteor for 1.20.6, and Im guessing its not in the release yet, because its still occurring in 0.5.7

Do you know what version this code will make it into the game?
