### ISSUE TITLE
http proxies

### ISSUE THREAD

**Issue by someone39212321** [MeteorDevelopment/meteor-client#4055]
### Describe the feature

http proxy support

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Fiz-Victor** [comment]
why

**Comment by someone39212321** [comment]
faster proxies

**Comment by Fiz-Victor** [comment]
http cannot proxy sockets
you can use software to convert other kind of proxies into socks4/5

**Comment by Paddyk45** [comment]
Pretty sure that http proxies are only for, well, HTTP requests
Minecraft uses TCP
