### ISSUE TITLE
CrystalAura calculation

### ISSUE THREAD

**Issue by eqwdsamosadomsa** [MeteorDevelopment/meteor-client#4056]
### Describe the feature

Now crystal, the faster you run, the more fps drops

I don't know what the fps problem is, the game is 20 ticks, it makes more unnecessary calculations in this time period (I think about this) and as a result, it reduces unnecessary fps And it doesn't happen when you put it slow

And the more players around me, the more calculations they make and the fps decreases as a result

Maybe maxTargets 1-10 can be made for CrystalAura and redundant calculation correction

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
Does your FPS noticeably decrease?

**Comment by eqwdsamosadomsa** [comment]
It happens when there are too many players and when ca is too fast
