### ISSUE TITLE
meteor shits itself if trying to crystalaura ender dragon[Bug]

### ISSUE THREAD

**Issue by ekcire06** [MeteorDevelopment/meteor-client#406]
**Describe the bug**
when trying to crystalaura ender dragon, the game lags very hard. 1 frame every 5 seconds type shit.

**To Reproduce**
1: join multiplayer server
2: summon ender dragon
3: turn on crystalaura and go up to enderdragon
4: let computer roast for aprox 5 minutes until fully baked

theres not much more to explain...

**Comment by RedCarlos26** [comment]
It happens with withers too. I think this is not possible to fix, because it is linked to the crystals placement calculations.

**Comment by ekcire06** [comment]
theres an fps drop with withers, but its really minor. for me it goes to 120 -> 40fps, noticiable but not a big deal.

with the ender dragon  windows telll you minecraft stopped responding.
