### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Amnessie** [MeteorDevelopment/meteor-client#4065]
### Describe the bug

When hitting wool Shears do not get auto-switched to when auto-tool is active

although I just saw this post from Sep 11, 2021 it has deemed fixed I think but it is not fixed yet 

anyone has any suggestions?

### Steps to reproduce

```bash
activate autotool, put pickaxe hatchet and shears in hotbar then hit a stone wood and a wool block and u will see it does not switch to shears automatically when holding the mouse1 like it changes to pickaxe and hatchet when u are hitting stone and wood.
```

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by bruh1273** [comment]
Glad I was searching through bugs because I was *just* about to report this. Same concept applies to leaves. No reason this shouldn't be fixed.
