### ISSUE TITLE
[Bug] Crashes

### ISSUE THREAD

**Issue by retree1** [MeteorDevelopment/meteor-client#4067]
### Describe the bug

Crashes when using Optimization mods, Not sure what is incompatible which is causing mc to crash (Fabric Mods are in the log)

### Steps to reproduce

```bash
^^^
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/7dC03KY

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Does this happen with just meteor on it's own? If not, then try to figure out which mod is causing it. My guesses would be `wnt` or `disableinsecurechattoast`

**Comment by retree1** [comment]
> Does this happen with just meteor on it's own? If not, then try to figure out which mod is causing it. My guesses would be `wnt` or `disableinsecurechattoast`

Thanks but I found the issue `Concurrent Chunk Management Engine` is incompatible with meteor.

**Comment by retree1** [comment]
`Concurrent Chunk Management Engine` was incompatible with meteor. (If this would be "fixed" in the next update ill be grateful)
