### ISSUE TITLE
auto walk mobs avoidation

### ISSUE THREAD

**Issue by Nickelless1** [MeteorDevelopment/meteor-client#4068]
### Describe the feature

The suggestion I'm making is to have an additional setting on auto walk to make it so it'll avoid mobs with an additional menu to change the specific mobs.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Baritone.
