### ISSUE TITLE
Add durability to Better tooltips

### ISSUE THREAD

**Issue by t1m013y** [MeteorDevelopment/meteor-client#4070]
### Describe the feature

Add tool/armor/item durability to Better tooltips

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
Press F3+H
