### ISSUE TITLE
Sodium Crash

### ISSUE THREAD

**Issue by LOLYAYDEV** [MeteorDevelopment/meteor-client#4072]
### Describe the bug

![image](https://github.com/MeteorDevelopment/meteor-client/assets/118024018/1b12ecca-ca5d-4be7-9dca-139835e27ce9)
I tried to start Minecraft with sodium but i get the crash i used Atlauncher and downloaded sodium from modrinth and metor dev build 1.20.
My mods:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/118024018/334d1495-a94f-4f45-b221-84b0c4b98c44)

### Steps to reproduce

```bash
Just download the mods in atlauncher with metor and doesnt work!
```

### Link to crash report/log if applicable (https://mclo.gs)

https://paste.atlauncher.com/view/3fbd361c-6cf1-40e1-8cef-35bb3c48174d

### Meteor Version

meteor-client-0.5.4-1935.jar

### Minecraft Version

1.20

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Fiz-Victor** [comment]
the log literally tells you what to do

**Comment by Wide-Cat** [comment]
Use the latest version of sodium
