### ISSUE TITLE
[Bug] searching in "Add new HUD-Element" crashes game

### ISSUE THREAD

**Issue by Techline420** [MeteorDevelopment/meteor-client#4073]
### Describe the bug

typing anything in the "Add new HUD-Element" and pressing "Enter" crashes the game.

The Minecraft Launcher error code is "-1"

### Steps to reproduce

```bash
see description
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/oSlnLPQ

### Meteor Version

0.5.3

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Paddyk45** [comment]
It doesnÄt just crash if you enter "dir", it crashes when you type anything

**Comment by Wide-Cat** [comment]
Can you send a crash report

**Comment by Techline420** [comment]
oh wow, true. Changed the bug report. `

How do I get a crash report?

**Comment by Wide-Cat** [comment]
https://meteorclient.com/faq/getting-log

**Comment by Techline420** [comment]
> Can you send a crash report

https://mclo.gs/oSlnLPQ

here you go
