### ISSUE TITLE
Slider crash (The issue is Better Chat Anti Spam)

### ISSUE THREAD

**Issue by Anonymous3-a** [MeteorDevelopment/meteor-client#4076]
### Describe the bug

This only works in-game? I don't know why. I am using Quilt instead of Fabric, but Quilt is compatible with Fabric, so I hope there's no problem with that. According to the crash logs, it's an issue with the Better Chat module (specifically the anti spam), so is that a problem for a separate repo?

### Steps to reproduce

```bash
Go to the settings menu, then navigate to chat settings. Once there, adjust the Focused Height slider, and it crashes.
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/WYdhrF1

### Meteor Version

Dev Build, 1.5.4

### Minecraft Version

20.1

### Operating System

Linux

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Paddyk45** [comment]
Can't reproduce, what are your active modules and better chat settings?

**Comment by Anonymous3-a** [comment]
Modules (Overview):
```
Auto Tool
Fast Climb
Better Tooltips
Break Indicators
Camera Tweaks
Trajectories
Unfocused CPU
No Ghost Blocks
Better Beacons
Better Chat
Better Tab
Inventory Tweaks
```

Better Chat settings (if I don't mention it, it's false, or in the case of text boxes/sliders, default):
```
Player Heads on
Coords Protection on
Keep History on
Anti Spam (this appears to be mentioned in the crash logs) on
 Depth 20
Infinite Chat Box on
Longer Chat History on
Extra Lines (1000)
```
