### ISSUE TITLE
[Suggestion] Better Building

### ISSUE THREAD

**Issue by Myithspa25** [MeteorDevelopment/meteor-client#4078]
### Describe the feature

When using `#sel paste` the current system checks for items with specific block states (ie a lever on a specific face) and, even when the correct item is there, pauses the build until I manually place it exactly how it wants.

It probably wouldn't take too long to change this to just *having* the item.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)
- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Open this issue in the baritone GitHub page
