### ISSUE TITLE
[Suggestion] GOBLIN!!!!!!!!

### ISSUE THREAD

**Issue by SH1TEATINGOBLIN** [MeteorDevelopment/meteor-client#4080]
### Describe the feature

MAKE IT SO YOU CAN AJUST THE SCALE IN BETTER TAB OR MAKE BETTER TAB EXPAND VERTICALLY!!!!!!!!!!! WHEN I AM ON TWO BUILDERS TWO TOOLS THE TABLIST OVERLAPS ON ITSELF!!!!!!!!!!!! THIS ONLY HAPPENS WHEN MY GUI SCALE IS SET TO 3, BUT THAT IS THE GUI SCALE I PREFER!!!!!!!!!!

PLEASE CONSIDER THIS SUGGESTION IT WOULD HELP MANY METEOR USERS

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
what

**Comment by FlightXamb** [comment]
what ?
Also please dont type in caps please
