### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by ncneLV** [MeteorDevelopment/meteor-client#4081]
### Describe the feature

Add Auto Enchant Mod

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
And what exactly would the auto enchant mod do? Would it impossibly force add an enchantment in survival mode? Would it use an anvil? Would it use an enchant table? Would it use a grindstone? Please be more specific.
