### ISSUE TITLE
Minecraft crash due to error in meteor client

### ISSUE THREAD

**Issue by Visalyputra** [MeteorDevelopment/meteor-client#4085]
### Describe the bug

I just launch the Minecraft with meteor client in it and suddenly crash. upon checking it said that could not execute entrypoint stage 'prelaunch' due to error provided by 'meteor client' 

Please help me fix this one. 

### Steps to reproduce

```bash
I just download the latest fabric installer and after that i just download the latest meteor client dev-build 1.20.1 and put it into the mods folder of mincraft directory and launch it. 

after that the error comes out provided in the crash report/log link
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/CAERr9A

### Meteor Version

1.20.1

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
send the full crash report

**Comment by Fiz-Victor** [comment]
maybe mixinextras bug
