### ISSUE TITLE
Anti-Lag back feature

### ISSUE THREAD

**Issue by neelanshj** [MeteorDevelopment/meteor-client#4093]
### Describe the feature

This is just an idea and I am actually not sure if it is even possible, but I was thinking abut a new module or feature that allows players to use the other modules without getting lagged back again and being forced to play as if meteor isn't even in use.I saw two different hackers in two different bedwars games and both of them were completely unaffected by the anticheat of the server while I was only able to use rendering modules like esp and tracers.If this is actually not possible and someone else knows better than me,please gmail me at neelansh2407@gmail.com because I often don't remember to check my github for comments,that is, if you want to tell me.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by neelanshj** [comment]
Also,I am sorry for suggesting such a thing if it turns out to be impossible

**Comment by Meesterbouwer123** [comment]
You get lagged back for a bad config, so if you just take some time to improve your config you won't be lagged back

Also meteor isn't designed for servers where you aren't allowed to hack, use a ghost client instead

**Comment by neelanshj** [comment]
oh,sorry

**Comment by ManInMyVan** [comment]
> use a ghost client instead

I think he wants to use a blatant client.

Assuming you're wanting 1.8, here's some options:
- Paid:
 - [Novoline](https://novoline.wtf)
 - [Rise](https://riseclient.com)
 - [Moon](https://moonx.gg)
 - Free:
  - [NightX](https://github.com/Aspw-w/NightX-Client)
  -  [Liquidbounce](https://liquidbounce.net/download)
  - [FDP](https://fdpinfo.github.io/next)

**Comment by neelanshj** [comment]
ok,thanks

**Comment by ManInMyVan** [comment]
Please close this

**Comment by neelanshj** [comment]
done, sorry for leaving it open. :)
