### ISSUE TITLE
Futureclient compalibity

### ISSUE THREAD

**Issue by real-F-00** [MeteorDevelopment/meteor-client#4094]
### Describe the bug

Compability with Futureclient was broken in commit 738d0d93d24e80c7527ef67d95205dfe341ec253

the error is the following:
```
[19:11:32] [Render thread/WARN]: @ModifyConstant conflict. Skipping meteor
-client.mixins.json:PlayerListHudMixin from mod meteor-client-
>@ModifyConstant::modifyHeight(I)I with priority 1000, already redirected by mixins.future.common.json:render.MixinGuiPlayerTabOverlay from mod (unknown)-
>@ModifyConstant::f$C(I)I with priority 2147483647
```
after this warning the game crashes right away.

### Steps to reproduce

```bash
use Futureclient with version of meteor that contain the changes in this commit: 738d0d93d24e80c7527ef67d95205dfe341ec253
```

### Meteor Version

738d0d93d24e80c7527ef67d95205dfe341ec253

### Minecraft Version

1.20.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by VenroyDEV** [comment]
same issue here!

**Comment by BebSxy** [comment]
same

**Comment by NiftyHamish** [comment]
same
