### ISSUE TITLE
1.20.2?

### ISSUE THREAD

**Issue by Blayung** [MeteorDevelopment/meteor-client#4095]
### Describe the feature

An update to 1.20.2.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Awokein** [comment]
What exactly are you wanting updated? Can you explain further?

**Comment by Blayung** [comment]
Well, this mod.
