### ISSUE TITLE
is meteor client a rat?

### ISSUE THREAD

**Issue by FeydH** [MeteorDevelopment/meteor-client#4099]
### Describe the bug

i heard someone tell me it was and im wondering if it is or not.

### Steps to reproduce

```bash
please tell me if it is or not
```

### Meteor Version

idk

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by FeydH** [comment]
im serious

**Comment by RacoonDog** [comment]
yes 👍

**Comment by ManInMyVan** [comment]
POV: Mod is open source

\*People ask if it's safe to use*

**Comment by Big-Iron-Cheems** [comment]
With almost 4 million downloads, you'd think people would have complained by now if it were...

And as said before, it's open source, anyone's free to verify that themselves.

**Comment by identity7** [comment]
its a monero miner real
