### ISSUE TITLE
[Bug] Better tooltips shulker preview

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#410]
Shulker preview cannot be set on always in the latest dev build. If you set it on always, it goes back to keybind.

**Comment by seasnail8169** [comment]
This is not a bug, it is because you have your display mode set to screen. If you were to have display always and display mode screen, every time you hover over it, it would open a screen. This is intended functionality so if you want to use always, you must set display mode to container.

**Comment by RedCarlos26** [comment]
Oh ok
