### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by djhecker1** [MeteorDevelopment/meteor-client#4100]
### Describe the bug

everytime i try to download it it says no profile found?

### Steps to reproduce

```bash
by installing
```

### Meteor Version

1.20.2

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ManInMyVan** [comment]
I like how there isn't a 1.20.2 version
