### ISSUE TITLE
Switch from saving Setting in NBT to JSON

### ISSUE THREAD

**Issue by Moosbee** [MeteorDevelopment/meteor-client#4102]
### Describe the feature

Currently all of the Settings are saved in the NBT(Named Binary Tag) format. NBT is outside of the game unreadable and cannot be edited without a special tool. This is very inconvenient.

My Suggestion is switching to JSON.
JSON is the de facto standard in saving configs for mods.

Why does Meteor not use it?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Nbt is much faster to parse and more space efficient than json. The need to manually edit configs should be fairly minimal, and even if you need to there are plenty of decent tools to do it with

**Comment by Moosbee** [comment]
They are valid, but I do not think any of your arguments outweighs the comfort of quickly changing and reading JSON.
I can understand the speed factor although I do believe JSON parsing isn't that much slower, especially with gson.
I also understand the space efficiency of NBT... but they are settings files, they aren't big.
There is a certain ease of mind of having plain text config files.

**Comment by Talhoid** [comment]
you can simply use nbtexplorer to easily change the data, and like widecat said, its more efficient than syntax-based human-readable plaintext
