### ISSUE TITLE
Add railds blocks to spawn proofer 

### ISSUE THREAD

**Issue by wlm3201** [MeteorDevelopment/meteor-client#4107]
### Describe the feature

Railds blocks stop spawns. Consider adding it to list of available blocks for spawn proofer.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ManInMyVan** [comment]
Railds

**Comment by MineGame159** [comment]
Added in 67b8753ef8a2af40214a3f53d58fb9aaf5825153.
