### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by aksyttt** [MeteorDevelopment/meteor-client#4111]
### Describe the bug

Whenever someone mine a block in your rendered chunk, it will be marked as a ghost block until you rejoin the server.

### Steps to reproduce

```bash
Whenever someone mine a block in your rendered chunk, it will be marked as a ghost block until you rejoin the server.
```

### Link to crash report/log if applicable (https://mclo.gs)

no crash 

### Meteor Version

0.5.4-1941 (latest dev build)

### Minecraft Version

1.20.1

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
Do you have the packet canceller module active by any chance
