### ISSUE TITLE
dev build.

### ISSUE THREAD

**Issue by Emelmr** [MeteorDevelopment/meteor-client#4112]
### Describe the bug

Soi was trying to download meteor on dev build on discord then i tried to download the 0.4.1 download file,But when i downloaded it its name is 0.5.4                   if you can pls send me mediafire link of 0.4.1 meteor client also 0.4.2 ad 0.4.3

Thank you

### Steps to reproduce

```bash
go to meteor discord go to dev build download any file u want
```

### Link to crash report/log if applicable (https://mclo.gs)

no logs

### Meteor Version

0.4.1

### Minecraft Version

1.16.5

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Old builds are not supported.

**Comment by Emelmr** [comment]
fast ahh response team
