### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Plintor** [MeteorDevelopment/meteor-client#4113]
### Describe the bug

A problem occurred configuring root project 'MyAddon1_19_2'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find meteordevelopment:meteor-client:0.5.1-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/User/Desktop/MyAddon1_19_2/.gradle/loom-cache/remapped_mods/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/User/Desktop/MyAddon1_19_2/.gradle/loom-cache/remapped_mods/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-SNAPSHOT.pom
       - https://maven.fabricmc.net/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/maven-metadata.xml
       - https://maven.fabricmc.net/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-SNAPSHOT.pom
       - https://libraries.minecraft.net/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/maven-metadata.xml
       - https://libraries.minecraft.net/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-SNAPSHOT.pom
       - https://libraries.minecraft.net/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-SNAPSHOT.jar
       - https://repo.maven.apache.org/maven2/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-SNAPSHOT.pom
       - file:/C:/Users/User/.gradle/caches/fabric-loom/0.5.1-SNAPSHOT/meteor-client.jar
       - file:/C:/Users/User/Desktop/MyAddon1_19_2/.gradle/loom-cache/0.5.1-SNAPSHOT/meteor-client.jar
       - https://maven.meteordev.org/releases/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/maven-metadata.xml
       - https://maven.meteordev.org/releases/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-SNAPSHOT.pom
       - https://maven.meteordev.org/snapshots/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/maven-metadata.xml
       - https://maven.meteordev.org/snapshots/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-SNAPSHOT.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

### Steps to reproduce

```bash
I just launched my project (addon on Meteor 1.19.2) and encountered these errors
```

### Meteor Version

0.5.1

### Minecraft Version

1.19.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
old versions are not kept up on the maven, that is to say you cant develop an addon for these old versions
currently, the only versions on the maven are `0.5.3` and `0.5.4-SNAPSHOT`

**Comment by GreemDev** [comment]
meteor maven is missing older dependencies (because for some reason it gets reset every like 4 months) which causes compilation to fail, as @RacoonDog said you'll need to develop for the latest
