### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by playernik2003** [MeteorDevelopment/meteor-client#4115]
### Describe the bug

after updating to 1.20.1 i updated all my mods in my mod list (uploaded) and wanted to start minecraft but meteor just crashes the game on startup

### Steps to reproduce

```bash
i am not sure how to reproduce it but i will upload crash report logs and modlist
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/KQBPpKX (log) https://mclo.gs/HuSuWan (crashreport) 

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ManInMyVan** [comment]
Try remove c2me

**Comment by playernik2003** [comment]
> Try removing c2me

Thanks it works now
