### ISSUE TITLE
[SUGGESTION] Ability to copy/paste colors onto color pickers like a csgo cheat

### ISSUE THREAD

**Issue by killerbigpoop** [MeteorDevelopment/meteor-client#412]
**Describe the feature**
Can copy paste colors from one color picker to another (if you right click it)

**Screenshots**
![image](https://user-images.githubusercontent.com/72179067/113607866-fc316d80-9606-11eb-923b-a92b99d0fc25.png)
![image](https://user-images.githubusercontent.com/72179067/113607881-02bfe500-9607-11eb-842a-94c7720d1193.png)

**Comment by RedCarlos26** [comment]
Really good idea. This would be useful for making everything the same colour.

**Comment by StormyBytes** [comment]
Maybe using hex?

**Comment by seasnail8169** [comment]
probably never gonna add this
