### ISSUE TITLE
ayo where is 1.20.2

### ISSUE THREAD

**Issue by ThrowerWay** [MeteorDevelopment/meteor-client#4120]
### Describe the bug

ayo where is 1.20.2?

### Steps to reproduce

```bash
ayo where is 1.20.2??https://3.bp.blogspot.com/-5UyWLmYYABs/UApQkFFTeYI/AAAAAAAANIU/QeBiFuaTHEQ/s1600/Hamster6.jpg
```

### Link to crash report/log if applicable (https://mclo.gs)

https://3.bp.blogspot.com/-5UyWLmYYABs/UApQkFFTeYI/AAAAAAAANIU/QeBiFuaTHEQ/s1600/Hamster6.jpg

### Meteor Version

not 1.20.2 :(

### Minecraft Version

1.20.2

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Check the [Pull Requests](https://github.com/MeteorDevelopment/meteor-client/pull/4119) page first next time.
