### ISSUE TITLE
Meteor client can't connect to Minecraft servers

### ISSUE THREAD

**Issue by Vortex-scripts** [MeteorDevelopment/meteor-client#4121]
### Describe the bug

The same error keeps appearing whenever I try to join a Minecraft server. I only have the Meteor client, and the most recent version of the Fabric API installed. I know it's Meteor because whenever I load Minecraft without it installed, I can join servers.

![Screenshot 2023-10-09 130017](https://github.com/MeteorDevelopment/meteor-client/assets/109775088/8d74b037-390f-4e8c-8e11-2110b75f5c7d)
![Screenshot 2023-10-09 130814](https://github.com/MeteorDevelopment/meteor-client/assets/109775088/0f74843c-e18d-4ae3-afe3-9474e49469aa)

### Steps to reproduce

```bash
Join a Minecraft server
```

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by identity7** [comment]
join a single player world and turn off anti-packet kick

**Comment by Wide-Cat** [comment]
should be fixed by 3a426d57c52c09ebc6f365905e2f6d2830febf47
