### ISSUE TITLE
[CRITICAL] Meteor baritone has issues mining below y0

### ISSUE THREAD

**Issue by TheKidThatCodes** [MeteorDevelopment/meteor-client#4125]
### Describe the bug

Meteor baritone has issues mining below y0
MERGE THE PR THAT FIXES IT PLS IM DIEING OF LACK OF DIEMONDS

### Steps to reproduce

```bash
`#mine` anything that can be below y0
```

### Link to crash report/log if applicable (https://mclo.gs)

na

### Meteor Version

0.5.5-1945

### Minecraft Version

1.20.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
this is not the baritone github

**Comment by TheKidThatCodes** [comment]
well, this will get seen quickly

**Comment by RacoonDog** [comment]
> well, this will get seen quickly

yes, but we are not the baritone people?

**Comment by Big-Iron-Cheems** [comment]
Closing since we are not the devs of Baritone, nothing we can do about it.
Go and report the issue to them, unless it's already known in their issues tracker.
