### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by qeqeqeplayer533** [MeteorDevelopment/meteor-client#4127]
### Describe the bug

it crashes the game

### Steps to reproduce

```bash
join a server with server hopping, basicly a lobby server that redirect u to another server, crash during redirection
```

### Link to crash report/log if applicable (https://mclo.gs)

https://mclo.gs/nB3Lv35

### Meteor Version

dev build 0.5.5

### Minecraft Version

1.20.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by ManInMyVan** [comment]
Try with just meteor installed
