### ISSUE TITLE
[Bug]Item Moving in inventory breaking

### ISSUE THREAD

**Issue by w1wwwwww** [MeteorDevelopment/meteor-client#413]
**Describe the bug**
When Auto Mend is enabled you cannot grab items in your inventory.

**To Reproduce**
1. Enable Auto Mend
2. Attempt to grab an item in your inventory

**Expected behavior**
Item is grabbed.

**Additional context**
mod list - [https://pastebin.com/LEVpUt1Q](https://pastebin.com/LEVpUt1Q)

**Comment by RedCarlos26** [comment]
I can confirm

**Comment by MineGame159** [comment]
Fixed in 3bb115cc11cb35dcd6326d5a202d54df3e6d5048

**Comment by MineGame159** [comment]
Fixed in 17306b395ac337ba25214b6ded4ea9dff55d5294
