### ISSUE TITLE
GameJoinedEvent does not get fired

### ISSUE THREAD

**Issue by Paddyk45** [MeteorDevelopment/meteor-client#4137]
### Describe the bug

The GameJoinedEvent does not get fired when you join a game.

### Steps to reproduce

```bash
Add an EventHandler for GameJoinedEvent and log when it received it. It will not log anything when you join a world/server
```

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Paddyk45** [comment]
Okay, enabling `runInMainMen` for the module seems to work, but the Notifier module doesn't have that so its GameJoined Event Handler doesn't work.

**Comment by Fiz-Victor** [comment]
It has been intended behavior long time ago

**Comment by Paddyk45** [comment]
huh
