### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by KrispyBigPvp** [MeteorDevelopment/meteor-client#414]
**Describe the feature**
A clear and concise description of what feature/change is.
I'm not too sure if you would be able to do this but it has something to do with baritone. How about having a like gps thing sorta and having it say up top on your screen or in chat the ETA to your destination if you have one set. Such as if I wanted to go from 0,0 to 1000, 1000 it would be cool to get an ETA on it. 
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

idk

**Comment by MineGame159** [comment]
This is a baritone suggestion, not a meteor one.
