### ISSUE TITLE
xray crashes game?

### ISSUE THREAD

**Issue by brenkel** [MeteorDevelopment/meteor-client#4142]
### Describe the bug

i tried to play on an earth server and i activate xray and game crashes instantly

### Steps to reproduce

```bash
1. go onto server
2. activate xray
3. game crash
```

### Meteor Version

0.5.5

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by brenkel** [comment]
another thing is that on other servers the xray doesnt do anything. is there like a new xray protection?

**Comment by 19MisterX98** [comment]
crash report?

**Comment by Coderx-Gamer** [comment]
What mods are you using with meteor?

Some rendering / optimization mods like sodium or optifine could potentially cause issues.

Try running meteor with no other mods and see if it still crashes.

**Comment by brenkel** [comment]
I don't use any optimization mods

**Comment by Big-Iron-Cheems** [comment]
Cannot reproduce, provide a crash report.
