### ISSUE TITLE
Modrinth [Suggestion] 

### ISSUE THREAD

**Issue by Aapeli1304** [MeteorDevelopment/meteor-client#4143]
### Describe the feature

Pls add Meteor client to Modrinth

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Mods like Meteor are not allowed there.

**Comment by Paddyk45** [comment]
https://modrinth.com/legal/rules
Cheats and Hacks

Projects cannot contain or download "cheats", which we define as a client-side modification that: 

is advertised as a "cheat", "hack", or "hacked client"

gives an unfair advantage in a multiplayer setting over other players that do not have a comparable modification and does not provide a server-side opt-out 

contains any of the following functions without requiring a server-side opt-in: 

X-ray or the ability to see through opaque blocks

aim bot or aim assist

flight, speed, or other movement modifications

automatic or assisted PvP combat

active client-side hiding of third party modifications that have server-side opt-outs 

item duplication
