### ISSUE TITLE
key combinations support for keybindings

### ISSUE THREAD

**Issue by Moosbee** [MeteorDevelopment/meteor-client#4144]
### Describe the feature

Currently you can only use one key per keybind. This is very inconvienient.

It would be nice to be able to use key combinations in keybinds. eg ctr+k

[tweakeroo](https://github.com/maruohon/tweakeroo) from masa is an example how this could work.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by sacdj1** [comment]
i agree!

**Comment by Wide-Cat** [comment]
implemented
