### ISSUE TITLE
[SUGGESTION] PistonAura

### ISSUE THREAD

**Issue by feliscatusmeows** [MeteorDevelopment/meteor-client#415]
**Describe the feature**
Uses a piston to push crystals into a player
**Screenshots**
https://www.youtube.com/watch?v=ItJz5kZhGHc
Add this so that hydra client has 0 anarchy pvp features meteor doesn't have.

**Comment by seasnail8169** [comment]
hydra still exists?

**Comment by feliscatusmeows** [comment]
yes, farmer joe/farmer jennifer owns it now.

**Comment by seasnail8169** [comment]
i dont think we will ever add piston aura

**Comment by feliscatusmeows** [comment]
:( I can't say hydra has no features meteor doesn't have.
