### ISSUE TITLE
[Bug(?)] Having sprint spoof enabled in AntiHunger causes FOV to spaz out when running on soul blocks with soul speed.

### ISSUE THREAD

**Issue by identity7** [MeteorDevelopment/meteor-client#4151]
### Describe the bug

I've worked it down to that. noslow, nofall, or any other movement related modules seem to work fine with soul speed. I'm not sure if this is a "bug" or an unfortunate, unfixable side effect, but ¯\_(ツ)_/¯ 

### Steps to reproduce

```bash
Enable AntiHunger with sprint spoof enabled, then run on a soul block with soul speed boots
```

### Meteor Version

0.5.5 1949

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Seaturtle111501** [comment]
when trying to recreate this bug i wasnt able to get it to work, the screen seemed fine. what may be related is that it isnt allowing me to sprint as it'll start then instantly going back to walking. I have attached a clip showing the problem. Is it that your screen is zooming in and out? 

https://drive.google.com/file/d/1bNFfd6UPBXNEWvtcTl1JFH6IhJ-H-Oyb/view?usp=drive_link
that is the clip
