### ISSUE TITLE
[Suggestion] auto 32k

### ISSUE THREAD

**Issue by TheKingOfVic** [MeteorDevelopment/meteor-client#4159]
### Describe the feature

Many client dont have auto 32k in 1.20. It is useful in some of the server. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by LLKawi** [comment]
this was patched in 1.19 and above iirc

**Comment by Wide-Cat** [comment]
What servers actually have 32k combat in the present day? Could you give some examples?

**Comment by TheKingOfVic** [comment]
8b8t.me, endcrystal.me , we can play in friend's server,
play.nobanmc.com   *doteh.xyz
<http://doteh.xyz>*
I hope that the glory of 2b2t 32k can be reproduced in version 1.20

Wide-Cat ***@***.***> 於 2023年10月23日 週一 下午7:26寫道：

**Comment by TheKingOfVic** [comment]
8b8t.me, endcrystal.me , we can play in friend's server,
play.nobanmc.com   doteh.xyz
doteh.xyz, doteh.xyz
I hope that the glory of 2b2t 32k can be reproduced in version 1.20

**Comment by TheKingOfVic** [comment]
If we launch auto 32k, we will be the first plugin to have this feature in version 1.20. Maybe it will more people use meteor. And  more server add 32k in the server because 1.20 has auto 32k.

**Comment by ManInMyVan** [comment]
32ks don't exist in 1.20, it's been capped at 255 since 1.17

**Comment by TheKingOfVic** [comment]
ik. just a habbit to call it 32k
