### ISSUE TITLE
[Bug] Entity Selector 

### ISSUE THREAD

**Issue by Ghost861** [MeteorDevelopment/meteor-client#416]
**Describe the bug**
A clear and concise description of what the bug is. On entity selection screens it will expand everything when u just expand one section

**To Reproduce**
1. Go to 'kill aura'
2. Click on 'Select Entities'
3. Click expand on one section

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc). Meteor version 687

**Comment by RedCarlos26** [comment]
I can confirm the bug.

**Comment by MineGame159** [comment]
Fixed in 3bb115cc11cb35dcd6326d5a202d54df3e6d5048
