### ISSUE TITLE
Meteor client issue 

### ISSUE THREAD

**Issue by ShivaXYZ2** [MeteorDevelopment/meteor-client#4160]
### Describe the feature

When I join server and then eat something and right om something getting are you sending to many packets when I start game with normal minecraft then nothing problem only getting on meteor client place help me im 1.20.1 version user please help me

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
what

**Comment by ShivaXYZ2** [comment]
I getting this error sir please help me

**Comment by Meesterbouwer123** [comment]
it helps if you would explain exactly what error you are getting, so we can help you
