### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by ShivaXYZ2** [MeteorDevelopment/meteor-client#4162]
### Describe the feature

what is best meteor client addon please tell 
(That' is my question not any problem so)
I'm waiting for your answer sir I'm waiting 🌝

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Talhoid** [comment]
@ShivaXYZ2 join the anticope discord and you can find addons there

**Comment by ManInMyVan** [comment]
[https://anticope.dev.pages](anticope.dev.pages)

**Comment by ManInMyVan** [comment]
> [https://anticope.ml](anticope.ml)

**Comment by LLKawi** [comment]
anticope.pages.dev now
