### ISSUE TITLE
Meteor Crashed! (Addon Causes)

### ISSUE THREAD

**Issue by ModxVoldHunter** [MeteorDevelopment/meteor-client#4163]
### Steps to reproduce

added Blackout (Addon) [LINK: https://github.com/KassuK1/Blackout/releases ] and Meteor Plus (Addon) [LINK: https://github.com/Nekiplay/MeteorPlus/releases ]

Started Minecraft 1.20.2 with Fabulously Optimized [Modpack]

Runs without the addons

LATEST LOG AT 10/23/2023
(Uploaded)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/LUkDrjM

### Meteor Version

Dev Build 1.20.2 Meteor Client

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
We are not the developrs of those addons, why are you reporting this to us?

**Comment by ModxVoldHunter** [comment]
just launched with different addons and it doesn't lunch, it wouldn't matter if your not the dev. you did make meteor detect if a addon is on, seems like Meteor Client is not detecting it and if it is then its causing an instant crash. as seen if you read the log. seems like meteor is trying to detect the addons but crashes instead

**Comment by Wide-Cat** [comment]
You dont know what you're talking about. Just contact the addon developers.

**Comment by ModxVoldHunter** [comment]
> You dont know what you're talking about. Just contact the addon developers.

alright

**Comment by ModxVoldHunter** [comment]
> You dont know what you're talking about. Just contact the addon developers.

i may not know much about java but i know this isn't a addon bug. i think its a meteor bug inside its Addon Manager code. 
plus i used your client many times and i have not had this problem.

**Comment by MineGame159** [comment]
If you know so much then explain this line sherlock. Addon manager isnt even mentioned anywhere.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/25082624/fc2a0f47-227f-41ba-bbf9-ad735900dc48)

**Comment by ModxVoldHunter** [comment]
when i was away and you both were doing what you were doing, i seperated the addons in separated instances in prism launcher, i launched them 1 by 1, non of the addons were launching minecraft and meteor detected them but never made it past a line in the command line. blackout, meteorplus and those that are updated with 1.20.2 didn't launch. 

i tried to see if other mods other then meteor and the addons were the problem but seems like the other mods weren't the problem. i might have to see if maybe its problem. i might have to see if updating my Adoptium JDK will fix anything. but i highly doubt it.

like i said, i don't know much. and i wasn't saying i know it all but i only checking. ill send the crash logs. for those as well. 

if your curious, im using the latest dev version of meteor from the website. like it said, its a development build so i have no idea. all i know that the past 1.20.1 dev build worked fine but not like this.

https://mclo.gs/j3FHDGe btw this log says something about baritone

 `[13:51:32] [main/WARN]: Error loading class: baritone/command/defaults/ComeCommand (java.lang.ClassNotFoundException: baritone/command/defaults/ComeCommand)`
 
 but that's pretty much all. i may run a test using the latest build

**Comment by ModxVoldHunter** [comment]
i deleted the last comment, because i believe it is useless to help. im sorry. closing.
