### ISSUE TITLE
Seed xray

### ISSUE THREAD

**Issue by FakeSiryakari** [MeteorDevelopment/meteor-client#4169]
### Describe the feature

you would insert seed to xray setting on your client and it would outline diamonds (or whatever ore you would want) based on seed, bcuz every normal server has antixray

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
If the server has an Anti-Xray then it most certainly is not an anarchy one.
You shouldn't be using Meteor there anyways, and there's mods that can do this already.
