### ISSUE TITLE
[Bug] Searching issue

### ISSUE THREAD

**Issue by Columner** [MeteorDevelopment/meteor-client#417]
**Describe the bug**
When searching for a module, if you narrow the search results down to a single result, the header for the result clips into the line on each side of the header. Interestingly, I failed to replicate the bug with module settings.

**To Reproduce**
1. Search for any module
2. Narrow the search results until there is only one module
3. See error

**Expected behavior**
The header line not clipping into the header.

**Screenshots**
![image](https://user-images.githubusercontent.com/58351403/113650389-79c2af80-96d3-11eb-9cf0-8e4250fdc1f9.png)

**Additional context**
Latest dev build (build 687)

**Comment by Lovecrafts-Cat** [comment]
Duplicate of #386, they are working on it already 👍

**Comment by Columner** [comment]
alright
