### ISSUE TITLE
Can you make a dupe mod as well for vanilla servers

### ISSUE THREAD

**Issue by mrxplasma** [MeteorDevelopment/meteor-client#4173]
### Describe the feature

Can you make a dupe mod as well for vanilla servers

all so can you upload or show me where you can get older meteor client versions? 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
2 dumb questions in one you really cant get much worse than this
