### ISSUE TITLE
auto clicker inverts its trigger[Bug] 

### ISSUE THREAD

**Issue by Something500** [MeteorDevelopment/meteor-client#4174]
### Describe the bug

While holding the key bind, if I hover my cursor over a chest, it opens correctly.
However, when I close the chest while still holding the key bind, the auto clicker turns off unexpectedly.
The auto clicker turns back on when I release the key bind, even though I'm no longer holding the key.

### Steps to reproduce

1: Enable the auto clicker and set it to toggle on key release.
2: Hold down the key bind for the auto clicker.
3: Hover your cursor over a chest to open it.
4: Close the chest while still holding the key bind.
5: Observe that the auto clicker turns off even though the key is still being held.
6: Release the key bind, and the auto clicker turns back on even though the key is not being held.

### Meteor Version

v0.5.4-1863

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by panpanpro888** [comment]
This is probably something with toggle on bind release, because the module's active state gets inverted.
