### ISSUE TITLE
Download not downloading[Bug] 

### ISSUE THREAD

**Issue by wolly369** [MeteorDevelopment/meteor-client#4178]
### Describe the bug

When i press download it takes me to a new tab to download as normal but it just says saying "Download will start in 5 seconds"

### Steps to reproduce

press download
wait
nothing

### Meteor Version

Release 0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by loma-baldsson** [comment]
1. not a client issue
2. disable your adblocker
3. (optional but recommended) uninstall opera gx if you're using it
4.

**Comment by Big-Iron-Cheems** [comment]
It's amusing how this issue affects only OperaGX users, really says somehing about their browser :trollface:

**Comment by MineGame159** [comment]
😱 What do you mean disabling javascript breaks websites

**Comment by wolly369** [comment]
edge is the best browser though

**Comment by loma-baldsson** [comment]
set the download page to only allow firefox useragents and redirect everyone else to a trollface
