### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by khanislegendabdul** [MeteorDevelopment/meteor-client#4180]
### Describe the bug

pls fix 1.19.4 aim assist missing brah

### Steps to reproduce

aim asisit misingg 1.19.4

### Meteor Version

1.19.4

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
We know, theres no justifiable reason to use it instead of killaura
