### ISSUE TITLE
[Bug] Download

### ISSUE THREAD

**Issue by Jaydentan7471** [MeteorDevelopment/meteor-client#4186]
### Describe the bug

When i press download i was waiting for it to download for 1 minute than it didnt donwload 

### Steps to reproduce

i just press the download button

### Meteor Version

1.20.1

### Minecraft Version

1.19.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
OperaGX issue, related to their adblocker.
Use another browser or try and see if disabling the ad blocker works
