### ISSUE TITLE
blocks like dirt cobble etc always go back into my main inventory

### ISSUE THREAD

**Issue by ItsLLolly** [MeteorDevelopment/meteor-client#4187]
### Describe the bug

everytime i but dirt into my invetory it always comes back to main inventory

https://github.com/MeteorDevelopment/meteor-client/assets/132750111/66471f25-d922-4b2d-8b5f-4dc50014e1fa

### Steps to reproduce

11

### Meteor Version

11111111111111111111111111

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
It's a baritone thing do `#allowInventory false`
