### ISSUE TITLE
[Suggestion] hello can you please add a dupe and add another fly but with levitation effect

### ISSUE THREAD

**Issue by Yukiri1** [MeteorDevelopment/meteor-client#4188]
### Describe the feature

hello can you please add a dupe and add another fly but with levitation effect

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by loma-baldsson** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/102317848/c22c2931-5542-4f71-8712-ad07a4188615)
