### ISSUE TITLE
Meteor crash on game open 

### ISSUE THREAD

**Issue by IvaskiyGooD** [MeteorDevelopment/meteor-client#4191]
### Steps to reproduce

I launch Minecraft and it crashes.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/3j8iPJo

### Meteor Version

Meteor 0.5.4

### Minecraft Version

Minecraft 1.20.1

### Operating System

Windows

### Before submitting a crash report

- [x] This crash wasn't already reported (I have searched crash reports on GitHub).

- [x] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
try removing the allow portal guis mod. Meteor already has a module for that, the `portals` module
