### ISSUE TITLE
Meteor crashing when I open the game

### ISSUE THREAD

**Issue by Hamude995** [MeteorDevelopment/meteor-client#4194]
### Steps to reproduce

1. Open the game

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/P7TBSR9

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
Meteor itself does not perform mixin transformations on its own classes, this crash is caused by an addon or another mod

**Comment by ModxVoldHunter** [comment]
what version of meteor plus were you using?

**Comment by Nekiplay** [comment]
> ### Steps to reproduce
> 1. Open the game
> 
> ### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)
> https://mclo.gs/P7TBSR9
> 
> ### Meteor Version
> 0.5.5
> 
> ### Minecraft Version
> 1.20.2
> 
> ### Operating System
> Windows
> 
> ### Before submitting a crash report
> * [x]  This crash wasn't already reported (I have searched crash reports on GitHub).
> * [x]  This is a valid crash (I am able to reproduce this on the latest dev build).

Use last version of Meteor plus
