### ISSUE TITLE
TPS HUD not working

### ISSUE THREAD

**Issue by PickSawPlzz** [MeteorDevelopment/meteor-client#4198]
### Describe the bug

The HUD have this section for TPS, and it's not changing. I don't know it is a bug or the server is glitching. 

### Steps to reproduce

1. I activated the mini HUD in meteor client.
2. TPS not working. 

### Meteor Version

Meteor Client 0.05 1949

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by moritz-t-w** [comment]
Well if you're on a decent server the tps is gonna stay constant, right?
