### ISSUE TITLE
[Suggestion] Auto Log clarify health value

### ISSUE THREAD

**Issue by moritztim** [MeteorDevelopment/meteor-client#4201]
### Describe the feature

Allow to set Health requirement in auto log to -1 or disable looking at health, so that auto log still logs me out if a 32k enters for example but not when I die

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Paddyk45** [comment]
Just set it to 0

**Comment by moritz-t-w** [comment]
Won't that logout when I die?

**Comment by moritz-t-w** [comment]
Just checked, it does

**Comment by moritz-t-w** [comment]
Nevermind lmao I had smart mode on

**Comment by moritz-t-w** [comment]
thanks

**Comment by moritz-t-w** [comment]
Actually, I think this should be clarified
