### ISSUE TITLE
[Bug] Telling baritone to place a pressure plate is weird

### ISSUE THREAD

**Issue by Myithspa25** [MeteorDevelopment/meteor-client#4205]
### Describe the bug

When baritone tries to place a pressure plate and it's standing on it, the bot just has a seizure and repeatedly breaks and places the pressure plate.

### Steps to reproduce

1. Have baritone place a pressure plate, preferrably the build is more than just the pressure plate.
2. Run baritone and wait
3. Baritone is a bit funky

Video for reference
https://github.com/MeteorDevelopment/meteor-client/assets/72114037/ffa758be-6b91-428f-a6b0-397481b623cc

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
report it to the baritone repo
