### ISSUE TITLE
Added support for Chinese display

### ISSUE THREAD

**Issue by 0x132406C** [MeteorDevelopment/meteor-client#4206]
### Describe the feature

"nametags" cannot display Chinese

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
part of #333

**Comment by 0x132406C** [comment]
> part of #333

tanks you ,I solved it.
