### ISSUE TITLE
[Bug] Adding a keybind to some modules doesn't work

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#421]
**Describe the bug**

Some modules like Air Jump can't be added to a keybind, I literally have no explanation for this.

**To Reproduce**

(Latest dev build)
Go to Air Jump in the click gui and try to bind a keybind to it, it won't work

**Expected behavior**

It should add a keybind which it doesn't

**Screenshots**
/

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by MineGame159** [comment]
Fixed in 76e9249bf2784269b61c00676684a629046aafbf
