### ISSUE TITLE
unlimited money

### ISSUE THREAD

**Issue by skylakekung** [MeteorDevelopment/meteor-client#4212]
### Describe the feature

two player in the server player 1 try and send every packet from every money plugin but the player1 doesn’t have a money and player 2 recieve unlimited money

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
No idea what this is supposed to mean, it's an incomprehensible list of words.
Anyways, if this was a request for supes or something similar, it does not concern us.
