### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Mert4131** [MeteorDevelopment/meteor-client#4215]
### Describe the feature

How to get dupe button pls help 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We have nothing to do with dupes.
You're probably thinking of some addon.
