### ISSUE TITLE
Village in .locate

### ISSUE THREAD

**Issue by XitsXZyloX** [MeteorDevelopment/meteor-client#4216]
### Describe the feature

 locating villages in .locate (.locate village)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Not possible without the seed, and if you have the seed there are many tools online to do it
