### ISSUE TITLE
[Suggestion] WitherBot

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#422]
**Describe the feature**
A module that automatically spawns withers in possibly the most efficient way. Idea isn't mine, but the method worth looking into is found in this video (https://www.youtube.com/watch?v=-ZRdj4azyEg) at about 1:31. 

**Additional info**
Credit to whoever this youtuber is for the idea

**Comment by seasnail8169** [comment]
swag

**Comment by Wide-Cat** [comment]
that is so fucking ridiculous and over the top, but absolutely amazing

**Comment by ekcire06** [comment]
im going to try to make this. itll prob take a few days because im kinda bad.

if you arent concerned about legitmacy you can spawn withers about 30% faster by skipping the support cobble

**Comment by Declipsonator** [comment]
> im going to try to make this. itll prob take a few days because im kinda bad.
> 
> if you arent concerned about legitmacy you can spawn withers about 30% faster by skipping the support cobble

Did you ever finish this?

**Comment by Declipsonator** [comment]
Also, I don't think you can place blocks in withers, I'll try though.
@GildedS weren't you working on autowither as well?

**Comment by AstroOrbis** [comment]
Isn’t #516 identical, but with more features? I say we move over to there.

**Comment by RedCarlos26** [comment]
Yea. I saw close the other for this one.

**Comment by AstroOrbis** [comment]
#516 has more features, so it would be better to keep that one.

**Comment by RedCarlos26** [comment]
Exactly

**Comment by AstroOrbis** [comment]
you said close the other one and keep this one
