### ISSUE TITLE
more 1.116 sword/axe combat  pvp modules

### ISSUE THREAD

**Issue by JoshuaT1105** [MeteorDevelopment/meteor-client#4226]
### Describe the feature

add more modules for axe/sword pvp, like a bettter kill aura, or just automatep pvp. Maybe include baritone. Also add aim assist. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Will probably never happen
