### ISSUE TITLE
[Suggestion] Add option to quickly switch fonts ingame

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#423]
**Describe the feature**
1. Let the client make a `fonts` subfolder inside the `meteor-client` folder
2. Add a setting in the GUI tab to switch fonts through `.ttf` files

Customisation is a big part of Meteor, this could be a nice addition 👍

**Screenshots**
![2021-04-06 20_30_36-Minecraft 1 16 5](https://user-images.githubusercontent.com/52252627/113760820-fc209300-9716-11eb-821f-2eefb9592287.png)
Possibly placed just under Themes for easy access

**Comment by RedCarlos26** [comment]
I like this idea!

**Comment by MineGame159** [comment]
Added in e9dd92071a436ec8beb109f9477368aa0345f0af
