### ISSUE TITLE
Infinity Miner's Baritone not being paused when Auto-Eat attempts to eat

### ISSUE THREAD

**Issue by Ogmur** [MeteorDevelopment/meteor-client#4237]
### Describe the bug

Infinity Miner's Baritone not being paused when Auto-Eat attempts to eat with baritone and auto pause baritone enabled under auto eat

### Steps to reproduce

to replicate this issue, turn on auto eat with hunger set to any amount. then turn on infinity miner in the nether (this is just how it happened to me, can be any ore in any dimension) targeting ancient debris block, targeting ancient debris item, with repair block nether quartz. then let it mine until you have hunger below auto eat threshold. it will just stand there trying to eat for eternity 

### Meteor Version

meteor client v0.5.5 build #1978

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by moritz-t-w** [comment]
#4203 please check other issues before reporting.

**Comment by HanhIsMe** [comment]
how do i get infinity miner for meteor client?

**Comment by moritz-t-w** [comment]
The module is called `InfinityMiner`.
https://meteorclient.com/faq/#how-do-i-open-the-gui?
