### ISSUE TITLE
Crashes on Complex-Gaming

### ISSUE THREAD

**Issue by LOLYAYDEV** [MeteorDevelopment/meteor-client#4238]
### Steps to reproduce

I started minecraft and only on Complex-gaming the game crashes even after i diable every module

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/tuo5XdZ

### Meteor Version

meteor-client-0.5.4.jar

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
appears to be some sort of compatibility issue between meteor and essential mod

**Comment by Big-Iron-Cheems** [comment]
Essential Mod is closed source and extremely invasive, it'd be hard to fix this issue.
Also, the server you're trying to join definitely doesn't support mods like Meteor.

I personally won't provide support for this.

**Comment by LOLYAYDEV** [comment]
removed essential and it works now
