### ISSUE TITLE
[Bug] Sneaking while in inventory with gui move doesn't slow you down

### ISSUE THREAD

**Issue by NathanKassab** [MeteorDevelopment/meteor-client#424]
**Describe the bug**
Title

**To Reproduce**
1. enable gui move and open inventory
2. sneak
3. Walk foward
4. Is not slowed down
5. exit inventory
6. sneak
7. slowed down

**Expected behavior**
slows down player

**Screenshots**
NaN

**Additional context**
Meteor version 0.4.2

**Comment by RedCarlos26** [comment]
So you have no slow enabled?

**Comment by NathanKassab** [comment]
No, I have sprint on though. Would that change anything?

**Comment by RedCarlos26** [comment]
No. This is probably an anti-cheat issue. Did you try in a single-player world?

**Comment by MineGame159** [comment]
Do you have sneak enabled in GUI Move settings?

**Comment by NathanKassab** [comment]
> No. This is probably an anti-cheat issue. Did you try in a single-player world?

Yes, both in single-player and in multiplayer

> Do you have sneak enabled in GUI Move settings?

DIdn't check, am using default settings

**Comment by MineGame159** [comment]
Fixed in d70ca1172f002aaf5c2ff6753c1c6ff5e663863f
