### ISSUE TITLE
Meteor Client crashes when using Baritone with Mouse Wheelie installed

### ISSUE THREAD

**Issue by imadraude** [MeteorDevelopment/meteor-client#4244]
### Describe the bug

Launching Baritone commands like #mine causes the Minecraft client to freeze and crash when Meteor Client and the Mouse Wheelie (v1.13.0 Fabric) mod are installed. Specifically, the game freezes when trying to execute Baritone mining commands.

### Steps to reproduce

1. Launch any world (online or offline)
2. Type a Baritone command like "#mine minecraft:oak_log" into chat
3. Game client will freeze

### Meteor Version

0.5.4-release

### Minecraft Version

MC 1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Looks like mouse wheelie isn't maintiained anymore.
