### ISSUE TITLE
auto 32k

### ISSUE THREAD

**Issue by gitchub09** [MeteorDevelopment/meteor-client#4248]
### Describe the feature

Please add auto 32k no other 1.20 client have auto 32k

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by headzz06** [comment]
because 32ks don't exist in modern versions of the game

**Comment by zoegaming9255** [comment]
hey i cant messgae in meteor client dc

**Comment by ManInMyVan** [comment]
> hey i cant 
> Message in meteor client dc

read the [FAQ](https://meteorclient.com/faq/)

**Comment by gitchub09** [comment]
idk what to do if u cant message in dc

**Comment by zoegaming9255** [comment]
> > hey i cant
> > Message in meteor client dc
> 
> read the [FAQ](https://meteorclient.com/faq/)

hey but in which java verson tlauncher i have 1.20.1 but it dosnot work i downloaded 0.5.4 meteor client

**Comment by zoegaming9255** [comment]
> did you install fabric api

yes

**Comment by zoegaming9255** [comment]
> did you install fabric api

i tried with all fabric verson

**Comment by zoegaming9255** [comment]
![Screenshot 2023-12-05 174042](https://github.com/MeteorDevelopment/meteor-client/assets/144536433/5bc76dba-81eb-485a-9e09-c5f8af95dcd9)
wth

**Comment by ManInMyVan** [comment]
> > > hey i cant
> > > Message in meteor client dc
> > 
> > read the [FAQ](https://meteorclient.com/faq/)
> 
> hey but in which java verson tlauncher i have 1.20.1 but it dosnt work i downloaded 0.5.4 meteor client but my friend have tlaundher and he can play
> 

1. TLauncher is spyware/malware
2. TLauncher (and every other cracked launcher) is not supported
3. TLauncher is piracy, which is illegal
4. Buy the game
5. Read the [FAQ](https://meteorclient.com/faq) before asking questions

**Comment by GreemDev** [comment]
> greendev first learn to write green 
> 
> 

says the fucking idiot asking for 32ks in 2023 almost 2024 in modern minecraft

**Comment by D-a-r-n-o-l-d** [comment]
![2024-08-13_13 29 38](https://github.com/user-attachments/assets/1d4ac831-a905-4a58-bd9e-e9efe49e7ed0)

**Comment by Wide-Cat** [comment]
no servers have 32k pvp anymore, and if you somehow find one there are better clients for it
