### ISSUE TITLE
Meteor crash when i open singleplayer game or join a multiplayer server

### ISSUE THREAD

**Issue by phvkuhkk** [MeteorDevelopment/meteor-client#4251]
### Steps to reproduce

1. I start up minecraft 
2. click either multiplayer or singleplayer 
3. join a single player world or a multiplayer server
4. game crashes and puts me back into launcher with an exit code

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

i only get exit code and no crash report

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
We can't do anything without a crash report

**Comment by Wide-Cat** [comment]
Look in your .minecraft/crash-reports or .minecraft/logs folders to find one
