### ISSUE TITLE
idk how to uninstall[Suggestion] 

### ISSUE THREAD

**Issue by monkleton582** [MeteorDevelopment/meteor-client#4253]
### Describe the feature

how do i uninstall meteorrr

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Remove it from your mods folder.

**Comment by GreemDev** [comment]
it's not that hard dude. delete the file YOU downloaded. this is literally one of the most simple things about computers.
