### ISSUE TITLE
where do i find my mod folder[Suggestion] 

### ISSUE THREAD

**Issue by monkleton582** [MeteorDevelopment/meteor-client#4254]
### Describe the feature

where do i locate my mods folder

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
.minecraft/mods

**Comment by MineGame159** [comment]
Stop opening issues for support questions or I will ban you from here.
