### ISSUE TITLE
update to 1.20.3

### ISSUE THREAD

**Issue by Ebanytiy** [MeteorDevelopment/meteor-client#4255]
### Describe the feature

update to 1.20.3

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
The [PR](https://github.com/MeteorDevelopment/meteor-client/pull/4249) is already open, you can go and built it yourself to use it while it's still not merged.

**Comment by ModxVoldHunter** [comment]
> ### Describe the feature
> update to 1.20.3
> 
> ### Before submitting a suggestion
> * [x]  This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)
> * [x]  This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

you build the latest build by downloading from the Fork and using "./gradlew build" in an IDE or using cmd and doing just "gradlew build"

Win: .\meteor-client-1.20.3-update\meteor-client-1.20.3-update\build\libs for the builded jar after running command and build runs correctly
