### ISSUE TITLE
Latest Meteor Client Dev version and Latest Sodium Version crash

### ISSUE THREAD

**Issue by NakyoykaN** [MeteorDevelopment/meteor-client#4256]
### Steps to reproduce

1.) The Control
Set up a new Minecraft 1.20.2 instance with Fabric Loader 15 + LWJGL 3 3.3.2
Install Fabric API 0.91.1+1.20.2 and latest Meteor Client Dev 0.5.5-1980
Good to go.  Game launches and a single player world can load.

2.) Install Sodium 0.5.3 => Game launches and a single player world can load (Reaches 100% and game loads)
Now remove it for step 3.

3.) Install Sodium 0.5.4 => Game launches but it crashes on single player world load.  (Reaches 100% and game crashes)

Single player worlds and server is the same result - crashes at 100%.

Latest change log for Sodium 0.5.4:
https://modrinth.com/mod/sodium/version/mc1.20.2-0.5.4

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

Available on request

### Meteor Version

Meteor Client 0.5.5-1980

### Minecraft Version

1.20.2

### Operating System

Linux

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Known issue, the fix is going to be merged alongside the 1.20.4 update when mojang releases it. Use sodium 0.5.3 for the time being
