### ISSUE TITLE
build #1980 crash

### ISSUE THREAD

**Issue by Blalala6868** [MeteorDevelopment/meteor-client#4257]
### Steps to reproduce

The game crashed when I entered a local save, but I didn't test entering multiplayer.
Here are the other mods I added for the client
![image](https://github.com/MeteorDevelopment/meteor-client/assets/85837864/41eb4604-c041-4c73-994b-fbd5b8eb5e1c)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/F5B7krL

### Meteor Version

meteor-client-0.5.5-1980

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Known issue, use sodium 0.5.3 until we update and fix it
