### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by irock2190** [MeteorDevelopment/meteor-client#426]
list of things to add:
W-tap
An option under KA to keep momentum after attacking

Target strafe
Glide
Anti-wobble 
Range Circle
Long Jump
Opacity changer for water
Anti-ghostblock
Lightning locator
AutoBlock
No slime jump
True sight
disabler(ping spoof)
Have inventoryManager (all items selected by default)
AntiCheat detector
Flag detector
Hacker Detector
Option for NoFall to Send teleport packets to previous location
FreecamTP

**Comment by seasnail8169** [comment]
1. This is a 1.16.5 anarchy utility mod, not a 1.8 "cheat".
2. Please, make separate issues for separate suggestions, it's much much easier for us to manage them this way.
