### ISSUE TITLE
Crash with Fabulously Optimized

### ISSUE THREAD

**Issue by Bedmor** [MeteorDevelopment/meteor-client#4261]
### Steps to reproduce

1.Open Minecraft
2.Crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/692Kard

### Meteor Version

0.5.5-1980

### Minecraft Version

MC 1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Remove more chat history, meteor already has a setting for that in the better chat module
