### ISSUE TITLE
Help my game crashes for no reason

### ISSUE THREAD

**Issue by ahnafsha** [MeteorDevelopment/meteor-client#4262]
### Steps to reproduce

1. i put the 1.20.2 meteor client in the 1.20.2 fabric loaders mod folder. ps : there was no mods in it.
2. Then i start minecraft it just ccrashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/1NG6g9G

### Meteor Version

meteor 1.20.2

### Minecraft Version

mc 1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
It's because you're using a cracked launcher. If you use a normal launcher it should work fine
