### ISSUE TITLE
autoclutch

### ISSUE THREAD

**Issue by Frazzle21** [MeteorDevelopment/meteor-client#4269]
### Describe the feature

whenever you fall place a water bucket (if you have one) below you, cobweb, haybale and other items.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Already a feature in no fall
