### ISSUE TITLE
Freecam Prevents Scrolling

### ISSUE THREAD

**Issue by bruh1273** [MeteorDevelopment/meteor-client#4272]
### Describe the bug

The module Freecam has a bug where if it's active, and yo have scroll speed enabled, you will NOT be able to scroll in any screens, especially in screens that require a scroll bar.

### Steps to reproduce

1. Enabled Freecam with scroll speed enabled.
2. Went to any screen with a scroll wheel (Statistics Screen Has A Scroll Bar)
3. Try to scroll down into the screen

Expected Result:
 Scrolling works in game, but when you have any screen open that is not null (in game screen) the freecam scrolling feature allows you to scroll in GUI's
### Meteor Version

0.5.6-1983

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DAMcraft** [comment]
Isn't this intended behavior? Check your settings, do you have scroll to speed adjust (or whatever it was called) on?

**Comment by bruh1273** [comment]
> Isn't this intended behavior? Check your settings, do you have scroll to speed adjust (or whatever it was called) on?

Yes, it indeed IS intended behavior HOWEVER, scrolling should still work in GUIs
