### ISSUE TITLE
Suggestion. 

### ISSUE THREAD

**Issue by Balls199** [MeteorDevelopment/meteor-client#4275]
### Describe the feature

A feature something like the "goto" command. This command is to location blocks or entities at far distances. For example an enderchest at 1 million blocks away or a dragon egg at 500k. 
And when turned on, it will show the exact coords of the respective blocks or entity blocks. It can have a list of coords something like "stash finder" so if I select "enderchest" it can pop up something like this 

"2837,76,3627"
"862,100,9187" 
and so on

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
It is not possible to locate blocks outside your render distance. 
That's why Baritone's goto command starts walking in a random direction when the target is not rendered nearby.
