### ISSUE TITLE
Meteor crashes when sodium installed

### ISSUE THREAD

**Issue by ehamawy** [MeteorDevelopment/meteor-client#4276]
### Steps to reproduce

1. Install meteor-client-0.5.5
2. Install sodium-fabric-mc1.20.2-0.5.5
3. Launch game
4. Crashes on world load
[Log here](https://mclo.gs/djeeYOi)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/djeeYOi

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by soup-s-kotom** [comment]
same problem

**Comment by Wide-Cat** [comment]
Known issue, it's been fixed as of the latest dev builds

**Comment by drakfreddy** [comment]
> Known issue, it's been fixed as of the latest dev builds

The newest dev builds are for 1.20.4 , which most of the mods I use are for 1.20.2 is there a meteor 1.20.2 version that fixes this?
