### ISSUE TITLE
[Bug] kick class_8911 NBT data

### ISSUE THREAD

**Issue by Gllody** [MeteorDevelopment/meteor-client#4279]
### Describe the bug

I'm just playing and suddenly this happened

![Zrzut ekranu 2023-12-16 015838](https://github.com/MeteorDevelopment/meteor-client/assets/97754667/189758d7-f9b1-4aff-b78e-8dbf960ba019)

### Steps to reproduce

I'm just playing and suddenly it kicks me out off the server.

### Meteor Version

0.5.6-1985

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
If you can trigger this reliably, ease attach the full [log](https://meteorclient.com/faq/getting-log) generated by Minecraft.

**Comment by Big-Iron-Cheems** [comment]
Closing as logs are missing. Repoen if they're provided.

**Comment by routhing** [comment]
可能是carpet模组高版本不兼容服务端低版本
