### ISSUE TITLE
[Suggestion] Auto jumpbug (nofall mode)

### ISSUE THREAD

**Issue by hellidox** [MeteorDevelopment/meteor-client#4281]
### Describe the feature

https://www.youtube.com/watch?v=3EepUFynH7w
does the fall damage cancel glitch if possible with your current speed and height above the ground

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
I and at least one other have poked around with this before, and we couldn't reproduce it consistently. If you can point to an example of where another mod has automated it, then we could definitely do so, but until then this is unlikely to happen.
