### ISSUE TITLE
[Suggestion] Allow AutoEat to use food from your offhand

### ISSUE THREAD

**Issue by Set2Minecraft** [MeteorDevelopment/meteor-client#429]

**Comment by seasnail8169** [comment]
Great suggestion! Thanks!!

**Comment by Set2Minecraft** [comment]
Auto Eat not able to eat when food is in off-Hand

-Great Client, very smartly designed

**Comment by seasnail8169** [comment]
Did you mean to report this as a bug?

**Comment by Set2Minecraft** [comment]
Ahhhhh yes sorry! (read the discord text too small)
