### ISSUE TITLE
Baritone setting maxFallHeightNoWater constantly set to 159159 on loading a game

### ISSUE THREAD

**Issue by DogsRNice** [MeteorDevelopment/meteor-client#4290]
### Describe the bug

The setting in in the baritone gui tab is consistently set to 159159 when a new game is started (loading a world or joining a server). pressing the reset button sets it to 3 and any other changes will persist for that session.

This causes baritone to leap from a cliff no matter what the height is without using a water bucket to stop itself.

### Steps to reproduce

1. Change the maxFallHeightNoWater baritone setting in the gui
2. Load a new game

### Meteor Version

Meteor 0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Send a screenshot of your active modules

**Comment by DogsRNice** [comment]
> Send a screenshot of your active modules

So I was about to when i noticed i had no fall turned on, which seems to be what sets the value. I must have forgotten to turn it off after checking if it worked on the server i was playing. It might be useful to put a warning about this on the tooltip though.
