### ISSUE TITLE
minecraft with mods and meteor client crashed

### ISSUE THREAD

**Issue by Yuu-Sakuma** [MeteorDevelopment/meteor-client#4293]
### Steps to reproduce

![ppoop](https://github.com/MeteorDevelopment/meteor-client/assets/88208983/08a8c50b-adcc-45f4-87eb-6caaa2172ea3)
here is my collection of mods on which everything works without a meteor, if you add it there everything will crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Fl5vQq8

### Meteor Version

Meteor 0.5.5

### Minecraft Version

MC 1.20.2

### Operating System

Windows

### Before submitting a crash report

- [x] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
meteor doesnt work on tlauncher, you will have to use a different one

**Comment by Big-Iron-Cheems** [comment]
Cracked launchers issue. TLauncher modified the authentication library, and consistently fails with the features introduced by Meteor.


We do not support cracked users, so consider buying the game and use one of the supported launchers mentioned in our FAQ.
