### ISSUE TITLE
Random cracked account name

### ISSUE THREAD

**Issue by Tarodictrl** [MeteorDevelopment/meteor-client#4294]
### Describe the feature

Сould you add a `Random` button in the `Accounts -> Cracked` section which would substitute a random account name.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RealmKebab** [comment]
why would this be useful
