### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by rastley1** [MeteorDevelopment/meteor-client#4295]
### Describe the feature

Auto repair: automagically splashes xp bottles on the ground below you if your health is above a certain value, you are not in a fight currently, your durability is below a threshold and has mending, exct. Could be useful in pvp situations and might save some inventory space

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Already exists
