### ISSUE TITLE
i cant get older versions of meteor 

### ISSUE THREAD

**Issue by mtprfan** [MeteorDevelopment/meteor-client#4296]
### Describe the bug

its not letting me install 1.19.2 link from dc, its downloading 
![Screenshot 2023-12-24 

> `[]([](102034](https://github.com/MeteorDevelopment/meteor-client/assets/154753275/9060a605-a575-4f34-8996-dffd044f26f)))))` newest version

### Steps to reproduce

You should put all the links for all versions and also can u give me 1.19.2 meteor link??
![Screenshot 2023-12-24 102034](https://github.com/MeteorDevelopment/meteor-client/assets/154753275/18541105-e573-4396-ba8f-8c717744a184)

### Meteor Version

Meteor 0.53

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by mtprfan** [comment]
tutrial for multiconnect pls

**Comment by Wide-Cat** [comment]
Use ViaFabricPlus

**Comment by mtprfan** [comment]
im on 1.19.2

**Comment by mtprfan** [comment]
not 1.19.3
