### ISSUE TITLE
1.1.9.2 viafabricplus link?

### ISSUE THREAD

**Issue by mtprfan** [MeteorDevelopment/meteor-client#4297]
### Describe the bug

i need da link and turtioal

### Steps to reproduce

i need link

### Meteor Version

Meteor 1.19.2

### Minecraft Version

1.19.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Please read the FAQ on our website.
You're supposed to use the latest version of Meteor, with the latest version of ViaFabricPlus to be able to join old servers.
