### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by EpikCatto6900** [MeteorDevelopment/meteor-client#4298]
### Steps to reproduce

1. I launched minecraft 2. Minecraft didnt launch 3. After 3 secs my game crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/7VVVbK3

### Meteor Version

1.20.2-0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [x] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Meteor doesn't work on tlauncher. Use another one

**Comment by EpikCatto6900** [comment]
its not tlauncher its Legacy Launcher, legacy launcher is tlauncher but its safe and with more functionality and with different style and etc

**Comment by EpikCatto6900** [comment]
im using that launcher https://llaun.ch/en

**Comment by herloc123** [comment]
> im using that launcher https://llaun.ch/en

turn it off. this solved the problem for me.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/155285631/5d46749f-499e-4b60-b81f-07d511503ad7)
