### ISSUE TITLE
Wurst-like TabGui

### ISSUE THREAD

**Issue by solarite1797** [MeteorDevelopment/meteor-client#4299]
### Describe the feature

It would be good to have a Wurst-like menu to enable hacks like this: 
![image](https://github.com/MeteorDevelopment/meteor-client/assets/118111762/58cd77fe-6f0c-4767-bb6f-f109abab0432)
Would be useful, for people migrating from wurst.

Don't know what else to add.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
meteor's ui is not that hard to understand

**Comment by Wide-Cat** [comment]
Not gonna happen

**Comment by RealmKebab** [comment]
wurst is literally worst than meteor :skull:
