### ISSUE TITLE
Team Checker

### ISSUE THREAD

**Issue by mariokart617** [MeteorDevelopment/meteor-client#4306]
### Describe the feature

Pls Add Teamchecker(It is divided into Hoplite mode and Bedwars mode, and Hoplite Mode recognizes the glow effect, and Bedwars recognizes people wearing the same armor as you)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We don't make minigame server cheats, get good.
