### ISSUE TITLE
CTD with sodium

### ISSUE THREAD

**Issue by logitek184** [MeteorDevelopment/meteor-client#4308]
### Steps to reproduce

1.launch
2.join world (single/multiplayer)
3.ctd

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

crash report: https://mclo.gs/uCEWPW0
Log: https://mclo.gs/ZkgZXBu

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Is that the full log?
Anyways, since you're on 1.20.2, I assume you're using Sodium.
If that's the case, downgrade it to version 0.5.3; close this issue if that solves your crash.

**Comment by logitek184** [comment]
oh sorry forgot to add the log i'll try that and see if it works

**Comment by logitek184** [comment]
edited with log included

**Comment by Big-Iron-Cheems** [comment]
Yeah, classic. Downgrade sodium to 0.5.3 and it'll work.

**Comment by Myuui** [comment]
> Yeah, classic. Downgrade sodium to 0.5.3 and it'll work.

Helped me, thanks.

**Comment by Big-Iron-Cheems** [comment]
Closing as this is the solution anyways.
