### ISSUE TITLE
Chat Feedback of Speed Crash When Re-entering a Server

### ISSUE THREAD

**Issue by Phoupraw** [MeteorDevelopment/meteor-client#4309]
### Steps to reproduce

1. Enter a server.
2. Set the bind for Speed.
3. Send some messeges and toggle Speed for several times.
4. Quit the server.
5. Re-enter the server.
6. Press the bind of Speed.
7. Crash.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/IKMF1xC

### Meteor Version

meteor 0.5.4

### Minecraft Version

MC 1.20.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Phoupraw** [comment]
Maybe it's caused by OMMC's keep chat history or meteor's Better Chat - Keep History.

**Comment by Wide-Cat** [comment]
Open this issue again if you can reproduce it on the latest dev build

**Comment by Phoupraw** [comment]
Where can I download the latest version for MC 1.20.1? The one in the homepage is for 1.20.4.

**Comment by GreemDev** [comment]
There is no latest version for 1.20.1. The latest version is for the latest MC version. If you can't be bothered to reproduce the issue on that version then you're out of luck
