### ISSUE TITLE
i want 1.19 virsion of meteor cline i want infiminer

### ISSUE THREAD

**Issue by starswar13** [MeteorDevelopment/meteor-client#4310]
### Describe the feature

i want 1.19 version of hacks i am unable to find in 1.120 the is no infiminner or autominer what to do bro ):

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
ViaFabricPlus and Baritone
