### ISSUE TITLE
[Bug] Highway builder issue

### ISSUE THREAD

**Issue by Torrentel** [MeteorDevelopment/meteor-client#4314]
### Describe the bug

A feature that makes the module not break your pickaxe is constantly breaking them. ive lost hours of work because of this dumb issue. Please fix it.

### Steps to reproduce

1. turn on "dont break pickaxe"
2. turn on highway builder until the it should stop and it will break the pickaxe

### Meteor Version

meteor 0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
there is literally an option in the module to avoid breaking tools
