### ISSUE TITLE
[Suggestion] Built in module creator

### ISSUE THREAD

**Issue by MissingReports** [MeteorDevelopment/meteor-client#4315]
### Describe the feature

So basically there will be an ingame module creator, you can use a custom coding language to code what it does or use java (its up to meteor to use a custom language or java)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Definitely not something we want to spend dev time on.
If you want to make a module, develop your own addon, or have your own fork of Meteor with all the changes you want.

**Comment by MissingReports** [comment]
it could be a small module that doesnt need a whole addon such as pay all players, msg all players, a dupe module on certain servers, delay a packet if u really want to, stuff like that that's not that big for an addon
