### ISSUE TITLE
Memory leak occurred while entering local saves

### ISSUE THREAD

**Issue by Blalala6868** [MeteorDevelopment/meteor-client#4318]
### Steps to reproduce

1. create and enter a local save with meteor dev build1992
2. replace meteor dev build1992 to dev build1997
3. enter the save again and the game crashed

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/7KPUSl3 (latest.log) https://mclo.gs/aSWupkL (hs_err_pid8756.log)

### Meteor Version

meteor v0.5.6 1997

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
not a memory leak, you’re allocating too much memory for your system

**Comment by Blalala6868** [comment]
> not a memory leak, you’re allocating too much memory for your system

Wait a minute, the cause of the crash is that I allocating too much memory?

**Comment by RacoonDog** [comment]
> > not a memory leak, you’re allocating too much memory for your system
> 
> Wait a minute, the cause of the crash is that I allocating too much memory for minecraft?

Unless the leak happens in native memory, it'd show up as an `OutOfMemoryError` or a `StackOverflowError`. This crash is caused by the jvm failing to find native memory to map the heap onto, in other words the size of the heap is too high for the amount of memory your system has.
