### ISSUE TITLE
Crashiny meteor in vulkan mod

### ISSUE THREAD

**Issue by ShivaXYZ22** [MeteorDevelopment/meteor-client#4319]
### Steps to reproduce

My meteor crash is happening when I started with vulkan mod in version 1.20.2. 
[crash-2024-01-10_13.30.13-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/13884803/crash-2024-01-10_13.30.13-client.txt)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

Sorry i dont under stand so

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by ModxVoldHunter** [comment]
Vulkan Renderer isn't compatible with meteor because no compatiblity was made for it.

**Comment by MineGame159** [comment]
#3567
