### ISSUE TITLE
Suggestion of a control for the nuker/freecam

### ISSUE THREAD

**Issue by lory54** [MeteorDevelopment/meteor-client#4320]
### Describe the feature

i usually play on a prison server and i found out that some blocks can be instamined from infinity distance and trough other blocks with nuker or freecam. for some reason, the first time the nuker followed my movements with the freecam and that was op af, but suddendly, after a restart of the server the nuker works only around the player and not in spectator mod or freecam, i tried others clients and they work with both nuker and freecam. please add a control that makes the nuker to follow the movements in client-side

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Any interactions done in freecam outside of your physical player's max interact distance don't affect the world.
Also: we don't develop features for minigame servers etc, Meteor is meant for anarchy servers.
