### ISSUE TITLE
Have .binds so we can see binds

### ISSUE THREAD

**Issue by vkiitsune** [MeteorDevelopment/meteor-client#433]
**Describe the feature**
A clear and concise description of what feature/change is.
.binds will be a feature so when you do, .binds, you can see every bind you have, its good if you forgot or if you downloaded some randoms config.
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.
No screenshots sorry.
**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
Added

**Comment by vkiitsune** [comment]
Thanks cutie.
