### ISSUE TITLE
Crash when joining world

### ISSUE THREAD

**Issue by zhubenjamin** [MeteorDevelopment/meteor-client#4330]
### Steps to reproduce

1. Boot up minecraft with sodium, meteor client, and fabric api
2. join a singleplayer world or server
3. watch as your minecraft crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/G1XiKj1

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [x] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Downgrade Sodium to 0.9.3 or update all your mods to 1.20.4
