### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Epiccoolman2001** [MeteorDevelopment/meteor-client#4333]
### Describe the bug

im having issues with notebot basically i just wanna play a song and i do all the appropiate steps and when i press play instead of the notes playing they dissapear 

### Steps to reproduce

i just used the notebote as intended and it isnt working

### Meteor Version

0.5.6 dev build

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
send a video of what you mean

**Comment by Epiccoolman2001** [comment]
ok

https://github.com/MeteorDevelopment/meteor-client/assets/121214745/9841dace-febc-4e8d-9445-b5b15acbc9ea

**Comment by Wide-Cat** [comment]
The .gamemode command is clientside only, even if you do .gamemode survival you're still in creative mode really lmao

**Comment by Epiccoolman2001** [comment]
im stupid as hell 😭 😭
