### ISSUE TITLE
[Suggestion] meteor lite

### ISSUE THREAD

**Issue by eyescave** [MeteorDevelopment/meteor-client#4335]
### Describe the feature

meteor lite would be a smaller version of meteor client to make it avalable on feather client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
bro just use one or the other its not that hard of a concept
