### ISSUE TITLE
Notebot 

### ISSUE THREAD

**Issue by ZingMCPC** [MeteorDevelopment/meteor-client#4336]
### Describe the feature

How to dowload songs in notebot It is too difficult

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
you find a song file and put it in your meteor folder and use it.
if this is too difficult for you, I would suggest doing something else; because if you can't download files from the internet and put them in a folder you shouldn't be trusted with a computer
