### ISSUE TITLE
Meteor crashed upon initializing 

### ISSUE THREAD

**Issue by supermankeys52** [MeteorDevelopment/meteor-client#4338]
### Steps to reproduce

I Removed the Fabric Api and i updated fabric yet no result

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/lQVnrea

### Meteor Version

Meteor 1.20.4

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Go to the .minecraft/meteor-client folder and delete modules.nbt

**Comment by Fr0o0Zzzy** [comment]
Same. Is there soluton 4 this? I tried with several versions (1.20.3, 1.20.2) and only 1.20.1 worked 4 me

**Comment by Fr0o0Zzzy** [comment]
Ok I fixed it. If ya using legacy launcher try switching to another, I tried it with Tlauncher and its worked :/ dunno why

**Comment by Wide-Cat** [comment]
should be fixed 30437a09b9a0f89f6fc5421d4faa3b6db778dc02
