### ISSUE TITLE
New Easy Villager Trading Module

### ISSUE THREAD

**Issue by Doviiiii** [MeteorDevelopment/meteor-client#4339]
### Describe the feature

Im tired of replacing over and over again the lectern for the librarian villager to obtain the enchanted book i want, so i came up with the idea for a new module that does excactly this (I think many people would like this module because not everyone uses meteor on anarchy servers, personally i use it for normal survival for fun, so it would be a great addition). You input the enchanted book (with the level) that you want to obtain, and a bot will make this steps:
---------------------------------------------
1. Check if the player input is alright
---------------------------------------------
2. Check if a villager is near
---------------------------------------------
3. Put down the lectern
---------------------------------------------
4. Check if the villager has the enchanted book with the level wanted. If the librarian has the enchanted book wanted in the input, if its possible to make an option for enabling the bot to take emeralds and books from the player inventory and lock the enchant.
---------------------------------------------

THIS IS THE END OF THE CYCLE.

IMPORTANT: If the librarian doesn't has the enchanted book with the level wanted, replace the lectern over and over again until it has the book wanted.

I came up with the idea for the name of the module like "Villager Aura", "Auto Villager" or "Easier Villager Trading"

I know its not an easy module to do, but it would definetly it would be worth it.

Thanks for reading<3

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by pixo2000** [comment]
Maybe you can also add a function for trading where you add items to a list to trade and when you come near a villger with the matching job, it opens the gui and executes the trade. Its realy anoying to trade string with the villagers

**Comment by Big-Iron-Cheems** [comment]
This already exists as its own [addon](https://github.com/maxsupermanhd/meteor-villager-roller), it works pretty well, it just doesn't lock the trade, but you get a notification with sound when the villager you want is rolled.

As for automatic trading, that's not included in said addon.

**Comment by Doviiiii** [comment]
> Maybe you can also add a function for trading where you add items to a list to trade and when you come near a villger with the matching job, it opens the gui and executes the trade. Its realy anoying to trade string with the villagers

It would be a nice addition too<3

**Comment by Doviiiii** [comment]
> This already exists as its own [addon](https://github.com/maxsupermanhd/meteor-villager-roller), it works pretty well, it just doesn't lock the trade, but you get a notification with sound when the villager you want is rolled.
> 
> As for automatic trading, that's not included in said addon.

Tysm, i didn't knew about that one, i will check it out if it's compatible with Fabric on newer versions<3

**Comment by Doviiiii** [comment]
> This already exists as its own [addon](https://github.com/maxsupermanhd/meteor-villager-roller), it works pretty well, it just doesn't lock the trade, but you get a notification with sound when the villager you want is rolled.
> 
> As for automatic trading, that's not included in said addon.

Also i have a question, i already installed it and it leads me to a folder, i drop it on .minecraft? or on a special meteor client folder¿
