### ISSUE TITLE
[SUGGESTION] arrow dodge

### ISSUE THREAD

**Issue by kurshy1** [MeteorDevelopment/meteor-client#434]
**Describe the feature**
A clear and concise description of what feature/change is.
The feature looks for arrows being shot at you and dodges out of the way. There could be an option to not 'dodge' if a shield is up.
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by seasnail8169** [comment]
This already exists in meteor.
