### ISSUE TITLE
Crashed 0.5.5 1.20.2

### ISSUE THREAD

**Issue by daniil2327** [MeteorDevelopment/meteor-client#4341]
### Steps to reproduce

I run Minecraft with Meteor, but it crashed
I run Minecraft with CRACKED launcher
PLS HELP

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/YzyvuQE

### Meteor Version

Meteor 0.5.5

### Minecraft Version

MC 1.20.2

### Operating System

Windows

### Before submitting a crash report

- [x] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Its crashing because youre using a cracked launcher. Try using another launcher or buying the game.
