### ISSUE TITLE
meteor not opening

### ISSUE THREAD

**Issue by somerandomaccountpiss** [MeteorDevelopment/meteor-client#4342]
### Describe the bug

so when i tried to ran meteor on tlauncher. it did this crash
![Скриншот 18-01-2024 201057](https://github.com/MeteorDevelopment/meteor-client/assets/150542575/f0837e47-d173-4641-85bf-80426b2e86a5)
and i cant do anything about it

### Steps to reproduce

1: so basically i loaded tlauncher. then i inserted the 0.5.5 version into the mods and choose fabric 1.20.2
2: then it gave me this error. i tried other versions like forge but still didnt work

### Meteor Version

Release 0.5.5 [1.20.2]

### Minecraft Version

Fabric 1.20.2 and i also tried Forge 1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
The log is quite clear, you need to update the [Fabric Loader](https://fabricmc.net/use/installer/).

**Comment by somerandomaccountpiss** [comment]
k ill try

**Comment by somerandomaccountpiss** [comment]
> The log is quite clear, you need to update the [Fabric Loader](https://fabricmc.net/use/installer/).

does the same thing 
![hbfd](https://github.com/MeteorDevelopment/meteor-client/assets/150542575/b82837a9-06d8-425b-99de-0e2562df79d2)

**Comment by Wide-Cat** [comment]
Meteor doesn't work on tlauncher

**Comment by somerandomaccountpiss** [comment]
> Meteor doesn't work on tlauncher

ok so i did some research and some things and it works now so nope

**Comment by Wide-Cat** [comment]
Sure, don't really care one way or another

**Comment by somerandomaccountpiss** [comment]
> Sure, don't really care one way or another

how to kick someone out of a issue github chat oops thought this is google

**Comment by GreemDev** [comment]
shut the fuck up minecraft pirate, you're so fucking poor you can't afford to pay for a $20 game and then cry when shit doesnt work

**Comment by Paddyk45** [comment]
Ever heard of something called "reading the error"?

**Comment by RealmKebab** [comment]
> shut the fuck up minecraft pirate, you're so fucking poor you can't afford to pay for a $20 game and then cry when shit doesnt work as a direct cause of you not having obtained the game properly.

(on one note, minecraft is now 30 dollars (i'm not supporting him))

**Comment by GreemDev** [comment]
> > shut the fuck up minecraft pirate, you're so fucking poor you can't afford to pay for a $20 game and then cry when shit doesnt work as a direct cause of you not having obtained the game properly.
> 
> (on one note, minecraft is now 30 dollars (i'm not supporting him))

last i checked it was 26 so that doesn't surprise me
