### ISSUE TITLE
Highway Builder will stop when it encounters glowstone

### ISSUE THREAD

**Issue by Krischan-Klug** [MeteorDevelopment/meteor-client#4344]
### Describe the bug

Highway Builder will stop when it encounters glowstone.  When encountering glowstone it prints in the chat "Failed to find suitable tool for mining."

This bug wasn't already reported (I have searched bug reports on GitHub). * is wrong but seems like it happen again

### Steps to reproduce

1. Use Highway Builder
2. Encounter Glowstone

### Meteor Version

0.5.6-1999

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
30437a09b9a0f89f6fc5421d4faa3b6db778dc02
