### ISSUE TITLE
Meteor Client Crashes while Vulkan Renderer is in the mods

### ISSUE THREAD

**Issue by ModxVoldHunter** [MeteorDevelopment/meteor-client#4345]
### Steps to reproduce

(used mods);
Fabric Loader 0.15.3
Fabric API 0.91.3
baritone-api-fabric-1.10.1-11-g3ed49fd4
VulkanMod_1.20.4-0.3.9
meteor-client-0.5.6-1992 (also does it with Latest Dev Build)

JAVA JDK Dev: Eclipse
JAVA JDK Version: 17.0.9

Click Launch

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/xBOhh86

### Meteor Version

meteor-client-0.5.6-1992

### Minecraft Version

Minecraft (Release) 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by ModxVoldHunter** [comment]
Note: I have OpenGL 3.2 for my PC so it shouldn't crash

**Comment by Big-Iron-Cheems** [comment]
Quite sure it's only natural that it crashes. 
VulkanMod rewrites most rendering methods (unsurprisinlgy, that's what using another rendering system does).
This in turn breaks our mixins into said methods, crashing.

**Comment by ModxVoldHunter** [comment]
ah, it is possible to make it compatible with Vulkan Renderer?

**Comment by GreemDev** [comment]
Possible? Yeah. Will it be done? Probably not, because you can more easily just... not use vulkanmod.

**Comment by ModxVoldHunter** [comment]
> Possible? Yeah. Will it be done? Probably not, because you can more easily just... not use vulkanmod.

Yeah but I would see an effect with sodium where the settings to kinda see blocks is 255 but no grass is shown when using sodium so guess what I was trying to do. Use Vulkan Renderer to solve that problem. I can't see full blocks but only exposed

**Comment by Big-Iron-Cheems** [comment]
We have no interest in developing compatibility with a mod for another rendering engine.
Especially considering the early stage it is in currently.

**Comment by ModxVoldHunter** [comment]
alright, issue closed,
