### ISSUE TITLE
[Suggestion] Bedrock version

### ISSUE THREAD

**Issue by TurtlemanLiam** [MeteorDevelopment/meteor-client#4348]
### Describe the feature

Although Meteor is specifically made for Java. There are very few bedrock clients, like there is Horion, which sends your data to somewhere in Germany or something like that.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
I'm afraid that isn't going to happen

**Comment by unknown324764** [comment]
is it a config?
