### ISSUE TITLE
The Games Closes when i try to start minecraft 

### ISSUE THREAD

**Issue by Tagiekk** [MeteorDevelopment/meteor-client#4349]
### Describe the bug

Today I tried to access 1.20.2 to play for a while, I have version 5.6.5 of fabulously optimized because I don't have a good PC

### Steps to reproduce

when I try to open the game it closes

### Meteor Version

Release 0.5.5 [1.20.2]

### Minecraft Version

Fabric 0.15.6/1.20.2 

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Send the crash report

**Comment by Tagiekk** [comment]
https://mclo.gs/LsMxGW1

**Comment by Wide-Cat** [comment]
remove more chat history, meteor has a setting for that in the better chat module
