### ISSUE TITLE
[Suggestion] auto cobble

### ISSUE THREAD

**Issue by big-boluptuous-boy** [MeteorDevelopment/meteor-client#4350]
### Describe the feature

whenever you have some crappy block like netherack cobblestone or normal stone it automatically forces it into the 9th inventory slot and it can be very annoying if you are doing something where it taking up space in the hotbar is annoying so you could make it togglable so it isn't forced into your hotbar

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Its a baritone setting do #allowInventory false
