### ISSUE TITLE
Meteor crashs with "Permanent Chat Logs"

### ISSUE THREAD

**Issue by Blalala6868** [MeteorDevelopment/meteor-client#4356]
### Steps to reproduce

launch meteor clicent with "Permanent Chat Logs" then it crashes.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/pYPd6Kc

### Meteor Version

meteor-client-0.5.6-1999

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
should be fixed by 35b82361cdb4a41e2195dee485c146d0fa4df428
