### ISSUE TITLE
Game crashes while intializing

### ISSUE THREAD

**Issue by ProfessionalPumpking** [MeteorDevelopment/meteor-client#4358]
### Steps to reproduce

1. Have fabric api, meteor and sodium installed
2. Game crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/bndqsJC

### Meteor Version

meteor client v0.5.6 build #1999

### Minecraft Version

Fabric 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Seeing as it crashes the authentication library, I assume you're using a cracked launcher. In that case, buy the game and use one of the supported launchers.
