### ISSUE TITLE
IRC Chat

### ISSUE THREAD

**Issue by NetworkCicada** [MeteorDevelopment/meteor-client#4359]
### Describe the feature

Would be nice to see such feature in Meteor let it be a public one or make it so u can create one with a pw and people can join it so u have like a universal minecraft chat from where ever u are to chat with yo homies + what would also be hella nice would be a chat encyption tool so yo messages are encrypted and only meteor player with a decrypt moduel can read it 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [ ] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
bro just use a discord server or a discord group

**Comment by Big-Iron-Cheems** [comment]
I honestly don't see the point of integrated chat systems like this one.
I'd expect the chatters to already know eachother from elsewhere, for example Discord or similar.
