### ISSUE TITLE
BetterTab

### ISSUE THREAD

**Issue by AlexMarshall123** [MeteorDevelopment/meteor-client#436]
BetterTab self colors display even when the module is off.

At least for me, it happens without having to do anything.

No out of place colors on the tab menu.

https://user-images.githubusercontent.com/62858980/113964337-4e39e500-97f9-11eb-9713-08ac8101f6c3.png

Using meteor client v0.4.2 build #696

**Comment by seasnail8169** [comment]
oops

**Comment by MineGame159** [comment]
Fixed
