### ISSUE TITLE
Performance mod affecting meteor client xray, unable to identify it.

### ISSUE THREAD

**Issue by Mope04** [MeteorDevelopment/meteor-client#4369]
### Describe the bug

Hello I've started to have issues since I've been using a performance modpack+Meteor and it has caused it to only show exposed ores are shown, I disabled iris and sodium and yet I still have this issue, this has happened in two modpacks, Remarkably Optimized, and fabulously optimized, both have caused Meteors xray features to bug out and only show exposed ores. So I'm wondering if there is a list of all mods that cause issues with Meteor? Or if there is any solution.
Screenshot for reference: https://prnt.sc/7dbwpmRaaIEN
Modpacks I used:

https://modrinth.com/modpack/remarkably/version/c9Hyth2o
https://modrinth.com/modpack/fabulously-optimized/version/5.6.5

### Steps to reproduce

1. Load into any world using a modpack+Meteor (fabulously optimized for example)
2. Turn on Xray.

### Meteor Version

Release 0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Probably the more culling mod, should be fixed if you go into it's settings and disable the block state culling option

**Comment by Mope04** [comment]
> Probably the more culling mod, should be fixed if you go into it's settings and disable the block state culling option

Thank you this worked!
