### ISSUE TITLE
I'm using the connector and I'm half successful.

### ISSUE THREAD

**Issue by 0hVanny1** [MeteorDevelopment/meteor-client#4370]
### Describe the feature

It has almost run successfully, but it shows that the execution of baritone failed.
failed to execute baritone.
Can you publish a version that cancels baritone, even if its related features are cancelled. Or is there a separate method for executing baritone? Thank you, buddy

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 0hVanny1** [comment]
Where should I get Meteor without Baritone

**Comment by Wide-Cat** [comment]
Meteor had come without baritone for a few months now

**Comment by 0hVanny1** [comment]
wow！  does the version without baritone include 1.20.1?

**Comment by Big-Iron-Cheems** [comment]
We don't provide older downloads as explained in [this](https://meteorclient.com/faq/old-versions/) guide, but the current supported versions on our website are both without Baritone.

**Comment by 0hVanny1** [comment]
I have actually read it in detail.So I learned that The only official place to get older Meteor releases is our GitHub repository,so
I came to GitHub to find the earlier versions but I can find it

**Comment by 0hVanny1** [comment]
Oh! I found it. My internet connection is not very good, which caused the interface I saw before to be very chaotic. Thx
