### ISSUE TITLE
[Suggestion] Add lunar client emblem beside your name for other lunar client users.

### ISSUE THREAD

**Issue by bewf** [MeteorDevelopment/meteor-client#4371]
### Describe the feature

I am not sure if this is possible, but I suggest there is an option where if you click it, other people see that you're on "lunar client" when you aren't. This could be helpful if someone asks what client you're using, you could just respond with lunar client.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by theotherhades** [comment]
Meteor is for anarchy servers not cheating on Hypixel play the game legit

**Comment by bewf** [comment]
I get that, and im wasn't planning on cheating on hypixel, just random smp's

**Comment by GreemDev** [comment]
> I get that, and im wasn't planning on cheating on hypixel, just random smp's

"I wasn't planning on cheating on hypixel, just cheating somewhere else" 
you are a sad individual.
