### ISSUE TITLE
[Suggestion] Will other languages ​​be supported in the future?

### ISSUE THREAD

**Issue by andy3559167** [MeteorDevelopment/meteor-client#4372]
### Describe the feature

Will other languages ​​be supported in the future?
For example Traditional Chinese
ESP will not be displayed when MC switches to Traditional Chinese

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by LLKawi** [comment]
when font rendering is fixed

**Comment by Blalala6868** [comment]
Temporarily patch it with [Caxton](https://gitlab.com/Kyarei/caxton/) first

**Comment by andy3559167** [comment]
> 先用[Caxton](https://gitlab.com/Kyarei/caxton/)臨時修補一下

not working

**Comment by hexadecimal233** [comment]
> > 先用[Caxton](https://gitlab.com/Kyarei/caxton/)臨時修補一下
> 
> not working <img alt="image" width="113" src="https://private-user-images.githubusercontent.com/92452845/307439356-0d136e31-4c0a-45ca-8efc-94f9385eaf19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTAxMTcsIm5iZiI6MTcwODc0OTgxNywicGF0aCI6Ii85MjQ1Mjg0NS8zMDc0MzkzNTYtMGQxMzZlMzEtNGMwYS00NWNhLThlZmMtOTRmOTM4NWVhZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA0NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YWQxYjYyM2QwMjVkMmM5Njk1ZjJlMDk4MjZmYzYyNDdkYTZjOTQ0Zjg3OTNkMmE4NDdmNGI0MDMzM2Q1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UxciWoWXxf-hblvNF9fHJA7kY1fPg-inpv7vtar-jr4">

Turn off custom fonts

**Comment by andy3559167** [comment]
> > > 先用[Caxton](https://gitlab.com/Kyarei/caxton/)臨時修補一下
> > 
> > 
> > not working <img alt="image" width="113" src="https://private-user-images.githubusercontent.com/92452845/307439356-0d136e31-4c0a-45ca-8efc-94f9385eaf19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTAxMTcsIm5iZiI6MTcwODc0OTgxNywicGF0aCI6Ii85MjQ1Mjg0NS8zMDc0MzkzNTYtMGQxMzZlMzEtNGMwYS00NWNhLThlZmMtOTRmOTM4NWVhZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA0NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YWQxYjYyM2QwMjVkMmM5Njk1ZjJlMDk4MjZmYzYyNDdkYTZjOTQ0Zjg3OTNkMmE4NDdmNGI0MDMzM2Q1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UxciWoWXxf-hblvNF9fHJA7kY1fPg-inpv7vtar-jr4">
> 
> Turn off custom fonts

where can turn off

**Comment by MineGame159** [comment]
#333
