### ISSUE TITLE
Auto Walk always goes to 0,0

### ISSUE THREAD

**Issue by gdcfxvnjvbncvb** [MeteorDevelopment/meteor-client#4373]
### Describe the bug

Hello,
When activating "Auto Walk", it always goes in the direction of 0,0 position, even if looking the other way.
When activated, "Auto Walk" should walk in the direction you were looking.

Using:
Minecraft 1.20.4
Latest fabric (fabric-installer-1.0.0 (0.15.6))
Lastest dev build (meteor-client-0.5.6-2005). Version meteor-client-0.5.6-1999 is also affected. I don't have older dev builds to test.
Tested with the latest baritone from the official github https://github.com/cabaletta/baritone/releases/tag/v1.10.2 (baritone-api-fabric-1.10.2)
Tested with the baritone version available on your website https://meteorclient.com/ (baritone-1.20.4-20240126.214906-1)

### Steps to reproduce

Activate Auto Walk, despite what direction you are looking at, it will always goes to 0,0.

### Meteor Version

meteor-client-0.5.6-2005

### Minecraft Version

Minecraft 1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by anhwaivo** [comment]
upvote

**Comment by MineGame159** [comment]
Fixed in babc0c409c2c08cd69ab4398e6e5343b6222a1cc
