### ISSUE TITLE
[Suggestion] 1.8.9 Version

### ISSUE THREAD

**Issue by Taduroz** [MeteorDevelopment/meteor-client#4374]
### Describe the feature

Create a 1.8 version for Meteor Client.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
lol
