### ISSUE TITLE
[Suggestion] Anti-Swear Module I Made For Meteor

### ISSUE THREAD

**Issue by Yaimsputnik5** [MeteorDevelopment/meteor-client#4375]
### Describe the feature

Hello Meteor Development Team,

This module is meticulously designed for users seeking a more respectful and cleaner chat environment in-game. It serves as a robust tool to eliminate swearing and vulgar language from the game chat, thereby fostering a more inclusive and friendly community.

Note: It's also good for streamers who use Meteor, especially on servers like 2b.

[AntiSwear.java.txt](https://github.com/MeteorDevelopment/meteor-client/files/14128940/AntiSwear.java.txt)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Something like this would probably serve better as an addon or just a standalone mod

**Comment by Yaimsputnik5** [comment]
> Something like this would probably serve better as an addon or just a standalone mod

I thought so too, but decided to make it a module since not everyone knows how to, or is too lazy to download addons, or even know where to find them.

**Comment by theotherhades** [comment]
Open a PR next time you have code to contribute, don't use Issues.
PS. This seems like something that could be integrated into Better Chat

**Comment by Big-Iron-Cheems** [comment]
I honestly agree that this would be better off as an addon of its own.
If you want it as a module, it should allow the user to specify a list of words or regex to filter the chat.
