### ISSUE TITLE
CW

### ISSUE THREAD

**Issue by Jamier1074** [MeteorDevelopment/meteor-client#4376]
### Describe the feature

Add some crystal pvp hacks like auto totem auto hit crystal auto anchor 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
:buh:
