### ISSUE TITLE
I keep crashing using crystal aura

### ISSUE THREAD

**Issue by Thesussycheese69420** [MeteorDevelopment/meteor-client#4378]
### Steps to reproduce

When someone comes to me using speed I keep crashing even before I place crystals to kill him/her and then it says Saving World... before crashing

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/7sutioD

### Meteor Version

Meteor 0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
Please post crash log and crystal aura settings

**Comment by Wide-Cat** [comment]
hopefully fixed by 4260f7c0af660a9aba81b787ef5e547393c235bd
