### ISSUE TITLE
Enderchest farming in Highway Builder

### ISSUE THREAD

**Issue by zhubenjamin** [MeteorDevelopment/meteor-client#4379]
### Describe the bug

When Highway Builder runs out of Obsidian, it should try to farm Enderchests to get more obsidian. Instead, it mines one enderchest, then just stops.

### Steps to reproduce

1. Turn on "Mine Ender Chests" in Highway Builder settings.
2. Wait for it to run out of obsidian.

### Meteor Version

0.5.6-2005

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by zhubenjamin** [comment]
It seems as if the player is walking a bit too close to the block where it places enderchests, making it unable to place new enderchests, as it would be placing enderchests in the player.

**Comment by Wide-Cat** [comment]
should be fixed 30437a09b9a0f89f6fc5421d4faa3b6db778dc02
