### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Danielqwwww1** [MeteorDevelopment/meteor-client#438]
**Describe the feature**
A clear and concise description of what feature/change is.
Make nuker fast (like wurst nuker)
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by Cypphi** [comment]
Yes, we really need this.
It would be cool if there was an "instant" option which makes the nuker instant instead of 1 block per tick

**Comment by MineGame159** [comment]
`1 block per tick` excuse me?

**Comment by MineGame159** [comment]
Do you even play Minecraft?

**Comment by seasnail8169** [comment]
lmfao
