### ISSUE TITLE
Ignore Friends with kill aura

### ISSUE THREAD

**Issue by Dylanthedabber** [MeteorDevelopment/meteor-client#4382]
### Describe the feature

I am trying to make a swarm of bots to kill players but there is no "ignoreFriends" toggle. pls i feel like in a 2v2 situation would be help full to not kill your Friends with kill aura.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Woodmanxd3** [comment]
Yes, there needs to be an option like this to create bots to fight all players but the ones in the friends list.
Agree.

**Comment by Big-Iron-Cheems** [comment]
Combat modules already ignore friends, as long as you add them to your friends list, either via chat command or using Middle Click Extra.
