### ISSUE TITLE
Meteor Player Tracker

### ISSUE THREAD

**Issue by Mp-Snowie** [MeteorDevelopment/meteor-client#4386]
### Describe the feature

Alr i would love a feater that lets everyone(that uses meteor) can see all other players that use meteor, just like with lunar client on the tab list you could mb add a meteor sign on the right of the name or on the left idk just would love this featere

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This was a feature long ago, but it was removed after many users complained about it. Main reason being admins using Meteor to spot other users.

Though, if you use Meteor where not allowed you deserve the ban.

**Comment by Mp-Snowie** [comment]
alr
sadge but understandable
