### ISSUE TITLE
Sugeestion

### ISSUE THREAD

**Issue by CPC4U** [MeteorDevelopment/meteor-client#4387]
### Describe the feature

I suggest a module is added which you can choose blocks that even if you try to break the block you can't.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
No interact module
