### ISSUE TITLE
Storage ESP

### ISSUE THREAD

**Issue by Set2Minecraft** [MeteorDevelopment/meteor-client#439]
Storage Esp does not register Blast Furnaces or smokers
![2021-04-08_13 50 33](https://user-images.githubusercontent.com/75960074/114073720-98f74380-9871-11eb-974f-c1efe8ce704b.png)

**Comment by MineGame159** [comment]
Can you check your settings if you didn't turn them off

**Comment by MineGame159** [comment]
Nvm, just confirmed it

**Comment by MineGame159** [comment]
Fixed
