### ISSUE TITLE
Crash 1.20.4

### ISSUE THREAD

**Issue by quangei** [MeteorDevelopment/meteor-client#4390]
### Steps to reproduce

it have same crash in dev build 2007 and 2008

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/QXNVzTl

### Meteor Version

0.5.6-2011

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
buy the fucking game

**Comment by quangei** [comment]
but other versions can still be used

**Comment by LLKawi** [comment]
duplicate of #4358
