### ISSUE TITLE
[Suggestion] LongJump

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#440]
**Describe the feature**
Add a module called LongJump. It has probably been suggested already, but it's something we need in our lives.

Options:
Height (how high you jump)
Timer (Timer obviously)
Boost (Boosts you in the beginning of the jump aka you go faster in the beginning of the jump)
Distance (How l o n g is the longjump)
Glide (This would be a checkbox to enable or disable with a slider that determines how slow you glide down)

**Comment by irock2190** [comment]
glide as a separate module would be great

**Comment by ikeafridge4** [comment]
surprised snail hasnt added this yet. not sex >:(

**Comment by Cypphi** [comment]
> surprised snail hasnt added this yet. not sex >:(

yeah, I've suggested it 2 times already in the old suggestions discord channel I believe :/

**Comment by mathmakgakpak** [comment]
close this

**Comment by Cypphi** [comment]
sex

**Comment by Wide-Cat** [comment]
ez
