### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Osmobyte** [MeteorDevelopment/meteor-client#4405]
### Describe the bug

For the HighwayBuilder module, it refuses to build a highway, but I can tell it is trying. It looks like it's just repeat spamming over and over until it places.

### Steps to reproduce

Click the highwaybuilder module. Done

### Meteor Version

1.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
anticheat issue probably
