### ISSUE TITLE
Meteor client crashes with sodium

### ISSUE THREAD

**Issue by exd1337** [MeteorDevelopment/meteor-client#4406]
### Steps to reproduce

1. i opened minecraft and then it crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/xzPuiNc

### Meteor Version

meteor-client-0.5.4-1857

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Paddyk45** [comment]
Quilt is not supported

**Comment by Wide-Cat** [comment]
What sodium version are you using

**Comment by Wide-Cat** [comment]
Acrually nevermind that, I think 0.5.0 is the version that works with meteor for 1.20.1
