### ISSUE TITLE
Crash with sodium

### ISSUE THREAD

**Issue by hmmfab** [MeteorDevelopment/meteor-client#4407]
### Steps to reproduce

1. i opened minecraft 
2. it crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/xAphEQp

### Meteor Version

meteor-client-0.5.4-1857

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Meteor 0.5.4 isn't compatible with sodium 0.5.8. Use an older sodium version, or update to 1.20.4.
