### ISSUE TITLE
can not enter minehut server and evrey server

### ISSUE THREAD

**Issue by TheOnlyOne200** [MeteorDevelopment/meteor-client#4408]
### Describe the bug

can not enter server 
<img width="1440" alt="Screenshot 2024-02-16 at 21 20 50" src="https://github.com/MeteorDevelopment/meteor-client/assets/149260858/205bca92-08f5-4fec-bb00-5b5ae306a804">

### Steps to reproduce

joining server

### Meteor Version

Meteor Client 0.5.5

### Minecraft Version

1.20.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [ ] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Can't do anything without a complete log that includes this error.

**Comment by TheOnlyOne200** [comment]
i have the log



> Can't do anything without a complete log that includes this error.
you need the game log

**Comment by TheOnlyOne200** [comment]
i can join agian
