### ISSUE TITLE
[SUGGESTION] Connect through SOCKS proxies.

### ISSUE THREAD

**Issue by CountBleck** [MeteorDevelopment/meteor-client#441]
**Describe the feature**
Adding the ability to connect to server through a SOCKS proxy, like Inertia.

**Screenshots**
Inertia Proxy:
![Inertia Proxy](https://user-images.githubusercontent.com/79281724/114083421-cd640300-9863-11eb-877c-092fd7666514.png)

**Comment by RedCarlos26** [comment]
Hmmm...

**Comment by Declipsonator** [comment]
You probs can use this for now: https://www.curseforge.com/minecraft/mc-mods/proxy-server

**Comment by MineGame159** [comment]
Added
