### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Yuu1x1** [MeteorDevelopment/meteor-client#4417]
### Describe the feature

![Screenshot (3)](https://github.com/MeteorDevelopment/meteor-client/assets/69886952/ad81d7ea-2d5e-463d-bcdb-45eae5a03ebd)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Have you considered not using Meteor on servers that don't allow it?
