### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TannerRomeo** [MeteorDevelopment/meteor-client#4418]
### Describe the bug

Basically the kill aura no longer works on player it works for like 2 hits then stops working

### Steps to reproduce

No idea what caused it but please fix I used to love this client

### Meteor Version

1.20.4 I believe

### Minecraft Version

1.20.4 I think

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by GreemDev** [comment]
no fucking way you're this oblivious on what version you're using
and also meteor version is not the same as the minecraft version (that's why they're separately asked version numbers.)
