### ISSUE TITLE
Meteor Client crashes with Future

### ISSUE THREAD

**Issue by Nekiplay** [MeteorDevelopment/meteor-client#4422]
### Steps to reproduce

If you remove this change of arguments in this mixin, it stops crashing.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/35975332/1282da9b-6ab7-4597-9a2d-b6bd484df56f)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://paste.ee/p/9of4u

### Meteor Version

0.5.6-2024

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Alixxx-please** [comment]
Please fix!
