### ISSUE TITLE
Add an annotation @Resettable which will reset the value field marked with it onDisable/Activate

### ISSUE THREAD

**Issue by delyfss4796** [MeteorDevelopment/meteor-client#4423]
### Describe the feature

title

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
more context please?

**Comment by delyfss4796** [comment]
```
    private TeleportConfirmC2SPacket packet = null;

    @Override
    public void onActivate() {
        packet = null;
    }
```

in such cases, you can use 
`@Resettable private TeleportConfirmC2SPacket packet = null;`

**Comment by RacoonDog** [comment]
> ```
>     private TeleportConfirmC2SPacket packet = null;
> 
>     @Override
>     public void onActivate() {
>         packet = null;
>     }
> ```
> 
> in such cases, you can use `@Resettable private TeleportConfirmC2SPacket packet = null;`

i dont think it's worth the runtime reflection & added performance usage just to save 4 lines of code per module
