### ISSUE TITLE
[Bug] on website, download for dev build installs the incorrect file

### ISSUE THREAD

**Issue by MrMcDoesntExist** [MeteorDevelopment/meteor-client#4425]
### Describe the bug

download button for devbuild downloads the 1.20.2 version (meteor 5.5 to be specific), I believe it's more that the link has not been updated yet

### Steps to reproduce

1) go to the meteor website;
2) Click dev build (should be 1.20.4);
3) Wait for the 5 seconds before installation;
4) It installs the 5.5 file instead of the 5.6

### Meteor Version

5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Fixed.

**Comment by MrMcDoesntExist** [comment]
Tyvm
