### ISSUE TITLE
The Bug Download in website

### ISSUE THREAD

**Issue by HduongX** [MeteorDevelopment/meteor-client#4426]
### Describe the bug

i go to the website and click to purple button Dev Build 1.20.4
I'm wait 5 sec and download but it's version 0.5.5 not a 0.5.6
not working and can't download!!
![image](https://github.com/MeteorDevelopment/meteor-client/assets/129287904/e1a20944-6c6e-43b2-b9e7-1b8600692844)

### Steps to reproduce

1. this bug make me can't download a new version

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Fixed.

**Comment by HduongX** [comment]
thanks bro
