### ISSUE TITLE
Meteor Client Crashing on v 1.20.1

### ISSUE THREAD

**Issue by Snaxolotl71** [MeteorDevelopment/meteor-client#4427]
### Steps to reproduce

1) Load Minecraft with the following mods on V 1.20.1 with Fabric loader 1.15.7
![Screenshot 2024-02-26 235853](https://github.com/MeteorDevelopment/meteor-client/assets/112205782/40752397-c4c4-420a-adfa-521ff9dde54a)

2) Create a new world
3) "Loading World," then "Saving World."
4) Crash.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/AKSDuYv

### Meteor Version

Meteor 0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
since 1.20.1 is no longer supported, please create support threads on the discord server instead of creating issues

for this crash report though, you need to downgrade sodium to 0.5.3, or possibly older i'm not sure

**Comment by FIVOZ** [comment]
Sodium + meteor = crash
