### ISSUE TITLE
[Suggestion] Auto Tool

### ISSUE THREAD

**Issue by Set2Minecraft** [MeteorDevelopment/meteor-client#443]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
Already in the client

**Comment by Set2Minecraft** [comment]
Gah
I didn't mean to post that, 
What I meant was an option for auto tool to use inventory and set preferences

**Comment by seasnail8169** [comment]
"set preferences"?
