### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nezumi0627** [MeteorDevelopment/meteor-client#4433]
### Describe the bug

Minecraft crashes when I approach a wizar with a specific name. Is there any solution?
![スクリーンショット 2024-02-29 105632](https://github.com/MeteorDevelopment/meteor-client/assets/103794002/889bf4f7-e3dd-4c32-b8a7-4600fee39b8c)

### Steps to reproduce

I approached the wizar with 2b2t jp and displayed the boss bar, but Minecraft crashed. The same phenomenon occurs even if I unplug any mods other than Client.

### Meteor Version

meteor-client-0.5.6-2027.jar

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
send logs

**Comment by nezumi0627** [comment]
> ログを送信

Sorry, where can I get the log?

**Comment by nezumi0627** [comment]
> send logs

Ah, sorry, officially the Client will not be stopped and will no longer be able to access the server.

**Comment by GreemDev** [comment]
> > send logs
> 
> Ah, sorry, officially the Client will not be stopped and will no longer be able to access the server.

??????

**Comment by nezumi0627** [comment]
> > > send logs
> > 
> > 
> > Ah, sorry, officially the Client will not be stopped and will no longer be able to access the server.
> 
> ??????

When I try to display Wizard's BOSS BAR on a server called 2b2t jp, an error occurs on the server and a bug regarding the loading of Wizard's name occurs.

**Comment by hexadecimal233** [comment]
try turning nopacketkick on

**Comment by nezumi0627** [comment]
> nopacketkick

This bug has been successfully fixed by you! Specifically, I used BOSS stack and nopacketkick! thanks so much! ! !
