### ISSUE TITLE
AntiBot in Misc

### ISSUE THREAD

**Issue by zxavius** [MeteorDevelopment/meteor-client#4436]
### Describe the feature

+ AntiBot in Misc
  - Control if Bots should be considered/ignored for Visual and/or Combat Modules
  - Maybe more/better Checks or adjusted Checks since i noticed that ignore bots in nametags for example takes a couple seconds which can be anoying in more crowded scenarios 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by hexadecimal233** [comment]
It did exist in meteor but it was removed and addedto rejects addon

**Comment by hexadecimal233** [comment]
It did exist in meteor but it was removed and addedto rejects addon
