### ISSUE TITLE
Crash on loading world when using Sodium

### ISSUE THREAD

**Issue by sussyboiiii** [MeteorDevelopment/meteor-client#4443]
### Steps to reproduce

I had sodium and metor client installed, after clicking on my world and the loading animation finishing at 100% it said saving world and crashed. Exit-Code: -1073740791

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/aqsTLXj

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Use Sodium 0.5.3 on 1.20.2 or update to 1.20.4 along with your other mods.
