### ISSUE TITLE
[Suggestion] Button which instantly disables Meteor 

### ISSUE THREAD

**Issue by KryptonMiner** [MeteorDevelopment/meteor-client#4447]
### Describe the feature

A button for the Meteor client which does the following:
Disables all the Meteor Enabled Functions,
Hides Meteor Completely,
To enable meteor again you would need to hold a following button, for example Right-Shift for multiple seconds and meteor would activate again

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by GreemDev** [comment]
the only use for a panic feature is to hide cheating on servers you aren't allowed to use clients on. stop cheating on minecraft servers

**Comment by BigShotEmzy** [comment]
bruh just make an extention to it at this point, they not adding it

**Comment by GreemDev** [comment]
> bruh just make an extention to it at this point, they not adding it

Alternatively, stop cheating on a block game made for children. It's fucking sad.
