### ISSUE TITLE
Add support for Sodium 0.5.5 for Meteor Client 1.20.2

### ISSUE THREAD

**Issue by sussyboiiii** [MeteorDevelopment/meteor-client#4458]
### Describe the feature

basically what the title says. When using the newest version and sodium 0.5.5 minecraft crashes on loading a world

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Well known issue, use Sodium 0.5.3 there.
We can't really back port fixes to the 1.20.2 stable branch.

You're free to update to 1.20.4 if you want to use the latest version of Sodium.
