### ISSUE TITLE
[Bug] elytra fly no crash stops on incorrect blocks

### ISSUE THREAD

**Issue by Wide-Cat** [MeteorDevelopment/meteor-client#446]
**Describe the bug**
The elytra no crash setting stops you on some blocks that you can fly through and take no damage on, such as nether portals or tall grass

**To Reproduce**
1. Go to elytra fly
2. turn on no crash
3. fly into portal
4. stop

**Expected behavior**
not stopping

**Comment by RedCarlos26** [comment]
This is not an anti crash issue. The issue was still there before it was implemented.

**Comment by RedCarlos26** [comment]
I also happens without elytra fly on sometimes

**Comment by Declipsonator** [comment]
> 
> 
> This is not an anti crash issue. The issue was still there before it was implemented.

huh? 

> 
> 
> I also happens without elytra fly on sometimes (just by flying in vanilla)

Never heard of this before

**Comment by Wide-Cat** [comment]
how tf is this not an anti crash issue

**Comment by MineGame159** [comment]
Fixed in 790e7580d1ba1e387dfbe7fdc284df582b4c5008

**Comment by Wide-Cat** [comment]
Poggie ❤️
