### ISSUE TITLE
[Bug] sodium / iris not working with meteor?

### ISSUE THREAD

**Issue by TheExoticBone** [MeteorDevelopment/meteor-client#4460]
### Describe the bug

when i launch a world or go into a server with sodium and iris installed, i just crash. the error is too big for me to even understand. anyone know how to fix this?

### Steps to reproduce

1: get meteor 
2: get iris and sodium
3: open minecraft
4: launch world / join server
5: crash

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Downgrade your sodium version. I think 0.5.3 should work.
