### ISSUE TITLE
Game crashes when i start the game

### ISSUE THREAD

**Issue by aedr001** [MeteorDevelopment/meteor-client#4465]
### Steps to reproduce

when i open the game it crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/84NXc8D

### Meteor Version

0.5.5

### Minecraft Version

1.20.2

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Yet another duplicate. 
Use Sodium 0.5.3 if you're using Meteor on 1.20.2, or update to 1.20.4 and use updated mods.
