### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Zitrone30** [MeteorDevelopment/meteor-client#4466]
### Describe the feature

Maby that .panic also disables HUD 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
.panic is not a meteor feature
