### ISSUE TITLE
(sorry for my English) I had an error due to which meteor does not start

### ISSUE THREAD

**Issue by BonBuason** [MeteorDevelopment/meteor-client#4467]
### Describe the bug

meteor I got an error not long ago, I tried to fix the error, but nothing worked, there are no mods, here are the error logs:
[tl-logger4196127999365638463.txt](https://github.com/MeteorDevelopment/meteor-client/files/14664760/tl-logger4196127999365638463.txt)

### Steps to reproduce

I did everything according to the instructions, launched the launcher and an error appeared

### Meteor Version

 meteor Dev Build 0.5.6 [1.20.4]

### Minecraft Version

minecraft 1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/4b256252-9ce7-4819-830f-53054c3683f8)
Cracked launcher issue, we don't provide support for that.
