### ISSUE TITLE
Add Grim Velocity + Grim NoSlow

### ISSUE THREAD

**Issue by PrimeTDMomega** [MeteorDevelopment/meteor-client#4471]
### Describe the feature

Grim Velo + NoSlow is required for CC and most clients don't have it so yeah 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Razzy52** [comment]
make a pull request with the bypasses.

**Comment by PrimeTDMomega** [comment]
I could make a addon since the bypasses are public.

**Comment by Nekiplay** [comment]
Grim No Slow added in Meteor+

**Comment by PrimeTDMomega** [comment]
thx
