### ISSUE TITLE
undetectable nofall

### ISSUE THREAD

**Issue by DaPixelG** [MeteorDevelopment/meteor-client#4475]
### Describe the feature

there is a thing called shift clutch, its basiclly shifting before hitting the ground and you wont get fall damage ive been trying this in hypixel and i didnt get banned

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Nekiplay** [comment]
> there is a thing called shift clutch, its basiclly shifting before hitting the ground and you wont get fall damage ive been trying this in hypixel and i didnt get banned

Lol

**Comment by RacoonDog** [comment]
not worth implementing
