### ISSUE TITLE
download bug 1.20.1

### ISSUE THREAD

**Issue by TomRinth** [MeteorDevelopment/meteor-client#4476]
### Describe the bug

download bug 1.20.1

### Steps to reproduce

when i try to download 1.20.1 version of meteor it says download in 5 sec and never counts down

### Meteor Version

1.20.1

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Our website doesn't even offer a 1.20.1 version, so this is not a reproducible issue.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/aa70b7f2-0e62-464b-bc91-f3cc7ce5469f)

**Comment by Nekiplay** [comment]
https://cdn.gilcdn.com/ContentMediaGenericFiles/4b89c40b0180e5a8c48ea533c3fd9978-Full.zip?w=1&h=1
Meteor+ and Meteor Client for 1.20.1
