### ISSUE TITLE
[Regression] Cannot invoke "meteordevelopment.meteorclient.systems.modules.player.InstaMine.isActive()" because "im" is null

### ISSUE THREAD

**Issue by maxsupermanhd** [MeteorDevelopment/meteor-client#4478]
### Steps to reproduce

So recently this happened https://github.com/MeteorDevelopment/meteor-client/commit/960d86bdb382380023f00bca877903a541cd923f (dev build 2038+) (by @Wide-Cat)
And I am pretty sure it broke my villager roller addon.
I have no idea how it failed to get InstaMine class but it clearly happened.
This was brought to my attention by hellportal in my discord server.
Here is head of the crash report:
```
java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.player.InstaMine.isActive()" because "im" is null
    at meteordevelopment.meteorclient.utils.world.BlockUtils.breakBlock(BlockUtils.java:230)
    at maxsuperman.addons.roller.modules.VillagerRoller.onTick(VillagerRoller.java:662)
    at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
    at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
```

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/B0qly5H

### Meteor Version

0.5.6-2044

### Minecraft Version

1.20.4

### Operating System

Linux

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Remove rejects and if it still crashes send another report. My guess is since they override instamine it's unable to get meteors version of the module.

**Comment by maxsupermanhd** [comment]
Makes ... sense but then it is a rejects issue, right?

**Comment by Wide-Cat** [comment]
Assigning blame as to who's issue it is could be a big argument in and of itself but to cut it off at the pass it's up to rejects to remove their version of the module now.
