### ISSUE TITLE
[Bug]Modules Disable Upon Reconnecting To Servers

### ISSUE THREAD

**Issue by GoldenAureuz** [MeteorDevelopment/meteor-client#448]
Whenever I rejoin a server, all modules that had previously been enabled are disabled (although they appear to be enabled in the gui). Waypoints are also reset.

Leave and rejoin a server with modules enabled. The modules will appear enabled but won't take effect until you disable and reenable them again in the gui.

Modules should stay enabled even after rejoining. 

This is my mods folder (though I'm fairly certain nothing in here is causing the bug. All I have are most of the mods in the Fabulously Optimized modpack, and some Hacked Clients): 
https://user-images.githubusercontent.com/62858980/114110405-6a935b80-98a5-11eb-970e-9849d5ade9ae.png

**Comment by seasnail8169** [comment]
not this again 😭

**Comment by GildedS** [comment]
Snail too ez

**Comment by Declipsonator** [comment]
I remember this making me so confused a while back

**Comment by GoldenAureuz** [comment]
> Whenever I rejoin a server, all modules that had previously been enabled are disabled (although they appear to be enabled in the gui). Waypoints are also reset.
> 
> Leave and rejoin a server with modules enabled. The modules will appear enabled but won't take effect until you disable and reenable them again in the gui.
> 
> Modules should stay enabled even after rejoining.
> 
> This is my mods folder (though I'm fairly certain nothing in here is causing the bug. All I have are most of the mods in the Fabulously Optimized modpack, and some Hacked Clients):
> https://user-images.githubusercontent.com/62858980/114110405-6a935b80-98a5-11eb-970e-9849d5ade9ae.png

**Comment by seasnail8169** [comment]
what

**Comment by MineGame159** [comment]
:pepehuh:
