### ISSUE TITLE
Nucker seems crash with Xaero's World Map (?)

### ISSUE THREAD

**Issue by Blalala6868** [MeteorDevelopment/meteor-client#4483]
### Steps to reproduce

1.turn on the nuker and it crashes
my launcher's automatic analysis says the game is crashing due to Xaero's World Map
![image](https://github.com/MeteorDevelopment/meteor-client/assets/85837864/c54921c3-dce9-4d2c-9a4c-7cc03c51897e)
Here are all the mods I use:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/85837864/c49ae80f-d3ca-4dce-a3d3-364b37435e99)
ps: This crash can also be reproduced in build 2044

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/BZd6rCT

### Meteor Version

meteor-client-0.5.6-2041

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Nekiplay** [comment]
Remove rejects

**Comment by Wide-Cat** [comment]
update rejects to its latest build
