### ISSUE TITLE
Font is blurry after 1.18.2

### ISSUE THREAD

**Issue by ItsMeTomTom** [MeteorDevelopment/meteor-client#4485]
### Describe the bug

FontRender got blurry after the version 1.18.2.

//Code that must be changed in CustomTextRenderer.java
    public CustomTextRenderer(FontFace fontFace) {
        this.fontFace = fontFace;

        byte[] bytes = Utils.readBytes(fontFace.toStream());
        ByteBuffer buffer = BufferUtils.createByteBuffer(bytes.length).put(bytes).flip();

        fonts = new Font[5];
        for (int i = 0; i < fonts.length; i++) {
            fonts[i] = new Font(buffer, (int) Math.round(18 * ((i * 0.5) + 1)));
        }
    }

Maybe something can be done with that number 18 or bring back the old code from that version.
I tried fucking around with it here are the pictures VVVV
![image](https://github.com/MeteorDevelopment/meteor-client/assets/117825828/9dbcd99d-c1c5-40a3-988d-467678168847)

### Steps to reproduce

1. open 1.18.2 instance with meteor
2. open latest meteor instance
3. compare the roundness of the font in the gui

### Meteor Version

meteor-client-0.5.6-2044

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
f42a690ce50e3235d8becb1b9e0384194d6b33b3
