### ISSUE TITLE
[Suggestion] Change how auto mend's auto armor slots & auto armor confliction works

### ISSUE THREAD

**Issue by yupyup0666** [MeteorDevelopment/meteor-client#450]
**Describe the feature**
Instead of disabling auto armor slots all together when auto armor is on, keep it enabled but stop it from doing anything until auto armor is disabled. This is so it still works if you toggle off auto armor instead of having to manually enable it again through the GUI, which is rather annoying.
I am aware you can toggle auto armor off, toggle auto mend on, then off, then toggle auto armor back on, but that requires even more effort than it took me to write that sentence.

**Comment by MineGame159** [comment]
After 17306b395ac337ba25214b6ded4ea9dff55d5294 Auto Mend now doesn't use armor slots because it isn't any faster than just using offhand.
