### ISSUE TITLE
Add Anti Vanish Tab numbers

### ISSUE THREAD

**Issue by BaeHyolyn** [MeteorDevelopment/meteor-client#4500]
### Describe the feature

In the tab game add numbers to the players for count the number of users in the game and see if a staff vanish is on the game

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by theotherhades** [comment]
Please reword in a coherent way

**Comment by Nekiplay** [comment]
> Please reword in a coherent way

On the servers there is /vanish and he wants the admins who are in vanish to be shown in the tab, or rather how many admins are in vanish

**Comment by BaeHyolyn** [comment]
> Please reword in a coherent way

I meant to assign numbers to each user in the scoreboard to compare with the number of connected users/staff in vanish
