### ISSUE TITLE
Litematic Auto Build

### ISSUE THREAD

**Issue by TurtlemanLiam** [MeteorDevelopment/meteor-client#4502]
### Describe the feature

Recently baritone and Meteor Client have separated, which could lead to other things of such, like litematica, litematica as you prob know is like schematica but for fabric. meteorclient can use .litematica files from the schematics folder and will auto build them

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This makes no sense, are you trying to say that now you can't use Litematica with Meteor or something?

You can still download Baritone separately too, it is it's own mod after all.
