### ISSUE TITLE
The player wearing Nethrit Helmet broke my Minecraft.

### ISSUE THREAD

**Issue by Gxy20101221** [MeteorDevelopment/meteor-client#4504]
### Steps to reproduce

1. I used ViaFabricPlus to get into version 1.19.2 of Minecraft servers.
2. I met a player wearing a Netherite Helmet.In an instant, my Minecraft crashed.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/jEjUKXn

### Meteor Version

Meteor 0.5.6-2051

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
should be fixed by c2990cf6a62ca8413a129fdba683d9f5ddf12250
