### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by illiania100** [MeteorDevelopment/meteor-client#4505]
### Steps to reproduce

reboot system(windows) and sometimes minecraft will crash on start

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/3unzc0T

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
meteor doesnt work on tlauncher or its other shitty derivatives, buy the game
