### ISSUE TITLE
esp

### ISSUE THREAD

**Issue by litobait** [MeteorDevelopment/meteor-client#4506]
### Describe the feature

add player and mob esp please

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by litobait** [comment]
@Wide-Cat what is it called then in meteor

**Comment by Wide-Cat** [comment]
Esp
