### ISSUE TITLE
[Bug]Rejoining a Server Disables All Modules

### ISSUE THREAD

**Issue by GoldenAureuz** [MeteorDevelopment/meteor-client#451]
Whenever I rejoin a server, all modules that had previously been enabled are disabled (although they appear to be enabled in the gui). Waypoints are also reset.

Leave and rejoin a server with modules enabled. The modules will appear enabled but won't take effect until you disable and reenable them again in the gui.

Modules should stay enabled even after rejoining.

This is my mods folder (though I'm fairly certain nothing in here is causing the bug. All I have are most of the mods in the Fabulously Optimized modpack, and some Hacked Clients):
https://user-images.githubusercontent.com/62858980/114110405-6a935b80-98a5-11eb-970e-9849d5ade9ae.png
(reuploaded, I accidentally closed the last one because I'm an idiot)

**Comment by seasnail8169** [comment]
lol

**Comment by RedCarlos26** [comment]
I can confirm I need to reload a profile for the modules to come back.

**Comment by RedCarlos26** [comment]
I cannot confirm in latest dev build.

**Comment by RedCarlos26** [comment]
I think this got fixed.

**Comment by RedCarlos26** [comment]
@GoldenAureuz does it still happen with the latest release?
