### ISSUE TITLE
causes the clone and stack tool of axiom to crash

### ISSUE THREAD

**Issue by voidapex11** [MeteorDevelopment/meteor-client#4511]
### Steps to reproduce

go onto creative with meteor and axiom enablesd, try to use clone or stack tool, observe crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

no crash report just exit code -1

### Meteor Version

meteor-client-0.5.6-2051

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
cant really do anything without a crash report

**Comment by tajemniktv** [comment]
Possible fix provided in Axiom discord:
![image](https://github.com/user-attachments/assets/0fbdaa82-6211-4e42-af55-5837148e6069)
to
![image](https://github.com/user-attachments/assets/e317f7c5-d845-46d3-b16a-fcd6fa46a025)

**Comment by Wide-Cat** [comment]
think this has been fixed
