### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Streakygg** [MeteorDevelopment/meteor-client#4514]
### Describe the feature

Add Excavate It would be useful to mine AFK, for example, you point from one side to the other and have the bot mine the part you pointed out, being useful to mine AFK chunks all night
 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
I literally wrote that [module](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/systems/modules/world/Excavator.java) 8 months ago.
So yeah, use it.
