### ISSUE TITLE
[Bug] Crash when leaving the game (again)

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#452]
The same issue as #425 is happening in dev build 706.
Here is the new crash report:
[crash-2021-04-08_22.02.06-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6282669/crash-2021-04-08_22.02.06-client.txt)

**Comment by seasnail8169** [comment]
Can you try to figure out which module is causing it please.

**Comment by RedCarlos26** [comment]
I'm gonna check this tomorrow

**Comment by RedCarlos26** [comment]
I guess I need to enable a module at a time?

**Comment by Declipsonator** [comment]
Just take all the modules you have and slowly toggle them off until it doesn't do it anymore

**Comment by RedCarlos26** [comment]
I found which module causes the crash. It's the anti void module. And also, when I disable it (in-game) it activates the flight module. @seasnail8169

**Comment by MineGame159** [comment]
Couldnt reproduce the crash but fixed it enabling Flight in a144562f604f2e05a2c4ca693c8ba5d2983bfebe
