### ISSUE TITLE
[Suggestion] client side andticheat 

### ISSUE THREAD

**Issue by TDbea** [MeteorDevelopment/meteor-client#4523]
### Describe the feature

this is a module that detects if anyone in your render distance is cheating or not and lets you know it chat and highlights their nametag.
<img width="474" alt="Screenshot 2024-04-14 at 17 41 51" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/06b5cde3-b50b-432c-9b35-dd05a0effcbb">
<img width="488" alt="Screenshot 2024-04-14 at 17 42 30" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/c17ede84-c5e6-4240-b0ad-9d84519857ab">
<img width="463" alt="Screenshot 2024-04-14 at 17 42 49" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/7a82cd04-b3ae-4d81-ba7f-b8a79059bc86">
<img width="466" alt="Screenshot 2024-04-14 at 17 43 15" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/1d14a783-48ff-4359-9187-a7ef66d50c73">
<img width="495" alt="Screenshot 2024-04-14 at 17 43 35" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/d22088e2-692f-4201-9cc8-e1d68ff69036">
<img width="434" alt="Screenshot 2024-04-14 at 17 44 12" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/3f7a23cf-f35f-4af0-b2d4-2d610d61ead8">
<img width="434" alt="Screenshot 2024-04-14 at 17 44 24" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/de2ff7f4-b354-4498-834f-7c7f71c0dc1f">
<img width="434" alt="Screenshot 2024-04-14 at 17 45 02" src="https://github.com/MeteorDevelopment/meteor-client/assets/108836857/d083b22c-c002-438b-9d5c-0bd0e4ec7518">

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Let's ignore the complexity of such a module for a second.
- What would be the use case of this?
- What does the end user gain by knowing if someone else is cheating?

**Comment by abb3v** [comment]
> What would be the use case of this?

so you can report people who are cheating, using a screenshot from your hacked client as proof, duh.

**Comment by TDbea** [comment]
> Let's ignore the complexity of such a module for a second.
> 
> * What would be the use case of this?
> * What does the end user gain by knowing if someone else is cheating?

ok so it is already in alot of 1.8.9 clients and not not to report the cheater just to identify them befor you run into them ingame or avoid them iv used the 1.8.9 ones and it was quite usfule

**Comment by Wide-Cat** [comment]
This would be useful for something like a 1.8.9 minigame cheating client but meteor is designed for anarchy servers, and in those cases you can pretty comfortably assume everyone else you meet is using a client.

**Comment by TDbea** [comment]
> This would be useful for something like a 1.8.9 minigame cheating client but meteor is designed for anarchy servers, and in those cases you can pretty comfortably assume everyone else you meet is using a client.

yes ik but i have been in multiple situations that i would have liked to have this feature

**Comment by Wide-Cat** [comment]
I guess on an intellectual level it could be interesting to look at, but frankly I wouldn't count on it being added. Do you know of any leaked or open source clients with checks like these because I can say with near 100% certainty none of the main contributors would care enough to discover and write checks themselves.

**Comment by TDbea** [comment]
> I guess on an intellectual level it could be interesting to look at, but frankly I wouldn't count on it being added. Do you know of any leaked or open source clients with checks like these because I can say with near 100% certainty none of the main contributors would care enough to discover and write checks themselves.

https://github.com/Alexdoru/MegaWallsEnhancements?tab=readme-ov-file#installation

this mod has nocheaters mod in it and has open source
