### ISSUE TITLE
Enabling HighwayBuilder crashes game

### ISSUE THREAD

**Issue by Tristan3030** [MeteorDevelopment/meteor-client#4526]
### Steps to reproduce

1. Enable HighwayBuilder
2. Game crashes instantly

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/oasknml

### Meteor Version

0.5.6 - 2055

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
update or remove rejects addon

**Comment by Tristan3030** [comment]
> update or remove rejects addon

issue fixed, thank you!
