### ISSUE TITLE
The mod 'advanced_runtime_resource_pack' has thrown an exception.

### ISSUE THREAD

**Issue by harmoff** [MeteorDevelopment/meteor-client#4527]
### Steps to reproduce

1. clean minecraft folder
2. installed 1.20.4 (official minecraft launcher)
3. installed fabric 1.20,4
4. installed all my mods (https://i.imgur.com/xwlzpJ0.jpeg)
5. installed meteor+meteor plus from official/github pages (for 1.20.4 ver)
6. open official minecraft launcer, boost memory limit to 22gb (i have 32)
7. open minecraft

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/PPkb6Z4

### Meteor Version

Dev Build 0.5.6 [1.20.4]

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by harmoff** [comment]
anyway i dont install any resourcepack mod :/

**Comment by Big-Iron-Cheems** [comment]
> anyway i dont install any resourcepack mod :/

![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/c56cb353-ad23-401a-b183-27fdeed282e4)
It's being included by `enhancedblockentities`, seems like it's crashing with one of our mixins.

Try without that mod.

**Comment by harmoff** [comment]
> > anyway i dont install any resourcepack mod :/
> 
> ![image](https://private-user-images.githubusercontent.com/52252627/322992871-c56cb353-ad23-401a-b183-27fdeed282e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMDA0OTIsIm5iZiI6MTcxMzMwMDE5MiwicGF0aCI6Ii81MjI1MjYyNy8zMjI5OTI4NzEtYzU2Y2IzNTMtYWQyMy00MDFhLWIxODMtMjdmZGVlZDI4MmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDIwNDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2EzNmQ3ODVjZmM0Y2Q3OGMxYTU5ZThhNDljNjBmODNkNTA3ZTA0MDA0OTdkY2Y0ZDAzZGNlYTkzMDE4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z8m6zWDRyBHhlA5wryO3Hz2dvpJ25xTsS0NMIUGPpBU) It's being included by `enhancedblockentities`, seems like it's crashing with one of our mixins.
> 
> Try without that mod.

https://mclo.gs/hz20NoZ - analyze, when i cleaned mod folder, couse all my mods, include replaymod and optimization mods warned in mclo.gs

**Comment by RacoonDog** [comment]
> > > anyway i dont install any resourcepack mod :/
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/52252627/322992871-c56cb353-ad23-401a-b183-27fdeed282e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMDA0OTIsIm5iZiI6MTcxMzMwMDE5MiwicGF0aCI6Ii81MjI1MjYyNy8zMjI5OTI4NzEtYzU2Y2IzNTMtYWQyMy00MDFhLWIxODMtMjdmZGVlZDI4MmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDIwNDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2EzNmQ3ODVjZmM0Y2Q3OGMxYTU5ZThhNDljNjBmODNkNTA3ZTA0MDA0OTdkY2Y0ZDAzZGNlYTkzMDE4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z8m6zWDRyBHhlA5wryO3Hz2dvpJ25xTsS0NMIUGPpBU) It's being included by `enhancedblockentities`, seems like it's crashing with one of our mixins.
> > Try without that mod.
> 
> https://mclo.gs/hz20NoZ - analyze, when i cleaned mod folder, couse all my mods, include replaymod and optimization mods warned in mclo.gs

keep removing mods until you find the smallest combination of mods that still crashes with this error

**Comment by harmoff** [comment]
> > > > anyway i dont install any resourcepack mod :/
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/52252627/322992871-c56cb353-ad23-401a-b183-27fdeed282e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMDA0OTIsIm5iZiI6MTcxMzMwMDE5MiwicGF0aCI6Ii81MjI1MjYyNy8zMjI5OTI4NzEtYzU2Y2IzNTMtYWQyMy00MDFhLWIxODMtMjdmZGVlZDI4MmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDIwNDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2EzNmQ3ODVjZmM0Y2Q3OGMxYTU5ZThhNDljNjBmODNkNTA3ZTA0MDA0OTdkY2Y0ZDAzZGNlYTkzMDE4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z8m6zWDRyBHhlA5wryO3Hz2dvpJ25xTsS0NMIUGPpBU) It's being included by `enhancedblockentities`, seems like it's crashing with one of our mixins.
> > > Try without that mod.
> > 
> > 
> > https://mclo.gs/hz20NoZ - analyze, when i cleaned mod folder, couse all my mods, include replaymod and optimization mods warned in mclo.gs
> 
> keep removing mods until you find the smallest combination of mods that still crashes with this error

ahh man( https://i.imgur.com/0nxKlSx.jpeg

**Comment by harmoff** [comment]
after i delete emotecraft, it works stable, thank you for help a lot!
