### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by z3r0br00** [MeteorDevelopment/meteor-client#4528]
### Describe the bug

better chat doesn't work it doesn't show suffix or fancy chat

### Steps to reproduce

better chat does not work

### Meteor Version

Meteor 0.5.5

### Minecraft Version

mc 1.20.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by lostthereal** [comment]
^^ fix this pls papiss LMFAO

**Comment by Big-Iron-Cheems** [comment]
Issues are supposed to be made only if the bug happens on the newest Meteor version.
We cannot backport changes to older versions.
