### ISSUE TITLE
Meteor Client Crashes Minecraft upon Activating Modules

### ISSUE THREAD

**Issue by TheSrBig** [MeteorDevelopment/meteor-client#4529]
### Describe the bug

Upon activating a module in the latest version of Meteor Client for Minecraft 1.20.4, the game functions correctly initially. However, once the user leaves or the servers kicks the user and re-enters the server, activating the same module or any other module results in Minecraft crashing.

### Steps to reproduce

Launch Minecraft 1.20.4 with the latest version of Meteor Client installed.
Activate a module, such as Fly, using a bound key.
Play the game with the module active.
Exit the server or get kicked from the server.
Rejoin the server.
Attempt to activate the same module or any other module.
Observe Minecraft crashing.

### Meteor Version

meteor-client-0.5.6-2054

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by TheSrBig** [comment]
[crash-2024-04-18_17.09.00-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/15031348/crash-2024-04-18_17.09.00-client.txt)

**Comment by TheSrBig** [comment]
[crash-2024-04-18_17.09.00-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/15031354/crash-2024-04-18_17.09.00-client.txt)

**Comment by Wide-Cat** [comment]
Can you try to reproduce this error with just meteor and no other mods present, and send another crash report if you manage to do so.

**Comment by TheSrBig** [comment]
Hello, thanks to a friend of mine, he told me that this happens thanks to rusherhack, I checked and it is true, so the cause is to have rusherhack.

**Comment by TheSrBig** [comment]
> Can you try to reproduce this error with just meteor and no other mods present, and send another crash report if you manage to do so.

Hello, thanks to a friend of mine, he told me that this happens thanks to rusherhack, I checked and it is true, so the cause is to have rusherhack.
