### ISSUE TITLE
Meteor crashes on launch

### ISSUE THREAD

**Issue by Saokian** [MeteorDevelopment/meteor-client#4533]
### Steps to reproduce

Meteor crashes on launch whenever I use a specific launcher (Legacy Launcher)
This also happens on the 0.5.5 build
1.  Install legacy launcher latest
2. Install meteor and fabric api
3. Launch

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/ctqSgdA

### Meteor Version

0.5.6 

### Minecraft Version

1.20.4

### Operating System

macOS

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Meteor doesn't work on tlauncher or it's derivatives. Buy the game.

**Comment by Big-Iron-Cheems** [comment]
We do not support cracked launchers, as explained in our [FAQ](https://meteorclient.com/faq/installation#unsafe-cracked-launchers).
Any issues related to them are not going to be handled, as these launchers modify the game itself in incompatible ways.

**Comment by DarkFenix139** [comment]
That's funny. Apparently, the Meteor developers specifically made it so that the mod would not work with the pirate launcher.

**Comment by Big-Iron-Cheems** [comment]
> That's funny. Apparently, the Meteor developers specifically made it so that the mod would not work with the pirate launcher.

Correction: the incompatibility is caused by outdated code in the cracked launcher.
It's not our fault their code is broken and then causes issues with our.

**Comment by DarkFenix139** [comment]
> > That's funny. Apparently, the Meteor developers specifically made it so that the mod would not work with the pirate launcher.
> 
> Correction: the incompatibility is caused by outdated code in the cracked launcher. It's not our fault their code is broken and then causes issues with our.

There is also a theoretical possibility that this incompatibility was done on purpose. Because the launcher developers do not openly support cheaters (and they can be understood). But whether this was done on purpose or not, I don’t know. Not a programmer. Maybe you know better
