### ISSUE TITLE
Old downloads

### ISSUE THREAD

**Issue by durozzzz** [MeteorDevelopment/meteor-client#4535]
### Describe the bug

I tried to download old versions of meteor client aka version 0.5.4 and I listens to all the instructions but I can’t get the terminal to build the jar file

### Steps to reproduce

I downloaded the zip and extracted it then I opened the file in a new terminal and ran the code but there was an error

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported (I have searched bug reports on GitHub).

- [ ] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by durozzzz** [comment]
Help fast

**Comment by Wide-Cat** [comment]
not like we can do anything unless you provide the error

**Comment by durozzzz** [comment]
where do i find it once its built

**Comment by Big-Iron-Cheems** [comment]
In the build/libs folder, as said in our guide.
