### ISSUE TITLE
Baritone keeps crashing when trying to launch Minecraft 

### ISSUE THREAD

**Issue by Nightsper** [MeteorDevelopment/meteor-client#4536]
### Steps to reproduce

I'm using Fabric and pojav launcher on my android. This is the baritone file I used baritone-api-fabric-1.10.2-1-g6d067136.jar in the [artifacts](https://github.com/cabaletta/baritone/actions/runs/8475101949) folder on baritone's GitHub page 

I added baritone into my mods folder and tried joining Minecraft but it keeps crashing everytime

Also I asked baritone's GitHub and they said to send you [these](https://github.com/cabaletta/baritone/commit/d51b23bd1ea09e940b18874b6a0f52843735f48c#diff-20ac2ad58ae3e02c48339b26e344680be33dbcf2f3ac2902a944e0e07ff7cbb7R55) [two](https://github.com/MeteorDevelopment/meteor-client/blob/8a7079652a6bd42cc6acc5cfe8eb917e5d1d0199/src/main/java/meteordevelopment/meteorclient/pathing/BaritoneSettings.java#L80) in addition to my log file

### Meteor Version

Dev Build 0.5.6 [1.20.4]

### Minecraft Version

1.20.4

### Operating System

Linux

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Kyrotechnic** [comment]
Go to [meteor client](meteorclient.com) and scroll down and click the baritone download button

**Comment by ZacSharp** [comment]
@Kyrotechnic they can't use that file because it is missing a crashfix @Nightsper needs ([this one](https://github.com/cabaletta/baritone/pull/4244) specifically). Without it Baritone itself crashes their game during startup.

**Comment by MineGame159** [comment]
Fixed in 53b141f12797234904b4968808e631ffb02919f9.

**Comment by Nightsper** [comment]
I know I might sound dumb but where is the download?
