### ISSUE TITLE
portal esp

### ISSUE THREAD

**Issue by litobait** [MeteorDevelopment/meteor-client#4537]
### Describe the feature

add portal esp 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
You can already locate portals using `BlockESP` and filtering for the `nether_portal` block.

**Comment by litobait** [comment]
thank you!!!
