### ISSUE TITLE
I know I might sound dumb but where is the download that I need?

### ISSUE THREAD

**Issue by Nightsper** [MeteorDevelopment/meteor-client#4539]
I know I might sound dumb but where is the download that I need?

_Originally posted by @Nightsper in https://github.com/MeteorDevelopment/meteor-client/issues/4536#issuecomment-2068259613_

**Comment by Wide-Cat** [comment]
either our discord server or the github actions tab

**Comment by Nightsper** [comment]
> either our discord server or the github actions tab

Yeah but I crashed with the baritone file from the meteor client website

**Comment by Big-Iron-Cheems** [comment]
Minegame literally made a patch for it earlier.
You just need to download the new meteor dev build.

**Comment by Nightsper** [comment]
> Minegame literally made a patch for it earlier. You just need to download the new meteor dev build.

Yes I added the new Dev build he made and it works fine when launching Minecraft but when I  also add the baritone file too it crashes 
Here the log of you want: 
[latestlog.txt](https://github.com/MeteorDevelopment/meteor-client/files/15055636/latestlog.txt)

**Comment by Nightsper** [comment]
Nvrmd I had use this release cause the the release on the meteor website was too old

**Comment by Nightsper** [comment]
Nvrmd I had use [this](https://github.com/cabaletta/baritone/actions/runs/8475101949/artifacts/1368500843) release cause the the release on the meteor website was too old

**Comment by abb3v** [comment]
meteor user figures something out on their own??? 🤯
