### ISSUE TITLE
Crash on server when activating 

### ISSUE THREAD

**Issue by Lapinoub** [MeteorDevelopment/meteor-client#4540]
### Steps to reproduce

Turn on Insta Mine **on a server** and then it kicks you. Does not kick in singleplayer

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

not applicable

### Meteor Version

0.5.6 2061

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Can't do anything without a log or crash report
