### ISSUE TITLE
suggest dont close

### ISSUE THREAD

**Issue by HackerYT2078** [MeteorDevelopment/meteor-client#4542]
### Describe the feature

please add a cheat called Infinity reach to the meteor client, which allows you to beat players with a maximum of about 50
grids in minecraft and please update the meteor client to 1.20.5

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
No. Open the issue once more time and you are banned

**Comment by HackerYT2078** [comment]
fuck off on me ticket im tell to police!!!

**Comment by HackerYT2078** [comment]
for

**Comment by HackerYT2078** [comment]
whats ban for?

**Comment by HackerYT2078** [comment]
i have good sugest bruch

**Comment by HackerYT2078** [comment]
what
