### ISSUE TITLE
pls ban this user for banning suggestions and users user is MineGame159

### ISSUE THREAD

**Issue by HackerYT2078** [MeteorDevelopment/meteor-client#4543]
### Describe the feature

[MineGame159](https://github.com/MineGame159) banning me for good suggest for meteor client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by HackerYT2078** [comment]
bruch what

**Comment by Wide-Cat** [comment]
Sorry minegame you're getting banned now

**Comment by MineGame159** [comment]
:why:
