### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by WalksygyATT** [MeteorDevelopment/meteor-client#4550]
### Describe the bug

I think better tab has something to do with this. Basically very frequently all sort of guis start glitching out (not the meteor one) like the inventory , hotbar , chat and basically they keep on disappearing and only SOMETIMES the only fix to it is to open and reopen the clickgui of meteor idk what to do and how to fix this

### Steps to reproduce

happens on different servers

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
can you send a list of what other mods you have installed

**Comment by theotherhades** [comment]
"happens on different servers" is not a valid step to reproduce. send a screenshot of your mod folder and your log
