### ISSUE TITLE
Box Miner

### ISSUE THREAD

**Issue by ori64TS** [MeteorDevelopment/meteor-client#4552]
### Describe the feature

I love playing box servers and i love using meteor and i would like a way to auto mine in box server. i know you can use vein miner but if people are around ofc that you cant. i want you to please add a mod that mine for you in box servers and mine like regular player would. it will be hard but i know that you can do it. there are a lot of pepole who are waiting a lot of time for this
![Screenshot (50)](https://github.com/MeteorDevelopment/meteor-client/assets/117532209/ffabf979-0d1a-4e7b-b4f8-4457412594d2)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Meteor is blatant by design, we have no interest in making it undetectable for minigame servers or similar.
It is a mod targeting anarchy servers, where such modifications are allowed.
