### ISSUE TITLE
ingame scripting.

### ISSUE THREAD

**Issue by kgncengiz** [MeteorDevelopment/meteor-client#4554]
### Describe the feature

feature: People can create in-game scripts with Lua (or a similar scripting language) such as packet modification, response, packet loops, module macros, hotkeys, module settings, GUI, etc. in the meteor menu.

example script:
```
@eventhandler
packetsendevent(packetsendevent event){
  if(event.getpacket == something)
  event.setpacket(event.getpacket.getvalue + 1);
}
```

btw yes I am a Java dev.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
The amount of effort required to support that is really way more than what I personally would put into Meteor.
I have honestly never understood the point of in-game scripting for an MC mod.

If you're going to write code, you might as well download the source, implement your feature in the native language, and use it directly.

**Comment by kgncengiz** [comment]
I cant change it in-game if I implement it in code.

**Comment by Big-Iron-Cheems** [comment]
Do you want me to really explain, in depth, via multiple paragraphs, what are the complete requirements this feature should meet to be easily accessible by the general public?
Or would you rather think about those yourself first and understand the complexity of such an addition?

**Comment by CrytoPal** [comment]
@kgncengiz https://github.com/CrytoPal/meteor-scripts-api
