### ISSUE TITLE
Coordinate numbers arent the same as F3 menu

### ISSUE THREAD

**Issue by Tristan3030** [MeteorDevelopment/meteor-client#4555]
### Describe the bug

When using the text position hud it shows the wrong coordinates. off by 1 block. I'm not sure if its being rounded up or what, but its annoying because I built something off by 1 block.
![image_2024-04-30_005737697](https://github.com/MeteorDevelopment/meteor-client/assets/67524464/0d082186-4293-4477-a967-6b878fae7caf)
![image_2024-04-30_005751269](https://github.com/MeteorDevelopment/meteor-client/assets/67524464/00760c37-731a-47b8-9242-cd1ea6e02736)

### Steps to reproduce

Add "Text - Position" to your HUD
Check F3
Will be off by 1 block (might just be negative coordinates)

### Meteor Version

Meteor 0.5.6-2065

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by abb3v** [comment]
The text position script is just `Pos: #1{floor(camera.pos.x)}, {floor(camera.pos.y)}, {floor(camera.pos.z)}`, if you wan't, remove flooring

**Comment by Tristan3030** [comment]
> The text position script is just `Pos: #1{floor(camera.pos.x)}, {floor(camera.pos.y)}, {floor(camera.pos.z)}`. It doesn't round, it floors, I am not sure why you are having this functionality. Can you ensure that your script is doing this?

I have that exact script in it but it shows -1051 instead of -1050

**Comment by abb3v** [comment]
So are you sure that bottom text's script is flooring and not ceil?

**Comment by Tristan3030** [comment]
> So are you sure that bottom text's script is flooring and not ceil?
 Yes im sure. changing it to ceil only fixes it for the negative coordinates. as for positive coordinates floor fixes it.

**Comment by Tristan3030** [comment]
Fixed by doing `Pos: #1{((round(camera.pos.x, 1)))}, {((round(camera.pos.y, 1)))}, {(round(camera.pos.z, 1))}`

**Comment by Big-Iron-Cheems** [comment]
I believe the "issue" is that one of the two takes height at the player head, while the other does so at the player legs.
