### ISSUE TITLE
Auto Discard

### ISSUE THREAD

**Issue by IfMadeAGitHubAccount** [MeteorDevelopment/meteor-client#4556]
### Describe the feature

I got this idea because when I was killing sheep I got wool I didn't want, so it'd be nice to automatically discard unwanted items from inventory

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
inventory tweaks module
