### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ahmetycan** [MeteorDevelopment/meteor-client#4557]
### Steps to reproduce

It crashes as soon as I enter.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/HbNJkWm

### Meteor Version

Last Version

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Meteor doesn't work on tlauncher or it's derivatives. Buy the game.
