### ISSUE TITLE
[Suggestion] no fog

### ISSUE THREAD

**Issue by litobait** [MeteorDevelopment/meteor-client#4558]
### Describe the feature

i swear if its there 😭

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
It's a setting in no render

**Comment by litobait** [comment]
thanks
