### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wasteyou** [MeteorDevelopment/meteor-client#4560]
### Describe the bug

Nothing renders when loading in.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/104725269/ecb021ed-db4f-4953-ae06-f1705f352205)

### Steps to reproduce

May be sever lag that caused it? idk

### Meteor Version

0.5.6-2065

### Minecraft Version

1.20.4, used viafabric to connect to a 1.20.5 server

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
A 1.20.4 client connecting to a 1.20.5 server will undoubtedly be thoroughly broken. The latest dev build we just released is compatible with 1.20.5, use that instead.
