### ISSUE TITLE
Recent Update Crash

### ISSUE THREAD

**Issue by TheSrBig** [MeteorDevelopment/meteor-client#4561]
### Steps to reproduce

I have only replaced meteor with the new update and it crashes at startup.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/XSGHZab

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
The keybinds system was updated to support key combinations.
Any addon that tries to change this behaviour needs to update accordingly.

Solution: temporarily stop using `meteorplus` until they adapt.

**Comment by TheSrBig** [comment]
Alright
