### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Vortex5k** [MeteorDevelopment/meteor-client#4565]
### Describe the bug

If I pick up stone or netherrack, it get put in a random hotbar slot. For netherrack its slot 9 and for cobblestone its slot 1. Its not bc of any module ( i turned them all off).

### Steps to reproduce

I dont know. I just used the client a bit. Configing installing and deleting addons...

### Meteor Version

latest realease (not beta) this was an issue in every verion though

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Vortex5k** [comment]
also my pickaxe is moving into the first slot upon moving it in the inventory

**Comment by Wide-Cat** [comment]
its a baritone setting do #allowInventory false

**Comment by Vortex5k** [comment]
thx

**Comment by Vortex5k** [comment]
it worked
