### ISSUE TITLE
1.20.1not compatible with sodium

### ISSUE THREAD

**Issue by TBNLZLDYD** [MeteorDevelopment/meteor-client#4566]
### Steps to reproduce

use HMCL launcher start game,then crash.HMCL Traditional Chinese Medicine Hospital said,This is meteor not compatible with sodium,but meteor is cheat，they not resolved.qwq

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://www.123pan.com/s/pvn0jv-nm7LH.html

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
1. Meteor 0.5.4 is no longer supported
2. You should downgrade Sodium to v0.5.3 if you're playing on 1.20.1

**Comment by TBNLZLDYD** [comment]
Ok,thank you.
________________________________
发件人: Big Iron ***@***.***>
发送时间: 2024年5月5日 19:06
收件人: MeteorDevelopment/meteor-client ***@***.***>
抄送: TBNLZLDYD ***@***.***>; Author ***@***.***>
主题: Re: [MeteorDevelopment/meteor-client] 1.20.1not compatible with sodium (Issue #4566)


  1.  Meteor 0.5.4 is no longer supported
  2.  You should downgrade Sodium to v0.5.3 if you're playing on 1.20.1

―
