### ISSUE TITLE
departure due to the operation of the piston, and the fall of the blocks (mod continuity)

### ISSUE THREAD

**Issue by razuriru** [MeteorDevelopment/meteor-client#4567]
### Steps to reproduce
1.Using Sodium
2. When using a piston (any activate block), the game crashes
3. If  block (sand, gravel) falls, the game also crashes
4. mods
![23](https://github.com/MeteorDevelopment/meteor-client/assets/168965725/f89aed2e-6a27-4f7a-b473-8f38e05e0f5f)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Kp5jn69

### Meteor Version

meteor-client-0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Crash seems to be caused by Continuity, not Meteor. Reopen if this happens without said mod.

**Comment by 0xTas** [comment]
iirc, installing Indium fixes this issue.
