### ISSUE TITLE
Recent commit causes upside HUD elements

### ISSUE THREAD

**Issue by CoffeeBrewer64** [MeteorDevelopment/meteor-client#4568]
### Describe the bug

[This commit ](https://github.com/MeteorDevelopment/meteor-client/commit/cc675ed9b2ec25977c8b0e836457f803c8cbd676) has made parts of the vanilla HUD, such as the hearts, food, armour strength and connectivity bar, upside down.

i tried this in a fork of mine, but reverting this single commit in my fork and rebuilding it fixed the issue

i may be going crazy

### Steps to reproduce

1. use dev build
2. open a game (i only tried multiplayer, doubt it's different for singleplayer)
3. observe

### Meteor Version

0.5.7

### Minecraft Version

1.20.6

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Send an image of your screen, and what other mods you have installed.

**Comment by CoffeeBrewer64** [comment]
i have no clue what happened. it doesn't seem to happen anymore. no clue what i did
