### ISSUE TITLE
Meteor crash with Concurrent Chunk Management Engine

### ISSUE THREAD

**Issue by Blalala6868** [MeteorDevelopment/meteor-client#4569]
### Steps to reproduce

Meteor crash with Concurrent Chunk Management Engine
(But I’m not sure the latest version of Meteor will crash with this)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/gyKe9pP

### Meteor Version

meteor-client-0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [ ] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
The crash is actually being caused by Meteor Plus, they need to update their code.
Also, we don't suggest using c2me as it could cause some issues.

**Comment by Blalala6868** [comment]
> The crash is actually being caused by Meteor Plus, they need to update their code. Also, we don't suggest using c2me as it could cause some issues.

But this crash doesn't seem to occur with meteor-client-0.5.6-2061+meteor-plus-1.0.7+c2me-fabric-mc1.20.4-0.2.0+alpha.11.65

**Comment by Wide-Cat** [comment]
meteor is broken with meteor plus as of dev build 2066
