### ISSUE TITLE
Update for MC 1.21

### ISSUE THREAD

**Issue by MrHello420** [MeteorDevelopment/meteor-client#4577]
### Describe the feature

I just wanted to know how fast a update is planned when 1.21 will be released.
Could someone give me a quick overview how updates for new MC versions are done?
I gladly would help developing.

Best,
Martin

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We don't give ETAs for updates.
It can be anywhere from a couple of days to a couple of weeks, depending on the scale of the changes.

**Comment by MrHello420** [comment]
Okay

> We don't give ETAs for updates. It can be anywhere from a couple of days to a couple of weeks, depending on the scale of the changes.

Okay of course that is understandable.
What has to be done with a version update?
I guess we have to make sure the codebase is compatible with the new fabric version. What else is there?
As I said, I will help as soon the updates gets released.

**Comment by Lapinoub** [comment]
I don't know 1.20.6 was within a few days but then again it is a snapshot and not a full version but still (I can't give official answers as I am not part of the dev team).

**Comment by MrHello420** [comment]
> I don't know 1.20.6 was within a few days but then again it is a snapshot and not a full version but still (I can't give official answers as I am not part of the dev team).

Ok thanks for the info. Because 1.21 will be a major update and will bring one of the most powerful new blocks (the crafter) I hope that Meteor will update as soon as possible.

Because I want to help to do this, can someone tell me how the process to update to a new version went in the past?

**Comment by Big-Iron-Cheems** [comment]
If you're curious about how we do version updates, I suggest you look at some [update PRs](https://github.com/MeteorDevelopment/meteor-client/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+author%3ABig-Iron-Cheems+update) I made.
I won't explain all the steps since it's a relatively long process, and I believe looking at the commits should give an idea of the flow.

**Comment by MrHello420** [comment]
Okay thanks for the hint. I will have a look.
