### ISSUE TITLE
1.20.6 Better Tooltips Crash with ViaVersion

### ISSUE THREAD

**Issue by Xenapte** [MeteorDevelopment/meteor-client#4578]
### Steps to reproduce

1. Install ViaFabric or ViaFabricPlus
2. Enable Better Tooltips Module and tick Banners
3. Open a container with custom banners
4. Crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/kse1tdA

### Meteor Version

Meteor 0.5.7-2078

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
https://github.com/ViaVersion/ViaFabricPlus/issues/405#issuecomment-2103214753 see this for a fix for the underlying issue
