### ISSUE TITLE
meteor crashs with no mods just meteor and fabric api 1.20.4

### ISSUE THREAD

**Issue by minekraftgamer** [MeteorDevelopment/meteor-client#4579]
### Steps to reproduce

1.put meteor and fabric api in mods
2.launch the game

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/78O1US2

### Meteor Version

Meteor 0.5.6

### Minecraft Version

MC 1.20.4

### Operating System

macOS

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
tlauncher is not supported

**Comment by minekraftgamer** [comment]
tl legacy

**Comment by Big-Iron-Cheems** [comment]
Same thing, as said in the FAQ we don't support cracked launchers. This crash is only caused by them.
