### ISSUE TITLE
[Linux] Cannot bind to "special" keys (left-control, left-alt)

### ISSUE THREAD

**Issue by Neon-44** [MeteorDevelopment/meteor-client#4581]
### Describe the bug

I am unable to bind modules to keys such as left-control. It doesn't matter if the key is bound in the Settings or not, it just doesn't want to bind. Other keys include: tab, left-shift, left-alt

### Steps to reproduce

1. install and launch
2. Try to bind to "special" key

### Meteor Version

Meteor 0.5.6

### Minecraft Version

Mc 1.20.4

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by arlomcwalter** [comment]
works fine for me
![screenshot](https://github.com/MeteorDevelopment/meteor-client/assets/17166139/6463649e-cf68-4c3f-8bef-21d3025b5a26)

**Comment by Neon-44** [comment]
i just tried it again and it really doesn't work for me.

But i realized that i can add combos (left-shift + l, left-alt + a)

maybe that helps pinpointng the Problem?

are you also on the last version? It used to work for me as well on 0.5.4, before i had to reinstall it and installed 0.5.6.

**Comment by Wide-Cat** [comment]
Afraid that I cannot reproduce this issue either. Maybe it is somehow a linux issue? It seems a bit unlikely but it's the only discrepancy you have pointed out for the time being. What other mods are you using?

**Comment by Wide-Cat** [comment]
Has been confirmed as an issue with linux.

**Comment by Neon-44** [comment]
i found my old jar in my wastebasket. It was 0.5.6-2019. i reinstalled it, and i was again able to bind left-ctrl, left-shift, left-alt etc. It seems it really is a Problem in a new update.

Hope this helps to pinpoint it! i will just continue playing with 0.5.6-2019 in the meantime :)

**Comment by 19MisterX98** [comment]
On linux this [check](https://github.com/MeteorDevelopment/meteor-client/blob/fa00a6da7847e1e644d6d15d2326738d1a9135a0/src/main/java/meteordevelopment/meteorclient/utils/misc/Keybind.java#L78) fails.
when releasing the left control key for example:
the modifier is still 2 indicating that control is pressed and the key is obv a modifier key.
windows might not emit the modifier on the release of the modifier key?

**Comment by Neon-44** [comment]
🥳 thank you, @MineGame159 🎉
