### ISSUE TITLE
[Suggestion] skibidi toilet minion hud

### ISSUE THREAD

**Issue by zetnik88** [MeteorDevelopment/meteor-client#4582]
### Describe the feature

the title says it all

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by zetnik88** [comment]
heres how he look like
![image](https://github.com/MeteorDevelopment/meteor-client/assets/167034173/3c17f560-48d0-4931-9463-d923f9f43efa)

**Comment by Pixel556** [comment]
wtf
