### ISSUE TITLE
Crash on Launch (mixin apply failed)

### ISSUE THREAD

**Issue by s-downpour** [MeteorDevelopment/meteor-client#4586]
### Steps to reproduce

1. Launch the game.
2. Crash.

There is a similar error in #4571, but seems to be for different reasons.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/ITC37XK

### Meteor Version

Meteor 0.56

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
MeteorPlus issue, they need to update their mixins. An issue is already open on their repo: https://github.com/Nekiplay/MeteorPlus/issues/122
