### ISSUE TITLE
[win] [Crush] sodium + indium + meteor 

### ISSUE THREAD

**Issue by Foxylol121** [MeteorDevelopment/meteor-client#4587]
### Steps to reproduce

Installed sodium-fabric-0.5.8+mc1.20.1 ,indium-1.0.30+mc1.20.4 ,supplementaries-1.20-2.8.10-fabric.jar ,moonlight-1.20-2.11.12-fabric ,meteor-client-0.5.4-1.20.1 . And they somehow conflict.
I can be in the game menu. When logging into a server or entering a single player game it crashes.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/dDtADo9

### Meteor Version

meteor-client-0.5.4-1.20.1

### Minecraft Version

MC Fabric  1.20.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
1. 1.20.1 is no longer supported 
2. Use Sodium 0.5.3 to fix this (downgrade Iris if necessary as well)

**Comment by Foxylol121** [comment]
Thx .fixed
