### ISSUE TITLE
[win] [crush] meteor 0.5.6

### ISSUE THREAD

**Issue by Foxylol121** [MeteorDevelopment/meteor-client#4589]
### Steps to reproduce

1.installed meteor-client-0.5.6-1996.jar ,fabric-api-0.92.1+1.20.4.jar
2. Launch
3.Crush

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/LTgf1bO

### Meteor Version

meteor-client-0.5.6-1996.jar

### Minecraft Version

MC Fabric  1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Cracked launcher issue. Buy the game.
