### ISSUE TITLE
[Suggestion] InfiniteAura

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#459]
**Describe the feature**
This would be killaura / multiaura with a way higher range. It bypasses on vanilla servers and is very useful for fucking around or straight up pvping. I'm sick of using monero miners for infinite aura (you know what I mean)

**Additional info**
Add any other info.
Options:
- Targets (how many players to target at once)
- All regular killaura options, range (10 - 150 blocks or whatever), cps (and smart delay obv), mode (bypass pog?)
- Visuals (the visual lines you see on many infiniteaura modules), also an esp that shows who you're targeting maybe.

**Comment by seasnail8169** [comment]
I have no idea what this does/how it works, can you provide some more information or a video?

**Comment by GildedS** [comment]
Smegma module moment

**Comment by Cypphi** [comment]
> I have no idea what this does/how it works, can you provide some more information or a video?

Oh sure, It's basically killaura, but since extreme reach doesn't work there's some wonky method that allows you to hit players from hundreds of blocks. It's kinda made for 1.8 but also works on 1.16 although you often get tped towards the player you're hitting.

https://www.youtube.com/watch?v=YQH2bZuCLBc (ignore the monero miner, and timestamp is 0:30)
https://www.youtube.com/watch?v=0KY-C6_mThA (time stamp 1;00) (another monero miner clip, i couldnt find anything else)

**Comment by NathanKassab** [comment]
You should really have a basic understanding on how something works before suggesting it. But for those who don't know infinite aura sends lots of movement packets to teleport the player next to the target, hit them and teleport back. You need to know pathfinding to make it and it's useless on any server with an anticheat
