### ISSUE TITLE
Meteor client crashing with Liquid Bounce Nextgen

### ISSUE THREAD

**Issue by CheeseEater3000Turbo** [MeteorDevelopment/meteor-client#4590]
### Steps to reproduce

1. Download Meteor client (1.20.4 or 1.20.6)
2. Download Liquid Bounce (same)
3. Download Fabric Language Kotlin (same)
4. Play game! (Expect crash without fabric error)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Maq222L

### Meteor Version

meteor-client-0.5.6

### Minecraft Version

1.20.4 and 1.20.6

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
The crash clearly says that you're trying to run LiquidBounce 1.20.4 on 1.20.6, so not a meteor issue

**Comment by Big-Iron-Cheems** [comment]
Also I have no idea why you have installed several versions of ViaFabricPlus.
You don't seem to understand how to use it.

**Comment by CheeseEater3000Turbo** [comment]
> Also I have no idea why you have installed several versions of ViaFabricPlus. You don't seem to understand how to use it.

I tried the 1.20.6 and 1.20.4 which was exacly downloaded from official website.

**Comment by Wide-Cat** [comment]
The latest dev build of meteor will work with liquid bounce, but meteor doesn't work on tlauncher.

**Comment by CheeseEater3000Turbo** [comment]
> e latest dev build of meteor will work with liquid bounce, but meteor doesn't work on tlauncher.

Will it be this fixed in the future? or any better launchers?

**Comment by tympanicblock61** [comment]
> > e latest dev build of meteor will work with liquid bounce, but meteor doesn't work on tlauncher.
> 
> Will it be this fixed in the future? or any better launchers?

They will not fix this
