### ISSUE TITLE
[Suggestion]   New suggestion

### ISSUE THREAD

**Issue by 2OnHard** [MeteorDevelopment/meteor-client#4592]
### Describe the feature

you guys should add like the thing that lunar client and stuff has that next to other peoples name whos using the client is the logo you guys should do that for meteor to have a little meteor next to therfe name

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We had that long ago, but it was removed because people were stupid enough to keep it on and joining non-anarchy servers (and getting rightfully banned).
