### ISSUE TITLE
Server Spoof and Packet Canceller do not work as expected

### ISSUE THREAD

**Issue by CyberFoxar** [MeteorDevelopment/meteor-client#4593]
### Describe the bug

When using the "Server Spoof" module, the client still sends unmodified packets to the server.
On the same vein, the "Packet Canceller" module does not block any kind of packets. 

This seems to stems from an incorrect pointcut/mixin usage around the `ClientConnectionMixin`. Looking over at what Wurst does (which does not have this issue), they seem to do doing their injection a bit differently than how meteor does. [Here's the file in question on their repo.](https://github.com/Wurst-Imperium/Wurst7/blob/master/src/main/java/net/wurstclient/mixin/ClientConnectionMixin.java) -- Though, as of Wurst 7.42, it does not seem to work either.

Sadly, my java-fu is not high enough to suggest a fix, but I can point out this.

### Steps to reproduce

1. Install Meteor client
2. Install any kind of mod that send stuff on the `minecraft:register` channel. Mods like VoxelMap and Controlify are good candidates.
3. Add a MitM proxy to examine in/out packets, for example [pakkit](https://github.com/Heath123/pakkit)
4. Launch minecraft, on main menu and either:
  - Enable Packet Canceller and block C2S packet: CustomPayloadC2SPacket
  - Enable Server Spoof and enable channel block with the default `minecraft:register` value
 5. Connect to any server using the MitM proxy
 6. Observe that CustomPayloadC2SPackets are still sent and that they even have the `minecraft:register` channel.

### Meteor Version

0.5.7-2079

### Minecraft Version

MC 1.20.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by 19MisterX98** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/41451155/ded2e75a-4c37-4e1f-85ff-859ef1122e6c)
meteor injects send events in the upper method while wurst injects in the lower one.

fabrics networking lib calls the lower method and therefore bypasses the event system in meteor.
I'll fix it

**Comment by CyberFoxar** [comment]
Fast ! I'll check it out when the dev build comes out.

**Comment by Wide-Cat** [comment]
Shoutout to @19MisterX98

**Comment by CyberFoxar** [comment]
Weirdly enough, it still seems to happen with version 0.5.7-2079. 
Having a MitM proxy and Controlify and packetCanceller or server spoof active... does not work.

I mean, server spoof does correctly report `minecraft:brand` as `vanilla` but it does not block `mincraft:register` channels, or any kind of channels for that matter.

Packet Canceller does not seems to cancel any packets either.

**Comment by CyberFoxar** [comment]
Nevermind, I was using an old build. It's working as expected now !
