### ISSUE TITLE
Compatability with Featherclient

### ISSUE THREAD

**Issue by DaRealMFer** [MeteorDevelopment/meteor-client#4596]
### Describe the feature

Please add compatability with Featherclient or if it already is tell me how and what version.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Feather is closed source, we don't care to achieve compatibility with a launcher whose code we can't see.
