### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by m4kii420** [MeteorDevelopment/meteor-client#4604]
### Describe the feature

Idk is it possible but it would be nice to have a feature to save items on server and load them in singleplayer.
Maybe a "fake creative" that lets you save hotbar even if you are in survival

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
You can try using the .gamemode command for this purpose, I think it should work. It fakes your gamemode clientside.

**Comment by m4kii420** [comment]
it doesn't work
