### ISSUE TITLE
Crashing on newer Java version.

### ISSUE THREAD

**Issue by CookieXD** [MeteorDevelopment/meteor-client#461]
I am using Java version JDK 16.0.0.36 and it crashes on every start.
[crash-2021-04-10_16.20.20-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6289995/crash-2021-04-10_16.20.20-client.txt)

This java version works with vanilla and fabric.
It is a lot faster on my computer.

**Comment by MineGame159** [comment]
This has been fixed in latest dev builds.
