### ISSUE TITLE
Add option to use TOR as proxy

### ISSUE THREAD

**Issue by TheOne-Player** [MeteorDevelopment/meteor-client#4613]
### Describe the feature

Most of the users aren't able to find reliable proxies with good proxies with a relatively high uptime. So to make it easier for the users, an option can be added to use TOR as a proxy.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Does TOR work as a SOCKS proxy? Can you send any documentation related to using it as such? Unless there's some further steps TOR requires you to take, if you have the ip address and port you should be able to use it as is.

**Comment by TheOne-Player** [comment]
It does, after starting tor browser, you can use tor as socks5 proxy on the ip: localhost:9150

**Comment by TheOne-Player** [comment]
You can enter it manually, but most of the players don't know about this, and end up with non-functional proxies that they found on google. Adding a tor proxy button will make using proxies much more easier.

**Comment by Talhoid** [comment]
afaik there are no tor server implementations in java so the user would need to set up their own tor proxy or we could bundle tor with meteor client. this is not ideal. i think we can close this issue for now

**Comment by Wide-Cat** [comment]
After discussing this a couple weeks ago I dont think adding feature to use tor as a proxy en-masse would be particularly healthy for the tor ecosystem, plus the latency would be extremely high.
