### ISSUE TITLE
Crashing when starting client

### ISSUE THREAD

**Issue by Le-Khuong** [MeteorDevelopment/meteor-client#4614]
### Steps to reproduce

it just crash when i start the legacy lauchr client

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/wjJCrIl

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

macOS

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Most probably a cracked launcher issue.
Buy the game and use one of the supported launchers.

Reopen in case you're not using a cracked launcher.
