### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by szklu090** [MeteorDevelopment/meteor-client#4615]
### Describe the feature

Hello, I have an error, I can't write anything on the public dc server

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This place is used for software related issues with Meteor as a mod.
You should [inform yourself](https://meteorclient.com/faq/#why-can%E2%80%99t-i-talk-in-the-meteor-discord?) before abusing the GitHub issues section.
