### ISSUE TITLE
Crash in Mod Menu

### ISSUE THREAD

**Issue by ryoosukran** [MeteorDevelopment/meteor-client#4616]
### Steps to reproduce

1.Open Tlauncher
2. Open Mod Menu
3. Crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/sRrSM73

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Cracked launcher issue. Buy the game and use a supported launcher.

**Comment by ryoosukran** [comment]
okay, thankyou so much
