### ISSUE TITLE
fly bypass

### ISSUE THREAD

**Issue by airtatic** [MeteorDevelopment/meteor-client#4617]
### Describe the feature

I found out that flying in servers with anticheats don't work like vulcan but you can do .vclip commands to bypass it. I was wondering if you could combine those and make a fly bypass

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 19MisterX98** [comment]
vclipping just flags you. Doing it lots of times will kick/ban you
