### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by DDLOsf** [MeteorDevelopment/meteor-client#4627]
### Describe the feature

maybe get this to work with Tlauncher cracked minecraft i’ve tested it a few times can’t get it to work please try make it work

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Duplicate issue, we don't plan on supporting cracked launchers, buy the game.
