### ISSUE TITLE
add a 1.8.9 version

### ISSUE THREAD

**Issue by PP09PetyaDecryptor** [MeteorDevelopment/meteor-client#4628]
### Describe the bug

Please😍😍😍😍😍😍😍

### Steps to reproduce

1.1.1.1.1.1.

### Meteor Version

1.8.9 add

### Minecraft Version

1.8.9 add

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by PP09PetyaDecryptor** [comment]
thanks

**Comment by NanometersNotMeters** [comment]
big iron is so patient
