### ISSUE TITLE
[Suggestion] A way to make possible to view shulkers besides typing .peek 

### ISSUE THREAD

**Issue by 2OnHard** [MeteorDevelopment/meteor-client#4629]
### Describe the feature

like maybe having a way to bind it or making a module of .peek in the client cause .peek is quick but i dont like it

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/1487617c-7096-4735-9aca-7d1397d729c4)
Is this not a feature already offered by the `BetterTooltips` module?
Reopen the issue if this is not what you meant.
