### ISSUE TITLE
how do i set up a proxy 

### ISSUE THREAD

**Issue by C0smicc001** [MeteorDevelopment/meteor-client#4643]
### Describe the bug

i need help making a proxy or importing one for meteor client, i jsut dont know how lol, please help

### Steps to reproduce

1. im dumb 
2. please help

### Meteor Version

0.5.7

### Minecraft Version

1.20.5

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
This place is to report issues with Meteor, please don't use it for something unrelated.

You can get an answer straight from [Google](https://duckduckgo.com/?q=how+to+setup+a+proxy&t=fpas&ia=web).
