### ISSUE TITLE
Show Freecam Coordinates

### ISSUE THREAD

**Issue by brentspine** [MeteorDevelopment/meteor-client#4645]
### Describe the feature

My suggestion is, that you should be able to see the coordinates of your freecam, either in F3 or some other GUI overlay. For example Wurst does it. It helps with for example configuring Baritone. 

Example:

Manipulate the coordinates marked in red (and potentially the looking at block/fluid section).
![image](https://github.com/MeteorDevelopment/meteor-client/assets/55391576/442e148b-7510-49ac-be0e-46ca45ee52c1)

or

Add a GUI overlay for displaying the coords seperately
![image](https://github.com/MeteorDevelopment/meteor-client/assets/55391576/e8d2b9b5-b4c3-4df1-8b43-7653dc55e8ac)

While having options to toggle coordinate manipulation (Screenshot 1) or the coordinate overlay (Screenshot 2)

![image](https://github.com/MeteorDevelopment/meteor-client/assets/55391576/2cd86fbd-2968-4ced-9a9d-a28ad35b7f98)

(As briefly described in issue #2098)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 19MisterX98** [comment]
enable the hud. Hud coords are the coords of your camera so they will change in freecam.
see bottom right:
![2024-06-14_19 11 09](https://github.com/MeteorDevelopment/meteor-client/assets/41451155/66dcafd4-6bfb-45de-a118-0d8c7ef726fc)

**Comment by brentspine** [comment]
Oh, I didn't know that, thanks!
