### ISSUE TITLE
[Suggestion] Display of health and name of the person close to u

### ISSUE THREAD

**Issue by elre2** [MeteorDevelopment/meteor-client#4649]
### Describe the feature

When fighting someone there will be a little tab that shows their health name and face
![meteor sugg](https://github.com/MeteorDevelopment/meteor-client/assets/172983002/5175e53f-f4ed-4d94-a66e-13fccbe7fd53)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
the combat hud element
