### ISSUE TITLE
help in servers

### ISSUE THREAD

**Issue by Jaggik8888** [MeteorDevelopment/meteor-client#4652]
### Describe the feature

which hack or modules are completely usable in servers with anticheat plugin

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Xargana** [comment]
mostly anything that works server-side
