### ISSUE TITLE
Something went Wrong

### ISSUE THREAD

**Issue by TaoThao415** [MeteorDevelopment/meteor-client#4656]
### Describe the feature

I dont know why i cant join the game
![image](https://github.com/MeteorDevelopment/meteor-client/assets/173163326/9e3907c1-b8f7-4547-a0af-71c3f4b2e870)
![image](https://github.com/MeteorDevelopment/meteor-client/assets/173163326/fe151eaa-1680-4c2e-a7df-0055b31d6f86)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
send the crash report

**Comment by TaoThao415** [comment]
> send the crash report

Crash report ?

**Comment by Wide-Cat** [comment]
.minecraft/logs, upload the latest.log to https://mclo.gs and send it here

**Comment by TaoThao415** [comment]
> .minecraft/logs, upload the latest.log to https://mclo.gs and send it here

what next

**Comment by Big-Iron-Cheems** [comment]
1. You didn't send the link to the log here :neutral_face: 
2. You're using a cracked launcher, and I can assure you that is causing the crash.
