### ISSUE TITLE
How do i use the client with feather client

### ISSUE THREAD

**Issue by developers-fun** [MeteorDevelopment/meteor-client#4657]
### Describe the bug

idk

### Steps to reproduce

idk

### Meteor Version

Meteor 1.20.6

### Minecraft Version

MC 1.20.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
you cant
