### ISSUE TITLE
What launcher do i use

### ISSUE THREAD

**Issue by developers-fun** [MeteorDevelopment/meteor-client#4658]
### Describe the bug

idk

### Steps to reproduce

idk

### Meteor Version

Meteor 1.20.6/4

### Minecraft Version

MC 1.20.6/4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Please stop abusing the issues page.
This is to report software issues, not spoonfeed you easily available info from our [website](https://meteorclient.com/faq/installation/#installing).
