### ISSUE TITLE
.inventory not working with custom names with §'s

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#466]
**Describe the bug**
issue with .inventory; typing their regular name does not work either.

**To Reproduce**
.inventory {custom name}

**Expected behavior**
no

**Screenshots**
no

**Additional context**
meteor 0.42

**Comment by Cypphi** [comment]
Does & also not work? Servers often use & instead of that other symbol due to minecraft not recognizing it. § is only meant to be used in config files etc.

**Comment by C10udburst** [comment]
I think it was fixed in #302 .

**Comment by seasnail8169** [comment]
yeah
