### ISSUE TITLE
[Suggestion] Add tab on website for ease of access to older versions

### ISSUE THREAD

**Issue by Bioshot122** [MeteorDevelopment/meteor-client#4662]
### Describe the feature

![image](https://github.com/MeteorDevelopment/meteor-client/assets/173299854/dd08dc2f-f125-4835-ad7c-e368c6316557)

something similar to this bar would make meteor massively easier to use on previous versions.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Xargana** [comment]
this is so gonna get rejected

**Comment by Big-Iron-Cheems** [comment]
Not goingto repeat myself:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/6c8c85cc-a5fc-47de-a868-95b738090123)
