### ISSUE TITLE
make a newer version of meteor client 

### ISSUE THREAD

**Issue by LEGO202434** [MeteorDevelopment/meteor-client#4665]
### Describe the feature

make a 1.21 version for the new update

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by moxvallix** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/17493061/52c8e155-8075-4f6b-b3af-16c31093edf5)

**Comment by Xargana** [comment]
this is so crazy

**Comment by Big-Iron-Cheems** [comment]
Really pretentious of you to say that. People should learn to be patient and respectful towards those that offer a free service.

Meanwhile, you can track the update progress at [this](https://github.com/MeteorDevelopment/meteor-client/pull/4640) PR.
