### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Mariobros2019** [MeteorDevelopment/meteor-client#4667]
### Describe the feature

Make an update that works with 1.21 because my son is threating me of punching me in the night before 22/06/2024

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Please do not abuse the issues page.

This is to report software issues, not asking people to work faster on a free product.
Be patient and wait like everyone else.

**Comment by RealMuffinTime** [comment]
But his son will be punching.
