### ISSUE TITLE
[Suggestion] how to mine this ore (baritone)

### ISSUE THREAD

**Issue by Astyc1** [MeteorDevelopment/meteor-client#4668]
### Describe the feature

![2024-06-21_15 57 05](https://github.com/MeteorDevelopment/meteor-client/assets/173470294/a02dfc77-1956-45ff-b7c0-b123f0cc31b4)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
1. This has nothing to do with Meteor, Baritone is an independant project.
2. Use the `#mine` command with the corresponding block name.

Please use the support channel in the Baritone discord next time.

**Comment by Astyc1** [comment]
thx
