### ISSUE TITLE
Crash even before main game instance init

### ISSUE THREAD

**Issue by GNUser224** [MeteorDevelopment/meteor-client#4670]
### Steps to reproduce

Welp, everything in logs

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/InB1wcE

### Meteor Version

meteor-client-0.5.6

### Minecraft Version

Minecraft 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Cracked launcher issue.
Buy the game and use one of the supported launchers listed in our FAQ.
