### ISSUE TITLE
Nuker crashes the game when trying to mine a falling block

### ISSUE THREAD

**Issue by Xargana** [MeteorDevelopment/meteor-client#4671]
### Steps to reproduce

1. Use nuker to break any kind of falling block

The problem seems to be caused by Meteor and Axiom being incompatible, Cannot reproduce on latest dev build because of another compatibility  issue, crashing the game when joining servers/singleplayer worlds.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/HBxu6RL

### Meteor Version

Meteor 0.5.6-2031 / Meteor 0.5.7-2109

### Minecraft Version

Minecraft 1.20.4 Fabric 0.15.7 / Minecraft 1.20.6 Fabric 0.15.11

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Xargana** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/84742364/b340821d-d496-46fe-8cb2-469f73e0ff65)

**Comment by MineGame159** [comment]
Sorry but I can't replicate the crash. If you still experience the crash then provide more detailed instructions on how to replicate it
