### ISSUE TITLE
NameTag hasnot correct location in 1.21

### ISSUE THREAD

**Issue by wupengabc** [MeteorDevelopment/meteor-client#4672]
### Describe the bug

NameTag hasnot correct location
but it is correct when i press F1
this is video https://drive.google.com/file/d/1RD0Fd1DOUd_KIUJ7GLu45qa_SQAN_zDL/view?usp=drive_link

### Steps to reproduce

NameTag has correct location

### Meteor Version

Meteor 0.5.7

### Minecraft Version

MC 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
#333
