### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NetworkCicada** [MeteorDevelopment/meteor-client#4673]
### Describe the bug

So the Baritone Fork just instant crashes but only for me... a friend and i have the exact same mods and stuff but for some reason it wont work for me (we only use meteor 1.20.6 and the baritone build with addition to some meteor addons which r tho not the cause of this) even without anythin it just wont work and i couldnt figure out why

### Steps to reproduce

1. But the 1.20.6 Dev Build of Meteor client and Baritone in ur 1.20.6 fabric profile in the Minecraft Launcher
2. start game
3. use command like #goto nether_portal 
4. crash.

### Meteor Version

1.20.6 Dev Build

### Minecraft Version

Fabric 1.20.6- 0.15.11

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
1. You used the wrong issue template. If you have a crash, use the crash template.
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/b2a1c315-3c1a-4d26-92f1-52ccec390d3c)
2. If you're experiencing a crash, upload it to https://mclo.gs/ and paste the generated link here.
