### ISSUE TITLE
Baritone Crashes Upon using it

### ISSUE THREAD

**Issue by NetworkCicada** [MeteorDevelopment/meteor-client#4674]
### Steps to reproduce

1. Put baritone and Meteor in ur Mods folder on minecraft launcher and yea

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/TH0wHhb

### Meteor Version

1.20.6 Dev Build

### Minecraft Version

Fabric 1.20.6- 0.15.11

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/5ce07629-f639-4c7f-9f21-92ccbdbeecb8)
Suggestion from an older issue in the Baritone GitHub.
Try it via the Baritone tab in the main menu and see if it helps.

**Comment by NetworkCicada** [comment]
Accept my endless gratitude.
