### ISSUE TITLE
[Bug]  XRAY

### ISSUE THREAD

**Issue by iZerxx** [MeteorDevelopment/meteor-client#4677]
### Describe the bug

When you activate the xray the game closes automatically and when you get back into the world it closes again

### Steps to reproduce

1. I put xray
2. and the game closed

### Meteor Version

1.21

### Minecraft Version

fabric loader 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Install sodium to temporarily fix it
