### ISSUE TITLE
Unable to launch minecraft fabric with meteor client in mods folder

### ISSUE THREAD

**Issue by BogmanElite** [MeteorDevelopment/meteor-client#4678]
### Steps to reproduce

Put the meteor client.jar in the mods folder
Then start minecraft whit fabric

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/TgomSv9

### Meteor Version

1.20.6

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
This crash is caused by cracked launchers like TLauncher and others.
Please buy the game, use a supported launcher and try agin.

Reopen this issue if you're not using a cracked launcher.
