### ISSUE TITLE
a search hack

### ISSUE THREAD

**Issue by LEGO202434** [MeteorDevelopment/meteor-client#4679]
### Describe the feature

this hack is about finding blocks that you want if you want deepslate diamond ore you put it in the search and that tipes of blocks are a color that you chose and you can see them through walls it is like storage Esp but for all the blocks

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This already exists, it's called Block ESP.
