### ISSUE TITLE
[Bug] Hue picker goes outside of color picker box

### ISSUE THREAD

**Issue by ikeafridge4** [MeteorDevelopment/meteor-client#468]
**Describe the bug**
The little dot that you drag around to pick hues goes outside of the box

**To Reproduce**
1. Right click on any module with color picker thing idk what the actual name is
2. Click on the color thing to change the color.
3. move the hue picker dot to the right, as far as it will go.

**Expected behavior**
Should stay within the color picker box (again idk what the actual name is)

**Screenshots**
![Screenshot 2021-04-10 135241](https://user-images.githubusercontent.com/78064813/114284489-2c14b280-9a05-11eb-9277-259d02dbfc5f.png)

**Additional context**
Meteor client dev build 718, 1.16.5
Mods:
baritone-api-fabric-163.jar
dark-loading-screen-1.5.0.jar
fabric-api-0.32.0+1.16.jar
lithium-fabric-mc1.16.5-0.6.4.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar
meteor-client-0.4.2-718.jar
modmenu-1.16.8.jar
multiconnect-1.3.34.jar
notenoughcrashes-3.1.8-fabric.jar
phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
raisedclouds-1.0.0.jar
sodium-extra-0.2.2.jar
sodium-fabric-mc1.16.3-0.1.0.jar

**Comment by MineGame159** [comment]
@ikeafridge4 what OS are you using?

**Comment by ikeafridge4** [comment]
> @ikeafridge4 what OS are you using?

im using windows 10 pro

**Comment by RedCarlos26** [comment]
I cannot reproduce.

**Comment by ikeafridge4** [comment]
doesnt happen anymore in 0.4.3
