### ISSUE TITLE
2 bugs 1.21 dev

### ISSUE THREAD

**Issue by UnderQuestion** [MeteorDevelopment/meteor-client#4680]
### Describe the bug

1)esp problem: hostiles use water animal color, water animals use hostile color
2)cant create cracked account

### Steps to reproduce

idk

### Meteor Version

2112 dev

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
1. Cannot reproduce the ESP issue
![2024-06-25_13 38 18](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/5cbf15bd-e26a-4c1e-863f-b64b214dd9b9)
2. Cannot reproduce the account issue
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/e0e6be81-1f89-4c94-b75e-bb19e3625c20)

**Comment by Big-Iron-Cheems** [comment]
Note: the ESP bug only happens with Sodium, we're working on a fix, no ETA.

**Comment by UnderQuestion** [comment]
lol but i cant still create a cracked account
