### ISSUE TITLE
1.21 not downloading

### ISSUE THREAD

**Issue by leopcxco** [MeteorDevelopment/meteor-client#4681]
### Describe the bug

1.21 dosent download for me, its stuck at 5 seconds.

### Steps to reproduce

Anytime i try to download it

### Meteor Version

1.21

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Xargana** [comment]
internet issue probably, also the site is down for some specific browsers so that might be causing an issue so you might want to try again later
