### ISSUE TITLE
HUGE BUG WEBSITE IS DOWN

### ISSUE THREAD

**Issue by Loopo6534** [MeteorDevelopment/meteor-client#4682]
### Describe the bug

The website doesn't work at all it doesn't even look the same

### Steps to reproduce

opened the website

### Meteor Version

N/A

### Minecraft Version

N/A

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Isaihacksschoollaptops** [comment]
The domain expired they have to renew again
