### ISSUE TITLE
WEBSITE DOWN!! DOMAIN EXPIRED

### ISSUE THREAD

**Issue by consore** [MeteorDevelopment/meteor-client#4684]
### Describe the bug

Website goes to a blank page. Domain has expired and there is no longer a download page or anything for that fact. Just one of these:
![image](https://github.com/MeteorDevelopment/meteor-client/assets/93456830/09db7b9e-591e-4966-b7aa-86fc6bc7497d)

### Steps to reproduce

Go to https://meteorclient.com/[anything or just leave blank]

### Meteor Version

N/A

### Minecraft Version

N/A

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by S1lvan7** [comment]
The site doesn't work on mac nor linux, so Probably one of their servers shut down, if anyone else has a better explanation please go ahead
