### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by purpsyrz** [MeteorDevelopment/meteor-client#4687]
### Describe the bug

whenever i turn on x-ray it crashes my game 

### Steps to reproduce

1. i went to turn on x ray and when i tunred it on it crashed my game

### Meteor Version

1.21

### Minecraft Version

1,21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Known issue. Install sodium to temporarily fix it.

**Comment by purpsyrz** [comment]
whats sodium?

**Comment by Big-Iron-Cheems** [comment]
Google is a really helpful tool: [Sodium for Fabric 1.21](https://modrinth.com/mod/sodium/versions?g=1.21)
