### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by JianOlethros** [MeteorDevelopment/meteor-client#4689]
### Steps to reproduce

1. Launch (I use legacy launcher)
2. Crashed

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/4x9igPD

### Meteor Version

Meteor 0.5.8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by tympanicblock61** [comment]
viafabricplus crash not meteor

**Comment by JianOlethros** [comment]
> viafabricplus crash not meteor

Nope, Removed viafabricplus and still crashed. Log - (https://mclo.gs/UqiDfmA)

**Comment by Big-Iron-Cheems** [comment]
This is a cracked launcher issue, buy the game and use a supported launcher as explained in our FAQ.
There's nothing we can do on our end to fix this.
