### ISSUE TITLE
cant attack

### ISSUE THREAD

**Issue by kittenvr** [MeteorDevelopment/meteor-client#4691]
### Describe the bug

when i try to attack with meteor it fails
https://streamable.com/0j2bwf

### Steps to reproduce

1. join server
2. try to attack

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
send an image of your active modules

**Comment by kittenvr** [comment]
> send an image of your active modules

they dont fit on my screen

**Comment by MineGame159** [comment]
We can't reproduce your issue and you have not provided any instructions on how to replicate it. It might be a compatibility issue with some other mod you are using, it might only happen on that particular server you are playing, etc. If you can provide more information then we can re-open the issue.

**Comment by kittenvr** [comment]
im on  a 1.19.2 server using viafabricplus

**Comment by MineGame159** [comment]
Can you first confirm if it happens without viafabricplus? On a different server.
