### ISSUE TITLE
Crashes game when typing

### ISSUE THREAD

**Issue by Earth1283** [MeteorDevelopment/meteor-client#4692]
### Steps to reproduce

1. Go in creative
2. You go to something other than the search tab
3. As soon as you click on the search tab, begin typing
4. the game crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/l0nfEke

### Meteor Version

0.5.8

### Minecraft Version

MC 1.21

### Operating System

macOS

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by cpj6789** [comment]
I have the same issue, dev build #2119 on Windows.
