### ISSUE TITLE
When turning x-ray on 1.21 version of Minecraft it crashes the game.

### ISSUE THREAD

**Issue by LandSharkBubR** [MeteorDevelopment/meteor-client#4693]
### Describe the bug

The x-ray feature on Meteor Client does not work, it crashes my game when turning on this feature.
It should be updated so Meteor doesn't crash my game.

Thanks in advance- LandSharkBub

### Steps to reproduce

I enabled x-ray, looked around for a second or less, then it crashes Minecraft.

### Meteor Version

Meteor Dev Build 0.5.8

### Minecraft Version

MC 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Known issue, Installing [Sodium](https://modrinth.com/mod/sodium/versions?g=1.21) will fix this until we release a patch.

**Comment by MineGame159** [comment]
Fixed in cff4cf578c71691fc17bf4e50619975f0200f1fd
