### ISSUE TITLE
[Suggestion] - Villager / Librarian Trade Finder

### ISSUE THREAD

**Issue by unfallvoll** [MeteorDevelopment/meteor-client#4696]
### Describe the feature

Could you please add a bot who finds my wanted trades by selecting them in a config menu? Great Function and already usable in Wurst, but i love meteor and don´t wanna use wurst! There is no Mod with that feature on 1.21 yet (except for cheat clients like wurst).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This already exists as an [addon](https://github.com/maxsupermanhd/meteor-villager-roller), but it hasn't updated to 1.21 yet.
