### ISSUE TITLE
You should add back baritone to meteor client

### ISSUE THREAD

**Issue by Some10101** [MeteorDevelopment/meteor-client#4697]
### Describe the feature

It will help me baritone needs a ci build to work with meteor can you guys add it back?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Baritone can be downloaded separately, both on our [website](https://meteorclient.com/) (at the moment v1.20.6) or on Baritone's [GitHub](https://github.com/cabaletta/baritone).
The 1.21 version of Baritone is still not merged, but you can get it [here](https://github.com/cabaletta/baritone/actions/runs/9593797633/artifacts/1619776591).
