### ISSUE TITLE
[Suggestion] add back EntityAttributeHelper and StatusEffectHelper

### ISSUE THREAD

**Issue by kittenvr** [MeteorDevelopment/meteor-client#4698]
### Describe the feature

crosby told me they were removed but my addon uses it could you please add it back

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
They physically cannot be kept in as they are broken due to the changes Minecraft made.
Find your way around them like we did.

**Comment by kittenvr** [comment]
> They physically cannot be kept in as they are broken due to the changes Minecraft made.
> Find your way around them like we did.

Could you show some code where you did l?
