### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Tbadger1288** [MeteorDevelopment/meteor-client#4699]
### Describe the feature

1.20.1? possibly, if it has already had a version im so sorry 

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
https://meteorclient.com/faq/old-versions
