### ISSUE TITLE
Save and Load books

### ISSUE THREAD

**Issue by Errorcrafter** [MeteorDevelopment/meteor-client#47]
Add some buttons to the book writing GUI to allow saving and loading the contents of books. This could be used to make a lot of the same book quickly (if you wanted them all to be Originals), and i guess could just save and load bookbot books.

**Comment by dakone22** [comment]
@Errorcrafter, like this buttons in the left top corner? There are already.
![image](https://user-images.githubusercontent.com/35692622/101938855-2349d680-3bf5-11eb-8647-0efc9b023084.png)

**Comment by dakone22** [comment]
Some offtopic.
Did you know that you can create books using text formatting with **BookBot** in `file` mode? Like this:
![bookboot](https://user-images.githubusercontent.com/35692622/101941049-7ec99380-3bf8-11eb-93eb-014d4b63abaa.gif)
`book.txt`:
```
§o§n§l§1Cool §4Text §b§min§a §nMinecraft§6 Books§r

§l§kSomename
Some else text

§2aHR0cHM6Ly95b3V0dS5iZS9kUXc0dzlXZ1hjUQ==
```
[More about Minecraft formatting](https://minecraft.gamepedia.com/Formatting_codes)

**Comment by MineGame159** [comment]
Lol
