### ISSUE TITLE
[Bug] Nametags rendering above the player when not in free-cam.

### ISSUE THREAD

**Issue by MenacingEntity** [MeteorDevelopment/meteor-client#470]
**Nametags Rendering above the player while not in free-cam**
Usually nametags render when the player is in free-cam but the client renders the nametag when not in free-cam which is really annoying 

**Expected behavior**
I expect the nametag to render only when in free-cam.

**Screenshots**
![Nametag](https://user-images.githubusercontent.com/70501814/114278194-3d34e200-9a4c-11eb-8a47-75e7b2b221fd.png)

**Comment by seasnail8169** [comment]
I have absolutely no idea what you mean, nametags have always and will always render regardless of freecam.

**Comment by MenacingEntity** [comment]
Hey,
Iits rendering when you look up :( in the new dev builds.

**Comment by seasnail8169** [comment]
oh you mean on yourself

**Comment by MenacingEntity** [comment]
Yeah.
