### ISSUE TITLE
SuperMace

### ISSUE THREAD

**Issue by thestarontop** [MeteorDevelopment/meteor-client#4703]
### Describe the feature

/*
 * This file is part of the Meteor Client distribution (https://github.com/MeteorDevelopment/meteor-client).
 * Copyright (c) Meteor Development.
 */

package meteordevelopment.meteorclient.systems.modules.combat;

import meteordevelopment.meteorclient.events.entity.player.AttackEntityEvent;
import meteordevelopment.meteorclient.events.packets.PacketEvent;
import meteordevelopment.meteorclient.events.world.TickEvent;
import meteordevelopment.meteorclient.mixin.PlayerMoveC2SPacketAccessor;
import meteordevelopment.meteorclient.systems.modules.Categories;
import meteordevelopment.meteorclient.systems.modules.Module;
import meteordevelopment.meteorclient.utils.network.PacketUtils;
import meteordevelopment.orbit.EventHandler;
import net.minecraft.item.Items;
import net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket;

public class SuperMace extends Module{
    public SuperMace(){super(Categories.Combat,"SuperMace","improve your mace's damage");}
    @EventHandler
    public void onPacket(PacketEvent.Send event){
        if (event.packet instanceof PlayerMoveC2SPacket){
            PlayerMoveC2SPacketAccessor packet = (PlayerMoveC2SPacketAccessor) event.packet;
            packet.setOnGround(false);
        }
        if (event.packet instanceof PlayerInteractEntityC2SPacket){
            event.setCancelled(true);
            mc.getNetworkHandler().sendPacket(new PlayerMoveC2SPacket.LookAndOnGround.PositionAndOnGround(mc.player.getX(), mc.player.getY() + 10000000, mc.player.getZ(), false));
            mc.getNetworkHandler().sendPacket(new PlayerMoveC2SPacket.LookAndOnGround.PositionAndOnGround(mc.player.getX(), mc.player.getY(), mc.player.getZ(), false));
            event.setCancelled(false);
        }
    }
}

I don't know how to use pull requests, so I used this instead.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
skull emoji

**Comment by Earth1283** [comment]
did this guy just code it
