### ISSUE TITLE
Mace with Nofall

### ISSUE THREAD

**Issue by karbored** [MeteorDevelopment/meteor-client#4706]
### Describe the bug

Mace does not function with NoFall Enabled

### Steps to reproduce

Turn on NoFall
Use mace

### Meteor Version

Dev Build 1.21

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by tympanicblock61** [comment]
Yeah obviously

**Comment by tympanicblock61** [comment]
Not a bug

**Comment by Big-Iron-Cheems** [comment]
Obviously using `Packet` mode won't let you use the mace's fall damage mechanic.
It simulates you being at a safe distance from the ground to negate damage.
If the game thinks you're on the ground, you cannot use the mace's jump attack.

This is intended behaviour, not a bug.
