### ISSUE TITLE
BetterToolTips MidClick Open

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [MeteorDevelopment/meteor-client#4709]
### Describe the feature

In creative mode, the middle mouse button is used to duplicate items
Middle Click Open, on the other hand, will cause the Shulker Box interface to open instead of duplicating items when using the middle button

A KeySetting should be added to open the preview screen to avoid key conflicts

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
f33e87bf752715b768b536b08d23ff0f3efc9332
