### ISSUE TITLE
[Bug] ESP not working for Pufferfish, Tropical fish, Salmon, and Cod

### ISSUE THREAD

**Issue by MenacingEntity** [MeteorDevelopment/meteor-client#471]
**Describe the bug**
ESP not working for fish.

**Expected behavior**
ESP needs to work for all entities including Pufferfish, Tropical fish, Salmon, and Cod.

**Screenshots**
![Pufferfish](https://user-images.githubusercontent.com/70501814/114292713-0f808500-9aae-11eb-8452-45f6bd35a95d.png)
![Tropical Fish](https://user-images.githubusercontent.com/70501814/114292718-1909ed00-9aae-11eb-852d-f7b7da3479ce.png)
![Cod](https://user-images.githubusercontent.com/70501814/114292720-21fabe80-9aae-11eb-8521-19792e1b4efc.png)
![Salmon](https://user-images.githubusercontent.com/70501814/114292726-2c1cbd00-9aae-11eb-8916-cac8baaf0cfa.png)

**Additional Info**
ESP was turned on.
ESP was on for all entities.

**Comment by MineGame159** [comment]
Fixed in 6e5c0b77c7ce064c4b594375cc8f2f3f8fb8b66a
