### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by I21b** [MeteorDevelopment/meteor-client#4711]
### Describe the feature

Copyright © 2023 Meteor Development -> Copyright © 2024 Meteor Development

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 19MisterX98** [comment]
Wrong repo and already reported plus open pull request https://github.com/MeteorDevelopment/meteor-website/issues/29
