### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Greggus98** [MeteorDevelopment/meteor-client#4715]
### Steps to reproduce

1. Launch the game.
2. Crash.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/0eRpPtZ

### Meteor Version

0.5.7

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
cracked launcher issue, find a different launcher to use or buy the game

**Comment by Big-Iron-Cheems** [comment]
Crash log consistent with those caused by cracked launchers, buy the game and use a supported launcher as explained in our FAQ.
