### ISSUE TITLE
Hỗ trợ cài shader

### ISSUE THREAD

**Issue by ZingMCPC** [MeteorDevelopment/meteor-client#4716]
### Describe the feature

Can Meteor add optifine-like options? I can't install any mod that supports shader, optifabric, sodium, ebedium.... they all crash, I'm using meteor cilent 1.19.3

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
1. 1.19.3 is really old, we don't provide support for it
2. Update the game to 1.20.6 or 1.21, install [Iris](https://modrinth.com/mod/iris/versions?g=1.21&g=1.20.6) and you'll be able to use shaders on Fabric.

_Closing as old version request._
