### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Merks11** [MeteorDevelopment/meteor-client#4718]
### Describe the bug

In DEV build 0.5.8 when you active the Xray module the game crash 

### Steps to reproduce

I active the Xray module

### Meteor Version

DEV build 0.5.8

### Minecraft Version

1.21.0

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
reopen this when you post a crash report
