### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Lombrigao** [MeteorDevelopment/meteor-client#4727]
### Describe the bug

Every time I activate the nametags module my fps drops a lot, for example: I'm at 150 fps but when I activate the nametags module it drops to 70/60 fps. Is there no way the fps can stay stable?

### Steps to reproduce

I activated the nametags module and my fps dropped a lot

### Meteor Version

all meteor clients

### Minecraft Version

1.20.1+

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Update to 1.20.6 (or even better, 1.21) and see if this still happens, 1.20.1 is really outdated and we can't provide support for it.
Can't reproduce on my end as of the latest dev build, tested with around 20 players.

Re-open this issue if the bug persists.
