### ISSUE TITLE
Does Baritone continue to update to minecraft version 1.21?

### ISSUE THREAD

**Issue by lsinda** [MeteorDevelopment/meteor-client#4728]
### Describe the feature

Pls is Baritone still updated
![png](https://github.com/MeteorDevelopment/meteor-client/assets/140962801/85180e83-4a63-414b-9e6d-bca73031dc0f)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
1. Baritone is not our project, don't clog our issues (or theirs for that matter) for this kind of stuff.
2. There's an open PR you can use for 1.21 already: https://github.com/cabaletta/baritone/pull/4394

**Comment by lsinda** [comment]
全部的话要💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵💵X20个
