### ISSUE TITLE
[Bug] Waypoints with same name cause error/debug/log message "duplicate key"

### ISSUE THREAD

**Issue by B0NBunny** [MeteorDevelopment/meteor-client#4729]
### Describe the bug

This caused me to lose all my waypoints.

### Steps to reproduce

Make multiple waypoints and give them the same name and it gives you a Network Protocol Error and you can't join the game
I started messing with my waypoints nbt and was finally able to get back into the server but lost all my waypoint data in the process. That is unless waypoint locations are stored not in the nbts?

### Meteor Version

Meteor 0.5.8

### Minecraft Version

MC 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Fixed in af60c8e83e67b788eb4b99ead08d3262bf3529e7
