### ISSUE TITLE
[Bug] GUI bug in infinity miner

### ISSUE THREAD

**Issue by Dam-Buty** [MeteorDevelopment/meteor-client#473]
**Describe the bug**

When configuring Infinity Miner, if i select a block type to mine (for example Iron Ore) it doesn't update in the GUI. It does, however, start mining Iron ore as expected. If i close the GUI and open it again, it shows the correct block.

**To Reproduce**
1. Go to Infinity Miner
2. Select "Iron Ore"

**Expected behavior**
The GUI should show Iron Ore as the block to mine

**Additional context**
Tested on latest dev build (719)

**Comment by MineGame159** [comment]
Fixed in 690ba8991533bfd73b1affb577e234aa2a4f68fc
