### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by Dreamtell** [MeteorDevelopment/meteor-client#4731]
### Describe the bug

Too many fonts on the HUD can cause frame drops when configuring the HUD, and sometimes even if you don't have the HUD configuration screen open _(it seems to be when you open a custom font)_

### Steps to reproduce

![39ACF3F194077D4C7B7EF05705C794A0](https://github.com/MeteorDevelopment/meteor-client/assets/155887909/31cd6e00-af4a-4ccb-b845-437aa387529a)
I added a lot of HUD after turning on the custom font, and then it was very stuttering, only 1 to 2 FPS

### Meteor Version

Meteor 1.20.4 Official version

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
I am not really able to replicate any noticeable frame drops when filling up my screen with text elements. If you could provide better instructions or maybe a video then I could look at it.
