### ISSUE TITLE
Chinese Language Crash (Maybe)

### ISSUE THREAD

**Issue by LumIsHere** [MeteorDevelopment/meteor-client#4732]
### Steps to reproduce

I'm using Chinese language and when i use freecam, or do interaction with players like attacking, tping will cause the game crash.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/OVtkt3d

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Nippaku-Zanmu** [comment]
将mc更新至1.21并使用最新的流星端

**Comment by Wide-Cat** [comment]
has been fixed
