### ISSUE TITLE
[Suggestion] Auto Craft (suggestion has been made in 2021 but not been added so I decided to remind ya'll abt this unique feature)

### ISSUE THREAD

**Issue by BUBIFIRE** [MeteorDevelopment/meteor-client#4733]
### Describe the feature

So I was thinking of this feature that if gold nuggets were to drop on you from your gold farm, you would auto-craft them into ingots and then turn it into gapples or gold blocks when I am in the crafting table gui. Or when in the middle of a fight, a saturation stew (which is the best food in the game, better than a notch apple) is auto crafted and put into your hotbar slots without you opening the inventory and crafting it which takes time.
So yea I was thinking of a feature that would let me select what item I wanna autocraft and meteor autocrafts it as long as I have it turned on and the ingredients are ready without having to open the inventory and craft it myself. It will save sooo much time and be OP in fights especially on servers with anti-cheat that blocks other pvp features. (It surely can't do anything to this).

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Well I dont think I need to say that its a duplicate but here we go
