### ISSUE TITLE
betterchat suffix not work

### ISSUE THREAD

**Issue by SodamX** [MeteorDevelopment/meteor-client#4736]
### Describe the bug

betterchat suffix not work

### Steps to reproduce

i think it's onMessageSend issue

### Meteor Version

Meteor 0.5.6

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/84e5ae85-eb0a-43f1-b35a-f92c5cb72b06)
![image](https://github.com/MeteorDevelopment/meteor-client/assets/52252627/cbde2b18-ea35-4bf0-a97c-4f74e564f7e6)
Seems to be working just fine as of 1.21 both in single and multiplayer, I suggest you update.
If the bug persists, re-open this issue.
