### ISSUE TITLE
game not starting [1.21] [meteor 0.5.8]

### ISSUE THREAD

**Issue by MrVINIK** [MeteorDevelopment/meteor-client#4739]
### Steps to reproduce

I JUST tried to launch it, but it didn't work out. I tried to install even Sodium - also a mistake. I have literally removed all mods and addons, left only meteor - it does not start. Previously, I played on the old version for 1.20.1, everything worked fine. Switched to 0.5.8 for 1.21 - faced a startup problem.
I use the Legacy Launcher

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/CeYA7d0

### Meteor Version

0.5.8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
Meteor does not support using cracked launchers
