### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by BubbaNak** [MeteorDevelopment/meteor-client#474]
**Describe the feature**
Nether portal finder, EXACT same as Stash Finder, but marks either obsidian with a minimun of "X" blocks, or active portals.

**Screenshots**
N/A
**Additional info**
Should be able to repurpose Stash Finder, make it use diff txt file, and change targets and criteria boom done. (I hope)

BTW you guys rock

**Comment by BobIsMyManager** [comment]
or maybe have make stash find be able to have any blocks set to it and rename it "base finder"
