### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yaeas0** [MeteorDevelopment/meteor-client#4740]
### Describe the bug

I can't turn off kill aura

### Steps to reproduce

1. 
don't know 2. 
don't know

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
We don't provide support for outdated versions.
Also, try `.toggle all off`, if you enabled a module, you can turn it off.
