### ISSUE TITLE
[Suggestion] fix baritone with deepslate

### ISSUE THREAD

**Issue by Alekstaros** [MeteorDevelopment/meteor-client#4741]
### Describe the feature

when you try to mine some diamonds with baritone it works but only mines normal diamonds and allot of the time there are allot of deepslate diamonds that it doesnt mine

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
`#mine diamond_ore deepslate_diamond_ore`

**Comment by Aculoss** [comment]
The ones he doesnt mine is probably the ones with lava or water behind.
