### ISSUE TITLE
[Suggestion] new modules

### ISSUE THREAD

**Issue by Merks11** [MeteorDevelopment/meteor-client#4746]
### Describe the feature

Make new modules like a type of Creative or /give 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Least nonsensical feature description.
Any creative-like feature would need OP anyways.

**Comment by Merks11** [comment]
Or make a module for Op

**Comment by Nippaku-Zanmu** [comment]
> 或者为Op制作一个模块

This is not possible, the permission management is carried out on the server side, so far no elevation of privilege vulnerability has been discovered, and illegal access to operator privileges can only be carried out through backdoors and other means

**Comment by Nippaku-Zanmu** [comment]
This is not possible, the permission management is carried out on the server side, so far no elevation of privilege vulnerability has been discovered, and illegal access to operator privileges can only be carried out through backdoors and other means

> Or make a module for Op
