### ISSUE TITLE
Kill aura doesnt work for me

### ISSUE THREAD

**Issue by SolarFRFR** [MeteorDevelopment/meteor-client#4750]
### Describe the bug

I turn on KIll aura and nothing happened but then when my friend turned it on it worked. 
Why?

### Steps to reproduce

1. download and put the client in the game
2. turn on kill aura and isee if it works

### Meteor Version

tbh idk

### Minecraft Version

MC 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Well it is most definitely an issue with your config. You have to select which entities you want it to target, or maybe it is set to only attack while holding a weapon, etc.
