### ISSUE TITLE
.bind

### ISSUE THREAD

**Issue by pay2lose2** [MeteorDevelopment/meteor-client#4751]
### Describe the bug

Command `.bind` makes you not able to bind any modules, both via command and via GUI.
After running the command and pressing any key, it does nothing.

https://github.com/user-attachments/assets/7413200b-031c-40a8-8b85-9a40c779c72c

https://github.com/user-attachments/assets/5db1ae0b-fab5-4514-a373-048faab6e9f2

### Steps to reproduce

1\. `.bind` any module
2\. press any key (no message, nothing will pop up that it's binded, even if you will look at it in GUI, it says it's not binded)

Optionally:
3. Open ClickGUI
4. Open any module and try to bind it via there, not only you won't be able to bind any module but you will also be soft locked until you click a button to return bind to default.

### Meteor Version

0.5.8 2129

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Fixed in 21e034d007a9ae06806a2097f5f89e54c8037a3a

**Comment by pay2lose2** [comment]
> Fixed in [21e034d](https://github.com/MeteorDevelopment/meteor-client/commit/21e034d007a9ae06806a2097f5f89e54c8037a3a)

![mc](https://github.com/user-attachments/assets/6846312c-3004-4a7d-88e8-afd69eb8f04d)
:+1:
