### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by eastboundten761** [MeteorDevelopment/meteor-client#4752]
### Describe the bug

when i type in the link token into the bot on discord it comes up with "Unknown Integration" after refreshing it comes up with "The application did not respond". i am very confused

### Steps to reproduce

1. i copied the link token
2. i pasted it into the bots DMs

### Meteor Version

meter bot

### Minecraft Version

discord

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
I don't really know what to tell you because I just tried it and it worked
