### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by eastboundten761** [MeteorDevelopment/meteor-client#4753]
### Describe the bug

i am unable to enchant with the commands

### Steps to reproduce

1. i wrote .enchant max all
2. it sent me to a error screen
![image_2024-07-17_225602206](https://github.com/user-attachments/assets/15e4134b-a8d5-483a-b756-e24330527abc)

### Meteor Version

metor 0.8.5

### Minecraft Version

MC 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Duplicate of #4688
