### ISSUE TITLE
AntiPacket Kick doesnt work

### ISSUE THREAD

**Issue by majkokiska** [MeteorDevelopment/meteor-client#4754]
### Describe the bug

This module is broken.

### Steps to reproduce

1. I turned on the mod
2. It didnt worked

### Meteor Version

Meteor 0.5.8

### Minecraft Version

MC 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Go into the module settings and enable the two catch exceptions settings. If it still doesn't work reopen this issue with some sort of proof or elaboration.
