### ISSUE TITLE
AntiPacket Kick still doesnt work

### ISSUE THREAD

**Issue by majkokiska** [MeteorDevelopment/meteor-client#4755]
### Describe the bug

This module is still not working.

Proof: https://www.mediafire.com/file/z11m8j5xt2fhn00/2024-07-18+17-19-26.mp4/file

### Steps to reproduce

1. I turned on the medule settings
2. It still doesnt work.

### Meteor Version

Meteor 0.5.8

### Minecraft Version

MC 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
AntiPacketKick is meant to prevent OffhandCrash. If you read the description of AntiPacketKick then you will see it tries to protect against large packets. Which is not how OffhandCrash works. It overhelms the audio engine with too many sounds.

**Comment by majkokiska** [comment]
How am i supposed to crash big servers then?

**Comment by MineGame159** [comment]
You are simply getting kicked by sending too many packets

**Comment by majkokiska** [comment]
And how do i avoid that?

**Comment by MariusLord** [comment]
> How am i supposed to crash big servers then?

PayPal me $50 I'll SHUT DOWN any server you want, even hypixel ;)

**Comment by majkokiska** [comment]
im broke and i love meteor client than any hacking clients

**Comment by majkokiska** [comment]
Hey @MineGame159 How do i crash minecraft servers and how do i stopped getting kicked out?

**Comment by MariusLord** [comment]
> im broke and i love meteor client than any hacking clients

meatier client on top!
