### ISSUE TITLE
Incompatibility Crash with Axiom

### ISSUE THREAD

**Issue by furiouswhqle** [MeteorDevelopment/meteor-client#4756]
### Steps to reproduce

1. Have Fabric API, Axiom, and Meteor installed
2. Create a new world
3. Select two points with the Axiom tool
4. Then use the scroll wheel. It crashes instead of moving the selection.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/3foX5Co

### Meteor Version

0.5.0 2130

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Fixed in ab5f7ac151ca83879ea0a112fdb5e7bd119f5dd4
