### ISSUE TITLE
Auto Reconnect conflict with Autolog

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [MeteorDevelopment/meteor-client#4757]
### Describe the bug

When both AutoLog and AutoReconnect modules are turned on, game exits caused by AutoLog will be reconnected by AutoReconnect. 

The following is a modified code(AutoLog.java)

```
private void disconnect(String reason) {
        if (Modules.get().isActive(AutoReconnect.class)){
            Modules.get().get(AutoReconnect.class).toggle();
        }
        mc.player.networkHandler.onDisconnect(new DisconnectS2CPacket(Text.literal("[AutoLog] " + reason)));
    }
```

### Steps to reproduce

1. Enable Autolog and AutoReconnect 
2. Self -harm, until the player's health is lower than the setting value in Autolog, triggers Autolog automatically disconnects connection
3. AutoReconnect module will make you re -connect to the server

### Meteor Version

0.5.8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Fixed in c7d2f7f2f1d0b0b259617f486fff9a01134d10ed
