### ISSUE TITLE
AutoNametag waste nametag

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [MeteorDevelopment/meteor-client#4758]
### Describe the bug

Automatic creature renaming with the autonametag module 4 uses multiple nametags on a creature

The AutoNametag module performs a naming attempt on each tick
This does not take into account that delays with the server will keep trying to name the same creature before receiving feedback from the server should be avoided by using delays
<img width="478" alt="before" src="https://github.com/user-attachments/assets/2f4f4d31-6312-4482-8e76-762248b20ee5">

The following is my personal solution source code
<img width="492" alt="after" src="https://github.com/user-attachments/assets/a4b18641-e5c6-4407-ae83-df83bc789787">

### Steps to reproduce

1. Enable the AutoNametag module and hold the nametag
2. Approach the creature selected in the AutoNametag module
3. The module uses multiple nametags for a creature

### Meteor Version

0.5,8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Hopefully fixed in 30a1b68f7eef5e18c1d88394ebd6a7ca8c4b64a7. I didn't feel like adding another setting for a delay but because I implemented it using a per-entity cooldown rather than a global one I think it should be fine. I think one second cooldown should be fine but if it's not then just comment on this issue.

**Comment by XingYeSensei** [comment]
神秘的东方文字
