### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by HealingArcYT** [MeteorDevelopment/meteor-client#476]
**Describe the feature**
Additional Feature for Zoom

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
The further you zoom in (using scrollwheel) the slower should the sensitivity be

**Comment by MineGame159** [comment]
It already does that (assuming you are talking about mouse sensitivity)

**Comment by HealingArcYT** [comment]
Yes, but you can use scrollwheel t zoom in reaaally far and then it doesnt reduce enough for it not to overspeed of small movements
