### ISSUE TITLE
Crashing when zooming out too much with Camera Tweaks module

### ISSUE THREAD

**Issue by cozybro** [MeteorDevelopment/meteor-client#4760]
### Steps to reproduce

1. Turn on Camera Tweaks with the default settings
2. scroll out until it crashes (idk how long u have to scroll out for, really depends on ur mouse)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

i have no idea how to get my log, they all encrypted

### Meteor Version

0.5.8 2125-2134

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Hyped1XGeek** [comment]
We will need a crash report to understand what is causing the crash.

Crash Report are stored at `C:\Users\<username>\AppData\Roaming\.minecraft\crash-reports` by default.
Logs are stored at `C:\Users\<username>\AppData\Roaming\.minecraft\logs` by default.

These are stored in the same directory as your saves(world) folder. Follow the following steps to access the files:

Step 1: Press the Windows + R keys at the same time to open the Run dialogue box.
Step 2: Copy and paste the command – %appdata%\.minecraft and click the OK button.

Let me know if you need any help

**Comment by Arson-Arson** [comment]
After quick testing, I was unable to replicate. I was able to zoom out to world border/integer limit without crashing, so it likely has to do with other user settings; can you provide either the logs as indicated or even an sc of your current modules when you ran it?
![image](https://github.com/user-attachments/assets/72fc7655-bfcb-455e-a80a-0fae1f28f967)

**Comment by Wide-Cat** [comment]
cant do anything without a crash report
