### ISSUE TITLE
BRING BACK Auto Mine

### ISSUE THREAD

**Issue by Xoaenel** [MeteorDevelopment/meteor-client#4768]
### Describe the feature

i have recently found out  that i cant find automine and that is really bad for me

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
You mean Baritone? You can download it separately.

**Comment by Xoaenel** [comment]
no i dont mean baritone last time i used meteor client that was maybe about 5 months ago there was a feature that auto Mine whitelisted blocks and everything between it

**Comment by MineGame159** [comment]
Infinity Miner? That is still there, it just needs Baritone.

**Comment by Xoaenel** [comment]
why the hell does it need baritone and what is that? it didnt need it last time i used it

**Comment by MineGame159** [comment]
Yes it did. Baritone was simply bundled with Meteor before. Now it's not. Baritone is the mod that takes control of the player and automatically mines, walks, etc. Infinity Miner just gives commands to Baritone.

**Comment by Xoaenel** [comment]
and where do i download that?

**Comment by MineGame159** [comment]
Either use Google or go to our website.

**Comment by Xoaenel** [comment]
how do i install baritone to minecraft

**Comment by theblazehen** [comment]
Either use [Google](https://google.com) or go to [the website](https://meteorclient.com/)
