### ISSUE TITLE
Block Esp exposed to air option.

### ISSUE THREAD

**Issue by Minecat2010** [MeteorDevelopment/meteor-client#4774]
### Describe the feature

"Exposed to air only" option in Block Esp, to combat the anti xray protection some servers have, letting you locate exposed diamonds trough walls.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Not really within the scope for block esp, plus theres already a setting for that in xray.
