### ISSUE TITLE
offhand crash kicks you because of plugins

### ISSUE THREAD

**Issue by meteorclientuser69420** [MeteorDevelopment/meteor-client#4776]
### Describe the bug

offhand crash kicks you for exceeding the packet limit

### Steps to reproduce

i tried using anti packet kick and does not work
then tried downloading bigger packets off forge and didnt work

### Meteor Version

meteor 0.5.8

### Minecraft Version

mc 1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by meteorclientuser69420** [comment]
help please

**Comment by MineGame159** [comment]
Unless you want to be banned you might want to stop opening this issue

**Comment by meteorclientuser69420** [comment]
what

**Comment by Wide-Cat** [comment]
Theres nothing you can do to bypass packet rate limits on the client, all you can do is send less packets.

**Comment by meteorclientuser69420** [comment]
but can you still kick players

**Comment by meteorclientuser69420** [comment]
@MineGame159 what do you mean by ban

**Comment by Big-Iron-Cheems** [comment]
![image](https://github.com/user-attachments/assets/3fb79fdf-17af-4850-964d-9e43e2281f93)
This is what he means, so please don't abuse the issues page with reports that actually have no basis.

**Comment by meteorclientuser69420** [comment]
@Big-Iron-Cheems  what did i do wrong

**Comment by Big-Iron-Cheems** [comment]
I literally explained it in my message, if you're unble or unwilling to read I can't help you.

**Comment by meteorclientuser69420** [comment]
@Big-Iron-Cheems what does basis mean

**Comment by meteorclientuser69420** [comment]
so asking for power is abuse

**Comment by Big-Iron-Cheems** [comment]
1. You first opened an issue for an `enhancement` that cannot be implemented, as it would require you having admin powers, at that point you'd be able to give yourself any effetc you want.
2. You then open a `bug` report and talk about two modules that are completely unrelated to what you're experiencing, as explained by @Wide-Cat already in this same issue.

So yeah, you're abusing the issues system by opening tickets that are fundamentally wrong.
