### ISSUE TITLE
Meteor natural crash

### ISSUE THREAD

**Issue by CTM54652** [MeteorDevelopment/meteor-client#4778]
### Describe the bug

The client crashes when i opened the mod on forge

### Steps to reproduce

1: I put the meteor client, and an API, (API or not, it crashed anyways)
2: Opened the forge game (TLauncher specifically) and crashed
I followed the steps on the website, but didnt work.

### Meteor Version

0.5.8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
1. meteor is for fabric not forge
2. meteor does not work on tlauncher, use a different launcher or buy the game

**Comment by CTM54652** [comment]
my bad, i meant forge
i got it now, thank
