### ISSUE TITLE
incorrect display of armor and items in nametags

### ISSUE THREAD

**Issue by rufwyll** [MeteorDevelopment/meteor-client#4779]
### Describe the bug

the nametags function does not display the icons of armor and items in the player's hand, all other information is displayed normally, only the problem is in the icons of items.
![2024-07-25_21 34 50](https://github.com/user-attachments/assets/8123ed0a-cfc9-4dff-8f1c-dcf5fe685a1d)
![2024-07-21_12 25 24](https://github.com/user-attachments/assets/b77787b3-0506-4990-be7e-3345d0125670)

### Steps to reproduce

1. launched minecraft with meteor client mod + fabric api (nothing else)
2. enabled nametags function
3. looked at player's armor icons

### Meteor Version

0.5.8-2137

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Arson-Arson** [comment]
Could I get some clarification on this? I could not replicate the bug on the exact same version doing the exact steps listed. Tested both on local lan and on public server.

**Comment by rufwyll** [comment]
> Could I get some clarification on this? I could not replicate the bug on the exact same version doing the exact steps listed. Tested both on local lan and on public server.

I'm not sure what exactly causes this bug, but I have it all the time. maybe because of the GPU, I don’t know, I updated to 1.21 and it turned out right away, there are some logs that may be useful to you

**Comment by Arson-Arson** [comment]
Interesting. I will take a look at the logs once sent; will try and fix.

**Comment by rufwyll** [comment]
> Interesting. I will take a look at the logs once sent; will try and fix.
[latest.log](https://github.com/user-attachments/files/16423861/latest.log)
I don't know if there is anything useful here, you can ask me anything that can help you

**Comment by Arson-Arson** [comment]
After taking a look at the latest.log you have sent, it seems you have plenty of mods running, any of which could cause a gui render problem; could you send me another with just metoer and the fabric api loaded? Really appreciate :)

**Comment by rufwyll** [comment]
> After taking a look at the latest.log you have sent, it seems you have plenty of mods running, any of which could cause a gui render problem; could you send me another with just metoer and the fabric api loaded? Really appreciate :)

[latest.log](https://github.com/user-attachments/files/16424124/latest.log)
oh sorry I didn't even think)

**Comment by Arson-Arson** [comment]
All good. I couldn't find anything in the log that would indicate something breaking; do you think it could be something to do with the language?

**Comment by rufwyll** [comment]
> All good. I couldn't find anything in the log that would indicate something breaking; do you think it could be something to do with the language?

no, the language works in another part, it works fine but there is no icon. The Russian language really doesn’t work with the custom font, but I fix it through another mod. in general, the text and language have nothing to do with it. 
I can show you the screen in discord and we’ll see, although I don’t know English very well. If you speak, I won’t understand you)

**Comment by Arson-Arson** [comment]
catholicpropaganda#0001 on discord, add me and ill try and give you a hand

**Comment by Arson-Arson** [comment]
It appears the issue is fixed
