### ISSUE TITLE
dupe feature

### ISSUE THREAD

**Issue by meteorclientuser69420** [MeteorDevelopment/meteor-client#4782]
### Describe the feature

up to date duping

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by identity7** [comment]
lol

**Comment by JoqueR211** [comment]
Is it possible?
