### ISSUE TITLE
Unscrambler module

### ISSUE THREAD

**Issue by arthurauffray** [MeteorDevelopment/meteor-client#4784]
### Describe the feature

There is a popular server plugin called Scrambler that automatically throws a scrambled word in chat and whoever unscrambles it via a chat command gets a money reward. You can either actually unscramble the word or use a website to show answers, but this isn't ideal: have to copy from chat, takes time, others can guess first etc; which is why a module would be amazing. Programatical unscrambling is pretty easy, there's some tutorials out there too.

Module settings:
- random answer delay range slider (0-30s)
- don't answer percentage chace
- try multiple answers toggle
- try multiple answers delay range slider
- custom API choice

Example of plugin in action:
![Screenshot](https://github.com/user-attachments/assets/ef3bda85-c459-443d-800d-bb25a8677e05)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This is a really niche feature for minigame servers.
Definitely something better suited to a dedicated addon than the main client.

**Comment by arthurauffray** [comment]
interesting, ive found the plugin on many smp and some anarchy servers

**Comment by OrangeMan-432** [comment]
This feature is in Liquidbounce, I think you may need a ChatGPT api key to use it though.
