### ISSUE TITLE
[Suggestion] anti fire mode and water breathing mode

### ISSUE THREAD

**Issue by yoursoneandonlyguy** [MeteorDevelopment/meteor-client#4789]
### Describe the feature

in these 2 module the player should be able in lava without taking any damage and in the 2nd one the player can swim as much as they want without any tension of going up to breath

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Just because we can tinker with the Minecraft code doesn't mean suddenly you can get lava immunity etc, please be realistic.
