### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ryssiaczrk** [MeteorDevelopment/meteor-client#4792]
### Describe the bug

Every module that hits entities (crystal aura, kill aura, etc.), when hitting a end crystal it crashes the game

### Steps to reproduce

1. add end crystals to kill aura, or just turn on crystal aura itself
2. crash when trying to hit a crystal

### Meteor Version

0.5.8 2137

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
send logs

**Comment by Ryssiaczrk** [comment]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-07-31 04:42:18
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_1511 cannot be cast to class net.minecraft.class_1309 (net.minecraft.class_1511 and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @55f3ddb1)
	at zgoly.meteorist.modules.ZKillaura.onTick(ZKillaura.java:181)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$chh000$meteor-client$onPreTick(class_310.java:16735)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at zgoly.meteorist.modules.ZKillaura.onTick(ZKillaura.java:181)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$chh000$meteor-client$onPreTick(class_310.java:16735)

-- Uptime --
Details:
	JVM uptime: 2494.995s
	Wall uptime: 2466.400s
	High-res time: 23423.994s
	Client ticks: 47089 ticks / 2354.450s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Richard'/7849, l='ClientLevel', x=-29.72, y=57.18, z=45.26]]
	Chunk stats: 1024, 841
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,56,0), Section: (at 0,8,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 241 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 5

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterconfig, c2me, clientcommands, cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, enhancedblockentities, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, google-chat, immediatelyfast, indium, libjf-config-core-v2, libjf-translate-v1, lithium, meteor-additions, meteor-client, meteor-villager-roller, meteorist, modernfix, moreculling, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, nochatreports, noisium, nvidium, sodium, streak-addon, viafabricplus, vmp

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 599299104 bytes (571 MiB) / 1509949440 bytes (1440 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 530
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 23.20.16.4973
	Graphics card #1 name: NVIDIA GeForce GTX 960M
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.5612
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 65363.88
	Virtual memory used (MiB): 11141.70
	Swap memory total (MiB): 32768.00
	Swap memory used (MiB): 84.00
	Space in storage for jna.tmpdir (MiB): available: 502707.25, total: 953306.19
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 502707.25, total: 953306.19
	Space in storage for io.netty.native.workdir (MiB): available: 502707.25, total: 953306.19
	Space in storage for java.io.tmpdir (MiB): available: 502707.25, total: 953306.19
	Space in storage for workdir (MiB): available: 502707.25, total: 953306.19
	JVM Flags: 8 total; -Xmx8192M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		badoptimizations: BadOptimizations 2.1.4
		baritone-meteor: Baritone 1.21-SNAPSHOT
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.107+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.107+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.107+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.107+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.107+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.107+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.107+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.107+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.107+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.107+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.107+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.107+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.107+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.107+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.107+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.107+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.107+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.107+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.107+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.107+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.107+1.21
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		clientcommands: Client Commands 2.9
			betterconfig: BetterConfig 1.3
			clientarguments: clientarguments 1.9
			net_fabricmc_mapping-io: mapping-io 0.5.1
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.100.7+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.12+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.25+5bd9f1bcd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.82+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 7.0.0
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.34+mc1.21
		java: Java HotSpot(TM) 64-Bit Server VM 22
		lithium: Lithium 0.12.8+git.427dd75
		meteor-additions: MeteorAdditions 1.2.0
			google-chat: GoogleChat 0.8.1
			libjf-base: LibJF Base 3.16.0
			libjf-config-core-v2: LibJF Config 3.16.0
			libjf-translate-v1: LibJF Translate 3.16.0
		meteor-client: Meteor Client 0.5.8-2137
		meteor-villager-roller: Meteor Villager Roller 1.4.6+mc1.21-rev.bd1a1a1-dirty
		meteorist: Meteorist 1.10
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.18.8+mc1.21
		moreculling: More Culling 0.26.0
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
			mixinsquared: MixinSquared 0.1.1
		nochatreports: No Chat Reports 1.21-v2.8.0
		noisium: Noisium 2.2.1+mc1.21
		nvidium: Nvidium 0.2.9-beta
		sodium: Sodium 0.5.11+mc1.21
		streak-addon: TrouserStreak 1.1.1
		viafabricplus: ViaFabricPlus 3.4.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.0.2-20240717.170712-16
			com_viaversion_viaversion-common: viaversion-common 5.0.2-20240719.093012-26
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.6
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.6
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.6
			io_netty_netty-codec-http: netty-codec-http 4.1.111
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.5.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_raphimc_minecraftauth: MinecraftAuth 4.0.3-SNAPSHOT
			net_raphimc_viaaprilfools: ViaAprilFools 3.0.1-20240719.220217-9
			net_raphimc_viabedrock: ViaBedrock 0.0.10-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 3.0.2-20240714.181616-4
			net_raphimc_vialoader: ViaLoader 3.0.2-20240716.014912-6
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		vmp: Very Many Players 0.2.0+beta.7.163+1.21
	Launched Version: fabric-loader-0.15.11-1.21
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 960M/PCIe/SSE2 GL version 3.2.0 NVIDIA 556.12, NVIDIA Corporation
	Window size: 1920x1017
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, betterconfig, c2me, clientcommands (incompatible), cloth-config, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, enhancedblockentities, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, google-chat, immediatelyfast, indium, libjf-config-core-v2, libjf-translate-v1, lithium, meteor-additions, meteor-client, meteor-villager-roller, meteorist, modernfix (incompatible), moreculling, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, nochatreports, noisium, nvidium, sodium, streak-addon, viafabricplus, vmp
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Richard'/7849, l='ServerLevel[New World]', x=-29.72, y=57.18, z=45.26]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, moreculling
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, moreculling, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -1825908535217251712

-- Meteor Client --

Version: 0.5.8
Dev Build: 2137

[[ Active Modules ]]

[Combat]:
auto-exp
auto-totem
auto-weapon
crystal-aura

[Player]:
auto-eat
auto-replenish
auto-tool
fast-use
middle-click-extra
portals

[Movement]:
no-fall
sprint

[Render]:
better-tab
better-tooltips
block-esp
block-selection
blur
break-indicators
camera-tweaks
entity-owner
esp
fullbright
hand-view
item-highlight
item-physics
logout-spots
nametags
no-render
storage-esp
time-changer
trajectories
unfocused-cpu

[World]:
auto-breed
build-height
collisions
enderman-look
no-ghost-blocks
vein-miner

[Misc]:
anti-packet-kick
auto-reconnect
better-chat
inventory-tweaks
notifier
server-spoof
sound-blocker
translator

[Meteorist]:
auto-login
auto-sneak
z-kill-aura

[TrouserStreak]:
1.17InventoryDupe
shulker-dupe

[[ Active Hud Elements ]]
Text
{FPS: {fps}}
Text
{TPS: {round(server.tps, 1)}}
Text
{Ping: {ping}}
Text
{XYZ: {floor(camera.pos.x)} {floor(camera.pos.y)} {floor(camera.pos.z)}, {player.opposite_dimension != "End" ? player.opposite_dimension + ":" : ""} {player.opposite_dimension != "End" ? "" + floor(camera.opposite_dim_pos.x) + " " + floor(camera.opposite_dim_pos.y) + " " + floor(camera.opposite_dim_pos.z) : ""}}
armor
inventory
Text
{Health: {round(player.health)/2-round(meteorist.fall_damage)/2}}

**Comment by Ryssiaczrk** [comment]
this was used with z-killaura, but meteors vanilla kill aura also crashes

**Comment by Wide-Cat** [comment]
Can you post a crash report with a meteor module? Also use https://mclo.gs to post crash reports.
