### ISSUE TITLE
bariton litematic not working

### ISSUE THREAD

**Issue by cosmicmonkey659** [MeteorDevelopment/meteor-client#4793]
### Describe the bug

when ever im building using litematic and i try to use the #litematic command i just says done building without doing anything

![image](https://github.com/user-attachments/assets/1b9400fb-83ea-43d7-944f-1354f7ac7ea6)

### Steps to reproduce

1: use litematic to place a schematic
2: use the #litematic command

### Meteor Version

1.20.4

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [ ] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Open an issue in the baritone github page

**Comment by Wide-Cat** [comment]
https://github.com/cabaletta/baritone
