### ISSUE TITLE
player heads in chat not showing up

### ISSUE THREAD

**Issue by hugginfrogs** [MeteorDevelopment/meteor-client#4796]
### Describe the bug

the player head setting in better chat should show player heads beside the player name but it is not longer working

### Steps to reproduce

i think just upgrade to 1.21

### Meteor Version

0.5.8 deb build

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by nickcat325** [comment]
This works just fine for me with the dev build.

**Comment by hugginfrogs** [comment]
It just started working again so yey ig

**Comment by Wide-Cat** [comment]
cant reproduce
