### ISSUE TITLE
meteor starscript crash

### ISSUE THREAD

**Issue by yasha71** [MeteorDevelopment/meteor-client#4798]
### Steps to reproduce

i write the text on the hud using the starscript, everything worked well and minecraft crashed randomly. I'm re-entering the game, it freezes on the mojang screen(red). I made sure that the problem is in the starscript. I deleted the config folder and everything is working well. I'm also use pojavlauncher, pls help me

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/K0ptVl6

### Meteor Version

meteor 0.5.8

### Minecraft Version

1.21

### Operating System

Linux

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [x] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Might be fixed as of the latest dev build. If it isn't open a new issue
