### ISSUE TITLE
[Bug] block esp   1.20.4

### ISSUE THREAD

**Issue by JB323323** [MeteorDevelopment/meteor-client#4802]
### Describe the bug

crashes/freezes game on activation

### Steps to reproduce

-

### Meteor Version

0.5.6

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Version 1.20.4 is unsupported, update and re-open this if the issue persists on version 1.21.
