### ISSUE TITLE
auto highway builder and schematic

### ISSUE THREAD

**Issue by mohamadbagherblack** [MeteorDevelopment/meteor-client#481]
hi if u see sal hack there is some thing call auto highway builder.i know i can do it with baritone but with this is so much faster and ofc easier. i want ask meteor developers to add this to client that will be awesome. this client is one of the best client.
second is schematic. using it is a bit hard and bugy if developers can add some thing to help players use it that would be so much good

**Comment by GildedS** [comment]
We cannot implement schematica cause of the the fact that it's stuck on 1.12.2

**Comment by Declipsonator** [comment]
For the schematic printer, you can probs just use a litematica fork that has the printer option. (If you wanted to, you could also make a schematic for a highway and just afk walk it :wink:)

**Comment by RoastedCheese** [comment]
Just build highway schematics with baritone bruh

**Comment by seasnail8169** [comment]
#516
