### ISSUE TITLE
Warn on incoming projectile or fireball

### ISSUE THREAD

**Issue by axelkar** [MeteorDevelopment/meteor-client#4810]
### Describe the feature

Meteor should display a warning to the user when an incoming projectile or fireball is detected

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
meteor is a client for anarchy only
