### ISSUE TITLE
Show items at stack 0

### ISSUE THREAD

**Issue by OvaldehAardvark** [MeteorDevelopment/meteor-client#4813]
### Describe the feature

Show items at stack 0 (show reverted illegals) to view items in shulker view tooltips or even out of shulkers.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
I dont think its possible for items to have a stack size less than one. If there is a way for this to happen or server this happens on reopen the issue and provide more info.
