### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by JoqueR211** [MeteorDevelopment/meteor-client#4823]
### Describe the feature

Could You create an addon that allowes the Player to get into any gamemode or turn cheats for himself on or allowes him to become an Operator and all this also works on a Server?
Or have I overlooked that addon?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
not possible

**Comment by JoqueR211** [comment]
Sad

**Comment by JoqueR211** [comment]
Then it‘s not possible to be unbannable either I guess

**Comment by Wide-Cat** [comment]
unfortunately not
