### ISSUE TITLE
meteor don't starting

### ISSUE THREAD

**Issue by MrVINIK** [MeteorDevelopment/meteor-client#4825]
### Steps to reproduce

[latest.log](https://github.com/user-attachments/files/16573523/latest.log)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/uCbNnCx

### Meteor Version

0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
issue with whatever addon-template is, WindowResizedEvent was renamed to ResolutionChangedEvent
