### ISSUE TITLE
my xray doesent work on devbuild 1.21.1

### ISSUE THREAD

**Issue by IDK35** [MeteorDevelopment/meteor-client#4829]
### Describe the bug

i se the same blocks when i use xray it doesent show diamonds emerald or smth like that i have it on im sure i got everything on but it still doesent work

### Steps to reproduce

u enable xray on devbuild

### Meteor Version

its the dev build1.21.1

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by wilsontulus** [comment]
Any chances you have More Culling installed? Certain mods like culling may break certain Meteor's rendering functionality.
It's advised to also include the list of installed mods while reporting an issue.

**Comment by helladamnleet** [comment]
I'm also having this issue, and while there is a work around to make it work, the work around completely kills render distance (hard capped at 34 blocks. THIRTY FOUR.)

**Comment by 0x132406C** [comment]
![image](https://github.com/user-attachments/assets/122a01f7-31e4-4976-9e0d-eb0b907931cc)
be like
only installed Meteor

**Comment by Wide-Cat** [comment]
unable to reproduce
