### ISSUE TITLE
Incompatibility with latest (1.0.35) Indium

### ISSUE THREAD

**Issue by tajemniktv** [MeteorDevelopment/meteor-client#4830]
### Description 

Most likely the Indium update to support latest FRAPI made some things borked

https://github.com/comp500/Indium/commits/1.0.35+mc1.21

### Logs

https://mclo.gs/no3f28c

### Meteor Version

0.5.8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by ac1mx** [comment]
Also experiencing a similar issue. Logs match!
