### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by SpankedPlank** [MeteorDevelopment/meteor-client#4832]
### Describe the feature

since we can use viafabric to play on diffrent versions you should also make it like a 1.8 pvp hack client for certain modules add diffrent types of anti cheat bypassers so people can play on diffrent servers without having to worry about the anti cheat

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Arson-Arson** [comment]
Wide cat is going to close this without saying anything so ill say it for them: "No, lol"
