### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by SpankedPlank** [MeteorDevelopment/meteor-client#4833]
### Describe the feature

add a option to make scaffold seem legit 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Arson-Arson** [comment]
Don't play on servers that don't allow meteor and you won't need scaffold to seem legit
