### ISSUE TITLE
cant do .enchant

### ISSUE THREAD

**Issue by hhoneeyy** [MeteorDevelopment/meteor-client#4838]
### Describe the bug

.enchant is broken, it gives me this error (i am in creative + also have op)

![image](https://github.com/user-attachments/assets/fd587a9b-0d30-4bb8-8e85-a3c4cc7bc2fb)

### Steps to reproduce

1) .enchant all_possible max
2) server gets disconnected
3) get the error

### Meteor Version

Dev build 0.5.8 2146

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by hhoneeyy** [comment]
duplicate

**Comment by empty-ai** [comment]
Hi! i also experience the same issue/Bug, its not only ".enchant all possible maxx" happens alos if you use .enchant in general.
Please! please! fix this , it is my favorite feature( wish you all the best guys!
make meteor greate again)
