### ISSUE TITLE
[Bug]  stuck on loading terrain

### ISSUE THREAD

**Issue by Flowzz198** [MeteorDevelopment/meteor-client#4839]
### Describe the bug

it gets stuck on loading terrain so i cant join servers

### Steps to reproduce

try and join a server

### Meteor Version

Dev build 0.5.8 1.21.1

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Unable to reproduce. Make sure youre on the latest dev build
