### ISSUE TITLE
don't delete the backup of all the customizations as soon as you get into a world/server

### ISSUE THREAD

**Issue by lory54** [MeteorDevelopment/meteor-client#4840]
### Describe the feature

every time the game crashes while playing, all of the customizations of the client get cancelled. this is so annoying since you can't remember all the macros, profiles ecc. so please make it so the backup is overwritten by the new one when saving and not deleted as soon as you enter a world or a server

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
> so please make it so the backup is overwritten by the new one when saving and not deleted as soon as you enter a world or a server

i dont understand what you mean by this

**Comment by lory54** [comment]
i was playing on a world, the game crashed because of a different reason and all the settings of the modules, the macros, the profiles and the hud were deleted. all i want is not to lose all of this (because of a crash) by just keeping the backup while playing

**Comment by lory54** [comment]
im sorry the issue about the reset of all meteor doesn't happen anymore. it was there some months ago when i last played the client, maybe it was a specific crash
