### ISSUE TITLE
.enchant 1.21.1

### ISSUE THREAD

**Issue by Lombrigao** [MeteorDevelopment/meteor-client#4842]
### Describe the bug

every time I give the .enchant command on any item it gives an error and kicks me out of my own world

### Steps to reproduce

1-.enchant any item

### Meteor Version

meteor-client-0.5.8-2151

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
duplicate #4688
