### ISSUE TITLE
enchant command causes errors

### ISSUE THREAD

**Issue by Lncvrt** [MeteorDevelopment/meteor-client#4843]
### Describe the bug

.enchant command causes issues and kicks you from your own world

Error:
Caused by: java.lang.IllegalArgumentException: Can't find id for 'Reference{ResourceKey[minecraft:enchantment / minecraft:breach]=Enchantment Breach}' in map net.minecraft.registry.Registry$1@4b412802

Kick message:
![image](https://github.com/user-attachments/assets/29d06e6d-4743-4f37-97ea-aefaf84fd475)

### Steps to reproduce

1. Load a world
2. Hold a item
3. Run .enchant all level 255 (or any type)
4. Kicked and a error is printed in log

### Meteor Version

meteor-client-0.5.8-2151

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This is a duplicate of #4842 but less lazy and actually includes what the errors were

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by stefexec** [comment]
I am experiencing the same issues, any hints? This is a problem since the 1.21 build

**Comment by gunandblade123** [comment]
still having the same problem

**Comment by Wide-Cat** [comment]
duplicate #4688
