### ISSUE TITLE
Auto Log and Auto Reconnect should have more synergy

### ISSUE THREAD

**Issue by Kyuunex** [MeteorDevelopment/meteor-client#4845]
### Describe the feature

Auto Log and Auto Reconnect should have more synergy.

My suggestion would be for Auto Reconnect to distinguish between disconnect reasons and allow me to pick in which cases it should reconnect.

For example: If I got kicked by the server for being AFK or using a module that triggered the AC too much (like custom printers) or the server restarted, I would like it to reconnect. 

But if I got disconnected because an untrusted player entered my render distance or my health went too low, I would prefer meteor does not auto reconnect.

I'm basically asking for relevant checkboxes and etc to be added to the Auto Reconnect module.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Unknowndestroy** [comment]
Prob. It'll get you loop. If you leave, it'll log you back prob.

**Comment by 0xTas** [comment]
> For example: If I got kicked by the server for being AFK or using a module that triggered the AC too much (like custom printers) or the server restarted, I would like it to reconnect.
>But if I got disconnected because an untrusted player entered my render distance or my health went too low, I would prefer meteor does not auto reconnect.
<br>
AutoLog already disables AutoReconnect when it disconnects you for any reason, meaning it already works exactly how you described in your example.
