### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Rlmy1st-alt** [MeteorDevelopment/meteor-client#4846]
### Describe the feature

esp bypass donutsmp 

i found how to esp down to deep slate and and then it stop and i dont render pls make it / they have a anti esp so it will be hard 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We do not make bypasses, if the sevrer has an AC and rules against ESP, you deserve to be banned from it.
