### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Pancakeman213** [MeteorDevelopment/meteor-client#4847]
### Describe the feature

make a anti world generator  add onfor donut smp 
for example heres a vid: https://youtu.be/aiQsKEBt6wE?si=nQopJjCnP6fjms1d 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
That is a scam, please don't fall for these videos and trust them blindly.

**Comment by Pancakeman213** [comment]
I know it’s a scam but it would be nice if it was made cause it would be very useful for finding bases

**Comment by GreemDev** [comment]
...so you don't know it's a scam

**Comment by Pancakeman213** [comment]
I guess not but if you join their discord server they rat the files
