### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by JustaGithubGuy** [MeteorDevelopment/meteor-client#4848]
### Describe the feature

Hello! I'd like to suggest an addition to the .setblock command (setting ghost blocks in meteor) it would be nice if you added a .fill command just like .setblock but like the /fill command for ghost blocks and when in fake creative via .gamemode creative whenever you break a block in that mode or place a ghost block rather than it disappearing, it places a ghost block of that type where you placed it.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
The [SetBlockCommand](https://github.com/AntiCope/meteor-rejects/blob/master/src/main/java/anticope/rejects/commands/SetBlockCommand.java) you mention is part of the [Meteor Rejects](https://github.com/AntiCope/meteor-rejects) addon.
Open this issue on their GitHub.
