### ISSUE TITLE
new module similar to .panic

### ISSUE THREAD

**Issue by lory54** [MeteorDevelopment/meteor-client#4850]
### Describe the feature

the best way of turning off all the modules (maybe you want to take a vanilla screenshot or seem legit to a friend) is by using the .panic command. the pain in the neck is when you have to turn on all the previous modules. so i just want a module that deactivates/disables all the modules when its on and reactivates them when its turned back off

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
not happening
