### ISSUE TITLE
[Bug] x ray is broken

### ISSUE THREAD

**Issue by imincomputer** [MeteorDevelopment/meteor-client#4854]
### Describe the bug

x ray doesnt work its just fullbright

### Steps to reproduce

1 i enable xray 
2 then i see its just full bright

### Meteor Version

Meteor dev build 0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Fixed in 8f83d5d0320b8e10a1d0e860eec79b1bad1e35ff.
