### ISSUE TITLE
Crash with Axiom

### ISSUE THREAD

**Issue by Sauron971** [MeteorDevelopment/meteor-client#4856]
### Steps to reproduce

1. Place enything in axiom
2. crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://paste.ee/p/QD3TU

### Meteor Version

0.5.7

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
has been fixed as of the latest dev build
