### ISSUE TITLE
crashed when joining a single-player world/server

### ISSUE THREAD

**Issue by kurumisuki520** [MeteorDevelopment/meteor-client#4857]
### Steps to reproduce
When I enable Sodium, my game crashes whenever I try to join a single-player world or server.

![prismlauncher_5YnzE9CG11](https://github.com/user-attachments/assets/76d4f095-2de9-41c1-9f05-fc1fb09be09a)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Ng0il0e

### Meteor Version

meteor client v0.5.8 build #2153

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by kurumisuki520** [comment]
When I disable Sodium, the game runs normally, but when I enable it, it crashes.

**Comment by MineGame159** [comment]
Fixed in 902308faca05f0a8e7e8750cf5698cef549e7f23.
