### ISSUE TITLE
Deleting maps and cant join servers

### ISSUE THREAD

**Issue by Unknowndestroy** [MeteorDevelopment/meteor-client#4863]
### Describe the bug

I cant join any servers. It says Disconnected. I tried to reinstalling the client too. It changed nothing.

### Steps to reproduce

IDK, cuz when everything is working, i normally left the server and i cant join anymore. I am using viafabric to join server at 1.19.2, i can login before too.

### Meteor Version

0.5.7

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [x] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
if you can reproduce this on the latest dev build open another issue
