### ISSUE TITLE
Force-OP 

### ISSUE THREAD

**Issue by Unknowndestroy** [MeteorDevelopment/meteor-client#4864]
### Describe the feature

Force-OP hack like can bypass authme or bruteforce authme.  or can open command prompt and like when we write /pardon username, and it'll send commands without capturing to authme. 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Impossible.

**Comment by Unknowndestroy** [comment]
why?

**Comment by Unknowndestroy** [comment]
i remember wurst has bruteforce for authme

**Comment by haune8445** [comment]
https://github.com/MeteorDevelopment/meteor-client/issues/4864
