### ISSUE TITLE
Creative Flying.

### ISSUE THREAD

**Issue by Unknowndestroy** [MeteorDevelopment/meteor-client#4865]
### Describe the feature

When double jumped, we can fly like on creative mode.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Just enable Flight.
