### ISSUE TITLE
Teleport Aura

### ISSUE THREAD

**Issue by Unknowndestroy** [MeteorDevelopment/meteor-client#4866]
### Describe the feature

We can select the speed and range, User will teleport around the teleported around users or entities. And hit her.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Impossible.

**Comment by Unknowndestroy** [comment]
Wurst has it. It means its not impossible
