### ISSUE TITLE
Invincibility / God / InfHealth

### ISSUE THREAD

**Issue by Unknowndestroy** [MeteorDevelopment/meteor-client#4868]
### Describe the feature

You cant die / You have almost infinite hearts.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Impossible.

**Comment by Unknowndestroy** [comment]
Bro everything is impossible for you.

**Comment by identity7** [comment]
> Bro everything is impossible for you.

your suggestions arent good, thats why
