### ISSUE TITLE
SendMessageEvent did not work in meteor 0.5.6-SNAPSHOT

### ISSUE THREAD

**Issue by Abstr3act** [MeteorDevelopment/meteor-client#4870]
### Describe the bug

![image](https://github.com/user-attachments/assets/4616c160-17bf-495e-8d1b-178748d6cd52)
![image](https://github.com/user-attachments/assets/16cb3c0b-504e-4220-95fd-25f19f0cacbb)
SendMessageEvent did not work in meteor 0.5.6-SNAPSHOT（1.20.4）
it affect all modules that use SendMessageEvent

### Steps to reproduce

i was trying to create a new module that use SendMessageEvent, then i found that it doesn't work
so i tried betterchat and then it just didn't work

### Meteor Version

0.5.6-SNAPSHOT

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
We can't back port fixes.
Unless this happens on the latest dev build, there's nothing we can do.
