### ISSUE TITLE
Doesnt work on 1.21

### ISSUE THREAD

**Issue by screengui** [MeteorDevelopment/meteor-client#4872]
### Steps to reproduce

1. I downgraded from 1.21.1 to 1.21
2. I used 0.5.8 dev build and when i started mc it crashed (i am using pojavlauncher but it worked perfectly fine on 1.21.1)

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Gszf6Cl

### Meteor Version

0.5.8

### Minecraft Version

1.21

### Operating System

Linux

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by screengui** [comment]
nvm i fixed it by changing the "depends" to 1.21 instead of 1.21.1

**Comment by master7720** [comment]
age restrictions for github issues
