### ISSUE TITLE
Crystal aura

### ISSUE THREAD

**Issue by robeber** [MeteorDevelopment/meteor-client#4880]
### Steps to reproduce

I tp to some it starts placing crytsals 5 seconds Later my game crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

i dont have

### Meteor Version

The one got 1.20.6 mc

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
cant do anything without a crash report
