### ISSUE TITLE
Meteor isn't compatible with 1.21

### ISSUE THREAD

**Issue by Radaggon** [MeteorDevelopment/meteor-client#4882]
### Describe the bug

I need to run an instance of minecraft 1.21 but the fabric loader tells me that Meteor is not compatible with 1.21.
I run the latest dev build 0.5.8-2160 and it requires 1.21.1 to work.

I see a lot of 1.21.1 mods that are compatible with 1.21, would it be possible to have meteor compatible as well?
Thank you very much!

### Steps to reproduce

1. Install Meteor 0.5.8-2160 on minecraft 1.21, with Fabric Loader 0.16.3
2. Run the game, the mod is incompatible with 1.21, fabric loader asks me to update to 1.21.1

### Meteor Version

0.5.8-2160

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
If it was possible for it to be compatible with both 1.21 and 1.21.1 then it would already be marked such.

**Comment by Pepit234** [comment]
Hola

**Comment by Pepit234** [comment]
2025 2b2t edit
