### ISSUE TITLE
sugestion add a meteor insatalation menu where u pick the versions 

### ISSUE THREAD

**Issue by itzrazh** [MeteorDevelopment/meteor-client#4884]
### Describe the feature

sugestion add a meteor insatalation menu where u pick the versions and make it so u can the oldest version is 1.9

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
This is not something we are interested in doing. You can use viafabricplus to connect to older servers.
