### ISSUE TITLE
Inventory Crash

### ISSUE THREAD

**Issue by oxriginal** [MeteorDevelopment/meteor-client#4886]
### Steps to reproduce

join a world open inventory and go to search and press a letter and it crashes or just open inventory and it crashes

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/lQKIoJy

### Meteor Version

0.5.8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
update to the latest dev build, this has been fixed
