### ISSUE TITLE
Meteor 1.21 conflict 

### ISSUE THREAD

**Issue by FishMCVN** [MeteorDevelopment/meteor-client#4887]
### Describe the feature

Is there a version of meteor 1.21 that doesn't conflict with Indium mod 1.0.35?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Probably not no. Update to the latest dev build, it should be fixed
