### ISSUE TITLE
[SUGGESTION] Elytra Fly No Crash Blacklist

### ISSUE THREAD

**Issue by Paradox-77** [MeteorDevelopment/meteor-client#489]
**Describe the feature**
When using the No Crash Elytra Fly setting, nether portals are counted as blocks. This makes you stop when flying on a nether highway (or wherever) when there is a portal in your path. This is kinda annoying. I suggest adding a blacklist (A list of blocks that are ignored by the No Crash settings) as it is better than only portals as some people might want to disable other blocks.

**Screenshots**
N/A

**Additional info**
You could add an option for just portals and not a blacklist if for some reason a blacklist feature wouldn't be possible. 
If you do end up adding the blacklist I suggest setting the portal block to be blacklisted by default.

**Comment by seasnail8169** [comment]
same as #446
