### ISSUE TITLE
Meteor crashs with "Permanent Chat Logs"

### ISSUE THREAD

**Issue by Blalala6868** [MeteorDevelopment/meteor-client#4890]
### Steps to reproduce

launch meteor clicent with "Permanent Chat Logs" then it crashes.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/lKeWJc9

### Meteor Version

meteor 0.5.8-2157

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
this isnt a meteor issue, Permanent ChatLogs 0.2.4-build20240831 crashes on startup on 1.21.1 no matter what. Maybe try the previous version on modrinth 0.2.3-build20240714
