### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lovehoi4** [MeteorDevelopment/meteor-client#4892]
### Describe the bug

xray dosent work

### Steps to reproduce

i enbaled x ray 

### Meteor Version

0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Send a screenshot of your mods folder

**Comment by Wide-Cat** [comment]
reopen when you attach a screenshot of your mods folder

**Comment by Wide-Cat** [comment]
update sodium to 0.6.0
