### ISSUE TITLE
[Bug] Meteor not compatible with Particular

### ISSUE THREAD

**Issue by Bakbuz2** [MeteorDevelopment/meteor-client#4894]
### Describe the bug

In my opinion it should since particular isn't a mod that adds anything special and is client sided, it's nothing related to meteor

### Steps to reproduce

I added particular meteor and owo-lib (particular dependency)

### Meteor Version

meteor-client-0.5.8-2157

### Minecraft Version

Minecraft 1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Posting a [crash log](https://meteorclient.com/faq/getting-log) would be helpful then.
