### ISSUE TITLE
my pickaxe is buggin

### ISSUE THREAD

**Issue by Supernova35911** [MeteorDevelopment/meteor-client#4896]
### Describe the bug

meteor client let me take my pickaxe out of my hotbar

### Steps to reproduce

idk what i did as i had 0 modles enabled

### Meteor Version

1.21

### Minecraft Version

1.21

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
`#allowInventory false`
