### ISSUE TITLE
sodium white screen

### ISSUE THREAD

**Issue by TeaL0L** [MeteorDevelopment/meteor-client#4897]
### Describe the bug

when i use sodium 0.6.0-beta.2 with meteor client my minecraft just shows up white

### Steps to reproduce

install sodium 0.6.0-beta.2 with meteor client

### Meteor Version

2171

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
send your latest.log

**Comment by TeaL0L** [comment]
[latest.log](https://github.com/user-attachments/files/17007144/latest.log)

**Comment by Wide-Cat** [comment]
update sodium extra to 0.6.0-beta.2, nothing to do with meteor
