### ISSUE TITLE
Add entitiy black/white list for No Mining Trace

### ISSUE THREAD

**Issue by E0x72-21** [MeteorDevelopment/meteor-client#4898]
### Describe the feature

Add an black/white list of entitiy for No Mining Trace.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Funtimes909** [comment]
#4914
