### ISSUE TITLE
where can i find the older versions

### ISSUE THREAD

**Issue by Creepzzzz** [MeteorDevelopment/meteor-client#4900]
### Describe the feature

idk why im doing this in issues but i am and i need to find the older versions cus i play on 1.20.1 and that is my main version

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
https://meteorclient.com/faq/old-versions
