### ISSUE TITLE
Crashes at client start

### ISSUE THREAD

**Issue by jharrison123** [MeteorDevelopment/meteor-client#4901]
### Steps to reproduce

I just updated a couple of mods including Sodium and now I meteor crashes my game.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/7hn7U8X

### Meteor Version

meteor-client-0.5.8-2146

### Minecraft Version

MC 1.21

### Operating System

Linux

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Update Meteor to the latest dev build, or downgrade Sodium to 0.5.11 to fix this.

**Comment by jharrison123** [comment]
> Update Meteor to the latest dev build, or downgrade Sodium to 0.5.11 to fix this.

Thanks so much this fixed it!
