### ISSUE TITLE
make speed-mine in damage mode, insta-mine enabled stop creating ghost block

### ISSUE THREAD

**Issue by 4bb0n** [MeteorDevelopment/meteor-client#4904]
### Describe the feature

speed-mine is already OP since you don't need haste 2 but it is the exact same but the only problem is it create quite a lot of ghost block so it is quite annoying to use

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Try using the no ghost block module. Aside from that theres probably not much we can do about it.
