### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Qbobic** [MeteorDevelopment/meteor-client#4907]
### Describe the bug

Module burrow should place a block on your feet. (to protect you from crystals) But when I do that, I get launched in the air, even in singleplayer (where there is no anti cheat)

### Steps to reproduce

1. Activate burrow.
2. No step two lol

### Meteor Version

0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Burrow relies on there being an anticheat in order to rubberband you back down inside the block, it won't work on single player or similar environments
