### ISSUE TITLE
meteor client v0.5.8 build #2147 download link doesn't work

### ISSUE THREAD

**Issue by tdg3001** [MeteorDevelopment/meteor-client#4908]
### Describe the bug

when i open the link and wait 5 seconds i got invalid response error

### Steps to reproduce

1 open the devbuild download link in discord https://meteorclient.com/download?devBuild=2147
2 Waited 5 seconds
3![image](https://github.com/user-attachments/assets/6b00aaa6-0e96-4855-a611-7c7fc04ea322)

### Meteor Version

meteor client v0.5.8 build #2147

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [ ] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Old links are not available, only the last 5 (maybe 10) work at any given time.

**Comment by tdg3001** [comment]
> Old links are not available, only the last 5 (maybe 10) work at any given time.

can you give me the devbuild

**Comment by Big-Iron-Cheems** [comment]
No? I don't keep random builds around, build it yourself as explained on our [guide](https://meteorclient.com/faq/old-versions), or just get 1.21.1 since it still works on 1.21 servers,

**Comment by tdg3001** [comment]
> No? I don't keep random builds around, build it yourself as explained on our [guide](https://meteorclient.com/faq/old-versions), or just get 1.21.1 since it still works on 1.21 servers,

Can you give me the 1.21 tags please so i can build it
