### ISSUE TITLE
packet server disconnect

### ISSUE THREAD

**Issue by therandomdudejajaja** [MeteorDevelopment/meteor-client#4916]
### Describe the bug

there's not much to it, or i just dont know.
![image](https://github.com/user-attachments/assets/0c1433f1-3058-45de-832a-cb75b4c1f9ed)
every time i try enchant it happens. image is not of enchant but of a BaQ dupe on paper.

### Steps to reproduce

.enchant anything

### Meteor Version

0.5.8 #2172

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
#4688
