### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MrEnderman-YT** [MeteorDevelopment/meteor-client#4918]
### Describe the bug

When starting Minecraft, meteor conflicts with sodium.
![error sodium-meteor mc1 21 1](https://github.com/user-attachments/assets/fc65dc55-05c8-4b1d-b997-dd121347a005)

### Steps to reproduce

1. Install Minecraft version Fabric 1.21.1.
2. Download and install sodium mod
3. Download and install Meteor

### Meteor Version

0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Have you considered reading the error message, that clearly tells you to update to at least Sodium `0.6.0-beta.2`?
