### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dino-lgtm** [MeteorDevelopment/meteor-client#4920]
### Describe the bug

i did all the proscesso requests correctly(by-less and what I think) put in the mods folder, so I launched the game, all right until then, but when I went to enter a server, minecraft simply closed, the log is following:

---- Minecraft Crash Report ----
// You're mean.

Time: 2024-09-29 17:32:05
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_44912" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_3188(class_757.java:1085)

-- Affected level --
Details:
	All players: 2 total; [class_745['T3chnoBladeSadS2'/1692, l='ClientLevel', x=-1.35, y=6.00, z=-12.44], class_745['.Mathxtk'/1899, l='ClientLevel', x=3.27, y=6.00, z=9.06]]
	Chunk stats: 256, 90 F: 0 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,1,-1), Section: (at 0,1,15 in 0,0,-1; chunk contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 158240 game time, 149046000 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_746.method_3135()" because "this.field_3729.field_1724" is null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, high_contrast, file/3D Armor Items 1.0 - Copia.zip, file/3D Variated Bookshelves.zip, file/3D items.zip, file/Low Shield.zip, file/LowOnFire_1.20.1.zip, file/SuperSimple3DdripstoneV1.4.zip, file/[1.4.1] Enhanced Boss Bars - Copia.zip, file/crops-3d.zip, file/cubic-sun-moon-vb1-7-4a.zip, file/§eWooden Fishing Rod §b[OF] - Copia.zip, file/§l3D§f+Ladders+v1.1 - Copia.zip, file/Default-Dark-Mode-1.20-2023.7.0.zip, file/Eyeless Fresh Moves v3.0.1.zip, file/FreshAnimations_v1.9.2.zip, file/3D-Item-Blocks.zip, file/totem_overlay y.zip, file/Durability.zip, file/EBE_1.20.x_v1.1.zip, replaymod_lang, Essential Assets, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.11, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1085144576 bytes (1034 MiB) / 2147483648 bytes (2048 MiB) up to 4227858432 bytes (4032 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7535HS with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1681
	Graphics card #0 versionInfo: DriverVersion=31.0.22048.11001
	Graphics card #1 name: NVIDIA GeForce RTX 2050
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25ad
	Graphics card #1 versionInfo: DriverVersion=32.0.15.6109
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Virtual memory max (MB): 28885.43
	Virtual memory used (MB): 18918.09
	Swap memory total (MB): 21504.00
	Swap memory used (MB): 1816.53
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4032M
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20
		baritone: Baritone 1.10.1
		beautifiedchatclient: Beautified Chat Client 2.6
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		bobby: Bobby 5.0.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		camerautils: Camera Utils 1.20.1-1.0.14
		chat_heads: Chat Heads 0.12.10
		cicada: CICADA 0.8.3+1.20.1
		citresewn: CIT Resewn 1.1.5+1.20.1
			citresewn-defaults: CIT Resewn: Defaults 1.1.5+1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		controlling: Controlling For Fabric 12.0.2
		durabilityviewer: Giselbaers Durability Viewer 1.20-fabric0.83.0-1.10.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.20
		elementa: Elementa 665
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
			player-animator: Player Animator 1.0.2-rc1+1.20
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential: Essential 1.3.4.1
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		essential-dependencies: Essential Dependencies 0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.0+kotlin.2.0.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.15.11
		freecam: Freecam 1.2.1+1.20
		gammautils: Gamma Utils 1.7.16
		iris: Iris 1.7.2+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.12.3.54
		jeresources: Just Enough Resources 1.4.0.247
		malilib: MaLiLib 0.16.3
		meteor-client: Meteor Client 0.5.4
			baritone-meteor: Baritone 1.20.1-SNAPSHOT
		minecraft: Minecraft 1.20.1
		minecraftcapes: MinecraftCapes 12.3.7
		modmenu: Mod Menu 7.2.2
		mousetweaks: Mouse Tweaks 2.26
		mru: Mineblock's Repeated Utilities 1.0.0+1.20.1+fabric
		notenoughanimations: NotEnoughAnimations 1.7.4
		org_jetbrains_annotations: annotations 23.0.0
		replaymod: Replay Mod 1.20.1-2.6.17
			mixinextras: MixinExtras 0.3.6
		searchables: Searchables 1.0.2
		showmeyourskin: Show Me Your Skin! 1.9.0+1.20
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.3+1.20
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sodiumdynamiclights: Sodium Dynamic Lights 1.0.1
			forgeconfigapiport: Forge Config API Port 8.0.0
		sodiumextras: Sodium Extras 1.0.3
		taterzens: Taterzens 1.11.7
			config2brigadier: Config to Brigadier 1.2.6
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.0-rc.2+1.20-rc1
			server_translations_api: Server Translations API 2.0.0-beta.2+1.19.4-pre2
				packet_tweaker: Packet Tweaker 0.3.1+23w06a
			sgui: sgui 1.2.2+1.20
		universalcraft: UniversalCraft 362
		vigilance: Vigilance 306
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerobetterpvp: Better PVP 24.4.0
	Loaded Shaderpack: (off)
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2050/PCIe/SSE2 GL version 3.2.0 NVIDIA 561.09, NVIDIA Corporation
	Window size: 3840x2126
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, high_contrast, file/3D Armor Items 1.0 - Copia.zip, file/3D Variated Bookshelves.zip, file/3D items.zip, file/Low Shield.zip, file/LowOnFire_1.20.1.zip, file/SuperSimple3DdripstoneV1.4.zip, file/[1.4.1] Enhanced Boss Bars - Copia.zip, file/crops-3d.zip, file/cubic-sun-moon-vb1-7-4a.zip, file/§eWooden Fishing Rod §b[OF] - Copia.zip, file/§l3D§f+Ladders+v1.1 - Copia.zip, file/Default-Dark-Mode-1.20-2023.7.0.zip, file/Eyeless Fresh Moves v3.0.1.zip, file/FreshAnimations_v1.9.2.zip, file/3D-Item-Blocks.zip, file/totem_overlay y.zip (incompatible), file/Durability.zip (incompatible), file/EBE_1.20.x_v1.1.zip
	Current Language: pt_br
	CPU: 12x AMD Ryzen 5 7535HS with Radeon Graphics 

-- Meteor Client --

Version: 0.5.4

[[ Active Modules ]]

[Misc]:
discord-presence

### Steps to reproduce

.

### Meteor Version

0.5.14 (i think)

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Meteor 1.20.1 is not supported, the issues are used to report bugs on the latest dev build.
Anyways, on 1.20.1 you should use Sodium 0.5.3 or lower to fix this crash if I'm not mistaken.
