### ISSUE TITLE
Cannot xray with sodium installed

### ISSUE THREAD

**Issue by x21tewntyone** [MeteorDevelopment/meteor-client#4925]
### Describe the bug

this xray feature broken with sodium 
![image](https://github.com/user-attachments/assets/078afb10-d37b-4c54-a004-2e11b848f749)

### Steps to reproduce

1. I reinstalled meteorclient Tlauncher(notinstalled sodium) > Legacy Launcher(soudium installed)

### Meteor Version

0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
What's the issue exactly, that picture explains nothing. Also send a picture of your mods folder

**Comment by x21tewntyone** [comment]
i using sodium with meteor, i want to xray it has nothing(not working)
![image](https://github.com/user-attachments/assets/0828891c-37ca-420a-aa12-c7e9efcb3f22)
i want xray but, didnt work if using sodium.

**Comment by x21tewntyone** [comment]
pls fix sodium xray

**Comment by Wide-Cat** [comment]
update your version of sodium to 0.6.0-beta.1
