### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by skl1nke** [MeteorDevelopment/meteor-client#4928]
### Describe the feature

> **_Hello dear Meteor client developers_, I ask you to add support for the _Vulkan_ mod for weak devices**

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
unlikely to happen
