### ISSUE TITLE
[Suggestion] AutoSleep

### ISSUE THREAD

**Issue by HayzDev** [MeteorDevelopment/meteor-client#4934]
### Describe the feature

Automatically sleep in nearby beds during thunderstorms or nighttime

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by git4rker** [comment]
imo absolutely not worth adding into the base client

**Comment by Wide-Cat** [comment]
what he said
