### ISSUE TITLE
[Suggestion] add item frames to block esp

### ISSUE THREAD

**Issue by githubshit11** [MeteorDevelopment/meteor-client#4935]
### Describe the feature

add item frames to block esp

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 19MisterX98** [comment]
item frames arent blocks. You can highlight them with normal esp

**Comment by Wide-Cat** [comment]
See misterxs comment
