### ISSUE TITLE
Crash When Saving World

### ISSUE THREAD

**Issue by UnknownUser010** [MeteorDevelopment/meteor-client#4939]
### Describe the bug

When i try to save the world with only meteor mod it crashes with error -1 in minecraft launcher (Original Launcher)

### Steps to reproduce

1. Create new world
2. Click on save world
3. And it cash

### Meteor Version

0.5.7

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
1. You used the bug form to report a crash
2. You reported a crash, but did not provide a crash log

Kindly provide the log.

**Comment by Big-Iron-Cheems** [comment]
Closing as log is missing.
