### ISSUE TITLE
Meteor-Sodium crash

### ISSUE THREAD

**Issue by madeline-yana** [MeteorDevelopment/meteor-client#4940]
### Steps to reproduce

1. Have Meteor Client installed
2. Install Sodium
3. crash

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/uzjJXPJ

### Meteor Version

Meteor Dev 1.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [x] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
update meteor to the latest dev build, has been fixed
