### ISSUE TITLE
Game crashes when using .enchant

### ISSUE THREAD

**Issue by AykhanUV** [MeteorDevelopment/meteor-client#4942]
### Steps to reproduce

I tried to enchant using .enchant command and game froze then crashed

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Hp5EhXY

### Meteor Version

meteor-client-0.5.8-2147.jar

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
known issue, we have no idea when its going to be fixed
