### ISSUE TITLE
[Bug] I don't get the aimbot:c

### ISSUE THREAD

**Issue by xHxpnotic** [MeteorDevelopment/meteor-client#4943]
### Describe the bug

I want to use the aimbot and it doesn't wo
![imagen_2024-10-08_082551194](https://github.com/user-attachments/assets/ec04bdbd-b85c-4278-a899-ea3f0ec31306)
rk anywhere

### Steps to reproduce

ummm no hablo ingles xd

### Meteor Version

1.21

### Minecraft Version

1.21.1

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Aim Assist was removed a long time ago.
Use Kill Aura instead.
