### ISSUE TITLE
Crash on Start-Up with Big Globe and Distant Horizons

### ISSUE THREAD

**Issue by UnburnedToast** [MeteorDevelopment/meteor-client#4944]
### Steps to reproduce

I have Big Globe, Distant Horizons, FerriteCore, and Satin API. My guess is an incompatibility with one of those that isnt listed on the incompatibilities list.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/tw3YH4P

### Meteor Version

Meteor 0.5.8-2165

### Minecraft Version

MC 1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Sodium compatibility issue, has been fixed. Update to the latest dev build.

**Comment by UnburnedToast** [comment]
Ty!
