### ISSUE TITLE
[New Feature] Auto lighting

### ISSUE THREAD

**Issue by Blalala6868** [MeteorDevelopment/meteor-client#4945]
### Describe the feature

Automatically place lighting blocks (such as torches, glowstone, sea lanterns, etc.) to illuminate a specified radius around the player to a specified light level.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This is already implemented via the SpawnProofer module.
