### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Akzhol111** [MeteorDevelopment/meteor-client#4948]
### Describe the bug

A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Meteor Client' (meteor-client) 0.5.8-2179 with any version that is compatible with:
		 - sodium 0.5.11+mc1.21
More details:
	 - Mod 'Meteor Client' (meteor-client) 0.5.8-2179 is incompatible with any version before 0.6.0-beta.2 of mod 'Sodium' (sodium), but a matching version is present: 0.5.11+mc1.21!

### Steps to reproduce

1.I turned on Minecraft; 2. This error appears

### Meteor Version

meteor-client-0.5.8-2179

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Akzhol111** [comment]
Sorry, I accidentally chose bag

**Comment by Big-Iron-Cheems** [comment]
As the log says clearly, update Sodium to at least `0.6.0-beta.2`
