### ISSUE TITLE
[Bug] Jump and MiniJump mode in Criticals don't actually deal a critical hit

### ISSUE THREAD

**Issue by ikeafridge4** [MeteorDevelopment/meteor-client#495]
**Describe the bug**
To deal a critical hit, you have to hit an opponent while going down after a jump. MiniJump and Jump mode on criticals only hit the opponent while going up, thus not dealing a critical hit. 

**To Reproduce**
1. Go to Criticals module. 
2. Click on Jump mode or MiniJump mode
3. Turn Killaura on. 

**Expected behavior**
To work as expected, these two modes should swing the sword while going down, instead of up. 

**Screenshots**
link to mediafire with short clip of issue
https://www.mediafire.com/file/56cqnevh0l6kgxg/Meteor_Client_0.4.2_2021-04-13_19-08-02.mp4/file

**Additional context**
1.16.5, Metor 0.4.2 dev-build 730
Mods:
baritone-api-fabric-163.jar
dark-loading-screen-1.5.0.jar
fabric-api-0.32.0+1.16.jar
lithium-fabric-mc1.16.5-0.6.4.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar
meteor-client-0.4.2-718.jar
modmenu-1.16.8.jar
multiconnect-1.3.34.jar
notenoughcrashes-3.1.8-fabric.jar
phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
raisedclouds-1.0.0.jar
sodium-extra-0.2.2.jar
sodium-fabric-mc1.16.3-0.1.0.jar

**Comment by ikeafridge4** [comment]
had to add the clip as mediafire because github only allows files that are less than 10mb

**Comment by RedCarlos26** [comment]
Does the bug also happen in single player?

**Comment by ikeafridge4** [comment]
i tested this in singleplayer and in multiplayer. same result. might just be a config issue though, not sure

**Comment by RedCarlos26** [comment]
Hum ok. I'm gonna investigate into that tomorrow

**Comment by MineGame159** [comment]
Cannot reproduce.
