### ISSUE TITLE
[Suggestion] collab with iris shaders

### ISSUE THREAD

**Issue by iosifeistderking2** [MeteorDevelopment/meteor-client#4955]
### Describe the feature

it would be great to work with them because it allows players to put in the features from iris shaders and meteor client in the mods folder in minecraft

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Iris already works with Meteor, so I don't see what you're trying to suggest.
