### ISSUE TITLE
Player Blocks

### ISSUE THREAD

**Issue by UrAdoptedMom** [MeteorDevelopment/meteor-client#4959]
### Describe the feature

A feature where it highlights and traces blocks places down by players

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
It's not that easy.
