### ISSUE TITLE
Nametags not in the correct place

### ISSUE THREAD

**Issue by antonii1357** [MeteorDevelopment/meteor-client#496]
So when I use the nametags module, they display but not on top of the player, they just display under the ground
**To Reproduce**
1.  activate the nametag module
2. Go near players
3. See error

**Expected behavior**
To see the nametags and armor of any player above his head and not under the ground

I'm currently using the latest version of meteor client on 
![unknown](https://user-images.githubusercontent.com/75284544/114652268-28a25500-9cab-11eb-89a2-0104a3cc425e.png)
1.16.5

**Comment by MineGame159** [comment]
https://github.com/MeteorDevelopment/meteor-client/issues/263
