### ISSUE TITLE
[Bug] file wont respond 

### ISSUE THREAD

**Issue by mxz-42** [MeteorDevelopment/meteor-client#4960]
### Describe the bug

when i download it it show a blank picture
![image (1)](https://github.com/user-attachments/assets/45f6f6f2-d207-4c84-925c-6f7332de0858)

### Steps to reproduce

i downloaded the file it look like this
![image (1)](https://github.com/user-attachments/assets/33964ac1-4349-49b0-b174-8c8298decca3)

### Meteor Version

1.21.1

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Tf where did you download it from, getting it from the website it should be a jar file

**Comment by Wide-Cat** [comment]
theres no way this was downloaded from the official website, get it from there next time
