### ISSUE TITLE
[Bug] BlockESP 

### ISSUE THREAD

**Issue by UrAdoptedMom** [MeteorDevelopment/meteor-client#4961]
### Describe the bug

Whenever I turn on BlockESP, it crashes the entire game

### Steps to reproduce

1. Turn on the module

### Meteor Version

1.20.6

### Minecraft Version

1.20.6

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
attach a crash report, and next time use the crash report template

**Comment by Wide-Cat** [comment]
nvm 1.20.6 is unsupported, if you cant reproduce it on the latest dev build we arent going to investigate further
