### ISSUE TITLE
ggg

### ISSUE THREAD

**Issue by Noeggnolife** [MeteorDevelopment/meteor-client#4963]
### Steps to reproduce

When I enter the game it automatically logs out

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/qy1AITj

### Meteor Version

0.5.8-1.21.1

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Some sort of issue with Norse addon. Try looking in NorseModule
