### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by houpxx** [MeteorDevelopment/meteor-client#4967]
### Describe the bug

meteor crash with sodium

### Steps to reproduce

when i connect to server minecraft is crash

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [ ] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by houpxx** [comment]
[crash-2024-10-18_13.44.21-client.txt](https://github.com/user-attachments/files/17431405/crash-2024-10-18_13.44.21-client.txt)

**Comment by Big-Iron-Cheems** [comment]
We do not provide support for older versions, 0.5.4 is really outdated.
Either update to the latest version, or downgrade sodium to [v0.5.3](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.3).

**Comment by houpxx** [comment]
I love u, thx :3
