### ISSUE TITLE
[FEAT] Add TPaura likes 1.8 clients

### ISSUE THREAD

**Issue by liquidbounce-thebestclient** [MeteorDevelopment/meteor-client#4969]
### Describe the feature

Add A tpaura like 1.8 clients
like open src clients fdp etc
makes it pls
or just skid
it will be useful in pvp
or a tp cryatal aura

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Johnsmith927** [comment]
Go to killaura and enable Random Teleport on Hit (or something similarly called)

**Comment by Johnsmith927** [comment]
It’s added in the meteor rejects addon: https://github.com/AntiCope/meteor-rejects

**Comment by liquidbounce-thebestclient** [comment]
Thanks
