### ISSUE TITLE
Unusual Crash on Fabric 1.21 (Heavily Modded)

### ISSUE THREAD

**Issue by zcraftelite9495** [MeteorDevelopment/meteor-client#4971]
### Steps to reproduce

Can anybody help me figure out what is going on here? Meteor fails to load (causing a game crash). Could it be due to one of my mods?

1. Load my modpack
2. Game crash occurs right before the client finishes loading mixins.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/0Ym0UHH

### Meteor Version

0.5.8 DEV 2137

### Minecraft Version

MC 1.21

### Operating System

Windows 11

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
update meteor to the latest dev build

**Comment by zcraftelite9495** [comment]
Is the latest dev build compatible with 1.21
