### ISSUE TITLE
[Suggestion] Minecraft Font in Settings

### ISSUE THREAD

**Issue by RogatkaMC** [MeteorDevelopment/meteor-client#4972]
### Describe the feature

I think it would be neat to have the Minecraft font (Mojangles or something) in the fonts list. The closest one right now is Pixelation, which is used on a few newer servers. Not sure if there's any copyright problems with having the official font in the game, but it would be cool to see in the client.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 0xTas** [comment]
Meteor loads its font selection from your system, you can already do this.

**Comment by RogatkaMC** [comment]
How do I add it?

**Comment by RogatkaMC** [comment]
Nevermind, just realized how silly I was. Didn't know that the default font for the client WAS the Minecraft font already and didn't see the custom font toggle at the top of the list, my apologies.
