### ISSUE TITLE
Sodium 5.11.0 crashes despite being the recommended version

### ISSUE THREAD

**Issue by RugRatt1** [MeteorDevelopment/meteor-client#4974]
### Steps to reproduce

Launching latest meteor client (0.5.8 - 2188) crashes the game. I've tried using the other sodium versions (sodium-fabric-0.5.11+mc1.21) to the latest available for 0.21.1 (sodium-fabric-0.6.0-beta.2+mc1.21.1).

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/UFy8FLM

### Meteor Version

Meteor 0.5.8 - 2188

### Minecraft Version

MC 0.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
`sodium-fabric-0.6.0-beta.2+mc1.21.1` should have worked, try it again and send the crash report

**Comment by 4bb0n** [comment]
It didn't work, I have the same problem and tried both of the new sodium 1.21 Beta I just simply removed sodium instead

**Comment by Wide-Cat** [comment]
The latest dev build is compatible with sodium 0.6.0-beta.2. If meteor crashes with that verison of sodium open another issue
