### ISSUE TITLE
jesus bug??

### ISSUE THREAD

**Issue by kurumisuki520** [MeteorDevelopment/meteor-client#4975]
### Describe the bug

When I activate the Jesus mod, walking on water or lava makes me bounce on the surface.

### Steps to reproduce

activate Jesus and walking on water or lava

### Meteor Version

meteor client v0.5.8 build #2188

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
send an image of your jesus module config, and what other modules you have enabled

**Comment by kurumisuki520** [comment]
![javaw_8IEY8oGm8V](https://github.com/user-attachments/assets/50dd4308-0d12-41c4-a13f-c3f26fc0a234)
![javaw_W6unoSKe08](https://github.com/user-attachments/assets/42515b9b-e760-4d7f-a967-edd40c244f5f)

**Comment by kurumisuki520** [comment]
> send an image of your jesus module config, and what other modules you have enabled

![javaw_8IEY8oGm8V](https://github.com/user-attachments/assets/049ba188-0875-4530-ae3a-f779918ef584)
![javaw_W6unoSKe08](https://github.com/user-attachments/assets/c9d19c37-a687-473f-b822-549554861f48)

**Comment by Nextinor** [comment]
On what server are you, this could be an AntiCheat issue

**Comment by kurumisuki520** [comment]
> On what server are you, this could be an AntiCheat issue 🪦


I have tried it in single-player mode, and the same issue occurs.

**Comment by kurumisuki520** [comment]
https://github.com/user-attachments/assets/63465e27-8b9f-4f3e-aedd-06d9541934a2

**Comment by Nextinor** [comment]
Can you send the list of addons you have, so we can reproduce it ?
I'm not having any issues with latest dev build

**Comment by kurumisuki520** [comment]
The showcase video does not contain any addons.

> 2024-10-28.21-58-08.mp4

**Comment by Nextinor** [comment]
Well wtf, I tried :[https://youtu.be/7DlXHEtw60M](https://youtu.be/7DlXHEtw60M) no issues as you can see, I don't get it

**Comment by kurumisuki520** [comment]
I also don't know what the problem could be to cause this.

**Comment by Nextinor** [comment]
Let me try on windows

**Comment by Nextinor** [comment]
[https://youtu.be/jKMfsBD_IuE](https://youtu.be/jKMfsBD_IuE)
With this config : 
    Java 21
    Fabric 0.16.7
    PrismLauncher

Well I still can't reproduce the issue, even with the same build.
So let's dive deeper, can you send the java version, fabric version and launcher ?

**Comment by Nextinor** [comment]
![image](https://github.com/user-attachments/assets/386f3cbf-f0b4-471b-a8e9-9953b3a3afaf)
Finally can you also send the modules.nbt file here ?

**Comment by Nextinor** [comment]
`[main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/entity/LithiumEntityCollisions (java.lang.ClassNotFoundException: me/jellysquid/mods/lithium/common/entity/LithiumEntityCollisions)
[19:31:06] [main/WARN]: @Mixin target me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions was not found meteor-client-lithium.mixins.json:LithiumEntityCollisionsMixin from mod meteor-client`

Looks like the issue right

**Comment by Wide-Cat** [comment]
hm ill take a look

**Comment by I-No-oNe** [comment]
> > send an image of your jesus module config, and what other modules you have enabled
> 
> ![javaw_8IEY8oGm8V](https://private-user-images.githubusercontent.com/123770278/379564513-049ba188-0875-4530-ae3a-f779918ef584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjM2NTMsIm5iZiI6MTczMDMyMzM1MywicGF0aCI6Ii8xMjM3NzAyNzgvMzc5NTY0NTEzLTA0OWJhMTg4LTA4NzUtNDUzMC1hZTNhLWY3Nzk5MThlZjU4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQyMTIyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDg1Y2I0MjUxM2VkYzUzN2MzYjE3ZmExZjcxMGUwMTZlZmZhYzNiODAzNDE0NjI2N2M5NDhhMDljMGQ1MDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rTBsSi-GbOe-RWhmIRVsXn2H9g-Ryqv4rXA9bV9gyzc) ![javaw_W6unoSKe08](https://private-user-images.githubusercontent.com/123770278/379564585-c9d19c37-a687-473f-b822-549554861f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjM2NTMsIm5iZiI6MTczMDMyMzM1MywicGF0aCI6Ii8xMjM3NzAyNzgvMzc5NTY0NTg1LWM5ZDE5YzM3LWE2ODctNDczZi1iODIyLTU0OTU1NDg2MWY0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQyMTIyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmM4M2ZlNzM1OWI3MDE5YzNmN2IxMGIyY2FhMDI1M2Q0NmYwNTlhMWVjMGZhOTI2OTkyZDlmMTQ2YTUzYTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rLnG9d8C8LIDfMvLGyt_KGRy_ZPQNjPpYgp5GxowjGI)

What addons are you using?

**Comment by wirl** [comment]
Also ran into this using the release 0.5.8 from the main website, disabling Lithium fixed it. Is there a way to make both work? I don't mind downgrading Lithium if that fixes it.
