### ISSUE TITLE
ShulkerView / ContentView

### ISSUE THREAD

**Issue by sysdefense1337** [MeteorDevelopment/meteor-client#4977]
### Describe the feature

A feature that allows you to view the contents of the shulker when you hover the cursor in the inventory. (Didn't find this feature in addons)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
that should already exist in the Better Tooltips module

**Comment by Big-Iron-Cheems** [comment]
Indeed it is.

**Comment by sysdefense1337** [comment]
like this?
![Screenshot_1](https://github.com/user-attachments/assets/e91d5d88-ad3b-436c-b851-ad8dd623f637)
I meant something like this
![Screenshot_2](https://github.com/user-attachments/assets/328d5e99-b054-4d75-824b-9708e855342e)

**Comment by sysdefense1337** [comment]
Oh, sorry, understood I thought it would be called simpler, inattentive
