### ISSUE TITLE
Game Crashes when switching profiles

### ISSUE THREAD

**Issue by oxriginal** [MeteorDevelopment/meteor-client#4980]
### Steps to reproduce

1. switch profiles

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/b4dAKlS

### Meteor Version

0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
has been fixed as of the latest dev build
