### ISSUE TITLE
1.21.3 update

### ISSUE THREAD

**Issue by E0x72-21** [MeteorDevelopment/meteor-client#4982]
### Describe the feature

update  to 1.21.3

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We are already working on it, you can track the progress at [this](https://github.com/MeteorDevelopment/meteor-client/pull/4970) draft PR.
