### ISSUE TITLE
Game Crashes after i update to the newest meteor client.

### ISSUE THREAD

**Issue by oxriginal** [MeteorDevelopment/meteor-client#4983]
### Steps to reproduce

Updated my Meteor Client to the latest version.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/scxnzLE

### Meteor Version

0.5.8

### Minecraft Version

1.21

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
You didn't update it to the latest dev build. If you go to the website and it keeps downloading that file, try clearing your browser cache and download it again. You'll also need to update sodium alongside meteor because as of the latest dev build we only support sodium 0.6.0-beta.2 and up.
