### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by McFernan404** [MeteorDevelopment/meteor-client#4984]
### Describe the feature

that is compatible with the iris mod for shaders, it only needs to be compatible with that mod and it would undoubtedly be the best hack https://www.curseforge.com/minecraft/mc-mods/irisshaders/files/5485655

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Meteor is already compatible with Iris.
Update Sodium to 0.6.0 beta 2 and Iris accordingly.
