### ISSUE TITLE
Crashes 4 unknown reason

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#4987]
### Steps to reproduce

I saw everything's fine inside modrinth livelog until meteor load then crashes.. i have no idea, it might be related to the quilt library or something. The minecraft show's up with blank white tab then crashes.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/ANINdvc

[crash-2024-10-26_23.24.59.7668-quilt_loader.txt](https://github.com/user-attachments/files/17531427/crash-2024-10-26_23.24.59.7668-quilt_loader.txt)

### Meteor Version

Meteor 0.5.8-2192

### Minecraft Version

MC 1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [x] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by SussyBob** [comment]
[crash-2024-10-26_23.24.59.7668-quilt_loader.txt](https://github.com/user-attachments/files/17531420/crash-2024-10-26_23.24.59.7668-quilt_loader.txt)
that's the same log as i uploaded in mclo.gs

**Comment by 12344313114** [comment]
It looks like "Show Me Your Skin!" is causing the crash

**Comment by SussyBob** [comment]
i'll try deactivating it, wait

**Comment by SussyBob** [comment]
it works, thanks a lot!
