### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by SussyBob** [MeteorDevelopment/meteor-client#4988]
### Steps to reproduce

couldn't figure out why, i installed too many mods.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/nruHfaY

### Meteor Version

Meteor 0.5.8-2192

### Minecraft Version

MC 1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
remove indium (not required with sodium beta 0.6.0), remove sodium extras (no versions compatible with sodium beta 0.6.0)

**Comment by SussyBob** [comment]
I decided to deactivate LambDynamicLights & Remove Reloading Screen because of this reason:
![image](https://github.com/user-attachments/assets/0f754944-a9d7-41dd-b749-242d3e4d84d5)
are there any solution for fabric loader mismatching version? or i just need to wait for the next Quilt Fabric API?

and then here's the latest log:
https://mclo.gs/xcTGNZC - "Complex Error"

**Comment by Wide-Cat** [comment]
remove lazydfu

**Comment by 4bb0n** [comment]
I had the same crash, except it said the those mods are incompatible with Meteor Client and morechathistory mod. I just removed the mods and simply removed them and issue solved. By the way, there is a sodium crash for the latest Meteor dev build and Xray only show exposed block even though the exposed part isn't ticked

**Comment by SussyBob** [comment]
yeah

**Comment by SussyBob** [comment]
LazyDFU is discontinued btw
