### ISSUE TITLE
[Suggestion] tracers in meteor clint

### ISSUE THREAD

**Issue by WITHERERIK** [MeteorDevelopment/meteor-client#4989]
### Describe the feature

i downloaded meteor client from github and i changed tracers to 25600 max distance.
how do i run meteor client file so i can test bigger distances for tracers in mc
![Screenshot 2024-10-27 190903](https://github.com/user-attachments/assets/541a0596-0bd4-4505-8d41-3576326623ba)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
You cannot just "increase" the max distance of tracers, or any other rendering related module.
The server's render distance is what limits you, and there is no way to bypass that.

**Comment by WITHERERIK** [comment]
is it possible to get more distance
