### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Synthyan** [MeteorDevelopment/meteor-client#499]
**Describe the feature**
Piston Aura, An aura that automatically places pistons and redstone blocks to push end crystals into obsidian/bedrock holes to make the opponent die from pushed crystals instead if having to mine obsidian to deal more damage with crystals

**Screenshots**
-

**Additional info**
Helps with crystal aura

**Comment by seasnail8169** [comment]
thank you i will add this right now

**Comment by Synthyan** [comment]
updated the comment

**Comment by Synthyan** [comment]
cuz i posted it with out info by accsidant

**Comment by seasnail8169** [comment]
duplicate of #415
