### ISSUE TITLE
Add built in timer module for speed mine

### ISSUE THREAD

**Issue by 4bb0n** [MeteorDevelopment/meteor-client#4990]
### Describe the feature

I notice that using the Timer hack make mining faster but of course make the FPS drop a bit.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
i dont think this is true

**Comment by DrParanoya** [comment]
The block breaks fast and then reapears, so you still spend the same amount of time mining it

**Comment by Wide-Cat** [comment]
^
