### ISSUE TITLE
Add a module called auto vault or something like that for Ominous vault 1.21

### ISSUE THREAD

**Issue by 4bb0n** [MeteorDevelopment/meteor-client#4991]
### Describe the feature

This module open the Ominous vault at correct timing so you could get your wanted item from the Vault that you selected from the module. e.g(if you chose heavy core, the module open the vault when the heavy core appears in the vault)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
this is not true

**Comment by DesiCow** [comment]
The item display is purely visual and shows which items are in the loot table. You can't influence the item that you get by timing it with the item displayed.

Source: https://minecraft.wiki/w/Vault#Unlocking

**Comment by 4bb0n** [comment]
um actually, I tried and it worked! I also thought it is a myth but it isn't, you just gotta time it correctly. test it in your creative world, when right click it will spit out the item currently in the vault.

**Comment by Wide-Cat** [comment]
Guys I thought it was a myth but I also tried it and it actually worked. We should totally add an ominous vault module to meteor.
