### ISSUE TITLE
CRETAE METEOR TO 1.21.3 PLS

### ISSUE THREAD

**Issue by terrarich** [MeteorDevelopment/meteor-client#4995]
### Describe the feature

thnk u and pls crate this

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Duplicate of #4982
