### ISSUE TITLE
REPOST - auto ominous vault unlock

### ISSUE THREAD

**Issue by 4bb0n** [MeteorDevelopment/meteor-client#4996]
### Describe the feature

my previous post was closed and people claimed it isn't possible to get the item you want out of a vault by opening a vault at the correct timing. But actually, I tried and it worked! I also thought it is a myth but it isn't, you just gotta time it correctly. test it in your creative world, when right click it will spit out the item currently in the vault.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by 4bb0n** [comment]
previous Issue: #4991

**Comment by Wide-Cat** [comment]
This guy understands it. I tried it earlier and it worked. We need to add it to meteor.

**Comment by RacoonDog** [comment]
i’m sorry to tell you this, but you’ve been gotten by confirmation bias

this is not possible

**Comment by Big-Iron-Cheems** [comment]
Do yourself a favor and look at the source code related to how the vault loot table is handled.
You will see that the result is pre determined, there is nothing the client can do to force a specific drop.

**Comment by 4bb0n** [comment]
Sorry, maybe it's because I'm lucky, I got it 3 times a row so I thought it
was real
