### ISSUE TITLE
[Suggestion] Have you ever heard of EaglercraftX

### ISSUE THREAD

**Issue by ghjjhghj** [MeteorDevelopment/meteor-client#4998]
### Describe the feature

EaglercraftX is Minecraft On the WEB! Soo if you don't mine can you make metor Client jar file for Eaglercraft soo you make the jar file into .js for example Metor.jar into Metor.js

Thx

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by MineGame159** [comment]
Not possible
