### ISSUE TITLE
Teleport command

### ISSUE THREAD

**Issue by 4bb0n** [MeteorDevelopment/meteor-client#5000]
### Describe the feature

add a command that let you teleport anywhere! Meteor Rejects addons have this feature but you can only teleport over small distances. Another meteor addon that had this feature is Vector Addon but is discontinued and there is an unfixed crash for it

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
You cannot teleport over long distances without OP or the server kicking you.
