### ISSUE TITLE
Where can i find the 1.21 version in git hub?

### ISSUE THREAD

**Issue by Fabri209** [MeteorDevelopment/meteor-client#5003]
### Describe the feature

Where can I find the 1.21 version in this page i already checked all the folders bit I can't find it

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
We have stated multiple times in our Discord and in previously closed issues that 1.21.1 is also compatible with 1.21.
Please checkout the [`fabric.mod.json`](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/resources/fabric.mod.json#L48) as stated in the FAQ next time.
