### ISSUE TITLE
vulkan mod crashes

### ISSUE THREAD

**Issue by VitzS7ven** [MeteorDevelopment/meteor-client#5007]
### Steps to reproduce

I know that Meteor probably doesn't support Vulkan, but it could support it, it's very good and it's becoming famous on my PC, it was better than Sodium and anyone else, I have almost no FPS without it and it's not possible to use it with Meteor, which I can't leave or even change.

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Yg3DMsr

### Meteor Version

0.5.8

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
> it could support it

Sure, if someone is willing to make a PR and provide all the necessary changes, we might consider it.
But we have no interest/need to support a mod that is still not at 100% parity with the standard OpenGL implementation.

As for the low FPS: your mods are a mess, slapping together 30 mods that all "optimise" something doesn't make your game run better.

**Comment by VitzS7ven** [comment]
so i just take them off?
