### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by om3ga6400** [MeteorDevelopment/meteor-client#5009]
### Describe the feature

Could you make a auto updater like essential dose so we don't have to go to the website and download it everytime. If that would impact the ad revenue you could make it like a premium feature or something

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Updating mods is not the responsibility of the mod itself, that is for the user to handle.
You can't really hot reload mods as well, you'd have to restart the game anyways.

Nobody forces you to update with each released dev build, unless you truly care about the changes we made in a given commit.

**Comment by om3ga6400** [comment]
I want to be forced to update because its so annoying to have to delete meteor and baritone and then go to the site and download both then put them back its so annoying

**Comment by Big-Iron-Cheems** [comment]
You still have to update all your other mods whenever the game updates, this is a non-issue.

**Comment by om3ga6400** [comment]
I don't mean when my game updates, I mean when meteor updates I wish it would auto replace it

**Comment by om3ga6400** [comment]
> You still have to update all your other mods whenever the game updates, this is a non-issue.

i made one for baritone and meator 

@echo off
setlocal

set "METEOR_URL=https://meteorclient.com/api/download?devBuild=latest"
set "BARITONE_URL=https://meteorclient.com/api/downloadBaritone"
set "MOD_DIR=%INST_MC_DIR%\mods"

echo Updater made by om3ga6400

del /Q "%MOD_DIR%\meteor-client*.jar"
del /Q "%MOD_DIR%\baritone*.jar"

curl -L -o "%MOD_DIR%\meteor-client-latest.jar" "%METEOR_URL%"
curl -L -o "%MOD_DIR%\baritone-latest.jar" "%BARITONE_URL%"

endlocal

and then 
![{F1BDBB6D-4894-4C9E-88CF-A83E07326624}](https://github.com/user-attachments/assets/304a7a56-9178-4a96-a8ab-65c8c530bf1a)
