### ISSUE TITLE
Suggestion Piston Aura

### ISSUE THREAD

**Issue by Roxy333** [MeteorDevelopment/meteor-client#501]
**Describe the feature**
Piston Aura helps with killing people with end crystals it will automatically place pistons and redstone blocks against end crystals to kill players in anti-crystal holes faster instead of having to mine the obsidian

**Screenshots**
-

**Additional info**
-

**Comment by Roxy333** [comment]
just found comment 415 and 499 nice

**Comment by RedCarlos26** [comment]
Duplicate of #415
