### ISSUE TITLE
conflicts with meteor and sodium

### ISSUE THREAD

**Issue by MetalAddictCFH** [MeteorDevelopment/meteor-client#5011]
### Steps to reproduce

install meteor while sodium and iris are installed
game crashes on startup

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/LfnMnKS

### Meteor Version

0.5.8-2200

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Starmania** [comment]
This is intended behavior. The latest dev build is compatible with sodium 0.6.0-beta.2. Please update your mods accordingly.

**Comment by MetalAddictCFH** [comment]
I switched the version of sodium I had to sodium 0.6.0-beta.2 and still got a crash. log is below
https://mclo.gs/nybMMtf

**Comment by MetalAddictCFH** [comment]
I updated Iris and it works with no crashes

**Comment by lyionqq** [comment]
@MetalAddictCFH ты решил проблему с конфликтом meteor и sodium?
