### ISSUE TITLE
Meteor version setting incorrece

### ISSUE THREAD

**Issue by vanvac** [MeteorDevelopment/meteor-client#5012]
### Steps to reproduce

launch using meteor client build 0.5.9-2202 
![image](https://github.com/user-attachments/assets/284a5570-74d9-4fe7-80d0-3508dd40a702)
Fix:
change fabricmod.json file to sy mc version 1.21.3?

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/Ht14Ab3

### Meteor Version

meteor 0.5.9- 2202

### Minecraft Version

1.21.3

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by vanvac** [comment]
![image](https://github.com/user-attachments/assets/bc404300-efc8-41cb-8d95-484366fcb841)

**Comment by MineGame159** [comment]
2202 is not the dev build with the .3 commit. You want 2203
