### ISSUE TITLE
Meteorclient 0.5.9 incompatible with 1.21.3

### ISSUE THREAD

**Issue by QuarkOS** [MeteorDevelopment/meteor-client#5013]
### Describe the bug

The version is described as 1.21.3, however it says it is incompatible with this version.

### Steps to reproduce

![Screenshot 2024-11-17 144116](https://github.com/user-attachments/assets/9a71a572-6cf5-4f5c-a13c-727640b6d0aa)

### Meteor Version

Meteor 0.5.9

### Minecraft Version

MC 1.21.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Oh my god

**Comment by MineGame159** [comment]
https://github.com/MeteorDevelopment/meteor-client/issues/5012#issuecomment-2481271821
