### ISSUE TITLE
Lithium issue

### ISSUE THREAD

**Issue by kurumisuki520** [MeteorDevelopment/meteor-client#5014]
### Describe the bug

When enabling the Lithium mod and joining a server, I encounter a "Connection Lost: Network Protocol Error."
![image](https://github.com/user-attachments/assets/3fa31494-6989-4eb0-bfc1-d939500c73bf)

### Steps to reproduce

enable lithium joining server

### Meteor Version

meteor client v0.5.9 build #2203

### Minecraft Version

1.21.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Festnt** [comment]
The exact same thing happens to me in a linux (EndeavourOS, a fork of arch, to be exact) machine, though even singleplayer worlds don't work (minecraft crashes). Disabling Lithium allows joining servers and singleplayer worlds.

**Comment by kurumisuki520** [comment]
In the latest version of Meteor Client v0.5.9 build #2204, the issue has been fixed.
