### ISSUE TITLE
[Bug] ".input sprint" does not work

### ISSUE THREAD

**Issue by 6x9cmc** [MeteorDevelopment/meteor-client#5015]
### Describe the bug

does literly nothin

### Steps to reproduce

...

### Meteor Version

1.21.1 v0.5.8 (latest version)

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
I'm not sure what you're expecting, the [code](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/commands/commands/InputCommand.java) shows what it does.
