### ISSUE TITLE
Menu is darker when opened from title screen

### ISSUE THREAD

**Issue by moxvallix** [MeteorDevelopment/meteor-client#5017]
### Describe the bug

Menu renders darker when opened from the title screen. Kinda seems like its rendering behind the title screens dark overlay but idk.

![2024-11-19_16 52 27](https://github.com/user-attachments/assets/e0c51007-d18c-4e48-bd68-a395f037c7b6)
![2024-11-19_16 52 59](https://github.com/user-attachments/assets/93fe5ec0-ca91-4ead-b58d-e5ee320c4a1b)

### Steps to reproduce

Open the menu from the title screen, and also from in-game, and just look.

### Meteor Version

0.5.9-2203

### Minecraft Version

1.21.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by arizotaz** [comment]
I had have the same issue but it's worse with a texture pack that uses a texture for menu background. It seems like the Meteor menus are being rendered behind the vanilla menus.   With a texture pack, (such as programmer art) the menu is entirely invisible.

**Comment by MineGame159** [comment]
Fixed in 46b7fbab9a2d480728aa9c560305f307c7bb7da7.
