### ISSUE TITLE
Meteor incombatibility with Sodium 0.6.0 beta 5

### ISSUE THREAD

**Issue by TheSilverFoxes** [MeteorDevelopment/meteor-client#5018]
### Steps to reproduce

Using Fabulously Optimized (turned off all the incompatible mods) + Baritone + Meteor

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/lCIZwSg

### Meteor Version

0.5.9-2203

### Minecraft Version

1.21.3

### Operating System

Linux

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Update Sodium to the stable 0.6.0 release, no we longer use the betas.
