### ISSUE TITLE
inventory hud shows wrong texture

### ISSUE THREAD

**Issue by Powie69** [MeteorDevelopment/meteor-client#5020]
### Describe the bug

inventory hud shows wrong texture
the texture also changes depending if i have items in my inventory/hotbar

no other resource pack or mods are loaded other than meteor

![image](https://github.com/user-attachments/assets/442aac43-04ac-425f-97c5-dbd4f70e59d2)
![image](https://github.com/user-attachments/assets/0a56c51c-9328-4544-8dec-0b11fe2404f0)
![image](https://github.com/user-attachments/assets/458132ef-90b8-48e2-9293-46f0e60ff9c6)
![image](https://github.com/user-attachments/assets/1069551f-9f07-4e56-affa-bcbaef5bd3f0)
![image](https://github.com/user-attachments/assets/6dbe5673-227d-481c-84b8-89b163e3031c)

### Steps to reproduce

1. make an inventory hud element

### Meteor Version

0.5.9 2206

### Minecraft Version

1.21.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by MineGame159** [comment]
Fixed in 2f50225e8e63ea9f03e097d2535670e26d943d19.
