### ISSUE TITLE
[Bug] flight

### ISSUE THREAD

**Issue by sunnygt19** [MeteorDevelopment/meteor-client#5023]
### Describe the bug

when i try and fly its like i get stuck i can try and move about but i get teleported back to my orignal spot and i

### Steps to reproduce

just trying to fly causes the bug

### Meteor Version

dev build 0.5.9 (1.21.3)

### Minecraft Version

1.21.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
Sounds like an anticheat issue. If you don't think it's that, then reopen the issue and send a video illustrating what you mean.
