### ISSUE TITLE
[Suggestion] FLAG CHECKS

### ISSUE THREAD

**Issue by veiderTrajektoor** [MeteorDevelopment/meteor-client#5025]
### Describe the feature

This is pretty important because we need to see when mod's have reasons go come and look at us. Please, and also some anti vanish for us to see the vanished staff!!

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Meteor is blatant by design, since it's made for anarchy servers.
We cannot magically let you know which checks you are flagging for any given anticheat,
nor is it possible in any way to detect vanished players, as they are effectively not sent to you by the server.

**Comment by veiderTrajektoor** [comment]
Okay, goof to hear. thanks!
