### ISSUE TITLE
Crash on world join because of Sodium

### ISSUE THREAD

**Issue by Ex-RaidBoss** [MeteorDevelopment/meteor-client#5028]
### Steps to reproduce

It crashes when joining a singleplayer or multiplayer world if you have sodium installed along with meteor, works normally without sodium. Tested all the sodium versions for 1.21.1 all are the same. Meteor version is the one at the official website 

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/La1aYhO

### Meteor Version

Meteor 0.5.8

### Minecraft Version

MC 1.21.1

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Big-Iron-Cheems** [comment]
Downgrade it to [this](https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.0-beta.4-fabric) version and see if the issue persists.
Unfortunately, the 1.21.1 release of Meteor relied on a beta version of Sodium, and we can't guarantee that the 0.6.0 release works with it, nor can we backport fixes to it.

**Comment by Ex-RaidBoss** [comment]
Seems like it still crashes on world join, the only real solution would be to not use sodium at all
