### ISSUE TITLE
Save Waypoints when disconnecting

### ISSUE THREAD

**Issue by tinmarr** [MeteorDevelopment/meteor-client#503]
**Describe the feature**
When you disconnect from a server, your waypoints only save if you saved a profile. It would be nice if they would save no matter what.

This might be because I turned on "load on join" in the profile options. So maybe an autosave feature?

**Comment by seasnail8169** [comment]
I am planning to do this thanks. Im gonna close this issue since its not completely relevant to what i plan to do but i appreciate you pointing it out, thanks.
