### ISSUE TITLE
Memory Leak on build 2209 (1.21.3)

### ISSUE THREAD

**Issue by Jatc252** [MeteorDevelopment/meteor-client#5033]
### Describe the bug

Meteor Client alone, or in combination with other mods appears to have a memory leak. I have isolated all of my running mods individually and found that when Meteor is enabled, RAM usage of Minecraft steadily increases until it reaches 100% of memory I allocate to Minecraft (I increased it to 19GB for testing). Minecraft becomes unplayable due to garbage collection every ~500ms. Mods below:

![image](https://github.com/user-attachments/assets/50d50e78-682c-41a4-83a3-e6ec4cef668f)

### Steps to reproduce

Run Meteor (build 2209) and play for a while. RAM usage will increase to high 90%s

### Meteor Version

0.5.9-2209

### Minecraft Version

1.21.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
Seems to be a hard to diagnose issue, would you be open to joining the discord server in order to discuss this further?

**Comment by Banana1059** [comment]
I'm having the same issue and may have found something.
I'm not able to check the exact wording but I found that Wireframe Renderer was using a lot of memory

**Comment by Jatc252** [comment]
> I'm having the same issue and may have found something. I'm not able to check the exact wording but I found that Wireframe Renderer was using a lot of memory
> 
> Edit- Believe this is the file: /src/main/java/meteordevelopment/meteorclient/utils/render/WireframeEntityRenderer.java

I've tested flying around a creative world with ESP on and ESP off, and found with ESP on Minecraft went up to ~7GBs after 17 mins and with ESP off, I got to 6.6GB in just under an hour. I restarted Minecraft between tests and also turned off storage ESP for both as I assume that storage ESP is just an extension of entity ESP. Thanks for your insight @Banana1059

**Comment by Banana1059** [comment]
> I've tested flying around a creative world with ESP on and ESP off, and found with ESP on Minecraft went up to ~7GBs after 17 mins and with ESP off, I got to 6.6GB in just under an hour. I restarted Minecraft between tests and also turned off storage ESP for both as I assume that storage ESP is just an extension of entity ESP. Thanks for your insight @Banana1059

Ive rebuild meteor with a single word changed and so far it seems to be working just fine without memory increasing massively
In the mentioned file,
> Edit- Believe this is the file: /src/main/java/meteordevelopment/meteorclient/utils/render/WireframeEntityRenderer.java
I just changed the `matrices.push();` on line 67 to `matrices.pop();`
Feel free to test it and see if the same thing happens or if it seems fine

**Comment by Jatc252** [comment]
Fixed in #5037
