### ISSUE TITLE
Chest stealer

### ISSUE THREAD

**Issue by HackerGavin** [MeteorDevelopment/meteor-client#5049]
### Describe the feature

When you open the chest there will be buttons on the left that say steal items  and another button that says put items or smth that puts everything in your inv into the chest

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This is already a feature, look into the InventoryTweaks module.
