### ISSUE TITLE
[Suggestion] Ability to control meteor modules through web requests

### ISSUE THREAD

**Issue by Banana1059** [MeteorDevelopment/meteor-client#5050]
### Describe the feature

There should be a setting to allow the ability to control modules and the module's settings through post requests (using something such as python's Requests module), along with getting information back from meteor (such as player position, world state, a list of all modules, module statuses and their settings, etc). This would be great for people who don't know java to create things for Meteor (such as myself) and could allow for some other things that could be helpful.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
I do not see how accessing modules at runtime, via web requests, will let you do anything useful.
My honest opinion is that you should learn Java if you want to develop anything Minecraft related.

**Comment by Banana1059** [comment]
>  It's better suited for an addon.

Are Meteor addons able to toggle other modules along with their settings within Meteor? And if so is there a docs page for making meteor addons? I know there is a template but I couldn't find any docs for addons.

**Comment by Big-Iron-Cheems** [comment]
An addon can directly interact with any module defined in Meteor (or other addons, as long as you add them to your dependencies).
Also no, there's no docs apart from what's in the addon template repo itself.

**Comment by Banana1059** [comment]
Alright, well time to learn java.
