### ISSUE TITLE
[Suggestion] .seed command 

### ISSUE THREAD

**Issue by Leonn170709** [MeteorDevelopment/meteor-client#5052]
### Describe the feature

Add a .seed command where you can paste the seed if it’s know so that .locate works and it can locate more stuff using the seed

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by vanvac** [comment]
mod; https://modrinth.com/mod/seedmapper/versions
source: https://github.com/xpple/SeedMapper/

**Comment by Wide-Cat** [comment]
that or online tools like chunkbase
