### ISSUE TITLE
God mode or insta kill

### ISSUE THREAD

**Issue by HackerGavin** [MeteorDevelopment/meteor-client#5056]
### Describe the feature

Can’t die or instantly kill people

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
That is impossible without admin perms.
Kindly think twice about the feasibility of things before suggesting features.
