### ISSUE TITLE
Freecam rotating other players instead of your own

### ISSUE THREAD

**Issue by Wapplee** [MeteorDevelopment/meteor-client#5057]
### Describe the bug

When you enable freecam if you fly by other players it will make them turn.

### Steps to reproduce

1. Turn on FreeCam
2. Go near a player
3. Strafe around until bug happens.

### Meteor Version

0.5.9

### Minecraft Version

1.21.3

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
should be resolved as of fbdc927f118e636396a67e62fd193f1948239b79
