### ISSUE TITLE
Build failed "Could not open proj generic class cache for build file"

### ISSUE THREAD

**Issue by Almondski** [MeteorDevelopment/meteor-client#5059]
### Describe the bug

> Configure project :
Fabric Loom: 1.2.8

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'meteor-client-0.5.4'.
> Could not open proj generic class cache for build file 'C:\Users\97154\Downloads\meteor-client-0.5.4\build.gradle' (C:\Users\97154\.gradle\caches\8.1.1\scripts\bzm3xidqi5hb620wx98v9g8on).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 67

### Steps to reproduce

followed the steps in your installation guide but build keeps failing

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
use java 17 to build it
