### ISSUE TITLE
[Suggestion] Static flight

### ISSUE THREAD

**Issue by hashalite** [MeteorDevelopment/meteor-client#506]
**Describe the feature**
A "Static" flight option that cancels velocity when toggled off.

**Screenshots**
[Current flight](https://i.imgur.com/xLIny3Y.mp4)
[Static flight](https://i.imgur.com/kKuirCd.mp4)

**Comment by seasnail8169** [comment]
change your flight mode to velocity

**Comment by hashalite** [comment]
> change your flight mode to velocity

The first video is using velocity mode.  It doesn't slow you down after flight is toggled off

**Comment by seasnail8169** [comment]
uh

**Comment by seasnail8169** [comment]
ok

**Comment by octoshrimpy** [comment]
This can be closed, right?

**Comment by RedCarlos26** [comment]
I guess so

**Comment by hashalite** [comment]
No, it was closed by mistake. Velocity mode doesn’t have the functionality I described

**Comment by octoshrimpy** [comment]
@hashalite what is missing? Abilities mode you "float" around while flying, like survival. in velocity mode you stop at dead stops. what version are you in, and what other mods do you have installed? It works for me, even on a brand new install, and it looks like it works for everyone I've asked.

**Comment by hashalite** [comment]
> @hashalite what is missing?

1. Toggle flight on velocity mode
2. Hold w
2. Toggle flight off while still holding w

When flight is toggled off, you keep your velocity instead of stopping instantly.  This happens with no other mods installed.

I guess what I'm looking for is an option that stops you instantly when flight is toggled off, like in the second video I linked. It’s a little bit nit-picky, but I just find it easier navigate with this type of flight.

**Comment by octoshrimpy** [comment]
what you're looking for isn't planned features.. what you're asking for is for flight to stop the player _while you still hold down W_. that's ... not only counter-intuitive, but going against user input....

**Comment by hashalite** [comment]
Holy shit please look at the videos I linked.  It doesn’t come to a complete stop, it just cancels the velocity caused by the flight so you don’t go flying after you toggle off.  You should continue moving at the same speed as you would just holding W while falling. Almost every other client I’ve come across does flight this way.

Make the change if you want, I really dont care enough about it to keep arguing with retards on here.

**Comment by seasnail8169** [comment]
> what you're looking for isn't planned features..

Since when do you decide what is a planned feature lol

**Comment by seasnail8169** [comment]
also this really isn't an issue
