### ISSUE TITLE
[Bug] Mod mixmatch

### ISSUE THREAD

**Issue by Paintzx1** [MeteorDevelopment/meteor-client#5060]
### Describe the bug

![Screenshot 2024-12-23 183357](https://github.com/user-attachments/assets/94c12c21-a645-43f0-807d-5c1031164ff9)

### Steps to reproduce

At first it was good but after the server I played in updated. The start to be incompatible mod.

### Meteor Version

Meteor-client-0.5.8

### Minecraft Version

Minecraft 1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by DrParanoya** [comment]
Better Chat from meteor lets you do the exact same thing, just remove morechathistory
