### ISSUE TITLE
Better Chat minor issue

### ISSUE THREAD

**Issue by Risc-A2** [MeteorDevelopment/meteor-client#5067]
### Describe the feature

setting Fancy Chat for weird reason makes the characters unicode the issue is what if a server doesnt like unicode a.k.a blocks messages with unicode characters so it would be nice in Fancy Chat To Add a small config to force it to not use unicode
im not sure if this was fixed since im using 1.20.4 meteor client

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Wide-Cat** [comment]
Literally the whole point of the fancy chat setting is to replace each character with the small capital equivalents. I don't understand what you mean by having it not use unicode. If the server blocks messages with it enabled then disable the setting.

**Comment by Risc-A2** [comment]
okey
