### ISSUE TITLE
randomly crashing when using esp/storage esp/block esp

### ISSUE THREAD

**Issue by stxrdxst** [MeteorDevelopment/meteor-client#5068]
### Steps to reproduce

1. launch mc
2. turn on block esp, esp, and storage esp
3. it randomly crashes anywhere from 10 seconds later - hours later

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/UZn27W8

### Meteor Version

Meteor 0.5.6

### Minecraft Version

MC 1.20.4

### Operating System

Windows

### Before submitting a crash report

- [X] This crash wasn't already reported (I have searched crash reports on GitHub).

- [X] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by RacoonDog** [comment]
1.20.4 is unsupported

**Comment by stxrdxst** [comment]
> 1.20.4 is unsupported

one of the most popular versions of minecraft atm is unsupported, wow ! great client

**Comment by stxrdxst** [comment]
btw ive been using this for almost a year now and it's only happening recently, sometimes in the past it has fps drops (to like <5 fps if i leave mc open for over a day though. vv annoying and only happens on meteor

**Comment by Wide-Cat** [comment]
if you cant reproduce this as of the latest builds its not relevant. Probably a mod compatibility issue anyway
