### ISSUE TITLE
[Bug] Tracers bob up and down when view bobbing is enabled

### ISSUE THREAD

**Issue by hashalite** [MeteorDevelopment/meteor-client#507]
**Describe the bug**
Tracers bob up and down when view bobbing is enabled.

**To Reproduce**
Enable view bobbing
Walk around and observe tracers

**Expected behavior**
Tracers remain fixed to the crosshair regardless of view bobbing

**Screenshots**
https://user-images.githubusercontent.com/71229440/114794785-1aac0d00-9d5b-11eb-946b-fe2f5885fa32.mp4

**Comment by RedCarlos26** [comment]
It was partially foxed in an earlier dev build, but it is still happening even though it is less appealing.

**Comment by MineGame159** [comment]
Fixed
