### ISSUE TITLE
InfinityMiner

### ISSUE THREAD

**Issue by Boneshadow** [MeteorDevelopment/meteor-client#5070]
## Feature Request: InfinityMiner Area Restriction and Looping Mining Solutions

* **InfinityMiner Area Restriction:** Please make it possible to configure InfinityMiner so that it mines only in a selected area, so that it cannot go beyond its borders. This is very helpful for farming.

* **Looping Resource Extraction:** If there are other ways to loop resource extraction, please consider them. For example: when the Auto-Miner updates, the InfinityMiner automatically waits for the mine to update and then starts mining diamond ore itself.

If there are other alternative varieties please tell me I will be very grateful

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
sounds to me like you might be cheating on a prison server
