### ISSUE TITLE
[Bug] problem with autofill items in hotbar

### ISSUE THREAD

**Issue by KietLacThichLapTrinh** [MeteorDevelopment/meteor-client#5071]
### Describe the bug

on my bar always fill pickaxe item and blocks at slots 1 and 9 i dont know how to turn it off can you help me

### Steps to reproduce

install meteor mod

### Meteor Version

all

### Minecraft Version

all

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
It's a baritone setting do #allowInventory false
