### ISSUE TITLE
[Suggestion] Boatphase

### ISSUE THREAD

**Issue by hashalite** [MeteorDevelopment/meteor-client#508]
**Describe the feature**
A Boatphase module similar to Inertia's that allows you to phase through blocks using a boat.

**Comment by GildedS** [comment]
Already in meteor+

**Comment by Declipsonator** [comment]
> Already in meteor+

:trollface:

**Comment by BobIsMyManager** [comment]
Phase

**Comment by seasnail8169** [comment]
Why close?

**Comment by BobIsMyManager** [comment]
Maybe accident

**Comment by hashalite** [comment]
Since its already in + I thought the issue wasn't needed anymore
