### ISSUE TITLE
[Suggestion] Sneak

### ISSUE THREAD

**Issue by zyrafal** [MeteorDevelopment/meteor-client#510]
**Describe the feature**
A clear and concise description of what feature/change is.
Automatically sneaks using packets, so that other players can't see your nameteg. You can still walk normally.
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by rjbarber** [comment]
This is a much needed enhancement! I enthusiastically second this suggestion!

**Comment by Psychogenic88** [comment]
I third this suggestion. 100% needed.

**Comment by C10udburst** [comment]
This can be closed. Added in b3a1bd7fdce1c5aa2fd7b86c5ef0b854bdf986de
