### ISSUE TITLE
[SUGGESTION] Option to name saved proxies

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#513]
**Describe the feature**
As said in the title, adding a box to give a proxy a name.
Could be added in the Optional section, makes it easier to know where you are connecting to.

**Screenshots**
![2021-04-15 21_49_11-Minecraft 1 16 5](https://user-images.githubusercontent.com/52252627/114929894-a9408d00-9e34-11eb-8f64-297adf062730.png)

**Comment by Wide-Cat** [comment]
👍
