### ISSUE TITLE
[Suggestion] Auto Build

### ISSUE THREAD

**Issue by ForBai** [MeteorDevelopment/meteor-client#516]
**Describe the feature**
Look Title
You can build automatic:
Withers
Irongolems
Flat
Wall
Highway
Tower
Highway tunnel
...

**Screenshots**
Look above

**Additional info**
Like the one in SalHack

**Comment by ikeafridge4** [comment]
use baritone bruh

**Comment by ForBai** [comment]
Baritone is slow

**Comment by BobIsMyManager** [comment]
Baritone will walk around and would generally be slower than someone walking forwards and auto building a highway

**Comment by BobIsMyManager** [comment]
Also it would be pog if you could use .json files to be able to make custom auto builds

**Comment by C10udburst** [comment]
There's a [Auto Highway Addon](https://github.com/VoidCyborg/meteor-auto-highway-addon). idk how well it works though

**Comment by ForBai** [comment]
i tried it and it is rly bad i need to say

**Comment by AstroOrbis** [comment]
Maybe something like HighwayTools from KAMI? (It’s a modified version, discord.gg/highways for more info)

**Comment by AstroOrbis** [comment]
Nvm they lost their vanity URL KEKW

**Comment by Wide-Cat** [comment]
> Nvm they lost their vanity URL KEKW

Kek

**Comment by RoastedCheese** [comment]
You can use a schematic with baritone for highways, but we definitely need this for small and quick builds like withers.

**Comment by ForBai** [comment]
After i tested and done much shit the last 22days ifound some things out
1: Placing Blocks in mid air flags you on most servers
2: you need much time too code this
3: you need to code it so that it can place in every direction
4: withers cant be placed diagonal XD
5: Look at my fork of meteor and go under (editing)
6: i am coding my self, i put completly 200hrs in finding info about how it could place things and how you could easily add yourself something that it can build
7: For more info dm me(look down)
Discord: Anemoi#7990
Pls help me :sob:

**Comment by RealHours** [comment]
Already stated previously, but still very true. A way to autobuild other than Baritone would be a good idea.

SalHack made a good version of this, maybe something to look into?

**Comment by ForBai** [comment]
When i am back from vacation i am gona Code it!

**Comment by Dream23322** [comment]
Think about this:

Use lambda
