### ISSUE TITLE
[Bug] HUD menu wont show

### ISSUE THREAD

**Issue by Sharedlines** [MeteorDevelopment/meteor-client#520]
**Describe the bug**
Hello, I'm getting a issue where the mod loads just fine, its just that there is no HUD Ingame. What I mean by this is that the HUD feature in the right shift menu, when I click it, no HUD comes up for me. I know that there should be a HUD there because it did load once, but then went away. I also know because there are outlines for buttons that show up when I hover over some parts of the screen.

**To Reproduce**
I don't know how you would reproduce this, besides running sodium client with meteor I guess?

**Expected behavior**
I expected a HUD that was Seperate from the right shift menu that displayed coords, and other things ( I know what it looks like because I got it to work once, but then it went away)
**Screenshots**

https://cdn.discordapp.com/attachments/767068986772029492/833133000292040704/unknown.png

**Additional context**

My pc is quite slow, so I don't know if this is contributing to it not loading. Minecraft itself is, so I don't see why that would be a issue.
Or, I could just be doing something wrong, who knows.
One final thing, I'm running Sodium client with Meteor on 1.16.5
I also looked around everywhere to see if this was a known bug, and I didn't find anything.

**Comment by seasnail8169** [comment]
Do you have the hud module enabled?

**Comment by Wide-Cat** [comment]
Did you make sure to enable the hud elements in the hud tab? If they are enabled by default then nvm

**Comment by seasnail8169** [comment]
> Did you make sure to enable the hud elements in the hud tab? If they are enabled by default then nvm

thats not the issue

**Comment by Sharedlines** [comment]
"hud module enabled:" I just clicked right shift, Then I clicked on the hud button, and i just got that blank menu. Was there something else i was meant to enable?

**Comment by Wide-Cat** [comment]
> > Did you make sure to enable the hud elements in the hud tab? If they are enabled by default then nvm
> 
> thats not the issue

Alr my bad

**Comment by Sharedlines** [comment]
> "hud module enabled:" I just clicked right shift, Then I clicked on the hud button, and i just got that blank menu. Was there something else i was meant to enable?

In the search menu, I searched for something to enable the hud, and nothing came up

**Comment by seasnail8169** [comment]
There is a module called HUD, try enabling that. (its in the render category)

**Comment by Sharedlines** [comment]
alr ill try that

**Comment by Sharedlines** [comment]
Ok, That worked. Sorry for making a ticket for this, and ty for helping
