### ISSUE TITLE
[Bug] 1.16.4 crashing with optifine

### ISSUE THREAD

**Issue by astella6969** [MeteorDevelopment/meteor-client#524]
1.16.4 crashes when i use meteor and optifine

**Comment by RedCarlos26** [comment]
Meteor is not compatible with optifine, please use sodium if you want performance improvements.

**Comment by cybrpop** [comment]
> please use sodium if you want performance improvements.


and maybe [optifabric](https://www.curseforge.com/minecraft/mc-mods/optifabric)

**Comment by astella6969** [comment]
im already using optifabric but thats the thing that causes me to crash, sodium barely does anything its just vanilla Minecraft with a different video settings ui

**Comment by cybrpop** [comment]
Have you tried using phosphor and lithium with sodium? It improved my fps a lot. 
I use [LambDynamicLights](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights) as a replacement for optifine's dynamic lightning, its cool and maybe looks better than optifine's
I will recommend you using sodium, lithium, phosphor and lambdynamiclights.
