### ISSUE TITLE
Meteor support on crystal aura has stopped working for all entities

### ISSUE THREAD

**Issue by PersonOnline** [MeteorDevelopment/meteor-client#525]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by PersonOnline** [comment]
Meteor Crystal Aura Support isn't working. I use no other mc mods except for meteor.

**Comment by RedCarlos26** [comment]
I can confirm

**Comment by RedCarlos26** [comment]
Why is it closed tough?

**Comment by Cranky481** [comment]
Same i cant use crystal aura , i reset all my settings still doesnt work

**Comment by RedCarlos26** [comment]
Was fixed for me though. Maybe air place is patched on the server your playing on?
