### ISSUE TITLE
Hud editor being retarded

### ISSUE THREAD

**Issue by RoastedCheese** [MeteorDevelopment/meteor-client#526]
Hud editor being retarded

As of 0.4.2 and dev build #748 when using the hud editor and trying to move stuff near the corners of the screen it results hard to do so and the modules get stuck in some spots.

**Comment by seasnail8169** [comment]
Are you talking about elements snapping together ?

**Comment by RoastedCheese** [comment]
@seasnail8169 yea didn't notice that was the cause of it.
