### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Panky55** [MeteorDevelopment/meteor-client#527]
**Describe the feature**
Make Meteor client compatible with inertia client. The commands that start with a period are the only incompatible things.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by supakeks** [comment]
It is...

**Comment by Panky55** [comment]
the commands that start with a period in chat are incompatible.

**Comment by StormyBytes** [comment]
change your meteor commands prefix?

**Comment by Panky55** [comment]
how do you change the prefix?

**Comment by Panky55** [comment]
i dont know how to change the prefix.

**Comment by StormyBytes** [comment]
**Configs Tab**
open the gui (right shift),
on the top there are tabs, one of them is the configs tab. 
change the prefix there.

**Comment by Panky55** [comment]
config tab? you mean the tab on the inertia client?

**Comment by StormyBytes** [comment]
i said meteor commands prefix, ofc its on meteor

**Comment by StormyBytes** [comment]
did it work?

**Comment by Panky55** [comment]
yes it did work
