### ISSUE TITLE
Copy Items (The /give command) With ctrl/strg + c and paste it in an empty slot with strg/ctrl +v

### ISSUE THREAD

**Issue by Z3r0ut** [MeteorDevelopment/meteor-client#529]
**Describe the feature**
Strg/crtl + c Copies the /give command of that item into the clipboard, and ctrl/strg + v paste that /give command in an empty slot. That way the chat limit would be eleminated, as we can use online /give command generators without having to worry about the max chat length

**Comment by MineGame159** [comment]
Better Chat has infinite chat box length setting.
