### ISSUE TITLE
[Bug] Better Chat infinte chat length not working

### ISSUE THREAD

**Issue by Z3r0ut** [MeteorDevelopment/meteor-client#531]
**Describe the bug**
Better Chat infinte chat length is not working

**Additional context**
Minecraft 1.16.5 Meteor 0.4.2 Fabric.
Other mods:
Autoconfig
Cloth config
Fabric API
ReAuth
Roughly Enough Items
Spark
ToroHealth
XaerosMinimap/Worldmap

https://user-images.githubusercontent.com/35275513/115213307-afb75900-a101-11eb-8da0-13033fda58fa.mp4

**Comment by BobIsMyManager** [comment]
Correct me if I’m wrong, but I’m pretty sure longer chat makes it so there are more lines you can scroll through in chat

**Comment by BobIsMyManager** [comment]
Not for letting you say longer messages

**Comment by MineGame159** [comment]
Get a dev build, there is a different setting called "infinite chat box length".
