### ISSUE TITLE
[Suggestion] Addition to scaffold

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#533]
**Describe the feature**
Tower speed: define tower speed
speed: (speed options to increase scaffold speed)
- a bhop that makes you bhop / lowhop while scaffolding without making you scaffold upwards.
- onground, onground speed on scaffold
- packet speed: packet speed
extend: places blocks further in the direction you're looking. useful when moving very fast.

**Comment by Declipsonator** [comment]
Can't you just turn on speed for the first 3
