### ISSUE TITLE
[Suggestion] Some options to make the client more customizable and smooth

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#535]
PanoramaSpoofer: change the panorama to another panorama or just a static picture
Smooth animations: add additional animations to sepcific clickgui actions
Rounded edges (toggelable in hud settings): make edges of the clickgui rounded.
Option to change all minecraft buttons to meteor style (things like sound sliders and exit game button)

**Comment by MineGame159** [comment]
Can you split it to multiple issues

**Comment by Cypphi** [comment]
> Can you split it to multiple issues

alr, which ones?

**Comment by MineGame159** [comment]
Everything? One feature / bug per issue.

**Comment by Cypphi** [comment]
okay, 1 sec

**Comment by Cypphi** [comment]
done
