### ISSUE TITLE
[SUGGESTION] Customizable minecraft window title

### ISSUE THREAD

**Issue by flaxeneel2** [MeteorDevelopment/meteor-client#536]
**Describe the feature**
Basically, the ability to customize the minecraft window title. For ex, from "Meteor client 0.4.2" to "totally a legit client" (just an example, this could be customizable to any possible string. this will help people who want to send screenshots to be able to do so without having to make the game fullscreen)
 
**Screenshots**
This example is from a client I was working on, 
OLD:
![image](https://user-images.githubusercontent.com/60919292/115353649-d3de6d00-a1c9-11eb-9289-46271eace80d.png)
NEW:
![image](https://user-images.githubusercontent.com/60919292/115353936-24ee6100-a1ca-11eb-9ca5-c311b7e1ee21.png)

**Additional info**
None

**Comment by seasnail8169** [comment]
If you don't want to have the window title just disable it. There is literally no reason for us to make it customisable.

**Comment by seasnail8169** [comment]
Also, might I add that meteor is not a mod you should be using on servers that do not allow utility mods or similar.

**Comment by MineGame159** [comment]
I dont see a reason why we should deny this

**Comment by MineGame159** [comment]
Its a valid suggestions

**Comment by seasnail8169** [comment]
Because its literally just a way for people to hide meteor in screenshares or similar things which we do not and can not condone. I don't see any reason why we should have this.

**Comment by MineGame159** [comment]
`Because its literally just a way for people to hide meteor in screenshares or similar things` the same effect has just disabling the custom title

**Comment by seasnail8169** [comment]
Exactly, ah yes lets add two things that literally do the exact same thing!

**Comment by MineGame159** [comment]
:skull:

**Comment by seasnail8169** [comment]
🐒🙉🐵🙈🙉🙊

**Comment by flaxeneel2** [comment]
So uh, is the suggestion accepted or denied? sorry but im a bit confused.

I do agree it can be used to hide the hacks, but isnt `vanillaSpoof` also used for the same thing? So I thought that this would be a valid suggestion.

**Comment by MineGame159** [comment]
Well its not closed

**Comment by flaxeneel2** [comment]
oh okay. Will be looking forward to an update :)

**Comment by seasnail8169** [comment]
🐒🐒🐒🐒🐒🐒🐒🐒

**Comment by seasnail8169** [comment]
so 🙈 fucking 🙉 monkey 🐒

**Comment by ikeafridge4** [comment]
seasnail so monke. i dont see why this shouldnt be added. the argument that this can be used to hide the fact that your cheating is so stupid, like flaxeneel2 said. besides, many people have been requesting this for a while.

**Comment by Declipsonator** [comment]
https://www.curseforge.com/minecraft/mc-mods/custom-window-title If you want to change it, you can probably just use this for now.

**Comment by MineGame159** [comment]
Added in eb5ff60bbab30ab7d1268e6540e6361c8d31dea7
