### ISSUE TITLE
[Suggestion] Ore simulation

### ISSUE THREAD

**Issue by mathmakgakpak** [MeteorDevelopment/meteor-client#537]
**Describe the feature**
Ore simulation using seed.

**Screenshots**
![image](https://user-images.githubusercontent.com/44949126/115355162-b05ff600-a1ba-11eb-9c9a-504430252e64.png)
![image](https://user-images.githubusercontent.com/44949126/115355242-c4a3f300-a1ba-11eb-82aa-0278bc10ec35.png)
![image](https://user-images.githubusercontent.com/44949126/115355272-cbcb0100-a1ba-11eb-948e-e4eb51d763cf.png)

**Additional info**
There is a mod by 19MisterX98 called [diamondgen](https://github.com/19MisterX98/DiamondSim) which renders where diamonds and ancient debris should generate in world using world seed

I would love to see it in meteor with all ores.
There is  [Atomic](https://github.com/cornos/Atomic) which includes both AntiAntiX-Ray and OreSimulator modules.
19misterX98 (he did a fork of SeedCracker called SeedCrackerX and adds features to it) made the commit which adds OreSim to Atomic

ConstantinDev and tokfrans03 also did a mod which bypasses orebfuscator ~~https://github.com/AriliusClient/AntiAntiXray~~ new link https://github.com/tokfrans03/AntiAntiXray

**Comment by flaxeneel2** [comment]
👍 
+1, that would be a pretty cool addition. The only issue is that players usually dont have access to world seed, which i guess can be solved by the addition of https://github.com/KaptainWutax/SeedCracker . Also it would be super cool if we can use baritone  with it too

**Comment by mathmakgakpak** [comment]
19misterX98 created a fork of SeedCracker called [SeedCrackerX](https://github.com/19MisterX98/SeedcrackerX/) which allows to crack seed through more versions and using Warped Fungu

**Comment by NobleOMD** [comment]
Why is this beneficial ontop of baritone, surely if u want ores you can just use that?

**Comment by flaxeneel2** [comment]
> Why is this beneficial ontop of baritone, surely if u want ores you can just use that?

To bypass anti xrays? baritone doesnt work when there is an anti xray present. This coupled with baritone (so that baritone can work even with the anti xray there) would be amazing

**Comment by NobleOMD** [comment]
> To bypass anti xrays
Meteor is a utility mod not for using on Hypixel UHC... If there is an anti-xray in place then most likely the rest of meteor client will not be welcome on that server either. Other things, such as less bait kill aura, have also been turned down for this reason.

**Comment by Epik123** [comment]
> > To bypass anti xrays
> 
> Meteor is a utility mod not for using on Hypixel UHC... If there is an anti-xray in place then most likely the rest of meteor client will not be welcome on that server either. Other things, such as less bait kill aura, have also been turned down for this reason.

Some anarchy servers have anti xray tbh

**Comment by StormyBytes** [comment]
> Some anarchy servers have anti xray tbh

Then its not true anarchy

**Comment by Epik123** [comment]
> > Some anarchy servers have anti xray tbh
> 
> Then its not true anarchy

Nothing is true anarchy anymore

**Comment by flaxeneel2** [comment]
well some anarchies do have anticheats etc. The meaning of anarchy is "no rules", never did it ever say that anti xrays cannot be put, so technically xrays are allowed but xraying is effectively patched


yes yes i know that is VERY dumb but idk i don't make recent anarchy server so yeah

**Comment by mathmakgakpak** [comment]
There is a client including both antiantixray and oresimulator features https://github.com/cornos/Atomic

**Comment by mathmakgakpak** [comment]
https://github.com/StormyBytes/Meteor-OreSim not updated

**Comment by unixquuw** [comment]
> > > Some anarchy servers have anti xray tbh
> > 
> > 
> > Then its not true anarchy
> 
> Nothing is true anarchy anymore

We live in society.
