### ISSUE TITLE
[SUGGESTION] List of macros that auto reconnect can toggle when you reconnect and highways building feature

### ISSUE THREAD

**Issue by adrianfuchs** [MeteorDevelopment/meteor-client#538]
When AFKing with meteor's baritone, like digging 7x3 highways for example, sometimes for many reasons i can get disconnected. I just use auto reconnect. Ok. The problem is: **auto reconnect** doesn't have an option to toggle some macros.

Let's say I have three macros:
1 - "#sel p1 -3 120 0"
2 - "#sel p2 3 122 -375000"
3 - "#sel fill air"

When I auto reconnect, it would be interesting to have a **list of macros that it can toggle**, so I don't just AFK like a rock in the end of the highway I was digging.

![image](https://user-images.githubusercontent.com/34813889/115395195-fcf70180-a1b9-11eb-9d10-3bff3ca1754e.png)

===========================================================================
In addition, another function that I found very interesting, would be a module to build (dig and build) highways.

using macros like 
#sel p1/p2
#sel fill air
and #sel fill obsidian
together with echest farm it is possible to automate the process 100%

an example you (reader) can try in your game to see how simple the macros are:

first iteration:

 DIG

	#sel p1 -3 120 -3750
	#sel p2 3 122 -3750

	#sel p1 -2 119 -3750
	#sel p2 2 119 -3750

	#sel fill air
	#sel clear

 BUILD

	#sel p1 -3 120 -3750
	#sel p2 -3 120 -3750

	#sel p1 3 120 -3750
	#sel p2 3 120 -3750

	#sel p1 -2 119 -3750
	#sel p2 2 119 -3750

	// if inventory has less than 16 obsidian:
	//	 toggle meteor's echest farm 1 time (for 1 echest)

	#sel fill obsidian
	#sel clear

second iteration: repeat first iteration and add 1 to the z coordinate, if it was -3750 now it needs to be -3751
third iteration: repeat second iteration and add 1 to the z coordinate, if it was -3751 now it needs to be -3752
...

**Comment by seasnail8169** [comment]
I think this would be better integrated into the profiles system

**Comment by adrianfuchs** [comment]
sorry, what profiles system? the one that you can save what modules/macros/etc each profile you save enables and disables?
if so, i still can't or at least don't know how to make auto reconnect toggle some macros for me in a predetermined order

**Comment by seasnail8169** [comment]
Who said it could? I just said it should be a part of profiles not auto reconnect.

**Comment by adrianfuchs** [comment]
ahh. ok  :)
