### ISSUE TITLE
[Suggestion] PanoramaSpoofer

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#542]
Changes the panorama to whatever you tell it to change it to. Similar to how Inertia does it but it would be more fun if it would actually support panoramas and not static images only.

**Comment by seasnail8169** [comment]
you can do this with a resource pack

**Comment by Cypphi** [comment]
> you can do this with a resource pack

static backgrounds as well?

**Comment by seasnail8169** [comment]
Im fairly sure if you just put in 1 image it will just display it. Not completely sure tho

**Comment by Cypphi** [comment]
> Im fairly sure if you just put in 1 image it will just display it. Not completely sure tho

Hmm maybe not this then

**Comment by Declipsonator** [comment]
https://www.youtube.com/watch?v=hN-b8_N2wMs
The Panorama itself is 5 images btw

**Comment by seasnail8169** [comment]
Resource packs
