### ISSUE TITLE
[Suggestion] More smooth animations

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#543]
add / change some animations in the client to look smoother. idk

**Comment by MineGame159** [comment]
Thats extremely vague, can you say where should the animations be add or changed?

**Comment by Cypphi** [comment]
> Thats extremely vague, can you say where should the animations be add or changed?

Ye sorry. I was talking about the various clickgui tabs. They sort of have an animation but it's really fast. Maybe a way to customize the speed? Maybe also something like a fade-in effect when opening the clickgui (toggleable)

(1.7 animations are different from 1.8 animations and also better imo)
- 1.7 / 1.8 block animations
- 1.7 / 1.8 eating animations 
- 1.7 / 1.8 bow animation

thats all ig

**Comment by AstroOrbis** [comment]
I think in LB, when you open your ClickGUI, all previously opened tabs will scroll out again. Maybe something like this?

**Comment by Cypphi** [comment]
> I think in LB, when you open your ClickGUI, all previously opened tabs will scroll out again. Maybe something like this?

Yeah that could work. LB next gen looks very sick
