### ISSUE TITLE
[Suggestion] Phase (yes this works on 1.16 and I have proof now)

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#546]
Add phase, there have been phase suggestions before but they were closed because apparently it's "impossible"?

Proof that it does work: (I used minehut bc I couldnt think of any other 1.16 server lol) (I can provide more proof if needed or you just use Jello for Sigma (troll) yourself)
https://www.youtube.com/watch?v=4NB6eksNk5M

**Comment by Declipsonator** [comment]
who said it didn't work

**Comment by Declipsonator** [comment]
also, minehut is on 1.8
