### ISSUE TITLE
[Bug] Nametag Bug

### ISSUE THREAD

**Issue by ForBai** [MeteorDevelopment/meteor-client#547]
**Describe the bug**
Namtags show in other position (it is with the damage with crystals the same)

**To Reproduce**
1. Go to 'https://meteorclient.com/download?devBuild=748'
2. Put it in your mods folder only this mod
3. Start Minecraft
4. Go on 'pvp.meteorclient.com'
5. Turn on NameTags
6. see they are in the wrong Position

**Expected behavior**
It should display them over the from others

**Screenshots**
![2021-04-20_21 10 30](https://user-images.githubusercontent.com/79467608/115452319-91934b00-a21e-11eb-88e0-cd7882472b6c.png)

**Additional context**
I use:
Linux "-" 4.4.0-209-generic #241-Ubuntu SMP Tue Apr 13 01:06:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
)
Minecraft 1.16.4/5
Graphic Card AMD JUNIPER
![Bildschirmfoto vom 2021-04-20 21-29-09](https://user-images.githubusercontent.com/79467608/115453062-7d038280-a21f-11eb-9a7f-fca52112ecc4.png)
DiscordTag: Anemoi#7990

**Comment by MineGame159** [comment]
Already reported in #263
