### ISSUE TITLE
[Bug] Waypoint Crash

### ISSUE THREAD

**Issue by GamR90** [MeteorDevelopment/meteor-client#548]
**Describe the bug**
Every time you create a waypoint you crash and can't join back.

**To Reproduce**
1. Log onto Meteor Client Version 748 on Fabric
2. Join server
3. Go onto click GUI and go to Waypoints
4. Left click it for more options
5. Click "Create"
6. It should crash your game, and you wont be able to rejoin the server (I haven't tested other servers)

**Expected behavior**
It is suppose to create a waypoint.

**Additional context**
I am using
![Untitled](https://user-images.githubusercontent.com/81706908/115455247-5590c380-a1e7-11eb-8e55-086c2e0444c8.png)

**Comment by MineGame159** [comment]
Can you post the crash report

**Comment by GamR90** [comment]
[crash-2021-04-20_13.46.41-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6351030/crash-2021-04-20_13.46.41-client.txt)

**Comment by MineGame159** [comment]
Should be fixed in d78ef7e50bed72c813d2a548477eb56940d722c4.
