### ISSUE TITLE
[Bug]Notebot attempts to play noteblocks that cannot be played

### ISSUE THREAD

**Issue by feliscatusmeows** [MeteorDevelopment/meteor-client#550]
**Describe the bug**
The notebot is attempting to play noteblocks that have another block on top of it. This does not make a sound. 

**To Reproduce**
1. Build a notebot chamber
2. Put torches or any other block on top of the notebot chamber
Even worse, the automatic noteblock placer doesn't check for any blocks above the noteblock it is placing, nor does it care about what block is under the noteblock.
**Expected behavior**
I expected notebot to ignore unplayable noteblocks. I also expected the notebot to not automatically place blocks in places where the noteblock will be silenced or where it will play the wrong instrument 

**Screenshots**
![image](https://user-images.githubusercontent.com/29553771/115478647-719e6000-a1fb-11eb-8d71-5c6647d8897b.png)
notebot auto-placing the noteblock in a place where it will be silenced. 
![image](https://user-images.githubusercontent.com/29553771/115478725-985c9680-a1fb-11eb-81db-5307d820bfe8.png)
No matter how hard you try, you aren't gonna make the noteblocks any louder, notebot. 
![image](https://user-images.githubusercontent.com/29553771/115478567-4e73b080-a1fb-11eb-932b-f287a54d2e44.png)
I ran into this issue when trying to play with this chamber, since note blocks are considered wood, and wood is a instrument according to minecraft.

**Comment by C10udburst** [comment]
Yeah, oops. I think i fixed it in #554
