### ISSUE TITLE
[Suggestion] F3 Spoofer

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#551]
**Describe the feature**
Would be a text file city the f3 menu components, that can be modified to whatever we want. There cloud be: spoof: true or false. And then if it's true, you can write something next to it and it replaces it (like in inertia client).

**Comment by seasnail8169** [comment]
Its literally so useless

**Comment by RedCarlos26** [comment]
It is really useful for people streaming. Trust me

**Comment by seasnail8169** [comment]
What about... not pressing f3

**Comment by TheRedHippo** [comment]
Sorry for bringing this back up, but this is definitely something useful. A f3spoofer menu would be incredibly useful for streamers- one accidental press of f3- something which is very much a habit- will leak your coordinates to everyone. It'd also be useful for faking coordinate screenshots. This is clearly a feature that people want, it's mentioned in #1029 as well.

**Comment by RedCarlos26** [comment]
I totally agree with you

**Comment by seasnail8169** [comment]
i totally dont
