### ISSUE TITLE
[Suggestion] Confirm option for saving profiles

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#552]
Add an option that could be toggled, that sends a confirmation box or something to ask if you really want to save the profile. This could stops unwanted savings to happen (when u press on it by accident for example)

**Comment by seasnail8169** [comment]
How hard is it to just not click on the save button?

**Comment by supakeks** [comment]
> How hard is it to just not click on the save button?

The save and load button are so close to each other you accidentally click save, it's happened to me so many times I hate it

**Comment by RedCarlos26** [comment]
> > How hard is it to just not click on the save button?
> 
> 
> 
> The save and load button are so close to each other you accidentally click save, it's happened to me so many times I hate it

Exactly

**Comment by Declipsonator** [comment]
I mean, shouldn't the save button and load button be moved slightly apart from each other instead of adding another check

**Comment by RedCarlos26** [comment]
I agree

**Comment by seasnail8169** [comment]
what about learning to use your mouse :trollface:

**Comment by Declipsonator** [comment]
:trollface:

**Comment by seasnail8169** [comment]
nono
