### ISSUE TITLE
[Suggestion] raidmasternotify

### ISSUE THREAD

**Issue by c-harlotte** [MeteorDevelopment/meteor-client#557]
**Describe the feature**
notifies you in chat if a raid captain spawns nearby

**Screenshots**
ur mom

**Additional info**
would be cool

**Comment by Declipsonator** [comment]
_Tracers or Entity Logger_

**Comment by Wide-Cat** [comment]
Someone close this lmao, as declipse said, tracers and entity logger already do this

**Comment by c-harlotte** [comment]
ok
