### ISSUE TITLE
[Bug] Scaffold sometimes places against other blocks when towering

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#558]
**Describe the bug**
Tower places blocks against walls even when towering.

**To Reproduce**
Go on the latest dev build and tower next to a wall. (I towered with shulkers and they got places sideways, not how tower works)

**Expected behavior**
Blocks should be placed right below someone, not against a block.

**Comment by Cypphi** [comment]
> Thats just how it works, I dont see a reason why the priority of sides would need to be changed.

true, but it can be annoying when using blocks that can be placed in different rotations. And doesn't tower mean going up and placing blocks under you? (yes placing against a wall also is under you but it doesn't make much sense to me)

**Comment by Declipsonator** [comment]
I don't see why this is bug, it works as intended
