### ISSUE TITLE
[Suggestion] Log out button for alt manager

### ISSUE THREAD

**Issue by Lerbiq** [MeteorDevelopment/meteor-client#565]
Simple log out button in alt manager that would basically log you in back into the account the game was launched with. Could be probably be done with holding onto the session token and using it later when you "log out".

**Comment by ikeafridge4** [comment]
this would be so useful as theres no clear way to log out of alts at the moment. 👍

**Comment by MineGame159** [comment]
Not gonna save your token, just add your main to the alt manager.
