### ISSUE TITLE
[SUGGESTION] Low Profile

### ISSUE THREAD

**Issue by hardro** [MeteorDevelopment/meteor-client#569]
Add the option to disable the "M" in your nametag. Some people don't want others to know they're using Meteor Utility and this would be a great way to go "low profile" while still getting all of the advantages.

I'm already leaning towards donating but having this feature would make it well worth it.

**Comment by MineGame159** [comment]
Go to config tab and disable "send data to api". Does exactly what you want.

**Comment by hardro** [comment]
Thank you!
