### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Sadfafass** [MeteorDevelopment/meteor-client#570]
SOLVED

**Comment by Declipsonator** [comment]
Can you send the full crash report

**Comment by Sadfafass** [comment]
The last part of the Report. 
![image](https://user-images.githubusercontent.com/83101109/115942017-9f8adb00-a46d-11eb-8431-ce96f3873e76.png)

**Comment by Declipsonator** [comment]
_View crash report_

**Comment by Sadfafass** [comment]
![image](https://user-images.githubusercontent.com/83101109/115942467-0c06d980-a470-11eb-864b-41b2d15b9094.png)
![image](https://user-images.githubusercontent.com/83101109/115942480-1de87c80-a470-11eb-8123-fb3c8f18a486.png)
![image](https://user-images.githubusercontent.com/83101109/115942485-2640b780-a470-11eb-91e9-676455949fdc.png)
![image](https://user-images.githubusercontent.com/83101109/115942492-2e005c00-a470-11eb-83ac-ce4bbdc259f5.png)

**Comment by StormyBytes** [comment]
Are you using other mods?

**Comment by Sadfafass** [comment]
Origins and Origins classes

**Comment by Sadfafass** [comment]
Issue solved, I figured out I need to delete Origins and Origins classes when I want to play with the new Meteor.

**Comment by StormyBytes** [comment]
Then close it

**Comment by Declipsonator** [comment]
@Sadfafass ^
