### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Arbisy** [MeteorDevelopment/meteor-client#576]
**Describe the feature**
A clear and concise description of what feature/change is.
Rear view, shows a screen of what's behind. Or you can choose a option where it just shows your ass :trollface:
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
#472

**Comment by Arbisy** [comment]
> #472 

What does that mean

**Comment by MineGame159** [comment]
But was made sooner.

**Comment by Arbisy** [comment]
> If you click on it you will see its the same suggestion.

Oh well I'm dumb

**Comment by Arbisy** [comment]
But still add the butt feature :trollface:
