### ISSUE TITLE
[Bug] Rich presence not going away after closing the client

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#577]
**Describe the bug**
the meteor rich presence doesn't go away after closing meteor. It sometimes also overrides other applications like here:
https://big-black.nigga-balls.com/lnB4D7Ht

**To Reproduce**
launch meteor, turn on discord rich presence and close it

**Expected behavior**
the rich presence should go away

**Screenshots**
https://big-black.nigga-balls.com/lnB4D7Ht

**Additional context**
:trollface:

**Comment by seasnail8169** [comment]
Firstly, not able to access any of that media.
Secondly im fairly sure this is a discord issue because if you reload discord it goes away.

**Comment by Cypphi** [comment]
> Firstly, not able to access any of that media.
> Secondly im fairly sure this is a discord issue because if you reload discord it goes away.

yea that's true, it's still kinda weird since it doesn't just happen on betterdiscord, it's normal discord as well

**Comment by RedCarlos26** [comment]
I cannot reproduce this bug. this is probably an issue with discord.

**Comment by Declipsonator** [comment]
> > Firstly, not able to access any of that media.
> > Secondly im fairly sure this is a discord issue because if you reload discord it goes away.
> 
> yea that's true, it's still kinda weird since it doesn't just happen on betterdiscord, it's normal discord as well

might be some betterdiscord enhancement

**Comment by Declipsonator** [comment]
Discord is weird when it comes to game activity. I've been using applications that I couldn't get to show up and sometimes they can't get rid of them. 🤷‍♂️

**Comment by ikeafridge4** [comment]
cant reproduce either and im on bd. rpc goes away in like 5 seconds after i close the game

**Comment by AstroOrbis** [comment]
I think it just sticks around for like 10 seconds. Happens to me on all discord versions (stable, ptb, canary), and on BD/PC (powercord)

**Comment by seasnail8169** [comment]
doesnt seem like an issue
