### ISSUE TITLE
[Suggestion] Window title placeholders

### ISSUE THREAD

**Issue by hashalite** [MeteorDevelopment/meteor-client#579]
**Describe the feature**
Placeholder support in the window title changer would be pretty cool

**Additional info**
Some possible placeholders:
%mc_version%
%meteor_version%
%mc_username%
%server_ip%

**Comment by Lerbiq** [comment]
Shouldn't be hard. I'll see what I can do

**Comment by Lerbiq** [comment]
Nvm Snail was faster, 4028da68beddae28c90a7e0945eefe8430b4f8bc implements it. The current placeholders are `{version}`, `{mc_version}`, `{username}`, `{server}`.

**Comment by hashalite** [comment]
Oh cool.  I’ll go ahead and close this then
