### ISSUE TITLE
[SUGGESTION] Fullbright: Entites

### ISSUE THREAD

**Issue by AutistEren** [MeteorDevelopment/meteor-client#580]
**Describe the feature**
Fullbright, but only for entities.
Blocks will remain same but entities will render at full light level.

**Screenshots**
-
**Additional info**
-

**Comment by AstroOrbis** [comment]
We can’t do this because FullBright turns up your Gamma. You don’t need a client to use fullbright, open your `minecraft/options.txt`, look for your `gamma` setting, and set it to 10. Use Chams (texture) for full entity brightness.
