### ISSUE TITLE
[SUGGESTION] Piston Crystal

### ISSUE THREAD

**Issue by ARm8-2** [MeteorDevelopment/meteor-client#581]
An option/a module that, when activated, places a piston with a crystal in front. The piston pushes(with redstone block or redstone torch) the crystal into the player that is camping in a hole and destroys it so the player takes a lot of damage, the lower hitbox is now exposed because the crystal is right on top of the player.

Maybe you can add an option for placing obsidian above the player so he can't escape while you are doing the action,
maybe also a module called anti-pistoncrystal that automatically places a block of obsidian in front of the piston.

**Comment by AstroOrbis** [comment]
This has to be one of the most inconvenient ideas ever. I love it!

All jokes aside, this can be some new PVP meta... time to learn raytracing I guess :p
