### ISSUE TITLE
When Holding Weapon trigger setting

### ISSUE THREAD

**Issue by joeslizz** [MeteorDevelopment/meteor-client#590]
This has been a feature of some clients in the past and as of right now there are no good 1.16 clients with it. Basically, a setting where trigger only works when you have a weapon in your hand. This would be incredibly useful since a lot of the time you don't want trigger going when your hand is empty, or when you're holding a bow food etc. 

![image](https://user-images.githubusercontent.com/83043658/116011850-11416100-a5f5-11eb-88fc-7b3e267573ab.png)

**Comment by Declipsonator** [comment]
implemented in https://github.com/MeteorDevelopment/meteor-client/pull/606
