### ISSUE TITLE
[Suggestion] An EXP count in the LookingAt HUD module (for furnaces, smokers and blast furnaces.)

### ISSUE THREAD

**Issue by flaxeneel2** [MeteorDevelopment/meteor-client#591]
**Describe the feature**
Basically for blocks used for smelting, it also shows the amount of experience it has stored in it
This is not a very important suggestion, so I understand if you deny it, but it's still a nice-to-have

**Screenshots**
![image](https://user-images.githubusercontent.com/60919292/116001218-70f33880-a604-11eb-979b-8c67d5ac2f9d.png)

**Additional info**
None

**Comment by Fr-gs** [comment]
Yes

**Comment by AstroOrbis** [comment]
What mod/client is in the screenshot?

**Comment by Declipsonator** [comment]
You sure this works on multiplayer? I believe it was a feature in tweakaroo but it only worked in singleplayer or on fabric servers

**Comment by Declipsonator** [comment]
I don't think block traits like this are given from the server to the client by default

**Comment by flaxeneel2** [comment]
> I don't think block traits like this are given from the server to the client by default

Its just a modded meteor client. I tried giving it a go myself first but im kinda not used to fabric so i was unable to do it myself. I just added a string to meteor which added a `(Contains: 20.5 XP)` at the end of the string if you look at a furnace

**Comment by flaxeneel2** [comment]
> What mod/client is in the screenshot?

Its just a modded meteor client. I tried giving it a go myself first but im kinda not used to fabric so i was unable to do it myself. I just added a string to meteor which added a `(Contains: 20.5 XP)` at the end of the string if you look at a furnace

**Comment by flaxeneel2** [comment]
> I don't think block traits like this are given from the server to the client by default

Oh I see. rip

**Comment by Declipsonator** [comment]
looking into it rn

**Comment by Declipsonator** [comment]
can't find anything on it 🤷‍♂️

**Comment by flaxeneel2** [comment]
> can't find anything on it 🤷‍♂️ 

Hm ill probably take a look into paper's code to see if it does

**Comment by flaxeneel2** [comment]
Okay i guess not paper, paper's github only contains what all patches they do, and not the actual code. I will probably have to find another way (probably decompiling spigot and looking st its src)

**Comment by Declipsonator** [comment]
I don't think it was patched by paper or spigot

**Comment by Declipsonator** [comment]
I just don't think servers pass that info on to the player

**Comment by seasnail8169** [comment]
no

**Comment by AstroOrbis** [comment]
Just ideas :p

**Comment by seasnail8169** [comment]
ok 🐒
