### ISSUE TITLE
[SUGGESTION] MessageTrigger

### ISSUE THREAD

**Issue by Fr-gs** [MeteorDevelopment/meteor-client#592]
**Describe the feature**
So this module would basically send a message when a specific messages gets typed for example
player1withoutmodule: @player2withthemoduleenabled hi
player2withthemoduleenabled: hi (this would get send automatically) 

**Screenshots**
No
**Additional info**
No

**Comment by AstroOrbis** [comment]
Can you give more clarification? Is this like a discord bot?

**Comment by Fr-gs** [comment]
> Can you give more clarification? Is this like a discord bot?

I think it's pretty obvious I'm talking about a module for the client while talking in the mods github

**Comment by AstroOrbis** [comment]
I know. But is this like a bot? Like someone types something, and the module automatically returns a string?

**Comment by AstroOrbis** [comment]
Like Inertia's ChatBot?
