### ISSUE TITLE
[Bug] Peek Module (shulkers and echests) is gone in 0.4.3

### ISSUE THREAD

**Issue by TheGreatRambler** [MeteorDevelopment/meteor-client#593]
The modules ShulkerPeek and EChestViewer (I believe those were the names) are gone in version 0.4.3. Those were pretty essential modules for me so I wonder if this was intentional. I checked the `Modules.java` and they seem to have been removed there too in master

**Comment by GildedS** [comment]
Those two have been merged to the BetterTooltips module

**Comment by TheGreatRambler** [comment]
Leaving this for future readers
