### ISSUE TITLE
Settings folder

### ISSUE THREAD

**Issue by Seaparty** [MeteorDevelopment/meteor-client#596]
I think everyone knows the pain, of going to get a new dev build, it having a feuture you really love. you get it, install it, and go on a server to go crystal pvp, but look at that, all your settings and keybinds, gone.  i would like a update where a folder is added in the .minecraft or .minecraft/meteor-client where all settings are saved, and all dev builds can read it and save it. or where you can choose profiles, and they save between dev bulds

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
Thats what already happens.

**Comment by Seaparty** [comment]
> Thats what already happens.

how

**Comment by MineGame159** [comment]
Profiles were reset in one commit because they got rewritten but apart from that the settings are saved every time.

**Comment by Seaparty** [comment]
> Profiles were reset in one commit because they got rewritten but apart from that the settings are saved every time.

does it save accounts

**Comment by MineGame159** [comment]
Yes.
