### ISSUE TITLE
[Bug]shulker peek unavailable in latest 0.4.3[Bug]

### ISSUE THREAD

**Issue by jj15warrior** [MeteorDevelopment/meteor-client#597]
is it only my issue or was it removed?
mods runned with meteor:
  Ares-2.8-1.16.4
  clientcommands-2.4.9
  bookdupe
  fabric-api-0.30.0+1.16
  seedcracker-0.2.2-beta
it does not show up in hud menu or in .toggle
![Ares 2 8 - 1 16 4 - Multiplayer (3rd-party Server) 26 04 2021 17_00_43](https://user-images.githubusercontent.com/74490157/116105337-82dee500-a6b1-11eb-8725-576b466ff126.png)

**Comment by supakeks** [comment]
It's in better tooltips

**Comment by jj15warrior** [comment]
thx
but i like the old one more
