### ISSUE TITLE
[Bug] Issue building meteor-client

### ISSUE THREAD

**Issue by Oskar2601** [MeteorDevelopment/meteor-client#598]
when i download meteor-client, go to the directory and type gradlew build it starts building and 20 seconds in gives me an error:

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_281 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
1 actionable task: 1 executed

**Comment by MineGame159** [comment]
You need java JDK not JRE.

**Comment by seasnail8169** [comment]
@MineGame159 fix your shitty client this is clearly a bug
