### ISSUE TITLE
[Bug] Shulker Peek missing in 0.4.3

### ISSUE THREAD

**Issue by grape32** [MeteorDevelopment/meteor-client#599]
**Describe the bug**
In the new Meteor Version 0.4.3 the module Shulker Peek seems to be completely missing or disabled. When issuing the .modules command, shulker peek also doesnt show up. It was present in the previous version 0.4.2 

**To Reproduce**
1. Open Meteor Menu
2. Search for Shulker Peek
-or-
1. Open Chat
2. type .modules
3. See no shulker peek

**Additional context**
Using Meteor 0.4.3 with Modmenu, Sodium, Phosphor, Lithium and 19MisterX98 Diasim

**Comment by MineGame159** [comment]
Better Tooltips

**Comment by seasnail8169** [comment]
It has been merged with a few other modules into BetterTooltips, this isn't a bug.
