### ISSUE TITLE
Meteor client not launching

### ISSUE THREAD

**Issue by MobESP** [MeteorDevelopment/meteor-client#602]
**Describe the bug**
The game isn't launching, and other fabric mods put in the folder are: sodium-fabric-mc1.16.3, meteor-client-0.4.3, MinecraftCapes+, fabric-api for 1.16.

**To Reproduce**
1. Download all of the above 
2. Click on 'Launch' (1.16.5 bug)
3. Shows that game launched
4. Shows a crash report

**Expected behavior**
Its supposed to launch and play normally (it was working 1 hour ago)

**Screenshots**
-----------

**Additional context**
Minecraft 1.16.5, sodium-fabric-mc1.16.3, meteor-client-0.4.3, MinecraftCapes+, fabric-api for 1.16.

**Comment by Declipsonator** [comment]
can you try it without minecraftcapes+

**Comment by Drakesdrs** [comment]
wtf is minecraftcapes+

**Comment by MobESP** [comment]
The problem is solved, Just needed to update Minecraft launcher
