### ISSUE TITLE
[Bug] Canvas compatibility

### ISSUE THREAD

**Issue by Arbisy** [MeteorDevelopment/meteor-client#603]
**Describe the bug**
So meteor should be compatible with canvas, but meteor affects it and esp is weird and theres problems with rendering. and it constantly crashes.

**To Reproduce**
1. install canvas, lumi lights, and fabric with fabric api
2. install meteor
3. use them together and you get the problems

**Expected behavior**
the rendering should be normal, esp should be normal, and no crashing.

**Screenshots**
![2021-04-28_13 48 08](https://user-images.githubusercontent.com/76462987/116451990-33242900-a82b-11eb-9214-114be01ba805.png)

**Additional context**
the meteor version is dev build #784, game version 1.16.5, and other mods im using are xaeros world map and minimap, meteor book dupe, and multi connect.

**Comment by MineGame159** [comment]
Apart from shader esp they should now be compatible from d55f0d5563bd8c3c85a15bb953e9b586cb491a61.
