### ISSUE TITLE
[Xray Bypass from this video]

### ISSUE THREAD

**Issue by erxdev** [MeteorDevelopment/meteor-client#608]
https://youtu.be/5Icj5TNmBUI

Check description and comments

**Comment by ikeafridge4** [comment]
if the server youre on has anti xray, youre probably not supposed to be using meteor on it...

![Screenshot 2021-04-29 204036](https://user-images.githubusercontent.com/78064813/116645694-31418f00-a92b-11eb-85c2-c2d9c928dd3d.png)

**Comment by Drakesdrs** [comment]
There are some anarchy servers with anti-xray plugins

**Comment by erxdev** [comment]
Bruh, its working with anti xray. U didnt check the video.

**Comment by erxdev** [comment]
300 iq xray bypass. I think its possible to make xray for visible block. Because antixray working on clay

**Comment by seasnail8169** [comment]
This is not really a realistic idea.
