### ISSUE TITLE
[Suggestion] Add Phase

### ISSUE THREAD

**Issue by Drakesdrs** [MeteorDevelopment/meteor-client#615]
Its funny how meteor hasnt even added the simple module yet bruh

**Comment by seasnail8169** [comment]
"the simple module yet"
Try to write it then 🐒

**Comment by Drakesdrs** [comment]
https://gitlab.com/Arithmo/Sigma/-/blob/master/info/sigmaclient/module/impl/movement/Phase.java

 hhehehehehehe skid time

**Comment by seasnail8169** [comment]
🤡
please stop commenting on issues
