### ISSUE TITLE
[Bug] Baritone building & Gui move

### ISSUE THREAD

**Issue by BitorBit1357** [MeteorDevelopment/meteor-client#620]
**Describe the bug**
While baritone is building and i am in goi, it just stops after some time for no reason.

**To Reproduce**
1. See error: no, it just stops and its anoying with multiple accs
2. is that it?: yes

**Expected behavior**
To not stop but it stopped while moving in gui

**Screenshots**
Me waiting with open gui and stopped baritone.

**Additional context**
Fix it, i cant use 5 accs at the same time to build my base.

**Comment by seasnail8169** [comment]
This doesn't seem like a meteor issue to me. Sounds like baritone is getting stuck or you are running out of materials
