### ISSUE TITLE
[Bug] Reach doesn't work beyond 3 blocks

### ISSUE THREAD

**Issue by Maximillus** [MeteorDevelopment/meteor-client#625]
It works if you turn it down to 2 blocks (you can't hit a player you are 2.5 blocks away from) but it doesn't work past 3 blocks, maybe a mixin problem

**Comment by Declipsonator** [comment]
sounds like an anticheat 🤔

**Comment by Maximillus** [comment]
happens on vanilla

**Comment by Drakesdrs** [comment]
why would you use meteor utility mod on a singleplayer world.

**Comment by Maximillus** [comment]
> why would you use meteor utility mod on a singleplayer world.

i mean it happens on a server without any anticheat
