### ISSUE TITLE
[Suggestion] Autosneak

### ISSUE THREAD

**Issue by Drakesdrs** [MeteorDevelopment/meteor-client#626]
Automatically sneaks

**Comment by MineGame159** [comment]
Vanilla has that feature already.

**Comment by Drakesdrs** [comment]
> 
> 
> Vanilla has that feature already.
 bruh idk what you are talking about just add it

**Comment by Declipsonator** [comment]
> bruh idk what you are talking about just add it

In settings, there is an option for toggle sneak. When you press shift it will sneak and when you press it again it will stop sneaking.
