### ISSUE TITLE
[Bug] Offhand and AutoTotem interfering

### ISSUE THREAD

**Issue by blendifyClient** [MeteorDevelopment/meteor-client#628]
**Describe the bug**
Autototem with offhandextra doesnt work well (weird flickering between the two) 

**To Reproduce**
1. activate autototem+offhandextra with crystal
2. bring your health low
3. look the crystals and totems do weird actions

**Expected behavior**
They switch back and forth

**Additional context**
Running the most recent version of meteor

**Comment by blendifyClient** [comment]
forgot to rename the name lmao

**Comment by seasnail8169** [comment]
Are you using a dev build or 0.4.3

**Comment by blendifyClient** [comment]
dev builds

**Comment by seasnail8169** [comment]
Can you show me your settings?

**Comment by seasnail8169** [comment]
@blendifyClient please send a screenshot of your settings

**Comment by RedCarlos26** [comment]
I can confirm @seasnail8169

**Comment by seasnail8169** [comment]
Thats completely useless telling me that, i clearly asked for the settings used to reproduce multiple times. I cant fix it if I cant reproduce it.

**Comment by seasnail8169** [comment]
Cant fix it if i cant reproduce it, ping me if any of you ever send me your settings to actually help.

**Comment by blendifyClient** [comment]
sorry but its fixed now

**Comment by seasnail8169** [comment]
ok
