### ISSUE TITLE
Spoof blocks? [SUGGESTION]

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#630]
**Describe the feature**
allow people to spoof blocks and remove hitboxes from certian blocks (or maybe just a hack to remove tallgrass/grass)

**Additional info**

**Comment by seasnail8169** [comment]
No idea what you mean by "spoof blocks" can you elaborate?

**Comment by Texbio** [comment]
I usually do not check back on pull requests, but I completely forgot about this one! I will make another pull request instead because my explanation was horrible.
