### ISSUE TITLE
[Suggestion] Barier particle vision

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#631]
Allow barrier particles to be shown without holding the item

**Comment by C10udburst** [comment]
I tried to add it in #485, you should use search module instead.

**Comment by Texbio** [comment]
I think this should be a thing, inertia already has a this module and it works fine, but I think meteor should add this module. 
Esp for blocks is pretty laggy (meteor client 0.43).
This module should added to esp and be named [Toggle Barriers] or something.

**Comment by C10udburst** [comment]
I've added this to [my addon](https://github.com/C10udburst/meteor-rejects), because my PR didn't get merged.

**Comment by C10udburst** [comment]
Added in 6daa58353f1d04fc70e37c074bf72d9e5079fe72. Can be closed
