### ISSUE TITLE
Book Dupe (.dupe) [Suggestion]

### ISSUE THREAD

**Issue by MobESP** [MeteorDevelopment/meteor-client#632]
**Describe the feature**
When holding a book and quill in hand, and looking at a chest, you can type ".dupe" or ".d" to overload packet data and get things from your last autosave and the current. (Note: For those who don't know how .dupe works, you basically fill a book up with foreign and non-ASCII to try and overload chunk memory.)

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
I tried to put the book dupe mod and meteor together, but it isn't compatible. And since I don't have permission to change the code, I'm suggesting the dupe inside the client.

**Comment by supakeks** [comment]
No point in adding a dupe command which works on like 0 servers

**Comment by MineGame159** [comment]
Also we already have an addon for it.

**Comment by MobESP** [comment]
can I get the link to the add-on?

**Comment by MobESP** [comment]
And it works on Realms and single-player world, it can also work on servers that don't update plugins as much.
