### ISSUE TITLE
Add more to the macro tab

### ISSUE THREAD

**Issue by joeslizz** [MeteorDevelopment/meteor-client#635]
Currently the macro tab is incredibly restricted, purely being message based. I think the ability to add placement and usage macros would be incredibly useful, a feature which few if not any other clients has. 

How this would work:

You bind a specific slot # to a keybind. Let's say for example, bind the 5th slot in the hotbar to R. If we were to put a loaded crossbow in this slot, then press R, it will swap to the crossbow and fire it very quickly. This could be done for placing blocks, throwing potions, using items, etc. Basically, it would use the item you have in the keybinded slot. This could further be expanded by adding options such as how long the delay between swapping to the slot and using the item is, and if it should click or hold down the item in the keybinded slot (and if holding down, for how long before releasing). 

Thanks!

**Comment by ikeafridge4** [comment]
👍

**Comment by seasnail8169** [comment]
This just isnt a reasonable idea to implement. The gui or interface would be way too complex and messy and the idea is way too niche imo.
