### ISSUE TITLE
[SUGGESTION]Add Self Anvil Delay, Auto City Improvements

### ISSUE THREAD

**Issue by necrophili** [MeteorDevelopment/meteor-client#638]
Self Anvil Delay;
Add a delay for self anvil just like the ones in Crystal aura, Bed aura and Anchor Aura

Auto City Improvements;
Make auto city try and mine the block that is next to the crystal aura surround break, if there is none then it will mine the closets targeted block just like usual.

**Comment by Declipsonator** [comment]
self anvil places 1 anvil, there would be no place to put delay

**Comment by necrophili** [comment]
Is it not doable for the first anvil it places then?

**Comment by Declipsonator** [comment]
Why would you add delay to that, just toggle the module when you want the anvil placed
