### ISSUE TITLE
Place Delay Bypass

### ISSUE THREAD

**Issue by Lynxdeer** [MeteorDevelopment/meteor-client#640]
Place Delay Bypass
Removes/Changes the place delay that prevents you from godbridging with 1 click and removes the delay to how much you can place per tick, similar to Aristois' Fastclick.

Recorded using caterpillow's cps cap bypass mod.

https://user-images.githubusercontent.com/79340005/116879814-2454c200-abef-11eb-836a-07403467f367.mp4
https://user-images.githubusercontent.com/79340005/116879823-27e84900-abef-11eb-8b2c-45c7122d8a2a.mp4

Would be helpful to block off quickly using this.

**Comment by MineGame159** [comment]
Fast Use
