### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Samreds** [MeteorDevelopment/meteor-client#641]
**Idiot proof jar file**
Basically, to make the installation process idiot proof you could make it so if you click the jar it will open up an installer to make a meteor profile, or you could just drag the jar into /appdata/.minecraft/mods like normal, I believe Kami blue had a feature like that with the jars it had. something like this would be ideal for people who do not know much about the technicalities of using a computer and just 1 and done.

**Screenshots**
![image](https://user-images.githubusercontent.com/65549785/116901700-ddbb9380-abff-11eb-83f7-602c8d579f75.png)

**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
If you tried to double click meteor's jar then you would know it already says what the person needs to do.
