### ISSUE TITLE
[Bug] Search Highlighting every single block (air included)

### ISSUE THREAD

**Issue by tinmarr** [MeteorDevelopment/meteor-client#642]
**Describe the bug**
Title says it all. I turn on search and every single block get highlighted, even if there are no blocks in the menu. 

**To Reproduce**
1. Turn on search

**Expected behavior**
The blocks in the search list light up. The others don't.

**Screenshots**
![2021-05-03_09 33 15](https://user-images.githubusercontent.com/35586618/116904591-c2965700-abf2-11eb-98b6-f122637efb48.png)

**Additional context**
Using Meteor version 0.4.3-819

**Comment by MineGame159** [comment]
Click the reset button next to blocks setting. If it didn't fix it reopen this issue.

**Comment by Enchoseon** [comment]
Found how to consistently cause this bug in `0.4.5`.

If the game is closed by Windows shutdown or BSOD, at next launch the `Search` module is set to all blocks. (This also overrides previous configurations every time it happens.)
