### ISSUE TITLE
[Bug]Macro issues

### ISSUE THREAD

**Issue by necrophili** [MeteorDevelopment/meteor-client#644]
Deleted Macros still activates when the keybind is hit after it is deleted sometimes. I had a macro for vclip and after it is deleted my vclip would still activate after it's deleted.

**Comment by Declipsonator** [comment]
🤔

**Comment by necrophili** [comment]
No commit?

**Comment by RoastedCheese** [comment]
Just relog

**Comment by MineGame159** [comment]
Should be fixed in e098fb1d48cca745f5c3cd214c08f3a427f44bc8
