### ISSUE TITLE
[Suggestion] make inventory hud rescale to the size of the texture

### ISSUE THREAD

**Issue by GhostTypes** [MeteorDevelopment/meteor-client#647]
Inventory HUD cannot be dragged to the bottom of the screen, inline with other elements. This occurs with no resource packs and many custom resource packs.

https://cdn.discordapp.com/attachments/742396489581723728/838931717242617896/inv.PNG

**Comment by ikeafridge4** [comment]
i get this bug too

**Comment by seasnail8169** [comment]
Its not a bug, thats just how it works. This should be a suggestion not bug.
