### ISSUE TITLE
[Bug] Air jump "on hold" does not time jumps like minecraft does.

### ISSUE THREAD

**Issue by AprilF00lz** [MeteorDevelopment/meteor-client#648]
During testing, I found a bug where if you toggle "on hold" in the airjump module, it spams the space bar for you (I expected it to time my jump).

**Comment by MineGame159** [comment]
Jesus, title is supposed to be simple so we can easily look at it and see whats the issue. You can write more info inside the github issue itself, not the issue.

**Comment by seasnail8169** [comment]
This also isnt a bug im fairly sure its intended but whatever

**Comment by seasnail8169** [comment]
Fixed the title and desc

**Comment by The-Warlord** [comment]
I think there's an option to maintain your height, if that's what you're looking for.
