### ISSUE TITLE
[SUGGESTION] Meteor has plenty of useful modules to go around with, just like any good hacked client would. That's why I was so surprised when I found that Meteor lacks a compass or radar module. Adding either one would help greatly.

### ISSUE THREAD

**Issue by AprilF00lz** [MeteorDevelopment/meteor-client#649]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by MineGame159** [comment]
Same as previously, title is supposed to be simple and write more info in the issue. Also meteor has compass in HUD module.
