### ISSUE TITLE
[Bug] Alt manager broken

### ISSUE THREAD

**Issue by Samreds** [MeteorDevelopment/meteor-client#652]
**Describe the bug**
In the latest dev builds #821 and #822 The alt manager appears to be broken and is not useable by any means.

**To Reproduce**
Go to multiplayer screen then alts, It will not work at all by any means

**Expected behavior**
To work

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).
It deleted all my alts, my personal paid alts and my alt list

**Comment by MineGame159** [comment]
You mean cracked accounts? Because normal accounts work fine.
