### ISSUE TITLE
[Suggestion] Fast fall

### ISSUE THREAD

**Issue by icpvpbadly** [MeteorDevelopment/meteor-client#655]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by ikeafridge4** [comment]
reverse step :bruh:

**Comment by seasnail8169** [comment]
Not quite the same thing

**Comment by a-couple-objects** [comment]
you can set it to be

**Comment by seasnail8169** [comment]
This can be done in so many other ways a module is useless
