### ISSUE TITLE
[Suggestion] Liquid interact improvement

### ISSUE THREAD

**Issue by MatG4n** [MeteorDevelopment/meteor-client#656]
I wanted to gried a bit by flooding an area with water source blocks using only a water bucket, so I don't have to place and break ice blocks.
The problem is that I can't place the water source blocks **on top/next to** already existing water source blocks. I can only place them if I ineract with a regular block. 
Also AirPlace doesnt work with water/lava buckets.

**Just a couple more ideas**
- A render module that draws an outline to water source blocks or flowing water blocks.
- A module that automatically fills an empty water bucket with water from a nearby water source block that can regenerate from 2 water source blocks next to it.
- Module that places a water source blocks in nearby airblocks and flowing water blocks.

**Comment by seasnail8169** [comment]
too niche
