### ISSUE TITLE
[Suggestion] km/s on speed (HUD)

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#664]
Add a k/m on the speed thing in the hud so we can choose between BPS (m/s) and km/s

**Comment by C10udburst** [comment]
Also add miles per hour :trollface:

**Comment by GoldenAureuz** [comment]
I like this

**Comment by RoastedCheese** [comment]
Add inches per second

**Comment by Wide-Cat** [comment]
this is now possible with the current hud. To convert bps to kmh, multiply it by 3.6
