### ISSUE TITLE
[Suggestion] adding radar

### ISSUE THREAD

**Issue by jade0101hedenskog** [MeteorDevelopment/meteor-client#665]
**Describe the feature**
It allows you to see whats around to without turning around

**Screenshots**
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1281579-radarbro-gui-mob-player-radar

**Additional info**
Just an idea i saw the client didn't have it but I am very much fine with it not being there.
Its not really needed but a flex.

**Comment by seasnail8169** [comment]
Just use a dedicated minimap/radar mod. Its always gonna be better then something we put in HUD.
