### ISSUE TITLE
[Suggestion] .give command

### ISSUE THREAD

**Issue by The-Warlord** [MeteorDevelopment/meteor-client#668]
**Describe the feature**
A creative only command that allows you to give yourself any item in creative without having access to commands, like command blocks (which aren't in the creative menu) or items with custom nbt data (unbreakable items, etc)

**Screenshots**
N/A

**Additional info**
Additional Idea: Make it a module and add a GUI to help customize nbt data, because the structure of these commands can be quite hard to figure out at first. Probably not very high priority though.

**Comment by StormyBytes** [comment]
`.give` already exists...

**Comment by Declipsonator** [comment]
...

**Comment by AutistEren** [comment]
🐒

**Comment by The-Warlord** [comment]
> `.give` already exists...

Okay, in my defense, it just got added 5 days ago and I just updated yesterday. Sorry about that, I'll close this issue.

**Comment by kaelwood6-png** [comment]
Can u add a feature that turns like a axe or sword into basically a mace? Make it look like the original item but just behave like a mace.
