### ISSUE TITLE
End Crystal Placing Issue

### ISSUE THREAD

**Issue by AtomicGamer** [MeteorDevelopment/meteor-client#669]
Crystal Aura Place Glitch
The placing module on Meteor's Crystal Aura is quite buggy, it would do the placing animation, but the crystals wouldn't place.
Also, while the placing animation is running I would keep lagging back to my position. This was done on an anarchy server with no much anticheat too. I hope you do fix this, Meteor is the best client I've ever tried.

LMFAO ISSUE 669

**Comment by ikeafridge4** [comment]
config issue 100%
