### ISSUE TITLE
[Bug] autoarmor crash

### ISSUE THREAD

**Issue by feikaaaaa5** [MeteorDevelopment/meteor-client#672]
[crash-2021-05-05_21.17.51-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6431144/crash-2021-05-05_21.17.51-client.txt)
**Describe the bug**
game crashes with autoarmor whenever a pumpkin is worn

**To Reproduce**
turn on autoarmor
equip a pumpkin on the head slot

**Expected behavior**
game crashes

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by StormyBytes** [comment]
Can you atleast send the crash report?

**Comment by feikaaaaa5** [comment]
[crash-2021-05-05_21.17.51-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6431133/crash-2021-05-05_21.17.51-client.txt)

**Comment by feikaaaaa5** [comment]
[crash-2021-05-05_21.17.51-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6431141/crash-2021-05-05_21.17.51-client.txt)
