### ISSUE TITLE
[Bug] 1.12 server kick

### ISSUE THREAD

**Issue by DerpoDrago** [MeteorDevelopment/meteor-client#673]
**Describe the bug**
Kick for "Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraftPlayer" when on 1.12

**To Reproduce**
1. Connect to a 1.12 server
2. cpvp

**Expected behavior**
You pvp as usual

**Screenshots**
![Screenshots_2021-05-05-20-36-09](https://user-images.githubusercontent.com/67514977/117227364-a954fc80-ade4-11eb-8a64-23a056b5aac1.png)

**Additional context**
Mods: meteor, multiconnect
Modules: Auto Armor, Auto Totem, Criticals, Crystal Aura, Kill Aura, Offhand, Surround, Totem Pop Notifier, Auto Replenish, Middle Click Extra, Portals, Gui Move, No Fall, Speed, Velocity, Build Height, Anti Packet Kick, Better Chat, Vanilla Spoof
Server: us.crystalpvp.cc

**Comment by DerpoDrago** [comment]
Don't have to fight, just got kicked before even moving

**Comment by supakeks** [comment]
uuid issue

**Comment by AutistEren** [comment]
same thing happens to me on inertia
fixed by adding
-Duser.country=US -Duser.language=en -Duser.variant=Traditional_WIN
in my JVM

**Comment by DerpoDrago** [comment]
im on linux

**Comment by ikeafridge4** [comment]
why are you using meteor on 1.12 servers lol

**Comment by DerpoDrago** [comment]
no good open source 1.12 client

**Comment by AutistEren** [comment]
> same thing happens to me on inertia
> fixed by adding
> -Duser.country=US -Duser.language=en -Duser.variant=Traditional_WIN
> in my JVM

did this work

**Comment by DerpoDrago** [comment]
I cant test that becauee im using linux, if you know of a Duser.variant value for linux i could try that

**Comment by MineGame159** [comment]
This is multiconnect's problem, net meteor's
