### ISSUE TITLE
[Suggestion] Auto Mine

### ISSUE THREAD

**Issue by ngudulalose** [MeteorDevelopment/meteor-client#674]
**Describe the feature**
Automatic mining block which you are looking at.

**Additional info**
If I use _AutoClicker with hold mode_ I can't auto mine when I minimize the window and do something else.

**Comment by Drakesdrs** [comment]
Use #tunnel and you can do that if you really want automine as a seperate module from baritone, well go ahead.

**Comment by StormyBytes** [comment]
Does the F3+T trick no longer work?

**Comment by ngudulalose** [comment]
insta mine is a good alternative.

**Comment by RoastedCheese** [comment]
@ngudulalose insta mine is completely different.
It mines a block in a position where you've mined a block before.

**Comment by EpicE870** [comment]
someone actually get on this 🙏
