### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Lukaa91** [MeteorDevelopment/meteor-client#677]
**Describe the feature**
Add like a chat command .serverip where you get the Ipv4 of the server you are connected too, including port if possible.

**Screenshots**
I dont think its needed

**Additional info**
nah

**Comment by seasnail8169** [comment]
pretty sure .server does this

**Comment by C10udburst** [comment]
> pretty sure .server does this

Yeah pretty much, but it displays the address used to connect, so if you connect to `pvp.meteorclient.com` it will display `pvp.meteorclient.com`, not `157.90.39.241:25565`

**Comment by MineGame159** [comment]
Added in 5fb36bf940f6cb91c3bf7195db5eea9de089cf6e
