### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Arbisy** [MeteorDevelopment/meteor-client#678]
**Describe the feature**
AutoDupe, dupes for you.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by Declipsonator** [comment]
amazing suggestion

**Comment by Declipsonator** [comment]
I wish I had thought of this

**Comment by Wide-Cat** [comment]
me when meteor doesnt auto doop 😠

**Comment by supakeks** [comment]
HOLY SHIT THIS IS SO GOOD

**Comment by Arbisy** [comment]
I'm guessing these people are sarcastic? Am I missing something?

**Comment by C10udburst** [comment]
> I'm guessing these people are sarcastic? Am I missing something?

[yes](https://github.com/MeteorDevelopment/meteor-book-dupe-addon) and [yes](https://github.com/MeteorDevelopment/meteor-mbd-addon)

**Comment by Arbisy** [comment]
Wait then does it already exist? Cause I can't find it

**Comment by Arbisy** [comment]
Ya I know the dupe exists but is there a AUTO dupe?

**Comment by a-couple-objects** [comment]
mbd is automatic book dupe is extremely simple to automate
