### ISSUE TITLE
[Suggestion] Tunnel ESP

### ISSUE THREAD

**Issue by 453452hw** [MeteorDevelopment/meteor-client#679]
**Describe the feature**
Highlights 1x2 tunnels 

**Screenshots**
i have
![image](https://user-images.githubusercontent.com/59623580/117365857-35882200-aec0-11eb-9b44-8d08cc553662.png)

**Comment by RoastedCheese** [comment]
I agree this would be cool. I don't wanna use bleach hack with meteor and mars

**Comment by MineGame159** [comment]
Added in 4ad507bed3a3479ccd46c131722887b491f4115a.
