### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by ked17** [MeteorDevelopment/meteor-client#681]
`**Describe` the feature**
A clear and concise description of what feature/change is.
viaversion
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.
just the same viaversion that inertia uses. i don’t like using inertia on top of meteor just for the viaversion because it’s buggy and laggy

**Comment by StormyBytes** [comment]
Multiconnect
