### ISSUE TITLE
[Suggestion] Capes

### ISSUE THREAD

**Issue by goztb22** [MeteorDevelopment/meteor-client#684]
**Add a capes system like any user of meteor getting cape and seen to other meteor users, or by name not uuid**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by Wide-Cat** [comment]
there is a cape system, but you need to donate to the developers in order to get one

**Comment by seasnail8169** [comment]
Capes are one of our very few donor benefits, we have a system for capes and it uses UUIDs, not names, for obvious reasons. If you'd like a cape, or just to support us as a free, open source project, donations can be made at https://meteorclient.com/donate with a minimum of $5 for the donator benefits.

**Comment by seasnail8169** [comment]
> there is a cape system, but you need to donate to the developers in order to get one

Just to follow up, you aren't donating *to the developers*, we don't take donations as profit but rather put it back into our community, mainly paying bills for our backend web server and our Minecraft pvp server and other misc costs.

**Comment by GildedS** [comment]
> > there is a cape system, but you need to donate to the developers in order to get one
> 
> Just to follow up, you aren't donating _to the developers_, we don't take donations as profit but rather put it back into our community, mainly paying bills for our backend web server and our Minecraft pvp server and other misc costs.

Misc costs like minegame's crack addiction
