### ISSUE TITLE
[Suggestion] Add Auto Crossbow Spam Hack

### ISSUE THREAD

**Issue by ServerRanger** [MeteorDevelopment/meteor-client#689]
**Describe the feature**
With crossbows, you can preload them and store them in your inventory. This hack, would abuse this feature. To preform this hack, you would have to preload a bunch of crossbows and place them them in your hotbar/inventory. Then if you have the hack turned on and you fire one crossbow, the hack will automaticly scrollwheel through your hotbar automaticly firing the other preloaded crossbows (like a machine gun). If there is also preloaded crossbows in your inventory, the hack will automaticly replace the crossbows that were just automaticly fired (the crossbows that are empty in your hotbar) with the preloaded crossbows from your inventory. Once the hack finishes automaticly rapid firing all the crossbows, if you right click and reload one crossbow, the hack will automaticly reload the other crossbows as fast as possible.

**Additional info**
Also make it so you can change the delay between each crossbow firing.

**Comment by ServerRanger** [comment]
This means if the hack can shoot 9 crossbows in 1 sec, you can deal 99 max damage to a player in under a sec (a crossbow does 11 max damage).

**Comment by BobIsMyManager** [comment]
Yes and also option for fireworks

**Comment by The-Warlord** [comment]
> This means if the hack can shoot 9 crossbows in 1 sec, you can deal 99 max damage to a player in under a sec (a crossbow does 11 max damage).

It doesn't work like that, invulnerability frames means you can only take damage every 1/2 seconds.

**Comment by The-Warlord** [comment]
This would be useful for spamming firework particles, +1

**Comment by Diamondhero777** [comment]
I believe they should add something like the bow spam for the crossbow cuz it would be pretty cool and in some cases usefull.
