### ISSUE TITLE
[SUGGESTION] add anchor fot surround

### ISSUE THREAD

**Issue by LDoom** [MeteorDevelopment/meteor-client#695]
https://i.imgur.com/I0QNQoX.png

https://imgur.com/I0QNQoX

**Comment by StormyBytes** [comment]
wouldn't this just make it easier for people to kill you?

**Comment by Wide-Cat** [comment]
> 
> 
> wouldn't this just make it easier for people to kill you?

not in the nether, it would probably be useful because you cant put crystals on anchors, so reduced faceplacing
