### ISSUE TITLE
[Bug] Freecam while taking damage causes crash.

### ISSUE THREAD

**Issue by CountBleck** [MeteorDevelopment/meteor-client#698]
**Describe the bug**
Freecam crashes while taking damage.

**To Reproduce**
1. Trap yourself inside a block so you are constantly damaged.
2. While you take damage, turn Freecam on (I used a keybind).
3. The Minecraft client world closes and a crash message appears before your eyes.

[Here's a video](https://dropbox.com/s/723c7m0xd8wekfl/meteor_freecam_crash.mp4?dl=1)

**Expected behavior**
I expected Freecam to work normally and place me in a spectator-like view without crashing.

**Screenshots**
![Screenshot 2021-05-08 01 05 49](https://user-images.githubusercontent.com/79281724/117532147-ecf16700-af9a-11eb-8761-c6c09b5ee9de.png)

**Additional context**
Every relevant piece of information is included in the below logs. Also, I got a seemingly rare crash that, judging from the stack trace, was specific to the mods I was using and the fact that I was in a single-player world, and yet it seems to be from the same issue, since that log appeared from more or less the same steps. That stack trace, like the normal crash, also mentions threads.

[Here's what a normal crash log normally looks like.](https://github.com/MeteorDevelopment/meteor-client/files/6445520/crash-2021-05-08_01.10.39-server.txt)
[Here's the weird, mod-specific one.](https://github.com/MeteorDevelopment/meteor-client/files/6445524/possibly_rare_meteor_crash.log)

**Comment by MineGame159** [comment]
Fixed
