### ISSUE TITLE
[Bug] AirPlace interacting with blocks when it shouldn't

### ISSUE THREAD

**Issue by The-Warlord** [MeteorDevelopment/meteor-client#703]
**Describe the bug**
When you airplace a block next to a bed, for example, sometimes you will click on the bed instead of placing the block. I haven't tested this with other blocks, but it should be easily fixable by sending a shift packet.
Also, airplace swings your hand even when it doesn't place blocks. For example, if you hold a carrot and right click in the air, it swings your hand even though there is nothing to place.
**To Reproduce**
Place bed in air
Set your airplace block next to bed
Hold block and right click
**Expected behavior**
Block should be placed

**Comment by seasnail8169** [comment]
For me this is what it should do, airplace shouldn't stop you from interacting with blocks, if you want to not interact with a block just shift click it, airplace is for *placing in the air*.
