### ISSUE TITLE
[Suggestion] Tile Entity Support for No Render

### ISSUE THREAD

**Issue by Cypphi** [MeteorDevelopment/meteor-client#705]
**Describe the feature**
An option on No Render to prevent rendering of specific tile entities such as chests and shulker boxes.

**Additional info**
this would be similar to Tweakeroo's no render for tile entities

**Comment by agua420** [comment]
add this please

**Comment by Cypphi** [comment]
> add this please

Wtf this is still a thing

**Comment by Cypphi** [comment]
Honestly might just make a pull request for it when I have time
