### ISSUE TITLE
[Bug] Liquid filler ghost blocks

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#709]
when filling water with liquid filler it often places ghost ghost blocks above you in positions that seem related to the position of the water
**To Reproduce**
1. place a bunch of water
2. toggle liquid filler
3. move in the water

**Comment by Wide-Cat** [comment]
This has happened to me as well before, its been a bug for ages https://youtu.be/U47OnA8D6oM

**Comment by StormyBytes** [comment]
Does this still happen in latest dev builds?

**Comment by RedCarlos26** [comment]
It's still happening on latest version

**Comment by RedCarlos26** [comment]
@StormyBytes its still still hapenning...
