### ISSUE TITLE
[Suggestion] remove hand swing and dinamic fov when using freecam while baritoning

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#710]
it's pretty annoying when you freecam while using baritone, your hand keeps swinging and your fov keeps changing because the bot sprints.

**Comment by seasnail8169** [comment]
You can disable the rendering of your hands in freecam

**Comment by Megahaosguy** [comment]
Bobbing still occurs even with hand rendering disabled while in freecam using baritone pathing.

**Comment by Wide-Cat** [comment]
should be resolved with the static setting added ages ago
