### ISSUE TITLE
[SUGGESTION] 2D esp

### ISSUE THREAD

**Issue by bigMax69** [MeteorDevelopment/meteor-client#716]
**Describe the feature**
Hi, can you add 2D esp.

**Screenshots**
Something like this: 
![image](https://user-images.githubusercontent.com/62725017/117637756-68f9d380-b182-11eb-857c-fde2e585fe76.png)

**Additional info**
Add any other info.

**Comment by Cypphi** [comment]
yes 2d esp very very secksy

**Comment by MineGame159** [comment]
#500
