### ISSUE TITLE
[Bug] i had auto log on to log me out when a person with a 32k was near, i then  put it to if my health is lower then 20 when a 32k person was near it would log me out. so now i can't log onto any server without being logged out

### ISSUE THREAD

**Issue by Penguins211** [MeteorDevelopment/meteor-client#717]
i had auto log on to log me out when a person with a 32k was near, i then put it to if my health is lower then 20 when a 32k person was near it would log me out. so now i can't log onto any server without being logged out 
![Screen Shot 2021-05-10 at 8 02 33 AM](https://user-images.githubusercontent.com/83964768/117671503-15798c80-b166-11eb-8823-355564f601b4.png)

**Comment by MineGame159** [comment]
You had "Smart" setting on which disconnects you when it thinks you are going to take enough damage to kill you. That said you can open the GUI in main menu the same way you would in-game to disable it.
