### ISSUE TITLE
[Bug] Pickaxe and Block forced into hotbar

### ISSUE THREAD

**Issue by sbxte** [MeteorDevelopment/meteor-client#718]
**Description**
If there is a pickaxe in the inventory and it is not in the hotbar.
Meteor will force the pickaxe into the first hotbar slot.

Same thing happens to blocks. 
The blocks will be forced into the last hotbar slot.

Even with all modules turned off. This behavior still happens

**Expected behavior**
Pickaxe and block not forced into hotbar.

**Video**
https://streamable.com/493k6r

**Additional context**
Mods : Sodium, Phosphor, Lithium, Multiconnect, Meteor dev build 843

**Comment by MineGame159** [comment]
Do `#allowInventory false`. Its a baritone setting that causes it.
