### ISSUE TITLE
[Suggestion] Auto spawn proof

### ISSUE THREAD

**Issue by Th3L1nk** [MeteorDevelopment/meteor-client#719]
**Describe the feature**
A module that if enabled would continually check for solid block surfaces within placing range and if any were found would automatically cover them in slabs if there were some in the inventory

**Screenshots**
![Screenshot 2021-05-10 142021](https://user-images.githubusercontent.com/80180485/117706094-e16c8e80-b19a-11eb-9be4-fa209747a3b3.png)

would be for spawn-proofing biomes

**Additional info**
Add any other info.

**Comment by RoastedCheese** [comment]
Bruh dude what are you planning

**Comment by MineGame159** [comment]
Added
