### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by cpj6789** [MeteorDevelopment/meteor-client#722]
**Describe the feature**
Please add a toggle for the entire Render section of modules, similar to how you can disable just hud, so you can instantly disable tracers, esp, hud, and all that, making the game looks vanilla. I know this can be done with profiles, but this would still be pretty cool to see in a future update.

**Screenshots**
![something like this](https://user-images.githubusercontent.com/83755138/117756938-13a6dc00-b1ed-11eb-87ef-6a4afbfc4dfb.png)
(I know it's really bad but something like that. Maybe a command or something).

**Comment by UZIvanity** [comment]
yes add that
