### ISSUE TITLE
[Bug] Search blocks maintain when you change dimension

### ISSUE THREAD

**Issue by RoastedCheese** [MeteorDevelopment/meteor-client#723]
when you go from the overworld to the nether or opposite sometimes search highlights blocks that where highlighted there in the other dimension.
for example when you enter nether hub on ecme it sometimes highlights portal blocks that are actually at overworld hub.
the portal blocks that are in the current dimension are however highlighted correctly.

**Comment by RoastedCheese** [comment]
![2021-05-11_14 52 46](https://user-images.githubusercontent.com/75800121/117832716-05e96900-b276-11eb-8ea9-10657e23d28e.png)

**Comment by MineGame159** [comment]
Fixed in 26562a5aa53a818c5f9cdb74d72471f0aed61ddc
