### ISSUE TITLE
[Bug] Load Issue with OptiFabric & Optifine?

### ISSUE THREAD

**Issue by jprknight** [MeteorDevelopment/meteor-client#724]
**Describe the bug**

I am trying to load the Meteor client along side OptiFabric and Optifine. I get a game crash every time I include the Meteor Jar. Game loads and plays fine without the Meteor Jar.

**To Reproduce**
1. Added the flowing into mods folder: fabric-api-0.34.2+1.16.jar, OptiFine_1.16.5_HD_U_G7.jar, optifabric-1.9.6.jar and meteor-client-0.4.3.jar.
2. Hit "Play" in the launcher.
3. See error game crashed "unexpected error occurred..exit code 0"
4. Collected more in depth info from the error log.

**Expected behavior**
Expecting Meteor client to load with Optifine / OptiFabric.

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).
Pastebin log: https://pastebin.com/YeHEfGYU

**Comment by MineGame159** [comment]
Known and won't be fixed.
