### ISSUE TITLE
[SUGGESTION] i'm thinking, you should probably redo the fly mod. Its very slippery and its hard to stop unless you touch the ground. can you try to make the fly maybe more like impact, or wursts fly? 

### ISSUE THREAD

**Issue by smopjop** [MeteorDevelopment/meteor-client#730]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by StormyBytes** [comment]
Similar to #506 static fly.

**Comment by Cypphi** [comment]
static fly

**Comment by Declipsonator** [comment]
_Velocity Flight_
