### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Fioflix** [MeteorDevelopment/meteor-client#731]
auto mlg
![2021-05-12_14 51 13](https://user-images.githubusercontent.com/83435685/118028907-9f298580-b331-11eb-90c0-5acd8fc4b953.png)
when falling from a high area and you have a waterbucket in your hotbar it auto places the water preventing fall damage, you can customize the module by turning on and off things such as cobwebs, slime, and other blocks that prevent fall damage
maybe using surround mechanics? More like a unpatchable no fall

**Comment by MineGame159** [comment]
Already in the client. No Fall with water bucket mode.
