### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by boberek18** [MeteorDevelopment/meteor-client#734]
**Describe the feature**
A clear and concise description of what feature/change is. add chest info that i can see what is in chest on freecam and thing to noclip

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by Wide-Cat** [comment]
🤨

**Comment by RoastedCheese** [comment]
1. that's not possible
2. what
