### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zllliz-hub** [MeteorDevelopment/meteor-client#735]
add STRAFE NOT BHOP AM NOT ASKING FOR BHOP NOR NCP THATS BHOP AM ASKING FOR MF STRAFE ADD IT BRO

**Comment by RickyTheRacc** [comment]
Cope?

**Comment by RoastedCheese** [comment]
:trollface:

**Comment by a-couple-objects** [comment]
> add STRAFE NOT BHOP AM NOT ASKING FOR BHOP NOR NCP THATS BHOP AM ASKING FOR MF STRAFE ADD IT BRO

5.6 speed

**Comment by zllliz-hub** [comment]
ADD?
