### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by StepNikTteCoder** [MeteorDevelopment/meteor-client#737]
Add Not solid option into Scaffold for slap scaffolding

private final Setting<Boolean> notSolid = sgGeneral.add(new BoolSetting.Builder()
            .name("not-solid")
            .description("Allow place not solide blocks.")
            .defaultValue(false)
            .build()

// Filter out non solid blocks
        Block block = ((BlockItem) handStack.getItem()).getBlock();
        slotBlockState = block.getDefaultState();
        if (!notSolid.get() && !Block.isShapeFullCube(slotBlockState.getCollisionShape(mc.world, setPos(0, -1, 0)))) return slot;

**Comment by Declipsonator** [comment]
You know you can add stuff yourself right?

**Comment by RedCarlos26** [comment]
@StepNikTteCoder ^^

**Comment by seasnail8169** [comment]
That also wouldn't work at all
