### ISSUE TITLE
[SUGGESTION] Add Phase or Noclip

### ISSUE THREAD

**Issue by Shygal113** [MeteorDevelopment/meteor-client#742]
**Describe the feature**
Phase or Noclip Is where you can go trough walls or certain blocks

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by Texbio** [comment]
There is already Vclip. Hclip is not implemented in this client.

**Comment by seasnail8169** [comment]
literally.hclip 🤦‍♂️
