### ISSUE TITLE
[SUGGESTION]Addition to search module & storage esp module

### ISSUE THREAD

**Issue by necrophili** [MeteorDevelopment/meteor-client#752]
Allow the search module to also search for entities and items, not only blocks. Instead of having to search for entities using tracers, this can be moved to the search module.

Allow storage esp to also search for entities such as, minecart chest, minecart hoppers, etc and item frames.

**Comment by seasnail8169** [comment]
Literally makes 0 sense

**Comment by GildedS** [comment]
Storage esp and esp with tracers moment
