### ISSUE TITLE
[Bug] BowAimbot simply doesn't work

### ISSUE THREAD

**Issue by supakeks** [MeteorDevelopment/meteor-client#753]
**Describe the bug**
BowAimbot is supposed to make you look at an entity depending of your settings when holding a charged bow but it doesn't do anything.

**To Reproduce**
1. Turn on aimbot
2. Make sure you have the correct settings for bow aimbot to work
3. Bow Aimbot will simply not work

**Expected behavior**
BowAimbot should make the player look at the entity our settings choose when holding a charged bow

**Additional context**
Meteor Version: 0.4.3 dev-build 853

**Comment by StormyBytes** [comment]
Works fine for me. Im on dev build 861

**Comment by MineGame159** [comment]
Same, works fine

**Comment by Drakesdrs** [comment]
Use aimassist and bowaimbot (this will not work if you are shooting from a high place.

**Comment by supakeks** [comment]
Ok, I think bowaimbot only works with normal arrows, I'll test this in a bit and update this comment

**Comment by StormyBytes** [comment]
Yea, Bow Aimbot only works with normal arrows.
