### ISSUE TITLE
[SUGGESTION] Spoof Blocks Module Suggestion

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#755]
I suggested this in #630 but forgot to include a bunch of key details.

**Describe the feature**
I want a module that when toggled could replace certain blocks with other ones visually. I also want certain blocks like grass and flowers to be compatible with being able to be replaced with air and being able to swing though those like normal (instead of adding it to the spoof blocks module you could just add them to 'no render')

**Additional info**
Inertia client already as a spoof module where you can spoof certain blocks but it is super laggy.

**Comment by seasnail8169** [comment]
This is so unclear about what it does. "spoof blocks" is so meaningless. What are you actually wanting to "spoof"??

**Comment by Texbio** [comment]
If you could just add a module to be able to remove grasses and flowers from rendering on the client that would work instead. 

I wanted something where you could pick a block [tall grass] then pick another block to replace it with [air] and you could not mine it since that is a block that normally has no collision with the player. You could also choose [barriers] and replace them with something like [stone], but if you picked a block like [dirt] and tried replacing it with [air], it would just make it invisible like a barrier but you could still mine it the same as normal dirt. 
SO:
tall grass -> air (can't see it and cant mine)
dirt -> air (can't see but can still mine, still collides with the player)
