### ISSUE TITLE
Offhand BROKEN

### ISSUE THREAD

**Issue by SKRecreated** [MeteorDevelopment/meteor-client#758]
**Describe the bug**
Offhand COMPLETEY GLITCHY
**To Reproduce**
1. Turn on auto totem and offhand extra
Do that (below
Make AT health 10, smart, inventory, and yeah
And make off-extra replace, crystal, 15 hp, self toggle, sword gap, offhand crystal on ca, and yeah.
![image](https://user-images.githubusercontent.com/70330761/118526320-c96fae80-b748-11eb-80df-66f75857a598.png)

3. Make them on. Now it wont work and only once has the crystal been equipped for a brief period and replaced.

**Expected behavior**
Auto totem will work but offhand WONT.

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).
Latest meteor version (not dev)

**Comment by supakeks** [comment]
Update your meteor before reporting an issue

also that's a config issue, offhand also worked before the rewrite

**Comment by SKRecreated** [comment]
> Update your meteor before reporting an issue
> 
> also that's a config issue, offhand also worked before the rewrite

its updated and wdym update

**Comment by SKRecreated** [comment]
It also still doesnt work after reseting

**Comment by supakeks** [comment]
Update to latest dev build, you can find those in the discord

Also, offhand still worked before the rewrite, what you're experiencing is a config issue but I don't blame you because the setting names are horrible

**Comment by SKRecreated** [comment]
So basically I found out that it works with gap (the offhand) but it wont work if I enable sword gap or one of those settings. Doesnt work w/ crystals (I didnt try gaps and exp)

**Comment by supakeks** [comment]
Did you update to latest dev build

**Comment by SKRecreated** [comment]
OMG THANK YOU SO MUCH YOU'RE LITERALLY AMAZING IT WORKS!!!!
