### ISSUE TITLE
[Adding Entities/Players to the Reach function.]

### ISSUE THREAD

**Issue by Bowievds** [MeteorDevelopment/meteor-client#761]
**Describe the feature**
With the current Reach option in Meteor Client. You can only increase the range of your hands. This means you'll be able to place blocks  and use blocks from further away. But It won't increase your hit range when attacking players/mobs. Being able to increase your hit reach would make the "Reach" option way more fun and special. This would also give players a advantage in pvp even without Killaura.

**Comment by a-couple-objects** [comment]
don't use on servers with anticheat
