### ISSUE TITLE
[Suggestion] Bedrock Obfuscator

### ISSUE THREAD

**Issue by Drakesdrs** [MeteorDevelopment/meteor-client#762]
**Describe the feature**
# Bedrock obfuscator
Rearranges Bedrock at the bottom of the world and top of the Nether to avoid seed searching.

**Comment by Drakesdrs** [comment]
what why

**Comment by flaxeneel2** [comment]
It was closed because meteor is a utility mod and not an anticheat. Requesting such features here is useless, anyways, how can a client do that in the first place? Thats more of a plugin type feature than a client feature.

**Comment by seasnail8169** [comment]
exactly, you didnt even say how this would work...

**Comment by Drakesdrs** [comment]
> 
> 
> It was closed because meteor is a utility mod and not an anticheat. Requesting such features here is useless, anyways, how can a client do that in the first place? Thats more of a plugin type feature than a client feature.

it  has been implemented in other clients

**Comment by seasnail8169** [comment]
so?

**Comment by flaxeneel2** [comment]
> > It was closed because meteor is a utility mod and not an anticheat. Requesting such features here is useless, anyways, how can a client do that in the first place? Thats more of a plugin type feature than a client feature.
> 
> it has been implemented in other clients

I mean you didnt even explain what it does or why one would need it, you just basically said oH OtHeR ClIeNtS hAvE iT sO iT ShOuLd bE AdDeD tO mEtEoR tOo

**Comment by LysergikProductions** [comment]
@Drakesdrs  You would need to be in creative mode to use it. If you are _worried_ about seed finding and have access to creative mode, that probably means you have operator status. you would want to use a server plugin to modify the bedrock at the time it is generated rather than a client mod rearranging blocks with creative mode access.
