### ISSUE TITLE
Auto BedTrap Module

### ISSUE THREAD

**Issue by GoldenAureuz** [MeteorDevelopment/meteor-client#763]
It'd automatically bedtrap beds when activated, prefferably with a couple different options as for the bedtrap method.

SS: https://user-images.githubusercontent.com/62858980/118576995-9b459b00-b757-11eb-8ad7-eaf342f2c7c5.png
(red is lava, light blue is bed, obsidian is yellow because of my texture pack)

Just to clarify, this would be used to trap a bed that's already there. Maybe allow block placement speed and other stuff to be configured with server compatability.

**Comment by seasnail8169** [comment]
How often/much do you really need to bed trap someone lmfao. This is extremely niche and would be bloat
