### ISSUE TITLE
[Suggestion] Minimum wideness for click gui columns

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#765]
Make the columns in the click GUI a certain size (wideness) because it's not really esthetic to have a really skinny column. For example, the render and player columns are a good wideness, but the combat and world columns are too skinny.
![2021-05-18_09 44 28](https://user-images.githubusercontent.com/58893097/118662295-e397a400-b7bd-11eb-8a30-37e68e79661e.png)

**Comment by Drakesdrs** [comment]
I mean the combat column is skinny because it has many modules and on some devices if it is the same side (for example) render it wouldn't fit on some screens.

**Comment by RedCarlos26** [comment]
Maybe, but I'm not talking of the vertical size, I am talking about the horizontal length of the categories.

**Comment by RedCarlos26** [comment]
When? 😢

**Comment by RedCarlos26** [comment]
Close caus bruh
