### ISSUE TITLE
[Bug] Friends settings are missing

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#767]
The friends settings are missing in the latest dev build (neutral, trusted, enemy) (build #875).

![2021-05-18_10 59 28](https://user-images.githubusercontent.com/58893097/118674899-252d4c80-b7c8-11eb-866b-1b512e639d78.png)

**Comment by seasnail8169** [comment]
They were removed

**Comment by RedCarlos26** [comment]
> They were removed

Why though it was really useful.
