### ISSUE TITLE
[Bug] Nametag color option is missing in the nametag GUI

### ISSUE THREAD

**Issue by RedCarlos26** [MeteorDevelopment/meteor-client#769]
This does that the nametags of players (not friends) are white, but I made them blue before. (It was working before the friends rewrite).

![2021-05-18_11 19 16](https://user-images.githubusercontent.com/58893097/118678313-e6e55c80-b7ca-11eb-8e73-ece271d55ce9.png)

**Comment by seasnail8169** [comment]
This was removed

**Comment by RedCarlos26** [comment]
Why can't we customise the nametag colors?

**Comment by RedCarlos26** [comment]
This is not related to friends

**Comment by RedCarlos26** [comment]
@seasnail8169 ?
