### ISSUE TITLE
Make it so you can choose the cps of trigger[SUGGESTION]

### ISSUE THREAD

**Issue by Th3L1nk** [MeteorDevelopment/meteor-client#773]
**Describe the feature**
A clear and concise description of what feature/change is.
Make it so that you can choose how fast trigger clicks, on servers with 1.8 pvp it clicks a billion times a second
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.
pee

**Comment by seasnail8169** [comment]
Trigger was removed, its now part of kill aura

**Comment by GildedS** [comment]
Stop using meteor on 1.8 pvp servers tard
