### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by NIGHTMARIO** [MeteorDevelopment/meteor-client#781]
I want a module that is fast block placement. This module is from the mod tweakroo in fabric. This module is the only reason I use tweakroo. I want to get rid of tweakroo but still want this feature so it's a suggestion. There's a similar feature in meteor which is fast use but I feel that fast use doesn't place blocks fast enough. It feels like this module kind of disables the Minecraft clicks limit. It can be tried after installing tweakroo because I can't give much description on this module.

**Comment by seasnail8169** [comment]
They are the same
