### ISSUE TITLE
make in profiles an option for hotkey switch

### ISSUE THREAD

**Issue by tygoz** [MeteorDevelopment/meteor-client#784]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by seasnail8169** [comment]
You can do this with macros, for example a macro for ".profile load meteorpvp". You can also make profiles load when you join a server with a specific ip

**Comment by tygoz** [comment]
oh thanks
