### ISSUE TITLE
auto config module for example you are in hypixel and you go in mineplex or somefing and ther is the anti cheat other and it optimaliseert per server

### ISSUE THREAD

**Issue by tygoz** [MeteorDevelopment/meteor-client#786]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by StormyBytes** [comment]
1. I have already mentioned it is impossible to do this in your previous issue.
2. Dont use meteor on servers where it is forbidden.
