### ISSUE TITLE
[Bug] nbt add not working.

### ISSUE THREAD

**Issue by YurniKismet** [MeteorDevelopment/meteor-client#792]
**Describe the bug**
using ".nbt add" with display tags only works if

**To Reproduce**
1. Hold item in your hand that does not have any vanilla attributes, enhcants, or potion effects. (Armor, Enchanted books, and Potions will not reproduce this issue)
2. attempt to add a display tag 
Example: .nbt add {display:{Name:'[{"text":"Example","italic":false}]',Lore:['[{"text":"Example","italic":false}]']}}
3: See error

**Expected behavior**
I expect the display tag along with its sub tags to be added.

**Screenshots**
![Screenshot of error](https://user-images.githubusercontent.com/81452891/118868927-65fd9200-b8aa-11eb-9c66-65a6f7fca1f6.png)

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).
Meteor version: v0.4.3 Build #888, MCVersion: 1.16.5. No other mods should interfere with this.

PS: this could potentially be a feature and not a bug but if thats the case ill remake this as a suggestion post as you shouldnt be restricted to ".nbt set" to add a tag

**Comment by Wide-Cat** [comment]
I would assume this fails because the item does not already have nbt data to add to, which is why it works for enchanted books and potions, which already have nbt by default. When I hold an item that does not already have nbt and do `.nbt set {display:{Name:'[{"text":"Example","italic":false}]',Lore:['[{"text":"Example","italic":false}]']}}`, it works fine.

**Comment by wejfbioeua** [comment]
Yea, thing is if a display tag already exists say {display:{Name:'[{"text":"Example","italic":false}]',Lore:['[{"text":"Example","italic":false}]']}} and then you try and add to it, it over writes it so I dont understand the need for the NBT to already be there.

**Comment by FolfyBlue** [comment]
I was about to report the same thing, I agree with their reasoning that it should work with nbt add.

**Comment by MineGame159** [comment]
Fixed in 676f95a8ac4ae660687a9929f38cc5213f1db83b

**Comment by RickyTheRacc** [comment]
Also please use 0.4.4

**Comment by FolfyBlue** [comment]
> Also please use 0.4.4

We can't use versions that weren't out yet at the time bruh
