### ISSUE TITLE
[Bug] Search rendering outside of your render distance

### ISSUE THREAD

**Issue by 453452hw** [MeteorDevelopment/meteor-client#795]
**Describe the bug**
search config not affect blocks outside of render distance

**Screenshots**
![image](https://user-images.githubusercontent.com/59623580/118990833-851c2280-b983-11eb-8b31-5731c95289bf.png)

**Comment by RedCarlos26** [comment]
Can confirm on latest version

**Comment by RedCarlos26** [comment]
Duplicate of #699 @arlomcwalter

**Comment by 453452hw** [comment]
damn this still aint fixed. this was fucking may

**Comment by RedCarlos26** [comment]
Yea pls close since it's a duplicate
