### ISSUE TITLE
[Bug] Kill aura does not work in FreeCam 

### ISSUE THREAD

**Issue by mokw** [MeteorDevelopment/meteor-client#799]
**Describe the bug**

Kill aura will only work in freecam if you are close to the target, you can see me demonstrate it in the gif below.

**To Reproduce**

1. Enable Kill Aura
2. Go into FreeCam
3. Freecam away from your target and watch as it stops attacking/working.

**Expected behavior**
Considering having random teleport enabled with kill aura is quite disorienting, I would have liked to be able to freecam with it enabled, turns out it does not work.

**Screenshots**
https://bean.forsale/dWW3xAsCXj.gif?key=wGumiq5b3CvqcM

**Additional context**
Dev build 890, as well as sodium.

**Comment by necrophili** [comment]
Nor does air jump

**Comment by StormyBytes** [comment]
Fixed in fba7f38a75619b8dd6f3f8c82e22bb64a33bdde8

**Comment by RedCarlos26** [comment]
@seasnail8169
