### ISSUE TITLE
Replay Mod

### ISSUE THREAD

**Issue by orangemn6** [MeteorDevelopment/meteor-client#8]
When I use this with the replay mod minecraft crashes, but without meteor minecraft works fine

**Comment by seasnail8169** [comment]
could you attach a crash report please.

**Comment by notseanyay** [comment]
other mods are not supported

**Comment by MineGame159** [comment]
Sean thats just not true, and yes attach a crash report

**Comment by orangemn6** [comment]
```
[2020-11-19-4.log.gz](https://github.com/MeteorDevelopment/meteor-client/files/5578882/2020-11-19-4.log.gz)

**Comment by orangemn6** [comment]
I cant paste it or chrome crashes

**Comment by seasnail8169** [comment]
To me that looks like an issue with replay mod, not meteor. Some sort of texture fetching thing.

**Comment by MineGame159** [comment]
Yeah this is not a Meteor issue
