### ISSUE TITLE
[Suggestion] Customfont

### ISSUE THREAD

**Issue by EndermanHackerVN** [MeteorDevelopment/meteor-client#801]
Custom font renderer? Like you can choose the font that will be used to render the meteor gui

**Comment by IIpho3nix** [comment]
already exist

open meteor client folder replace that tff with another one

**Comment by MineGame159** [comment]
You can, If you use dev builds then inside config tab there is a dropdown to select font. To add other fonts just put the .ttf file inside .minecraft/meteor-client/fonts
