### ISSUE TITLE
[Bug] Unable to GUI Move when using freecam

### ISSUE THREAD

**Issue by tyrannus00** [MeteorDevelopment/meteor-client#803]
**Describe the bug**
While freecam is active, the gui move module does nothing.

**To Reproduce**
Pretty self explanatory I think.

**Expected behavior**
I would expect to be able to move when having my inventory open, even when in freecam.

**Comment by RedCarlos26** [comment]
I can confirm

**Comment by MineGame159** [comment]
Fixed in f0546c180666a6fd2871074d4de0653f76019414.
