### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mokw** [MeteorDevelopment/meteor-client#804]
**Describe the bug**

Both the ESP and Nametags colors are overridden by a player's nametag color.

**To Reproduce**
1. Set a custom ESP color
2. Go to a server where the name tag color (in the tab list) is any color, (red, white, green, etc,) and watch as the color you set for ESP and nametags is overridden.

**Expected behavior**
I wanted to be able to set a custom color for every player, but it really sucks that the ESP and nametag colors are overridden :/

**Additional context**
Meteor dev build 890, as well as sodium.

**Comment by seasnail8169** [comment]
This is not a bug, its intentional. Despite this… i guess i can add the settings back.
