### ISSUE TITLE
[Bug] ESP Driver Crash

### ISSUE THREAD

**Issue by 453452hw** [MeteorDevelopment/meteor-client#806]
**Describe the bug**
Game + amd drivers crash when using ESP in dev build 890

**Screenshots**
![image](https://user-images.githubusercontent.com/59623580/119220344-58cee600-baea-11eb-8b2e-5999e0bc5010.png)

**Additional context**
Graphics card: AMD Radeon RX 580. I have my drivers all updated.
i think this is helpful
[hs_err_pid19128.log](https://github.com/MeteorDevelopment/meteor-client/files/6526116/hs_err_pid19128.log)

**Comment by MineGame159** [comment]
Fixed in 9c347b08238573b15d435783eb445946b08a675e
