### ISSUE TITLE
Random blocks appear

### ISSUE THREAD

**Issue by TheTongPro** [MeteorDevelopment/meteor-client#808]
pls help there are random blocks appearing on every single server also premium ones
![2021-05-22_19 26 31](https://user-images.githubusercontent.com/84638084/119235630-c3584400-bb33-11eb-85e7-bdb85378843b.png)

**Comment by seasnail8169** [comment]
what do you mean by random blocks

**Comment by TheTongPro** [comment]
like i can't see anything

**Comment by Cypphi** [comment]
> like i can't see anything

provide information about what's happening.
what mods do you run except meteor?
what version?

**Comment by TheTongPro** [comment]
I run sodium and fabric api, same issue with 0.4.3 and 0.4.2 versions, and sodium ain't the problem since I've uninstalled the client and the issue was gone

**Comment by seasnail8169** [comment]
I still don't understand what the "problem" is

**Comment by TheTongPro** [comment]
it looks like i am inside of a block but i really isn't

**Comment by seasnail8169** [comment]
Can you please actually describe what you see/is happening in a bit more detail, i really have no idea what you are talking about.

**Comment by TheTongPro** [comment]
air is replaced with like dirt, wood, leaves etc, and i can't really see anything

**Comment by seasnail8169** [comment]
what mods are you using, and what meteor modules do you have enabled

**Comment by TheTongPro** [comment]
mods ain't the problem
![image](https://user-images.githubusercontent.com/84638084/119701731-fc0a5d00-be54-11eb-81c1-d65d13c49e77.png)
![Skærmbillede 2021-05-26 190400](https://user-images.githubusercontent.com/84638084/119702111-63281180-be55-11eb-8e32-84a2bb09dfe0.png)

**Comment by RedCarlos26** [comment]
Try removing all the other folders and see if it fixes the problem.

**Comment by TheTongPro** [comment]
Fabric only loads the jars and not jars in sub-folders

**Comment by seasnail8169** [comment]
Does this still happen with latest release and updated mods?

**Comment by MineGame159** [comment]
I am 99% this was problem with Sodium
