### ISSUE TITLE
.panic "forget"

### ISSUE THREAD

**Issue by EMCgaming** [MeteorDevelopment/meteor-client#809]
when you do .panic, to disable all module ,to disappear from the recent commands that can be brought up with the arrows keys when you are in chat so when you get screen shared they cant find it easily

**Comment by seasnail8169** [comment]
You can just do .clear-chat which clears all history, pretty sure it clears the stuff that comes up when you press up too. Also meteor is an anarchy mod, shouldn't be used on servers that don't allow it.
