### ISSUE TITLE
Better baritone integration

### ISSUE THREAD

**Issue by JFronny** [MeteorDevelopment/meteor-client#81]
Currently if you enable Jesus baritone commands will still assume walking on water doesn't work. It would be great if that setting of baritone could be synced with the jesus hack and hidden in the baritone tab. It would also be great if baritone waypoints were synced with meteor waypoints and the gui allowed click-based starting of the pathing.

**Comment by notseanyay** [comment]
It works fine for me.

**Comment by JFronny** [comment]
At least waypoint syncing is definit. not there in the latest stable release (dev had some issues)
