### ISSUE TITLE
[Suggestion] Give us an option to download older versions of Meteor. 

### ISSUE THREAD

**Issue by ikeafridge4** [MeteorDevelopment/meteor-client#811]
This is all. I want to download early versions of Meteor but I can't find them anywhere except looking through old commits, which is a bit confusing at times. It would be nice if you could bring back the releases tab so we can download older versions.

**Comment by MineGame159** [comment]
If you really want it then you can build it yourself.

**Comment by ikeafridge4** [comment]
bruh

**Comment by a-couple-objects** [comment]
#dev-builds channel in discord
