### ISSUE TITLE
Anti Book Ban

### ISSUE THREAD

**Issue by Kermanium294** [MeteorDevelopment/meteor-client#816]
**Describe the feature**
Prevents a player from getting kicked by books filled with large unicode characters or increase the threshold. I know that there's always a point until it doesnt work anymore, but there can at least be an increased limit. Obviously anti packet kick exists but I don't think it works.

**Comment by MineGame159** [comment]
As you said, anti packet kick should work.

**Comment by LysergikProductions** [comment]
Does anti-packet kick work for receiving packets as well sending packets?

I know for sure in v0.4.2 `PacketPlayOutMapChunk` packets still kick the player 100% of the time. (aka the bug behind TE chunk bans)
