### ISSUE TITLE
[Suggestion] Anti Ghost Blocks

### ISSUE THREAD

**Issue by 453452hw** [MeteorDevelopment/meteor-client#818]
**Describe the feature**
Anti ghost block.

**Comment by Lovecrafts-Cat** [comment]
Yeah so how does it work? Give an explanation, an example,  a video of it, anything.

**Comment by Wide-Cat** [comment]
In 1.12, according to earthcomputer, you could send a stop digging packet for every block within a certain range to get the server to send the blocks to you. I think it still works in 1.16

**Comment by ehylo** [comment]
https://www.curseforge.com/minecraft/mc-mods/antighost

**Comment by necrophili** [comment]
> In 1.12, according to earthcomputer, you could send a stop digging packet for every block within a certain range to get the server to send the blocks to you. I think it still works in 1.16

Same goes for placing blocks, every blocks u placed sends a request to the server to confirm whether the block is there or not, though this needs to be adjusted somehow as requesting too much would get u packet kicked
