### ISSUE TITLE
[Suggestion] Add "waterlogged" tag to "Looking at" HUD element

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#821]
**Describe the feature**
As the title says

**Screenshots**
![2021-05-23 21_55_18-Minecraft 1 16 5 - Multiplayer (3rd-party Server)](https://user-images.githubusercontent.com/52252627/119274730-a134f380-bc11-11eb-9cff-12b8264e3dc3.png)

**Additional info**
Make it a toggleable option, not everyone wants/needs to see if a block is waterlogged

**Comment by flaxeneel2** [comment]
Seems easy enough

**Comment by flaxeneel2** [comment]
Added
![image](https://user-images.githubusercontent.com/60919292/119342496-371a5e00-bca6-11eb-998c-98c432252f99.png)
![image](https://user-images.githubusercontent.com/60919292/119342518-40a3c600-bca6-11eb-96df-2f5668889453.png)
I will make a PR, a sec

**Comment by flaxeneel2** [comment]
welp. it is now in the client, Please use client dev version 898 or newer to see it.

**Comment by RedCarlos26** [comment]
This got added. Can be closed now ;). @Lovecrafts-Cat
