### ISSUE TITLE
[Suggestion] Kill aura tps sync

### ISSUE THREAD

**Issue by 453452hw** [MeteorDevelopment/meteor-client#822]
**Describe the feature**
Have the timing of the hits sync with tps.

**Comment by Wide-Cat** [comment]
this would probably be better suited as an all-purpose tps sync module

**Comment by seasnail8169** [comment]
what would that even do?

**Comment by 453452hw** [comment]
bruh. Sync timing with tps of the server

**Comment by seasnail8169** [comment]
Idk how that would work or improved ka, it hits consistently regardless?

**Comment by flaxeneel2** [comment]
Well, I may be wrong, but from what I can gather from the name itself, its a module which slows down the modules according to the TPS of the server, which would prevent being detected if the server has some kind of sudden lag spike, for ex if you are hitting at 10 cps and the server dips to 2 tps for some reason (idk man get a better server lol), then suddenly in the server's eyes, the person's CPS will increase by a lot and then ban them for it, tps sync basically prevents that by adjusting the parameters (such as CPS) according to the server's TPS.

**I COULD BE WRONG**. This is just a guess.

**Comment by a-couple-objects** [comment]
> Idk how that would work or improved ka, it hits consistently regardless?

yeah  but attack speed would go down so you do less damage

**Comment by necrophili** [comment]
> Idk how that would work or improved ka, it hits consistently regardless?

Some hits still miss from my experience

**Comment by MineGame159** [comment]
Added in 6daa58353f1d04fc70e37c074bf72d9e5079fe72
