### ISSUE TITLE
[Suggestion] Add compatibility for the Nether sky to the Ambience module.

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#823]
**Describe the feature**
At the moment you're only able to change the color of the sky in the nether by enabling End mode and changing the end color, but that looks ugly as fuck with the grainy texture. I'm not sure if there's something keeping it from applying to the Nether, but if possible please make it apply to the Nether.

**Comment by Wide-Cat** [comment]
exists
