### ISSUE TITLE
Origins compatability [SUGGESTION]

### ISSUE THREAD

**Issue by Seaparty** [MeteorDevelopment/meteor-client#824]
I would like to be able to use this utility mod on servers that have origins mod

**Screenshots**
![image](https://user-images.githubusercontent.com/83017749/119277789-99645780-bbef-11eb-9b1b-99a37fe87c2d.png)
![image](https://user-images.githubusercontent.com/83017749/119277808-bb5dda00-bbef-11eb-927c-56bf838caa48.png)

**Additional info**
i have no clue if this is impossible, but thanks.

**Comment by Cypphi** [comment]
i dont see the point in having support for origins.And why tf do you even wanna hack on it.

**Comment by Seaparty** [comment]
> i dont see the point in having support for origins.And why tf do you even wanna hack on it.

I think having support for origins would be good because its a popular smp mod.  As for why, because im in a origins smp and would like to keep dedication to meteor, as it is an amazing client
