### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Axende** [MeteorDevelopment/meteor-client#829]
**Describe the feature**
Remove the M next to your name when using meteor client I've been nearly caught 3 times cheating cause of it and happily obliged to get off of it the meteor client's M makes staff has their job easier because of this

**Screenshots**
I don't have any

**Additional info**
None

**Comment by StormyBytes** [comment]
why are you using meteor in servers where it isnt permitted

**Comment by StormyBytes** [comment]
What M?

**Comment by RedCarlos26** [comment]
There is already an option for that. Go into the config tab and uncheck send data to API. The M will not appear for you and other players. @Axende

**Comment by a-couple-objects** [comment]
don't use utility mod on servers that'll ban for it ez
