### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by KriszAbyss** [MeteorDevelopment/meteor-client#834]
**Describe the feature**
A clear and concise description of what feature/change is.
Strafe Hacks
**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.
Its basicly strafing mid air,lots of hacked clients have it and i think meteor is perfect but its missing strafe
**Additional info**
Add any other info.
please add it

**Comment by seasnail8169** [comment]
Its called Speed

**Comment by KriszAbyss** [comment]
but im playing on servers like 2b2t where speed it patched but hacls are allowed and it dosent work

**Comment by KriszAbyss** [comment]
hope you understand

**Comment by StormyBytes** [comment]
Speed has settings to account for anticheats

**Comment by a-couple-objects** [comment]
> but im playing on servers like 2b2t where speed it patched but hacls are allowed and it dosent work

speed is just renamed strafe, try 5.6

**Comment by seasnail8169** [comment]
> but im playing on servers like 2b2t where speed it patched but hacls are allowed and it dosent work

Strafe is not patched on 2b, speed around 1.6 works pretty much flawlessly
