### ISSUE TITLE
[Bug] Weird Nametag render

### ISSUE THREAD

**Issue by supakeks** [MeteorDevelopment/meteor-client#837]
**Describe the bug**
Nametags render weirdly and the background only renders 1 half of it

**To Reproduce**
1. Use logout spots or nametags

**Expected behavior**
Background has to be same height/width as text

**Screenshots**
![image](https://user-images.githubusercontent.com/70498670/119531640-1f98af00-bd52-11eb-93c6-abab7f922bcf.png)

**Additional context**
Minecraft 1.16.5
Custom meteor by seasnail with some other changes (should be around dev build 890)
Other mods I'm using: 
- Fabric api
- Lithium
- Meteor+
- MountBypassDupe addon
- multiconnect
- phosphor
- sodium

Notes: I'm on an iMac, 5k display, 27-inch

**Comment by necrophili** [comment]
Mac enjoyer 😎

**Comment by RedCarlos26** [comment]
U are lucky meteor + seems so based lol

**Comment by supakeks** [comment]
bruh
