### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by GzuzMC** [MeteorDevelopment/meteor-client#839]
**Supports Optifine**
Some people do not need OptiFabric.  But some low-end pc such as mine needs OptiFabric/Optifine to run minecraft more smoother and not like a Slideshow.

**PC Specs**
No Graphics Card
AMD A4-5300 APU with Radeon(TM) HD Graphics

**Comment by StormyBytes** [comment]
sodium

**Comment by StormyBytes** [comment]
close this @GzuzMC . optifine will not be supported by meteor. use sodium, phosphor and lithium instead.
