### ISSUE TITLE
[Bug] Crash when using AutoMountBypassDupe addons

### ISSUE THREAD

**Issue by Rabkaleta** [MeteorDevelopment/meteor-client#842]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/27/21 2:10 AM
Description: Unexpected error

java.lang.NoSuchMethodError: minegame159.meteorclient.utils.player.InvUtils.clickSlot(IILnet/minecraft/class_1713;)V
	at meteordevelopment.addons.mountbypassdupe.AutoMountBypassDupe.onTick(AutoMountBypassDupe.java:178)
	at meteordevelopment.addons.mountbypassdupe.AutoMountBypassDupe$$Lambda$4814/70113816.accept(Unknown Source)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:85)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:27)
	at net.minecraft.class_310.handler$zjh002$onTick(class_310.java:8920)
	at net.minecraft.class_310.method_1574(class_310.java:1612)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at meteordevelopment.addons.mountbypassdupe.AutoMountBypassDupe.onTick(AutoMountBypassDupe.java:178)
	at meteordevelopment.addons.mountbypassdupe.AutoMountBypassDupe$$Lambda$4814/70113816.accept(Unknown Source)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:85)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:27)
	at net.minecraft.class_310.handler$zjh002$onTick(class_310.java:8920)

-- Affected level --
Details:
	All players: 1 total; [class_746['QGore'/16037, l='ClientLevel', x=801.84, y=83.90, z=-276.44]]
	Chunk stats: SodiumChunkCache: 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,72,48), Chunk: (at 0,4,0 in -14,3; contains blocks -224,0,48 to -209,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 477114 game time, 210421 day time
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1278576792 bytes (1219 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.6.3
		bookdupe-addon: Meteor Book Dupe Addon 0.1.2
		fabric: Fabric API 0.34.6+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		java: Java HotSpot(TM) 64-Bit Server VM 8
		meteor-client: Meteor Client 0.4.3-905
		meteor-mbd-addon: Meteor Mount Bypass Dupe Addon 0.1.2
		minecraft: Minecraft 1.16.5
		multiconnect: MultiConnect 1.3.36
		multiconnect-api: MultiConnect API 1.3.36
		sodium: Sodium 0.1.0
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4531, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, file/1.16x_Yakpack_v3.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

-- Meteor Client --
Version: 0.4.3
Dev Build: 905

[Combat]:
Criticals (criticals)

[Player]:
Anti Hunger (anti-hunger)
Auto Respawn (auto-respawn)
Death Position (death-position)
No Break Delay (no-break-delay)
Portals (portals)
Reach (reach)
Speed Mine (speed-mine)

[Movement]:
Elytra Fly (elytra-fly)
Entity Speed (entity-speed)
No Fall (no-fall)
No Slow (no-slow)
Sprint (sprint)
Velocity (velocity)

[Render]:
Better Tooltips (better-tooltips)
Break Indicators (break-indicators)
Camera Clip (camera-clip)
Chams (chams)
Fullbright (fullbright)
HUD (HUD)
Hand View (hand-view)
Hole Esp (hole-esp)
Nametags (nametags)
No Render (no-render)
Search (search)
Storage Esp (storage-esp)
Tracers (tracers)
Unfocused Cpu (unfocused-cpu)
Waypoints (waypoints)

[World]:
Enderman Look (enderman-look)

[Misc]:
Anti Packet Kick (anti-packet-kick)
Auto Mount Bypass Dupe (auto-mount-bypass-dupe)
Auto Reconnect (auto-reconnect)
Middle Click Friend (middle-click-friend)
Notifier (notifier)
Vanilla Spoof (vanilla-spoof)

**Comment by Rabkaleta** [comment]
i use dev build

**Comment by IIpho3nix** [comment]
stop

**Comment by IIpho3nix** [comment]
your old issue is already closed

**Comment by IIpho3nix** [comment]
it wont be fixed

**Comment by Rabkaleta** [comment]
uhhh, ok thx, sorry for disturb you :|
