### ISSUE TITLE
[Bug] Blocks moving bug (baritone)

### ISSUE THREAD

**Issue by Texbio** [MeteorDevelopment/meteor-client#843]
**Describe the bug**
-A random block will move to your hotbar for no reason and if your hotbar is full it will replace it.

**To Reproduce**
change allowInventory to true in baritone's config.

**Expected behavior**
not this

**Additional context**
Fixed this 'bug' by changing:
allowInventory true
to 
allowInventory false.
Apparently this is the cause of the issue that I spent a while on :(

I do not know if this is intended but this makes no sense for this to be a feature to always give you blocks.

**Comment by MineGame159** [comment]
You know this is caused by baritone but still reported it here

**Comment by Texbio** [comment]
I assumed it was a compatibility issue that meteor caused since I have never seen this bug. I should have closed it myself but was trying to get a vod of the bug.

https://user-images.githubusercontent.com/36513888/119725144-1ea17380-be5f-11eb-9274-d0057f81b72e.mp4
