### ISSUE TITLE
vclip doesn't work when trying to get on top of nether roof[Bug]

### ISSUE THREAD

**Issue by GimJules** [MeteorDevelopment/meteor-client#849]
When using at nether roof I will say the player has drowned when they move or disable flight.

1. Go to nether bedrock roof on multiplayer
2. Use .vclip 3 at y 125
3. Move in any direction or disable flight
4. Die of drowning?

**Expected behavior**
When I do it on a multiplayer server I die instantly but not on single player

Screenshots not available at this time

Meteor version: 4.3-849 Game Version: 1.16.4 Other mods:
![mods](https://user-images.githubusercontent.com/62084135/119769387-3b45a780-be6f-11eb-94af-83acd99c70ed.png)

(this may just be this specific server but I was told that nothing was patched/disabled)

**Comment by seasnail8169** [comment]
That means the server has patched the nether roof.

**Comment by GimJules** [comment]
yea the mods lied to me and said it wasn't patched when it actually was sorry for bothering
