### ISSUE TITLE
[Suggestion] Offhand + auto totem

### ISSUE THREAD

**Issue by GodsonGamerGr** [MeteorDevelopment/meteor-client#851]
**Describe the feature**
add an option in offhand to make it take effect after I run out of totems basically like a back up, say I ran out of totems and want to eat gapples in the mean time, add the option to do that

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by TheAlpH3x** [comment]
There is already an option for that in the Offhand module and the Auto totem Module

**Comment by RedCarlos26** [comment]
@GodsonGamerGr ^^
