### ISSUE TITLE
[Suggestion] add stuff to no interact 

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#855]
make no interact block setting spawn and add the possibility to choose what interactions to block

**Comment by seasnail8169** [comment]
"no interact block setting spawn" what?

**Comment by RoastedCheese** [comment]
> "no interact block setting spawn" what?
I mean that it should block interactions with beds and anchors

**Comment by DesiCow** [comment]
I think NoInteract has these features now.
