### ISSUE TITLE
[Bug] modules that equip items

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-client#856]
When using modules that equip items such as offhand, autototem and chest swap they often reove the items from your inventory and place them in your "mouse slot". 
Therefore, when you try to use those items you need to open the inventory and place them back in it, also they get dropped when you disconnect or change dimension.

**Comment by RedCarlos26** [comment]
I can confirm. Pretty annoying bug.

**Comment by StormyBytes** [comment]
Can confirm, happened so many times with chest swap (elytra fly also uses this) and has been the main reason i lose my elytras.

**Comment by necrophili** [comment]
I think BH might’ve found a way around this... I’m not sure tho

**Comment by RedCarlos26** [comment]
It is still happening 💀

**Comment by seasnail8169** [comment]
does anyone know if this still happens?

**Comment by StormyBytes** [comment]
tbh this issue sounds more like a lag issue

**Comment by seasnail8169** [comment]
gonna close it unless someone sends a video on latest dev ig
