### ISSUE TITLE
"Error Failed to read skin url." when trying to add another account

### ISSUE THREAD

**Issue by nikisalli** [MeteorDevelopment/meteor-client#862]
When trying to add a cracked account with the "accounts" tab in the multiplayer world menu it fails and the following error shows up in the logs:

```[15:07:26] [pool-4-thread-1/ERROR]: Failed to read skin url. (https://crafatar.com/avatars/b3e18b546202480a9c5165834d1fad2a?size=8&overlay&default=MHF_Steve)```

**To Reproduce**
1. Go to the "accounts" tab in multiplayer world selector
2. try to add a cracked account named "nikbot"
3. get error in the logs

it works with other random account names I tried

**Additional context**
minecraft version: 1.16.4 with fabric
meteor version: 0.4.3

**Comment by MineGame159** [comment]
Fixed in aee8b7140f7e712fba62641151e38437c0c1f55e.
