### ISSUE TITLE
[Bug] Cant add a acount (Premium acount)

### ISSUE THREAD

**Issue by DrDuggi** [MeteorDevelopment/meteor-client#864]
**Describe the bug**
I cant Add Acount

**To Reproduce**

**Expected behavior**
Theat it add it to my list But its just making nothing if i click the add button

**Screenshots**
I cant because i dont want theat someone log into my alt acount.

**Additional context**
(meteor version: 0.4.3, minecraft version: 1.16, Mods: Dynamic Music,Sodium,Xaero's World Map
![Screenshot 2021-05-28 163918](https://user-images.githubusercontent.com/62102560/120000600-4580b680-bfd3-11eb-8a6b-22527dceb699.png)

**Comment by DrDuggi** [comment]
Pleas Help me, idk if i have a virus i tryt it without mods just meteor and it doesnt work! Pleas Help!

**Comment by MineGame159** [comment]
Should be fixed in aee8b7140f7e712fba62641151e38437c0c1f55e.
