### ISSUE TITLE
optifabric not working with meteor

### ISSUE THREAD

**Issue by xZpolt** [MeteorDevelopment/meteor-client#866]
optifabric doesn't work with meteor, please fix this as i need optfine for better fps.

**Comment by supakeks** [comment]
No, use sodium

**Comment by xZpolt** [comment]
isn't as good as optfine.

**Comment by Wide-Cat** [comment]
Optifine is a legacy mod that makes sweeping changes to the minecraft code, causing mass incompatibilities with other mods. Optifine will never be made compatible with meteor, and so either use sodium, lithium and phosphor or don't use meteor.

**Comment by Makrennel** [comment]
> 
> 
> isn't as good as optfine.

It isn't as good.

It's better.

**Comment by nemyxo** [comment]
**on optifine, i get 60+ fps, on sodium i get 15 fps. chunk loading is screwed.**. intel i3 3110m, ihd 4000, 8 gb ram.. windows 10

**Comment by KavinKishore123** [comment]
Sodium is known for having issues with old intel gpu's on windows. You either have to switch to a linux distro or maybe use a different hacked client

**Comment by Skog-pog** [comment]
> > isn't as good as optfine.
> 
> It isn't as good.
> 
> It's better.

does sodium have alternate textures for blocks and mobs in different biomes?

idk why am i replying so late

**Comment by arlomcwalter** [comment]
> > > isn't as good as optfine.
> 
> > 
> 
> > It isn't as good.
> 
> > 
> 
> > It's better.
> 
> 
> 
> does sodium have alternate textures for blocks and mobs in different biomes?
> 
> 
> 
> idk why am i replying so late

Sodium focuses on the optimisation aspect of optifine, but there are many mods which aim to recreate other optifine features (like the one you mentioned). This way users can select the features they want without the mess of optifine.
