### ISSUE TITLE
[Bug] As of dev build 912, the game crashes when you click the 'guide' button in the swarm module

### ISSUE THREAD

**Issue by Wide-Cat** [MeteorDevelopment/meteor-client#867]
**Describe the bug**
As of dev build #912, when you click the 'guide' button in the swarm module, the game instantly crashes.

**Crash Report**
https://paste.ee/p/3uONj

**Comment by seasnail8169** [comment]
ugh

**Comment by seasnail8169** [comment]
not mtreo issue

**Comment by Wide-Cat** [comment]
rip
