### ISSUE TITLE
[Suggestion] Illuminate

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#868]
**Describe the feature**
Places torches or any other block that emits light to spawn-proof an area. It could take advntage of the Light Overlay code to find the best placement.

Would be better if it had settings like:
- a filter list for blocks to use
- the ability to place blocks always or only in a specified zone
- whether to place the light sources on walls or floors only

**Additional info**
Could be added to the World category. Useful to spawn-proof big areas, such as those around mob farms.

**Comment by Fyriii** [comment]
I think this is a good idea but if this gets refused you could try the auto torch mod for fabric. I don't think it has all the features you want and IDK how effective it is but it could be useful.

**Comment by StormyBytes** [comment]
Similar to #719
