### ISSUE TITLE
Trap-City [Suggestion]

### ISSUE THREAD

**Issue by Tokara1** [MeteorDevelopment/meteor-client#870]
**Describe the feature**
My suggestion is a additional setting to auto city (or a new module] that automatically breaks a Selftrap block of enemies to be able to use Anchor or Bed Aura on them without having to use freecam for breaking the blox.
 
[ pretty self explaining i hope its understandable what i mean]

**Screenshots**
N/A

**Additional info**
N/A

**Comment by RoastedCheese** [comment]
Nah

**Comment by Fyriii** [comment]
This is definitely a good idea. Would definitely make bed/anchor pvp easier

**Comment by seasnail8169** [comment]
Auto trap + auto city

**Comment by Tokara1** [comment]
Wdym seasnale
