### ISSUE TITLE
EntitySpawnS2C packet is missing from packet canceller in dev builds

### ISSUE THREAD

**Issue by TheRedHippo** [MeteorDevelopment/meteor-client#871]
**Describe the bug**
EntitySpawnS2C packet is missing from packet canceller in dev builds

**To Reproduce**
1. Open packet canceller menu
2. Search EntitySpawn
3. Observe how its missing

**Expected behavior**
EntitySpawnS2C packet shows up like in previous versions

**Additional context**
Using the most recent dev build

**Comment by supakeks** [comment]
Its not that packet, its any packet you add.

When relaunching your game any packet that was added just disappears

**Comment by TheRedHippo** [comment]
wdym add it? I haven't selected it.

**Comment by TheRedHippo** [comment]
Nevermind, I see what you mean. This needs to be fixed

**Comment by MineGame159** [comment]
Fixed in 4ba4130ed0bd0f0cf3809e51e2feda4464441167
