### ISSUE TITLE
[Suggestion] Add the ominous/illager banners to Search module

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [MeteorDevelopment/meteor-client#878]
**Describe the feature**
As the title says. These two banners are currently missing from the searcheable block list.

**Screenshots**
![2021-05-30 14_05_43-Window](https://user-images.githubusercontent.com/52252627/120103500-28bdbd80-c150-11eb-823c-b583ce3bd99b.png)

**Additional info**
Could be mising in other modules' selction, didn't check myeslf tho.

**Comment by MineGame159** [comment]
Those two banners are not separate blocks and thus search cannot differentiate between them. They are just normal banners with patterns.
