### ISSUE TITLE
[Suggestion] notification to visual range in notifier

### ISSUE THREAD

**Issue by RoastedCheese** [MeteorDevelopment/meteor-client#882]
add a sound notification to visual range (and possibly to entity logger if #881 gets added) and the possibility to choose the type of notification (chat and popup ) and the type of sound (bow notification and none)

**Comment by seasnail8169** [comment]
literally just #759

**Comment by seasnail8169** [comment]
wait no

**Comment by seasnail8169** [comment]
#688
