### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kaantayus** [MeteorDevelopment/meteor-client#887]
**Describe the bug**
While using freecam you cannot move down if your sneak key is bound to a mouse button. Instead, the Minecraft player will just sneak instead of the freecam moving down

**To Reproduce**
Bind your Minecraft sneak button to a mouse button (Button 5 is my one)
Go in-game and turn on Freecam
Press sneak and watch your MC player sneak instead of Freecam moving down

**Comment by RoastedCheese** [comment]
BRUH

**Comment by C10udburst** [comment]
Fixed in 7f5f1761413ed3db48072f5b244e78f6d6560002

**Comment by Kaantayus** [comment]
> When is someone ever going to bind sneak to a mouse button lol

me :)
