### ISSUE TITLE
game crashes randomly[Bug]

### ISSUE THREAD

**Issue by McBirbz** [MeteorDevelopment/meteor-client#888]
[crash-2021-05-31_13.40.33-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/6572432/crash-2021-05-31_13.40.33-client.txt)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by McBirbz** [comment]
also with latest dev build

**Comment by seasnail8169** [comment]
99% sure this is a multiconnect issue

**Comment by McBirbz** [comment]
Alright, I'll try without mutliconnect.

**Comment by MineGame159** [comment]
Multiconnect bug.
