### ISSUE TITLE
[Suggestion] Addition to .enchant

### ISSUE THREAD

**Issue by Z3r0ut** [MeteorDevelopment/meteor-client#896]
**Describe the feature**
Exclude enchantments from .enchant all/all_possible

**Additional info**
For example i dont want if i do .enchant all_possible 32000 that looting 32000 gets added. Thats just dumb. So for example like .enchant all_possible 32000  e looting , vanishing_curse That should exclude looting and vanishing curse from getting added

**Comment by seasnail8169** [comment]
just do `.enchant one <enchant> 32000`, all_possible is only there for convenience and it makes no sense to have more modifiers from that.
