### ISSUE TITLE
[Bug] HoleESP double bug

### ISSUE THREAD

**Issue by supakeks** [MeteorDevelopment/meteor-client#898]
**Describe the bug**
Double holes render a really small line (barely visible) in between double holes

**To Reproduce**
1. Turn on HoleESP and have the "double" setting turned on
2. See error

**Expected behavior**
No line should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/70498670/120358151-31d79780-c2d4-11eb-8a37-148b7311e4c9.png)

**Additional context**
Mods i'm using
- Sodium
- Phosphor
- Lithium
- Meteor+
- MountBypassDupe addon
- FabricAPI
- Multiconnect

I'm on a mac

**Comment by seasnail8169** [comment]
you issue

**Comment by supakeks** [comment]
BRUH

**Comment by Kiriyaga05** [comment]
coronaclient are op
