### ISSUE TITLE
Auto wither

### ISSUE THREAD

**Issue by GoodNightTea** [MeteorDevelopment/meteor-client#903]
**Describe the feature**
So how it should work: you turn on auto wither and it places soul sand at the form you make the wither and also places the wither skulls

**Screenshots**
i dont think it is in any other client

**Additional info**
it would be good for griefing or just annoy everyone with the spawn sound ;D

**Comment by GildedS** [comment]
Already in the works

**Comment by seasnail8169** [comment]
#516

**Comment by Dream23322** [comment]
> 
> **Screenshots** i dont think it is in any other client
> 
It's in lambda client but its called auto spawner
