### ISSUE TITLE
[Bug] Middle click in GUI creative mode

### ISSUE THREAD

**Issue by Rabkaleta** [MeteorDevelopment/meteor-client#912]
**Middle click in GUI creative mode**

middle click in gui not copy item in inven, but copy at crosshair

p.s. my eng bad, sorry

**Comment by MineGame159** [comment]
I have no idea what you mean.

**Comment by StormyBytes** [comment]
Can confirm. Middle click doesn't copy items in creative mode. Instead it copies the block the player is targeting/looking at

**Comment by StormyBytes** [comment]
Fixed in 79e78d04e3ed41158c2ae49ccd67c61ba871caec
