### ISSUE TITLE
[Suggestion] I want a feature/module to mob proof an area.

### ISSUE THREAD

**Issue by NIGHTMARIO** [MeteorDevelopment/meteor-client#916]
**Describe the feature**
I want a module to automatically put torches, slabs, or carpets on the top of blocks in a specific area if the user is holding the items.

**Screenshots**
I have no screenshots of it. I just came up with this idea now and I don't know any other mods implementing this feature.

**Additional info**
If you implement this feature in meteor, I want it so that it will take the data from the "Light Overlay" module and then place torches instead of placing torches everywhere. But slabs and carpets are needed to be put everywhere to mob proof the area.
I also want it not to place torches, slabs, or carpets over blocks like stairs or others where it can't be placed.

**Comment by dadudeme** [comment]
already exists in #868 not necessary to repeat

**Comment by StormyBytes** [comment]
#719

**Comment by MineGame159** [comment]
Added
