### ISSUE TITLE
crystals invisible during crystal aura 

### ISSUE THREAD

**Issue by poor69420** [MeteorDevelopment/meteor-client#922]
when i use my  op crystal aura config there are no crystals just ca render on block and does damage

1. have fast ca config
2. use it only tested on meteor pvp
3. watch it do damage but no crystals show up

a crystal to be renderd and then removed once it has been broken 

https://medal.tv/clips/54318792/d1337ToWGMgi a clip of the issue

Add any other context (meteor version, minecraft version, other mods you are using, etc).
0.4.3, 1.16.4, fabric api and sodium

**Comment by MineGame159** [comment]
Update to dev builds
