### ISSUE TITLE
Auto totem for offhand extra or ca 

### ISSUE THREAD

**Issue by user1000607** [MeteorDevelopment/meteor-client#941]
Im playing on an anarchy server and we cpvp on there. It is very helpful that o can offhand the crystals but due to high ping and some lags my auto totem doesn’t switch to the totem so I came up with the idea of adding a Auto totem function to the offhand extra mod so if you are low or about to die the mod gives you a totem. Pretty much the same as Auto totem but just that you can use the offhand for other items

**Comment by seasnail8169** [comment]
just use them at the same time lol, set auto totem to smart mode and you can use offhand until auto totem min health is reached
