### ISSUE TITLE
[Bug] Nuker causes NullPointer exceptions and error code 0 exits

### ISSUE THREAD

**Issue by D3V1LC0D3R** [MeteorDevelopment/meteor-client#945]
**Describe the bug**
The nuker module sometimes crashes meteor
**To Reproduce**
1. get the best gear possible (netterite + effi 5)
2. nuke with maximum reach and maximum speed
3. (maybe it has something to do with a serverside lagspike or a desync)

**Expected behavior**
the nuker is fault tolerant and accepts if blocks were not mined or whatever is causing the issue is not there
**Screenshots**

**Additional context**

> ```---- Minecraft Crash Report ----
> // This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
> 
> Time: 6/5/21 9:41 PM
> Description: Ticking entity
> 
> java.lang.NullPointerException: Ticking entity
> 	at net.minecraft.class_761.method_22987(class_761.java:1781)
> 	at net.minecraft.class_761.method_8569(class_761.java:2930)
> 	at net.minecraft.class_638.method_8517(class_638.java:570)
> 	at net.minecraft.class_636.method_2910(class_636.java:172)
> 	at minegame159.meteorclient.systems.modules.world.Nuker.cancelMine(Nuker.java:235)
> 	at minegame159.meteorclient.systems.modules.world.Nuker.lambda$onTick$1(Nuker.java:202)
> 	at minegame159.meteorclient.utils.player.Rotations$Rotation.runCallback(Rotations.java:232)
> 	at minegame159.meteorclient.utils.player.Rotations.onSendMovementPacketsPost(Rotations.java:119)
> 	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:85)
> 	at meteordevelopment.orbit.EventBus.post(EventBus.java:27)
> 	at net.minecraft.class_746.handler$zmh000$onSendMovementPacketsTail(class_746.java:3329)
> 	at net.minecraft.class_746.method_3136(class_746.java:290)
> 	at net.minecraft.class_746.method_5773(class_746.java:215)
> 	at net.minecraft.class_638.method_18646(class_638.java:193)
> 	at net.minecraft.class_1937.method_18472(class_1937.java:561)
> 	at net.minecraft.class_638.method_18116(class_638.java:164)
> 	at net.minecraft.class_310.method_1574(class_310.java:1556)
> 	at net.minecraft.class_310.method_1523(class_310.java:1021)
> 	at net.minecraft.class_310.method_1514(class_310.java:681)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.class_761.method_22987(class_761.java:1781)
> 	at net.minecraft.class_761.method_8569(class_761.java:2930)
> 	at net.minecraft.class_638.method_8517(class_638.java:570)
> 	at net.minecraft.class_636.method_2910(class_636.java:172)
> 	at minegame159.meteorclient.systems.modules.world.Nuker.cancelMine(Nuker.java:235)
> 	at minegame159.meteorclient.systems.modules.world.Nuker.lambda$onTick$1(Nuker.java:202)
> 	at minegame159.meteorclient.utils.player.Rotations$Rotation.runCallback(Rotations.java:232)
> 	at minegame159.meteorclient.utils.player.Rotations.onSendMovementPacketsPost(Rotations.java:119)
> 	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:85)
> 	at meteordevelopment.orbit.EventBus.post(EventBus.java:27)
> 	at net.minecraft.class_746.handler$zmh000$onSendMovementPacketsTail(class_746.java:3329)
> 	at net.minecraft.class_746.method_3136(class_746.java:290)
> 	at net.minecraft.class_746.method_5773(class_746.java:215)
> 	at net.minecraft.class_638.method_18646(class_638.java:193)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft:player (net.minecraft.class_746)
> 	Entity ID: xxx
> 	Entity Name: xxx
> 	Entity's Exact location: xxx.15, 72.92, xxx.05
> 	Entity's Block location: World: (xxx,72,xxx), Chunk: (at 4,4,13 in xxx,xxx; contains blocks xxx,0,xxx to xxx,255,xxx), Region: (107,522; contains chunks xxx,xxx to xxx,xxx, blocks xxx,0,xxx to xxx,255,xxx)
> 	Entity's Momentum: 0.05, 0.00, 0.07
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> Stacktrace:
> 	at net.minecraft.class_1937.method_18472(class_1937.java:561)
> 	at net.minecraft.class_638.method_18116(class_638.java:164)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_746['xxx'/xxx, l='ClientLevel', x=xxx.15, y=72.92, z=xxx.05]]
> 	Chunk stats: Client Chunk Cache: 1024, 169
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (-192,67,225), Chunk: (at 0,4,1 in -12,14; contains blocks -192,0,224 to -177,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: xxx game time, xxx day time
> 	Server brand: xxx
> 	Server type: Non-integrated multiplayer server
> Stacktrace:
> 	at net.minecraft.class_638.method_8538(class_638.java:449)
> 	at net.minecraft.class_310.method_1587(class_310.java:2239)
> 	at net.minecraft.class_310.method_1514(class_310.java:699)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Linux (amd64) version 5.8.0-3-amd64
> 	Java Version: 1.8.0_202, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 955373608 bytes (911 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
> 	CPUs: 8
> 	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Fabric Mods: 
> 		autoconfig1u: Auto Config v1 Updated 3.3.1
> 		baritone: Baritone 1.6.3
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-config2: Cloth Config v4 4.8.2
> 		com_github_kaptainwutax_biomeutils: BiomeUtils xxx
> 		com_github_kaptainwutax_chunkrandomreversal: ChunkRandomReversal xxx
> 		com_github_kaptainwutax_featureutils: FeatureUtils xxx
> 		com_github_kaptainwutax_latticg: LattiCG xxx
> 		com_github_kaptainwutax_mathutils: MathUtils xxx
> 		com_github_kaptainwutax_seedutils: SeedUtils xxx
> 		cullleaves: Cull Leaves 2.1.0
> 		fabric: Fabric API 0.34.1+1.16
> 		fabric-api-base: Fabric API Base 0.3.0+c88702897d
> 		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
> 		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
> 		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
> 		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
> 		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
> 		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.2+d6244c6d7d
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
> 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
> 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
> 		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
> 		fabricloader: Fabric Loader 0.11.3
> 		java: Java HotSpot(TM) 64-Bit Server VM 8
> 		lambdabettergrass: LambdaBetterGrass 1.0.3+1.16
> 		litematica: Litematica 0.0.0-dev.20210120.213004
> 		lithium: Lithium 0.6.4
> 		malilib: MaLiLib 0.10.0-dev.21+arne.5
> 		meteor-client: Meteor Client 0.4.3
> 		minecraft: Minecraft 1.16.5
> 		modmenu: Mod Menu 1.16.9
> 		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
> 		seedcracker: Seed Cracker 0.2.3-beta
> 		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
> 		sodium: Sodium 0.1.1+rev.9fbf07a
> 		spruceui: SpruceUI 2.0.4+1.16
> 		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
> 		visualoverhaul: VisualOverhaul 3.1.0
> 		worldedit: WorldEdit 7.2.5+57d5ac9
> 	Launched Version: fabric-loader-0.11.3-1.16.5
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: Quadro 3000M/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.143, NVIDIA Corporation
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fancy
> 	Resource Packs: programer_art, vanilla, Fabric Mods, lambdabettergrass/default, cullleaves/smartleaves, visualoverhaul/coloredwaterbucket, visualoverhaul/fancyfurnace, visualoverhaul/nobottles
> 	Current Language: English (United Kingdom)
> 	CPU: 8x Intel(R) Core(TM) i7-2820QM CPU @ 2.30GHz
> 
> -- Meteor Client --
> Version: 0.4.3
> 
> [Combat]:
> Auto Totem (auto-totem)
> Auto Weapon (auto-weapon)
> Bow Aimbot (Bow Aimbot)
> Criticals (criticals)
> 
> [Player]:
> Anti Hunger (anti-hunger)
> Auto Eat (auto-eat)
> Auto Gap (auto-gap)
> Auto Replenish (auto-replenish)
> Auto Respawn (auto-respawn)
> Auto Tool (auto-tool)
> Portals (portals)
> XCarry (XCarry)
> 
> [Movement]:
> Anti Levitation (anti-levitation)
> Anti Void (anti-void)
> Boat Fly (boat-fly)
> Fast Climb (fast-climb)
> Flight (flight)
> Jesus (jesus)
> No Fall (no-fall)
> No Slow (no-slow)
> Velocity (velocity)
> 
> [Render]:
> Better Tooltips (better-tooltips)
> Boss Stack (boss-stack)
> Break Indicators (break-indicators)
> Entity Owner (entity-owner)
> Esp (esp)
> Fullbright (fullbright)
> HUD (HUD)
> Hand View (hand-view)
> Hole Esp (hole-esp)
> Logout Spots (logout-spots)
> Nametags (nametags)
> Search (search)
> Storage Esp (storage-esp)
> Tracers (tracers)
> Trail (trail)
> Unfocused Cpu (unfocused-cpu)
> Waypoints (waypoints)
> 
> [World]:
> Build Height (build-height)
> Enderman Look (enderman-look)
> Nuker (nuker)
> 
> [Misc]:
> Anti Packet Kick (anti-packet-kick)
> Auto Reconnect (auto-reconnect)
> Better Tab (better-tab)
> Message Aura (message-aura)
> Middle Click Friend (middle-click-friend)
> Sound Blocker (sound-blocker)
> Vanilla Spoof (vanilla-spoof)```

**Comment by seasnail8169** [comment]
#255 duplicate
