### ISSUE TITLE
GUI and HUD are very, VERY small

### ISSUE THREAD

**Issue by AstroOrbis** [MeteorDevelopment/meteor-client#95]

**Comment by AstroOrbis** [comment]
So what happens is all of the elements are scaled down, maybe a HUD editor/resizer tool?

**Comment by MineGame159** [comment]
You can scale them up. HUD in HUD settings and GUI in GUI tab at the top

**Comment by notseanyay** [comment]
based

**Comment by MineGame159** [comment]
Why did you open it again

**Comment by AstroOrbis** [comment]
but it does this
<img width="1440" alt="Screen Shot 2020-12-29 at 5 20 51 PM" src="https://user-images.githubusercontent.com/65419194/103317784-35e84c00-49fa-11eb-889a-e0ca34d976d9.png">

**Comment by AstroOrbis** [comment]
the modules just clip together

**Comment by MineGame159** [comment]
You can move them. Or go into HUD settings and click "Reset" (its written there to do it after changing scale)

**Comment by AstroOrbis** [comment]
Ok thanks
