### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by osshe5** [MeteorDevelopment/meteor-client#953]
Make it so that Insta Mine resets after a block is broken, so that after placing a new block it doesn't get broken too. Currently Insta Mine keeps itself on one block until a new block in a different position is broken.

![2021-06-06_14 58 17](https://user-images.githubusercontent.com/84791485/120927183-e1977580-c6d7-11eb-85bb-1ee2b2598c78.png)
![2021-06-06_14 58 24](https://user-images.githubusercontent.com/84791485/120927192-e8be8380-c6d7-11eb-8112-9138545cbd53.png)

**Comment by seasnail8169** [comment]
This is just how insta mine works, it couldn't work like that.

**Comment by RickyTheRacc** [comment]
Bruh it breaking whatever you put there is literally the point of insta mine
