### ISSUE TITLE
[Suggestion] Seed Manager

### ISSUE THREAD

**Issue by C10udburst** [MeteorDevelopment/meteor-client#956]
A database of seeds for each world/server. The value could be set using `.seed` (taken for example from [SeedCracker](https://github.com/KaptainWutax/SeedCracker)) and used in calculations for `.locate` and  in future maybe for slime chunk calculation or OreSim like in #537

**Comment by ThebestkillerTBK** [comment]
Use meteor rejects

**Comment by C10udburst** [comment]
> Use meteor rejects

wow thanks its not like i made it :trollface:
