### ISSUE TITLE
[Suggestion] Better Veinminer

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#958]
**Describe the feature**
Add a block whitelist so you don't accidentally start mining all the stone around you, also add a delay slider for the delay between mining blocks

**Additional info**
Deez joe dn sugondese candice

**Comment by Lovecrafts-Cat** [comment]
I like the withelist idea, happens too often that i missclick and it starts going away at the whole cave 👍

**Comment by seasnail8169** [comment]
WHY DIDN'T IT CLOSE IT 🐒
