### ISSUE TITLE
[Suggestion] Improved Potion Saver

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#959]
**Describe the feature**
Allow the user to select which effects are preserved, obviously you wouldn't want to preserve poison or wither.

**Additional info**
Close if coper

**Comment by Wide-Cat** [comment]
:trollface:

**Comment by seasnail8169** [comment]
this is so fucking cool btw

**Comment by seasnail8169** [comment]
the setting i mean (it renders the potions with the correct potion color (very cool))
