### ISSUE TITLE
[Suggestion] .rename, letting you rename items, with custom colors, like you can with aristois

### ISSUE THREAD

**Issue by tomasventura13** [MeteorDevelopment/meteor-client#961]
**Describe the feature**
A clear and concise description of what feature/change is.

**Screenshots**
If applicable, add screenshots or examples to help demonstrate what you mean.

**Additional info**
Add any other info.

**Comment by Wide-Cat** [comment]
you can do this with the .nbt command, for example `.nbt set {display:{Name:'[{"text":"custom name","italic":false}]'}}` *should* work
