### ISSUE TITLE
[Bug] Elytra Fly is scuffed

### ISSUE THREAD

**Issue by DrDuggi** [MeteorDevelopment/meteor-client#964]
**Describe the bug**
I cant Do elytra fly because its stops right away.

**To Reproduce**
1. Go to 'Movment'
2. Click on 'Elytra Fly'
3. Try To Fly
4. See The Error

**Expected behavior**
Its stay in flight
**Screenshots**
![image](https://user-images.githubusercontent.com/62102560/120939697-7ec6ce00-c719-11eb-9247-102e917a285c.png)

**Additional context**
MC : 1.16.5 METEOR :  0.4.4 (The new update)

**Comment by Wide-Cat** [comment]
what server? It might be a config issue, or they might have just patched it

**Comment by DrDuggi** [comment]
> what server? It might be a config issue, or they might have just patched it

1b1t.org

**Comment by seasnail8169** [comment]
Its a mistake i made with nofall, open your nofall settings and set min height to 1
