### ISSUE TITLE
[Bug] Camera tweaks scroll problems

### ISSUE THREAD

**Issue by pintoso** [MeteorDevelopment/meteor-client#967]
**Describe the bug**
->The current scroll direction doesn't make sense... you scroll backwards, but the camera goes forward
->Scroll should be key+scroll and not just scroll, because that makes zoom mods(and anything that uses scroll) useless in third person

**To Reproduce**
1. enable Camera tweaks
2. F5
3. scroll
----------
1. enable Camera tweaks
2. install any zoom mod
3. F5
4. zoom
5. scroll

**Expected behavior**
🤡🤡🤡

**Comment by MineGame159** [comment]
Fixed in a95be82bcb0de43dbd24b89971b8bb382d8c882a
