### ISSUE TITLE
[Suggestion] Improvement of "Fake Player" module.

### ISSUE THREAD

**Issue by NIGHTMARIO** [MeteorDevelopment/meteor-client#968]
**Describe the feature**
I want the fake player module to be improved. Currently, it only spawns a fake player that is invincible. I want the fake player to be in survival so that we can test other modules like "Crystal Aura", "Anchor Aura", etc on the fake player in the single-player worlds rather than going to a multiplayer server and trying it out.

**Comment by supakeks** [comment]
What? Fakeplayer works in both single player and multiplayer...

**Comment by NIGHTMARIO** [comment]
Yes, it works, I just wanted to spawn the fake player in survival game mode so that we can try out modules like "Crystal Aura" on the fake player rather than trying it out on another player in an mp server.

**Comment by seasnail8169** [comment]
You can, this is not a bug or improvement it litteraly exists

**Comment by a-couple-objects** [comment]
they want the fake player to take damage
