### ISSUE TITLE
[Bug] Flight module bug.

### ISSUE THREAD

**Issue by NIGHTMARIO** [MeteorDevelopment/meteor-client#969]
**Describe the bug**
A bug in the flight module. After reproducing the bug you can fly like in creative by double-tapping the space bar even while being in survival. Only tried in singleplayer, not tried in multiplayer.

**To Reproduce**
1. Go to the flight module.
2. Change the mode to abilities.
3. And try to fly
4. Go again to the flight module and change mode to packet.
5. Try to fly again.
6. Disable flight module.
7. You can still fly in survival with flight disabled.

**Expected behavior**
I should fall due to the flight being disabled.

**Screenshots**
Enabled modules:
![image](https://user-images.githubusercontent.com/84377831/120966412-ec104880-c785-11eb-8b8c-e6576df100b6.png)

**Additional context**
Minecraft version: 1.16.5
Meteor version: 0.4.4

**Comment by RedCarlos26** [comment]
I cannot reproduce

**Comment by Wide-Cat** [comment]
i was able to reproduce this
