### ISSUE TITLE
[Bug] Elytra+ near unusable in latest update

### ISSUE THREAD

**Issue by supakeks** [MeteorDevelopment/meteor-client#973]
**Describe the bug**
Something messed up with elytra fly and launching your elytra is near impossible on most servers and you just get tp'd back to the floor or get kicked for flying. This happens no matter your config and no matter if you have NoFall on or off

**To Reproduce**
1. Toggle on elytra+
2. Try to launch your elytra
3. See error.

This didn't happen a few dev builds back. (last time I tested was a dev build from May 19)

**Comment by RedCarlos26** [comment]
This happens when you have no fall enabled. The issue here is compatibility between elytra fly and no fall

**Comment by RedCarlos26** [comment]
@arlomcwalter we should better do an bug report that explains that no fall breaks l'entêta fly I tease of this one because elytra fly is not the issue here. It's no fall that breaks it
