### ISSUE TITLE
[Suggestion] Insta Farmer

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#977]
**Describe the feature**
Add an option to echest farmer that uses insta mine to farm obsidian, this would be much faster on servers that allow it.

**Comment by Tokara1** [comment]
Good idea, you could until it maybe is added use surround in echest Mode and Just insta mine your surround

**Comment by MineGame159** [comment]
You can just enable EChest Farmer and Insta Mine at the same time

**Comment by RickyTheRacc** [comment]
True

**Comment by Tokara1** [comment]
> You can just enable EChest Farmer and Insta Mine at the same time

For me that didnt work last time i tried but that was a bit ago already
