### ISSUE TITLE
[Bug] Totem pop notifier crashes game when non player entity pops totems

### ISSUE THREAD

**Issue by SonyTV-Bryson** [MeteorDevelopment/meteor-client#979]
**To Reproduce**
1. Enable totem pop notifier
2. Give a non player entity a totem and pop them (e.g. fox, zombie, husk)
3. Game crashes

**Expected behavior**
Game to not crash

**Comment by supakeks** [comment]
Famous pvper sonytv bryson has left a bug report for meteor developers 😳

**Comment by seasnail8169** [comment]
this is not a pull request

**Comment by supakeks** [comment]
> this is not a pull request

lmao what a monkey

**Comment by SonyTV-Bryson** [comment]
> > this is not a pull request
> 
> lmao what a monkey

twas a slip of the tongue

**Comment by seasnail8169** [comment]
> > > this is not a pull request
> 
> > 
> 
> > lmao what a monkey
> 
> 
> 
> twas a slip of the tongue

:trollface:
