### ISSUE TITLE
[Bug] Rotations hold even when set to 0

### ISSUE THREAD

**Issue by BobIsMyManager** [MeteorDevelopment/meteor-client#983]
**Describe the bug**
Killaura still holds rotations even when set to 0

**To Reproduce**
1. set hold rotation ticks to 0
2. enable killaura
3. walk up to a targeted entity
4. walk away and watch that it still holds rotations
**Expected behavior**
It should snap back as soon as the entity is gone/out of range

**Screenshots**
![2021-06-07_19 14 37](https://user-images.githubusercontent.com/70704875/121069486-7330e100-c7c5-11eb-8579-7bedff43c71c.png)
Video: https://kurwa.club/u/Bxdya.mp4

**Additional context**
Meteor 0.4.4, minecraft 1.16.5, fabric 0.11.3, no other mods loaded

**Comment by supakeks** [comment]
BEcause your rotation mode is set to Always, set it to onhit

**Comment by seasnail8169** [comment]
wait

**Comment by seasnail8169** [comment]
@BobIsMyManager do you mean really briefly?

**Comment by BobIsMyManager** [comment]
> @BobIsMyManager do you mean really briefly?

yes

**Comment by BobIsMyManager** [comment]
ill try record killing the zombie to make it clearer

**Comment by BobIsMyManager** [comment]
https://kurwa.club/u/NeTpc.mp4

**Comment by MineGame159** [comment]
Based on the video you sent I don't see whats wrong

**Comment by BobIsMyManager** [comment]
Did you watch the video just above your comment?

**Comment by MineGame159** [comment]
Yes

**Comment by BobIsMyManager** [comment]
Well what I’m saying is that your head should snap back as soon as the entity dies instead of it waiting a bit since the rotation hold ticks are set to zero
