### ISSUE TITLE
Many Suggestions [Suggestion]

### ISSUE THREAD

**Issue by FeeNiiX** [MeteorDevelopment/meteor-client#990]
### Reset buttons

- Add a button to reset a module **settings** entirely _(good so people dont need to click in every single litte reset button at a time to finally reset everything)_
- Add a button to reset all modules settings at once _(that first suggestion but faster)_
- Add a button to reset everything and only the modules _(good so people dont need to close the game and delete the files to finally reset everything, it take ages)_

### Binds

- Add so people can bind to load profiles _(useful for when i need to load a cpvp profile because i was using a profile with diferents bind to play casually)_
- Add so people can have multiple binds to toggle modules
- Add so can people bind to toggle/change an module setting _(like in wurst)(good for changing elytra fly speed without going all the way to the elytra fly module settings)_

### Other

- Add so you can snap hud things into places like: top, bottom, top left, right (good for perfectionists)
- Add so you can see what modules or something from the client is taking fps away or causing fps drops (good so you can see what to disable to get more fps)

### Combat

- Add Cev Breaker
- Add Piston Crystal Aura
- Make Crystal Aura break crystals faster ( ͡° ͜ʖ ͡°)
- Make so you can toggle to when you are eating chorus or drinking potions it doesn't eat the egap when auto gap is on (good for when people are trapped in obsidian (cpvp) and someone is putting crystals on their feet, so they can just eat the chorus fruit already and leave without the auto gap interrupting)

### Special
This is an ideia that i invented, its really simple

- Make a feature that build a new hole automatically to get closer to an enemy (why not leave and use surround?) because the enemy can place crystals before the surround and it wouldn't work (why not build yourself?) because its slow and sometimes it can mess up missclick and fill the hole instead

**End**
Hope you guys liked these suggestions, i really hope some is added
If you don't understand one or another, i can explain better, just tell me

**Comment by Tokara1** [comment]
Cev breaker is Surround mine right?
Bc hat’s already in the client

**Comment by FeeNiiX** [comment]
> Cev breaker is Surround mine right?
> Bc hat’s already in the client

Cev breaker is when you put a obsidian on the top of the player in a full bedrock surround, place a crystal on that obsidian, break the obsidian and then the crystal, and it deals a lot of damage if that player isn't coming out of the hole.
If it is already in the client i didn't know, never heard of that hat module

**Comment by TheRedHippo** [comment]
Pretty sure you can bind profiles using macros.

**Comment by Tokara1** [comment]
Not yet i think
