### ISSUE TITLE
Exp Thrower[Bug]

### ISSUE THREAD

**Issue by FeeNiiX** [MeteorDevelopment/meteor-client#992]
**When you activate it start fixing the armor with mending throwing xp bottles at but it stop when just one piece of the armor is totally fixed even having all the four pieces, and the other pieces remain a bit unfixed**

**To Reproduce**
1. Get all the four pieces of armour (any)
2. Get a lot of Bottle o' Enchanting
3. Enchant **armour** with mending
4. Damage the armour
5. Activate Exp Thrower module
6. See that only one piece of the armour is totally fixed

**Expected behavior**
Fix every single piece of the armour 100%

If this should happen i didn't know, but it fixed all pieces 100% in the 0.4.3 version of the client

**Comment by supakeks** [comment]
Can confirm this also happens with dev build 1006
