### ISSUE TITLE
[Bug] Dev build #1007 crashes upon attempt of opening ClickGUI

### ISSUE THREAD

**Issue by JackRedstonia** [MeteorDevelopment/meteor-client#993]
**Describe the bug**
Dev build #1007 for 1.17 crashes upon opening the click GUI by hitting Right Shift.

**To Reproduce**
1. Go to any single/multiplayer world
3. Hit whatever shortcut opens your click GUI
4. Voila, it crashes! Here's my logs: https://paste.ee/p/3T5FL

**Expected behavior**
The click GUI opens.

**Screenshots**
No screenshots here, this is a crash Houston

**Additional context**
I'm running this on Linux, some other people have reported that it's working fine on Windows.

**Comment by seasnail8169** [comment]
Im gonna close anything we are already aware of because its pretty useless, i would recommend only reporting small bugs which we may not have noticed, like a module not working or some smaller crash.

**Comment by Lovecrafts-Cat** [comment]
Having the same crash on Windows, happens the same way.
Here's the log just in case: https://hastebin.com/upeyedipuh.yaml
