### ISSUE TITLE
[Suggestion] Tracer Thiccness adjustable

### ISSUE THREAD

**Issue by Tokara1** [MeteorDevelopment/meteor-client#998]
**Describe the feature**
Make tracer thiccness adjustable bc in some cases the Thin tracers are hard to Spot 
( Dynamic, adjustable With slidebar )

**Screenshots**
N/A

**Additional info**
N/A

**Comment by StormyBytes** [comment]
Duplicate of #521

**Comment by Tokara1** [comment]
Oopsy
